### ISSUE TITLE
 TypeError: unbound method _dispatch_result() must be called with UrlRequest instance as first argument (got float instance instead)

### ISSUE THREAD

**Issue by andrew-azarov** [kivy/kivy#1289]
Dear Kivy guys,

I have URLrequest in clock interval (5 sec) and I occasionally get  TypeError: unbound method _dispatch_result() must be called with UrlRequest instance as first argument (got float instance instead)

How to fix this?
Seems like a dispatcher bug to me

```
Traceback (most recent call last):
   File "main_window.py", line 161, in <module>
     tradeApp().run()
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\app.py", line 600, in run
     runTouchApp()
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\base.py", line 454, in runTouchApp
     EventLoop.window.mainloop()
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\core\window\window_pygame.py", line 325, in mainloop
     self._mainloop()
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\core\window\window_pygame.py", line 231, in _mainloop
     EventLoop.idle()
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\base.py", line 294, in idle
     Clock.tick()
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\clock.py", line 370, in tick
     self._process_events()
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\clock.py", line 481, in _process_events
     if event.tick(self._last_tick) is False:
   File "E:\Downloads\Kivy-1.7.1-w32\kivy\kivy\clock.py", line 280, in tick
     ret = callback(self._dt)
 TypeError: unbound method _dispatch_result() must be called with TickerRequest instance as first argument (got float instance instead)
```

**Comment by tshirtman** [comment]
seems to happen to one of my apps from time to time, but hard to reproduce :/

**Comment by matham** [comment]
Just a thought, try to modify the code in urlrequest.py from 
```py
self._trigger_result = Clock.create_trigger(self._dispatch_result, 0)
```

to
```py
m = self._dispatch_result
Logger.debug('urlrequest method is None: {}'.format(m.__self__ is None))
self._trigger_result = Clock.create_trigger(m, 0)
```

And see in the cases where you get that exception whether `m.__self__` was `None` as I suspect it may be. Possibly because of inheriting from `Thread`. But it's just a guess.

**Comment by artyanikey** [comment]
Just got that on android deployment. Kivy version 1.10.0. I was in bad wi-fi area when it happened. Happened for the first time.

buildozer.spec:

requirements = kivy,pyopenssl
android.permissions = INTERNET
android.api = 24
android.minapi = 24
android.sdk = 24
android.ndk = 16b

I'll try to figure out how to reproduce.

**Comment by artyanikey** [comment]
Don't think it's wi-fi related actually as it happened after the request was successfully handled.

**Comment by Fak3** [comment]
One user just got the same error on android with kivy 1.10.0. Traceback:
```
   Traceback (most recent call last):
  File "/home/u1/.local/share/python-for-android/dists/unnamed_dist_2/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 723, in mainloop
  File "/home/u1/.local/share/python-for-android/dists/unnamed_dist_2/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
  File "/home/u1/.local/share/python-for-android/dists/unnamed_dist_2/private/lib/python2.7/site-packages/kivy/base.py", line 337, in idle
  File "/home/u1/.local/share/python-for-android/dists/unnamed_dist_2/private/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
  File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7769)
  File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7529)
  File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7450)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3294)
TypeError: unbound method _dispatch_result() must be called with UrlRequest instance as first argument (got float instance instead)
```
