### ISSUE TITLE
accessing ids inside canvas leads to a error

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#1709]
sample code and error

```


    from kivy.app import App
    from kivy.lang import Builder

    class ShowcaseApp(App):

        def build(self):
            return Builder.load_string('''
    BoxLayout
       Button
           canvas.after:
               Rectangle:
                   size: self.size
                   pos: but_bubles.pos
       Button:
           id: but_bubbles
    ''')

    if __name__ == '__main__':
        ShowcaseApp().run()

     python main.py
    [INFO   ] Kivy v1.8.0-dev
    [INFO   ] [Logger      ] Record log in /home/qua-non/.kivy/logs/kivy_13-12-15_42.txt
    [INFO   ] [Factory     ] 156 symbols loaded
    [DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
    [DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
    [DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
    [INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif
    [DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
    [DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
    [DEBUG  ] [App         ] Loading kv <./showcase.kv>
    [DEBUG  ] [App         ] kv <./showcase.kv> not found
    [DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
    [INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
    [WARNING] [WinPygame   ] Video: failed (multisamples=2)
    [WARNING] [WinPygame   ] trying without antialiasing
    [DEBUG  ] [Window      ] Display driver x11
    [DEBUG  ] [Window      ] Actual window size: 800x600
    [DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a8
    [DEBUG  ] [Window      ] Actual depth bits: 24
    [DEBUG  ] [Window      ] Actual stencil bits: 8
    [DEBUG  ] [Window      ] Actual multisampling samples: 0
    [INFO   ] [GL          ] OpenGL version <2.1 Mesa 9.1.3>
    [INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
    [INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ironlake Mobile >
    [INFO   ] [GL          ] OpenGL parsed version: 2, 1
    [INFO   ] [GL          ] Shading version <1.20>
    [INFO   ] [GL          ] Texture max size <8192>
    [INFO   ] [GL          ] Texture max units <16>
    [DEBUG  ] [Shader      ] Fragment compiled successfully
    [DEBUG  ] [Shader      ] Vertex compiled successfully
    [DEBUG  ] [ImagePygame ] Load </mnt/Data/code/kivy/kivy/data/glsl/default.png>
    [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
    [INFO   ] [Text        ] Provider: pygame
     Traceback (most recent call last):
       File "main.py", line 19, in <module>
         ShowcaseApp().run()
       File "/mnt/Data/code/kivy/kivy/app.py", line 709, in run
         root = self.build()
       File "main.py", line 16, in build
         ''')
      File "/mnt/Data/code/kivy/kivy/lang.py", line 1463, in load_string
        self._apply_rule(widget, parser.root, parser.root)
      File "/mnt/Data/code/kivy/kivy/lang.py", line 1613, in _apply_rule
        self._apply_rule(child, crule, rootrule)
      File "/mnt/Data/code/kivy/kivy/lang.py", line 1564, in _apply_rule
        rule.canvas_after, rootrule)
      File "/mnt/Data/code/kivy/kivy/lang.py", line 1746, in _build_canvas
        '{}: {}'.format(e.__class__.__name__, e))
    kivy.lang.BuilderException: Parser: File "<inline>", line 7:
    ...
          5:            Rectangle:
          6:                size: self.size
    >>    7:                pos: but_bubles.pos
          8:    Button:
          9:        id: but_bubbles
    ...
    BuilderException: Parser: File "<inline>", line 7:
    ...
          5:            Rectangle:
          6:                size: self.size
    >>    7:                pos: but_bubles.pos
          8:    Button:
          9:        id: but_bubbles
    ...
    NameError: name 'but_bubles' is not defined

```
##

**Comment by fekga** [comment]
I had the same issue, using the 'app' id works, everything else fails. The Canvas construction could happen after resolving ids.

**Comment by Olygrim** [comment]
I do not know what you want to do with your code, but i think i had the same issue (access to another id from a canvas) and the solution is pretty simple.

Just give the dynamique value to `Button`'s `pos` property (and the own dynamique value `pos` to update `Rectangle`'s `pos`):

```
BoxLayout:
    Button:
        pos: but_bubbles.pos
        canvas:
            Rectangle:
                size: self.size
                pos: self.pos
    Button:
        id: but_bubbles
```

**Comment by fekga** [comment]
I could do that and duplicate variables but isn't is a bit inconvenient?

**Comment by Olygrim** [comment]
In my code, i have not duplicate the variable (i think ;). The `pos` property of `Button` is different from the `pos` property of `Rectangle`.
I just bind the `but_bubbles`'s position to the position of the `Button` and then i bind the `Button`'s position to the position of the `Rectangle` (it is not automatically).

For something more complex like bind the `size` of the `Rectangle` with another widget, while uncoupling the `size` of the `Rectangle` with the size of the widget container, it may be more complicated (maybe use tshirtman's solution in this case)

_I have just started with kivy so i could be wrong & sorry for my bad english :)_

PS: The example is not great because we use a `BoxLayout` and in this case the widgets can not overlap (once again i think)

**Comment by bj0** [comment]
I just hit this, is there no workaround?  Only thing I can come up with is to store stuff in `app`, which I would rather not clutter up.

**Comment by FilipeMarch** [comment]
This works for me:
```
Button:
    my_color: (1,0,0,1)
    canvas.before:
        Color:
            rgba: self.my_color
        Rectangle:
            size: self.size
            pos: self.pos
```
In that case, the canvas is being built on a button, so using `self` will allow you to access anything declared on this button, including IDs.

The inconvenience comes in cases with multiple parents, but we are still able to find and use those properties and IDs.
```
BoxLayout:
    my_color: (1,0,0,1)
    BoxLayout:
         Button:
            canvas.before:
                Color:
                    rgba: self.parent.parent.my_color
                Rectangle:
                    size: self.size
                    pos: self.pos
```
I am not sure if there is a better solution than this. The button's parent is a BoxLayout. The BoxLayout's parent is another BoxLayout that contains the reference to `my_color`. So `self.parent.parent` allows you to access the properties/IDs declared by your grandfather.
