### ISSUE TITLE
the issue of  character encoding  in OSC

### ISSUE THREAD

**Issue by erhuabushuo** [kivy/kivy#1882]
Python Ver: Python3.3
Kivy Ver: 1.8.0

They are some issues of character encoding in kivy/lib/osc/OSC.py.

line 181
binary  = struct.pack(">%ds" % (OSCstringLength), next)

It should be a  bytes object.
##

**Comment by FeralBytes** [comment]
Full Traceback.  Basically to trigger this, just use the OSC lib in Kivy with Python 3. Any attempt to send a message will fail with this error.
```
Traceback (most recent call last):
   File "Service.py", line 25, in <module>
     Handler()
   File "Service.py", line 15, in __init__
     self.ping(data)
   File "Service.py", line 23, in ping
     osc.sendMsg('/some_api', ['ping', ], port=8887)
   File "/usr/lib/python3/dist-packages/kivy/lib/osc/oscAPI.py", line 130, in sendMsg
     outSocket.sendto( createBinaryMsg(oscAddress, dataArray),  (ipAddr, port))
   File "/usr/lib/python3/dist-packages/kivy/lib/osc/oscAPI.py", line 166, in createBinaryMsg
     m.append(x)
   File "/usr/lib/python3/dist-packages/kivy/lib/osc/OSC.py", line 84, in append
     binary = OSCArgument(argument)
   File "/usr/lib/python3/dist-packages/kivy/lib/osc/OSC.py", line 181, in OSCArgument
     binary  = struct.pack(">%ds" % (OSCstringLength), next)
 struct.error: argument for 's' must be a bytes object
```

**Comment by Sentient07** [comment]
The error won't be there if type s has been converted to bytes ('utf-8' encoding). PR for that,   https://github.com/kivy/kivy/pull/3114

**Comment by tshirtman** [comment]
since we moved to the bytes-based oscpy implementation, this can be closed.
