### ISSUE TITLE
TextInput crashes while using clipboard bubble

### ISSUE THREAD

**Issue by emanuele-f** [kivy/kivy#1945]
After opening clipboard bubble, keyboard doesn't close anymore.
Moreover, when closing application, it gives:

```
I/python  ( 4932): [INFO              ] [Clipboard   ] Provider: dummy(['clipboard_android'] ignored)
I/python  ( 4932): [INFO              ] [Base        ] Leaving application in progress...
I/python  ( 4932): Python for android ended.
W/dalvikvm( 4932): threadid=10: thread exiting with uncaught exception (group=0x4001d560)
E/AndroidRuntime( 4932): FATAL EXCEPTION: Thread-11
E/AndroidRuntime( 4932): java.lang.NoClassDefFoundError: android.content.ClipData
E/AndroidRuntime( 4932):    at org.renpy.android.SDLSurfaceView.nativeInit(Native Method)
E/AndroidRuntime( 4932):    at org.renpy.android.SDLSurfaceView.run(SDLSurfaceView.java:725)
E/AndroidRuntime( 4932):    at java.lang.Thread.run(Thread.java:1019)
E/AndroidRuntime( 4932): Caused by: java.lang.ClassNotFoundException: android.content.ClipData in loader dalvik.system.PathClassLoader[/data/app/org.emanuele.LyricsDL-2.apk]
E/AndroidRuntime( 4932):    at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
E/AndroidRuntime( 4932):    at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
E/AndroidRuntime( 4932):    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 4932):    ... 3 more
```

If specifing "use_bubble: False" it works correctly, but clipboard is obviously disabled.

android sdk 14
kivy 1.8.0
##

**Comment by ElliotGarbus** [comment]
reproducer is not longer attached (Link to dropbox not valid). Will be addressed in 3.0
