### ISSUE TITLE
Image.save() fails

### ISSUE THREAD

**Issue by trivedigaurav** [kivy/kivy#1974]
Calling Image.save() fails on kivy 1.8.1-dev fails with the following error:

File "/Library/Python/2.7/site-packages/kivy/core/image/**init**.py", line 743, in save
     return loader.save(filename, size[0], size[1], fmt, pixels, flipped)
   File "img_imageio.pyx", line 270, in kivy.core.image.img_imageio.ImageLoaderImageIO.save (kivy/core/image/img_imageio.c:2641)
 TypeError: save() takes exactly 5 positional arguments (6 given)

Complete log is available here: https://gist.github.com/trivedigaurav/9588688

**Comment by tukhfatov** [comment]
Still have same problem. 

 Traceback (most recent call last):
   File "camera2.py", line 73, in <module>
     MyApp().run()
   File "/usr/local/lib/python2.7/site-packages/kivy/app.py", line 792, in run
     runTouchApp()
   File "/usr/local/lib/python2.7/site-packages/kivy/base.py", line 481, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 381, in mainloop
     self._mainloop()
   File "/usr/local/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 287, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python2.7/site-packages/kivy/base.py", line 324, in idle
     self.dispatch_input()
   File "/usr/local/lib/python2.7/site-packages/kivy/base.py", line 309, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/local/lib/python2.7/site-packages/kivy/base.py", line 220, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-wNgsN7/kivy/kivy/_event.c:4552)
   File "/usr/local/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 645, in on_motion
     self.dispatch('on_touch_down', me)
   File "_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-wNgsN7/kivy/kivy/_event.c:4552)
   File "/usr/local/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 657, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-wNgsN7/kivy/kivy/_event.c:4552)
   File "/usr/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 284, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-wNgsN7/kivy/kivy/_event.c:4552)
   File "/usr/local/lib/python2.7/site-packages/kivy/uix/behaviors.py", line 93, in on_touch_down
     self.dispatch('on_press')
   File "_event.pyx", line 312, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-wNgsN7/kivy/kivy/_event.c:4506)
   File "/usr/local/lib/python2.7/site-packages/kivy/lang.py", line 1299, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 15, in <module>
   File "camera2.py", line 66, in TakePicture
     self.export_to_png(self.ids.camera, filename='test2.png')
   File "camera2.py", line 55, in export_to_png
     fbo.texture.save(filename, flipped = False)
   File "texture.pyx", line 981, in kivy.graphics.texture.Texture.save (/tmp/pip-build-wNgsN7/kivy/kivy/graphics/texture.c:10640)
   File "/usr/local/lib/python2.7/site-packages/kivy/core/image/__init__.py", line 743, in save
     return loader.save(filename, size[0], size[1], fmt, pixels, flipped)
   File "img_imageio.pyx", line 245, in kivy.core.image.img_imageio.ImageLoaderImageIO.save (/tmp/pip-build-wNgsN7/kivy/kivy/core/image/img_imageio.c:2568)
 TypeError: save() takes exactly 5 positional arguments (6 given)


How to solve??? I tried to add flipped parameter to static function, but unfortunately after app stopped with segmentation fault.

**Comment by trivedigaurav** [comment]
@tukhfatov  What platform are you running this on?

**Comment by tukhfatov** [comment]
@trivedigaurav Mac OS 10.10

**Comment by dessant** [comment]
@tukhfatov have you updated kivy to master?

**Comment by NorthIsUp** [comment]
This is currently happening for me with `Kivy==1.9.1` on OS X 10.11
