### ISSUE TITLE
Interactive Launcher fails on Python3

### ISSUE THREAD

**Issue by brousch** [kivy/kivy#1978]
The Interactive Launcher module works on Python 2.7 but fails on Python 3.3.

```
C:\Users\ben\Projects\playground>python playground\interactivelauncher\main.py
[INFO              ] Kivy v1.8.0
[INFO              ] [Logger      ] Record log in C:\Users\ben\.kivy\logs\kivy_1
4-03-18_4.txt
[INFO              ] [Factory     ] 157 symbols loaded
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=
Nones
[DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout
=60s
[DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout
=Nones
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_pygame, img
_gif (img_pil ignored)
[DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeo
ut=60s
[DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeou
t=3600s
 Traceback (most recent call last):
   File "playground\interactivelauncher\main.py", line 1, in <module>
     from kivy.interactive import InteractiveLauncher
   File "C:\Kivy-1.8.0-py3.3-win32\kivy\kivy\interactive.py", line 177, in <modu
le>
     class SafeMembrane(object):
 ValueError: 'safeIn' in __slots__ conflicts with class variable
```

**Comment by dessant** [comment]
The interactive launcher has been deprecated in https://github.com/kivy/kivy/commit/3f83ed2a7b7d463d6b721b737b1adc0ec30ea7af.

**Comment by iasingularity** [comment]
help....
**from kivy.interactive import InteractiveLauncher
from kivy.app import App
from kivy.uix.button import Button

class MyApp(App):
    def build(self):
        return Button(text='Hello Shell')

launcher = InteractiveLauncher(MyApp())
launcher.run()**


and it throws me an error because interactive launcher is outdated .... what can I do? Thank you

**Comment by tshirtman** [comment]
It's been deprecated for 4 years, and broken for a long time, i'd say it's a good time to rip it off.
