### ISSUE TITLE
Segmentation fault in ArchLinux ARM on Raspberry Pi

### ISSUE THREAD

**Issue by cioban** [kivy/kivy#2373]
I've tried to use Kivy stable and Kivy dev in Arch Linux ARM in Raspberry Pi and I got a error, 'OpenGL not available' and after, a segfault.
The compilation process was OK, and if I try to import OpenGL and pygame on python no errors occurs.
```
[root@alarmpi showcase]# python
Python 2.7.8 (default, Jul  3 2014, 23:17:22) 
[GCC 4.8.2 20131219 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenGL
>>> import pygame
>>> 
```

This is the error when I try to run the showcase example
```
[root@alarmpi showcase]# python main.py 
[INFO   ] Kivy v1.8.1-dev
[INFO   ] [Python      ] v2.7.8 (default, Jul  3 2014, 23:17:22) 
[GCC 4.8.2 20131219 (prerelease)]
[INFO   ] [Factory     ] 169 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_ffpyplayer, img_pil ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libpng warning: iCCP: known incorrect sRGB profile
[WARNING] [WinPygame   ] Video: failed (multisamples=2)
[WARNING] [WinPygame   ] trying without antialiasing
[ERROR  ] [Window      ] Unable to use pygame
[ERROR  ] [Window      ] The module raised an important error: 'OpenGL not available'
 Traceback (most recent call last):
   File "main.py", line 212, in <module>
     ShowcaseApp().run()
   File "/usr/lib/python2.7/site-packages/kivy/app.py", line 794, in run
     self.load_kv(filename=self.kv_file)
   File "/usr/lib/python2.7/site-packages/kivy/app.py", line 592, in load_kv
     root = Builder.load_file(rfilename)
   File "/usr/lib/python2.7/site-packages/kivy/lang.py", line 1663, in load_file
     return self.load_string(data, **kwargs)
   File "/usr/lib/python2.7/site-packages/kivy/lang.py", line 1741, in load_string
     widget = Factory.get(parser.root.name)()
   File "/usr/lib/python2.7/site-packages/kivy/uix/boxlayout.py", line 102, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/site-packages/kivy/uix/layout.py", line 63, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 285, in __init__
     EventLoop.ensure_window()
   File "/usr/lib/python2.7/site-packages/kivy/base.py", line 122, in ensure_window
     import kivy.core.window  # NOQA
   File "/usr/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1179, in <module>
     ), True)
   File "/usr/lib/python2.7/site-packages/kivy/core/__init__.py", line 65, in core_select_lib
     cls = cls()
   File "/usr/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 561, in __init__
     self.create_window()
   File "/usr/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 136, in create_window
     raise CoreCriticalException(e.message)
 kivy.core.CoreCriticalException: OpenGL not available
Segmentation fault
```

**Comment by derekstavis** [comment]
After merging PR #2581 it is working. This issue can be closed.
