### ISSUE TITLE
InterpolationSyntaxError after freezing with nuitka or cx_freeze on py3.3

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2409]
The app does not crash.

```python
[ERROR             ] [Core        ] error while reading localconfiguration
Traceback (most recent call last):
  File "C:\kivy_dev\test_app\kivy\config.py", line 586, in config
    Config.read(kivy_config_fn)
  File "C:\kivy_dev\test_app\kivy\config.py", line 356, in read
    for k, v in self.items(section):
  File "C:\kivy_dev\Python33\lib\ConfigParser.py", line 853, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "C:\kivy_dev\Python33\lib\ConfigParser.py", line 850, in <lambda>
    section, option, d[option], d)
  File "C:\kivy_dev\Python33\lib\ConfigParser.py", line 391, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\kivy_dev\Python33\lib\ConfigParser.py", line 437, in _interpolate_some
    raise InterpolationSyntaxError(
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%y-%m-%d_%_.txt'
[ERROR             ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "C:\kivy_dev\test_app\kivy\logger.py", line 205, in emit
    self._configure()
  File "C:\kivy_dev\test_app\kivy\logger.py", line 147, in _configure
    log_name = Config.get('kivy', 'log_name')
  File "C:\kivy_dev\test_app\kivy\config.py", line 388, in get
    value = PythonConfigParser.get(self, section, option, **kwargs)
  File "C:\kivy_dev\Python33\lib\ConfigParser.py", line 790, in get
    d)
  File "C:\kivy_dev\Python33\lib\ConfigParser.py", line 391, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\kivy_dev\Python33\lib\ConfigParser.py", line 437, in _interpolate_some
    raise InterpolationSyntaxError(
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%y-%m-%d_%_.txt'
[INFO              ] Kivy v1.8.1-dev
```

**Comment by dessant** [comment]
Cannot reproduce anymore with master.
