### ISSUE TITLE
Textinput: past/copy problems

### ISSUE THREAD

**Issue by nesergen** [kivy/kivy#2418]
The problems appear on the real device. I have 'ASUS memopad HD7' .
1) I typed the text in a text field. Further I try to insert a new letter into the text middle, but together with this letter the text which costs to the right of the cursor is inserted also. After clear the text field and type a letter inserting previouse part of text. Problem leaves after switch-off virtual keyboard.
There are link to the video:
http://www.youtube.com/attribution_link?a=sF-EMSwaLGA&u=/watch%3Fv%3DoP1o_NmiLVs%26feature%3Dem-upload_owner
2) I copy the text from one field, I insert it into another, but I receive unreadable symbols. I code all text in my program by Unicode.
There are link to the video:
http://www.youtube.com/attribution_link?a=sF-EMSwaLGA&u=/watch%3Fv%3D3bxy96n110w%26feature%3Dem-upload_owner
##

**Comment by picibucor** [comment]
same on win10, python3.4

**Comment by dessant** [comment]
@picibucor, have you compiled kivy yourself with msvc?

**Comment by dessant** [comment]
@picibucor, I'm copying text from one field to the next in kivycatalog win10, and there are no issues. Could you share a runnable example which reproduces your issue? Kivy version?

@KeyWeeUsr, have you also seen it on windows or just android?

**Comment by KeyWeeUsr** [comment]
@dessant The second video(issue): Checked now on windows(py2/py3) with sdl2 and master, checked even on android, custom launcher with master branch from 13042016  - nothing. Copied some cyrillic text from wikipedia because I don't have russian keyboard - maybe again only keyboard issue?

The first one however is quite alive on android. No such problems on windows.

**Comment by picibucor** [comment]
I've downloaded the wheel from:
http://www.lfd.uci.edu/~gohlke/pythonlibs/

Probably miss-clicked by the issue, as I use the shortcut for copy a text from textinput, it crashes.
Here's what  my log says:

> Traceback (most recent call last):
>    File "C:\Users\Mihaly\Documents\munka\CETA-Software\EZS-2G\main.py", line 1527, in <module>
>      EZS.run()
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\app.py", line 828, in run
>      runTouchApp()
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\base.py", line 487, in runTouchApp
>      EventLoop.window.mainloop()
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
>      self._mainloop()
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\core\window\window_sdl2.py", line 552, in _mainloop
>      self.modifiers):
>    File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
>    File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
>    File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\core\window\__init__.py", line 159, in _on_window_key_down
>      return self.dispatch('on_key_down', keycode, text, modifiers)
>    File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
>    File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
>    File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\uix\textinput.py", line 2336, in keyboard_on_key_down
>      self.copy()
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\uix\textinput.py", line 1676, in copy
>      return Clipboard.copy(self.selection_text)
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\core\clipboard\__init__.py", line 80, in copy
>      self._copy(data)
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\core\clipboard\__init__.py", line 99, in _copy
>      self.put(data, self._clip_mime_type)
>    File "C:\Users\Mihaly\AppData\Local\Programs\Python\Python35\lib\site-packages\kivy\core\clipboard\clipboard_winctypes.py", line 41, in put
>      msvcrt.wcscpy(c_wchar_p(pchData), text)
>  OSError: exception: access violation writing 0x0000000000000000

**Comment by dessant** [comment]
@picibucor, it is an unofficial wheel, not supported by us. I'm not aware of anyone from the team working on shipping a py3.5 wheel, the more likely outcome is that we will wait until mingwpy releases a version which supports py3.5, unless someone from the community steps in and makes kivy work with msvc.

**Comment by nesergen** [comment]
Hello !
I made this post 3.5 years ago, but as I see the problem is not solved. I bought a new tablet with Android 7.0, an error appears in it. I downloaded from PlayMarket KivyShowcase, in this program there is also an error. I tried to work with two built-in keyboards (SwiftKey, Gboard), on both of them there is an error. Unless on Gboard at use of an English layout it is shown much less often. I made a fresh video for illustration https://youtu.be/GqMhwFWR8ХА. With such a problem, the use of Kivy becomes problematic, a minor correction of the text leads to radical changes.
