### ISSUE TITLE
GIF python loader is broken for some GIF files ?

### ISSUE THREAD

**Issue by tito** [kivy/kivy#254]
The default loader.gif make the Python GIF stuck

```

[DEBUG  ] [Image_GIF   ] Load </home/tito/code/museotouch2/app/museolib/data/loader.gif>
[WARNING] [Image       ] Unable to load Image </home/tito/code/museotouch2/app/museolib/data/loader.gif>
 Traceback (most recent call last):
   File "main.py", line 775, in <module>
     MuseotouchApp().run()
   File "/home/tito/code/kivy/kivy/app.py", line 410, in run
     root = self.build()
   File "main.py", line 325, in build
     self.build_for_table()
   File "main.py", line 336, in build_for_table
     return self.build_selector()
   File "main.py", line 341, in build_selector
     return ExpoSelector(app=self)
   File "/home/tito/code/museotouch2/app/museolib/widgets/exposelector.py", line 31, in __init__
     self.load()
   File "/home/tito/code/museotouch2/app/museolib/widgets/exposelector.py", line 34, in load
     content = Image(source='loader.gif', anim_delay=.1)
   File "/home/tito/code/kivy/kivy/uix/image.py", line 197, in __init__
     self.texture_update()
   File "/home/tito/code/kivy/kivy/uix/image.py", line 210, in texture_update
     anim_delay=self.anim_delay)
   File "/home/tito/code/kivy/kivy/core/image/__init__.py", line 309, in __init__
     self.filename = arg
   File "/home/tito/code/kivy/kivy/core/image/__init__.py", line 506, in _set_filename
     mipmap=self._mipmap)
   File "/home/tito/code/kivy/kivy/core/image/__init__.py", line 241, in load
     im = loader(filename, **kwargs)
   File "/home/tito/code/kivy/kivy/core/image/__init__.py", line 138, in __init__
     self._data = self.load(filename)
   File "/home/tito/code/kivy/kivy/core/image/img_gif.py", line 55, in load
     im = GifDecoder(open(filename, 'rb').read())
   File "/home/tito/code/kivy/kivy/core/image/img_gif.py", line 280, in __init__
     self.fill()
   File "/home/tito/code/kivy/kivy/core/image/img_gif.py", line 362, in fill
     self_global_color_table_size)
   File "/home/tito/code/kivy/kivy/core/image/img_gif.py", line 489, in lzw_decode
     output_append(ord(string_table[code]))
 KeyError: 32
```

**Comment by yaki29** [comment]
When gif is included it takes too long to start the application and moreover the gif doesn't play at it's original speed and some of the gifs on cycle completion reruns back with background screen shown once.
Is there some built in function for it in kivy or is there any method to solve this problem.

**Comment by akshayaurora** [comment]
make sure you have Pillow installed otherwise the loading of gif would be slow

**Comment by yaki29** [comment]
I use Ubuntu 15.04 it already has Pillow installed.
It is showing "Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/lib/python2.7/dist-packages" on entering "pip install Pillow".
But still it hangs.

**Comment by akshayaurora** [comment]
Try to run your program like this::

KIVY_IMAGE=pil,sdl2 python main.py

See if this solves your issue.

**Comment by yaki29** [comment]
@akshayaurora It worked and even application gif didn't restart ... but they still run slower than when we run them through some image viewer. Could you please help me out in this as well.

**Comment by akshayaurora** [comment]
you can try setting `anim_delay` to your specific needed interval.

**Comment by yaki29** [comment]
It worked .... Thanks for your help
