### ISSUE TITLE
Touchring module: Cannot set cursor_size or cursor_offset in config.ini

### ISSUE THREAD

**Issue by Darkhand81** [kivy/kivy#2716]
When using the touchring module, setting `cursor_size` or `cursor_offset` in config.ini causes all subsequent Kivy apps to crash.  Tested on both a Windows machine and on a Raspberry Pi:

Windows log:

```
[INFO              ] Logger: Record log in C:\Users\Paul\.kivy\logs\kivy_14-12-01_0.txt
[INFO              ] Kivy v1.8.0
[DEBUG             ] Cache: register <kv.image> with limit=None, timeout=60s
[DEBUG             ] Cache: register <kv.atlas> with limit=None, timeout=Nones
[INFO              ] Image: Providers: img_tex, img_dds, img_pygame, img_gif (img_pil ignored)
[DEBUG             ] Cache: register <kv.texture> with limit=1000, timeout=60s
[DEBUG             ] Cache: register <kv.shader> with limit=1000, timeout=3600s
[INFO              ] Factory: 157 symbols loaded
[DEBUG             ] Cache: register <kv.lang> with limit=None, timeout=Nones
[DEBUG             ] App: Loading kv <C:\Users\Paul\Desktop\Kivy\kivy\examples\application\test.kv>
[INFO              ] Text: Provider: pygame
[DEBUG             ] Window: Ignored <egl_rpi> (import error)
[INFO              ] Window: Provider: pygame(['window_egl_rpi'] ignored)
[DEBUG             ] Window: Display driver windib
[DEBUG             ] Window: Actual window size: %dx%d
[DEBUG             ] Window: Actual color bits r%d g%d b%d a%d
[DEBUG             ] Window: Actual depth bits: %d
[DEBUG             ] Window: Actual stencil bits: %d
[DEBUG             ] Window: Actual multisampling samples: %d
[INFO              ] GL: OpenGL version <3.3.11672 Compatibility Profile Context>
[INFO              ] GL: OpenGL vendor <ATI Technologies Inc.>
[INFO              ] GL: OpenGL renderer <ATI Mobility Radeon HD 4650>
[INFO              ] GL: OpenGL parsed version: 3, 3
[INFO              ] GL: Shading version <3.30>
[INFO              ] GL: Texture max size <8192>
[INFO              ] GL: Texture max units <16>
[INFO              ] Shader: fragment shader: <Fragment shader was successfully compiled to run on hardware.>
[DEBUG             ] Shader: Fragment compiled successfully
[INFO              ] Shader: vertex shader: <Vertex shader was successfully compiled to run on hardware.>
[DEBUG             ] Shader: Vertex compiled successfully
[INFO              ] Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.
 >
[DEBUG             ] ImagePygame: Load <C:\Users\Paul\Desktop\Kivy\kivy\kivy\data\glsl\default.png>
[DEBUG             ] Modules: Start <touchring> with config {u'cursor_size': u'(10', u'show_cursor': u'true', u'scale': u'.2', u'10)': True, u'cursor_offset': u'(-10'}
[DEBUG             ] Atlas: Load <C:\Users\Paul\Desktop\Kivy\kivy\kivy\data\..\data\images\defaulttheme.atlas>
[DEBUG             ] Atlas: Need to load 1 images
[DEBUG             ] Atlas: Load <C:\Users\Paul\Desktop\Kivy\kivy\kivy\data\..\data\images\defaulttheme-0.png>
[DEBUG             ] ImagePygame: Load <C:\Users\Paul\Desktop\Kivy\kivy\kivy\data\..\data\images\defaulttheme-0.png>
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] OSC: using <thread> for socket
[DEBUG             ] Base: Create provider from mouse
[DEBUG             ] Base: Create provider from wm_touch
[DEBUG             ] Base: Create provider from wm_pen
[INFO              ] Base: Start application main loop
[INFO              ] GL: NPOT texture support is available
[INFO              ] Base: Leaving application in progress...
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "C:\Users\Paul\Desktop\Kivy\kivy\examples\application\app_with_kv.py", line 19, in <module>
[WARNING           ] stderr:     TestApp().run()
[WARNING           ] stderr:   File "C:\Users\Paul\Desktop\Kivy\kivy\kivy\app.py", line 792, in run
[WARNING           ] stderr:     runTouchApp()
[WARNING           ] stderr:   File "C:\Users\Paul\Desktop\Kivy\kivy\kivy\base.py", line 481, in runTouchApp
[WARNING           ] stderr:     EventLoop.window.mainloop()
[WARNING           ] stderr:   File "C:\Users\Paul\Desktop\Kivy\kivy\kivy\core\window\window_pygame.py", line 381, in mainloop
[WARNING           ] stderr:     self._mainloop()
[WARNING           ] stderr:   File "C:\Users\Paul\Desktop\Kivy\kivy\kivy\core\window\window_pygame.py", line 299, in _mainloop
[WARNING           ] stderr:     self.mouse_pos = x, self.system_size[1] - y
[WARNING           ] stderr:   File "properties.pyx", line 345, in kivy.properties.Property.__set__ (kivy\properties.c:3524)
[WARNING           ] stderr:   File "properties.pyx", line 377, in kivy.properties.Property.set (kivy\properties.c:3979)
[WARNING           ] stderr:   File "properties.pyx", line 431, in kivy.properties.Property.dispatch (kivy\properties.c:4547)
[WARNING           ] stderr:   File "C:\Users\Paul\Desktop\Kivy\kivy\kivy\modules\touchring.py", line 106, in _mouse_move
[WARNING           ] stderr:     size=size)
[WARNING           ] stderr:   File "vertex_instructions.pyx", line 665, in kivy.graphics.vertex_instructions.Rectangle.__init__ (kivy\graphics\vertex_instructions.c:18163)
[WARNING           ] stderr:   File "vertex_instructions.pyx", line 716, in kivy.graphics.vertex_instructions.Rectangle.size.__set__ (kivy\graphics\vertex_instructions.c:18809)
[WARNING           ] stderr: TypeError: a float is required
```

Raspberry Pi log:

```
[INFO              ] Logger: Record log in /home/pi/.kivy/logs/kivy_14-12-01_9.txt
[INFO              ] Image: Providers: img_tex, img_dds, img_pygame, img_gif (img_sdl2, img_ffpyplayer, img_pil ignored)
[INFO              ] Kivy v1.9.0-dev
[INFO              ] Python: v2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
[INFO              ] Factory: 172 symbols loaded
[INFO              ] Window: Provider: egl_rpi
[INFO              ] GL: OpenGL version <OpenGL ES 2.0>
[INFO              ] GL: OpenGL vendor <Broadcom>
[INFO              ] GL: OpenGL renderer <VideoCore IV HW>
[INFO              ] GL: OpenGL parsed version: 2, 0
[INFO              ] GL: Shading version <OpenGL ES GLSL ES 1.00>
[INFO              ] GL: Texture max size <2048>
[INFO              ] GL: Texture max units <8>
[INFO              ] Shader: fragment shader: <Compiled>
[INFO              ] Shader: vertex shader: <Compiled>
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] Text: Provider: pygame
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] ProbeSysfs: device match: /dev/input/event0
[INFO              ] HIDInput: Read event from </dev/input/event0>
[INFO              ] ProbeSysfs: device match: /dev/input/event1
[INFO              ] HIDInput: Read event from </dev/input/event1>
[INFO              ] Base: Start application main loop
[INFO              ] HIDMotionEvent: using <Logitech USB Optical Mouse>
[INFO              ] HIDMotionEvent: using <CHICONY HP Basic USB Keyboard>
[INFO              ] GL: NPOT texture support is available
[WARNING           ] stderr: Exception in thread Thread-1:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:   File "/usr/lib/python2.7/threading.py", line 505, in run
[WARNING           ] stderr:     self.__target(*self.__args, **self.__kwargs)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 589, in _thread_run
[WARNING           ] stderr:     process_as_mouse_or_keyboard(*infos)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 429, in process_as_mouse_or_keyboard
[WARNING           ] stderr:     process([point])
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 480, in process
[WARNING           ] stderr:     Window.mouse_pos = points[0]['x'] * Window.width, points[0]['y'] * Window.height
[WARNING           ] stderr:   File "kivy/properties.pyx", line 377, in kivy.properties.Property.__set__ (kivy/properties.c:4351)
[WARNING           ] stderr:   File "kivy/properties.pyx", line 409, in kivy.properties.Property.set (kivy/properties.c:4866)
[WARNING           ] stderr:   File "kivy/properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy/properties.c:5442)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1055, in kivy._event.EventObservers.dispatch (kivy/_event.c:10974)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/modules/touchring.py", line 108, in _mouse_move
[WARNING           ] stderr:     c.pos = pos[0] + cursor_offset[0], pos[1] - c.size[1] + cursor_offset[1]
[WARNING           ] stderr: TypeError: unsupported operand type(s) for +: 'float' and 'unicode'
[WARNING           ] stderr: 
[WARNING           ] stderr: Exception in thread Thread-2:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:   File "/usr/lib/python2.7/threading.py", line 505, in run
[WARNING           ] stderr:     self.__target(*self.__args, **self.__kwargs)
[INFO              ] Base: Leaving application in progress...
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 589, in _thread_run
[WARNING           ] stderr:     process_as_mouse_or_keyboard(*infos)
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 429, in process_as_mouse_or_keyboard
[WARNING           ] stderr:     process([point])
[WARNING           ] stderr:   File "textinput.py", line 59, in <module>
[WARNING           ] stderr:     runTouchApp(root)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 480, in process
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 484, in runTouchApp
[WARNING           ] stderr:     Window.mouse_pos = points[0]['x'] * Window.width, points[0]['y'] * Window.height
[WARNING           ] stderr:   File "kivy/properties.pyx", line 377, in kivy.properties.Property.__set__ (kivy/properties.c:4351)
[WARNING           ] stderr:     EventLoop.window.mainloop()
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 77, in mainloop
[WARNING           ] stderr:     self._mainloop()
[WARNING           ] stderr:   File "kivy/properties.pyx", line 409, in kivy.properties.Property.set (kivy/properties.c:4866)
[WARNING           ] stderr:   File "kivy/properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy/properties.c:5442)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 72, in _mainloop
[WARNING           ] stderr:     EventLoop.idle()
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1055, in kivy._event.EventObservers.dispatch (kivy/_event.c:10974)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 324, in idle
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/modules/touchring.py", line 108, in _mouse_move
[WARNING           ] stderr:     Clock.tick()
[WARNING           ] stderr:     c.pos = pos[0] + cursor_offset[0], pos[1] - c.size[1] + cursor_offset[1]
[WARNING           ] stderr: TypeError: unsupported operand type(s) for +: 'float' and 'unicode'
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 461, in tick
[WARNING           ] stderr: 
[WARNING           ] stderr:     usleep(1000000 * (sleeptime - sleep_undershoot))
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 267, in usleep
[WARNING           ] stderr:     _default_sleep(microseconds / 1000000.)
[WARNING           ] stderr: KeyboardInterrupt
```

My config.ini line:

```
[modules]
touchring = show_cursor=true,scale=.2,cursor_size=(10,10),cursor_offset=(-10,10)
```

All other options work correctly, just the two options that use tuples are causing trouble.  Setting negatives or positives results in the same error, as well as either adding a space or not (i.e `(10,10)` vs `(10, 10)`).

In addition, hard coding the values to get around the config problem works correctly in Windows, but even the hard coded values are ignored on the Pi.  That is probably a separate issue, however.
##

**Comment by contisegler** [comment]
Hi, this issue is quite old, so someone probably already found a solution. However, I just had the same problem and the following worked for me.

In the file \<kivy\>/modules/touchring.py I changed the lines 126 and 129 form
`if isinstance(cursor_size, str):`
`if isinstance(cursor_offset, str):`
to
`if (isinstance(cursor_size, str) or isinstance(cursor_size, unicode)):`
`if (isinstance(cursor_offset, str) or isinstance(cursor_offset, unicode)):`

Afterwards using `cursor_size=10x10,cursor_offset=-10x10` worked for me on linux desktop (fedora) as well as on Raspberry PI 3 (raspbian jessie).

**Comment by wolkstein** [comment]
hi,
have the same problem on rpi3 here. i do not want to change kivy modules because update trouble. i not like it to change touchring.py on each update. is there a method to set own cursor and options for them inside the kivy application?
/g
wolke
