### ISSUE TITLE
Python3, video_gstplayer.py, line 88: self.player.set_volume(self.volume)  AttributeError: 'NoneType' object has no attribute 'set_volume'

### ISSUE THREAD

**Issue by macropas** [kivy/kivy#2762]
![screenshot - 12202014 - 07 22 17 pm](https://cloud.githubusercontent.com/assets/7488502/5515683/8b19a2d6-887d-11e4-90c5-1cf3e121dabd.png)

Traceback (most recent call last):
   File "/home/johndoe/kivy-examples/demo/kivycatalog/main.py", line 166, in <module>
     KivyCatalogApp().run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 825, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 484, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_pygame.py", line 381, in mainloop
     self._mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 324, in idle
     Clock.tick()
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/usr/lib/python3/dist-packages/kivy/uix/video.py", line 177, in _do_video_load
     self._video.play()
   File "/usr/lib/python3/dist-packages/kivy/core/video/video_gstplayer.py
", line 88, in play
     self.player.set_volume(self.volume)
 AttributeError: 'NoneType' object has no attribute 'set_volume'
##

**Comment by dereks** [comment]
@macropas is correct, the package is missing softboy.mpg.

As a workaround, try this:

```bash
# Manually copy the file into place, since the package is missing it.
sudo bash
cd /usr/share/kivy-examples/widgets/
wget https://github.com/kivy/kivy/raw/master/examples/widgets/softboy.mpg
exit

# Now launch the demo
python /usr/share/kivy-examples/demo/kivycatalog/main.py
```

This puts an uncontrolled file **softboy.mpg** into **/usr/share/kivy-examples/demo/**, which is bad sysadmin practice. It will eventually conflict with the package when they fix it. You can just delete the file when you're done playing, or else make a copy of the demo's main.py and edit it to use a copy of softboy.mpg under your $HOME directory.
