### ISSUE TITLE
KivyCatalog: Selectors crash

### ISSUE THREAD

**Issue by matham** [kivy/kivy#2791]
Open kivycatalog, open Selectors, click on dropdown menu, and click on any of the options - results:

```
[INFO              ] Kivy v1.9.0-dev
[INFO              ] [Python      ] v2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_sdl2, img_ffpyplayer, img_pil ignored)
[INFO              ] [Text        ] Provider: pygame
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libpng warning: iCCP: known incorrect sRGB profile
GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <3.3.0>
[INFO              ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO              ] [GL          ] OpenGL renderer <GeForce 8600M GT/PCIe/SSE2>
[INFO              ] [GL          ] OpenGL parsed version: 3, 3
[INFO              ] [GL          ] Shading version <3.30 NVIDIA via Cg compiler>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Video       ] Provider: null(['video_pygst', 'video_ffmpeg', 'video_ffpyplayer', 'video_pyglet'] ignored)
[INFO              ] [GL          ] NPOT texture support is available
[ERROR             ] [filechooser ] win32file module is missing
[ERROR             ] [filechooser ] we cant check if a file is hidden or not
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Base        ] Start application main loop
libpng warning: iCCP: known incorrect sRGB profile
[INFO              ] [Context     ] Reloading graphics data...
[INFO              ] [Context     ] Reloading done in 0.1630s
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "G:\Python\dev2\kivy\examples\demo\kivycatalog\main.py", line 166, in <module>
     KivyCatalogApp().run()
   File "g:\python\dev2\kivy\kivy\app.py", line 825, in run
     runTouchApp()
   File "g:\python\dev2\kivy\kivy\base.py", line 484, in runTouchApp
     EventLoop.window.mainloop()
   File "g:\python\dev2\kivy\kivy\core\window\window_pygame.py", line 381, in mainloop
     self._mainloop()
   File "g:\python\dev2\kivy\kivy\core\window\window_pygame.py", line 285, in _mainloop
     EventLoop.idle()
   File "g:\python\dev2\kivy\kivy\base.py", line 327, in idle
     self.dispatch_input()
   File "g:\python\dev2\kivy\kivy\base.py", line 312, in dispatch_input
     post_dispatch_input(*pop(0))
   File "g:\python\dev2\kivy\kivy\base.py", line 278, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 619, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:6250)
   File "g:\python\dev2\kivy\kivy\uix\behaviors.py", line 140, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 615, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:6209)
   File "kivy\_event.pyx", line 1074, in kivy._event.EventObservers.dispatch (kivy\_event.c:11307)
   File "g:\python\dev2\kivy\kivy\uix\spinner.py", line 138, in <lambda>
     item.bind(on_release=lambda option: dp.select(option.text))
   File "g:\python\dev2\kivy\kivy\uix\dropdown.py", line 242, in select
     self.dispatch('on_select', data)
   File "kivy\_event.pyx", line 615, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:6209)
   File "kivy\_event.pyx", line 1074, in kivy._event.EventObservers.dispatch (kivy\_event.c:11307)
   File "g:\python\dev2\kivy\kivy\uix\spinner.py", line 146, in _on_dropdown_select
     self.is_open = False
   File "kivy\properties.pyx", line 377, in kivy.properties.Property.__set__ (kivy\properties.c:4351)
   File "kivy\properties.pyx", line 409, in kivy.properties.Property.set (kivy\properties.c:4866)
   File "kivy\properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy\properties.c:5442)
   File "kivy\_event.pyx", line 1056, in kivy._event.EventObservers.dispatch (kivy\_event.c:11032)
   File "g:\python\dev2\kivy\kivy\uix\spinner.py", line 153, in on_is_open
     self._dropdown.dismiss()
   File "g:\python\dev2\kivy\kivy\uix\dropdown.py", line 233, in dismiss
     self.dispatch('on_dismiss')
   File "kivy\_event.pyx", line 615, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:6209)
   File "kivy\_event.pyx", line 1074, in kivy._event.EventObservers.dispatch (kivy\_event.c:11307)
   File "g:\python\dev2\kivy\kivy\uix\spinner.py", line 142, in _toggle_dropdown
     self.is_open = not self.is_open
   File "kivy\properties.pyx", line 377, in kivy.properties.Property.__set__ (kivy\properties.c:4351)
   File "kivy\properties.pyx", line 409, in kivy.properties.Property.set (kivy\properties.c:4866)
   File "kivy\properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy\properties.c:5442)
   File "kivy\_event.pyx", line 1056, in kivy._event.EventObservers.dispatch (kivy\_event.c:11032)
   File "g:\python\dev2\kivy\kivy\uix\spinner.py", line 150, in on_is_open
     self._dropdown.open(self)
   File "g:\python\dev2\kivy\kivy\uix\dropdown.py", line 215, in open
     'Cannot open a dropdown list on a hidden widget')
 kivy.uix.dropdown.DropDownException: Cannot open a dropdown list on a hidden widget

```

**Comment by kived** [comment]
@matham Please test #2813 and see if it fixes this. I could duplicate this bug but not consistently. Kivy Catalog had an issue with reloading the content two seconds after changing screens, and I think this bug may have been triggered by having the right (wrong?) timing and clicking when the content was reloading - therefore the widget had no parent and couldn't get a parent window.
