### ISSUE TITLE
Kivy-1.9.0 crash on startup Win8-32bit (expected basestring got str)

### ISSUE THREAD

**Issue by victor-rene** [kivy/kivy#2870]
This happened after migrating a project from desktop PC to laptop. Did a git pull + make force.

    C:\dev\project\ld-shooter>"C:\dev\program\kivy_dev\kivy.bat" "main.pyx"
    botstrapping Kivy @ C:\dev\program\kivy_dev\
    Setting Environment Variables:
    #################################
    GST_REGISTRY
    C:\dev\program\kivy_dev\gstreamer\registry.bin
    ---------------
    GST_PLUGIN_PATH:
    C:\dev\program\kivy_dev\gstreamer\lib\gstreamer-1.0
    ---------------
    PATH:
    C:\dev\program\kivy_dev\;C:\dev\program\kivy_dev\Python27;C:\dev\program\kivy_de
    v\tools;C:\dev\program\kivy_dev\Python27\Scripts;C:\dev\program\kivy_dev\gstream
    er\bin;C:\dev\program\kivy_dev\MinGW\bin;C:\Python27\;C:\Python27\Scripts;C:\Pro
    gram Files\Broadcom\Broadcom 802.11 Network Adapter\Driver;;C:\Program Files\Int
    el\TXE Components\TCS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C
    :\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\TXE Components
    \DAL\;C:\Program Files\Intel\TXE Components\IPT\;C:\Program Files\Microsoft SQL
    Server\110\Tools\Binn\;C:\Program Files\Microsoft SDKs\TypeScript\1.0\;C:\Progra
    m Files\Microsoft SQL Server\120\Tools\Binn\
    ----------------------------------
    PYTHONPATH:
    C:\dev\program\kivy_dev\kivy;
    ----------------------------------
    ##################################
    done bootstraping kivy...have fun!\n
    running "python.exe "main.pyx"" \n
    [INFO              ] [Logger      ] Record log in C:\Users\Victor\.kivy\logs\kiv
    y_15-01-20_8.txt
    [INFO              ] Kivy v1.9.0-dev
    [INFO              ] [Python      ] v2.7.6 (default, Nov 10 2013, 19:24:18) [MSC
     v.1500 32 bit (Intel)]
    [INFO              ] [Factory     ] 173 symbols loaded
     Traceback (most recent call last):
       File "main.pyx", line 30, in <module>
         from kivy.app import App
       File "C:\dev\program\kivy_dev\kivy\kivy\app.py", line 316, in <module>
         from kivy.base import runTouchApp, stopTouchApp
       File "C:\dev\program\kivy_dev\kivy\kivy\base.py", line 380, in <module>
         EventLoop = EventLoopBase()
       File "_event.pyx", line 186, in kivy._event.EventDispatcher.__cinit__ (kivy\_
    event.c:3605)
     TypeError: Expected basestring, got str
    Press any key to continue . . .

We've seen this before, I'm investigating.

**Comment by victor-rene** [comment]
Same as last time. Upgrading cython, rebuilding fixed it.
