### ISSUE TITLE
Effects scroll exception

### ISSUE THREAD

**Issue by matham** [kivy/kivy#2935]
Got this when someone was scrolling in my app. I could not make it happen when I tried scrolling directly.

```
Traceback (most recent call last):
  File "C:\py278_x64\libs\forced_choice\forced_choice\main.py", line 244, in run_app
    app.run()
  File "C:\py278_x64\Python\lib\site-packages\kivy\app.py", line 824, in run
    runTouchApp()
  File "C:\py278_x64\Python\lib\site-packages\kivy\base.py", line 484, in runTouchApp
    EventLoop.window.mainloop()
  File "C:\py278_x64\Python\lib\site-packages\kivy\core\window\window_pygame.py", line 381, in mainloop
    self._mainloop()
  File "C:\py278_x64\Python\lib\site-packages\kivy\core\window\window_pygame.py", line 285, in _mainloop
    EventLoop.idle()
  File "C:\py278_x64\Python\lib\site-packages\kivy\base.py", line 327, in idle
    self.dispatch_input()
  File "C:\py278_x64\Python\lib\site-packages\kivy\base.py", line 312, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\py278_x64\Python\lib\site-packages\kivy\base.py", line 271, in post_dispatch_input
    wid.dispatch('on_touch_move', me)
  File "kivy\_event.pyx", line 701, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:6962)
  File "C:\py278_x64\Python\lib\site-packages\kivy\uix\scrollview.py", line 671, in on_touch_move
    if self.dispatch('on_scroll_move', touch):
  File "kivy\_event.pyx", line 701, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:6962)
  File "C:\py278_x64\Python\lib\site-packages\kivy\uix\scrollview.py", line 680, in on_scroll_move
    if self.dispatch_children('on_scroll_move', touch):
  File "kivy\_event.pyx", line 710, in kivy._event.EventDispatcher.dispatch_children (kivy\_event.c:7371)
  File "kivy\_event.pyx", line 706, in kivy._event.EventDispatcher.dispatch_generic (kivy\_event.c:7163)
  File "kivy\_event.pyx", line 710, in kivy._event.EventDispatcher.dispatch_children (kivy\_event.c:7371)
  File "kivy\_event.pyx", line 706, in kivy._event.EventDispatcher.dispatch_generic (kivy\_event.c:7163)
  File "kivy\_event.pyx", line 710, in kivy._event.EventDispatcher.dispatch_children (kivy\_event.c:7371)
  File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch_generic (kivy\_event.c:7130)
  File "kivy\_event.pyx", line 701, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:6962)
  File "C:\py278_x64\Python\lib\site-packages\kivy\uix\scrollview.py", line 704, in on_scroll_move
    self.effect_x.update(touch.x)
  File "C:\py278_x64\Python\lib\site-packages\kivy\effects\scroll.py", line 116, in update
    self.displacement += abs(val - self.history[-1][1])
IndexError: list index out of range
```

**Comment by matham** [comment]
I can replicate it now with the following code:

```py
from kivy.lang import Builder
from kivy.app import runTouchApp

kv = '''
ScrollView:
    scroll_type: ['bars', 'content']
    bar_width: 10
    GridLayout:
        padding: 40
        size_hint: None, None
        size: 2048, 1024
        rows: 1
        ScrollView:
            scroll_type: ['bars', 'content']
            bar_width: 10
            Label:
                size_hint: None, None
                size: 2048, 1024
        Label
'''
runTouchApp(Builder.load_string(kv))
```

**Comment by matham** [comment]
In general, it's really frustrating try to scroll the inner scrollview horizontally by dragging the bar. The moment you're off the bar, even if you're on the same height as the bar, it thinks you're dragging by content, when it should still be dragging by bar.

**Comment by bgschaid** [comment]
Just wanted to open an issue on this but found this issue (seems that this still happens)

Are there any plans to fix this 

As far as I can tell the problem is that the start-method is never called (which initializes self.history in the parent-class). But why that is is above my pay-grade

Simply catching the exception fixes this (there are no effects but I can live with that)

BTW: once self.history was "filled" by another scrolling it doesn't fail anymore

[scroll.py.patch.txt](https://github.com/kivy/kivy/files/5950165/scroll.py.patch.txt)

**Comment by leiniar1234** [comment]
> 
> 
> Just wanted to open an issue on this but found this issue (seems that this still happens)
> 
> Are there any plans to fix this
> 
> As far as I can tell the problem is that the start-method is never called (which initializes self.history in the parent-class). But why that is is above my pay-grade
> 
> Simply catching the exception fixes this (there are no effects but I can live with that)
> 
> BTW: once self.history was "filled" by another scrolling it doesn't fail anymore
> 
> [scroll.py.patch.txt](https://github.com/kivy/kivy/files/5950165/scroll.py.patch.txt)

hello, i ran into this issues recently, can you please explain how to apply the patch? i am quite new to programming and this is a issues i hardly found info about

**Comment by bgschaid** [comment]
> > Just wanted to open an issue on this but found this issue (seems that this still happens)
> > Are there any plans to fix this
> > As far as I can tell the problem is that the start-method is never called (which initializes self.history in the parent-class). But why that is is above my pay-grade
> > Simply catching the exception fixes this (there are no effects but I can live with that)
> > BTW: once self.history was "filled" by another scrolling it doesn't fail anymore
> > [scroll.py.patch.txt](https://github.com/kivy/kivy/files/5950165/scroll.py.patch.txt)
> 
> hello, i ran into this issue recently, can you please explain how to apply the patch? i am quite new to programming and this is a issue i hardly found info about

If you haven't used the patch utility then it is easiest to apply the patch by hand: open the file listed on top of the file (probably without the venv in the path. But you find the location by looking at the stacktrace of your failure). Got to approximately line 111 and look for the lines with the "-" i nfron of them. Replace them with the lines with the "+" (without the + obviously)

**Comment by CrawfishPress** [comment]
Probably this is a low-priority, but I'll observe I'm running into it also, on a PC. (Ubuntu 20.04/Python 3.8.3/Kivy 2.0.0)
```
    """
    Source: https://stackoverflow.com/questions/35626320/kivy-image-scrolling
    """
    from kivy.app import App
    from kivy.uix.image import Image
    from kivy.uix.scrollview import ScrollView
    from kivy.core.window import Window

    class TutorialApp(App):
        def build(self):

            some_img = Image(source='/home/data/map/Map_07C.jpg', size_hint=(None, None),
                             keep_ratio=True, size=(Window.width * 2, Window.height * 2))
            sv = ScrollView(size=Window.size, bar_width=50,
                            scroll_type=['bars', 'content'], effect_cls='ScrollEffect')
            sv.add_widget(some_img)

            return sv

    if __name__ == "__main__":
        TutorialApp().run()
```
But hey,  no problem, I'll just tell the client, "Every time you run this app, be sure to click in the center, _before_ daring to use the scrollbars". :)
