### ISSUE TITLE
Textinput issue with unfocus / android

### ISSUE THREAD

**Issue by tito** [kivy/kivy#2936]
Here is a traceback i have by navigating between textinput and return key (escape):

```
I/python  (14720): [INFO              ] [Base        ] Leaving application in progress...
I/python  (14720):  Traceback (most recent call last):
I/python  (14720):    File "main.py", line 14, in <module>
I/python  (14720):    File "kivy/app.py", line 824, in run
I/python  (14720):    File "kivy/base.py", line 484, in runTouchApp
I/python  (14720):    File "kivy/core/window/window_pygame.py", line 381, in mainloop
I/python  (14720):    File "kivy/core/window/window_pygame.py", line 285, in _mainloop
I/python  (14720):    File "kivy/base.py", line 327, in idle
I/python  (14720):    File "kivy/base.py", line 312, in dispatch_input
I/python  (14720):    File "kivy/base.py", line 278, in post_dispatch_input
I/python  (14720):    File "kivy/_event.pyx", line 701, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6967)
I/python  (14720):    File "kivy/uix/behaviors.py", line 140, in on_touch_up
I/python  (14720):    File "kivy/_event.pyx", line 697, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6926)
I/python  (14720):    File "kivy/_event.pyx", line 1164, in kivy._event.EventObservers.dispatch (kivy/_event.c:11984)
I/python  (14720):    File "kivy/_event.pyx", line 1088, in kivy._event.EventObservers._dispatch (kivy/_event.c:11559)
I/python  (14720):    File "kivy/uix/textinput.py", line 1112, in _handle_released
I/python  (14720):    File "kivy/uix/textinput.py", line 1258, in _show_cut_copy_paste
I/python  (14720):  AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by tito** [comment]
@akshayaurora @matham ?
