### ISSUE TITLE
SDL2 window crash on (atleast) Windows

### ISSUE THREAD

**Issue by mgejke** [kivy/kivy#2954]
Run the following
```python
from kivy.app import App
from kivy.uix.label import Label
class TestApp(App):
    def build(self):
        return Label(text='Use scroll wheel without having the mouse touch the kivy window first')
TestApp().run()
```
The new window gets focus, without touching the window with the mousepointer, scroll the scrollwheel. 
Result:
```
 Traceback (most recent call last):
   File "dbg.py", line 11, in <module>
     TestApp().run()
   File "C:\dev\python\kivy\kivy\kivy\app.py", line 824, in run
     runTouchApp()
   File "C:\dev\python\kivy\kivy\kivy\base.py", line 484, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\dev\python\kivy\kivy\kivy\core\window\window_sdl2.py", line 478, in mainloop
     self._mainloop()
   File "C:\dev\python\kivy\kivy\kivy\core\window\window_sdl2.py", line 315, in _mainloop
     self._mouse_x, self._mouse_y, btn, self.modifiers)
 AttributeError: 'WindowSDL' object has no attribute '_mouse_x'
```
_mouse_x and _mouse_y aren't set, should probably just be set to 
self._mouse_x = x
self._mouse_y = y
as in the mousebutton* or mousemotion cases.

**Comment by kived** [comment]
Please test with #3066
