### ISSUE TITLE
no __self__ on EventDispatcher

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#3105]
I tried to use touch.grab(self) in method off an EventDispatcher, to get updates about this touches (interaction started by a widget, but managed by another EventDispatcher), i get a crash at dispatch time.

I think either i should get an error when i grab the touch, or the dispatching should happen correctly. Last time i had this issue a discussion ensued about various possible solutions:
- moving `__self__` to EventDispatcher
- make class_instance try weakref.ref(class_instance) if it cannot find `__self__`
- get class_instance.proxy_ref and only then create a new ref

Opinions/solutions welcome :)
##

**Comment by KeyWeeUsr** [comment]
@tshirtman I know it's an old thread, but could you perhaps paste some snippet if the issue still persists, please? If not for the fix, then to create a test/docs.

**Comment by tshirtman** [comment]
Not sure what exactly i wanted to do, but here is a simple (and quite artificial) example showing the issue:

```python
from kivy.app import App
from kivy.lang import Builder


KV = '''
Widget:
    on_touch_down: app.manage_touch(args[1])
'''

class TouchGraber(App):
    def build(self):
        return Builder.load_string(KV)

    def manage_touch(self, touch):
        touch.grab(self)

    def on_touch_move(self, touch):
        if touch.grab_current is self:
            print("managed this touch")
        else:
            print("lolwhat?")

    def on_touch_up(self, touch):
        if touch.grab_current is self:
            print("ok, ungrabbing")
            touch.ungrab(self)
        else:
            print("seriously, wtf?")


if __name__ == '__main__':
    TouchGraber().run()
```

and here is the output

```
[INFO   ] [Logger      ] Record log in /home/gabriel/.kivy/logs/kivy_17-10-09_0.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-4b77ede, 20170807
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 17.0.7>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "test_grap.py", line 33, in <module>
     TouchGraber().run()
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/app.py", line 827, in run
     runTouchApp()
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 660, in mainloop
     self._mainloop()
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 340, in idle
     self.dispatch_input()
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 325, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/base.py", line 231, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (/tmp/pip-fYYBEy-build/kivy/_event.c:8191)
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1189, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (/tmp/pip-fYYBEy-build/kivy/_event.c:8191)
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1205, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (/tmp/pip-fYYBEy-build/kivy/_event.c:8146)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (/tmp/pip-fYYBEy-build/kivy/_event.c:14035)
   File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch (/tmp/pip-fYYBEy-build/kivy/_event.c:12816)
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 3, in <module>
   File "test_grap.py", line 16, in manage_touch
     touch.grab(self)
   File "/home/gabriel/.virtualenvs/kivy/local/lib/python2.7/site-packages/kivy/input/motionevent.py", line 330, in grab
     class_instance = weakref.ref(class_instance.__self__)
 AttributeError: 'TouchGraber' object has no attribute '__self__'
```

The easiest solution is probably to tighten the requirements on `MotionEvent.grab` parameter, considering this doesn't make much sense, but i think there may be legitimate use cases for this, if you want for example to delegate touches from a few widgets to a common controller, which would use properties to communicate it's updated state to widgets or other parts of the system.

**Comment by pythonic64** [comment]
Seems solved by https://github.com/kivy/kivy/pull/6448 by moving __self__ to `EventDispatcher`.
