### ISSUE TITLE
[android] https not supported in urllib2

### ISSUE THREAD

**Issue by relet** [kivy/kivy#323]
Hi. I get the error message 

```
11-23 12:05:31.204: INFO/python(8200):  urllib2.URLError: <urlopen error unknown url type: https>
```

When trying to open (or being redirected to) HTTPS URLs. Usually that means that urllib2 has been compiled without SSL support. Is that something that can be fixed in the kivy release?

**Comment by MichaelCurrie** [comment]
Hi @tito, I'm having this problem with the following code on Android:

```
import json

try:
    # For Python 3.x
    from urllib.request import urlopen
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import urlopen

settings_url = 'https://www.dropbox.com/s/rwiud4qbhaudw28/settings.json?dl=1'

response = urlopen(settings_url)
settings_bytes = response.read()
settings_string = settings_bytes.decode('utf-8')
settings_dict = json.loads(settings_string)
```

Here's the error I get from my logcat:

```
I/python  (12455): Traceback (most recent call last):

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/app/main.py", line 12, in <module>

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/app/lanki.py", line 44, in <module>

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/app/lanki.py", line 36, in __init__

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/urllib2.py", line 126, in urlopen

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/urllib2.py", line 394, in open

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/urllib2.py", line 417, in _open

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/urllib2.py", line 372, in _call_chain

I/python  (12455):   File "/home/ubuntu/github/Lanki/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/urllib2.py", line 1232, in unknown_open

I/python  (12455): urllib2.URLError: <urlopen error unknown url type: https>

I/python  (12455): Python for android ended.

I/art     (12455): System.exit called, status: 0
```


Am I supposed to add `-m "openssl kivy" somewhere?  I run the line `buildozer --verbose android debug` to create my Android APK file.

**Comment by polopolopolopolo** [comment]
I know this issue is old but it's still referenced by google so i'll give a solution i found after being stucked on this problem...  
Just add openssl to your Application requirements in buildozer.spec.
Then type ```buildozer clean``` it's fine.
