### ISSUE TITLE
Android application exits prematurely

### ISSUE THREAD

**Issue by mfzl** [kivy/kivy#3234]
Logcat says I'm missing a text provider. I've installed all dependencies sdl__, sdl2__, pygame and it works fine on the Linux desktop.

Below is the output from logcat:

```
[INFO              ] [Logger      ] Record log in /data/data/org.test.myapp/files/.kivy/logs/kivy_15-04-05_1.txt
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v2.7.2 (default, Apr  5 2015, 02:29:28) 
[GCC 4.8]
[INFO              ] [Factory     ] 173 symbols loaded
k: Checking for images newer than 1428070183259
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL          ] [Text        ] Unable to find any valuable Text provider at all!
sdl2 - ImportError: No module named _text_sdl2
  File "python/kivy/hello2/.buildozer/android/app/lib/python2.7/site-packages/kivy/core/__init__.py", line 57, in core_select_lib
  File "python/kivy/hello2/.buildozer/android/app/lib/python2.7/site-packages/kivy/core/text/text_sdl2.py", line 12, in <module>
pil - ImportError: cannot import name _imaging
  File "python/kivy/hello2/.buildozer/android/app/lib/python2.7/site-packages/kivy/core/__init__.py", line 57, in core_select_lib
  File "python/kivy/hello2/.buildozer/android/app/lib/python2.7/site-packages/kivy/core/text/text_pil.py", line 8, in <module>
  File "python/kivy/hello2/.buildozer/android/app/lib/python2.7/site-packages/PIL/Image.py", line 63, in <module>
[CRITICAL          ] [App         ] Unable to get a Text provider, abort.
WIN DEATH: Window{10848a89 u0 org.test.myapp/org.renpy.android.PythonActivity}
Force-removing child win Window{124152af u0 SurfaceView} from container Window{10848a89 u0 org.test.myapp/org.renpy.android.PythonActivity}
Failed looking up window
java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@199aea8e does not exist
    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8539)
    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8530)
    at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1142)
    at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
WIN DEATH: null
Process 24074 exited cleanly (1)
```
##

**Comment by dessant** [comment]
Were you able to sort this out?
