### ISSUE TITLE
kivy-examples package broken

### ISSUE THREAD

**Issue by inclement** [kivy/kivy#3253]
It's reported at https://groups.google.com/forum/#!topic/kivy-users/hSyITNXQyb0 that the kivy-examples package doesn't currently work on Ubuntu.

**Comment by thopiekar** [comment]
Need a more detailed output, eg. a commandline output, and more important, which PPA was used.

**Comment by TimoKramer** [comment]
I tried to run the kivycatalog and got this error:

Traceback (most recent call last):
   File "main.py", line 191, in <module>
     KivyCatalogApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 539, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/video.py", line 177, in _do_video_load
     self._video.play()
   File "/usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py", line 88, in play
     self.player.set_volume(self.volume)
 AttributeError: 'NoneType' object has no attribute 'set_volume'

**Comment by TimoKramer** [comment]
same when running python3 kvrun.py app_logo.kv when I push the button

 Traceback (most recent call last):
   File "kvrun.py", line 35, in <module>
     KvApp(filename=sys.argv[1]).run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 539, in mainloop
     self._mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 330, in idle
     self.dispatch_input()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 221, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
   File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 904, in on_motion
     self.dispatch('on_touch_down', me)
   File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
   File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 920, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
   File "/usr/lib/python3/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
   File "/usr/lib/python3/dist-packages/kivy/uix/behaviors.py", line 134, in on_touch_down
     self._do_press()
   File "/usr/lib/python3/dist-packages/kivy/uix/behaviors.py", line 111, in _do_press
     self.state = 'down'
   File "properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4543)
   File "properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5025)
   File "properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5641)
   File "_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:11690)
   File "_event.pyx", line 1050, in kivy._event.EventObservers._dispatch (kivy/_event.c:10705)
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1477, in call_fn
     setattr(element, key, e_value)
   File "weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1218)
   File "properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4543)
   File "properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5025)
   File "properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5641)
   File "_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:11690)
   File "_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11029)
   File "/usr/lib/python3/dist-packages/kivy/uix/video.py", line 183, in on_play
     return self.on_state(instance, value)
   File "/usr/lib/python3/dist-packages/kivy/uix/video.py", line 194, in on_state
     self._video.play()
   File "/usr/lib/python3/dist-packages/kivy/core/video/video_gstplayer.py", line 88, in play
     self.player.set_volume(self.volume)

**Comment by thopiekar** [comment]
Same here. Looks like there is something missing for the gstreamer player. Do we have a specific gstreamer example?

```
thopiekar@home:~$ python /usr/share/kivy-examples/kv/kvrun.py /usr/share/kivy-examples/kv/app_logo.kv 
[INFO   ] [Logger      ] Record log in /home/thopiekar/.kivy/logs/kivy_15-06-06_3.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 175 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.5.2>
[INFO   ] [GL          ] OpenGL vendor <nouveau>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on NVAA>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <18>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [VideoGstplayer] Using Gstreamer 1.4.5.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [GL          ] Unpack subimage support is available
[ERROR  ] [Image       ] Error reading file /home/tito/code/pymt/examples/apps/videoplayer/softboy.mpg
[INFO   ] [Base        ] Start application main loop
FPS: 0.0000 (real draw: 0)
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/usr/share/kivy-examples/kv/kvrun.py", line 35, in <module>
     KvApp(filename=sys.argv[1]).run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 543, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 330, in idle
     self.dispatch_input()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 221, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 917, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 933, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/behaviors.py", line 134, in on_touch_down
     self._do_press()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/behaviors.py", line 111, in _do_press
     self.state = 'down'
   File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4680)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5203)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5852)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12152)
   File "kivy/_event.pyx", line 1050, in kivy._event.EventObservers._dispatch (kivy/_event.c:11095)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1477, in call_fn
     setattr(element, key, e_value)
   File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1189)
   File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4680)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5203)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5852)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12152)
   File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11451)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/video.py", line 183, in on_play
     return self.on_state(instance, value)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/video.py", line 194, in on_state
     self._video.play()
   File "/usr/lib/python2.7/dist-packages/kivy/core/video/video_gstplayer.py", line 88, in play
     self.player.set_volume(self.volume)
 AttributeError: 'NoneType' object has no attribute 'set_volume'
```

**Comment by thopiekar** [comment]
Haha! The video path is hardcoded :laughing: 

```
[ERROR  ] [Image       ] Error reading file /home/tito/code/pymt/examples/apps/videoplayer/softboy.mpg
```

**Comment by thopiekar** [comment]
Using another path fixes the problem :smile:

**Comment by mondayrain** [comment]
@thopiekar Has this been fixed? If not, I would like to take this up :)

**Comment by thopiekar** [comment]
@mondayrain I still see it in master: https://github.com/kivy/kivy/blob/master/examples/kv/app_logo.kv#L4
Go for it :dancer:

**Comment by dereks** [comment]
I don't know why it would still show up in master; the PPA package uses the following path:

```
/usr/share/kivy-examples/widgets/softboy.mpg
```

Maybe there is a Pull Request with this fix?

Unfortunately, the PPA is completely missing the file "softboy.mpg", so the same error still occurs... but it is due to a missing file, not a path pointing under /home/tito/code/.

See also: https://github.com/kivy/kivy/issues/2762 . There is a workaround posted there for the missing file (just d/l it RAW from github).

**Comment by theaverageguy** [comment]
Is this fixed ?
