### ISSUE TITLE
Register all folders recursively under default font paths

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3270]
Fonts grouped in subdirectories under default font paths are not found, for example when the font file is at  `/usr/share/fonts/truetype/msttcorefonts/FontName.ttf`:

```python
from kivy.app import App
from kivy.uix.button import Button


class TestApp(App):
    def build(self):
        return Button(font_name='FontName')

if __name__ == '__main__':
    TestApp().run()
```

```python
 Traceback (most recent call last):
   File "/home/vix/dev/prs/main/test/test_11.py", line 20, in <module>
     TestApp().run()
   File "/home/vix/dev/prs/kivy/kivy/app.py", line 824, in run
     runTouchApp()
   File "/home/vix/dev/prs/kivy/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/vix/dev/prs/kivy/kivy/core/window/window_sdl2.py", line 539, in mainloop
     self._mainloop()
   File "/home/vix/dev/prs/kivy/kivy/core/window/window_sdl2.py", line 300, in _mainloop
     EventLoop.idle()
   File "/home/vix/dev/prs/kivy/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/home/vix/dev/prs/kivy/kivy/uix/label.py", line 267, in texture_update
     self._label.refresh()
   File "/home/vix/dev/prs/kivy/kivy/core/text/__init__.py", line 614, in refresh
     self.resolve_font_name()
   File "/home/vix/dev/prs/kivy/kivy/core/text/__init__.py", line 257, in resolve_font_name
     raise IOError('Label: File %r not found' % fontname)
 OSError: Label: File 'FontName.ttf' not found
```

**Comment by dessant** [comment]
@akshayaurora, i think you had a branch with a fix for this.

**Comment by dessant** [comment]
@akshayaurora ping.
