### ISSUE TITLE
ObservableDict AttributeError

### ISSUE THREAD

**Issue by matham** [kivy/kivy#3280]
Example:

```py
>>> from kivy.properties import ObservableDict
>>> d1 = ObservableDict(None, None, {'abc': 5})
>>> d1.abc
5
>>> d1.cheese
 Traceback (most recent call last):
   File "<input>", line 1, in <module>
   File "kivy\properties.pyx", line 720, in kivy.properties.ObservableDict.__getattr__ (kivy\properties.c:10911)
     super(ObservableDict, self).__getattr__(attr))
 AttributeError: 'super' object has no attribute '__getattr__'
```

**Comment by tshirtman** [comment]
you mean it should raise a KeyError or a better AttributeError?

**Comment by KeyWeeUsr** [comment]
Perhaps instead of calling `super()` directly we should *check* first and then return
https://github.com/kivy/kivy/blob/67d02cdcd7f077bdf7f6c9568c4720aef2746dcd/kivy/properties.pyx#L838

i.e. something like this:

    if not hasattr(super(self.__class__, self), '__getattr__'):
        raise KeyError(attr)

IIRC, this might even give a useful message for KV lang properties instead of this kind of hidden `KeyError`.
