### ISSUE TITLE
video doesn't handle its own file check

### ISSUE THREAD

**Issue by schoolsplay** [kivy/kivy#3343]
After some frustrating hours of looking in all the wrong directions I noticed that the uix.Video class is not handling it's own file check :-(

This is the crash I got when trying to play a video:
 [ERROR  ] [Image       ] Error reading file test.mp4
[INFO   ] [Base        ] Leaving application in progress...
 2015-05-09 08:43:32,835 - sp._main - ERROR - Unhandled exception
 Traceback (most recent call last):
   File "main.py", line 95, in <module>
    [.....]
   File "/home/stas/GIT/btp-classic-kivy/kivy/uix/video.py", line 177, in _do_video_load
     self._video.play()
   File "/home/stas/GIT/btp-classic-kivy/kivy/core/video/video_gstplayer.py", line 90, in play
     self.player.set_volume(self.volume)
 AttributeError: 'NoneType' object has no attribute 'set_volume'
 
Looks like a gstreamer issue, also qua-non thought so at the ML, but this was not the issue.
The problem was that the file couldn't be found.
The uix.Video class does file checking but it disregards the result.
I've patch it to handle the file check and now I get a much better error:

[ERROR  ] [Image       ] Error reading file test.mp4
[INFO   ] [Base        ] Leaving application in progress...
 2015-05-09 08:52:00,960 - sp._main - ERROR - Unhandled exception
 Traceback (most recent call last):
   File "main.py", line 95, in <module>
     [......]
   File "/home/stas/GIT/btp-classic-kivy/kivy/uix/video.py", line 175, in _do_video_load
     raise FileNotFound, os.path.realpath(self.source)
 FileNotFound: /home/stas/GIT/btp-classic-kivy/test.mp4

As I can't attached a patch file to an issue I just paste it here:
<pre>
stas@Darthvader:~$ diff -u /usr/lib/python2.7/dist-packages/kivy/uix/video.py kivy_btp/uix/video.py
--- /usr/lib/python2.7/dist-packages/kivy/uix/video.py	2015-04-10 00:46:07.000000000 +0200
+++ kivy_btp/uix/video.py	2015-05-09 08:51:57.552854402 +0200
@@ -23,6 +23,7 @@
                duration=on_duration_change)
 
 '''
+import os
 
 __all__ = ('Video', )
 
@@ -33,6 +34,8 @@
 from kivy.properties import (BooleanProperty, NumericProperty, ObjectProperty,
                              OptionProperty)
 
+class FileNotFound(Exception):
+    pass
 
 class Video(Image):
     '''Video class. See module documentation for more information.
@@ -168,6 +171,8 @@
             # Check if filename is not url
             if not '://' in filename:
                 filename = resource_find(filename)
+            if not filename:
+                raise FileNotFound, os.path.realpath(self.source)
             self._video = CoreVideo(filename=filename, **self.options)
             self._video.volume = self.volume
             self._video.bind(on_load=self._on_load,
</pre>

**Comment by dessant** [comment]
It should be handled like in Image,

**Comment by schoolsplay** [comment]
My patch is just to illustrate the issue, the raising of the exception is not the way to go.

**Comment by erknrio** [comment]
I have the same with pip kivy installation. When I try with .deb package I have no problem. There are two screenshots with .deb packages:

New packages:
![kivy deb-new](https://cloud.githubusercontent.com/assets/1659540/23703973/8e233988-03fa-11e7-95cf-710438896afa.jpg)

Extra packages:
![kivy deb-extra](https://cloud.githubusercontent.com/assets/1659540/23703972/8e07a1b4-03fa-11e7-8559-aa2a0ad22a81.png)
