### ISSUE TITLE
Background(Canvas) change problem

### ISSUE THREAD

**Issue by nurgasemetey** [kivy/kivy#3352]
We faced some strange error when we dynamically changed background(canvas).

Part of kv file where we changing background:

```
canvas.before:
    Rectangle:
    size: self.size
source: "data/images/" + root.theme + ".png"
```

Py file regarding the _theme_:

```
...
themeList = ListProperty (["Dark", "Light"])
...

for i in range (0, len (self.themeList)):
                        if self.theme == self.themeList[i]:
                                currentTheme = i
                                break
                if (currentTheme == 0):
                        currentTheme = len (self.themeList) - 1
                else:
                        currentTheme -= 1
                self.theme = self.themeList[currentTheme]
```

When change theme on by button click, the following error raised:

```
 Traceback (most recent call last):
 File "main.py", line 2120, in <module>
 ClockApp().run()
 File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 824, in run
 runTouchApp()
 File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 484, in runTouchApp
 EventLoop.window.mainloop()
 File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 77, in mainloop
  self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 72, in _mainloop
  EventLoop.idle()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 330, in idle
  Builder.sync()
  File "/usr/local/lib/python2.7/dist-packages/kivy/lang.py", line 2082, in sync
   call_fn(next_args[:-1], None, None)
  File "/usr/local/lib/python2.7/dist-packages/kivy/lang.py", line 1477, in call_fn
 setattr(element, key, e_value)
  File "kivy/graphics/instructions.pyx", line 359, in kivy.graphics.instructions.VertexInstruction.source.__set__ (kivy/graphics/instructions.c:6840)
  File "kivy/graphics/context_instructions.pyx", line 381, in kivy.graphics.context_instructions.BindTexture.source.__set__ (kivy/graphics/context_instructions.c:7271)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 511, in __init__
 self.filename = arg
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 699, in _set_filename
 mipmap=self._mipmap, nocache=self._nocache)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 429, in load
 im = loader(filename, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 197, in __init__
 self._data = self.load(filename)
 File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/img_pygame.py", line 86, in load
 (filename, im.fmt))
 AttributeError: 'pygame.Surface' object has no attribute 'fmt'
```

Can you advise what can be done in such situation?
##

**Comment by Kartstig** [comment]
I also have this issue. I'm loading an Async image. I'm running on a Raspberry Pi 2.

```
[INFO              ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_15-09-11_10.txt
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
[INFO              ] [Factory     ] 177 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: pygame
[INFO              ] [Window      ] Provider: egl_rpi
[INFO              ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO              ] [GL          ] OpenGL vendor <Broadcom>
[INFO              ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO              ] [GL          ] OpenGL parsed version: 2, 0
[INFO              ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO              ] [GL          ] Texture max size <2048>
[INFO              ] [GL          ] Texture max units <8>
[INFO              ] [Shader      ] fragment shader: <Compiled>
[INFO              ] [Shader      ] vertex shader: <Compiled>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Loader      ] using a thread pool of 2 workers
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO              ] [HIDInput    ] Read event from </dev/input/event0>
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO              ] [HIDInput    ] Read event from </dev/input/event1>
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO              ] [HIDInput    ] Read event from </dev/input/event2>
[INFO              ] [Base        ] Start application main loop
[INFO              ] [HIDMotionEvent] using <ADS7846 Touchscreen>
[INFO              ] [HIDMotionEvent] using <SIGMACHIP USB Keyboard>
[INFO              ] [HIDMotionEvent] using <SIGMACHIP USB Keyboard>
[INFO              ] [HIDMotionEvent] <ADS7846 Touchscreen> range ABS X position is 0 - 4095
[INFO              ] [HIDMotionEvent] <ADS7846 Touchscreen> range ABS Y position is 0 - 4095
[INFO              ] [HIDMotionEvent] <ADS7846 Touchscreen> range ABS pressure is 0 - 255
'pygame.Surface' object has no attribute 'fmt'
```

**Comment by Julian-O** [comment]
Closing as Pygame is no longer supported.
