### ISSUE TITLE
Scatter not allowed in StackLayout

### ISSUE THREAD

**Issue by gwhittey23** [kivy/kivy#3427]
If you try and allow scatter inside a StackLayout is gives 

stacklayout.py", line 264, in do_layout
     c2.pos[innerattr] = u
 TypeError: 'tuple' object does not support item assignment
##

**Comment by gwhittey23** [comment]
Traceback (most recent call last):
   File "/Users/gerardwhittey/PycharmProjects/Dev/DCSV3/main.py", line 181, in <module>
     MainApp().run()
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 543, in mainloop
     self._mainloop()
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
     EventLoop.idle()
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/Users/gerardwhittey/Workspace/VirtualEnvs/dev_kivy/lib/python2.7/site-packages/kivy/uix/stacklayout.py", line 264, in do_layout
     c2.pos[innerattr] = u
 TypeError: 'tuple' object does not support item assignment

Process finished with exit code 1

**Comment by Julian-O** [comment]
@gwhittey23: Does this problem still occur for you? Do you have an example of a small program that fails?
