### ISSUE TITLE
Audio tests fail sometimes, causing false positives for travis builds

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3464]
@matham said that we likely need to wait a litle more before the audio is ready.

```python
#49 test_length_playing (kivy.tests.test_audio.AudioGstreamerTestCase) ... [INFO   ] [AudioGstplayer] Using Gstreamer 1.2.1.0
[DEBUG  ] [Audio       ] register SoundGstplayer
[TRACE  ] [Audio       ] Unable to use <sdl2> as loader!
[TRACE  ] 
Traceback (most recent call last):
  File "/home/travis/build/kivy/kivy/kivy/core/__init__.py", line 127, in core_register_libs
    level=0)
  File "/home/travis/build/kivy/kivy/kivy/core/audio/audio_ffpyplayer.py", line 49, in <module>
    import ffpyplayer
ImportError: No module named ffpyplayer
[DEBUG  ] [Audio       ] register SoundSDL2
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
FAIL
```

**Comment by matham** [comment]
I made it wait a bit longer, but it didn't help. @tito any thoughts?

**Comment by matham** [comment]
For reference:

```
<tito> i think the test is not well done from the start
<tito> sleep() will never ensure the sound is actually fully played
<tito> if the computer is slow / gstreamer slow to start playing = delay is not enough
<tito> ie, it should be dependent of the computer load
<matham> right
<matham> I increased the sleep value hoping it'd help, but it's not guarenteed
<tito> yep
<matham> how can we know for sure?
<tito> you would be able to know exactly by activating GST_DEBUG=*:4
<matham> ok
<tito> i suggest too loop until the state is stopped, with a maximum execution limit. if the execution limit is reached, we can raise a warning, but not fail on it
```
