### ISSUE TITLE
Error at startup: "Permission denied: '/dev/input/event6'"

### ISSUE THREAD

**Issue by gustavklopp** [kivy/kivy#3476]
First time installation here.
The program is (apparently) running when launching it but I've got this error:
```
[INFO              ] [Logger      ] Record log in /home/gus/.kivy/logs/kivy_15-07-01_8.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <b'3.0 Mesa 10.6.0-devel'>
[INFO              ] [GL          ] OpenGL vendor <b'X.Org'>
[INFO              ] [GL          ] OpenGL renderer <b'Gallium 0.4 on AMD KABINI'>
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <b'1.30'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: pygame
[INFO              ] [VideoGstplayer] Using Gstreamer 1.4.5.0
[INFO              ] [Video       ] Provider: gstplayer
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event6
[INFO              ] [MTD         ] Read event from </dev/input/event6>
[INFO              ] [Base        ] Start application main loop
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.4/threading.py", line 868, in run
     self._target(*self._args, **self._kwargs)
   File "/home/gus/.Envs/python3_kivy/lib/python3.4/site-packages/kivy/input/providers/mtdev.py", line 197, in _thread_run
     _device = Device(_fn)
   File "/home/gus/.Envs/python3_kivy/lib/python3.4/site-packages/kivy/lib/mtdev.py", line 131, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 PermissionError: [Errno 13] Permission denied: '/dev/input/event6'
 
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...
```

**Comment by gustavklopp** [comment]
Okay, apparently, it's due to my touchpad on the laptop. Not an error apparently:
http://stackoverflow.com/questions/26164723/kivy-and-buildozer-permission-denied
