### ISSUE TITLE
Can't use "before" canvas of a ScatterLayout

### ISSUE THREAD

**Issue by janssen** [kivy/kivy#3522]
Get an exception trying to draw on the "before" canvas of a ScatterLayout (same code works fine on a FloatLayout).

```
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "t2.py", line 39, in <module>
     MyApp().run()
   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 559, in mainloop
     self._mainloop()
   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 316, in _mainloop
     EventLoop.idle()
   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/base.py", line 343, in idle
     window.dispatch('on_draw')
   File "_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7049)
   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 928, in on_draw
     self.render_context.draw()
   File "instructions.pyx", line 599, in kivy.graphics.instructions.Canvas.draw (kivy/graphics/instructions.c:8660)
   File "instructions.pyx", line 602, in kivy.graphics.instructions.Canvas.draw (kivy/graphics/instructions.c:8613)
   File "instructions.pyx", line 863, in kivy.graphics.instructions.RenderContext.apply (kivy/graphics/instructions.c:11495)
   File "instructions.pyx", line 819, in kivy.graphics.instructions.RenderContext.pop_states (kivy/graphics/instructions.c:11054)
   File "instructions.pyx", line 812, in kivy.graphics.instructions.RenderContext.pop_state (kivy/graphics/instructions.c:10948)
 IndexError: list index out of range
```

See attached test case.

**Comment by janssen** [comment]
```
import sys, os, math

from kivy.app import App
from kivy.uix.scatterlayout import ScatterLayout, ScatterPlaneLayout
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.slider import Slider
from kivy.uix.label import Label
from kivy.graphics import Color, Line, Rectangle

class MyApp(App):

    def scale_sheet(self, *args):
        self.sheet.scale = math.exp(self.slider.value)

    def redraw_sheet(self, *args):
        self.sheet.canvas.before.clear()
        self.sheet.canvas.before.add(Color(1, 0, 0, 1))
        self.sheet.canvas.before.add(Line(rectangle=(0, 0, self.sheet.width, self.sheet.height)))

    def build (self):
        root = BoxLayout(orientation='horizontal')
        self.sheet = ScatterLayout(size_hint=(1, 1),
                                   do_translation=False,
                                   do_scaling=False,
                                   do_rotation=False,
                                   auto_bring_to_front=False)
        # self.sheet = FloatLayout(size_hint=(1,1))
        self.sheet.bind(size=self.redraw_sheet)
        root.add_widget(self.sheet)
        self.slider = Slider(orientation='vertical', size_hint=(None, 1), width=50, min=-1, max=1, value=0)
        self.slider.bind(value=self.scale_sheet)
        root.add_widget(self.slider)
        self.sheet.add_widget(Label(text="foo", pos=(100, 100), size_hint=(None, None), size=(50,30)))
        self.sheet.add_widget(Label(text="bar", pos=(300, 150), size_hint=(None, None), size=(50,30)))
        return root

if __name__ == "__main__":
    MyApp().run()
```

**Comment by kived** [comment]
You're clearing the `before` canvas, which `ScatterLayout` uses. Using the `before` canvas works fine, you're just removing part of `ScatterLayout` which is breaking it.

The correct way to do this is using bindings. Instead of clearing and adding new instructions, just update the existing instructions.

````python
self.rect = Rectangle(pos=self.sheet.pos, size=self.sheet.size)
self.sheet.canvas.before.add(self.rect)
self.sheet.bind(pos=self.redraw_sheet, size=self.redraw_sheet)
````

````python
def redraw_sheet(self, *args):
    self.rect.pos = self.sheet.pos
    self.rect.size = self.sheet.size
````

But of course you should be using kv anyway, since it's far easier to work with and binding happens automatically:

````
ScatterLayout:
    canvas.before:
        Color:
            rgba: 1, 0, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size
````

**Comment by janssen** [comment]
I'm following the documentation about how to draw on a Layout.  So maybe that needs to be changed?

**Comment by matham** [comment]
Which docs?

**Comment by janssen** [comment]
I was thinking of the Widgets API doc, "Adding a Background to a Layout".  However, after reviewing it, I see that it uses the technique "kived" espouses above.  Now I'm not sure where I came up with the idea that I needed to clear it before drawing.
