### ISSUE TITLE
Can't install anything with Kivy-Garden

### ISSUE THREAD

**Issue by gustavklopp** [kivy/kivy#3535]
Hi,
I've got this error when trying to install an addon from Kivy-Garden:
(Example with cefpython, but I've got the same thing for all the other apparently)

```
$ garden install cefpython
Downloading http://github.com/kivy-garden/garden.cefpython/archive/master.zip ...
Traceback (most recent call last):
  File "/home/gus/.Envs/python3_kivy/bin/garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "/home/gus/.Envs/python3_kivy/bin/garden", line 71, in main
    options.func()
  File "/home/gus/.Envs/python3_kivy/bin/garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "/home/gus/.Envs/python3_kivy/bin/garden", line 170, in download
    data += buf
TypeError: Can't convert 'bytes' object to str implicitly
```
my config: Ubuntu 15.04
Cython==0.21.2
Kivy==1.9.0
Kivy-Garden==0.1.1
pygame==1.9.2a0
requests==2.7.0
wheel==0.24.0

Thanks for your help!

**Comment by dessant** [comment]
@gustavklopp `pip install -U kivy-garden`
