### ISSUE TITLE
Kivy Settings panel crashes

### ISSUE THREAD

**Issue by aron-bordin** [kivy/kivy#3579]
Go to kivy/examples/widgets and run settings.py example.
Same with: /kivy/examples/settings/main.py

Getting an error when trying to open any panel.

[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)]
[INFO   ] [Factory     ] 177 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 10.6.3'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Ivybridge Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event8
[INFO   ] [MTD         ] Read event from </dev/input/event8>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.4/threading.py", line 868, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/lib/python3.4/site-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
     _device = Device(_fn)
   File "/usr/lib/python3.4/site-packages/kivy/lib/mtdev.py", line 131, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 PermissionError: [Errno 13] Permission denied: '/dev/input/event8'
 
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "settings.py", line 93, in <module>
     SettingsApp().run()
   File "/usr/lib/python3.4/site-packages/kivy/app.py", line 825, in run
     runTouchApp()
   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3.4/site-packages/kivy/core/window/window_sdl2.py", line 606, in mainloop
     self._mainloop()
   File "/usr/lib/python3.4/site-packages/kivy/core/window/window_sdl2.py", line 361, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 330, in idle
     self.dispatch_input()
   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 221, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7279)
   File "/usr/lib/python3.4/site-packages/kivy/core/window/__init__.py", line 979, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7279)
   File "/usr/lib/python3.4/site-packages/kivy/core/window/__init__.py", line 995, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7279)
   File "/usr/lib/python3.4/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7279)
   File "/usr/lib/python3.4/site-packages/kivy/uix/behaviors.py", line 183, in on_touch_down
     self.dispatch('on_press')
   File "kivy/_event.pyx", line 713, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7238)
   File "kivy/_event.pyx", line 1223, in kivy._event.EventObservers.dispatch (kivy/_event.c:12649)
   File "kivy/_event.pyx", line 1147, in kivy._event.EventObservers._dispatch (kivy/_event.c:12226)
   File "/usr/lib/python3.4/site-packages/kivy/app.py", line 913, in open_settings
     self._app_settings = self.create_settings()
   File "/usr/lib/python3.4/site-packages/kivy/app.py", line 984, in create_settings
     s.add_kivy_panel()
   File "/usr/lib/python3.4/site-packages/kivy/uix/settings.py", line 1001, in add_kivy_panel
     join(kivy_data_dir, 'settings_kivy.json'))
   File "/usr/lib/python3.4/site-packages/kivy/uix/settings.py", line 941, in add_json_panel
     panel = self.create_json_panel(title, config, filename, data)
   File "/usr/lib/python3.4/site-packages/kivy/uix/settings.py", line 981, in create_json_panel
     instance = cls(panel=panel, **str_settings)
   File "/usr/lib/python3.4/site-packages/kivy/uix/label.py", line 248, in __init__
     super(Label, self).__init__(**kwargs)
   File "/usr/lib/python3.4/site-packages/kivy/uix/widget.py", line 312, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy/_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (kivy/_event.c:4676)
 TypeError: object.__init__() takes no parameters

**Comment by aron-bordin** [comment]
fixed in https://github.com/kivy/kivy/pull/3699
