### ISSUE TITLE
TypeError: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3650]
Reported by TwoCubed on irc.

https://github.com/kivy/kivy/blob/master/examples/widgets/settings.py
```python
 Traceback (most recent call last):
   File "E:\dev\envs\py34_x86\kivy\examples\widgets\settings.py", line 93, in <module>
     SettingsApp().run()
   File "e:\dev\envs\py34_x86\kivy\kivy\app.py", line 825, in run
     runTouchApp()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 606, in mainloop
     self._mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 361, in _mainloop
     EventLoop.idle()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 330, in idle
     self.dispatch_input()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 221, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\__init__.py", line 986, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\__init__.py", line 1002, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 438, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 717, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7635)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\behaviors.py", line 183, in on_touch_down
     self.dispatch('on_press')
   File "kivy\_event.pyx", line 713, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7590)
   File "kivy\_event.pyx", line 1223, in kivy._event.EventObservers.dispatch (kivy\_event.c:13325)
   File "kivy\_event.pyx", line 1147, in kivy._event.EventObservers._dispatch (kivy\_event.c:12851)
   File "e:\dev\envs\py34_x86\kivy\kivy\app.py", line 913, in open_settings
     self._app_settings = self.create_settings()
   File "e:\dev\envs\py34_x86\kivy\kivy\app.py", line 984, in create_settings
     s.add_kivy_panel()
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\settings.py", line 1004, in add_kivy_panel
     join(kivy_data_dir, 'settings_kivy.json'))
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\settings.py", line 944, in add_json_panel
     panel = self.create_json_panel(title, config, filename, data)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\settings.py", line 984, in create_json_panel
     instance = cls(panel=panel, **str_settings)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\label.py", line 248, in __init__
     super(Label, self).__init__(**kwargs)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 312, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:4863)
 TypeError: object.__init__() takes no parameters
```

**Comment by Vagdish** [comment]
I can reproduce the error with the last master on many of my projects.
However, I can't write a small minimal example that raise the exception. I'll try to locate the commit that causes it.

**Comment by dessant** [comment]
@Vagdish the way you pass kwargs in your app needs to be adapted a bit: https://github.com/kivy/kivy/pull/3469.

**Comment by Vagdish** [comment]
@dessant Thanks for your help. I'm a little confused about what's going on. I've reinstalled kivy from 1.9.0 tag instead.

**Comment by ATLUSio** [comment]
Normally, that error would be given by calling the wrong class name. If you call super on the class whose base class is the 'object' class, you'll get that error since the object class takes no parameters
Error line:
super(EventDispatcher, self).__init__(**kwargs)

So it has to do with the following line of code
cdef class EventDispatcher(ObjectWithUid):

Since the class EventDispatcher's super class is the object class, which takes no params, you're getting this error.

**Comment by ngoonee** [comment]
Ah, I see this is already reported. Thanks for the hint ATLUSio, I only understood about 10% of it, but I've tested changing the appropriate line and it works. Push request incoming.

**Comment by matham** [comment]
The problem occurs because we forward up our inheritance chain any kwargs we don't use. And in python 3, anything that was not eaten by the time we call the highest class, i.e. `object` will cause a error. I.e. calling super on `object` must call with empty kwargs.

Now, what does kivy eat in kwargs? Any kwargs key that is a property name will be eaten. That's because kivy uses it to set the property value, and as per the rules, when it's used it's removed from kwargs. So, if you pass something on to super that is not a kivy prop, kivy will forward up the chain and cause an exception when it's passed to super.

**Comment by ngoonee** [comment]
I'm not passing any additional things to kivy prop, as mentioned in the initial report, this is hit with the default settings example (examples/settings/main.py) as well.

**Comment by ngoonee** [comment]
The error being hit is that, somehow, the SettingsPanel object is being passed on to EventDispatcher. This is obviously a bug but I can't track down why it's being passed on.

**Comment by ngoonee** [comment]
Okay, tracked it down to SettingTitle (in settings.py) being a Label rather than a SettingItem. I don't think it should be a setting item, as it's obviously just a label, but because it gets called with panel as an argument just like all the other settingitems...

Sending another PR which just adds the property.

**Comment by MoniaDev** [comment]
I have tried everything above, but I still can't get Popup().open() to work.

It still brings that same __init__() takes no parameters.

**Comment by matham** [comment]
@MoniaDev are you on master?

**Comment by MoniaDev** [comment]
Yes! I installed kivy-master.zip

**Comment by nikhilraj1321** [comment]
Essentially what you are resolving to is the __init__ of the object base class which takes no params.

Its a bit redundant, I know, to have to specify the class that you are already inside of, which is why in **python3** you can just do:  **_super().__init__()_**
