### ISSUE TITLE
Buildozer.spec 's title of your application can not be a Chinese character. it will show errors.

### ISSUE THREAD

**Issue by lhrlgl** [kivy/kivy#3683]
# Android packaging done!
# APK 中-1.0.0-debug.apk available in the bin directory
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.30', 'console_scripts', 'buildozer')()
  File "/Library/Python/2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 987, in run_command
    self.target.run_commands(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 97, in cmd_debug
    self.buildozer.build()
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 198, in build
    self.target.build_package()
  File "/Library/Python/2.7/site-packages/buildozer/targets/android.py", line 735, in build_package
    self.buildozer.state['android:latestapk'] = apk
  File "/Library/Python/2.7/site-packages/buildozer/jsonstore.py", line 33, in __setitem__
    self.sync()
  File "/Library/Python/2.7/site-packages/buildozer/jsonstore.py", line 55, in sync
    fd.write(unicode(dumps(self.data, ensure_ascii=False)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)

**Comment by dessant** [comment]
Ported to https://github.com/kivy/buildozer/issues/284.
