### ISSUE TITLE
Kivy base.py missing reference

### ISSUE THREAD

**Issue by dmcfadin** [kivy/kivy#3688]
I am using Ubuntu 14.4 LTS - Installed Kivy from ppa:kivy-team/kivy stable - ran update then install from command line - pointed python2.7 to work with Kivy. 

I was running the examples using script method --  #python main.py -- from demo .py files.
The files for the demo where installed to the following location from the ppa - /usr/share/kivy-examples/demo/...

The code does not exist in kivy.base or base.py.  I stopped debugging this issue at this point so I don't know what other code is missing from the distribution. The actual files exist correctly in the directory, but is missing code from within the file that is referenced from the the import is not there.

Traceback (most recent call last):
   File "main.py", line 27, in <module>
     from kivy.app import App
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 316, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 31, in <module>
     from kivy.lang import Builder
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 2143, in <module>
     Builder.load_file(join(kivy_data_dir, 'style.kv'), rulesonly=True)
   File "/usr/lib/python2.7/dist-packages/kivy/lang.py", line 1736, in load_file
with open(filename, 'r') as fd:
 IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/kivy/data/style.kv'

-DM

**Comment by dmcfadin** [comment]
Never mind -- I found the issue.. Apparently I needed an an additional package that didn't come with the stable ppa. To fix this issue I loaded the following package after everything else was installed.

 $ apt-get install apt-kivy-common

-DM
