### ISSUE TITLE
Examples don't have __version__ so buildozer complains.

### ISSUE THREAD

**Issue by stuaxo** [kivy/kivy#3689]
Tried adding to it the audio and pictures examples and they built ok (though the audio one didn't display the buttons as I guess the layout doesn't work on the smaller screen).

I guess it's not just adding __version__ but checking if they actually work ..

**Comment by dessant** [comment]
I'm not aware of buildozer requiring __version__ in the main module, is that the case?

**Comment by stuaxo** [comment]
Hm, when I remove it and try and rebuild it seems OK... trying one of the other examples now..

Here's the pictures example
http://imgur.com/j6wXrSm

- the pics themselves are quite small - should probably be scaled relative to the screen size initially ?

here's the sound example
http://imgur.com/qzSvH0m

- can't press any sound buttons as they are offscreen

**Comment by stuaxo** [comment]
Ah - found the relevant output (was lost way back in history).   I have no idea if it's needed, as I am super new to it

```
----------
id: 155 or "extra-google-simulators"
     Type: Extra
     Desc: Android Auto API Simulators, revision 1
           By Google Inc.
           Android Auto API testing simulators
           Install path: extras/google/simulators
----------
id: 156 or "extra-google-webdriver"
     Type: Extra
     Desc: Google Web Driver, revision 2
           By Google Inc.
           WebDriver
           Install path: extras/google/webdriver

# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
# Distribution compiled.
# Build the application #1
# Package the application
Traceback (most recent call last):
  File "/usr/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.31.dev0', 'console_scripts', 'buildozer')()
  File "/usr/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/buildozer/__init__.py", line 987, in run_command
    self.target.run_commands(args)
  File "/usr/lib/python2.7/dist-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/usr/lib/python2.7/dist-packages/buildozer/target.py", line 97, in cmd_debug
    self.buildozer.build()
  File "/usr/lib/python2.7/dist-packages/buildozer/__init__.py", line 198, in build
    self.target.build_package()
  File "/usr/lib/python2.7/dist-packages/buildozer/targets/android.py", line 583, in build_package
    version = self.buildozer.get_version()
  File "/usr/lib/python2.7/dist-packages/buildozer/__init__.py", line 681, in get_version
    ' (looking for `{1}`)'.format(fn, regex))
Exception: Unable to find capture version in ./main.py
 (looking for `__version__ = ['"](.*)['"]`)

```

**Comment by dessant** [comment]
Could you open this against buildozer? https://github.com/kivy/buildozer
Please post this log and a link to the example you have used.
