### ISSUE TITLE
Notes tutorial crashes when adding a new note

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3697]
https://github.com/kivy/kivy/blob/master/examples/tutorials/notes/final/main.py
Related to https://github.com/kivy/kivy/pull/3469.
```python
 Traceback (most recent call last):
   File "E:\dev\envs\py34_x86\kivy\examples\tutorials\notes\final\main.py", line 158, in <module>
     NoteApp().run()
   File "e:\dev\envs\py34_x86\kivy\kivy\app.py", line 828, in run
     runTouchApp()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 606, in mainloop
     self._mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 361, in _mainloop
     EventLoop.idle()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 336, in idle
     Clock.tick_draw()
   File "e:\dev\envs\py34_x86\kivy\kivy\clock.py", line 490, in tick_draw
     self._process_events_before_frame()
   File "e:\dev\envs\py34_x86\kivy\kivy\clock.py", line 640, in _process_events_before_frame
     event.tick(self._last_tick, remove)
   File "e:\dev\envs\py34_x86\kivy\kivy\clock.py", line 374, in tick
     ret = callback(self._dt)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\listview.py", line 950, in _spopulate
     self.populate()
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\listview.py", line 998, in populate
     item_view = self.adapter.get_view(index)
   File "e:\dev\envs\py34_x86\kivy\kivy\adapters\listadapter.py", line 211, in get_view
     item_view = self.create_view(index)
   File "e:\dev\envs\py34_x86\kivy\kivy\adapters\listadapter.py", line 234, in create_view
     view_instance = cls(**item_args)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\boxlayout.py", line 102, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\layout.py", line 72, in __init__
     super(Layout, self).__init__(**kwargs)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\widget.py", line 312, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:4863)
 TypeError: object.__init__() takes no parameters
```

**Comment by xwaffelx** [comment]
I'd like to start contributing by solving this issue. No one assigned as I see :)

**Comment by akshayaurora** [comment]
@xwaffelx go ahead

**Comment by dessant** [comment]
@xwaffelx :ice_cream: , here's a pointer for what needs to be changed: https://github.com/kivy/kivy/pull/3469#issuecomment-116297905.

**Comment by xwaffelx** [comment]
Well, it works just fine on my setup with python 2...
The Notes app is written in python 2 (at least because of the json.load()), so I suppose it's not meant to be run on python 3.

**Comment by abit2** [comment]
Hey, is this still open.

**Comment by dessant** [comment]
@abit2, does it look closed? :ghost:
