### ISSUE TITLE
Line dash_offset and dash_length do not always work

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3761]
I did these tests on win10 x64, with the first one i see a continuous line instead of a dashed one.

``` python
from kivy.app import App
from kivy.lang import Builder

kv = """
FloatLayout:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Widget:
        size_hint: None, None
        pos: 250, 250
        canvas:
            Color:
                rgba: 0, 0, 0, 1
            Line:
                points: self.x - 10, self.y, self.x - 10, self.top
                width: 1
                dash_length: 5
                dash_offset: 10
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()

```

My output:
![untitled-3](https://cloud.githubusercontent.com/assets/7513068/11075626/d7d0cede-87fe-11e5-82c0-7b6f7a1a109d.png)

@bionoid output on linux with kivy master + pygame, he also tested with sdl2 and the line was also dashed (the dashes were there on win7 x64 too):
![hgbpolq](https://cloud.githubusercontent.com/assets/7513068/11075750/a205e036-87ff-11e5-8ff0-96c4d50fdd5a.png)

@akshayaurora screenshot with kivy master on osx, the line is correctly dashed:
<img width="813" alt="24091828" src="https://cloud.githubusercontent.com/assets/7513068/11075882/4d8749f4-8800-11e5-916f-923431b86483.png">

@akshayaurora pointed me to a different example where the _second_ line is correctly dashed.
The main change here is that before our target line, there is a different Line instruction, with dash parameters defined and a width _that is not 1_ (the first line is not dashed, as it should according to the docs, because the width > 1):

``` python
from kivy.app import App
from kivy.lang import Builder

kv = """
#:import pt kivy.metrics.pt
FloatLayout:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Widget:
        size_hint: None, None
        pos: 250, 250
        canvas:
            Color:
                rgba: 0, 0, 0, 1
            Line:
                points: self.x - 20, self.y-20, self.x - 20, self.top - 20
                width: 2
                dash_length: 5
                dash_offset: 10
            Line:
                points: self.x - 10, self.y, self.x - 10, self.top
                width: 1
                dash_length: 5
                dash_offset: 10
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

My screenshot (@akshayaurora has seen the same output):
![untitled-4](https://cloud.githubusercontent.com/assets/7513068/11076143/e088fa30-8801-11e5-829b-8a5932d17c6b.png)

Ok, now let's change the width of the first line to 1, none of the lines will be dashed on my part:

``` python
from kivy.app import App
from kivy.lang import Builder

kv = """
#:import pt kivy.metrics.pt
FloatLayout:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Widget:
        size_hint: None, None
        pos: 250, 250
        canvas:
            Color:
                rgba: 0, 0, 0, 1
            Line:
                points: self.x - 20, self.y-20, self.x - 20, self.top - 20
                width: 1
                dash_length: 5
                dash_offset: 10
            Line:
                points: self.x - 10, self.y, self.x - 10, self.top
                width: 1
                dash_length: 5
                dash_offset: 10
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

Screenshot:
![untitled-4](https://cloud.githubusercontent.com/assets/7513068/11076288/942219e6-8802-11e5-850f-54ebb57dd1a2.png)

Finally, i have removed the dash properties of the first line, this caused the second line to be dashed correctly:

``` python
from kivy.app import App
from kivy.lang import Builder

kv = """
#:import pt kivy.metrics.pt
FloatLayout:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Widget:
        size_hint: None, None
        pos: 250, 250
        canvas:
            Color:
                rgba: 0, 0, 0, 1
            Line:
                points: self.x - 20, self.y-20, self.x - 20, self.top - 20
                width: 1
            Line:
                points: self.x - 10, self.y, self.x - 10, self.top
                width: 1
                dash_length: 5
                dash_offset: 10
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

Screenshot:
![untitled-4](https://cloud.githubusercontent.com/assets/7513068/11076350/f6e4b4c6-8802-11e5-8ce5-244513ef8f11.png)

Please test these cases and post screenshots for windows other platforms, for now it seems to be happening only on windows.

**Comment by tito** [comment]
Do you think you can have a trace log about it? Aka one run of the same program on windows that fail, and another platform that works?
Just to see if it's a clock/scheduling issue, or kv lang that leads do something else (aka, different trace output / order of execution)

**Comment by dessant** [comment]
Trace for the first example on win10 x64, a continuous line is displayed:

```python
$ python test.py -c kivy:log_level:trace
[INFO              ] [Logger      ] Record log in c:/Users/prc\.kivy\logs\kivy_15-11-30_0.txt
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[TRACE             ] [Builder     ] load file e:\dev\envs\py34_x86\kivy\kivy\data\style.kv
[TRACE             ] [Parser      ] parsing 1265 lines
[TRACE             ] [Parser      ] got directive <kivy 1.0>
[TRACE             ] [Builder     ] build rule for <Label>
[TRACE             ] [Builder     ] build rule for <-Button,-ToggleButton>
[TRACE             ] [Builder     ] build rule for <BubbleContent>
[TRACE             ] [Builder     ] build rule for <BubbleButton>
[TRACE             ] [Builder     ] build rule for <Slider>
[TRACE             ] [Builder     ] build rule for <ProgressBar>
[TRACE             ] [Builder     ] build rule for <SplitterStrip>
[TRACE             ] [Builder     ] build rule for <Scatter>
[TRACE             ] [Builder     ] build rule for <RelativeLayout>
[TRACE             ] [Builder     ] build rule for <Image,AsyncImage>
[TRACE             ] [Builder     ] build rule for <EffectWidget>
[TRACE             ] [Builder     ] build rule for <TabbedPanelContent>
[TRACE             ] [Builder     ] build rule for <TabbedPanelStrip>
[TRACE             ] [Builder     ] build rule for <StripLayout>
[TRACE             ] [Builder     ] build rule for <TabbedPanelHeader>
[TRACE             ] [Builder     ] build rule for <Selector>
[TRACE             ] [Builder     ] build rule for <TextInput>
[TRACE             ] [Builder     ] build rule for <TextInputCutCopyPaste>
[TRACE             ] [Builder     ] build rule for <CodeInput>
[TRACE             ] [Builder     ] build rule for <TreeViewNode>
[TRACE             ] [Builder     ] build rule for <TreeViewLabel>
[TRACE             ] [Builder     ] build rule for <StencilView>
[TRACE             ] [Builder     ] build rule for <FileChooserListLayout>
[TRACE             ] [Builder     ] build rule for <FileChooserListView>
[TRACE             ] [Builder     ] build template for [FileListEntry@FloatLayout+TreeViewNode]
[TRACE             ] [Builder     ] build rule for <FileChooserIconLayout>
[TRACE             ] [Builder     ] build rule for <FileChooserIconView>
[TRACE             ] [Builder     ] build template for [FileIconEntry@Widget]
[TRACE             ] [Builder     ] build rule for <FileChooserProgress>
[TRACE             ] [Builder     ] build rule for <Switch>
[TRACE             ] [Builder     ] build rule for <ModalView>
[TRACE             ] [Builder     ] build rule for <Popup>
[TRACE             ] [Builder     ] build rule for <SpinnerOption>
[TRACE             ] [Builder     ] build rule for <Spinner>
[TRACE             ] [Builder     ] build rule for <ActionBar>
[TRACE             ] [Builder     ] build rule for <ActionView>
[TRACE             ] [Builder     ] build rule for <ActionSeparator>
[TRACE             ] [Builder     ] build rule for <ActionButton,ActionToggleButton>
[TRACE             ] [Builder     ] build rule for <ActionLabel>
[TRACE             ] [Builder     ] build rule for <ActionGroup>
[TRACE             ] [Builder     ] build rule for <ActionCheck>
[TRACE             ] [Builder     ] build rule for <ActionPreviousImage@Image>
[TRACE             ] [Builder     ] build rule for <ActionPreviousButton@Button>
[TRACE             ] [Builder     ] build rule for <ActionPrevious>
[TRACE             ] [Builder     ] build rule for <ActionGroup>
[TRACE             ] [Builder     ] build rule for <ActionOverflow>
[TRACE             ] [Builder     ] build rule for <ActionDropDown>
[TRACE             ] [Builder     ] build template for [AccordionItemTitle@Label]
[TRACE             ] [Builder     ] build rule for <AccordionItem>
[TRACE             ] [Builder     ] build rule for <SettingSpacer>
[TRACE             ] [Builder     ] build rule for <SettingItem>
[TRACE             ] [Builder     ] build rule for <SettingBoolean>
[TRACE             ] [Builder     ] build rule for <SettingString>
[TRACE             ] [Builder     ] build rule for <SettingPath>
[TRACE             ] [Builder     ] build rule for <SettingOptions>
[TRACE             ] [Builder     ] build rule for <SettingTitle>
[TRACE             ] [Builder     ] build rule for <SettingSidebarLabel>
[TRACE             ] [Builder     ] build rule for <SettingsPanel>
[TRACE             ] [Builder     ] build rule for <Settings>
[TRACE             ] [Builder     ] build rule for <InterfaceWithSidebar>
[TRACE             ] [Builder     ] build rule for <InterfaceWithSpinner>
[TRACE             ] [Builder     ] build rule for <MenuSpinner>
[TRACE             ] [Builder     ] build rule for <MenuSidebar>
[TRACE             ] [Builder     ] build rule for <ContentPanel>
[TRACE             ] [Builder     ] build rule for <InterfaceWithTabbedPanel>
[TRACE             ] [Builder     ] build rule for <ScrollView>
[TRACE             ] [Builder     ] build rule for <VideoPlayerPreview>
[TRACE             ] [Builder     ] build rule for <VideoPlayerAnnotation>
[TRACE             ] [Builder     ] build rule for <VideoPlayer>
[TRACE             ] [Builder     ] build rule for <CheckBox>
[TRACE             ] [Builder     ] build rule for <ScreenManager>
[TRACE             ] [Builder     ] build rule for <ColorPicker_Input@TextInput>
[TRACE             ] [Builder     ] build rule for <ColorPicker_Label@Label>
[TRACE             ] [Builder     ] build rule for <ColorPicker_Selector@BoxLayout>
[TRACE             ] [Builder     ] build rule for <ColorPicker>
[DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[TRACE             ] [Image       ] Unable to use <gif> as loader!
[TRACE             ]
Traceback (most recent call last):
  File "e:\dev\envs\py34_x86\kivy\kivy\core\__init__.py", line 129, in core_register_libs
    level=0)
  File "e:\dev\envs\py34_x86\kivy\kivy\core\image\img_ffpyplayer.py", line 7, in <module>
    import ffpyplayer
ImportError: No module named 'ffpyplayer'
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG             ] [App         ] Loading kv <.\test.kv>
[DEBUG             ] [App         ] kv <.\test.kv> not found
[TRACE             ] [Parser      ] parsing 19 lines
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'3.3.0'>
[INFO              ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO              ] [GL          ] OpenGL renderer <b'GeForce 9600 GSO/PCIe/SSE2'>
[INFO              ] [GL          ] OpenGL parsed version: 3, 3
[INFO              ] [GL          ] Shading version <b'3.30 NVIDIA via Cg compiler'>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <32>
[DEBUG             ] [Shader      ] Fragment compiled successfully
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [ImageSDL2   ] Load <e:\dev\envs\py34_x86\kivy\kivy\data\glsl\default.png>
[TRACE             ] [Image       ] 'e:\\dev\\envs\\py34_x86\\kivy\\kivy\\data\\glsl\\default.png', populate to textures (1)
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[TRACE             ] [Builder     ] Found 0 rules for <kivy.uix.floatlayout.FloatLayout object at 0x031A3F10>
[TRACE             ] [Builder     ] Found 0 rules for <kivy.uix.widget.Widget object at 0x0325F420>
[DEBUG             ] [Base        ] Create provider from mouse
[DEBUG             ] [Base        ] Create provider from wm_touch
[DEBUG             ] [Base        ] Create provider from wm_pen
[INFO              ] [Base        ] Start application main loop
[TRACE             ] [Builder     ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x03260110>, key=size, value=<code object <module> at 0x0319FA70, file "<string>", line 8>, 'self.size'
[TRACE             ] [Builder     ] call_fn => value=[800, 600]
[TRACE             ] [Builder     ] call_fn <kivy.graphics.vertex_instructions.Line object at 0x031FA4E0>, key=points, value=<code object <module> at 0x0319F9D0, file "<string>", line 16>, 'self.x - 10, self.y, self.x - 10, self.top'
[TRACE             ] [Builder     ] call_fn => value=(240, 250, 240, 350)
[INFO              ] [GL          ] NPOT texture support is available
[TRACE             ] [WindowSDL   ] Unhandled event ('windowenter',)
[TRACE             ] [WindowSDL   ] Unhandled event ('windowleave',)
[TRACE             ] [WindowSDL   ] Unhandled event ('windowenter',)
[TRACE             ] [WindowSDL   ] Unhandled event ('windowleave',)
[TRACE             ] [WindowSDL   ] Unhandled event ('windowenter',)
[TRACE             ] [WindowSDL   ] Unhandled event ('windowleave',)
[TRACE             ] [WindowSDL   ] Unhandled event ('windowclose',)
[INFO              ] [Base        ] Leaving application in progress...
```

**Comment by dessant** [comment]
Trace for the first example on debian stretch, a dashed line is displayed:

```python
$ python test.py -c kivy:log_level:trace
[INFO   ] [Logger      ] Record log in /home/vix/.kivy/logs/kivy_15-12-02_2.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v3.4.3+ (default, May  7 2015, 23:10:14) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 179 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[TRACE  ] [Builder     ] load file /home/vix/dev/prs/kivy/kivy/data/style.kv
[TRACE  ] [Parser      ] parsing 1265 lines
[TRACE  ] [Parser      ] got directive <kivy 1.0>
[TRACE  ] [Builder     ] build rule for <Label>
[TRACE  ] [Builder     ] build rule for <-Button,-ToggleButton>
[TRACE  ] [Builder     ] build rule for <BubbleContent>
[TRACE  ] [Builder     ] build rule for <BubbleButton>
[TRACE  ] [Builder     ] build rule for <Slider>
[TRACE  ] [Builder     ] build rule for <ProgressBar>
[TRACE  ] [Builder     ] build rule for <SplitterStrip>
[TRACE  ] [Builder     ] build rule for <Scatter>
[TRACE  ] [Builder     ] build rule for <RelativeLayout>
[TRACE  ] [Builder     ] build rule for <Image,AsyncImage>
[TRACE  ] [Builder     ] build rule for <EffectWidget>
[TRACE  ] [Builder     ] build rule for <TabbedPanelContent>
[TRACE  ] [Builder     ] build rule for <TabbedPanelStrip>
[TRACE  ] [Builder     ] build rule for <StripLayout>
[TRACE  ] [Builder     ] build rule for <TabbedPanelHeader>
[TRACE  ] [Builder     ] build rule for <Selector>
[TRACE  ] [Builder     ] build rule for <TextInput>
[TRACE  ] [Builder     ] build rule for <TextInputCutCopyPaste>
[TRACE  ] [Builder     ] build rule for <CodeInput>
[TRACE  ] [Builder     ] build rule for <TreeViewNode>
[TRACE  ] [Builder     ] build rule for <TreeViewLabel>
[TRACE  ] [Builder     ] build rule for <StencilView>
[TRACE  ] [Builder     ] build rule for <FileChooserListLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserListView>
[TRACE  ] [Builder     ] build template for [FileListEntry@FloatLayout+TreeViewNode]
[TRACE  ] [Builder     ] build rule for <FileChooserIconLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserIconView>
[TRACE  ] [Builder     ] build template for [FileIconEntry@Widget]
[TRACE  ] [Builder     ] build rule for <FileChooserProgress>
[TRACE  ] [Builder     ] build rule for <Switch>
[TRACE  ] [Builder     ] build rule for <ModalView>
[TRACE  ] [Builder     ] build rule for <Popup>
[TRACE  ] [Builder     ] build rule for <SpinnerOption>
[TRACE  ] [Builder     ] build rule for <Spinner>
[TRACE  ] [Builder     ] build rule for <ActionBar>
[TRACE  ] [Builder     ] build rule for <ActionView>
[TRACE  ] [Builder     ] build rule for <ActionSeparator>
[TRACE  ] [Builder     ] build rule for <ActionButton,ActionToggleButton>
[TRACE  ] [Builder     ] build rule for <ActionLabel>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionCheck>
[TRACE  ] [Builder     ] build rule for <ActionPreviousImage@Image>
[TRACE  ] [Builder     ] build rule for <ActionPreviousButton@Button>
[TRACE  ] [Builder     ] build rule for <ActionPrevious>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionOverflow>
[TRACE  ] [Builder     ] build rule for <ActionDropDown>
[TRACE  ] [Builder     ] build template for [AccordionItemTitle@Label]
[TRACE  ] [Builder     ] build rule for <AccordionItem>
[TRACE  ] [Builder     ] build rule for <SettingSpacer>
[TRACE  ] [Builder     ] build rule for <SettingItem>
[TRACE  ] [Builder     ] build rule for <SettingBoolean>
[TRACE  ] [Builder     ] build rule for <SettingString>
[TRACE  ] [Builder     ] build rule for <SettingPath>
[TRACE  ] [Builder     ] build rule for <SettingOptions>
[TRACE  ] [Builder     ] build rule for <SettingTitle>
[TRACE  ] [Builder     ] build rule for <SettingSidebarLabel>
[TRACE  ] [Builder     ] build rule for <SettingsPanel>
[TRACE  ] [Builder     ] build rule for <Settings>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSidebar>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSidebar>
[TRACE  ] [Builder     ] build rule for <ContentPanel>
[TRACE  ] [Builder     ] build rule for <InterfaceWithTabbedPanel>
[TRACE  ] [Builder     ] build rule for <ScrollView>
[TRACE  ] [Builder     ] build rule for <VideoPlayerPreview>
[TRACE  ] [Builder     ] build rule for <VideoPlayerAnnotation>
[TRACE  ] [Builder     ] build rule for <VideoPlayer>
[TRACE  ] [Builder     ] build rule for <CheckBox>
[TRACE  ] [Builder     ] build rule for <ScreenManager>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Input@TextInput>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Label@Label>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Selector@BoxLayout>
[TRACE  ] [Builder     ] build rule for <ColorPicker>
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[TRACE  ] [Image       ] Unable to use <gif> as loader!
[TRACE  ] 
Traceback (most recent call last):
  File "/home/vix/dev/prs/kivy/kivy/core/__init__.py", line 129, in core_register_libs
    level=0)
  File "/home/vix/dev/prs/kivy/kivy/core/image/img_ffpyplayer.py", line 7, in <module>
    import ffpyplayer
ImportError: No module named 'ffpyplayer'
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [App         ] Loading kv <./test.kv>
[DEBUG  ] [App         ] kv <./test.kv> not found
[TRACE  ] [Parser      ] parsing 19 lines
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[TRACE  ] 
Traceback (most recent call last):
  File "/home/vix/dev/prs/kivy/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/vix/dev/prs/kivy/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl
ImportError: cannot import name 'bcm'
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'3.3.0 NVIDIA 340.93'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce 9600 GSO/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 3
[INFO   ] [GL          ] Shading version <b'3.30 NVIDIA via Cg compiler'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load </home/vix/dev/prs/kivy/kivy/data/glsl/default.png>
[TRACE  ] [Image       ] '/home/vix/dev/prs/kivy/kivy/data/glsl/default.png', populate to textures (1)
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[TRACE  ] [Builder     ] Found 0 rules for <kivy.uix.floatlayout.FloatLayout object at 0x7f142add18d0>
[TRACE  ] [Builder     ] Found 0 rules for <kivy.uix.widget.Widget object at 0x7f142ad8bd48>
[DEBUG  ] [Base        ] Create provider from mouse
[DEBUG  ] [Base        ] Create provider from probesysfs
[DEBUG  ] [ProbeSysfs  ] using probesysfs!
[INFO   ] [Base        ] Start application main loop
[TRACE  ] [Builder     ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x7f142c8a7a48>, key=size, value=<code object <module> at 0x7f142ade9300, file "<string>", line 8>, 'self.size'
[TRACE  ] [Builder     ] call_fn => value=[800, 600]
[TRACE  ] [Builder     ] call_fn <kivy.graphics.vertex_instructions.Line object at 0x7f142c935d68>, key=points, value=<code object <module> at 0x7f142ade91e0, file "<string>", line 16>, 'self.x - 10, self.y, self.x - 10, self.top'
[TRACE  ] [Builder     ] call_fn => value=(240, 250, 240, 350)
[INFO   ] [GL          ] NPOT texture support is available
[TRACE  ] [WindowSDL   ] Unhandled event ('windowmoved', 560, 227)
[TRACE  ] [WindowSDL   ] Unhandled event ('windowenter',)
[TRACE  ] [WindowSDL   ] Unhandled event ('windowfocusgained',)
[TRACE  ] [WindowSDL   ] Unhandled event ('windowleave',)
[TRACE  ] [WindowSDL   ] Unhandled event ('windowenter',)
[TRACE  ] [WindowSDL   ] Unhandled event ('windowleave',)
[TRACE  ] [WindowSDL   ] Unhandled event ('windowclose',)
[INFO   ] [Base        ] Leaving application in progress...

```

**Comment by Julian-O** [comment]
I tried the very first example, Windows 11, Kivy 2.2.1, and it worked - line is dashed.

Dessant is no longer using Kivy, so I am closing as stale. It probably got fixed sometime in the past 8 years.

If you are still seeing this issue, please let us know.

**Comment by FrenzyExists** [comment]
<img width="48" alt="Screen Shot 2024-07-14 at 6 31 12 AM" src="https://github.com/user-attachments/assets/0ba9bba5-f617-406d-a383-0fe2fda5021f">

```
    canvas:

        Line:
            points: self.center_x - 1, 0, self.center_x - 1, self.height
            width: 1
            dash_length: 5
            dash_offset: 30

        Line:
            points: self.center_x - 20, 0, self.center_x - 20, self.height
            width: 2
            dash_length: 5
            dash_offset: 30
```

Sorry for re-opening, but it seems this is a recurring problem on Mac. Basically, Dashed line works for width = 1 only instead of width >= 1. Any suggestions?

**Comment by ElliotGarbus** [comment]
This is working as documented. 
"The line has 3 internal drawing modes that you should be aware of for optimal results:

If the [width](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.width) is 1.0 and [force_custom_drawing_method](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.force_custom_drawing_method) is False, then the standard GL_LINE drawing from OpenGL will be used. [dash_length](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.dash_length), [dash_offset](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.dash_offset), and [dashes](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.dashes) will work, while properties for cap and joint have no meaning here.

If the [width](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.width) is greater than 1.0 or [force_custom_drawing_method](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.force_custom_drawing_method) is True, then a custom drawing method, based on triangulation, will be used. [dash_length](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.dash_length), [dash_offset](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.dash_offset), and [dashes](https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line.dashes) do not work in this mode. Additionally, if the current color has an alpha less than 1.0, a stencil will be used internally to draw the line."

see: https://kivy.org/doc/stable/api-kivy.graphics.html#kivy.graphics.Line
