### ISSUE TITLE
Error running app on OSX 10.8.5 python 2.7.8 XCode 4.6.1

### ISSUE THREAD

**Issue by zero01alpha** [kivy/kivy#3820]
Python stack trace:

```
[INFO   ] [Logger      ] Record log in /Applications/Kivy.app/Contents/Resources/.kivy/logs/kivy_15-12-03_7.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.2 (default, Oct 11 2012, 20:14:37) 
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)]
[INFO   ] [Factory     ] 173 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
 Traceback (most recent call last):
   File "/Users/root001/python/Kivy-Area/main.py", line 1, in <module>
     from kivy.app import App
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/app.py", line 324, in <module>
     from kivy.uix.widget import Widget
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/uix/widget.py", line 167, in <module>
     from kivy.graphics.transformation import Matrix
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/graphics/__init__.py", line 89, in <module>
     from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \
   File "kivy/graphics/vbo.pxd", line 7, in init kivy.graphics.instructions (kivy/graphics/instructions.c:14004)
   File "kivy/graphics/compiler.pxd", line 1, in init kivy.graphics.vbo (kivy/graphics/vbo.c:5119)
   File "kivy/graphics/transformation.pxd", line 3, in init kivy.graphics.compiler (kivy/graphics/compiler.c:2864)
 ImportError: dlopen(/Applications/Kivy.app/Contents/Resources/kivy/kivy/graphics/transformation.so, 2): Symbol not found: ___sincos_stret
   Referenced from: /Applications/Kivy.app/Contents/Resources/kivy/kivy/graphics/transformation.so
   Expected in: /usr/lib/libSystem.B.dylib
  in /Applications/Kivy.app/Contents/Resources/kivy/kivy/graphics/transformation.so
```

link to log gist https://gist.github.com/Mike-Hamer/9795eecafbce7f950abb

**Comment by dessant** [comment]
Please reopen the bug report if there are still issues with the latest release, try installing Kivy with pip: https://kivy.org/docs/installation/installation-osx.html.
