### ISSUE TITLE
Need to import scipy.optimize.minimize before Kivy, if not, there is a bug

### ISSUE THREAD

**Issue by Paradoxeuh** [kivy/kivy#3836]
If you try : 
from kivy.app import App
from scipy.optimize import minimize

You get:

[INFO              ] [Logger      ] Record log in C:\Users\qherrero\.kivy\logs\kivy_15-12-09_8.txt
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "C:\Users\qherrero\Desktop\Imp\Repository\Non_Linear_Tool\main.py", line 12, in <module>
     from scipy.optimize import minimize
   File "C:\WinPython-64bit-3.4.3.6\python-3.4.3.amd64\lib\site-packages\scipy\optimize\__init__.py", line 221, in <module>
     from .optimize import *
   File "C:\WinPython-64bit-3.4.3.6\python-3.4.3.amd64\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
     from .linesearch import (line_search_wolfe1, line_search_wolfe2,
   File "C:\WinPython-64bit-3.4.3.6\python-3.4.3.amd64\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
     from scipy.optimize import minpack2
 ImportError: DLL load failed: The specified module could not be found.

If you switch the order, then it works.
Python 3.4
scipy 0.16
Kivy 1.9.1
Windows 7 64 bits

Cheers

**Comment by dessant** [comment]
I couldn't reporduce this with the kivy portable package, it may be a problem with WinPython.

**Comment by matham** [comment]
Hey, I think this was a problem with the kivy deps (gstreamer/sdl2/glew). Try to download again all those deps using --upgrade and I think it should be fixed.
