### ISSUE TITLE
Exception: tostring() has been removed. Please call tobytes() instead.

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3860]
It is triggered by the loading gif, and it does not always happen.

```python
from kivy.config import Config
Config.set('kivy', 'log_level', 'debug')
from kivy.app import App
from kivy.lang import Builder


kv = """
AnchorLayout:
    AsyncImage:
        source: 'https://i.imgur.com/WIFWrfT.jpg'
        size_hint: 0.5, 0.5
        # allow_stretch: True
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

```python
[ERROR             ] [Loader      ] Failed to load image <https://i.imgur.com/WIFWrfT.jpg>
Traceback (most recent call last):
  File "e:\dev\envs\py34_x86\kivy\kivy\loader.py", line 342, in _load_urllib
    data = self._load_local(_out_filename, kwargs)
  File "e:\dev\envs\py34_x86\kivy\kivy\loader.py", line 277, in _load_local
    return ImageLoader.load(filename, keep_data=True, **kwargs)
  File "e:\dev\envs\py34_x86\kivy\kivy\core\image\__init__.py", line 430, in load
    im = loader(filename, **kwargs)
  File "e:\dev\envs\py34_x86\kivy\kivy\core\image\__init__.py", line 198, in __init__
    self._data = self.load(filename)
  File "e:\dev\envs\py34_x86\kivy\kivy\core\image\img_pil.py", line 101, in load
    return list(self._img_read(im))
  File "e:\dev\envs\py34_x86\kivy\kivy\core\image\img_pil.py", line 86, in _img_read
    img_tmp.mode.lower(), img_tmp.tostring())
  File "e:\dev\envs\py34_x86\Python\lib\site-packages\PIL\Image.py", line 686, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.
```

**Comment by akshayaurora** [comment]
closed via ff17850
