### ISSUE TITLE
Getting started tutorial is broken

### ISSUE THREAD

**Issue by chriscowley** [kivy/kivy#3876]
If one does a straight copy/paste of the final code, running `main.py` results in:

```
Traceback (most recent call last):
   File "main.py", line 74, in <module>
     PongApp().run()
   File "/usr/lib64/python2.7/site-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_pygame.py", line 398, in mainloop
     self._mainloop()
   File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
     EventLoop.idle()
   File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib64/python2.7/site-packages/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/usr/lib64/python2.7/site-packages/kivy/clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib64/python2.7/site-packages/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "main.py", line 43, in update
     self.player1.bounce_ball(self.ball)
 AttributeError: 'NoneType' object has no attribute 'bounce_ball'
```

In addition to this, this contains code that is not at all mentioned in any of the other steps. For example:

```
        #bounce of paddles
        self.player1.bounce_ball(self.ball)
        self.player2.bounce_ball(self.ball)
```

and the `serve_ball` function has come from nowhere.

**Comment by Andromfins** [comment]
i couldn't replicate, works for me copied the part from [here](http://kivy.org/docs/tutorials/pong.html#connect-input-events).

**Comment by Zen-CODE** [comment]
Also works for me no problem? I can only assume you missed a part pasting? Please could you paste the exact code you are running?

'bounce_ball' is mentioned in the "Connect Input Events" section, where it explains what is does and then gives the code for this class.

'serve_ball' is explained and introduced in the note in the 'Adding Ball Animation' section.

**Comment by GammaSoul** [comment]
I had this same problem until i noticed that you had to update many parts of the kv file as well. So i just cut and past the end kv file contents at the end of the tutorial and it worked

**Comment by Zen-CODE** [comment]
@chriscowley. I'm going to be forward and close this issue. Feedback indicates everything works if followed properly. Please re-open if you feel otherwise :-)
