### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 19: ordinal not in range(128)

### ISSUE THREAD

**Issue by mikbox74** [kivy/kivy#3927]
Hello!
I see this log message after any project template selecting:

```

## Environment Info

kivy: 1.9.1
pygments: 2.1
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 1.0.1
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-XP-5.1.2600-SP3
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "D:\kivy-designer-master\designer\uix\kivy_console.py", line 285, in run_command
    self._run_command_list()
  File "D:\kivy-designer-master\designer\uix\kivy_console.py", line 293, in _run_command_list
    self.stdin.write(self.command_list.pop(0))
  File "D:\kivy-designer-master\designer\uix\kivy_console.py", line 842, in write
    self.obj.on_enter()
  File "D:\kivy-designer-master\designer\uix\kivy_console.py", line 723, in on_enter
    ' directory:' + command[3:])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 19: ordinal not in range(128)
```

Some last strings from CMD:

```
[WARNING           ] [Accordion   ] need 220px, got 100px
[WARNING           ] [Accordion   ] layout aborted.
[INFO              ] [Base        ] Leaving application in progress...
[WARNING           ] [Base        ] Unknown <wm_touch> provider
[WARNING           ] [Base        ] Unknown <wm_pen> provider
[INFO              ] [Base        ] Start application main loop
[INFO              ] [Base        ] Leaving application in progress...
 Exception KeyError: (2030,) in <functools.partial object at 0x06EE8A80> ignored

 Exception KeyError: (2210,) in <functools.partial object at 0x06F0B660> ignored

 Exception KeyError: (2252,) in <functools.partial object at 0x06F49210> ignored

 Exception KeyError: (2294,) in <functools.partial object at 0x06F67D80> ignored

 Exception KeyError: (2442,) in <functools.partial object at 0x070C3930> ignored

 Exception KeyError: (2622,) in <functools.partial object at 0x0717DF90> ignored

 Exception KeyError: (2802,) in <functools.partial object at 0x072675D0> ignored

 Exception KeyError: (6065,) in <functools.partial object at 0x0886E6C0> ignored

 Exception KeyError: (6129,) in <functools.partial object at 0x08891270> ignored
```

**Comment by aron-bordin** [comment]
Hi @mikbox74 ,

Please, post this bug in kivy-designer repository (https://github.com/kivy/kivy-designer/issues/new).

**Comment by mikbox74** [comment]
@aron-bordin , excuse me, wrong window

**Comment by KeyWeeUsr** [comment]
ref https://github.com/kivy/kivy-designer/issues/170
