### ISSUE TITLE
Packaging on Linux by pyinstaller 3.1 , No such file or directory: '/tmp/_MEIZuQsSv/kivy_install/data/style.kv'

### ISSUE THREAD

**Issue by BillBillBillBill** [kivy/kivy#3941]
PyInstaller: 3.1
Python: 2.7.11
Platform: Linux-4.2.0-1-amd64-x86_64-with-debian-8.0
Kivy:1.9.0

I want to package [my application](https://github.com/BillBillBillBill/Tickeys-linux) on Linux, but failed. I am trying for a long time. But no use. Please help or try to give some ideas how to solve this.

The run.spec: 
```python
# -*- mode: python -*-

def filter_binaries(all_binaries):
    '''Exclude binaries provided by system packages, and rely on .deb dependencies
    to ensure these binaries are available on the target machine.

    We need to remove OpenGL-related libraries so we can distribute the executable
    to other linux machines that might have different graphics hardware. If you
    bundle system libraries, your application might crash when run on a different
    machine with the following error during kivy startup:

    Fatal Python Error: (pygame parachute) Segmentation Fault

    If we strip all libraries, then PIL might not be able to find the correct _imaging
    module, even if the `python-image` package has been installed on the system. The
    easy way to fix this is to not filter binaries from the python-imaging package.

    We will strip out all binaries, except libpython2.7, which is required for the
    pyinstaller-frozen executable to work, and any of the python-* packages.
    '''

    print 'Excluding system libraries'
    import subprocess
    excluded_pkgs  = set()
    excluded_files = set()
    whitelist_prefixes = ('libpython2.7', 'python-')
    binaries = []

    for b in all_binaries:
        try:
            output = subprocess.check_output(['dpkg', '-S', b[1]], stderr=open('/dev/null'))
            p, path = output.split(':', 2)
            if not p.startswith(whitelist_prefixes):
                excluded_pkgs.add(p)
                excluded_files.add(b[0])
                print ' excluding {f} from package {p}'.format(f=b[0], p=p)
        except Exception:
            pass

    print 'Your exe will depend on the following packages:'
    print excluded_pkgs

    inc_libs = set(['libpython2.7.so.1.0'])
    binaries = [x for x in all_binaries if x[0] not in excluded_files]
    return binaries
a = Analysis(['run.py'],
             pathex=['.'],
             hiddenimports=['six','packaging', 'packaging.version', 'packaging.specifiers'],
            )
pyz = PYZ(a.pure)
binaries = filter_binaries(a.binaries)
a.datas += Tree("Resources", prefix = "Resources")
exe = EXE(pyz,
          a.scripts,
          binaries, #a.binaries,
          a.zipfiles,
          a.datas,
          name='Tickeys',
          debug=False,
          strip=None,
          upx=True,
          console=False
          )

```

result:
pyinstaller run.spec 
```
13 INFO: PyInstaller: 3.1
13 INFO: Python: 2.7.11
14 INFO: Platform: Linux-4.2.0-1-amd64-x86_64-with-debian-8.0
16 INFO: UPX is not available.
17 INFO: Extending PYTHONPATH with paths
['/home/bill/Desktop/github/Tickeys-linux',
 '/home/bill/Desktop/github/Tickeys-linux/tickeys']
17 INFO: checking Analysis
18 INFO: Building Analysis because out00-Analysis.toc is non existent
18 INFO: Initializing module dependency graph...
19 INFO: Initializing module graph hooks...
63 INFO: running Analysis out00-Analysis.toc
81 INFO: Analyzing run.py
1098 INFO: Processing pre-find module path hook   distutils
2770 INFO: Processing pre-safe import module hook   _xmlplus
6092 INFO: Processing pre-find module path hook   site
6092 INFO: site: retargeting to fake-dir '/usr/local/lib/python2.7/dist-packages/PyInstaller/fake-modules'
6111 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named win32com
6126 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named win32com
9117 INFO: Processing pre-safe import module hook   six.moves
10268 INFO: Looking for import hooks ...
10270 INFO: Processing hook   hook-distutils.py
10270 INFO: Processing hook   hook-OpenGL.py
10366 INFO: Processing hook   hook-sysconfig.py
10366 INFO: Processing hook   hook-xml.py
10424 INFO: Processing hook   hook-PIL.py
10428 INFO: Excluding import 'FixTk'
10432 INFO: Excluding import 'Tkinter'
10435 INFO: Excluding import 'PyQt5'
10438 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui
10438 WARNING:   From PIL.ImageQt removing import PyQt5.QtCore.QBuffer
10438 WARNING:   From PIL.ImageQt removing import PyQt5.QtCore
10438 WARNING:   From PIL.ImageQt removing import PyQt5.QtCore.QIODevice
10439 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui.QImage
10439 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui.qRgba
10439 WARNING:   From PIL.ImageQt removing import PyQt5.QtGui.QPixmap
10439 INFO: Excluding import 'PySide'
10442 WARNING:   From PIL.ImageQt removing import PySide.QPixmap
10442 WARNING:   From PIL.ImageQt removing import PySide.qRgba
10442 WARNING:   From PIL.ImageQt removing import PySide
10442 WARNING:   From PIL.ImageQt removing import PySide.QImage
10442 INFO: Excluding import 'PyQt4'
10448 WARNING:   From PIL.ImageQt removing import PyQt4.qRgba
10448 WARNING:   From PIL.ImageQt removing import PyQt4
10448 WARNING:   From PIL.ImageQt removing import PyQt4.QImage
10448 WARNING:   From PIL.ImageQt removing import PyQt4.QPixmap
10448 INFO: Processing hook   hook-httplib.py
10448 INFO: Processing hook   hook-pydoc.py
10451 INFO: Excluding import 'Tkinter'
10454 WARNING:   From pydoc removing import Tkinter
10454 INFO: Processing hook   hook-PyQt5.py
10455 INFO: Processing hook   hook-encodings.py
10717 INFO: Processing hook   hook-kivy.py
10718 WARNING: Hook disabled because of Kivy version < 1.9.1
10718 INFO: Processing hook   hook-PIL.Image.py
10936 INFO: Processing hook   hook-pkg_resources.py
10945 WARNING: Hidden import 'pkg_resources._vendor.packaging.markers' not found (probably old hook)
10946 INFO: Processing hook   hook-requests.py
10947 INFO: Processing hook   hook-PyQt5.QtCore.py
10980 INFO: Processing hook   hook-PyQt5.QtGui.py
11155 INFO: Processing hook   hook-setuptools.py
11156 INFO: Processing hook   hook-PIL.SpiderImagePlugin.py
11160 INFO: Excluding import 'FixTk'
11163 INFO: Excluding import 'Tkinter'
11165 INFO: Processing hook   hook-PyQt5.Qt.py
11166 INFO: Processing hook   hook-pygame.py
11166 WARNING: Hidden import 'pygame._view' not found (probably old hook)
11167 INFO: Processing hook   hook-PyQt5.QtWidgets.py
11197 INFO: Looking for ctypes DLLs
11360 WARNING: library libc.dylib required via ctypes not found
11470 INFO: Analyzing run-time hooks ...
11486 INFO: Including run-time hook 'pyi_rth_pkgres.py'
11487 INFO: Including run-time hook 'pyi_rth_kivy.py'
11538 INFO: Looking for dynamic libraries
13911 INFO: Looking for eggs
13911 INFO: Python library not in binary depedencies. Doing additional searching...
13938 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
13967 INFO: Warnings written to /home/bill/Desktop/github/Tickeys-linux/tickeys/build/run/warnrun.txt
14142 INFO: checking Tree
14142 INFO: Building Tree because out00-Tree.toc is non existent
14142 INFO: Building Tree out00-Tree.toc
14152 INFO: checking PYZ
14153 INFO: Building PYZ because out00-PYZ.toc is non existent
14153 INFO: Building PYZ (ZlibArchive) /home/bill/Desktop/github/Tickeys-linux/tickeys/build/run/out00-PYZ.pyz
15094 INFO: checking PKG
15094 INFO: Building PKG because out00-PKG.toc is non existent
15094 INFO: Building PKG (CArchive) out00-PKG.pkg
15133 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller/bootloader/Linux-64bit/run
15133 INFO: checking EXE
15133 INFO: Building EXE because out00-EXE.toc is non existent
15133 INFO: Building EXE from out00-EXE.toc
15133 INFO: Appending archive to EXE /home/bill/Desktop/github/Tickeys-linux/tickeys/build/run/run
15139 INFO: checking COLLECT
15139 INFO: Building COLLECT because out00-COLLECT.toc is non existent
15139 INFO: Building COLLECT out00-COLLECT.toc
```

Then I run the program on dist, it shows:
```
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-01-25_91.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.11 (default, Jan 11 2016, 21:04:40) 
[GCC 5.3.1 20160101]
[INFO   ] [Factory     ] 173 symbols loaded
[Errno 2] No such file or directory: '/tmp/_MEIZuQsSv/kivy_install/data/style.kv'
```

It seems that some modules were not included. But why?

**Comment by BillBillBillBill** [comment]
Problem fix, I use pyinstaller 3.0 instead of 3.1 to package it and then successed.
My spec file:
```python
# -*- mode: python -*-
# coding: utf-8
block_cipher = None

a = Analysis(['./tickeys/run.py'],
             pathex=['./tickeys'],
             binaries=None, 
             datas=[("./tickeys/tickeys.png",".")],
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             win_no_prefer_redirects=None,
             win_private_assemblies=None,
             cipher=block_cipher)
a.datas += Tree("./tickeys/Resources", prefix = "Resources")
a.datas += Tree("./tickeys/kivy", prefix = "kivy")
print a.datas
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='Tickeys',
          debug=False,
          strip=None,
          upx=True,
          console=True
          )

```
