### ISSUE TITLE
AsyncImage fails to load remote zip file

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3973]
It works only if I point the source to a local copy of the file (`source: 'spinner.zip'`).

``` python
from kivy.app import App
from kivy.lang import Builder


kv = """
AnchorLayout:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    AsyncImage:
        size_hint: None, None
        size: dp(56), dp(56)
        source: 'https://github.com/dessant/kivy-designer/releases/download/1/spinner.zip'
        anim_delay: 0.0333333333333333
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()
```

``` python
Traceback (most recent call last):
  File "E:\dev\prs\kivy\kivy\loader.py", line 342, in _load_urllib
    data = self._load_local(_out_filename, kwargs)
  File "E:\dev\prs\kivy\kivy\loader.py", line 277, in _load_local
    return ImageLoader.load(filename, keep_data=True, **kwargs)
  File "E:\dev\prs\kivy\kivy\core\image\__init__.py", line 433, in load
    raise Exception('Unknown <%s> type, no loader found.' % ext)
Exception: Unknown <o> type, no loader found.
an integer is required (got type NoneType)
```

**Comment by KeyWeeUsr** [comment]
Works fine with https://github.com/kivy/kivy/raw/master/examples/widgets/sequenced_images/data/images/cube.zip, closing.
