### ISSUE TITLE
Explicitly state the need to install docutils and pigments in the relevant modules

### ISSUE THREAD

**Issue by miohtama** [kivy/kivy#4038]
`RstDocument` assumes presence of `docutils` package.

However this is not deployed by default on Android when you add kivy package in requirements, resulting the following error. I guess it's a missing dependency somewhere:

```
02-26 17:11:00.978 16023 16038 I python  :  Traceback (most recent call last):
02-26 17:11:00.979 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/app/main.py", line 9, in <module>
02-26 17:11:00.979 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/app/webkivy/main.py", line 78, in run
02-26 17:11:00.979 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 802, in run
02-26 17:11:00.980 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/app/webkivy/main.py", line 137, in build
02-26 17:11:00.980 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/app/webkivy/main.py", line 125, in reset_landing_screen
02-26 17:11:00.981 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/relativelayout.py", line 255, in __init__
02-26 17:11:00.981 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
02-26 17:11:00.982 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/layout.py", line 72, in __init__
02-26 17:11:00.982 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/widget.py", line 320, in __init__
02-26 17:11:00.982 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1970, in apply
02-26 17:11:00.983 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 2085, in _apply_rule
02-26 17:11:00.983 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 2085, in _apply_rule
02-26 17:11:00.984 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 2044, in _apply_rule
02-26 17:11:00.984 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/factory.py", line 139, in __getattr__
02-26 17:11:00.985 16023 16038 I python  :    File "/home/kivy/android-remote-python/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/rst.py", line 76, in <module>
02-26 17:11:00.985 16023 16038 I python  :  ImportError: No module named docutils.parsers
02-26 17:11:01.050 16023 16038 I python  : Python for android ended.
```

**Comment by dessant** [comment]
This is only the case if you use the rst widget, docutils is now installed by default on desktop (kivy master), but i would think it should not be added as a requirement for all android apks.
You can add the dependency to your requirements in buildozer.

We should document the dependency here:
https://kivy.org/docs/api-kivy.uix.rst.html

**Comment by dessant** [comment]
Actually it's already linked there, maybe we could we more explicit about the need for installing the dependency.

Same for pygments:
https://github.com/kivy/kivy/blob/c691091d1c3111e6625e92d1886ae80214b867aa/kivy/uix/codeinput.py#L15

**Comment by Neex101** [comment]
For anyone without the package, and just wanting to get this going:

`sudo apt-get install python-pip`
`sudo pip install docutils`
