### ISSUE TITLE
Kivy logger doesn't correctly handle Logger.exception(e)

### ISSUE THREAD

**Issue by miohtama** [kivy/kivy#4039]
Python loggers support logging exceptions. In this case the traceback of the exception is printed in the logs.

This does not work with Kivy's `Logger` object.

        try:
           # ...
        except Exception as e:
            Logger.exception(e)

Results to:

     Traceback (most recent call last):
       File "webkivy/main.py", line 157, in <module>
         RemoteRunnerApp().run()
       File "webkivy/main.py", line 88, in run
         super(RemoteRunnerApp, self).run()
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/app.py", line 828, in run
         runTouchApp()
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/base.py", line 487, in runTouchApp
         EventLoop.window.mainloop()
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 619, in mainloop
         self._mainloop()
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 362, in _mainloop
         EventLoop.idle()
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/base.py", line 330, in idle
         self.dispatch_input()
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/base.py", line 315, in dispatch_input
         post_dispatch_input(*pop(0))
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/base.py", line 281, in post_dispatch_input
         wid.dispatch('on_touch_up', me)
       File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7699)
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/uix/behaviors/button.py", line 138, in on_touch_up
         self.dispatch('on_release')
       File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7654)
       File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:13497)
       File "kivy/_event.pyx", line 1108, in kivy._event.EventObservers._dispatch (kivy/_event.c:12329)
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/lang.py", line 1557, in custom_callback
         exec(__kvlang__.co_value, idmap)
       File "<string>", line 19, in <module>
       File "webkivy/main.py", line 121, in run_script
         Logger.exception(e)
       File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1198, in exception
         self.error(msg, *args, **kwargs)
       File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1191, in error
         self._log(ERROR, msg, args, **kwargs)
       File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1284, in _log
         self.handle(record)
       File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1294, in handle
         self.callHandlers(record)
       File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1334, in callHandlers
         hdlr.handle(record)
       File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 757, in handle
         self.emit(record)
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/logger.py", line 218, in emit
         self._write_message(message)
       File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/logger.py", line 185, in _write_message
         FileHandler.fd.write(record.msg)
     TypeError: expected a character buffer object

**Comment by haoflynet** [comment]
The Logger.exception  only receive string, not the Except, although `print(e)` is string, but `type(e)` is Except. For example:

    import codecs

    fp = codecs.open('test.txt', 'w', 'utf-8')
    fp.write('test text')

    try:
        print(a)
    except NameError as e:
        print(type(e))
        fp.write(e)

**Comment by miohtama** [comment]
@matham: Thanks!

I just dug a little bit deeper what Python logging interface implies and there is a function called `formatException`: https://hg.python.org/cpython/file/tip/Lib/logging/__init__.py#l514

It is used when `record.exc_info` is checked https://hg.python.org/cpython/file/tip/Lib/logging/__init__.py#l555 - this is what the issue was originally about.

**Comment by matham** [comment]
Yes, that's what I added to call format: https://github.com/kivy/kivy/commit/78a0c8680d71a476dc5c63d6bcc5c8530ae43344#diff-c4b929a31ef8afab2a4f426efae2660aR183.

**Comment by miohtama** [comment]
@matham: Gotcha! Did not spot on the first time.

**Comment by matham** [comment]
All the other stuff is about encodings which I copied from `emit` from the stream handler there in py2.
