### ISSUE TITLE
Some properties are not registered in Factory

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4046]
```python
from kivy.app import App
from kivy.factory import Factory
from kivy.uix.boxlayout import BoxLayout


class Test(BoxLayout):
    a = Factory.DictProperty()
    b = Factory.VariableListProperty()
    c = Factory.ConfigParserProperty()

class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```

```python
 Traceback (most recent call last):
   File "E:\dev\prs\main\test2.py", line 6, in <module>
     class Test(BoxLayout):
   File "E:\dev\prs\main\test2.py", line 7, in Test
     a = Factory.DictProperty()
   File "E:\dev\prs\kivy\kivy\factory.py", line 131, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <DictProperty>
```

**Comment by ViniciusAugustoRR** [comment]
same problem
