### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by qwertologe** [kivy/kivy#4066]
I use kivy 1.9.1-dev. During boot of my raspberry with official touch display, i start myradio https://github.com/qwertologe/myradio (no X running at this time). Sometimes it is not working. I am not sure if the problem exists before or with the first touch since it starts in backlight-off mode.

```
[INFO          ]
[HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO          ]
[MTD           ] </dev/input/event0> range touch minor is 0 - 0
[INFO          ]
[HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO          ]
[MTD           ] </dev/input/event0> range pressure is 0 - 255
[INFO          ]
[MTD           ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO          ]
[HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480
[INFO          ]
[MTD           ] </dev/input/event0> rotation set to 0
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
    File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 324, in _thread_run
      process([l_points[x] for x in _changes])
      File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 198, in process
        touch = MTDMotionEvent(device, tid, args)
        File "/usr/local/lib/python2.7/dist-packages/kivy/input/motionevent.py", line 287, in __init__
          self.depack(args)
          File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 51, in depack
            self.sy = args['y']
            KeyError: 'y'

**Comment by dessant** [comment]
Could you update to master and see if the issue is still there?
