### ISSUE TITLE
Font not displayed correctly, Ubuntu

### ISSUE THREAD

**Issue by abhigenie92** [kivy/kivy#4100]
I am getting such buttons in kivy
![screenshot from 2016-03-19 07-07-24](https://cloud.githubusercontent.com/assets/12474640/13895937/4f016a92-eda1-11e5-8937-5901e87b32e3.png)

Errors while executing kivy's file:
```
ERROR  ] [WinPygame   ] unable to set icon
Traceback (most recent call last):
  File "/home/abhishek/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 215, in set_icon
    self._set_icon_standard(filename)
  File "/home/abhishek/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 223, in _set_icon_standard
    im = pygame.image.load(filename)
error: File is not a Windows BMP file

ERROR  ] [WinPygame   ] unable to set icon
Traceback (most recent call last):
  File "/home/abhishek/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 215, in set_icon
    self._set_icon_standard(filename)
  File "/home/abhishek/anaconda2/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 223, in _set_icon_standard
    im = pygame.image.load(filename)
error: File is not a Windows BMP file

```
I referred https://kivy.org/docs/installation/installation-linux.html . I am using Ubuntu.
Installation script
```
#!/bin/sh
dependencies=" python-pip build-essential git python python-dev ffmpeg libsdl2-dev \
libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev \
libavcodec-dev zlib1g-dev python-kivy python-pygame mercurial libsdl-image1.2-dev \
libsdl-image1.2-dev libsdl-image1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev  zlib1g-dev\
libsdl-ttf2.0-dev libsmpeg-dev libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev "
sudo add-apt-repository ppa:kivy-team/kivy
sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install -y $dependencies
sudo apt-get install ffmpeg   
```

**Comment by dessant** [comment]
Installing those sdl 1.2 dependencies should not be needed, nor pygame. Try removing them and uninstalling kivy, then installing it again from the ppa.

**Comment by abhigenie92** [comment]
Which dependencies to remove?
libsdl-image1.2-dev libsdl-image1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev \
 libsdl1.2-dev  python-pygame

**Comment by dessant** [comment]
All of them, the ppa should pull in the right dependencies.
