### ISSUE TITLE
SoftInput mode does not work on iOS with latest stable version

### ISSUE THREAD

**Issue by mrhdias** [kivy/kivy#4129]
The 'pan', 'resize' end 'below_target' softinput_mode does not work on iOS (9.2) with kivy version 1.9.1.

The code I use for this on Android however does not work on iOS

```
import kivy
from kivy.app import App
from kivy.core.window import Window
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput
from kivy.uix.label import Label

Window.softinput_mode = 'below_target'

class Test(App):
    def build(self):
        box = BoxLayout(size_hint=(1, 1),
                        orientation='vertical',
                        padding=8,
                        spacing=8)

        for n in range(0, 5):
            box.add_widget(Label(text='Test %s' % (str(n))))
            box.add_widget(TextInput(text=''))

        return box

if __name__ == '__main__':
    Test().run()
```

**Comment by ryandoherty** [comment]
I can confirm this does not work for our app also. 

![]
(http://i.imgur.com/dA3vkwm.jpg)

**Comment by brentpicasso** [comment]
Also confirming this on latest kivy-ios with 1.10.1.  RIght now, when one of these softinput modes is set, the iOS app locks up/freezes with errors.  

This is a critical bug to fix, because the iOS app is useless if we cannot correctly type into fields. 

Logged here in kivy-ios: https://github.com/kivy/kivy-ios/issues/367

Repro is easy:

When setting any valid softinput_mode, the app crashes.  repro script and stack track below:


* Python 2.7, XCode 10

Happens with any valid value:  ‘pan’, ‘resize’, ‘below_target’

<pre>
import kivy
kivy.require('1.10.1') # replace with your current kivy version !
from kivy.app import App
from kivy.uix.textinput import TextInput
from kivy.core.window import Window

class MyApp(App):
    def build(self):
        Window.softinput_mode = 'below_target'
        return TextInput(text='Hello world')

if __name__ == '__main__':
    MyApp().run()
</pre>

<pre>
2019-03-13 07:31:50.352677-0700 kivy_hellotext[420:85142] [DYMTLInitPlatform] platform initialization successful

2019-03-13 07:31:50.663015-0700 kivy_hellotext[420:85038] Could not load IOSurface for time string. Rendering locally instead.

2019-03-13 07:31:50.757276-0700 kivy_hellotext[420:85038] [framework] CUIThemeStore: No theme registered with id=0

2019-03-13 07:31:50.877317-0700 kivy_hellotext[420:85038] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown

2019-03-13 07:31:50.877437-0700 kivy_hellotext[420:85038] PythonHome is: /var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app

2019-03-13 07:31:50.879578-0700 kivy_hellotext[420:85038] Initializing python

2019-03-13 07:31:51.034390-0700 kivy_hellotext[420:85038] Running main.py: /var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/YourApp/main.pyo

[INFO   ] [Kivy        ] v1.10.1

[INFO   ] [Python      ] v2.7.1 (r271:86832, Nov 30 2018, 12:13:19) 

[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

[INFO   ] [Factory     ] 194 symbols loaded

[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)

[INFO   ] [Text        ] Provider: sdl2

[INFO   ] [Window      ] Provider: sdl2

[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system

[INFO   ] [GL          ] Backend used <sdl2>

[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0 Apple A7 GPU - 130.1>

[INFO   ] [GL          ] OpenGL vendor <Apple Inc.>

[INFO   ] [GL          ] OpenGL renderer <Apple A7 GPU>

[INFO   ] [GL          ] OpenGL parsed version: 2, 0

[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>

[INFO   ] [GL          ] Texture max size <4096>

[INFO   ] [GL          ] Texture max units <8>

[INFO   ] [Window      ] auto add sdl2 input provider

[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found

Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found

[INFO   ] [GL          ] NPOT texture support is available

[INFO   ] [Base        ] Start application main loop

2019-03-13 07:33:21.756268-0700 kivy_hellotext[420:85038] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles

2019-03-13 07:33:21.758021-0700 kivy_hellotext[420:85038] [MC] Reading from public effective user settings.

2019-03-13 07:33:22.482374-0700 kivy_hellotext[420:85038] [Common] _BSMachError: port 8103; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

[INFO   ] [Clipboard   ] Provider: sdl2

[INFO   ] [Base        ] Leaving application in progress...

 Traceback (most recent call last):

   File "/Users/macmini/git-projects/kivy-ios/kivy_hellotext-ios/YourApp/main.py", line 17, in <module>

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/app.py", line 826, in run

     runTouchApp()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/base.py", line 502, in runTouchApp

     EventLoop.window.mainloop()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop

     self._mainloop()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop

     EventLoop.idle()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/base.py", line 337, in idle

     Clock.tick()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick

     self._process_events()

   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events

   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events

   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events

   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/animation.py", line 346, in _update

     setattr(widget, key, value)

   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__

   File "kivy/properties.pyx", line 524, in kivy.properties.Property.set

   File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch

   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch

   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 898, in <lambda>

     self.bind(_kheight=lambda *args: self.update_viewport())

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1434, in update_viewport

     glViewport(x, y, w, _h)

   File "kivy/graphics/opengl.pyx", line 1548, in kivy.graphics.opengl.glViewport

 ValueError: cannot convert float NaN to integer

2019-03-13 07:33:22.655023-0700 kivy_hellotext[420:85038] Application quit abnormally!

2019-03-13 07:33:22.725459-0700 kivy_hellotext[420:85038] Leaving
</pre>

**Comment by brentpicasso** [comment]
Bump on this issue.
