### ISSUE TITLE
kivy deb package misses fonts-droid as a dependency

### ISSUE THREAD

**Issue by schoolsplay** [kivy/kivy#4141]
I installed the 1.9.1 kivy deb on a bare bones machine with only a minimal desktop environment and noticed that the current 1.9.1 deb misses fonts-droid as a dependency.
Without that package kivy crashes on the first attempt to do anything with text.

**Comment by dessant** [comment]
Are you using the stable ppa published on launchpad?

**Comment by schoolsplay** [comment]
Yes.

```
$ cat /etc/apt/sources.list.d/kivy-team-kivy-trusty.list 
deb http://ppa.launchpad.net/kivy-team/kivy/ubuntu trusty main
deb-src http://ppa.launchpad.net/kivy-team/kivy/ubuntu trusty main

$ dpkg -l | grep kivy
ii  python-kivy                                                 1.9.0-3~stable0+201511191651~pkg79~ubuntu14.04.1    amd64        Kivy - Multimedia / Multitouch framework - Python 2.7 modules
ii  python-kivy-bin                                             1.9.0-3~stable0+201511191651~pkg79~ubuntu14.04.1    amd64        Kivy - Multimedia / Multitouch framework - Python 2.7 binaries
ii  python-kivy-common                                          1.9.0-3~stable0+201511191651~pkg79~ubuntu14.04.1    amd64        Kivy - Multimedia / Multitouch framework - Python 2.7 common files
```

**Comment by dessant** [comment]
@schoolsplay, Droid Sans was removed in 1.9.1, i'm not sure from where does the issue come from, there is no reference to droid in the packaging scripts either.
https://github.com/kivy/kivy-sdk-packager/search?utf8=%E2%9C%93&q=droid&type=Code

Please share the full log of running a kivy app.

**Comment by schoolsplay** [comment]
I can't find the string   'DroidSans.ttf' anywhere in my project so I have no idea where it comes from.
(The project is to big and not free to share)

```
[INFO   ] [Logger      ] Record log in /home/stas/.kivy/logs/kivy_16-04-03_8.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
.....
[INFO   ] [Base        ] Leaving application in progress...
 2016-04-03 16:45:51,174 - sp.Starter.Starter - ERROR - Uncatched Error: Label: File 'DroidSans.ttf' not found
 Traceback (most recent call last):
   File "/home/stas/GIT/braintrainer.kivy/ViewStarter.py", line 35, in start
     self.ViewMain.start(error=error)
   File "/home/stas/GIT/braintrainer.kivy/ControllerPlainGames.py", line 1170, in start
     self.MA.run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 515, in tick
     self._process_events()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 647, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 406, in tick
     ret = callback(self._dt)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/label.py", line 356, in texture_update
     self._label.refresh()
   File "/usr/lib/python2.7/dist-packages/kivy/core/text/__init__.py", line 633, in refresh
     self.resolve_font_name()
   File "/usr/lib/python2.7/dist-packages/kivy/core/text/__init__.py", line 261, in resolve_font_name
     raise IOError('Label: File %r not found' % fontname)
 IOError: Label: File 'DroidSans.ttf' not found
```

**Comment by schoolsplay** [comment]
But I can't reproduce this with a simpe kivy test app.
So I fear it's something in my setup :-(

**Comment by dessant** [comment]
You've may be using `font_name = 'DroidSans'` somewhere.
