### ISSUE TITLE
Couldn't import App in anaconda env

### ISSUE THREAD

**Issue by enfeizhan** [kivy/kivy#4147]
I followed the steps on this [page](https://github.com/kivy/kivy/wiki/Connecting-Kivy-with-Anaconda-%28OSX%29). Everything looked fine until I tried to import the App class for the first example. It complains couldn't find kivy._event module:

```
$ kivyconda
discarding /Users/xxxx/miniconda/envs/kivy/bin from PATH
prepending /Users/xxxxx/miniconda/envs/kivy/bin to PATH
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kivy.app import App
[INFO              ] [Logger      ] Record log in /Applications/Kivy3.app/Contents/Resources/.kivy/logs/kivy_16-04-06_3.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09)
[GCC 4.2.1 (Apple Inc. build 5577)]
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/base.py", line 30, in <module>
     from kivy.event import EventDispatcher
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/event.py", line 8, in <module>
     import kivy._event
 ImportError: No module named 'kivy._event'
>>>
```

However it runs well in kivy's own virtual python environment:

```
$ kivy
Python 3.5.0 (default, Dec 12 2015, 05:50:29)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kivy.app import App
[INFO              ] [Logger      ] Record log in /Applications/Kivy3.app/Contents/Resources/.kivy/logs/kivy_16-04-06_4.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.5.0 (default, Dec 12 2015, 05:50:29)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
>>>
```

No idea why one can find it but the other can't if it's there. I know I am actually in miniconda but can it be the reason?

**Comment by dessant** [comment]
Please reopen the bug report if there are still issues with the latest release: https://kivy.org/docs/installation/installation-osx.html.
