### ISSUE TITLE
TextInput crashes if it is focused while the widget is disabled

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4196]
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.uix.boxlayout import BoxLayout

kv = """
<Test>:
    TextInput:
        id: form
        disabled: True
    Button:
        text: 'Focus it'
        on_press: root.callback()
"""

Builder.load_string(kv)


class Test(BoxLayout):

    def callback(self):
        self.ids.form.focus = True


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```

```python
 Traceback (most recent call last):
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12723)
   File "E:\dev\prs\kivy\kivy\uix\textinput.py", line 1635, in _on_textinput_focused
     self.focus = value
   File "kivy\properties.pyx", line 410, in kivy.properties.Property.__set__ (kivy\properties.c:5172)
   File "kivy\properties.pyx", line 448, in kivy.properties.Property.set (kivy\properties.c:5934)
   File "kivy\properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy\properties.c:6615)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13524)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12723)
   File "E:\dev\prs\kivy\kivy\uix\textinput.py", line 1635, in _on_textinput_focused
     self.focus = value
   File "kivy\properties.pyx", line 410, in kivy.properties.Property.__set__ (kivy\properties.c:5172)
   File "kivy\properties.pyx", line 448, in kivy.properties.Property.set (kivy\properties.c:5934)
   File "kivy\properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy\properties.c:6615)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13524)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12723)
   File "E:\dev\prs\kivy\kivy\uix\textinput.py", line 1635, in _on_textinput_focused
     self.focus = value

   ...

   File "kivy\properties.pyx", line 410, in kivy.properties.Property.__set__ (kivy\properties.c:5172)
   File "kivy\properties.pyx", line 448, in kivy.properties.Property.set (kivy\properties.c:5934)
   File "kivy\properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy\properties.c:6615)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13524)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12723)
   File "E:\dev\prs\kivy\kivy\uix\textinput.py", line 1635, in _on_textinput_focused
     self.focus = value
   File "kivy\properties.pyx", line 410, in kivy.properties.Property.__set__ (kivy\properties.c:5172)
   File "kivy\properties.pyx", line 448, in kivy.properties.Property.set (kivy\properties.c:5934)
   File "kivy\properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy\properties.c:6615)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13524)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12723)
   File "E:\dev\prs\kivy\kivy\uix\behaviors\focus.py", line 388, in _on_focus
     self._bind_keyboard()
   File "E:\dev\prs\kivy\kivy\uix\behaviors\focus.py", line 407, in _bind_keyboard
     self.focus = False
   File "kivy\properties.pyx", line 410, in kivy.properties.Property.__set__ (kivy\properties.c:5172)
   File "kivy\properties.pyx", line 448, in kivy.properties.Property.set (kivy\properties.c:5934)
   File "kivy\properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy\properties.c:6615)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13524)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12723)
   File "E:\dev\prs\kivy\kivy\uix\behaviors\focus.py", line 390, in _on_focus
     self._unbind_keyboard()
   File "E:\dev\prs\kivy\kivy\uix\behaviors\focus.py", line 429, in _unbind_keyboard
     del FocusBehavior._keyboards[keyboard]
 KeyError: <kivy.core.window.Keyboard object at 0x03BD8570>
```

**Comment by dessant** [comment]
Works with 1.8.0, but crashes with 1.9.0.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/commit/ccb1339ea40084f1b152e006350d306e60f711df.
