### ISSUE TITLE
using `cancel_all` with largs on animation sequence breaks.

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#4222]
```
from kivy.animation import Animation
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.clock import Clock


class AApp(App):
    def build(self):
        w = Widget()
        a = Animation(width=200) + Animation(height=200)
        a.start(w)

        def crash(*args):
            a.cancel_all(w, 'width')

        Clock.schedule_once(crash, .5)
        return w

if __name__ == '__main__':
    AApp().run()
```

```
 Traceback (most recent call last):
   File "test.py", line 20, in <module>
     AApp().run()
   File "/home/gabriel/kivy/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/gabriel/kivy/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/gabriel/kivy/kivy/core/window/window_sdl2.py", line 621, in mainloop
     self._mainloop()
   File "/home/gabriel/kivy/kivy/core/window/window_sdl2.py", line 364, in _mainloop
     EventLoop.idle()
   File "/home/gabriel/kivy/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/home/gabriel/kivy/kivy/clock.py", line 521, in tick
     self._process_events()
   File "/home/gabriel/kivy/kivy/clock.py", line 653, in _process_events
     event.tick(self._last_tick, remove)
   File "/home/gabriel/kivy/kivy/clock.py", line 412, in tick
     ret = callback(self._dt)
   File "test.py", line 14, in crash
     a.cancel_all(w, 'width')
   File "/home/gabriel/kivy/kivy/animation.py", line 191, in cancel_all
     animation.cancel_property(widget, x)
   File "/home/gabriel/kivy/kivy/animation.py", line 248, in cancel_property
     props['properties'].pop(prop, None)
 TypeError: 'bool' object has no attribute '__getitem__'
```

`Sequence` should probably override `cancel_property` and go into its current animation to cancel it for this property, but it's harder to decide what to do for future sub-animations.

**Comment by dessant** [comment]
Fixed by https://github.com/kivy/kivy/pull/4223.
