### ISSUE TITLE
Remove deprecated video and audio providers: pygst, pyglet and pygi

### ISSUE THREAD

**Issue by Zonzely** [kivy/kivy#4224]
hello!
I run a demo named **Camera Example**  in kivy website and get error ---**No module named 'pygst'**.
the link of demo  is [https://kivy.org/docs/examples/gen__camera__main__py.html](url).
my OS is  ubuntu15.04  and i use python3. the detailed error is following:

```
zz@zz-Aspire-E1-471G:~/data/code/kivy_practice/camera$ python3 test.py [INFO   ] [Logger      ] Record log in /home/zz/.kivy/logs/kivy_16-04-26_47.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 10.5.9'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Ivybridge Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[CRITICAL] [Camera      ] Unable to find any valuable Camera provider at all!
pygst - ImportError: No module named 'pygst'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/camera/camera_pygst.py", line 15, in <module>
    import pygst

opencv - ImportError: No module named 'cv'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/camera/camera_opencv.py", line 20, in <module>
    import cv

[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2123, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1189)
   File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy/properties.c:4968)
   File "kivy/properties.pyx", line 733, in kivy.properties.ListProperty.set (kivy/properties.c:10856)
   File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (kivy/properties.c:5666)
   File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy/properties.c:6315)
   File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:12786)
   File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy/_event.c:12085)
   File "/usr/lib/python3/dist-packages/kivy/uix/camera.py", line 103, in _on_index
     resolution=self.resolution, stopped=True)
 TypeError: 'NoneType' object is not callable

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "test.py", line 24, in <module>
     TestCamera().run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "test.py", line 22, in build
     return Builder.load_string(kv)
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1921, in load_string
     self._apply_rule(widget, parser.root, parser.root)
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2130, in _apply_rule
     e), cause=tb)
 kivy.lang.BuilderException: Parser: File "<inline>", line 6:
 ...
       4:    Camera:
       5:        id: camera
 >>    6:        resolution: (640, 480)
       7:        play: False
       8:    ToggleButton:
 ...
 TypeError: 'NoneType' object is not callable
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2123, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1189)
   File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy/properties.c:4968)
   File "kivy/properties.pyx", line 733, in kivy.properties.ListProperty.set (kivy/properties.c:10856)
   File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (kivy/properties.c:5666)
   File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy/properties.c:6315)
   File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:12786)
   File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy/_event.c:12085)
   File "/usr/lib/python3/dist-packages/kivy/uix/camera.py", line 103, in _on_index
     resolution=self.resolution, stopped=True)


```

**Comment by dessant** [comment]
@Zonzely, you are missing some dependenties.

@tito, can pygst be deprecated in favor of gstplayer?
https://github.com/kivy/kivy/blob/master/kivy/core/video/video_pygst.py
https://github.com/kivy/kivy/blob/master/kivy/core/video/video_gstplayer.py

**Comment by akshayaurora** [comment]
Gstplayer replaced pygst so pigs should be removed.

**Comment by dessant** [comment]
Ok, so we'll remove these:
https://github.com/kivy/kivy/blob/master/kivy/core/video/video_pygst.py
https://github.com/kivy/kivy/blob/master/kivy/core/video/video_pyglet.py
https://github.com/kivy/kivy/blob/master/kivy/core/video/video_gi.py

**Comment by FeralBytes** [comment]
From dessant: and this can be added to the delete list https://github.com/kivy/kivy/blob/master/kivy/core/camera/camera_videocapture.py

**Comment by dessant** [comment]
@matham, @Cheaterman: is this superseded by ffpyplayer and should it be removed?
https://github.com/kivy/kivy/blob/master/kivy/core/video/video_ffmpeg.py

**Comment by matham** [comment]
I never used it, so I'm not sure. But I'm guessing so. @tito would if there's any reason for it.

But I suspect it should not be removed in one cycle. It needs to be first deprecated and then removed.

**Comment by dessant** [comment]
A summary of the removed providers:

* audio: pygst, gi
* video: pygst, gi, pyglet
* camera: pygst, videocapture

**Comment by dessant** [comment]
@thopiekar, several files have been removed, this should affect the daily ppa.

**Comment by thopiekar** [comment]
Thank you for the mention.

Has it already been merged?

Thanks

**Comment by dessant** [comment]
Yes, the providers listed above.

**Comment by thopiekar** [comment]
No problem occurred. Looks like every pattern fit to at least one file.
Well done! No work for me :smile:

**Comment by dessant** [comment]
@thopiekar, on nice! 😺
