### ISSUE TITLE
AttributeError: 'super' object has no attribute '__getattr__' when trying to profile Kivy app

### ISSUE THREAD

**Issue by AvivC** [kivy/kivy#4250]
Hey,

I'm trying to profile my Kivy application using:

    python -m cProfile main.py

After a few seconds, during which the screen is black and cProfile outputs some lines to the console, the following exception is raised:

```
Traceback (most recent call last):
   File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
   File "c:\python27\Lib\runpy.py", line 72, in _run_code
     exec code in run_globals
   File "c:\python27\Lib\cProfile.py", line 199, in <module>
     main()
   File "c:\python27\Lib\cProfile.py", line 192, in main
     runctx(code, globs, None, options.outfile, options.sort)
   File "c:\python27\Lib\cProfile.py", line 49, in runctx
     prof = prof.runctx(statement, globals, locals)
   File "c:\python27\Lib\cProfile.py", line 140, in runctx
     exec cmd in globals, locals
   File "main.py", line 26, in <module>
     GameApp().run()
   File "C:\Users\Aviv\Envs\game\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Users\Aviv\Envs\game\lib\site-packages\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\Aviv\Envs\game\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "C:\Users\Aviv\Envs\game\lib\site-packages\kivy\core\window\window_sdl2.py", line 403, in _mainloop
     x, y = self._fix_mouse_pos(x, y)
   File "C:\Users\Aviv\Envs\game\lib\site-packages\kivy\core\window\window_sdl2.py", line 358, in _fix_mouse_pos
     self.mouse_pos = x, self.system_size[1] - y
   File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
   File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
   File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
   File "game\opening_screen.py", line 22, in _on_mouse_pos
     if self.ids.start_button.collide_point(*position):
   File "kivy\properties.pyx", line 757, in kivy.properties.ObservableDict.__getattr__ (kivy\properties.c:11882)
 AttributeError: 'super' object has no attribute '__getattr__'
```

The program runs fine without the profiler, using simply `python main.py`.

What seems to be the problem? And how can I profile my Kivy application?

Please note I asked the same question in the Google group and on StackOverflow. Please let me know if this is considered not okay.

**Comment by matham** [comment]
I have seen this before. It's a bug in the property code at https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L759. The code is just wrong there because as the error states there's no `__getattr__` in dict. I think there may similar bugs in other properties.

**Comment by AvivC** [comment]
With the help of Yoav Glazner on StackOverflow I found the problem :)

[The docs](https://kivy.org/docs/api-kivy.app.html#profiling-with-on-start-and-on-stop) state a Kivy app can't be profiled using `pythom -m cProfile main.py`, it has to be done differently:

```
import cProfile

class MyApp(App):
    def on_start(self):
        self.profile = cProfile.Profile()
        self.profile.enable()

    def on_stop(self):
        self.profile.disable()
        self.profile.dump_stats('myapp.profile')
```

I have also found the tool [profilehooks](https://pypi.python.org/pypi/profilehooks) incredibly useful, it lets you profile a specific function using a decorator.

Hope this helps someone in the future.
Cheers :)
