### ISSUE TITLE
graphics.vertex_instructions.Line - object has no attribute 'dash_lenght'

### ISSUE THREAD

**Issue by jligeza** [kivy/kivy#4407]
The Line is [supposed to](https://kivy.org/docs/api-kivy.graphics.vertex_instructions.html?highlight=dashed#kivy.graphics.vertex_instructions.Line.dash_length) have a `dash_length` attribute, but an attempt to use it throws an error. That is while using python 2.7 and kivy 1.9.2 dev.

Code:
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.lang import Builder

gui = '''
FloatLayout:
    canvas:
        Line:
            points: 100, 100, 200, 200
            dash_offset: 10
            dash_lenght: 10
            width: 1
'''


class Test(App):
    def build(self):
        return Builder.load_string(gui)


Test().run()
```
Error log:
```
[INFO   ] [Logger      ] Record log in /home/stefan/.kivy/logs/kivy_16-06-17_32.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.1.3>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Sandybridge Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 22, in <module>
     Test().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "main.py", line 19, in build
     return Builder.load_string(gui)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 379, in load_string
     self._apply_rule(widget, parser.root, parser.root)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 502, in _apply_rule
     rule.canvas_root, rootrule)
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 827, in _build_canvas
     '{}: {}'.format(e.__class__.__name__, e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 7:
 ...
       5:            points: 100, 100, 200, 200
       6:            dash_offset: 10
 >>    7:            dash_lenght: 10
       8:            width: 1
 ...
 AttributeError: 'kivy.graphics.vertex_instructions.Line' object has no attribute 'dash_lenght'
   File "/usr/local/lib/python2.7/dist-packages/kivy/lang/builder.py", line 822, in _build_canvas
     setattr(instr, key, value)

```

**Comment by bionoid** [comment]
Your example has a typo; ``dash_lenght``
