### ISSUE TITLE
MTDMotionEvent KeyError  in 1.9.0-3build1

### ISSUE THREAD

**Issue by davelawr** [kivy/kivy#4422]
kivy 1.9.0-3build1 on ubuntu xenial, I get occasional KeyErrors in mtdev.py:
```
Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run()
   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 304, in _thread_run
     process([l_points[x] for x in _changes])
   File "/usr/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 178, in process
     touch = MTDMotionEvent(device, tid, args)
   File "/usr/lib/python2.7/dist-packages/kivy/input/motionevent.py", line 286, in __init__
     self.depack(args)
   File "/usr/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 51, in depack
     self.sx = args['y']
 KeyError: 'y'
```
sometimes KeyError: 'x'

Printing args in these cases shows, e.g. {'x': 1.0568387681159421, 'id': 597}

**Comment by pigant** [comment]
I don't have  a log but I have also that exception, on Debian Jessie with kivy 1.9.2 using a screen touch, sometimes raises the exception,  not all the time.

**Comment by davelawr** [comment]
see also https://github.com/kivy/kivy/issues/3758

on the RPi touchscreen, once the KeyError has happened, the mtdev has died and no more touch events happen
