### ISSUE TITLE
touchring.py KeyError Exception _touch_move()

### ISSUE THREAD

**Issue by SectorNine50** [kivy/kivy#4479]
Running **Python 3.4.2** and **Kivy v1.9.2-dev0** on **KivyPie 0.9b**

I have some code that manages the RPi touchscreen's backlight by overriding the `on_touch_down()` function in the main application.  The idea behind this is to keep the click from turning on the screen and clicking a screen widget by accident (because it couldn't be seen yet).

```python
def on_touch_down(self, etype, motionevent):
        # Catches a touch event so that the backlight comes on first before propagating to child objects.
        self.last_touch = time.time()
        # If the backlight was off, this function returns True.
        return self.enable_backlight()
```

When the backlight was off on the prior touch (this function returning `False` after having previously returned `True` on the last touch), about 50% of the time this works fine, the other 50% it throws a KeyError exception in the `_touch_move()` function in touchring.py.

It appears that sometimes the `touch.ud` object is passed to the function empty.  Not sure why that is.

My current fix (more of a hack, really) is to catch the exception and log it.  It doesn't seem to hamper any of the functionality from what I can tell.

```python
def _touch_move(win, touch):
    ud = touch.ud

    try:
        ud['tr.rect'].pos = (
            touch.x - (pointer_image.width / 2. * pointer_scale),
            touch.y - (pointer_image.height / 2. * pointer_scale))
    except KeyError:
        Logger.exception('touchring.py: touch.ud is probably empty.')
```

I realize this is probably not the *proper* fix, but it's serving my needs for now.  Let me know if I can provide any more help/information in diagnosing!

Original Trace:
```
Traceback (most recent call last):
  File "app.py", line 147, in <module>
    App().run()
  File "/usr/local/lib/python3.4/dist-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_egl_rpi.py", line 89, in mainloop
    self._mainloop()
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_egl_rpi.py", line 84, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-a56bsdeu-build/kivy/_event.c:7726)
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/__init__.py", line 1072, in on_motion
    self.dispatch('on_touch_move', me)
  File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (/tmp/pip-a56bsdeu-build/kivy/_event.c:7681)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-a56bsdeu-build/kivy/_event.c:13524)
  File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (/tmp/pip-a56bsdeu-build/kivy/_event.c:13050)
  File "/usr/local/lib/python3.4/dist-packages/kivy/modules/touchring.py", line 80, in _touch_move
    touch.y - (pointer_image.height / 2. * pointer_scale))
KeyError: 'tr.rect'
```

**Comment by Whatnoww** [comment]
I've been having the exact same problem. No idea what to do here.
