### ISSUE TITLE
ZeroDivisionError in mtdev.py

### ISSUE THREAD

**Issue by davelawr** [kivy/kivy#4492]
running kivy 1.9.2-dev0 on raspberrypi my application occasionally produces this exception:

```
Exception in thread Thread-1:                                                                                  
 Traceback (most recent call last):                                                                             
   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                                       
     self.run()                                                                                                 
   File "/usr/lib/python2.7/threading.py", line 763, in run                                                     
     self.__target(*self.__args, **self.__kwargs)                                                               
   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 305, in _thread_run        
     range_max_minor)                                                                                           
   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/mtdev.py", line 214, in normalize
     return (value - vmin) / float(vmax - vmin)
 ZeroDivisionError: float division by zero
```

seems to be related to keyboard input.

full kivy 'debug' leading up to the exception attached.

[kivylog.txt](https://github.com/kivy/kivy/files/383938/kivylog.txt)

**Comment by tshirtman** [comment]
from your log
```
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event2> range position X is 0 - 800
[INFO   ] [MTD         ] </dev/input/event1> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event2> range position Y is 0 - 480
[INFO   ] [HIDMotionEvent] using <SIGMACHIP USB Keyboard>
[INFO   ] [MTD         ] </dev/input/event1> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event2> range touch major is 0 - 0
[INFO   ] [HIDMotionEvent] using <SIGMACHIP USB Keyboard>
[INFO   ] [HIDMotionEvent] using <FT5406 memory based driver>
[INFO   ] [MTD         ] </dev/input/event1> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range touch minor is 0 - 0
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS X position is 0 - 800
[INFO   ] [MTD         ] </dev/input/event1> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event2> range pressure is 0 - 255
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO   ] [MTD         ] </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO   ] [MTD         ] </dev/input/event1> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event2> rotation set to 0
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480
```
which, sorted, is more legible as
```
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
                                             
[INFO   ] [MTD         ] </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event1> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event1> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> rotation set to 0
                        
[INFO   ] [MTD         ] </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event2> range position X is 0 - 800
[INFO   ] [MTD         ] </dev/input/event2> range position Y is 0 - 480
[INFO   ] [MTD         ] </dev/input/event2> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event2> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> rotation set to 0
```
so all your inputs have 0-0 ranges for major/minor axes of the touch ellipse (according to https://github.com/kivy/kivy/blob/master/kivy/lib/mtdev.py#L32-L33), so if min == max, of course, normalize is going to freak out. Now, i don't know if that's a normal situation to have (https://github.com/kivy/kivy/blob/master/kivy/input/providers/mtdev.py#L235-L245 does the lookup and get_abs looks trivial enough), but aside ignoring the event in this situation, i'm not sure what more we can do, could this be a driver bug?

**Comment by davelawr** [comment]
Hi,
That certainly doesn't look very healthy! This was on a 'kivypie' image, so you should be able to recreate it, although if there's any other debug you'd like me to collect let me know.
