### ISSUE TITLE
Creating a kivy virtual environment fails on OS X 10.11

### ISSUE THREAD

**Issue by pieceofduke** [kivy/kivy#4536]
Hi! Installed using Kivy.app.
kivy command in terminal works, import kivy works.
Trying to create a virtual environment for a test project, here is what happens then... Please help? Googling didn't help...

MacBook-Pieceofduke:pong pieceofduke$ mkvirtualenv pong -p kivy
Running virtualenv with interpreter /usr/local/bin/kivy
Using base prefix '/Applications/Kivy.app/Contents/Resources/./venv/bin/../../../Frameworks/python/3.5.0'
New python executable in /Users/pieceofduke/.virtualenvs/pong/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/pieceofduke/....envs/pong/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/local/lib/python3.5/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/usr/local/lib/python3.5/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/usr/local/lib/python3.5/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/index.py", line 30, in <module>
  File "/usr/local/lib/python3.5/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>
  File "/usr/local/lib/python3.5/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/usr/local/lib/python3.5/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 66, in <module>
ImportError: cannot import name 'HTTPSHandler'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/virtualenv.py", line 2332, in <module>
    main()
  File "/usr/local/lib/python3.5/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.5/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/usr/local/lib/python3.5/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python3.5/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/pieceofduke/....envs/pong/bin/python - setuptools pip wheel failed with error code 1

**Comment by jegger** [comment]
I don't think that running Kivy in a virtualenv was ever supported this way (by using the packaged kivy.app). Or was it?
You could try installing Kivy into the virtualenv by building it from source: https://gist.github.com/jegger/9549865

**Comment by dessant** [comment]
@jegger is right, Kivy.app is not meant to be used that way, try installing manually.
