### ISSUE TITLE
Sklearn: _check_build.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by WGierke** [kivy/kivy#4750]
Hi everyone,
I really like this project and admire you for implementing it!
I'd like to develop an Android app that uses a library (whereami) that depends on sklearn.
Obviously, sklearn is built with 64-bit instead of the required 32-bit:
```log
I python  :  Traceback (most recent call last):
I python  :    File "/home/USER/Documents/Projects/office_live_map/.buildozer/android/app/main.py", line 3, in <module>
I python  :    File "/home/USER/Documents/Projects/office_live_map/.buildozer/android/app/_applibs/whereami/learn.py", line 6, in <module>
I python  :    File "/home/USER/Documents/Projects/office_live_map/.buildozer/android/app/_applibs/whereami/pipeline.py", line 2, in <module>
I python  :    File "/home/USER/Documents/Projects/office_live_map/.buildozer/android/app/_applibs/sklearn/__init__.py", line 56, in <module>
I python  :    File "/home/USER/Documents/Projects/office_live_map/.buildozer/android/app/_applibs/sklearn/__check_build/__init__.py", line 46, in <module>
I python  :    File "/home/USER/Documents/Projects/office_live_map/.buildozer/android/app/_applibs/sklearn/__check_build/__init__.py", line 41, in raise_build_error
I python  :  ImportError: dlopen failed: "/data/data/com.wordpress.bytedebugger.accelerometer/files/_applibs/sklearn/__check_build/_check_build.so" is 64-bit instead of 32-bit
I python  :  ___________________________________________________________________________
I python  :  Contents of /data/user/0/com.wordpress.bytedebugger.accelerometer/files/_applibs/sklearn/__check_build:
I python  :  setup.pyo                 _check_build.so           __init__.pyo
I python  :  ___________________________________________________________________________
I python  :  It seems that scikit-learn has not been built correctly.
I python  :  
I python  :  If you have installed scikit-learn from source, please do not forget
I python  :  to build the package before using it: run `python setup.py install` or
I python  :  `make` in the source directory.
I python  :  
I python  :  If you have used an installer, please check that it is suited for your
I python  :  Python version, your operating system and your platform.
I python  : Python for android ended.
I art     : System.exit called, status: 0
I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
I ActivityManager: Process com.wordpress.bytedebugger.accelerometer:python (pid 18906) has died
```
I'm using `buildozer android debug deploy run` to deploy and run it on my Nexus 5X. Tell me if you also need the `buildozer.spec` file.
Do you have any experience with that issue?

Thanks a lot and 
Best Regards

**Comment by KeyWeeUsr** [comment]
@WGierke Please move it to kivy/python-for-android, this repo is only the core. `scikit-learn` [requires `scipy`](https://github.com/scikit-learn/scikit-learn/blob/master/setup.py), there's no recipe, but there are [suggestions](https://github.com/kivy/python-for-android/issues/874) of how to make it.
