### ISSUE TITLE
Broken Fedora Download Links

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4766]
_From @ScriptGadget on February 5, 2015 19:19_

The links for fedora repos on the page at http://kivy.org/#download seem to be broken?
There are no directories for 16,17 or 18 in: http://download.opensuse.org/repositories/home:/thopiekar:/kivy/

I do see a Fedora_20 directory and some CentOS and RHEL directories that might be nice to show on the download page as if they are ready for use.
##

_Copied from original issue: kivy/kivy-website#53_

**Comment by dessant** [comment]
@thopiekar ping.

**Comment by thopiekar** [comment]
Thanks @dessant. I wonder that my OBS repository is still listed.
I remember that there was a repository by Python developers of OpenSuSE who provided builds for Fedora, etc. and we've switched to them.
I'll take a look on that.

**Comment by thopiekar** [comment]
Hmm, looks like there are no builds for other distributions.
Do you know of people, who are hosting Fedora packages in their own repositories?

I personally think it needs someone here, who is at least using a RPM based distribution on her/his own.
I sadly use Ubuntu/Debian here...

PS: The OpenSuSE list needs likely an update: https://software.opensuse.org/package/python-Kivy

**Comment by dessant** [comment]
You were my only candidate. 😋

**Comment by thopiekar** [comment]
Hmm, that's a problem then. It is nowadays very easy to install kivy via pip. Shouldn't we recommend to install via pip in that case?

**Comment by dessant** [comment]
Yes, i'd favor that.

**Comment by thopiekar** [comment]
I could also copy the source packages into my own repository (looks like I've did that before), but I can't give any guarantee on quality of the resulting binary packages 😏

**Comment by dessant** [comment]
It's probably better to just remove them from the download page and docs and encourage using pip. Maybe on day we'll also have wheels for linux and that will take care of binary deps too.

**Comment by FeralBytes** [comment]
So confirm fix action for Fedora is recommend install via pip? I can make that change to the site; but I also have to say; I think the last time I tried to install Kivy via pip it failed. The failure is usually a dependency issue; which is usually related to Cython. I will test again and confirm.

**Comment by FeralBytes** [comment]
At the very least we could advertise on the Fedora install page that we need a Fedora maintainer.

**Comment by SanketDG** [comment]
> The failure is usually a dependency issue; which is usually related to Cython. I will test again and confirm.

This is because `kivy` tries to import `cython` before letting it install it. Is there any way around this?

**Comment by cgvirus** [comment]
Hi Folks,
Couldn't find any stable repo but this:
https://fedora.pkgs.org/26/rpm-sphere/python-kivy-1.9.1-3.1.x86_64.rpm.html
It seems Fedora Kivy repo needs some support.

**Comment by gappleto97** [comment]
Still can't even install it from pip at this point. Installed all the dependencies I can think of, but getting this:

```python
pip3 install kivy==1.10
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting kivy==1.10
  Using cached Kivy-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any parent up to mount point /)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    Using distutils
    
    Detected Cython version 0.25
    Using this graphics system: OpenGL
    GStreamer found via pkg-config
    SDL2 found via pkg-config
    SDL2: found SDL header at /usr/include/SDL2/SDL.h
    SDL2: found SDL_mixer header at /usr/include/SDL2/SDL_mixer.h
    SDL2: found SDL_ttf header at /usr/include/SDL2/SDL_ttf.h
    SDL2: found SDL_image header at /usr/include/SDL2/SDL_image.h
    running egg_info
    creating pip-egg-info/Kivy.egg-info
    writing pip-egg-info/Kivy.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/Kivy.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/Kivy.egg-info/requires.txt
    writing top-level names to pip-egg-info/Kivy.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/Kivy.egg-info/SOURCES.txt'
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-ivpkk49q/kivy/setup.py", line 1060, in <module>
         ] if not skip_cython else [])
       File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
         dist.run_commands()
       File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
         self.run_command(cmd)
       File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
         cmd_obj.run()
       File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 278, in run
         self.find_sources()
       File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
         mm.run()
       File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 524, in run
         self.add_defaults()
       File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
         sdist.add_defaults(self)
       File "/usr/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
         self._add_defaults_ext()
       File "/usr/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
         build_ext = self.get_finalized_command('build_ext')
       File "/usr/lib64/python3.6/distutils/cmd.py", line 299, in get_finalized_command
         cmd_obj.ensure_finalized()
       File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
         self.finalize_options()
       File "/tmp/pip-build-ivpkk49q/kivy/setup.py", line 251, in finalize_options
         retval = build_ext.finalize_options(self)
       File "/usr/lib64/python3.6/site-packages/Cython/Distutils/build_ext.py", line 19, in finalize_options
         self.distribution.ext_modules)
       File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 809, in cythonize
         aliases=aliases)
       File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 752, in create_extension_list
         **kwds))
       File "/tmp/pip-build-ivpkk49q/kivy/setup.py", line 511, in __init__
         self.sources = args[1]
     IndexError: tuple index out of range
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ivpkk49q/kivy/
```

**Comment by ksaikiranr** [comment]
@gappleto97 am having the same issue. Can you let me know how you fixed it?

**Comment by ksaikiranr** [comment]
@gappleto97  how can i downgrade SDL2?

**Comment by ksaikiranr** [comment]
@gappleto97 i downgraded  SDL2 and yes it installed properly. 
To downgrade command in fedora is 
$sudo dnf downgrade SDL2
