### ISSUE TITLE
python -m pip install k ivy.deps.gstreamer locks command prompt window & memory error

### ISSUE THREAD

**Issue by frankgould** [kivy/kivy#4774]
I ran the command below:
>python -m pip install kivy.deps.gstreamer --extra-index-url https://kivy.org/downloads/packages/simple/
It generated the following messages then locked up (couldn't CNTL-C or escape out of script):
[INFO   ] [Logger      ] Record log in c:/users/build/data/logs\mp-ss_16-12-07_1.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

Log file listed in message above contains the same information as the message above.

UPDATE: Tried this a third time and it started downloading gstreamer. Results:
Collecting kivy.deps.gstreamer
  Downloading https://kivy.org/downloads/packages/simple/kivy-deps-gstreamer/kiv
y.deps.gstreamer-0.1.7-cp27-cp27m-win32.whl (115.1MB)
    99% |############################### | 115.1MB 1.4MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Python27\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "C:\Python27\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 605, in _download_url
    consume(downloaded_chunks)
  File "C:\Python27\lib\site-packages\pip\utils\__init__.py", line 852, in consume
    deque(iterator, maxlen=0)
  File "C:\Python27\lib\site-packages\pip\download.py", line 571, in written_chunks
    for chunk in chunks:
  File "C:\Python27\lib\site-packages\pip\utils\ui.py", line 139, in iter    for x in it:
  File "C:\Python27\lib\site-packages\pip\download.py", line 560, in resp_read    decode_content=False):
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 314, in read
    data = self._fp.read(amt)
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py",line 63, in read
    self._close()
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py",line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

**Comment by frankgould** [comment]
I went to https://kivy.org/downloads/packages/simple/kivy-deps-gstreamer/
Downloaded the correct version. Then ran python -m pip install <downloaded .whl filename>
This worked and solved this memory problem as a workaround.

**Comment by Zen-CODE** [comment]
For the record, this is caused by caching in pip. Another fix is:

    $ pip --no-cache-dir install kivy.deps.gstreamer

**Comment by zaban** [comment]
It's true! --no-cache-dir works fine!

**Comment by Marflage** [comment]
> 
> 
> For the record, this is caused by caching in pip. Another fix is:
> 
> ```
> $ pip --no-cache-dir install kivy.deps.gstreamer
> ```

Thank you so much! On the kivy website, they tell you to do the same; except there is written "-no" instead of "--no" which does not work and so I was confused. But your comment helped. Thanks again.
