### ISSUE TITLE
ubuntu 16.04 LTS cannot import App

### ISSUE THREAD

**Issue by jordahl74** [kivy/kivy#4810]
I'm somewhat new to writing python code, and I still don't fully understand errors, so any help with this would be greatly appreciated. I have tried this with python 3.5, as well as python 2.7, and so far i've had the same error both attempts. 
Here is the output when i attempt "from kivy.app import App"
>>> from kivy.app import App
[INFO   ] [Logger      ] Record log in /home/brendan/.kivy/logs/kivy_16-12-15_1.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 179 symbols loaded
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 327, in <module>
     from kivy.uix.widget import Widget
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 219, in <module>
     from kivy.graphics import (
   File "/usr/lib/python2.7/dist-packages/kivy/graphics/__init__.py", line 89, in <module>
     from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \
   File "kivy/graphics/vbo.pxd", line 7, in init kivy.graphics.instructions (kivy/graphics/instructions.c:14640)
   File "kivy/graphics/compiler.pxd", line 1, in init kivy.graphics.vbo (kivy/graphics/vbo.c:5482)
   File "kivy/graphics/shader.pxd", line 5, in init kivy.graphics.compiler (kivy/graphics/compiler.c:2983)
   File "kivy/graphics/texture.pxd", line 3, in init kivy.graphics.shader (kivy/graphics/shader.c:11981)
 ImportError: /usr/lib/python2.7/dist-packages/kivy/graphics/texture.x86_64-linux-gnu.so: undefined symbol: glGenerateMipmap
>>> from kivy import App
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 ImportError: cannot import name App

If anyone has any idea why this is happening, or how i can fix it, please let me know.
Thanks in advance.

**Comment by phunsukwangdu** [comment]
How did you installed Kivy? i also have same platform but no such issue.

**Comment by dessant** [comment]
Please try posting your question at one of these places: https://github.com/kivy/kivy#support
