### ISSUE TITLE
matplotlib error test_ test_backend.py

### ISSUE THREAD

**Issue by luisrodriguezgonzalez** [kivy/kivy#4830]
Hello :
i have installed all lib for matplotlib :

sysop@kivypie:~/garden.
matplotlib/examples$ python2.7 -c 'import matplotlib; print matplotlib.__version__, matplotlib.__file__'
2.0.0rc1+2670.gbf5aeb5 /usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc1_2670.gbf5aeb5-py2.7-linux-armv7l.egg/matplotlib/__init__.pyc

But it gives this error:

sysop@kivypie:~/garden.
matplotlib/examples$ python test_backend.py
[INFO   ] [Logger      ] Record log in /home/sysop/.kivy/logs/kivy_16-12-06_57.txt
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Mar  8 2015, 00:52:26)
[GCC 4.9.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Base        ] Adding binding for mouse move
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [MTD         ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [MTD         ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [MTD         ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event1> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range position Y is 0 - 0
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [MTD         ] </dev/input/event1> range touch major is 0 - 0
[INFO   ] [HIDMotionEvent] using <Genius USB Optical Mouse>
[INFO   ] [MTD         ] </dev/input/event2> range touch major is 0 - 0
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [MTD         ] </dev/input/event1> range touch minor is 0 - 0
[INFO   ] [HIDMotionEvent] using <SINO WEALTH USB KEYBOARD>
[INFO   ] [MTD         ] </dev/input/event2> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event2> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event1> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event1> rotation set to 0
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "test_backend.py", line 143, in <module>
     MatplotlibTest().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 89, in mainloop
     self._mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 84, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 512, in tick
     self._process_events()
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 644, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 403, in tick
     ret = callback(self._dt)
   File "/usr/local/lib/python2.7/dist-packages/kivy/uix/boxlayout.py", line 206, in do_layout
     c.width = w
   File "kivy/properties.pyx", line 410, in kivy.properties.Property.__set__ (kivy/properties.c:5009)
   File "kivy/properties.pyx", line 448, in kivy.properties.Property.set (kivy/properties.c:5707)
   File "kivy/properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy/properties.c:6356)
   File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:12813)
   File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy/_event.c:12112)
   File "kivy/properties.pyx", line 1217, in kivy.properties.ReferenceListProperty.trigger_change (kivy/properties.c:19144)
   File "kivy/properties.pyx", line 1232, in kivy.properties.ReferenceListProperty.trigger_change (kivy/properties.c:19031)
   File "kivy/properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy/properties.c:6356)
   File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:12813)
   File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy/_event.c:12112)
   File "/home/sysop/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py", line 1179, in _on_size_changed
     self.figure.set_size_inches(winch, hinch)
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc1_2670.gbf5aeb5-py2.7-linux-armv7l.egg/matplotlib/figure.py", line 720, in set_size_inches
     manager.resize(int(canvasw), int(canvash))
   File "/home/sysop/garden.matplotlib/examples/libs/garden/garden.matplotlib/backend_kivy.py", line 1247, in resize
     Window.size(w, h)
 TypeError: 'tuple' object is not callable

**Comment by dessant** [comment]
Please reopen here: https://github.com/kivy-garden/garden.matplotlib.

**Comment by luisrodriguezgonzalez** [comment]
Always made from here but the error persists in raspberry

**Comment by luisrodriguezgonzalez** [comment]
Hello :

This has already been done many times and the problem continues


2016-12-19 10:57 GMT-03:00 dessant <notifications@github.com>:

**Comment by luisrodriguezgonzalez** [comment]
Window.size=(w, h)

Thanks, it works
