### ISSUE TITLE
raspberry kivy matplotlib AttributeError: 'MTDMotionEvent' object has no attribute 'button'

### ISSUE THREAD

**Issue by luisrodriguezgonzalez** [kivy/kivy#4845]
hello:
In raspberry  I press on graph matplotlib (touch screen) and gives this error:
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "mainScreenManager2.py", line 329, in <module>
     ScreenApp3().run()
   File "/home/pi/kivy/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/pi/kivy/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 90, in mainloop
     self._mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 85, in _mainloop
     EventLoop.idle()
   File "/home/pi/kivy/kivy/base.py", line 342, in idle
     self.dispatch_input()
   File "/home/pi/kivy/kivy/base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/pi/kivy/kivy/base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivy/kivy/core/window/__init__.py", line 1084, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivy/kivy/core/window/__init__.py", line 1100, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivy/kivy/uix/screenmanager.py", line 1114, in on_touch_down
     return super(ScreenManager, self).on_touch_down(touch)
   File "/home/pi/kivy/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivy/kivy/uix/relativelayout.py", line 288, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "/home/pi/kivy/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivy/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivy/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivy/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
   File "/home/pi/kivypanel/libs/garden/garden.matplotlib/backend_kivy.py", line 1067, in on_touch_down
     if(touch.button == "scrollup" or touch.button == "scrolldown"):
 AttributeError: 'MTDMotionEvent' object has no attribute 'button'

**Comment by luisrodriguezgonzalez** [comment]
I added in the graphic class:
    def on_touch_down(self, touch):
        print " touch"

        pass
