### ISSUE TITLE
Kivy Segfault 

### ISSUE THREAD

**Issue by farisazni** [kivy/kivy#4847]
Hi. I'm trying to make a simple budgeting application using kivy. I just got a segfault from trying to run my code, Tried to help but I've never gotten segfaults before and I'm new to both kivy and python. I'm using Python 3.5.2 if that helps.

main.py
********************************************************************************************************************************
```python
import sqlite3 as sqlite
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.scrollview import ScrollView
from kivy.uix.popup import Popup
from kivy.base import runTouchApp

conn = sqlite.connect("demo.db")
c = conn.cursor()


class BudgetDatabase():
    

c.execute("""CREATE TABLE IF NOT EXISTS Budget
              (ID INTEGER PRIMARY KEY AUTOINCREMENT,
               TITLE TEXT,
               VALUE FLOAT)""")


class AddBudgetPopup(Popup):
    def submit_data(self):
        title = self.ids.title
        value = self.ids.amount
        c.execute("""insert into budget (title,value) values(?,?)""",
                  (title.text, float(value.text)))
        conn.commit()
        self.popup.close()


class EditBar(BoxLayout):
    def add_new_budget(self):
        popup = AddBudgetPopup()
        popup.open()


class DemoBase(BoxLayout):
    def update_budget_list(self):
        c.execute("SELECT ID FROM Budget")
        for row in c:
            for i in str(row[0]):
                title = c.execute("SELECT TITLE FROM Budget WHERE ID = (?)", i)
                amount = c.execute("SELECT VALUE FROM Budget WHERE ID = (?)", i)
                self.add_widget(Button(text=self.title))


class DemoRoot(ScrollView):
    pass


class DemoApp(App):
    runTouchApp(DemoRoot)


if __name__ == "__main__":
DemoApp().run()
```
********************************************************************************************************************************

demo.kv
********************************************************************************************************************************
```python
DemoRoot:

<EditBar>:
	size_hint_y: None
	Button:
		text: "auto-set budget"
		size_hint_x: 50
	Button:
		text: "Spending Tips"
		size_hint_x: 25
	Button:
		text: "Add Budget"
		size_hint_x: 25
		on_press: root.add_new_budget()


<AddBudgetPopup>:
	title: "Add Budget"
	size_hint: None, None
	size: 400, 400
	BoxLayout:
		orientation: "vertical"
		TextInput:
			id: title
			hint_text: "Title"
			size_hint_y: None
			multiline: False
		TextInput:
			id: amount
			hint_text: "Amount"
			input_type: 'number'
			size_hint_y: None
			multiline: False
		Button:
			size_hint: None, None
			text: "Submit"
			on_press: root.submit_data()


<DemoBase>:
	orientation: "vertical"
	Label:
		text: "This is the Demo Application"
		font_size: 25
	EditBar
	Button:
		on_press: root.update_budget_list()
		size_hint: None, None
		text: "Update Budget List"

<DemoRoot>:
DemoBase
```
********************************************************************************************************************************

**Comment by dessant** [comment]
If there are some logs besides the segfault, please share them.

**Comment by farisazni** [comment]
Thanks. Here's the backtrace of the segfault I got using gdb

```
#0  0x0000000000000028 in ?? ()
#1  0x00007ffff1cc57b9 in __pyx_f_4kivy_8graphics_12instructions_6Canvas_add (__pyx_v_self=__pyx_v_self@entry=0x7ffff6b27a68, 
    __pyx_v_c=__pyx_v_c@entry=0x7ffff7d5ea10 <_Py_NoneStruct>, __pyx_skip_dispatch=__pyx_skip_dispatch@entry=1)
    at /tmp/pip-build-tdrq_e01/Kivy/kivy/graphics/instructions.c:9433
#2  0x00007ffff1cc5a3c in __pyx_pf_4kivy_8graphics_12instructions_6Canvas_6add (__pyx_v_c=0x7ffff7d5ea10 <_Py_NoneStruct>, 
    __pyx_v_self=0x7ffff6b27a68) at /tmp/pip-build-tdrq_e01/Kivy/kivy/graphics/instructions.c:9521
#3  __pyx_pw_4kivy_8graphics_12instructions_6Canvas_7add (__pyx_v_self=0x7ffff6b27a68, __pyx_v_c=0x7ffff7d5ea10 <_Py_NoneStruct>)
    at /tmp/pip-build-tdrq_e01/Kivy/kivy/graphics/instructions.c:9501
#4  0x00007ffff7a2ef56 in PyEval_EvalFrameEx () from /lib64/libpython3.5m.so.1.0
#5  0x00007ffff7a305e3 in _PyEval_EvalCodeWithName () from /lib64/libpython3.5m.so.1.0
#6  0x00007ffff7a2ce59 in PyEval_EvalFrameEx () from /lib64/libpython3.5m.so.1.0
#7  0x00007ffff7a305e3 in _PyEval_EvalCodeWithName () from /lib64/libpython3.5m.so.1.0
#8  0x00007ffff7a2ce59 in PyEval_EvalFrameEx () from /lib64/libpython3.5m.so.1.0
#9  0x00007ffff7a305e3 in _PyEval_EvalCodeWithName () from /lib64/libpython3.5m.so.1.0
#10 0x00007ffff7a306c3 in PyEval_EvalCodeEx () from /lib64/libpython3.5m.so.1.0
#11 0x00007ffff7a2311c in builtin___build_class__ () from /lib64/libpython3.5m.so.1.0
#12 0x00007ffff79b7809 in PyCFunction_Call () from /lib64/libpython3.5m.so.1.0
#13 0x00007ffff7a2edb0 in PyEval_EvalFrameEx () from /lib64/libpython3.5m.so.1.0
#14 0x00007ffff7a305e3 in _PyEval_EvalCodeWithName () from /lib64/libpython3.5m.so.1.0
#15 0x00007ffff7a306c3 in PyEval_EvalCodeEx () from /lib64/libpython3.5m.so.1.0
#16 0x00007ffff7a306eb in PyEval_EvalCode () from /lib64/libpython3.5m.so.1.0
#17 0x00007ffff7a4f8e4 in run_mod () from /lib64/libpython3.5m.so.1.0
#18 0x00007ffff7a51e65 in PyRun_FileExFlags () from /lib64/libpython3.5m.so.1.0
#19 0x00007ffff7a51fd5 in PyRun_SimpleFileExFlags () from /lib64/libpython3.5m.so.1.0
#20 0x00007ffff7a68c1c in Py_Main () from /lib64/libpython3.5m.so.1.0
#21 0x0000555555554b60 in main ()

**Comment by dessant** [comment]
@farisazni, just noticed an oddity in your code:

```python
class DemoApp(App):
    runTouchApp(DemoRoot)
```

Here is a sample app for guidance:
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

kv = """
<Test>:
    Label:
        text: 'Test'
"""

Builder.load_string(kv)


class Test(BoxLayout):
    pass


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()
```

**Comment by farisazni** [comment]
Thank you.
