### ISSUE TITLE
Showcase fails to start on case-sensitive OS

### ISSUE THREAD

**Issue by JayGray** [kivy/kivy#4924]
```
❯ kivy /Applications/Kivy2.app/Contents/Resources/kivy/examples/demo/showcase/main.py
[WARNING] [Config      ] Older configuration version detected (0 instead of 14)
[WARNING] [Config      ] Upgrading configuration in progress.
Purge log fired. Analysing...
Purge finished!
[INFO   ] [Logger      ] Record log in /Applications/Kivy2.app/Contents/Resources/.kivy/logs/kivy_17-01-15_0.txt
[INFO   ] [Kivy        ] v1.9.1-dev0
[INFO   ] [Python      ] v2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] OpenGL version <2.1 INTEL-10.14.73>
[INFO   ] [GL          ] OpenGL vendor <Intel Inc.>
[INFO   ] [GL          ] OpenGL renderer <Intel Iris OpenGL Engine>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.20>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "/Applications/Kivy2.app/Contents/Resources/kivy/examples/demo/showcase/main.py", line 238, in <module>
     ShowcaseApp().run()
   File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/app.py", line 802, in run
     root = self.build()
   File "/Applications/Kivy2.app/Contents/Resources/kivy/examples/demo/showcase/main.py", line 72, in build
     self.go_next_screen()
   File "/Applications/Kivy2.app/Contents/Resources/kivy/examples/demo/showcase/main.py", line 93, in go_next_screen
     screen = self.load_screen(self.index)
   File "/Applications/Kivy2.app/Contents/Resources/kivy/examples/demo/showcase/main.py", line 117, in load_screen
     screen = Builder.load_file(self.available_screens[index].lower())
   File "/Applications/Kivy2.app/Contents/Resources/kivy/kivy/lang.py", line 1829, in load_file
     with open(filename, 'r') as fd:
 IOError: [Errno 2] No such file or directory: '/applications/kivy2.app/contents/resources/kivy/examples/demo/showcase/data/screens/accordions.kv'
```

I was able to fix this locally by removing the both lower calls in line:
https://github.com/kivy/kivy/blob/master/examples/demo/showcase/main.py#L117
and
https://github.com/kivy/kivy/blob/master/examples/demo/showcase/main.py#L122

Instead `lower()` the screen name in
https://github.com/kivy/kivy/blob/master/examples/demo/showcase/main.py#L71

```python
self.available_screens = [join(curdir, 'data', 'screens',
            '{}.kv'.format(fn.lower())) for fn in self.available_screens]
```

**Comment by dessant** [comment]
@JayGray, thanks! You may also open a pull request when you have a fix in mind.

**Comment by Zen-CODE** [comment]
Closed with https://github.com/kivy/kivy/commit/05a109ca31f39c89f0305f4997a65354e58f7a96

@JayGray Nice one :-)
