### ISSUE TITLE
weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by misl6** [kivy/kivy#4929]
```
[INFO   ] Logger: Record log in C:\Users\mirko\.kivy\logs\kivy_17-01-17_5.txt
[INFO   ] Kivy: v1.9.2-dev0.15012017.daf6407e
[INFO   ] Python: v2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
[INFO   ] Factory: 193 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <2.1 Chromium 1.9>
[INFO   ] GL: OpenGL vendor <Humper>
[INFO   ] GL: OpenGL renderer <Chromium>
[INFO   ] GL: OpenGL parsed version: 2, 1
[INFO   ] GL: Shading version <1.30>
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] AppRouter: Route is '/login'
[INFO   ] Text: Provider: sdl2
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Start application main loop
[INFO   ] AppRouter: Route is '/'
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "main.py", line 63, in <module>
[WARNING] stderr:     appnameApp().run()
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\app.py", line 828, in run
[WARNING] stderr:     runTouchApp()
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\base.py", line 504, in runTouchApp
[WARNING] stderr:     EventLoop.window.mainloop()
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 640, in mainloop
[WARNING] stderr:     self._mainloop()
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 392, in _mainloop
[WARNING] stderr:     EventLoop.idle()
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\base.py", line 342, in idle
[WARNING] stderr:     self.dispatch_input()
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\base.py", line 327, in dispatch_input
[WARNING] stderr:     post_dispatch_input(*pop(0))
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
[WARNING] stderr:     wid.dispatch('on_touch_up', me)
[WARNING] stderr:   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
[WARNING] stderr:     self.dispatch('on_release')
[WARNING] stderr:   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
[WARNING] stderr:   File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
[WARNING] stderr:   File "kivy\_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy\_event.c:12816)
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\venv\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
[WARNING] stderr:     exec(__kvlang__.co_value, idmap)
[WARNING] stderr:   File "C:\Users\mirko\Documents\projects\gitlab-repos\appname-kivy\appname.kv", line 17, in <module>
[WARNING] stderr:     on_release: dropdown.open(self)
[WARNING] stderr:   File "kivy\weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__ (kivy\weakproxy.c:1382)
[WARNING] stderr:   File "kivy\weakproxy.pyx", line 26, in kivy.weakproxy.WeakProxy.__ref__ (kivy\weakproxy.c:1284)
[WARNING] stderr: ReferenceError: weakly-referenced object no longer exists
```

**Comment by dessant** [comment]
Could you share the code you're running?

**Comment by matham** [comment]
The error basically says that `on_release: dropdown.open(self)` referenced an object which is not alive anymore. Likely, `dropdown` that you reference has been removed. Please see https://kivy.org/docs/guide/lang.html#referencing-widgets for the exact details.

But it's hard to know for sure without your code.

**Comment by misl6** [comment]
Unfortunately I can't share the code here right now.
I noticed that this issue only exists on a Windows 10 VM.

**Comment by BillBridge** [comment]
Dear 'Dessant' and 'misl6',
I am encountering exactly the same issue with exactly the same error messages sequence in the kivy log.
This issue is present on both Win7 as Win10. I am able to share code with you. But this should be done through private message. Could this issue be re-opened?

**Comment by dessant** [comment]
@BillBridge, you could prepare a minimal, runnable example with the proprietary code removed and post it here.

**Comment by BillBridge** [comment]
I will give it a try. Please have some patience as this will take some time I guess.

**Comment by BillBridge** [comment]
I have tried to reproduce the issue in a minimal runnable example but did not succeed. The issue only occurs in the bigger picture: the whole application and is clearly and easy reproducible. I am willing to share this code. However, this is only possible through private exchange. Would this be possible for you?

**Comment by krauseling** [comment]
I had a similar issue of weakly referenced DropDown lists.
To resolve it I added the id of the dropdown as an attribute on the root widget in kv and set it to id.__self__.  
Got this from matham after reading his linked kivy reference. Hope this helps!

`<MainScreen>:
    dd_level: dd_level.__self__
    dd_class: dd_class.__self__
    BoxLayout:
        id: menu_layout
        Button:
            id: btn_class_dropdown
            on_release: dd_class.open(self)
            DropDown:
                id: dd_class
        Button:
            id: btn_level_dropdown
            on_release: dd_level.open(self)
            DropDown:
                id: dd_level
`

**Comment by matham** [comment]
Likely the reason you cannot reproduce with a smaller example is that memory is collected and freed randomly depending on system load, which is system and usage dependent. You can force memory freeing by calling `import gc; gc.collect()`.

The solution as @krauseling says is to store a hard ref so the widget is not garbage collected.
