### ISSUE TITLE
CompositeListItem doesn't behave like SelectableView + BoxLayout

### ISSUE THREAD

**Issue by fritmayo** [kivy/kivy#4945]
Versions:
python 2.7.6
Ubuntu 14.04.4 LTS
kivy v1.9.2-dev0
Kivy installed via kivy's apt repository

Hello.
I'm currently experiencing issues with CompositeListItem. It seems that this widget does not really behave like a SelectableView + a BoxLayout.

Please have a look at this snippet (it is graphically ugly but this point is not relevant here):
```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.selectableview import SelectableView
from kivy.uix.boxlayout import BoxLayout
from kivy.adapters.listadapter import ListAdapter
from kivy.uix.listview import ListView, CompositeListItem
from kivy.properties import StringProperty, NumericProperty, ObjectProperty

Builder.load_string("""
<MyWidget>:
    ListView:
        adapter:
            root.listAdapter

<ItemBox>:
    orientation: 'horizontal'
    Label:
        text: str(root.lineNumber)
    Label:
        text: root.itemValue
""")

class MyWidget(BoxLayout) :
    listAdapter = ObjectProperty(None)

    def __init__(self, **kwargs) :
        self.argsConverter = lambda row_index, obj : { 'lineNumber': obj.lineNumber, 'itemValue': obj.itemValue }
        data = [Item(18, "test"), Item(12, "test"), Item(69, "test")]
        self.listAdapter = ListAdapter(data = data, args_converter = self.argsConverter, cls = ItemBox)
        super(MyWidget, self).__init__(**kwargs)

class ItemBox(CompositeListItem) :
    lineNumber = NumericProperty(0)
    itemValue = StringProperty("")

class Item(object) :
    def __init__(self, _lineNumber, _itemValue) :
        self.lineNumber = _lineNumber
        self.itemValue = _itemValue

class MyWidgetApp(App) :
    def build(self) :
        return MyWidget()

MyWidgetApp().run()
```

It crashes. Here is the traceback:
```
 Traceback (most recent call last):
   File "main.py", line 46, in <module>
     MyWidgetApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 637, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 390, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 412, in tick
     self._process_events()
   File "_clock.pyx", line 329, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:5820)
   File "_clock.pyx", line 359, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:5717)
   File "_clock.pyx", line 357, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:5666)
   File "_clock.pyx", line 164, in kivy._clock.ClockEvent.tick (kivy/_clock.c:2649)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/listview.py", line 924, in _spopulate
     self.populate()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/listview.py", line 972, in populate
     item_view = self.adapter.get_view(index)
   File "/usr/lib/python2.7/dist-packages/kivy/adapters/listadapter.py", line 211, in get_view
     item_view = self.create_view(index)
   File "/usr/lib/python2.7/dist-packages/kivy/adapters/listadapter.py", line 234, in create_view
     view_instance = cls(**item_args)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/listview.py", line 681, in __init__
     cls_dicts = kwargs.pop('cls_dicts')
 KeyError: 'cls_dicts'
```
But if I replace the class declaration of ItemBox in the source code, problem is solved:

```
-class ItemBox(CompositeListItem) :
+class ItemBox(SelectableView, BoxLayout) :
```

It looks like both definitions aren't the same, as I was expecting. According to the documentation:

> CompositeListItem mixes SelectableView with BoxLayout for a generic container-style list item, to be used in ListView.

Regards.

**Comment by dessant** [comment]
ListView and its helper classes have been deprecated, try updating to the dev version and use RecycleView.
