### ISSUE TITLE
UnicodeDecodeError on "import kivy"

### ISSUE THREAD

**Issue by arqeco** [kivy/kivy#4967]
Hello,

I am testing Kivy on Windows 10 (in brazilian portuguese). Importing kivy gives me the error below:

```
C:\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import kivy

[ERROR             ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\logger.py", line 205, in emit
    self._configure()
  File "C:\Python27\lib\site-packages\kivy\logger.py", line 153, in _configure
    _dir = os.path.join(_dir, log_dir)
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 8: ordinal not in range(128)
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

>>>
```

The Kivy test program I have written works fine. But when I try to use PyInstaller on it I have the same UnicodeDecodeError, so I can't get an .exe of my program.

Greetings,
Marcio

**Comment by dessant** [comment]
Could you share your home folder path?

**Comment by arqeco** [comment]
C:\Users\Márcio
There is an "a" with an acute accent.

**Comment by cwallenpoole** [comment]
It looks like this issue was already addressed with this commit: https://github.com/kivy/kivy/commit/dd2012fb2d1cd4839a6304b93ae43a4b56c38a12
