### ISSUE TITLE
KV - widget properties not available during custom property creation

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4982]
* Kivy: ce9206c + stable

### Description

Basically [this](http://stackoverflow.com/q/42104295/5994041) SO question looks like a bug in our code, most likely in the kv parser. I think it's not the init ↔ post-init issue and here's why: notice the `on_custom_size` event, which prints `__dict__`, `size` and `custom_size`. Now if I set a property with a default value, then make an event that prints the property, the source of the property and change the property later, I expect the event to print the correct values - which it does _and_ tells something more about the canvas presence (I think).

Let's draw a `Rectangle` using the value of the custom property.

### Code and Logs

**KV only**

```
from kivy.app import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
<Test@BoxLayout>:
    custom_size: [0, 0]
    on_custom_size: print((vars(self), self.size, self.custom_size))
    # print __dict__, 800, 600 (= Window size); 1600, 1200
    custom_size: [s*2 for s in self.size]
    canvas:
        Color:
            rgba: (1, 0, 0, 1)
        Rectangle:
            # 100x100 default, uncommented = [x for x in None]
            # size: self.custom_size

Test:
'''))
```

**Python only**
```
from kivy.app import runTouchApp
from kivy.uix.boxlayout import BoxLayout
from kivy.properties import ListProperty
from kivy.graphics import Color, Rectangle

class Test(BoxLayout):
    custom_size = ListProperty([0, 0])

    def on_custom_size(self, *_):
        print((vars(self), self.size, self.custom_size))

    def __init__(self, **kwargs):
        super(Test, self).__init__(**kwargs)
        # print __dict__, 100, 100(= Widget default); 200, 200
        self.custom_size = [s*2 for s in self.size]
        with self.canvas:
            Color(rgb=(1, 0, 0))
            Rectangle(size=self.custom_size)

runTouchApp(Test())
```

As you can see there are two different behaviors, I think it's like that because in one of the snippets the `canvas` was already constructed, which obviously means `size` available with the default value, etc etc (the Python one), but I'm not sure because `size` doesn't seem to be available in `__dict__` of the object (why? where is the first place the size/pos/... are created?).

On the other hand, kv code behaves like some kind of snake catching its own tail i.e. canvas isn't built, there's no `size`, yet the properties "work" or at least look like they work in the "functional" manner (kv executed line-by-line like PHP or C), **but** they are executed **after** the canvas is created **unless** they are used in the `canvas` and if they actually _are_ used, then the Python code is executed inplace/directly(???) with that call, thus leading to issues with `None`.

Or am I missing something?

**Comment by bionoid** [comment]
I suspect this is another illustration of the same or similar problem

```python
from kivy.lang import Builder
from kivy.factory import Factory

Builder.load_string('''
<Dummy@Widget>:
    ninja: 100
''')

# Uncomment and it will work because property exists
#x = Factory.Dummy()
x = Factory.Dummy(ninja=0)
```

---

```
 Traceback (most recent call last):
   File "prop3.py", line 11, in <module>
     x = Factory.Dummy(ninja=0)
   File "c:\python36\lib\site-packages\kivy\uix\widget.py", line 337, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:5332)
 TypeError: object.__init__() takes no parameters
```

Possible kvlang solution:

```
<Test@BoxLayout>:
    custom_size: [0, 0]
<Test>:
    custom_size: [s*0.5 for s in self.size]
```

**Comment by bionoid** [comment]
```python
from kivy.app import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
<Test@BoxLayout>:
    custom_size: [s*.5 for s in self.size]
<Test>
    canvas:
        Color:
            rgba: (1, 0, 0, 1)
        Rectangle:
            size: self.custom_size
Test:
'''))
```

As speculated this works, my understanding is that the property is created during the evaluation of the ``<Test@BoxLayout>`` rule and exists in the class by the time the canvas rule is evaluated

```python
from kivy.app import runTouchApp
from kivy.lang import Builder
from kivy.factory import Factory

class Dummy(Factory.BoxLayout):
    custom_size = Factory.ListProperty([0, 0])

runTouchApp(Builder.load_string('''
<Dummy>:
    custom_size: [s*.5 for s in self.size]
    canvas:
        Color:
            rgba: (1, 0, 0, 1)
        Rectangle:
            size: self.custom_size
Dummy:
'''))
```

**Comment by KeyWeeUsr** [comment]
> #x = Factory.Dummy()
x = Factory.Dummy(ninja=0)

Nope, this is a completely different problem and that's about a missing Kivy Property that pops the `ninja` from kwargs before passing it further down to the `object` instance initialization itself. See the [part about `__init__`](https://kivy.org/docs/api-kivy.properties.html#keyword-arguments-and-init).

I've already met this behavior and then I just switched to the Python classes instead as I don't think a dynamic class allows you to manipulate its `__init__`, or better said, it's not defined anywhere else (correct me if I'm wrong), therefore it just waits for the first instance because together with that the class property (`ninja` in this case) is created and otherwise it's just a plain `Widget` or even `object` class. Or maybe it's just in some dictionary somewhere, waiting. @matham or @tito will know more about this, I think.

> &lt;Test@BoxLayout>:
>&nbsp;&nbsp;&nbsp;&nbsp;custom_size: [s*.5 for s in self.size]
> &lt;Test>
> &nbsp;&nbsp;&nbsp;&nbsp;canvas:

About this piece, well this part just appends to the previous rule, therefore the property is there, but nothing was done with the canvas instructions from the user's side. At the second rule the property is properly created *after* the canvas is ready(in your case the default canvas instructions). In other words, see this:

```
<Test@BoxLayout>:
    custom_size: [s*.5 for s in self.size]
    # justa copypasta
    canvas:
        Color:
            rgba: (1, 0, 0, 1)
        Rectangle:
            size: self.custom_size  # crash boom
<Test>
    canvas:
        Color:
            rgba: (1, 0, 0, 1)
        Rectangle:
            size: self.custom_size
Test:
```

For more details see [this answer](https://stackoverflow.com/a/42124308/5994041) although I think I've already explained it in the first post. My point is that there's a big inconsistency between the Python and Kv part which will introduce more troubles later if we tell users (and we already did) to use KV for designing the widgets.

A solution to this should preferably be evaluating every property in the whole rule (e.g. collect all rule lines first, filter by category - properties, canvas, etc and eval properties first, canvas later) where the line-by-line behavior is preserved. For example:

```python
from kivy.app import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
# probe the rule
<Test@BoxLayout>:
    # collect to queue
    custom_size: [0, 0]

    # collect to the same queue as properties and on evaluation of the event
    # check if the property exists. If no, raise an error. If yes, don't care,
    # it can break at runtime (user's fault)
    on_custom_size: print((vars(self), self.size, self.custom_size))

    # collect to the queue; on evaluation the property already exists, so the
    # value would be just overwritten like in Python, so the event would be
    # triggered
    custom_size: [s*2 for s in self.size]

    # ignore until all properties and events are resolved
    canvas:
        Color:
            rgba: (1, 0, 0, 1)
        Rectangle:
            # ---> after evaluating properties first, canvas later this
            # ---> should work correctly as the value would be available
            # 100x100 default, uncommented = [x for x in None]
            # size: self.custom_size

    # collect to the queue
    random_property: 'blob'

    # end of rule, properties are evaluated here, canvas instructions'
    # evaluation should begin right after them

Test:
'''))
```

And that's probably even [expected](https://github.com/kivy/kivy/blob/7fd05aaa60b4afb683f594e454d85c42bf5fbc5c/kivy/lang/parser.py#L255) behavior and something just broke along those lines. 😢

**Comment by matham** [comment]
The kv compiler is supposed to make these things more sane.
