### ISSUE TITLE
Examples: Settings widget exception in partial and close_settings missing argument

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5005]
### Versions

* Python: 2.7, 3.5
* OS: Win8.1, 64bit
* Kivy: master, wheels

### Description

Settings widget in `examples/widget/settings.py` returns when displayed:

> Exception ignored in: functools.partial(...)

but otherwise everything works fine. Similar in `examples/settings/main.py` for closing, but it closes correctly:

> TypeError: close_settings() missing 1 required positional argument: 'settings'

**Comment by KeyWeeUsr** [comment]
Partially fixed by https://github.com/kivy/kivy/commit/5911e86a02c9cd258162e5273aa5a570f34d6b71, but the first `partial()` thingy is hard to reproduce, so there's a lot of settings openning&closing needed to actually trigger it, but it still _is_ present.

**Comment by pat1** [comment]
I get this error when app terminate on python3 and new toolchain:

```
11-08 14:01:49.346 19646 19672 I python  : [INFO   ] [Base        ] Leaving application in progress...
11-08 14:01:49.346 19646 19672 I python  : INFO:kivy:[Base        ] Leaving application in progress...
11-08 14:01:49.347 19646 19672 I python  :  Traceback (most recent call last):
11-08 14:01:49.347 19646 19672 I python  : WARNING:kivy:stderr: Traceback (most recent call last):
11-08 14:01:49.347 19646 19672 I python  :    File "main.py", line 38, in <module>
11-08 14:01:49.347 19646 19672 I python  : WARNING:kivy:stderr:   File "main.py", line 38, in <module>
11-08 14:01:49.349 19646 19672 I python  :      Rmap().run()
11-08 14:01:49.349 19646 19672 I python  : WARNING:kivy:stderr:     Rmap().run()
11-08 14:01:49.350 19646 19672 I python  :    File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/app.py", line 826, in run
11-08 14:01:49.351 19646 19672 I python  : WARNING:kivy:stderr:   File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/app.py", line 826, in run
11-08 14:01:49.355 19646 19672 I python  :      runTouchApp()
11-08 14:01:49.355 19646 19672 I python  : WARNING:kivy:stderr:     runTouchApp()
11-08 14:01:49.356 19646 19672 I python  :    File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/base.py", line 502, in runTouchApp
11-08 14:01:49.356 19646 19672 I python  : WARNING:kivy:stderr:   File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/base.py", line 502, in runTouchApp
11-08 14:01:49.359 19646 19672 I python  :      EventLoop.window.mainloop()
11-08 14:01:49.359 19646 19672 I python  : WARNING:kivy:stderr:     EventLoop.window.mainloop()
11-08 14:01:49.361 19646 19672 I python  :    File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
11-08 14:01:49.361 19646 19672 I python  : WARNING:kivy:stderr:   File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
11-08 14:01:49.364 19646 19672 I python  :      self._mainloop()
11-08 14:01:49.364 19646 19672 I python  : WARNING:kivy:stderr:     self._mainloop()
11-08 14:01:49.365 19646 19672 I python  :    File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 666, in _mainloop
11-08 14:01:49.365 19646 19672 I python  : WARNING:kivy:stderr:   File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 666, in _mainloop
11-08 14:01:49.368 19646 19672 I python  :      self.modifiers)
11-08 14:01:49.369 19646 19672 I python  : WARNING:kivy:stderr:     self.modifiers)
11-08 14:01:49.369 19646 19672 I python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8147)
11-08 14:01:49.369 19646 19672 I python  : WARNING:kivy:stderr:   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8147)
11-08 14:01:49.370 19646 19672 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (kivy/_event.c:14036)
11-08 14:01:49.371 19646 19672 I python  : WARNING:kivy:stderr:   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (kivy/_event.c:14036)
11-08 14:01:49.371 19646 19672 I python  :    File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch (kivy/_event.c:13565)
11-08 14:01:49.372 19646 19672 I python  : WARNING:kivy:stderr:   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch (kivy/_event.c:13565)
11-08 14:01:49.372 19646 19672 I python  :    File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/app.py", line 1041, in _on_keyboard_settings
11-08 14:01:49.373 19646 19672 I python  : WARNING:kivy:stderr:   File "/data/user/0/org.rmap.rmap/files/app/crystax_python/site-packages/kivy/app.py", line 1041, in _on_keyboard_settings
11-08 14:01:49.376 19646 19672 I python  :      return self.close_settings()
11-08 14:01:49.377 19646 19672 I python  : WARNING:kivy:stderr:     return self.close_settings()
11-08 14:01:49.377 19646 19672 I python  :  TypeError: close_settings() missing 1 required positional argument: 'settings'
11-08 14:01:49.377 19646 19672 I python  : WARNING:kivy:stderr: TypeError: close_settings() missing 1 required positional argument: 'settings'
```

**Comment by LESSSE** [comment]
Versions

    Python: 3.8.5
    OS: Ubuntu 20.04
    Kivy: 2.0.0 | through pip

Same problem here

```[INFO   ] [Base        ] Leaving application in progress...
 Exception ignored in: functools.partial(<function _widget_destructor at 0x7fa6b99b39d0>, 1967)
 Traceback (most recent call last):
   File "venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 264, in _widget_destructor
     del _widget_destructors[uid]
 KeyError: 1967
 Exception ignored in: functools.partial(<function _widget_destructor at 0x7fa6b99b39d0>, 2009)
 Traceback (most recent call last):
   File "venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 264, in _widget_destructor
     del _widget_destructors[uid]
 KeyError: 2009
 Exception ignored in: functools.partial(<function _widget_destructor at 0x7fa6b99b39d0>, 2662)
 Traceback (most recent call last):
   File "venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 264, in _widget_destructor
     del _widget_destructors[uid]
 KeyError: 2662
 Exception ignored in: functools.partial(<function _widget_destructor at 0x7fa6b99b39d0>, 2770)
 Traceback (most recent call last):
   File "venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 264, in _widget_destructor
     del _widget_destructors[uid]
 KeyError: 2770
 Exception ignored in: functools.partial(<function _widget_destructor at 0x7fa6b99b39d0>, 2912)
 Traceback (most recent call last):
   File "venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 264, in _widget_destructor
     del _widget_destructors[uid]
 KeyError: 2912``

**Comment by drernie** [comment]
I'm also getting this while attempting to test a kiva app:
```
Exception ignored in: functools.partial(<function _widget_destructor at 0x10705f1c0>, 63)
Traceback (most recent call last):
  File "/Users/quilt/Library/Caches/pypoetry/virtualenvs/kivy-resource-sUHzDjQV-py3.10/lib/python3.10/site-packages/kivy/uix/widget.py", line 269, in _widget_destructor
    del _widget_destructors[uid]
KeyError: 63
```

**Comment by MrTeferi** [comment]
I get this error near constantly when closing my settings popup elements, doesn't harm anything or cause any real issues but just kind of annoying to have flooding the console. Are there any known causes or ways around it?
