### ISSUE TITLE
Command failed: tar xjf android-ndk-r9c-linux-x86_64.tar.bz2

### ISSUE THREAD

**Issue by MrNocTV** [kivy/kivy#5013]
### Versions

* Python: 2.7
* OS: Ubuntu 16.04
* Kivy: v.1.9.1
* Kivy installation method:
https://gist.github.com/jhoonb/9454386

### Description

When I try to build android ndk using:
`buildozer android debug deploy run`
I got the error.
After searching, I see that this issue has not been asked yet. 

### Code and Logs

```python
import kivy
from kivy.app import App 
from kivy.uix.label import Label 

class MyApp(App):
    def build(self):
        return Label(text='hello')

if __name__ == '__main__':
    MyApp().run()


(venv) loctv@loctv:~/venv/code$ python main.py
[INFO   ] [Logger      ] Record log in /home/loctv/.kivy/logs/kivy_17-02-23_2.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer
ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 12.0.6>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ivybridge Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
(venv) loctv@loctv:~/venv/code$ buildozer init
File buildozer.spec created, ready to customize!
(venv) loctv@loctv:~/venv/code$ buildozer android debug deploy run
# Check requirements for android
# Install platform
# Apache ANT found at /home/loctv/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/loctv/.buildozer/android/platform/android-sdk-20
# Android NDK is missing, downloading
# Unpacking Android NDK
# Command failed: tar xjf android-ndk-r9c-linux-x86_64.tar.bz2
#
# Buildozer failed to execute the last command
# If the error is not obvious, please raise the log_level to 2
# and retry the latest command.
# In case of a bug report, please add a full log with log_level = 2


```

**Comment by Zen-CODE** [comment]
Seems like google change the path. Please update you buildozer and try again? Should be fixed by:

https://github.com/kivy/buildozer/commit/d1c0560a67c3d9d8249cd641896c629a2de65c1e

**Comment by MrNocTV** [comment]
I missed out these three lines:
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

I'm new here, I've just removed and redownload buildozer from 
https://github.com/kivy/buildozer/archive/master.zip
does that mean buildozer has been updated?

**Comment by Zen-CODE** [comment]
Yes, should be. You'll know, because it will either work or give a different error :-)

**Comment by ZingBallyhoo** [comment]
@Zen-CODE After the Buildozer update, I now get an error when downloading the SDK:

```
# Android SDK is missing, downloading
# Downloading http://dl.google.com/android/ndk/android-sdk_r20-linux.tgz
# Unpacking Android SDK
# Run 'tar xzf android-sdk_r20-linux.tgz'
# Cwd /root/.buildozer/android/platform

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
# Command failed: tar xzf android-sdk_r20-linux.tgz
```

**Comment by Zen-CODE** [comment]
Is there a firewall blocking you? Try pasting this into you browser bar,

    http://dl.google.com/android/ndk/android-sdk_r20-linux.tgz

Are you able to download this file?

**Comment by Zen-CODE** [comment]
Sorry, just pushed changes to fix this. Please re-download and try again?

**Comment by ZingBallyhoo** [comment]
@Zen-CODE Seems to be working. Thanks.

**Comment by Zen-CODE** [comment]
Yay :-) Thanks

**Comment by 700brains** [comment]
Put a dash sign I front of xjf like these tar -xjf

**Comment by ZingBallyhoo** [comment]
@Zen-CODE SDK downloading is now working, but NDK downloading is also broken.

Log:
```
# Android NDK is missing, downloading
# Downloading http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.zip
# Unpacking Android NDK
# Run 'unzip /root/.buildozer/android/platform/android-ndk-r10e-linux-x86_64.zip'
# Cwd /root/.buildozer/android/platform
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /root/.buildozer/android/platform/android-ndk-r10e-linux-x86_64.zip or
        /root/.buildozer/android/platform/android-ndk-r10e-linux-x86_64.zip.zip, and cannot find /root/.buildozer/android/platform/android-ndk-r10e-linux-x86_64.zip.ZIP, period.
Archive:  /root/.buildozer/android/platform/android-ndk-r10e-linux-x86_64.zip
# Command failed: unzip /root/.buildozer/android/platform/android-ndk-r10e-linux-x86_64.zip
```

Note: I am using NDK r10e

**Comment by Zen-CODE** [comment]
Does not seem like that file is there. If you paste the url into you browser, you get a 404....

**Comment by ZingBallyhoo** [comment]
@Zen-CODE The file that is needed is ```https://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin``` (.bin not .zip)

**Comment by 700brains** [comment]
Try to edit your buildozer.spec file,  if the ndk is uncommented,  comment
it and try again if commented uncomment it

**Comment by ZingBallyhoo** [comment]
@Zen-CODE Error is here https://github.com/kivy/buildozer/blob/d1c0560a67c3d9d8249cd641896c629a2de65c1e/buildozer/targets/android.py#L295

Line 295 should be ```archive = 'android-ndk-r{0}-linux-{1}.bin'```

**Comment by Zen-CODE** [comment]
@ZingBallyhoo. Spot on. Pushed those changes. Does that do it?

**Comment by ZingBallyhoo** [comment]
@Zen-CODE All working now. Thanks

**Comment by Zen-CODE** [comment]
Thanks :-)

**Comment by MrNocTV** [comment]
SDK and NDK downloading is fine, but I got new error :-( 

```
Copy libs
Copy java files from various libs
Fill private directory
Reduce private directory from unwanted files
Strip libraries
Entering in ARM environment
Compiler found at /home/loctv/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-andr
oideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
Leaving ARM environment
All done !
# Remove temporary build files
# Remove directory and subdirectory /home/loctv/venv/code/.buildozer/android/platform/python-for-an
droid/build
# Distribution compiled.
# Build the application #1
# Copy application source from /home/loctv/venv/code
# Create directory /home/loctv/venv/code/.buildozer/android/app
# Copy /home/loctv/venv/code/main.py
# Package the application
Traceback (most recent call last):
  File "/home/loctv/venv/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, i
n main
    Buildozer().run_command(sys.argv[1:])
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/__init__.py", line 1026, in ru
n_command
    self.target.run_commands(args)
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/target.py", line 91, in run_co
mmands
    func(args)
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/target.py", line 103, in cmd_d
ebug
    self.buildozer.build()
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/__init__.py", line 211, in bui
ld
    self.target.build_package()
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/targets/android.py", line 646,
 in build_package
    self._update_libraries_references(dist_dir)
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/targets/android.py", line 823,
 in _update_libraries_references
    fd.writelines(content)
TypeError: write() argument 1 must be unicode, not str
```
And while compiling, I noticed that there were many errors as well. Is that supposed to be normal?

**Comment by Zen-CODE** [comment]
Try the compile again? Had this this first compile too, but went away with
the second...
