### ISSUE TITLE
write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by MrNocTV** [kivy/kivy#5016]
### Versions

* Python: 2.7
* OS: Ubuntu 16.04
* Kivy: v1.9.1
* Kivy installation method: https://github.com/kivy/buildozer

### Description
SDK and NDK downloading is fine, but I got new error :-(
And while compiling, I noticed that there were many errors as well. Is that supposed to be normal?

### Code and Logs

```
Copy libs
Copy java files from various libs
Fill private directory
Reduce private directory from unwanted files
Strip libraries
Entering in ARM environment
Compiler found at /home/loctv/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-andr
oideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
Leaving ARM environment
All done !
# Remove temporary build files
# Remove directory and subdirectory /home/loctv/venv/code/.buildozer/android/platform/python-for-an
droid/build
# Distribution compiled.
# Build the application #1
# Copy application source from /home/loctv/venv/code
# Create directory /home/loctv/venv/code/.buildozer/android/app
# Copy /home/loctv/venv/code/main.py
# Package the application
Traceback (most recent call last):
  File "/home/loctv/venv/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, i
n main
    Buildozer().run_command(sys.argv[1:])
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/__init__.py", line 1026, in ru
n_command
    self.target.run_commands(args)
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/target.py", line 91, in run_co
mmands
    func(args)
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/target.py", line 103, in cmd_d
ebug
    self.buildozer.build()
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/__init__.py", line 211, in bui
ld
    self.target.build_package()
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/targets/android.py", line 646,
 in build_package
    self._update_libraries_references(dist_dir)
  File "/home/loctv/venv/local/lib/python2.7/site-packages/buildozer/targets/android.py", line 823,
 in _update_libraries_references
    fd.writelines(content)
TypeError: write() argument 1 must be unicode, not str
```

**Comment by MrNocTV** [comment]
Sorry, this question seems to be asked in
[#452](https://github.com/kivy/buildozer/issues/452)

**Comment by SpotlightKid** [comment]
I fixed this by changing the code block at around line 820 in `android.py` to:

```
        # recreate the project.properties
        with io.open(project_fn, 'w', encoding='utf-8') as fd:
            fd.writelines((line.encode('utf-8') for line in content))
            for index, ref in enumerate(references):
                fd.write(u'android.library.reference.{}={}\n'.format(index + 1, ref))
```

**Comment by lutre69** [comment]
Thanks, it worked for me.

**Comment by qingchenwuhou** [comment]
I use codecs solve this problem:

import codecs
fpred = codecs.open('pred_res.txt', 'w', 'utf-8')
fpred.write( (images_test[i] + ' ' + prediction[i] + '\n').decode('unicode_escape') )
fpred.close()
