### ISSUE TITLE
window_sdl2.py: TextInput crashes on numeric input in Android

### ISSUE THREAD

**Issue by ScissorHIll** [kivy/kivy#5043]
### Versions

* Python: 2.7.6
* OS: Ubuntu 14.04
* Kivy: 1.9.2
* Kivy installation method: kivy-daily PPA

### Description

Trying to use TextInput on Android. Works perfectly on Desktop, but app crashes when attempting to input anything on Android.

### Code and Logs
Example taken from the [Kivy Basic documentation](https://kivy.org/docs/guide/basic.html#customize-the-application):

```python
from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput


class LoginScreen(GridLayout):

    def __init__(self, **kwargs):
        super(LoginScreen, self).__init__(**kwargs)
        self.cols = 2
        self.add_widget(Label(text='User Name'))
        self.username = TextInput(multiline=False)
        self.add_widget(self.username)
        self.add_widget(Label(text='password'))
        self.password = TextInput(password=True, multiline=False)
        self.add_widget(self.password)


class MyApp(App):

    def build(self):
        return LoginScreen()


if __name__ == '__main__':
    MyApp().run()
```

The app runs on Android, the keyboard also comes up. But crashes on typing anything. Output of `$adb logcat | grep python` (last few lines only):

```
03-07 10:19:48.972  7842  7857 I python  : [INFO   ] [GL          ] Texture max units <16>
03-07 10:19:48.976  7842  7857 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
03-07 10:19:48.978  7842  7857 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
03-07 10:19:48.981  7842  7857 W linker  : /data/data/org.test.textinput_tester/files/app/lib/python2.7/site-packages/jnius/jnius.so: is missing DT_SONAME will use basename as a replacement: "jnius.so"
03-07 10:19:49.379  7842  7857 I python  : [WARNING] [Base        ] Unknown <android> provider
03-07 10:19:49.379  7842  7857 I python  : [INFO   ] [Base        ] Start application main loop
03-07 10:19:49.383  7842  7857 I python  : [INFO   ] [GL          ] NPOT texture support is available
03-07 10:19:49.386  7842  7857 I python  : [ERROR  ] [Base        ] Failed to import "android" module. Could not remove android presplash.
03-07 10:20:14.940  7842  7857 I python  : [INFO   ] [Base        ] Leaving application in progress...
03-07 10:20:14.941  7842  7857 I python  :  Traceback (most recent call last):
03-07 10:20:14.942  7842  7857 I python  :    File "/home/guru/EclipseWorkspace1/ScratchArea/.buildozer/android/app/main.py", line 27, in <module>
03-07 10:20:14.944  7842  7857 I python  :    File "/home/guru/EclipseWorkspace1/ScratchArea/.buildozer/android/platform/build/dists/textinput_tester/private/lib/python2.7/site-packages/kivy/app.py", line 828, in run
03-07 10:20:14.946  7842  7857 I python  :    File "/home/guru/EclipseWorkspace1/ScratchArea/.buildozer/android/platform/build/dists/textinput_tester/private/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
03-07 10:20:14.947  7842  7857 I python  :    File "/home/guru/EclipseWorkspace1/ScratchArea/.buildozer/android/platform/build/dists/textinput_tester/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 658, in mainloop
03-07 10:20:14.948  7842  7857 I python  :    File "/home/guru/EclipseWorkspace1/ScratchArea/.buildozer/android/platform/build/dists/textinput_tester/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 580, in _mainloop
03-07 10:20:14.950  7842  7857 I python  :  AttributeError: 'LogFile' object has no attribute 'encoding'
03-07 10:20:15.002  7842  7857 I python  : Python for android ended.
```

Tested on Android 6.0.1, and 5.1.1 (separate devices). FWIW, @Tommstein confirmed the same issue on IRC. 

The error seems to be coming from line#580 added in [commit#9246486](https://github.com/kivy/kivy/commit/92464860152abdbc8b9623eb76b0d558124d51cc#diff-5f05a9fe836a8283afe4a523b2038a32).

**Comment by Fogapod** [comment]
#5045

**Comment by KeyWeeUsr** [comment]
@inclement possibly a missing thing for https://github.com/kivy/python-for-android/blob/18a7b799f02dcd6899be77b1055a3028800be492/pythonforandroid/bootstraps/sdl2/build/jni/src/start.c#L184 and other `start.c` files? Maybe just an alias would be enough?

**Comment by inclement** [comment]
I guess so - it would be simplest to just copy the encoding from the normal sys.stdout object, or even to forward arbitrary attribute access.

**Comment by Fogapod** [comment]
After last commit `TextInput` start blocking all entering  buttons at some moment instead of crash the whole app. I need to deselect it and select again to continue entering symbols

**Comment by Julian-O** [comment]
Appears to be fixed - `window_sdl2.py` checks if the attribute is present.

Closing as fixed, but please let us know if it is still happening.
