### ISSUE TITLE
BoundedNumericProperty inconsistent behaviour

### ISSUE THREAD

**Issue by EvgueniB** [kivy/kivy#5055]
There seems to be a bug with this, first described here:
[http://stackoverflow.com/questions/42718908/kivy-boundednumericproperty-errorhandler-misbehaving](url)

### Versions

* Python: 2.7.9
* OS: Raspbian Jessie Pixel
* Kivy: 1.9.2
* Kivy installation method:

### Description

When using BoundedNumericProperty with errorhandler=lambda x, correct function depends on the lower bound value. It works as expected with some choices, crashes with others. See simple example in SO link above.

### Code and Logs
Example code here:
[http://stackoverflow.com/questions/42718908/kivy-boundednumericproperty-errorhandler-misbehaving](url)

Example log:
pi@raspberrypi:~/kivy/VBCIE2/test $ python error.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_17-03-13_31.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [MTD         ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <FT5406 memory based driver>
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS X position is 0 - 800
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 800
[INFO   ] [HIDMotionEvent] using <FT5406 memory based driver>
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 480
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS X position is 0 - 800
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "error.py", line 34, in <module>
     MyApp().run()
   File "/home/pi/kivy/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/pi/kivy/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 90, in mainloop
     self._mainloop()
   File "/home/pi/kivy/kivy/core/window/window_egl_rpi.py", line 85, in _mainloop
     EventLoop.idle()
   File "/home/pi/kivy/kivy/base.py", line 330, in idle
     self.dispatch_input()
   File "/home/pi/kivy/kivy/base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/pi/kivy/kivy/base.py", line 221, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
   File "/home/pi/kivy/kivy/core/window/__init__.py", line 1083, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
   File "/home/pi/kivy/kivy/core/window/__init__.py", line 1099, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
   File "/home/pi/kivy/kivy/uix/widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
   File "/home/pi/kivy/kivy/uix/behaviors/button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7681)
   File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
   File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy/_event.c:12356)
   File "/home/pi/kivy/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 11, in <module>
   File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1236)
   File "kivy/properties.pyx", line 423, in kivy.properties.Property.__set__ (kivy/properties.c:5171)
   File "kivy/properties.pyx", line 456, in kivy.properties.Property.set (kivy/properties.c:5859)
   File "kivy/properties.pyx", line 1098, in kivy.properties.BoundedNumericProperty.check (kivy/properties.c:16949)
 ValueError: MainWidget.number is below the minimum bound (0.150000)

**Comment by matham** [comment]
I'm only getting the crash when the value reaches .1 or lower. Isn't that what should happen? I'm not sure where the bug is here?

**Comment by EvgueniB** [comment]
Yes the point of errorhandler is to prevent the code crashing out. Indeed if you change valueMin to 0.5 it works as it should - no crashes. It also works with valueMin set to 0.25, 0.35 but curiously not with 0.4 or 0.15. I find this odd.

**Comment by germn** [comment]
> Isn't that what should happen?

@matham, no, since we have `errorhandler`, exception shouldn't happen at all.

`BoundedNumericProperty(1, min=0.1, max=2, errorhandler=lambda x: valueMax if x > valueMax else valueMin)`

P.S.
Not sure, but probably related to this issue: https://github.com/kivy/kivy/issues/731

**Comment by matham** [comment]
The reason is that the errorhandler returns an incorrect value (or at least it thinks it does). Specifically, the value returned is exactly the minimum value, which it thinks is actually less than the minimum value. 

The error happens here: https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L1097, possibly because we convert between a c float and python float which may lead to a python float being slightly less than a c float, causing the error.

**Comment by EvgueniB** [comment]
> Specifically, the value returned is exactly the minimum value, which it thinks is actually less than the minimum value.

It seemed that way at first to me also, but - when lower bound is set at 0.15 we still get an exception, even though the number is decremented from 1 in steps of 0.1

**Comment by matham** [comment]
The value I referred to was not the value you set the property, but the
value returned by the error handler. That value, e.g. 0.15 is set and then
compared to the minimum. That's where it fails.
