### ISSUE TITLE
FBO get_pixel_color on python3 is not RGBA format.

### ISSUE THREAD

**Issue by K9Crunch** [kivy/kivy#5072]
### Versions

* Python: 3.5.2 and tested on 3.6.0
* OS: Linux Mint and Arch
* Kivy: 1.9.0-3build1 and 1.9.1-1 
* Kivy installation method: pip, yaourt, apt-get

### Description

When ran on python2 the Fbo.get_pixel_color function returns the colors in RGBA format.
When ran on python3 the same function does not return the RGBA, but returns a list containing 11 numbers: [98, 39, 92, 120, 48, 48, 92, 120, 48, 48, 92, 120, 48, 48, 92, 120, 48, 48, 39]

When adding color to the FBO and clicking on them it will return the same list only a little longer with a few more of the same repeating numbers in it.

### Code and Logs

```python
`
from kivy.app import App

from kivy.core.window import Window
from kivy.uix.widget import Widget
from kivy.uix.label import Label

from kivy.graphics import Fbo, Rectangle




class Game(Widget):
	def __init__(self, **kwargs):
		super(Game, self).__init__(**kwargs)

		self.l = Label(text="label", pos=(300,300))
		self.add_widget(self.l)

		with self.canvas:
			self.fbo = Fbo(size=Window.size)
			Rectangle(size=Window.size, texture=self.fbo.texture)

	def on_touch_down(self, touch):
		self.l.text = str(self.fbo.get_pixel_color( touch.x, touch.y ) ) 


class GameApp(App):
	def build(self):
		return Game(size=Window.size)

if __name__ == "__main__":
	GameApp().run().`




> LOG:

[INFO              ] [Logger      ] Record log in /home/will/.kivy/logs/kivy_17-03-20_17.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <b'3.0 Mesa 17.0.1'>
[INFO              ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO              ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2) '>
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <b'1.30'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event15
[INFO              ] [MTD         ] Read event from </dev/input/event15>
[INFO              ] [Base        ] Start application main loop
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.6/threading.py", line 864, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/lib/python3.6/site-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
     _device = Device(_fn)
   File "/usr/lib/python3.6/site-packages/kivy/lib/mtdev.py", line 131, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 PermissionError: [Errno 13] Permission denied: '/dev/input/event15'
 
[INFO              ] [Base        ] Leaving application in progress...
[Finished in 2.2s]

```

**Comment by KeyWeeUsr** [comment]
@K9Crunch please try to compile the linked PR and see if it fixed the issue for you.
