### ISSUE TITLE
Scatter cannot be used under StackLayout

### ISSUE THREAD

**Issue by shivan1b** [kivy/kivy#5078]
Using Scatter inside StackLayout throws following error:

 `TypeError: 'tuple' object does not support item assignment`

Checked following in Kivy Catalog:
```
StackLayout
    Scatter
```

**Full traceback**: 
```
Traceback (most recent call last):
   File "/home/ard/code/kivy/examples/demo/kivycatalog/main.py", line 192, in <module>
     KivyCatalogApp().run()
   File "/home/ard/code/kivy/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/ard/code/kivy/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/ard/code/kivy/kivy/core/window/window_sdl2.py", line 640, in mainloop
     self._mainloop()
   File "/home/ard/code/kivy/kivy/core/window/window_sdl2.py", line 392, in _mainloop
     EventLoop.idle()
   File "/home/ard/code/kivy/kivy/base.py", line 348, in idle
     Clock.tick_draw()
   File "/home/ard/code/kivy/kivy/clock.py", line 588, in tick_draw
     self._process_events_before_frame()
   File "kivy/_clock.pyx", line 406, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8421)
   File "kivy/_clock.pyx", line 446, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8295)
   File "kivy/_clock.pyx", line 444, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8216)
   File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3530)
   File "/home/ard/code/kivy/kivy/uix/stacklayout.py", line 321, in do_layout
     c2.pos[innerattr] = u
 TypeError: 'tuple' object does not support item assignment
```

**Comment by KeyWeeUsr** [comment]
Try replacing brackets `(...)` with `[...]` in [L332](https://github.com/kivy/kivy/blob/master/kivy/uix/scatter.py#L332) and [L342](https://github.com/kivy/kivy/blob/master/kivy/uix/scatter.py#L342).

**Comment by Julian-O** [comment]
Don't know when it was fixed, but stacklayout.py no longer contains the offending line.

Closing as completed.

If the problem persists, please let us know.
