### ISSUE TITLE
Android app crashing after pasting unicode string to TextInput

### ISSUE THREAD

**Issue by Fogapod** [kivy/kivy#5096]
### Versions

* Python: 2.7
* OS: android
* Kivy: master
* Buildozer toolchain: android_new

### Description

Kivy android app get crashed after pasting unicode string to `TextInput`.
~~This fix helped me: https://github.com/Fogapod/kivy/commit/2017c6679a0a8c4f0ef9c8eb21c0ffe1d875ce53~~

~~Edit: removing `.encode('utf-8')` will work too~~

Edit: my fixes do not fix anything

### Code and Logs

```python
Traceback (most recent call last):
  File "/home/foga/Main/VKBot/.buildozer/android/app/main.py", line 19, in main
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/app.py", line 828, in run
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/base.py", line 342, in idle
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/base.py", line 327, in dispatch_input
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/base.py", line 233, in post_dispatch_input
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7336)
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1192, in on_motion
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7336)
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1228, in on_touch_up
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7336)
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/uix/textinput.py", line 328, in on_touch_up
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/uix/widget.py", line 479, in on_touch_up
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7336)
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/uix/widget.py", line 479, in on_touch_up
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7336)
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
  File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7295)
  File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:12844)
  File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy/_event.c:11810)
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
  File "/data/user/0/org.vkbot/files/app/lib/python2.7/site-packages/kivy/data/style.kv", line 213, in <module>
    on_release: root.do('paste')
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/uix/textinput.py", line 380, in do
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/uix/textinput.py", line 1723, in paste
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/core/clipboard/__init__.py", line 81, in paste
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/core/clipboard/__init__.py", line 97, in _paste
  File "/home/foga/Main/VKBot/.buildozer/android/platform/build/dists/VKBot/private/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_android.py", line 34, in get
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

```

**Comment by KeyWeeUsr** [comment]
Repasting if something would happen to that commit:

```
diff --git a/kivy/core/clipboard/clipboard_android.py b/kivy/core/clipboard/clipboard_android.py
index 426a4ca..85e3cad 100644
--- a/kivy/core/clipboard/clipboard_android.py
+++ b/kivy/core/clipboard/clipboard_android.py
@@ -31,7 +31,7 @@ def __init__(self):
         PythonActivity._clipboard = None
 
     def get(self, mimetype='text/plain'):
-        return self._get(mimetype).encode('utf-8')
+        return self._get(mimetype).decode('utf8').encode('utf-8')
 
     def put(self, data, mimetype='text/plain'):
         self._set(data, mimetype)
```

**Comment by Fogapod** [comment]
Same problem on old toolchain

**Comment by Fogapod** [comment]
Also unicode text gets corrupted after copying it.

Text in TextInput:
`Привет 123`
Text in clipboard after copying:
`ÐÑÐ²ÐµÑ 123`

**Comment by Fogapod** [comment]
#2418

**Comment by Fogapod** [comment]
#5023

**Comment by Fogapod** [comment]
#3606

**Comment by tshirtman** [comment]
I can copy/paste unicode text in recent kivy apps, i assume this is fixed, at least for python3, closing, feel free to reopen or open a new one if similar bugs are observed.
