### ISSUE TITLE
Packaging on windows with Gstreamer: GstPlayerException Unable to create a playbin. Failed to execute script videoplayer.

### ISSUE THREAD

**Issue by alegonzalezc** [kivy/kivy#5099]
### Versions

* Python: 2.7
* OS: Windows
* Kivy: 1.9.1

### Description

Hi guys. I having a big trouble trying to make work the example of packaging a video app with gstreamer, following the kivy's documentation site [https://kivy.org/docs/guide/packaging-windows.html#packaging-a-video-app-with-gstreamer](url). And when I attempt to execute the .exe file, the app crashes. 
I'm certain that is not the same issue [https://github.com/kivy/kivy/issues/4652](url) because that bug was fixed already.

### Code and Logs

Here is the log that I got:

```
[INFO   ] [Logger      ] Record log in C:\Users\alego_000\.kivy\logs\kivy_17-04-05_0.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-3e1ea73, 20170315
[INFO   ] [Python      ] v3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoGstplayer] Using Gstreamer 1.10.2.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.4.0 - Build 21.20.16.4534'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 520'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <b'4.40 - Build 21.20.16.4534'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[ERROR  ] [Image       ] Error reading file cityCC0.png
[INFO   ] [Base        ] Start application main loop
[ERROR  ] [Image       ] Error loading texture cityCC0.mpg
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\alego_000\Desktop\example-videoPlayer\source\videoplayer.py",
line 26, in <module>
     VideoPlayerApp().run()
   File "C:\Python34\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Python34\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 659, in mainloop
     self._mainloop()
   File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "C:\Python34\lib\site-packages\kivy\base.py", line 348, in idle
     Clock.tick_draw()
   File "C:\Python34\lib\site-packages\kivy\clock.py", line 588, in tick_draw
     self._process_events_before_frame()
   File "kivy\_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8381)
   File "kivy\_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8255)
   File "kivy\_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy\_clock.c:8176)
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
   File "C:\Python34\lib\site-packages\kivy\uix\video.py", line 176, in _do_video_load
     self._video = CoreVideo(filename=filename, **self.options)
   File "C:\Python34\lib\site-packages\kivy\core\video\video_gstplayer.py", line 56, in __init__
     super(VideoGstplayer, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\core\video\__init__.py", line 84, in __init__
     self.filename = kwargs.get('filename')
   File "C:\Python34\lib\site-packages\kivy\core\video\__init__.py", line 116, in <lambda>
     lambda self, x: self._set_filename(x),
   File "C:\Python34\lib\site-packages\kivy\core\video\__init__.py", line 113, in _set_filename
     self.load()
   File "C:\Python34\lib\site-packages\kivy\core\video\video_gstplayer.py", line 68, in load
     self.player.load()
   File "kivy\lib\gstplayer\_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load (kivy\lib/gstplayer\_gstplayer.c:3151)
 kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin
 Failed to execute script videoplayer
```

**Comment by matham** [comment]
This issue is fixed with https://github.com/pyinstaller/pyinstaller/pull/2417. The reason it may crash for you is that this fix is not included yet in the latest version of pyinstaller served on pypi. Please manually try doing the change from https://github.com/pyinstaller/pyinstaller/pull/2417 and see if it fixes it.

**Comment by KeyWeeUsr** [comment]
Tested with master and `videoplayer.py` from examples. Works fine.

**Comment by alegonzalezc** [comment]
Thank you guys. I know you close the ticket already but i'm going to try the pysintaller fix and see.
But can you help with something; Do you know if, in order to do the change of the file proposed in [https://github.com/pyinstaller/pyinstaller/pull/2417](url) in the pyinstaller lib folder, is necessary to compile the edited file or compile the entire lib or something?

**Comment by KeyWeeUsr** [comment]
@alegonzalezc nope, just locate the file in your e.g. `site-packages\PyInstaller\loader\rthooks\pyi_rth_gstreamer.py` and change the colon to `os.pathsep`. Then build the application with PyInstaller again and it'll work just fine. :)

**Comment by alegonzalezc** [comment]
Oh great, thank you @KeyWeeUsr . I' going try that right away. =)

**Comment by alegonzalezc** [comment]
I did the change in the site-packages\PyInstaller\loader\rthooks\pyi_rth_gstreamer.py file, and tried to package the videoplayer.py example again, but I get the same error. =(

`kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin`

@KeyWeeUsr  could you please tell me the version of python that you're using and the version of kivy and the version of windows?

I tried to package the app with python 2.7, kivy 1.9.1, and windows 8.1 pro.

**Comment by KeyWeeUsr** [comment]
1.9.2, latest version with Python 3.5.2, make sure you removed `build` and `dist` folders before building. If that doesn't help, try with the master version with [wheels](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation)

**Comment by alegonzalezc** [comment]
Ok, Thank you so much, I goint to do that.

**Comment by alegonzalezc** [comment]
Thank so much. Finally it works!!! =)

I used python 3.4 and kivy 1.9.2 .

Thank you!

**Comment by blurymind** [comment]
this is still borked
https://github.com/kivy/kivy/issues/5651
