### ISSUE TITLE
Problem installing Kivy with Python 2.7.13

### ISSUE THREAD

**Issue by Billmike** [kivy/kivy#5112]
Tried installing Kivy, but I'm getting this error

C:\Windows\system32>python -m pip install --upgrade pip wheel setuptools
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\site-packages\pip\__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarni
ng
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\__init__.py", line 62
, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\__init__.py"
, line 29, in <module>
    import urllib3
ImportError: No module named urllib3

**Comment by amadeusxnet** [comment]
ImportError: No module named urllib3
You'll get it by 'pip install urllib3'

**Comment by KeyWeeUsr** [comment]
This isn't a fault during Kivy installation, but with an installation/upgrading of pip, wheel, or setuptools. Try what @amadeusxnet said, it should help or reinstall pip.
