### ISSUE TITLE
Kivy not working after installing on windows 10 64 bit DLL Load Failed Error

### ISSUE THREAD

**Issue by fahadhussan** [kivy/kivy#5136]
I  am stuck on it for many days.
After writing this piece of code it gives me the following error

```
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()
```

It gives me this error:

```
[INFO              ] [Logger      ] Record log in C:\Users\Fahad\.kivy\logs\kivy_17-04-23_1.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.5.3 |Anaconda 4.2.0 (64-bit)| (default, Feb 22 2017, 21:28:42) [MSC v.1900 64 bit (AMD64)]
 Traceback (most recent call last):
   File "E:\Study\Semester 4\OS Software Development\Damn Practice\Kivy.py", line 1, in <module>
     from kivy.app import App
   File "C:\Program Files\Anaconda3\lib\site-packages\kivy\app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "C:\Program Files\Anaconda3\lib\site-packages\kivy\base.py", line 30, in <module>
     from kivy.event import EventDispatcher
   File "C:\Program Files\Anaconda3\lib\site-packages\kivy\event.py", line 8, in <module>
     import kivy._event
 ImportError: DLL load failed: The specified module could not be found.
```

**Comment by KeyWeeUsr** [comment]
@fahadhussan Please see the [warning](https://kivy.org/docs/installation/installation-windows.html) at the installation page. Use the wheels until the master version is released as a new stable, because `1.9.1` doesn't officially support Python 3.5+.

That's being said, I'm rather curious of how did you manage to install Kivy as the stable would definitely need a compilation for 3.5, which with Visual Studio returns some errors and with GCC it shouldn't even work (see the linked issue at installation page). Well, correctly at least.
