### ISSUE TITLE
Scrollbar in kivy 1.10

### ISSUE THREAD

**Issue by picibucor** [kivy/kivy#5185]
### Versions

* Python: 3.4
* OS: Win 7
* Kivy:  1.10
* Kivy installation method: "pip install kivy"

### Description

I updated my Kivy to the newest version. Unfortunately I found out that clicking on the scrollbar is breaking my software.  I just pasted my log here. Before the update I was able to use the scrollbar properly.

### Log

```python
[INFO   ] [Logger      ] Record log in C:\Users\mirk\.kivy\logs\kivy_17-05-18_5.txt
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.3.0 - Build 10.18.14.4432'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4600'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <b'4.30 - Build 10.18.14.4432'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [EZS-2G      ] The system parameters are: ['C:\\Mirk\\CETACal\\main.py']
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [EZS-2G      ] loading...
[INFO   ] [EZS-2G      ] Programm starts, and says "Hello!".
[INFO   ] [EZS-2G      ] Sensor-linenumber: 0
[INFO   ] [EZS-2G      ] Sensor-linenumber: 1
[INFO   ] [EZS-2G      ] MeasurePopup Pop-Up is generated
[INFO   ] [Base        ] Start application main loop
[INFO   ] [EZS-2G      ] Sensor-linenumber: 0
[INFO   ] [EZS-2G      ] Sensor-linenumber: 1
[INFO   ] [EZS-2G      ] MeasurePopup Pop-Up is generated
[INFO   ] [EZS-2G      ] ChooseFilePopup Pop-Up is generated
[INFO   ] [EZS-2G      ] ChooseFilePopup Pop-Up is generated
[INFO   ] [EZS-2G      ] Sensor-linenumber: 0
[INFO   ] [EZS-2G      ] Sensor-linenumber: 1
[INFO   ] [EZS-2G      ] MeasurePopup Pop-Up is generated
[INFO   ] [EZS-2G      ] form was generated with vertical-layout
[INFO   ] [EZS-2G      ] content of the protocol: 
{
  "general": {},
  "sensors": {}
}
[INFO   ] [EZS-2G      ] GUI-height-sum: [270, 245, 305, 380, 380, 245, 305, 380], GUI-heights: 2510
[INFO   ] [EZS-2G      ] labels are filled with DE text
[INFO   ] [EZS-2G      ] screen is cleared, and new screen "summary" is loaded.
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Mirk\CETACal\main.py", line 2939, in <module>
     EZS.run()
   File "C:\Python34\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Python34\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
     self._mainloop()
   File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "C:\Python34\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Python34\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Python34\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1188, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\core\window\__init__.py", line 1204, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\scrollview.py", line 601, in on_touch_down
     if self.dispatch('on_scroll_start', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Python34\lib\site-packages\kivy\uix\scrollview.py", line 692, in on_scroll_start
     self._handle_y_pos, self._handle_y_size, touch)):
 AttributeError: 'ScrollView' object has no attribute '_handle_y_pos'

```

**Comment by KeyWeeUsr** [comment]
Please paste some code, otherwise I'm not sure if we can help. I didn't test it yet though, but from a rough look at https://github.com/kivy/kivy/commit/0edae84139113c4f1b02c4c65164a1156f0d343f I think you did something either to the main kv rule for scrollview(own `<ScrollView>`) or did something bad in your code. If there's something we can test, then it might be a bug.

**Comment by picibucor** [comment]
@KeyWeeUsr :

Here is a simple Example:

```
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.scrollview import ScrollView
from kivy.core.window import Window
from kivy.app import runTouchApp

layout = GridLayout(cols=1, spacing=10, size_hint_y=None)
# Make sure the height is such that there is something to scroll.
layout.bind(minimum_height=layout.setter('height'))
for i in range(100):
    btn = Label(text=str(i), size_hint_y=None, height=40)
    layout.add_widget(btn)
root = ScrollView(size_hint=(1, None), size=(Window.width, Window.height), scroll_type=["bars"], bar_width=20, bar_inactive_color=[0.5, 0.5, 0.5, 1])
root.add_widget(layout)

runTouchApp(root)

```

**Comment by picibucor** [comment]
@KeyWeeUsr :

I edited the style.kv, and I copied the old edited one instead of the edited new one. THX for your reply...

**Comment by KeyWeeUsr** [comment]
Yep, I was writing that the example works and you probably did something wrong (or it hasn't updated properly) :)
