### ISSUE TITLE
Invalid property name, button.background_down

### ISSUE THREAD

**Issue by see01995** [kivy/kivy#5188]
### Versions

* Python:v2.7.2
* OS:Android
* Kivy:v1.9.1
* Kivy installation method:APK

### Description

On PC, my app run with .kv normally. but app crashed on Android.
It reported "Invalid property name" of button.background_down in .kv
i commoned off codelines of background_down, then app can work on Android.

### Code and Logs
code:
                Button:
                    id: btn_menu
                    size_hint: (0.15, 1)
                    #text: 'Menu'
                    background_normal: 'icon/icon_ao_button_1.png'
                    background_down  : 'icon/icon_ao_button_1.png'
                    on_release: root.ids.popup_connect.open()

log:
[INFO              ] Logger: Record log in /storage/emulated/0/kivy/kivy_android_usb/.kivy/logs/kivy_17-05-19_4.txt
[INFO              ] Kivy: v1.9.1
[INFO              ] Python: v2.7.2 (default, Mar 20 2016, 23:30:13)
[GCC 4.8]
[INFO              ] Factory: 179 symbols loaded
[WARNING           ] stderr: /data/user/0/org.kivy.pygame/files/lib/python2.7/site-packages/kivy/core/image/img_pygame.py:13: RuntimeWarning: import cdrom: No module named cdrom
[WARNING           ] stderr: (ImportError: No module named cdrom)
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] Text: Provider: pygame
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    Kivy_android_usb().run()
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 801, in run
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 598, in load_kv
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1842, in load_file
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1889, in load_string
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1264, in __init__
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1366, in parse
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1470, in parse_level
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1470, in parse_level
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1470, in parse_level
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1470, in parse_level
  File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1480, in parse_level
kivy.lang.ParserException: Parser: File "./kivy_android_usb.kv", line 71:
/...
     69:                    #text: 'Menu'
     70:                    background_normal: 'icon/icon_ao_button_1.png'
/>>   71:                    background_down  : 'icon/icon_ao_button_1.png'
     72:                    on_release: root.ids.popup_connect.open()
     73:                Label:
/...
Invalid property name

**Comment by dessant** [comment]
> />> 71: background_down : 'icon/icon_ao_button_1.png'

The space before the colon may be causing issues in 1.9.1, though this should also be fixed in 1.10.0.

**Comment by see01995** [comment]
Thanks
