### ISSUE TITLE
Error in Compilation

### ISSUE THREAD

**Issue by ed9bh** [kivy/kivy#5192]
### Versions

* Python: 3.5.0 / 3.6.0 / 2.7.0
* OS: MacOS 10.12.5 / Linux Kivy Buildozer Image
* Kivy: 1.10
* Kivy installation method: Android
* Buildozer: 0.33

### Description

I try compile to android. In the linux image happens the same too.

### Code and Logs

```python
Traceback (most recent call last):
  File "/Users/ed9bh/.pyenv/versions/3.5.0/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/ed9bh/.pyenv/versions/3.5.0/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 905, in <module>
    main()
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 902, in main
    ToolchainCL()
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/build.py", line 565, in build_recipes
    recipe.build_arch(arch)
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 44, in build_arch
    self.do_python_build(arch)
  File "/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 73, in do_python_build
    shprint(sh.cp, self.ctx.hostpython, self.get_build_dir(arch.arch))
AttributeError: 'Context' object has no attribute 'hostpython'
# Command failed: /Users/ed9bh/.pyenv/versions/3.5.0/bin/python3.5 -m pythonforandroid.toolchain create --dist_name=precojusto --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/Users/ed9bh/Dropbox/Work/Desenvolvimento/Python/Projetos/PrecoJusto/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by matham** [comment]
We need example code to reproduce the issue, which is not provided. Also, this repo is for kivy issues, not for buildozer/py4a issues.
