### ISSUE TITLE
Installation issue on Winodws

### ISSUE THREAD

**Issue by SweRavn** [kivy/kivy#5266]
### Versions

* Python: Python 3.5.2 :: Anaconda 4.1.1 (64-bit)
* OS: Winodws 10 64 bit
* Kivy: N.A
* Kivy installation method: According to installation guide on kivy homepage.

### Description

Tried to install according to installation guidelines for Windows. Started the Anaconda prompt as Adminstrator but get the following error:

### Code and Logs

```python
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
Requirement already satisfied: docutils in c:\program files\anaconda3\lib\site-packages
Requirement already satisfied: pygments in c:\program files\anaconda3\lib\site-packages
Collecting pypiwin32
  Downloading pypiwin32-219-cp35-none-win_amd64.whl (8.6MB)
    100% |################################| 8.6MB 117kB/s
Collecting kivy.deps.sdl2
  Downloading kivy.deps.sdl2-0.1.17-cp35-cp35m-win_amd64.whl (2.5MB)
    100% |################################| 2.5MB 333kB/s
Collecting kivy.deps.glew
  Downloading kivy.deps.glew-0.1.9-cp35-cp35m-win_amd64.whl (102kB)
    100% |################################| 112kB 582kB/s
Installing collected packages: pypiwin32, kivy.deps.sdl2, kivy.deps.glew
Exception:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Program Files\Anaconda3\lib\shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Anaconda3\\Lib\\site-packages\\win32\\win32api.pyd'

```

**Comment by bionoid** [comment]
> PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Anaconda3\\Lib\\site-packages\\win32\\win32api.pyd'

Are you running the cmd window as administrator? This looks like incorrect filesystem permissions, not a packaging/installation problem as such

**Comment by KeyWeeUsr** [comment]
To access `Program Files`, `Windows` and many other `C:\` only folders you have to run as administrator. If I were you, I'd move Anaconda to some better place where you as a user have permissions to do stuff instead of leaving it in a folder where you need elevated permissions.

Anyway, this isn't a Kivy issue.
