### ISSUE TITLE
PyInstaller created kivy app stops on ReceycleView

### ISSUE THREAD

**Issue by rjungbeck** [kivy/kivy#5276]
* Python: Python 3.6.1 32 bit
* OS: Windows 10 64
* Kivy: 1.10.0
* Kivy installation method: pip (including kivy.deps,angle, kivy.deps.glew, kivy.deps.gstreamer)
* PyInstaller: 3.3.dev0-gabfc806 (cause release version does not support Python 3.6)

### Description
Application works when started without PyInstaller
Application starts when packaged, but aborts when RecyleView is on opened from App

Similar (unconnected to my app) is on  Stackoverflow https://stackoverflow.com/questions/45068125/recycleview-causing-kivy-executable-to-crash
 

### Spec file

````` python
# -*- mode: python -*-

from kivy.deps import sdl2, glew

block_cipher = None

options = [ ('v', None, 'OPTION') ]


a = Analysis(['meltflow.py'],
             pathex=['C:\\Users\\ruediger.rj-w8\\PycharmProjects\\meltflow'],
             binaries=[],
             datas=[("*.json", "."),
                ("*.kv", "."),
                ('C:\\Users\\ruediger.rj-w8\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\kivy\\data\\*', "data"),
                ('C:\\Users\\ruediger.rj-w8\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\kivy\\data\\fonts\\*', "data/fonts"),
                ('C:\\Users\\ruediger.rj-w8\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\kivy\\data\\glsl\\*', "data/glsl"),
                ('C:\\Users\\ruediger.rj-w8\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\kivy\\data\\images\\*', "data/images"),
                ('C:\\Users\\ruediger.rj-w8\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\kivy\\data\\keyboards\\*', "data/keyboards"),
                ('C:\\Users\\ruediger.rj-w8\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\kivy\\data\\logo\\*', "data/logo"),
                ("locale/de/LC_MESSAGES/*", "locale/de/LC_MESSAGES"),
                ("locale/en/LC_MESSAGES/*", "locale/en/LC_MESSAGES"),
                ("rst/*", "rst"),
                ("artwork", "artwork"),
                ("*.png", "."),
                ("data/log/dummy.txt", "data/log")],
             hiddenimports=["kivy.uix.recycleview.__init__."],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          options,
          exclude_binaries=True,
          name='meltflow',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
                *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               strip=False,
               upx=True,
               name='meltflow')
`````

#### Log

````
Traceback (most recent call last):
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\meltflow.py", line 277, in main
    app.run()
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\menu.py", line 149, in on_release
    self.doRelease()
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\menu.py", line 155, in doRelease
    self.sequencer.runSequence(self.cmd["action"], done=self.doneHandler, error=self.error)
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\sequencer.py", line 165, in runSequence
    self.curSequence=Sequence(self, seq, done=done, error=error)
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\sequencer.py", line 335, in __init__
    self.step()
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\sequencer.py", line 341, in step
    self.execute()
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\sequencer.py", line 377, in execute
    cont=obj.run()
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\seqentity.py", line 117, in run
    entityselect.EntitySelect(self.sequencer, self.curCmd, done=self.completed, error=self.error)
  File "C:\Users\ruediger.rj-w8\PycharmProjects\meltflow\entityselect.py", line 39, in __init__
    XPopup.__init__(self, title=gettext(cmd["title"]), **kwargs)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\modalview.py", line 152, in __init__
    super(ModalView, self).__init__(**kwargs)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
    super(AnchorLayout, self).__init__(**kwargs)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\widget.py", line 345, in __init__
    Builder.apply(self, ignored_consts=self._kwargs_applied_init)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\lang\builder.py", line 451, in apply
    self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\lang\builder.py", line 567, in _apply_rule
    self._apply_rule(child, crule, rootrule)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\lang\builder.py", line 526, in _apply_rule
    cls = Factory_get(cname)
  File "C:\users\ruediger.rj-w8\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\factory.py", line 139, in __getattr__
    module = __import__(name=item['module'], fromlist='.')
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivy.uix.recycleview.__init__.'

```

**Comment by mdurian** [comment]
I'm seeing the same bug. It appears in both Windows and Mac builds. Here's a slightly different traceback.
[mac_traceback.txt](https://github.com/kivy/kivy/files/1157469/mac_traceback.txt)

**Comment by matham** [comment]
It's because of https://github.com/kivy/kivy/blob/master/kivy/factory_registers.py#L190. That is there because of https://github.com/kivy/kivy/pull/4108#issuecomment-199003918 which is caused by https://github.com/kivy/kivy/issues/2163. 

In other words, if I remember correctly, I explicitly listed `kivy.uix.recycleview.__init__` because otherwise `__import__` is having issues. This can be fixed by replacing the usage of `__import__` I think? 

A quick fix for the issue with pyinstaller is to change e.g. `r('RecycleViewBehavior', module='kivy.uix.recycleview.__init__')` to `r('RecycleViewBehavior', module='kivy.uix.recycleview')`.

**Comment by mdurian** [comment]
That quick fix didn't help (at least on the mac build, I haven't tried the windows build). I also experimented with removing __init__ from the following line. Without the __init__ the runtime error is
ImportError: No module named 'kivy.uix.recycleview'
instead of
ImportError: No module named 'kivy.uix.recycleview.__init__'

**Comment by matham** [comment]
Try replacing `module = __import__(name=item['module'], fromlist='.')` in `factory.py` with:

```py
import importlib
module = importlib.import_module(item['module'])
```
And remove the __init__.py form factory registers.

If that doesn't fix it then try adding `kivy.uix.recycleview` to `hidden_imports` (note that the original example above has a type there because it ends with a period).

**Comment by mdurian** [comment]
Modifying factory.py and removing the `__init__.py` forms worked on the mac build. It almost works on the windows build.

Under windows, the app now crashes in a different place. It doesn't crash when run from the command line. Just from a pyinstaller build. I'm thinking it might be related since the traceback mentions `frozen importlib._bootstrap`, but maybe that's a red herring.

```
Traceback (most recent call last):
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
 ImportError: No module named 'win32timezone'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
 SystemError: PyEval_EvalFrameEx returned a result with an error set

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "dashboard\dashboard.py", line 428, in <module>
   File "site-packages\kivy\app.py", line 828, in run
   File "site-packages\kivy\base.py", line 504, in runTouchApp
   File "site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
   File "site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
   File "site-packages\kivy\base.py", line 339, in idle
   File "site-packages\kivy\clock.py", line 581, in tick
   File "kivy\_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events
(kivy\_clock.c:7700)
   File "kivy\_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events
(kivy\_clock.c:7577)
   File "kivy\_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events
(kivy\_clock.c:7498)
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock
.c:3490)
   File "site-packages\kivy\uix\filechooser.py", line 697, in _update_files
   File "site-packages\kivy\uix\filechooser.py", line 717, in _create_files_entr
ies
   File "site-packages\kivy\uix\filechooser.py", line 828, in _generate_file_ent
ries
   File "site-packages\kivy\uix\filechooser.py", line 860, in _add_files
   File "site-packages\kivy\uix\filechooser.py", line 860, in <listcomp>
   File "site-packages\kivy\uix\filechooser.py", line 178, in is_hidden
   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
 SystemError: PyEval_EvalFrameEx returned a result with an error set
```

**Comment by mdurian** [comment]
Adding win32timezone to hidden files in the PyInstaller spec fixed the Windows problem.
`hiddenimports=['win32timezone']`

**Comment by matham** [comment]
Great, I'll make a pr with the fix. Not sure what is up with the `win32timezone`. But I'm guessing it's specific to your app.

**Comment by rjungbeck** [comment]
win32timezone seems to be required for FileChooser (at least for my app).

**Comment by mdurian** [comment]
I use FileBrowser in my app, so that must be it.

**Comment by KeyWeeUsr** [comment]
@rjungbeck @mdurian 

[1](https://github.com/kivy/kivy/search?utf8=%E2%9C%93&q=win32timezone&type=), [2](https://github.com/kivy-garden/garden.filebrowser/search?utf8=%E2%9C%93&q=win32timezone&type=), [3](https://github.com/kivy-garden/garden.filebrowser/search?utf8=%E2%9C%93&q=_find_and_load_unlocked&type=), [4](https://github.com/kivy/kivy/search?utf8=%E2%9C%93&q=_find_and_load_unlocked&type=)

Nope, but again ref [Hidden Imports](https://pythonhosted.org/PyInstaller/#id67) and maybe you didn't *explicitly* call something from that, but only used a part of that kind of package with Win32 API, which called that sub-part ([example?](https://stackoverflow.com/q/33212949/5994041)).

So, just check for any specific Win32 API calls through pywin32 (or something like that, because they change(d) the name) package if there's anything related to timezones or time. Or just start cutting parts off until it works to find the specific lines. That's just when you would like to debug it, you don't *need* to do it.

**Comment by E-Unit** [comment]
@matham. I had the same issue and I made the changes as per your suggestion. After sorting out the 'inconsistent tabs' issue (differences in editors used) it worked like a charm.
After modifying the Factory.py file, is it still necessary to include the 'recycleview' package in the 'hidden imports`?

**Comment by LYU-Daliang** [comment]
@matham I ran across the same problem with `PyInstaller`  on `Windows 7`. I appied the quick fix to `factory_registers.py` and it worked!

> A quick fix for the issue with pyinstaller is to change e.g. r('RecycleViewBehavior', module='kivy.uix.recycleview.__init__') to r('RecycleViewBehavior', module='kivy.uix.recycleview').

PS `factory_registers.py` also has `r('RecycleView', module='kivy.uix.recycleview.__init__')`, I didn't touch it.
