### ISSUE TITLE
App crashes at a second time launch

### ISSUE THREAD

**Issue by yangyangxcf** [kivy/kivy#5309]
### Versions

* Python: 2.7
* OS: android
* Kivy: <s>1.9.1</s>1.10.1-dev(master)
* Kivy installation method: pip

### Description

I compile the app and find it work at first time launch.
However, when I quit it (press the 'back' button of an android phone) and launch it a second time (just press the icon on the desktop), the app gets 
`AttributeError: type object 'kivy._clock.ClockEvent' has no attribute '__reduce_cython__'` and crashes. 
I launch it a third time and it gets 
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.y.x/org.kivy.android.PythonActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.` 
I think it has something to do with the previous crash. 
And the fourth time again works.
I grep '__reduce_cython__' in both kivy and cython codes and find nothing. I'm wondering what's that and what causes the crash.
I'll appreciate if you can help me.

### Code and Logs

log for the second time launch
```python
W/PropertyValuesHolder(  743): Method setBrightness() with type int not found on target class class hg
W/PropertyValuesHolder(  743): Method getBrightness() with type int not found on target class class hg
I/ActivityManager(  529): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.y.x/org.kivy.android.PythonActivity bnds=[10,450][186,690] (has extras)} from pid 743
D/dalvikvm(  529): GC_FOR_ALLOC freed 1018K, 22% free 8452K/10732K, paused 10ms, total 11ms
W/ContextImpl(  743): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1137 android.content.ContextWrapper.sendBroadcast:370 com.vphone.launcher.Stats.recordLaunch:129 com.vphone.launcher.Launcher.c:3069 com.vphone.launcher.Launcher.onClickAppShortcut:3037 
V/PythonActivity( 2606): My oncreate running
V/SDL     ( 2606): getting identifier
V/SDL     ( 2606): kind is drawable and name presplash
V/SDL     ( 2606): result is 2130837506
W/NetworkManagementSocketTagger(  529): setKernelCountSet(10045, 1) failed with errno -13
D/dalvikvm( 2606): GC_FOR_ALLOC freed 1141K, 31% free 3034K/4396K, paused 5ms, total 5ms
I/dalvikvm-heap( 2606): Grow heap (frag case) to 3.957MB for 916952-byte allocation
D/dalvikvm( 2606): GC_FOR_ALLOC freed 7K, 11% free 3923K/4396K, paused 5ms, total 5ms
D/dalvikvm( 2606): GC_CONCURRENT freed 0K, 11% free 3923K/4396K, paused 3ms+1ms, total 8ms
V/PythonActivity( 2606): Ready to unpack
V/PythonActivity( 2606): UNPACKING!!! private files
V/SDL     ( 2606): asked to get string private_version
V/SDL     ( 2606): getting identifier
V/SDL     ( 2606): kind is string and name private_version
V/SDL     ( 2606): result is 2130968577
V/PythonActivity( 2606): Data version is 1501251060.9
V/PythonActivity( 2606): About to do super onCreate
V/SDL     ( 2606): Device: LMY47X.G6000ZCS2AQA1
V/SDL     ( 2606): Model: HUAWEI G750-T00
V/SDL     ( 2606): onCreate():null
D/dalvikvm( 2606): Trying to load lib /data/app-lib/org.y.x-1/libSDL2.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/app-lib/org.y.x-1/libSDL2.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/app-lib/org.y.x-1/libSDL2_image.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/app-lib/org.y.x-1/libSDL2_image.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/app-lib/org.y.x-1/libSDL2_mixer.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/app-lib/org.y.x-1/libSDL2_mixer.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/app-lib/org.y.x-1/libSDL2_ttf.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/app-lib/org.y.x-1/libSDL2_ttf.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/app-lib/org.y.x-1/libpython2.7.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/app-lib/org.y.x-1/libpython2.7.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/app-lib/org.y.x-1/libmain.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/app-lib/org.y.x-1/libmain.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/data/org.y.x/files/lib/python2.7/lib-dynload/_io.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/data/org.y.x/files/lib/python2.7/lib-dynload/_io.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/data/org.y.x/files/lib/python2.7/lib-dynload/unicodedata.so 0x95000a80
D/dalvikvm( 2606): Shared lib '/data/data/org.y.x/files/lib/python2.7/lib-dynload/unicodedata.so' already loaded in same CL 0x95000a80
D/dalvikvm( 2606): Trying to load lib /data/data/org.y.x/files/lib/python2.7/lib-dynload/_ctypes.so 0x95000a80
E/dalvikvm( 2606): dlopen("/data/data/org.y.x/files/lib/python2.7/lib-dynload/_ctypes.so") failed: dlopen failed: library "/data/data/org.y.x/files/lib/python2.7/lib-dynload/_ctypes.so" not found
V/PythonUtil( 2606): Unsatisfied linker when loading ctypes
V/PythonUtil( 2606): Loaded everything!
V/PythonActivity( 2606): Did super onCreate
V/PythonActivity( 2606): Setting env vars for start.c and Python to use
V/PythonActivity( 2606): Access to our meta-data...
I/PythonActivity( 2606): Surface will NOT be transparent
V/SDL     ( 2606): onResume()
V/PhoneStatusBar(  591): setLightsOn(true)
V/SDL     ( 2606): surfaceCreated()
V/SDL     ( 2606): surfaceChanged()
V/SDL     ( 2606): pixel format RGB_565
V/SDL     ( 2606): Window size:900x1440
I/SDL     ( 2606): SDL_Android_Init()
I/SDL     ( 2606): SDL_Android_Init() finished!
I/python  ( 2606): Initialize Python for Android
I/python  ( 2606): Changing directory to the one provided by ANDROID_ARGUMENT
I/python  ( 2606): /data/data/org.y.x/files
I/python  ( 2606): Preparing to initialize python
I/python  ( 2606): crystax_python does not exist
I/python  ( 2606): Initialized python
I/python  ( 2606): AND: Init threads
I/python  ( 2606): testing python print redirection
I/python  ( 2606): Setting up python from ANDROID_PRIVATE
I/python  ( 2606): ('Android path', ['/data/data/org.y.x/files/lib/python27.zip', '/data/data/org.y.x/files/lib/python2.7/', '/data/data/org.y.x/files/lib/python2.7/lib-dynload/', '/data/data/org.y.x/files/lib/python2.7/site-packages/', '/data/data/org.y.x/files'])
I/python  ( 2606): ('os.environ is', {'ANDROID_APP_PATH': '/data/data/org.y.x/files', 'EXTERNAL_STORAGE': '/storage/emulated/legacy', 'LOOP_MOUNTPOINT': '/mnt/obb', 'ANDROID_SOCKET_zygote': '9', 'BOOTCLASSPATH': '/system/framework/core.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework2.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/webviewchromium.jar', 'ANDROID_PROPERTY_WORKSPACE': '8,0', 'PATH': '/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin', 'ANDROID_STORAGE': '/storage', 'ANDROID_BOOTLOGO': '1', 'EMULATED_STORAGE_TARGET': '/storage/emulated', 'ANDROID_ASSETS': '/system/app', 'LD_LIBRARY_PATH': '/vendor/lib:/system/lib', 'ANDROID_PRIVATE': '/data/data/org.y.x/files', 'ANDROID_ENTRYPOINT': 'main.pyo', 'PYTHONPATH': '/data/data/org.y.x/files:/data/data/org.y.x/files/lib', 'ANDROID_DATA': '/data', 'EMULATED_STORAGE_SOURCE': '/mnt/shell/emulated', 'PYTHON_NAME': 'python', 'ANDROID_ROOT': '/system', 'PYTHONHOME': '/data/data/org.y.x/files', 'ASEC_MOUNTPOINT': '/mnt/asec', 'ANDROID_ARGUMENT': '/data/data/org.y.x/files'})
I/python  ( 2606): ('Android kivy bootstrap done. __name__ is', '__main__')
I/python  ( 2606): ['/data/data/org.y.x/files/lib/python2.7/site-packages', '/data/data/org.y.x/files/lib/site-python']
I/python  ( 2606): AND: Ran string
I/python  ( 2606): Run user program, change dir and execute entrypoint
I/python  ( 2606): main.py
I/Choreographer(  529): Skipped 32 frames!  The application may be doing too much work on its main thread.
V/SDL     ( 2606): onWindowFocusChanged(): true
V/PhoneStatusBar(  591): setLightsOn(true)
I/ActivityManager(  529): Displayed org.y.x/org.kivy.android.PythonActivity: +585ms
W/ContextImpl(  529): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1123 com.android.server.InputMethodManagerService.hideCurrentInputLocked:1880 com.android.server.InputMethodManagerService.windowGainedFocus:1968 com.android.internal.view.IInputMethodManager$Stub.onTransact:221 com.android.server.InputMethodManagerService.onTransact:818 
I/python  ( 2606): [INFO   ] [Logger      ] Record log in /data/data/org.y.x/files/.kivy/logs/kivy_17-07-30_1.txt
I/python  ( 2606): [INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20170726
I/python  ( 2606): [INFO   ] [Python      ] v2.7.2 (default, Jul 26 2017, 10:39:08) 
I/python  ( 2606): [GCC 4.9.x 20150123 (prerelease)]
I/python  ( 2606):  Traceback (most recent call last):
I/python  ( 2606):    File "main.py", line 11, in <module>
I/python  ( 2606):      from kivy.app import App
I/python  ( 2606):    File "/data/data/org.y.x/files/lib/python2.7/site-packages/kivy/app.py", line 319, in <module>
I/python  ( 2606):      from kivy.base import runTouchApp, stopTouchApp
I/python  ( 2606):    File "/data/data/org.y.x/files/lib/python2.7/site-packages/kivy/base.py", line 26, in <module>
I/python  ( 2606):      from kivy.clock import Clock
I/python  ( 2606):    File "/data/data/org.y.x/files/lib/python2.7/site-packages/kivy/clock.py", line 362, in <module>
I/python  ( 2606):      from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
I/python  ( 2606):    File "kivy/_clock.pyx", line 14, in init kivy._clock
I/python  ( 2606):  AttributeError: type object 'kivy._clock.ClockEvent' has no attribute '__reduce_cython__'
I/python  ( 2606): Python for android ended.
V/SDL     ( 2606): onWindowFocusChanged(): false
D/dalvikvm(  529): GC_FOR_ALLOC freed 865K, 22% free 8394K/10732K, paused 13ms, total 13ms
V/SDL     ( 2606): onPause()
V/SDL     ( 2606): nativePause()
W/ContextImpl(  529): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1123 com.android.server.InputMethodManagerService.hideCurrentInputLocked:1880 com.android.server.InputMethodManagerService.windowGainedFocus:1968 com.android.internal.view.IInputMethodManager$Stub.onTransact:221 com.android.server.InputMethodManagerService.onTransact:818 
V/SDL     ( 2606): surfaceDestroyed()
W/NetworkManagementSocketTagger(  529): setKernelCountSet(10045, 0) failed with errno -13
V/SDL     ( 2606): onDestroy()
```

and the third time
```python
W/PropertyValuesHolder(  743): Method setBrightness() with type int not found on target class class hg
W/PropertyValuesHolder(  743): Method getBrightness() with type int not found on target class class hg
I/ActivityManager(  529): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.y.x/org.kivy.android.PythonActivity bnds=[10,450][186,690] (has extras)} from pid 743
D/dalvikvm(  529): GC_FOR_ALLOC freed 1169K, 22% free 8409K/10732K, paused 11ms, total 11ms
W/ContextImpl(  743): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1137 android.content.ContextWrapper.sendBroadcast:370 com.vphone.launcher.Stats.recordLaunch:129 com.vphone.launcher.Launcher.c:3069 com.vphone.launcher.Launcher.onClickAppShortcut:3037 
V/PythonActivity( 2606): My oncreate running
W/NetworkManagementSocketTagger(  529): setKernelCountSet(10045, 1) failed with errno -13
D/AndroidRuntime( 2606): Shutting down VM
W/dalvikvm( 2606): threadid=1: thread exiting with uncaught exception (group=0x94d05b20)
E/AndroidRuntime( 2606): FATAL EXCEPTION: main
E/AndroidRuntime( 2606): Process: org.y.x, PID: 2606
E/AndroidRuntime( 2606): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.y.x/org.kivy.android.PythonActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
E/AndroidRuntime( 2606): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2219)
E/AndroidRuntime( 2606): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269)
E/AndroidRuntime( 2606): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 2606): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 2606): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2606): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2606): 	at android.app.ActivityThread.main(ActivityThread.java:5045)
E/AndroidRuntime( 2606): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2606): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2606): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2606): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2606): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2606): Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
E/AndroidRuntime( 2606): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:3562)
E/AndroidRuntime( 2606): 	at android.view.ViewGroup.addView(ViewGroup.java:3415)
E/AndroidRuntime( 2606): 	at android.view.ViewGroup.addView(ViewGroup.java:3391)
E/AndroidRuntime( 2606): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:309)
E/AndroidRuntime( 2606): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:299)
E/AndroidRuntime( 2606): 	at android.app.Activity.setContentView(Activity.java:1949)
E/AndroidRuntime( 2606): 	at org.kivy.android.PythonActivity.showLoadingScreen(PythonActivity.java:349)
E/AndroidRuntime( 2606): 	at org.kivy.android.PythonActivity.onCreate(PythonActivity.java:55)
E/AndroidRuntime( 2606): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 2606): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
E/AndroidRuntime( 2606): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
E/AndroidRuntime( 2606): 	... 11 more
W/ActivityManager(  529):   Force finishing activity org.y.x/org.kivy.android.PythonActivity
I/WindowManager(  529): Screenshot max retries 4 of Token{4a981088 ActivityRecord{4a9cd274 u0 org.y.x/org.kivy.android.PythonActivity t8 f}} appWin=Window{4a911020 u0 Starting org.y.x} drawState=1
W/WindowManager(  529): Screenshot failure taking screenshot for (900x1440) to layer 21020
D/dalvikvm(  529): GC_FOR_ALLOC freed 817K, 25% free 8142K/10732K, paused 26ms, total 26ms
I/dalvikvm-heap(  529): Grow heap (frag case) to 9.151MB for 1127532-byte allocation
D/dalvikvm(  529): GC_FOR_ALLOC freed 1K, 22% free 9241K/11836K, paused 24ms, total 24ms
W/WindowManager(  529): updateFocusedWindowLocked, focusedAppToken is null.
D/DropBoxEntryAddedChimeraService( 1006): User is not opted-in to Usage & Diagnostics or Lockbox.
W/ActivityManager(  529): Activity pause timeout for ActivityRecord{4a9cd274 u0 org.y.x/org.kivy.android.PythonActivity t8 f}
W/NetworkManagementSocketTagger(  529): setKernelCountSet(10045, 0) failed with errno -13
W/ContextImpl(  529): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1123 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:9640 com.android.server.am.ActivityManagerService.handleApplicationCrash:9614 android.app.ActivityManagerNative.onTransact:1311 com.android.server.am.ActivityManagerService.onTransact:2071 
I/Process ( 2606): Sending signal. PID: 2606 SIG: 9
W/InputMethodManagerService(  529): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4a9627f4 attribute=null, token = android.os.BinderProxy@4a911fcc
I/ActivityManager(  529): Process org.y.x (pid 2606) has died.
I/Finsky  (  945): [1] com.google.android.finsky.utils.dm.onTrimMemory(25): Memory trim requested to level 5
```

**Comment by KeyWeeUsr** [comment]
I believe you are using an older version of `python-for-android`, because there was a PR related to this and although I can't find it, I think it has been merged. Try to update `python-for-android` to the master branch and rebuild your app.

    pip install -U https://github.com/kivy/python-for-android/zipball/master

**Comment by yangyangxcf** [comment]
It looks work! And also I find I missed 'android' in requirements, without that recipe, the app crashes if I quit before the loading has finished and launch the app again. Though I cannot yet figure out the reason.
Thanks a lot!
