### ISSUE TITLE
ActionBar throws exception when resized

### ISSUE THREAD

**Issue by tiktok7** [kivy/kivy#5333]
### Versions
* Python: 3.4.3
* OS: Linux-3.13.0-24-generic-x86_64
* Kivy: 1.10.1.dev0
* Kivy installation method: manual (git repo)

### Description
Steps to recreate the problem
1. Run `python3 ./kivy/uix/actionbar.py`
2. Resize the width down until an exception occurs

### Code and Logs
In `ActionView._layout_random()`, when the width contracts, newly hidden entries are added to `hidden_groups` which is in turn added to `hidden_items`. All hidden items are then added to `self.overflow_group` (so the Help menu item is no longer displayed unless the ellipsis is clicked). Unfortunately this means that the `ActionView.remove_widget()` later fails because it tries to remove the group from the action items list even though it's not contained in it. 

I'm not entirely sure what the correction should be but I verified the problem with the following change (which allows the same code to handle resizes without the same crash happening)

```
diff --git a/kivy/uix/actionbar.py b/kivy/uix/actionbar.py
index 5e4f400..c8161d7 100644
--- a/kivy/uix/actionbar.py
+++ b/kivy/uix/actionbar.py
@@ -491,7 +491,8 @@ class ActionView(BoxLayout):
         super(ActionView, self).remove_widget(widget)
         if isinstance(widget, ActionOverflow):
             for item in widget.list_action_item:
-                self._list_action_items.remove(item)
+                if item in self._list_action_items:
+                    self._list_action_items.remove(item)
 
         if widget in self._list_action_items:
             self._list_action_items.remove(widget)
```

#### Trace
```
[DEBUG  ] [Window      ] Resize window to (296, 600)
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "actionbar.py", line 779, in <module>
     runTouchApp(float_layout)
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/core/window/window_sdl2.py", line 660, in mainloop
     self._mainloop()
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/core/window/window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/base.py", line 346, in idle
     Clock.tick_draw()
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/clock.py", line 588, in tick_draw
     self._process_events_before_frame()
   File "kivy/_clock.pyx", line 405, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8381)
   File "kivy/_clock.pyx", line 445, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8255)
   File "kivy/_clock.pyx", line 443, in kivy._clock.CyClockBase._process_events_before_frame (kivy/_clock.c:8176)
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3490)
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/uix/boxlayout.py", line 309, in do_layout
     c.size = (w, h)
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__ (kivy/properties.c:5572)
   File "kivy/properties.pyx", line 1342, in kivy.properties.ReferenceListProperty.set (kivy/properties.c:21169)
   File "kivy/properties.pyx", line 494, in kivy.properties.Property.set (kivy/properties.c:6520)
   File "kivy/properties.pyx", line 516, in kivy.properties.Property.set (kivy/properties.c:6405)
   File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch (kivy/properties.c:7105)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (kivy/_event.c:14035)
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch (kivy/_event.c:13193)
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/uix/actionbar.py", line 648, in on_width
     self._layout_random()
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/uix/actionbar.py", line 557, in _layout_random
     self._clear_all()
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/uix/actionbar.py", line 501, in _clear_all
     self.clear_widgets()
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/uix/widget.py", line 605, in clear_widgets
     remove_widget(child)
   File "/home/will/Projects/kivy/kivy_git/kivy/kivy/uix/actionbar.py", line 494, in remove_widget
     self._list_action_items.remove(item)
 ValueError: list.remove(x): x not in list

```

**Comment by KeyWeeUsr** [comment]
@tiktok7 If you can, please open a pull request, so that you can take credit for the fix with your GitHub account or create a git patch :)

**Comment by tiktok7** [comment]
@KeyWeeUsr I'd be happy to. I just wasn't sure whether there was some other action to take on the hidden group. Is the change above enough?

**Comment by KeyWeeUsr** [comment]
If it's enough, I don't think so. But it stops the crashing because of mis-synced lists. The whole thing just tries to remove a widget when there's no space but most likely didn't take care of the corner cases. I've tested the change with resizing the window and it worked ok. Also, the same condition is even a little bit below.

If you want to dig further, it appears `ActionOverflow.list_action_item` and `ActionView._list_action_items` aren't synced properly for some reason I guess because of some `on_property` event. The `in` condition however needs to be there anyway.

**Comment by tiktok7** [comment]
@KeyWeeUsr Thanks for the quick feedback.
