### ISSUE TITLE
Jnius/Java NullPointerException in Android compas example

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5344]
### Versions

* Python: 2.7.2
* OS: Android
* Kivy: master

### Description

Trying to test&merge #4950 I encountered a weird error. I remember the example working quite well, so I wonder... perhaps there's a bug in jnius or the `org.renpy.android.Hardware` is broken?

### Code and Logs

```python
Traceback (most recent call last):
  File "/storage/emulated/0/kivy/compass/main.py", line 68, in <module>
    CompassApp().run()
  File "/home/kivy/.local/share/python-for-android/dists/mylaunchertest_sdl2/private/lib/python2.7/site-packages/kivy/app.py", line 802, in run
  File "/storage/emulated/0/kivy/compass/main.py", line 41, in build
    Hardware.magneticFieldSensorEnable(True)
  File "jnius/jnius_export_class.pxi", line 637, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:22329)
  File "jnius/jnius_export_class.pxi", line 820, in jnius.jnius.JavaMethod.call_staticmethod (jnius/jnius.c:24351)
  File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception (jnius/jnius.c:3739)
    jnius.jnius.JavaException: JVM exception occurred: java.lang.NullPointerException
```

**Comment by n1980212** [comment]
Hi,
    has anyone resolve this problem? thks.
