### ISSUE TITLE
setup.py should not depend on the existence of `git` on the system

### ISSUE THREAD

**Issue by vanschelven** [kivy/kivy#5365]
### Versions

* Python: 3.5.3
* OS: nixos
* Kivy: 1.10.0
* Kivy installation method: nix

### Description

I tried to package kivy for nixos, a Purely Functional Linux Distribution.

```
 Traceback (most recent call last):
   File "nix_run_setup.py", line 8, in <module>
     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
   File "setup.py", line 934, in <module>
     version=get_version(),
   File "setup.py", line 47, in get_version
     ['git', 'rev-parse', 'HEAD']
   File "/nix/store/kgh0z7i2n7xl6pvanmi0v8dw4qy63932-python3-3.5.3/lib/python3.5/subprocess.py", line 316, in check_output
     **kwargs).stdout
   File "/nix/store/kgh0z7i2n7xl6pvanmi0v8dw4qy63932-python3-3.5.3/lib/python3.5/subprocess.py", line 383, in run
     with Popen(*popenargs, **kwargs) as process:
   File "/nix/store/kgh0z7i2n7xl6pvanmi0v8dw4qy63932-python3-3.5.3/lib/python3.5/subprocess.py", line 676, in __init__
     restore_signals, start_new_session)
   File "/nix/store/kgh0z7i2n7xl6pvanmi0v8dw4qy63932-python3-3.5.3/lib/python3.5/subprocess.py", line 1282, in _execute_child
     raise child_exception_type(errno_num, err_msg)
 FileNotFoundError: [Errno 2] No such file or directory: 'git'
```
This can be attributed to `setup.py` attempting to run `git`. This was introduced here:

https://github.com/kivy/kivy/pull/4949/commits/ffcb437fc6d183f3e34db180c9b0f0220bf2e08b

I would postulate that the install-time dependency on `git` is unnecessary and bad practice.

**Comment by KeyWeeUsr** [comment]
Ah, sorry for this one! Unfortunately I couldn't really reproduce this error on Windows and experienced it only indirectly through some launchpad build log, but apparently the `CalledProcessError` wasn't enough to catch it.

Obviously we *need* git to fetch the version hash, so we can't really exclude it completely, however it should fallback to the `"Unknown"` revision instead. We still have the date and version, but a specific hash helps with debugging if something is fixed recently and the person uses e.g. stable or not so recent master branch.

**Comment by vanschelven** [comment]
Thanks, that was very quick!
