### ISSUE TITLE
`pip install kivy` in virtualenv fails with error: `'../include/config.pxi' not found`

### ISSUE THREAD

**Issue by sietse** [kivy/kivy#5391]
### Versions

* Python: 2.7.12
* OS: Ubuntu 16.04 LTS
* Kivy: 1.10.0, master (7991cef)
* Kivy installation method: pip + virtualenv

### Description

(As the included code makes this issue rather long, here is the structure of the headings so you can head straight for the bit most relevant to you.) 

    ### Versions
    ### Description
    ### Code and Logs
    #### Relevant bits from strace
    #### Full traceback
    #### Steps to reproduce
    ##### Vagrant usage
    ##### Vagrantfile

I am attempting to install kivy in a virtualenv, following [the official instructions](https://kivy.org/docs/installation/installation-linux.html#installation-in-a-virtual-environment). However, when I reach the step where I run `pip install kivy` I get the following error (full traceback and steps to reproduce further down):

       [...]
       File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 474, in included_files
         include_path = self.context.find_include_file(include, None)
       File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 274, in find_include_file
         error(pos, "'%s' not found" % filename)
       File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Compiler/Errors.py", line 177, in error
         raise InternalError(message)
     Cython.Compiler.Errors.InternalError: Internal compiler error: '../include/config.pxi' not found

**Where should config.pxi come from, and what should it contain? Am I missing an installation step, or is this due to an assumption in Kivy's setup.py?**

By inserting traces, I found the installation process looks for config.pxi in these locations:

* /tmp/pip-build-MB2bZR/include/config.pxi
* /home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/include/config.pxi

### Code and Logs

* The problem occurs both with `pip install kivy==1.10.0` and with `pip install git+https://github.com/kivy/kivy.git@master`.

* The problem occurs in [`find_include_file` in Cython 0.25's Main.py](https://github.com/cython/cython/blob/0.25/Cython/Compiler/Main.py#L268).

#### Relevant bits from strace

(Thanks to Julia Evans for her [zine explaining `strace`](https://jvns.ca/zines/#strace-zine)!)

    utimes("/tmp/pip-build-PQ2L9G/kivy/kivy/graphics/tesselator.pxd", [{1485276501, 0}, {1485276501, 0}]) = 0
    stat("/tmp/pip-build-PQ2L9G/kivy/kivy", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
    mkdir("/tmp/pip-build-PQ2L9G/kivy/kivy/graphics", 0777) = -1 EEXIST (File exists)
    open("/tmp/pip-build-PQ2L9G/kivy/kivy/graphics/instructions.pxd", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
    fstat(5, {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
    fstat(5, {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
    write(5, "include \"../include/config.pxi\"\n"..., 3564) = 3564
    [...]
    stat("/tmp/pip-build-PQ2L9G/kivy/kivy/graphics/../include/config.pxi", 0x7ffc556c92a0) = -1 ENOENT (No such file or directory)
    getcwd("/tmp/pip-build-PQ2L9G/kivy", 1024) = 27
    getcwd("/tmp/pip-build-PQ2L9G/kivy", 1024) = 27
    stat("./../include/config.pxi", 0x7ffc556c89c0) = -1 ENOENT (No such file or directory)
    stat("/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Includes/../include/config.pxi", 0x7ffc556c89c0) = -1 ENOENT (No such file or directory)

#### Full traceback

    (kivy) vagrant@vagrant:~$ pip install kivy==1.10.0
    Collecting kivy==1.10.0
      Using cached Kivy-1.10.0.tar.gz
        Complete output from command python setup.py egg_info:
        fatal: Not a git repository (or any of the parent directories): .git
        Using distutils
        
        Detected Cython version 0.25
        Using this graphics system: OpenGL
        GStreamer found via pkg-config
        WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)
        
        Package sdl2 was not found in the pkg-config search path.
        Perhaps you should add the directory containing `sdl2.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'sdl2' found
        Package SDL2_ttf was not found in the pkg-config search path.
        Perhaps you should add the directory containing `SDL2_ttf.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'SDL2_ttf' found
        Package SDL2_image was not found in the pkg-config search path.
        Perhaps you should add the directory containing `SDL2_image.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'SDL2_image' found
        Package SDL2_mixer was not found in the pkg-config search path.
        Perhaps you should add the directory containing `SDL2_mixer.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'SDL2_mixer' found
        
        
        running egg_info
        creating pip-egg-info/Kivy.egg-info
        writing requirements to pip-egg-info/Kivy.egg-info/requires.txt
        writing pip-egg-info/Kivy.egg-info/PKG-INFO
        writing top-level names to pip-egg-info/Kivy.egg-info/top_level.txt
        writing dependency_links to pip-egg-info/Kivy.egg-info/dependency_links.txt
        writing manifest file 'pip-egg-info/Kivy.egg-info/SOURCES.txt'
         Traceback (most recent call last):
           File "<string>", line 1, in <module>
           File "/tmp/pip-build-JTLGTF/kivy/setup.py", line 1060, in <module>
             ] if not skip_cython else [])
           File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
             dist.run_commands()
           File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
             self.run_command(cmd)
           File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
             cmd_obj.run()
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 280, in run
             self.find_sources()
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 295, in find_sources
             mm.run()
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 526, in run
             self.add_defaults()
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
             sdist.add_defaults(self)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
             self._add_defaults_ext()
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
             build_ext = self.get_finalized_command('build_ext')
           File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
             cmd_obj.ensure_finalized()
           File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
             self.finalize_options()
           File "/tmp/pip-build-JTLGTF/kivy/setup.py", line 251, in finalize_options
             retval = build_ext.finalize_options(self)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 19, in finalize_options
             self.distribution.ext_modules)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 809, in cythonize
             aliases=aliases)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 714, in create_extension_list
             kwds = deps.distutils_info(file, aliases, base).values
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 590, in distutils_info
             return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 600, in transitive_merge
             node, extract, merge, seen, {}, self.cimported_files)[0]
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 605, in transitive_merge_helper
             deps = extract(node)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 581, in distutils_info0
             externs = self.cimports_and_externs(filename)[1]
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Utils.py", line 44, in wrapper
             res = cache[args] = f(self, *args)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 491, in cimports_and_externs
             for include in self.included_files(filename):
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Utils.py", line 44, in wrapper
             res = cache[args] = f(self, *args)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 474, in included_files
             include_path = self.context.find_include_file(include, None)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 285, in find_include_file
             error(pos, "'%s' not found" % filename)
           File "/home/vagrant/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Compiler/Errors.py", line 177, in error
             raise InternalError(message)
         Cython.Compiler.Errors.InternalError: Internal compiler error: '../include/config.pxi' not found

#### Steps to reproduce

If you do not want to use Vagrant, look for this code block in the Vagrantfile below:

      config.vm.provision "shell", inline: <<-SHELL
        # ... this is the code you need ...
      SHELL

Because the steps to reproduce include `sudo apt-get install`, I have placed
them in a Vagrantfile. Vagrant makes it trivial to create and destroy virtual
machines that have the same environment every time. This is useful for
reproducible development environments, but also to demonstrate bugs.

##### Vagrant usage

* Install Vagrant from [https://www.vagrantup.com]()
* Create a directory, and place the contents below in a file called `Vagrantfile`
* `cd` to the directory and run `vagrant up`

That's it! The problem mentioned above will occur at the end of the provisioning. From there, you might want to:

* `vagrant ssh` to SSH into the virtual machine
* `vagrant halt` to shut down the machine; `vagrant up` to restart it
* `vagrant destroy` + `vagrant up` to recreate the machine from scratch
* `vagrant provision` to rerun the provisioning script.

##### Vagrantfile

Call this file `Vagrantfile`. See the previous section for usage.

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    # All Vagrant configuration is done below. The "2" in Vagrant.configure
    # configures the configuration version (we support older styles for
    # backwards compatibility). Please don't change it unless you know what
    # you're doing.
    Vagrant.configure("2") do |config|

      config.vm.box = "bento/ubuntu-16.04"

      config.vm.synced_folder "data", "/vagrant_data"

      config.vm.provision "shell", inline: <<-SHELL
        apt-get update

        sudo apt-get install -y \
          build-essential \
          mercurial \
          git \
          virtualenv \
          virtualenvwrapper \
          python2.7 \
          python-dev \
          libfreetype6-dev \
          libjpeg-dev \
          libav-tools \
          libsdl-image1.2-dev \
          libsdl-mixer1.2-dev \
          libsdl-ttf2.0-dev \
          libsmpeg-dev \
          libsdl1.2-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libfreetype6-dev \
          unzip \
          zlib1g-dev

          su vagrant
          # The following commands are run as the vagrant user
             mkvirtualenv kivy
             # also activates the venv, so the following commands are run inside it
                 pip install cython==0.25
                 pip install kivy==1.10.0
      SHELL
    end

**Comment by sietse** [comment]
This error does not occur with

    pip install cython==0.23
    pip install kivy==1.91.1

It may have to do with 00b2ddbcb02edc661a77d3ca23dd2e91554f50f7, 'path changes for config.pxi'.

**Comment by rubencabrera** [comment]
Hi, @sietse, is it possible that the exact commands are:
```
pip install Cython==0.23
pip install kivy==1.9.1
```
These didn't yield any errors for me.

**Comment by sietse** [comment]
Hi @rubencabrera, thank you for looking at this issue. The combination that I am reporting a problem with is

    pip install Cython==0.25
    pip install kivy==1.10.0

, which fails with the following error:

    Cython.Compiler.Errors.InternalError: Internal compiler error: '../include/config.pxi' not found

A quick overview of other version combinations, to save you some experimentation:

* `Cython==0.23` plus `kivy==1.91.1` was a typo: Kivy 'one point ninety-one' does not exist. I have edited my post above accordingly.
* `Cython==0.23` plus `kivy==1.9.1` is the most recent combination proposed by the docs that works.
* `Cython==0.25` plus `kivy==1.10.1` (suggested by the [official documentation](https://kivy.org/docs/installation/installation-linux.html#installation-in-a-virtual-environment) since 2017-07-24) throws an error because there is no Kivy `1.10.1` on PyPI.

Do you know anything about `config.pxi`, what it should contain, and why Cython fails to find it in `/tmp/pip-build-PQ2L9G/kivy/kivy/graphics/../include/config.pxi`,
`./../include/config.pxi`, or `$HOME/.virtualenvs/kivy/local/lib/python2.7/site-packages/Cython/Includes/../include/config.pxi`?

**Comment by andrewm41** [comment]
Confirm,
Cython 0.25 results in config.pxi error while installing kivy 1.10.0

I'm using virtualenv in Debian 8.9.

**Comment by der-spaete-jo** [comment]
I run into a similar error (at least the beginning of the traceback is quite similar). I will downgrade cython and try it with kivy==1.9.1. Nevertheless, here are my configurations and traceback.

### Versions

* Python: 2.7.14 (custom/manual python, not the "build-in python")
* OS: Lubuntu (32bit) 16.04.3 LTE
* Kivy: 1.10 (cython==0.25)
* Kivy installation method: "on ubuntu inside a virtualenv" (actually I am using pipenv)

### Description

I try to install kivy using pipenv. I follow the Ubuntu example for "Dependencies with SDL2" found on [kivy docs](https://kivy.org/docs/installation/installation-linux.html).

### Code and Logs

```
arbo@TINY-HAPPY:~/Projects/CalcGame/v0.1.7$ pipenv-27 install cython==0.25
Installing cython==0.25…
Collecting cython==0.25
  Downloading Cython-0.25-cp27-cp27m-manylinux1_i686.whl (5.8MB)
Installing collected packages: cython
Successfully installed cython-0.25

Adding cython==0.25 to Pipfile's [packages]…
Pipfile.lock (8dac7e) out of date, updating to (7f4b87)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (7f4b87)!
Installing dependencies from Pipfile.lock (7f4b87)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/14 — 00:00:19
To activate this project's virtualenv, run the following:
 $ pipenv shell
arbo@TINY-HAPPY:~/Projects/CalcGame/v0.1.7$ pipenv-27 graph
Cython==0.25
docutils==0.14
Kivy-Garden==0.1.4
  - requests [required: Any, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.1.18]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
matplotlib==2.2.2
  - backports.functools-lru-cache [required: Any, installed: 1.5]
  - cycler [required: >=0.10, installed: 0.10.0]
    - six [required: Any, installed: 1.11.0]
  - kiwisolver [required: >=1.0.1, installed: 1.0.1]
    - setuptools [required: Any, installed: 39.0.1]
  - numpy [required: >=1.7.1, installed: 1.14.2]
  - pyparsing [required: >=2.0.1,!=2.1.6,!=2.0.4,!=2.1.2, installed: 2.2.0]
  - python-dateutil [required: >=2.1, installed: 2.7.0]
    - six [required: >=1.5, installed: 1.11.0]
  - pytz [required: Any, installed: 2018.3]
  - six [required: >=1.10, installed: 1.11.0]
  - subprocess32 [required: Any, installed: 3.2.7]
pandas==0.22.0
  - numpy [required: >=1.9.0, installed: 1.14.2]
  - python-dateutil [required: Any, installed: 2.7.0]
    - six [required: >=1.5, installed: 1.11.0]
  - pytz [required: >=2011k, installed: 2018.3]
Pygments==2.2.0

arbo@TINY-HAPPY:~/Projects/CalcGame/v0.1.7$ pipenv install kivypipenv: command not found
arbo@TINY-HAPPY:~/Projects/CalcGame/v0.1.7$ pipenv-27 install kivy
Installing kivy…
Collecting kivy
  Using cached Kivy-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Using distutils
    
    Detected Cython version 0.25
    Using this graphics system: OpenGL
    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)
    
    Package gstreamer-1.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gstreamer-1.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gstreamer-1.0' found
    
    
    SDL2 found via pkg-config
    SDL2: found SDL header at /usr/include/SDL2/SDL.h
    SDL2: found SDL_mixer header at /usr/include/SDL2/SDL_mixer.h
    SDL2: found SDL_ttf header at /usr/include/SDL2/SDL_ttf.h
    SDL2: found SDL_image header at /usr/include/SDL2/SDL_image.h
    fatal: Not a git repository (or any of the parent directories): .git
    running egg_info
    creating pip-egg-info/Kivy.egg-info
    writing requirements to pip-egg-info/Kivy.egg-info/requires.txt
    writing pip-egg-info/Kivy.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/Kivy.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/Kivy.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/Kivy.egg-info/SOURCES.txt'
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-hpqx75/kivy/setup.py", line 1060, in <module>
         ] if not skip_cython else [])
       File "/opt/Python-27/lib/python2.7/distutils/core.py", line 151, in setup
         dist.run_commands()
       File "/opt/Python-27/lib/python2.7/distutils/dist.py", line 953, in run_commands
         self.run_command(cmd)
       File "/opt/Python-27/lib/python2.7/distutils/dist.py", line 972, in run_command
         cmd_obj.run()
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 278, in run
         self.find_sources()
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
         mm.run()
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 524, in run
         self.add_defaults()
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
         sdist.add_defaults(self)
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
         self._add_defaults_ext()
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
         build_ext = self.get_finalized_command('build_ext')
       File "/opt/Python-27/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
         cmd_obj.ensure_finalized()
       File "/opt/Python-27/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
         self.finalize_options()
       File "/tmp/pip-build-hpqx75/kivy/setup.py", line 251, in finalize_options
         retval = build_ext.finalize_options(self)
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 19, in finalize_options
         self.distribution.ext_modules)
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 809, in cythonize
         aliases=aliases)
       File "/home/arbo/.local/share/virtualenvs/v0.1.7-nZ9Ze13X/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 752, in create_extension_list
         **kwds))
       File "/tmp/pip-build-hpqx75/kivy/setup.py", line 511, in __init__
         self.sources = args[1]
     IndexError: tuple index out of range
    
    ----------------------------------------

Error:  An error occurred while installing kivy!
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hpqx75/kivy/

```

**Comment by AaryamanCodes** [comment]
Can someone please offer a solution for windows? I really need it.

**Comment by suvidh** [comment]
facing the same issue in wsl 2 Ubuntu 20

**Comment by AaryamanCodes** [comment]
@suvidh 
Hi, try re-installing Python, possibly 3.5+ then it should work!

**Comment by Julian-O** [comment]
I am closing this as stale.

If you are still having this problem with Python >=3.7 and Kivy 2.2.1, please let us know.
