### ISSUE TITLE
Not able to use Kivy for Python3.5 in Ubuntun 16.04, 64-bit.

### ISSUE THREAD

**Issue by IQYottabit** [kivy/kivy#5410]
I've the problem in using pythong3.5 in Kivy I get this following error. Perhaps I might missing any utility to be installed? 

Note: I can able to run Kivy in python2.7 without any problem.

----

Extra information about my host:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	        16.04
Codename:	xenial

Error log:
-----------

[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - TypeError: expected bytes, str found
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 65, in core_select_lib
    cls = cls()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 121, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 616, in __init__
    self.create_window()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 171, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 60, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1447)

x11 - ImportError: No module named 'kivy.core.window.window_x11'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kivy/utils.py", line 360, in __get__
     retval = self.func(inst)
   File "/usr/lib/python3/dist-packages/kivy/metrics.py", line 169, in dpi
     EventLoop.ensure_window()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 126, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.

**Comment by dessant** [comment]
You're [still](https://github.com/kivy/kivy/issues/3751#issuecomment-332785747) using an old Kivy version, judging by this log message: `Unable to find any valuable Window provider at all!`. Follow the installation instructions to get the latest one and share the full log, not just the traceback. Also make sure to fill in the issue template with the requested data.

https://kivy.org/docs/installation/installation-linux.html

**Comment by IQYottabit** [comment]
Thanks, that solved the issue. I update the Kivy 1.10.0 now.

**Comment by yoelk** [comment]
This happens to me as well. Here are the logs:
https://gist.github.com/yoelk/60edface44222f3955c478871b24ad24

The strange thing is, it doesn't happen always, only sometimes. Resetting the PC solves it (until next time)
