### ISSUE TITLE
Kivy Does not wait for Cython to be installed during PIP installation

### ISSUE THREAD

**Issue by dhoomakethu** [kivy/kivy#5411]
### Versions

* Python: 2.7
* OS: MAC OSX 
* Kivy: 1.9.1
* Kivy installation method: PIP

### Description
I have a python project ,which uses KIVY for its GUI, The project requirements is as below
```
click>=6.7
Cython==0.25.2
docutils==0.13.1
Kivy==1.9.1
Kivy-Garden==0.1.4
# modbus-tk==0.5.6
pygame==1.9.2
pyglet==1.2.4
Pygments==2.1.3
# pymodbus==1.3.2
pyserial==3.2.1
requests==2.12.4
```
When installing the Package with PIP, Kivy bails out before the Cython is installed at all. This makes it hard to distribute the package as it requires people to be explicitly told to install `cython` as a pre-requisite. I would rather prefer the installation to fail while compiling kivy  because of the missing dependencies than failing pre-maturely .

### Code and Logs

```
Processing ./modbus-simulator/dist/modbus_simulator-1.0.tar.gz
Requirement already satisfied: click>=6.7 in /Users/sanjay/.virtualenvs/test/lib/python2.7/site-packages (from modbus-simulator==1.0)
Collecting Cython==0.25.2 (from modbus-simulator==1.0)
  Downloading Cython-0.25.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.1MB)
    100% |████████████████████████████████| 4.1MB 1.6MB/s
Collecting docutils==0.13.1 (from modbus-simulator==1.0)
  Downloading docutils-0.13.1-py2-none-any.whl (537kB)
    100% |████████████████████████████████| 542kB 1.7MB/s
Collecting Kivy==1.9.1 (from modbus-simulator==1.0)
  Downloading kivy-1.9.1.tar.gz (16.4MB)
    100% |████████████████████████████████| 16.4MB 3.3MB/s
    Complete output from command python setup.py egg_info:
    Using distutils

    Cython is missing, its required for compiling kivy !


    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fj/bb6fj6zd1wb9sxnb1bj4fcbc0000gn/T/pip-build-pDSJaL/Kivy/setup.py", line 184, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fj/bb6fj6zd1wb9sxnb1bj4fcbc0000gn/T/pip-build-pDSJaL/Kivy/
```

**Comment by KeyWeeUsr** [comment]
duplicate #5375
