### ISSUE TITLE
Some phones don't allow access to /sdcard

### ISSUE THREAD

**Issue by RodADavison** [kivy/kivy#5448]
I'm a new user of RaceCapture which is user of Kivy.  I've encountered this error on my Huawei phone which throws an exception:

10-12 09:05:43.501 10388 10428 I python  : [CRITICAL] [Traceback (most recent call last)] 
10-12 09:05:43.501 10388 10428 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/main.py", line 608, in <module> 
10-12 09:05:43.501 10388 10428 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/main.py", line 168, in __init__ 
10-12 09:05:43.501 10388 10428 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/build/dists/racecapture/private/lib/python2.7/site-packages/kivy/app.py", line 780, in user_data_dir 
10-12 09:05:43.501 10388 10428 I python  : OSError: [Errno 2] No such file or directory: '/sdcard/racecapture' 

I've noticed 2 related bug reports here:
https://github.com/kivy/kivy/issues/2990 
https://github.com/kivy/kivy/issues/5259 

The code in kivy/app.py (around line 771)
            data_dir = join('/sdcard', self.name)
should be replaced using the android api requests something like:
            from jnius import autoclass 
            env = autoclass('android.os.Environment') 
            data_dir = join(env.getExternalStorageDirectory().getPath(), self.name )

**Comment by KeyWeeUsr** [comment]
ref #5237, probably missed that part. I'll include it soon and hopefully even merge. :)

**Comment by RodADavison** [comment]
Thanks for the quick and positive response KeyWee.  My read of #5237, is it refers to the /sdcard reference in the `get_application_config` function.  The one I'm referring to is in the `user_data_dir` function (in the same file).  Perhaps this issue should be merged with 5237 and both references could be changed at the same time.
Thanks.

**Comment by tshirtman** [comment]
sorry, my mistake, that does seem more at home in kivy.
