### ISSUE TITLE
Problem install Kivy on ubuntu 17.10

### ISSUE THREAD

**Issue by gabeta** [kivy/kivy#5488]
### Versions

* Python: 3.6.3
* OS: ubuntu 17.10
* Kivy:1.10.0
* Kivy installation method: sudo apt-get install python3-kivy

### Code and Logs

```python
 Traceback (most recent call last):
   File "test.py", line 4, in <module>
     from kivy.app import App
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 30, in <module>
     from kivy.event import EventDispatcher
   File "/usr/lib/python3/dist-packages/kivy/event.py", line 8, in <module>
     import kivy._event
 ImportError: /usr/lib/python3/dist-packages/kivy/_event.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

**Comment by KeyWeeUsr** [comment]
#5453 duplicate
