### ISSUE TITLE
Compile of jnius.c fails during Buildozer run for Python3  Kivy 1.10 

### ISSUE THREAD

**Issue by rogermorrell** [kivy/kivy#5492]
### Versions

* Python: 3.5.2
* OS: Ubuntu 16.04.3 LTS - ZENCode's virtual machine
* Kivy: 1.10
* Kivy installation method:

### Description

I was trying to run Buildozer to build an Android  version of my Python3 Kivy App.  ZENCode said he had not done the Python3 Buildozer yet.

On a previous run I found that the crystax code was not there and that it was required for the python3  python-for-android so I downloaded crystax-ndk-10.3.2-linux-x86_64.tar.xz from the crystax site.  This appeared to work. 

Then Buildozer ran , it said that a compile would fail the first time, which it and it ran it a second time and it failed again.  It appears that gcc detected an error but them crashed.  This appeared to be in a parallel backgound task.  Here is part of the log 

```
skipping 'jnius/jnius.c' Cython extension (up-to-date)	
building 'jnius' extension	
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/home/kivy/ksa/crystax-ndk/sources/python/3.5/include/python -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c jnius/jnius.c -o build/temp.linux-x86_64-3.5/jnius/jnius.o	
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_py_invoke0':	
jnius/jnius.c:32529:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]	
   __pyx_t_2 = ((PyObject *)((void *)__pyx_v_jptr));	
                             ^	
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_create_proxy_instance':	
jnius/jnius.c:33735:46: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]	
   __pyx_t_1 = __Pyx_PyInt_From_PY_LONG_LONG(((PY_LONG_LONG)((void *)__pyx_v_py_obj))); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 165, __pyx_L1_error)	
                                              ^	
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1)	
Please submit a full bug report,	
with preprocessed source if appropriate.	
See <https://tracker.crystax.net/projects/ndk> for instructions.	
error: command '/usr/bin/ccache' failed with exit status 4
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius && /usr/bin/python3.5 setup.py build_ext -v

[WARNING]: ERROR: /usr/bin/python3.5 failed!
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=SuperMagic --bootstrap=sdl2 --requirements=python3crystax,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/ksa/roger/.buildozer/android/platform/build
# 
```
### Code and Logs

*This is my buildozer.spec file*
#############################
```
[app]

# (str) Title of your application


title = SuperMagic

# (str) Package name
package.name = SuperMagic

# (str) Package domain (needed for android/ios packaging)
package.domain = magictimers.com

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
#version = 0.1

# (str) Application versioning (method 2)
version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = python3crystax,kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = landscape

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY


python_version = 3

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Android API to use
android.api = 19

# (int) Minimum API required
android.minapi = 13

# (int) Android SDK version to use
android.sdk = 23

# (str) Android NDK version to use
android.ndk = 9c

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = ~/ksa/crystax-ndk

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (str) python-for-android branch to use, defaults to master
#p4a.branch = stable

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

####################################
*This is the  command I typed*
buildozer -v android debug deploy

####################################
*this is the complete log *

***************************************************************

```
----------
id: 192 or "extra-google-webdriver"
     Type: Extra
     Desc: Google Web Driver, revision 2
           By Google Inc.
           Install path: extras/google/webdriver

# Check that aidl can be executed
# Search for Aidl
# Run '/home/kivy/.buildozer/android/platform/android-sdk-23/build-tools/27.0.1/aidl'
# Cwd None
# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=SuperMagic --bootstrap=sdl2 --requirements=python3crystax,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/ksa/roger/.buildozer/android/platform/build'
# Cwd /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[WARNING]: NDK version was set as r9c, but checking the NDK dir claims it is 10.3.2.
[WARNING]: The build will try to continue, but it may fail and you should check that your setting is correct.
[WARNING]: If the NDK dir result is correct, you don't need to manually set the NDK ver.
[INFO]:    Using Crystax NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3crystax', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name SuperMagic and recipes (python3crystax, kivy)
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> running cp -r /home/kivy/ksa/roger/.bu...(and 187 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is ['hostpython3crystax', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3crystax
[INFO]:    Skipping hostpython3crystax download as no URL is set
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/...(and 53 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_image download already cached, skipping                        
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/...(and 53 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    sdl2_mixer download already cached, skipping                        
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/...(and 51 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    sdl2_ttf download already cached, skipping                          
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading python3crystax
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/...(and 57 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/python3crystax
[INFO]:    -> running basename 
[INFO]:    -> running rm -f .mark-
[INFO]:    -> running touch .mark-
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/....(and 46 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/....(and 45 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping                               
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/...(and 50 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    pyjnius download already cached, skipping                           
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/kivy/ksa/roger/....(and 46 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    kivy download already cached, skipping                              
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3crystax for armeabi-v7a
[INFO]:    Skipping hostpython3crystax unpack as no URL is set
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.or...(and 52 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 48 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking python3crystax for armeabi-v7a
[INFO]:    -> running basename 
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a
[INFO]:    python3crystax is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org...(and 26 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/kivy-python3crystax-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3crystax for armeabi-v7a
[INFO]:    hostpython3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3crystax for armeabi-v7a
[INFO]:    python3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3crystax for armeabi-v7a
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building python3crystax for armeabi-v7a
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python3crystax/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Building six for armeabi-v7a
[INFO]:    six apparently isn't already in site-packages
[INFO]:    Installing six into site-packages
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a/six
[INFO]:    -> running python3.5 setup.py install -O2...(and 111 more)
[INFO]:    <- directory context /home/kivy/ksa/roger/.buildozer/android/platform/python-for-android-master
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    jnius apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in pyjnius
[INFO]:    -> directory context /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius
[INFO]:    -> running python3.5 -c import sys; print(sys.path)
[INFO]:    Trying first build of pyjnius to get cython files: this is expected to fail
[INFO]:    -> running python3.5 setup.py build_ext -v
cwd is /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius
Exception in thread background thread for pid 5710:                            
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python3.5 setup.py build_ext -v

  STDOUT:
/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '1.1.2-dev' to '1.1.2.dev0'
  normalized_version,
running build_ext
cythoning jnius/jnius.pyx to jnius/jnius.c
building 'jnius' extension
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/jnius
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/home/kivy/ksa/crystax-ndk/sources/python/3.5/include/python -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c jnius/jnius.c -o build/temp.linux-x86_64-3.5/jnius/jnius.o
jnius/jnius.c: In function '__pyx_f_5jnius_py_invoke0':
jnius/jnius.c:32529:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   __pyx_t_2 = ((PyObject *)((void *)__pyx_v_jptr));
                             ^
jnius/jnius.c: In function '__pyx_f_5jnius_create_proxy_instance':
jnius/jnius.c:33735:46: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   __pyx_t_1 = __Pyx_PyInt_From_PY_LONG_LONG(((PY_LONG_LONG)((void *)__pyx_v_py_obj))); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 165, __pyx_L1_error)
                                              ^
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://tracker.crystax.net/projects/ndk> for instructions.
error: command '/usr/bin/ccache' failed with exit status 4


  STDERR:


[INFO]:    pyjnius first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize jnius/jnius.pyx
[INFO]:    -> running cython ./jnius/jnius.pyx
[INFO]:    -> running python3.5 setup.py build_ext -v

Exception in thread background thread for pid 5839:                            
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/kivy/.local/lib/python3.5/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python3.5 setup.py build_ext -v

  STDOUT:
/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '1.1.2-dev' to '1.1.2.dev0'
  normalized_version,
running build_ext
skipping 'jnius/jnius.c' Cython extension (up-to-date)
building 'jnius' extension
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/home/kivy/ksa/crystax-ndk/sources/python/3.5/include/python -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c jnius/jnius.c -o build/temp.linux-x86_64-3.5/jnius/jnius.o
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_py_invoke0':
jnius/jnius.c:32529:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   __pyx_t_2 = ((PyObject *)((void *)__pyx_v_jptr));
                             ^
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_create_proxy_instance':
jnius/jnius.c:33735:46: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   __pyx_t_1 = __Pyx_PyInt_From_PY_LONG_LONG(((PY_LONG_LONG)((void *)__pyx_v_py_obj))); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 165, __pyx_L1_error)
                                              ^
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://tracker.crystax.net/projects/ndk> for instructions.
error: command '/usr/bin/ccache' failed with exit status 4


  STDERR:


[INFO]:    STDOUT:
	/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '1.1.2-dev' to '1.1.2.dev0'	
  normalized_version,	
running build_ext	
skipping 'jnius/jnius.c' Cython extension (up-to-date)	
building 'jnius' extension	
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/home/kivy/ksa/crystax-ndk/sources/python/3.5/include/python -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kivy/ksa/crystax-ndk/platforms/android-19/arch-arm -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c jnius/jnius.c -o build/temp.linux-x86_64-3.5/jnius/jnius.o	
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_py_invoke0':	
jnius/jnius.c:32529:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]	
   __pyx_t_2 = ((PyObject *)((void *)__pyx_v_jptr));	
                             ^	
jnius/jnius.c: In function '__pyx_f_5jnius_5jnius_create_proxy_instance':	
jnius/jnius.c:33735:46: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]	
   __pyx_t_1 = __Pyx_PyInt_From_PY_LONG_LONG(((PY_LONG_LONG)((void *)__pyx_v_py_obj))); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 165, __pyx_L1_error)	
                                              ^	
arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1)	
Please submit a full bug report,	
with preprocessed source if appropriate.	
See <https://tracker.crystax.net/projects/ndk> for instructions.	
error: command '/usr/bin/ccache' failed with exit status 4
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/kivy/ksa/roger/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius && /usr/bin/python3.5 setup.py build_ext -v

[WARNING]: ERROR: /usr/bin/python3.5 failed!
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=SuperMagic --bootstrap=sdl2 --requirements=python3crystax,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/ksa/roger/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
kivy@kivy-complete:~/ksa/roger$ 
```

**Comment by tshirtman** [comment]
> arm-linux-androideabi-gcc: internal compiler error: Killed (program cc1)

seems like it's an issue in crystax, i don't know if it got solved since the bug was reported, but if not, it would be best to see with that project what could cause this.

**Comment by AndreMiras** [comment]
Thanks for the bug report.
Yes it's more a p4a issue and we moved away from CrystaX indeed. Give it another try and open an issue in p4a if you thing there's a bug there.
