### ISSUE TITLE
Kivy mystery problem 

### ISSUE THREAD

**Issue by alkopop79** [kivy/kivy#5498]
* Kivy: 1.10.1dev

I have different versions of the same project in a directory. The idea of to display sensor values with labels. The files worked fine until I placed a file in the directory and tried to import it. The said file allows me to change the color of labels. After I removed and deleted the offending file and removed the import line from the code, the problem still persist. Let me emphasize, I have reverted ALL files into their original, working state and removed the offending file. 

### Code and Logs

```
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder
from kivy.clock import Clock
import random

import LabelB # the offending file, removing this line makes no difference

from tinkerforge.ip_connection import IPConnection
from tinkerforge.brick_dc import BrickDC
from tinkerforge.bricklet_ambient_light import BrickletAmbientLight
from tinkerforge.bricklet_motion_detector import BrickletMotionDetector

HOST = "localhost"
PORT = 4223
light_UID = 'uM9'
motion_UID = 'qo9'

ipcon = IPConnection()          # Create IP connection
al = BrickletAmbientLight(light_UID, ipcon)   # Create device object
md = BrickletMotionDetector(motion_UID, ipcon)
ipcon.connect(HOST, PORT)       # Connect to brickd

root = Builder.load_string('''
<Demo>:
    cols: 1
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        padding: 10
        Label:
            id: lbl0
            size_hint: .1, .1
            pos_hint: {'x': .1, 'center_y': .1}
            font_size: 48
        Label:
            id: lbl1
            size_hint: .1, .1
            pos_hint: {'x': .1, 'center_y': .2}
            font_size: 48
            canvas.before:
            Color:
                rgba: 1, 0, 0, 0.3


''')
class Demo(BoxLayout):
    def __init__(self, *args, **kwargs):
        BoxLayout.__init__(self, *args, **kwargs)
        Clock.schedule_interval(self.getvals, 0.01)

    def getvals(self, dt):
        # rand_val = random.randint(0, 10)
        self.ids.lbl0.text = str(al.get_illuminance())
        self.ids.lbl1.text = str(md.get_motion_detected())
        # print(rand_val)

class MainApp(App):
    def build(self):
        return Demo()

if __name__ == '__main__':
    MainApp().run()
```

The Kivy log and errors: python2 2.py
```
[INFO   ] [Logger      ] Record log in /Users/alkopop79/.kivy/logs/kivy_17-11-23_49.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20171104
[INFO   ] [Python      ] v2.7.14 (default, Sep 25 2017, 09:54:19) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <2.1 NVIDIA-10.4.12 310.90.30.05b27>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <NVIDIA GeForce GT 330M OpenGL Engine>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.20>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
 Traceback (most recent call last):
   File "2.py", line 61, in <module>
     MainApp().run()
   File "/usr/local/lib/python2.7/site-packages/kivy/app.py", line 803, in run
     root = self.build()
   File "2.py", line 58, in build
     return Demo()
   File "2.py", line 47, in __init__
     BoxLayout.__init__(self, *args, **kwargs)
   File "/usr/local/lib/python2.7/site-packages/kivy/uix/boxlayout.py", line 131, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/usr/local/lib/python2.7/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "/usr/local/lib/python2.7/site-packages/kivy/lang/builder.py", line 451, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "/usr/local/lib/python2.7/site-packages/kivy/lang/builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/local/lib/python2.7/site-packages/kivy/lang/builder.py", line 567, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/usr/local/lib/python2.7/site-packages/kivy/lang/builder.py", line 565, in _apply_rule
     widget.add_widget(child)
   File "/usr/local/lib/python2.7/site-packages/kivy/uix/widget.py", line 521, in add_widget
     'add_widget() can be used only with instances'
 kivy.uix.widget.WidgetException: add_widget() can be used only with instances of the Widget class.
```

The offending file: 

```from kivy.uix.label import Label
from kivy.properties import ListProperty

from kivy.factory import Factory
from kivy.lang import Builder

Builder.load_string("""
<LabelB>:
  bcolor: 1, 1, 1, 1
  canvas.before:
    Color:
      rgba: self.bcolor
    Rectangle:
      pos: self.pos
      size: self.size
""")

class LabelB(Label):
  bcolor = ListProperty([1,1,1,1])

Factory.register('KivyB', module='LabelB')`

**Comment by dessant** [comment]
I imagine it must be frustrating to encounter bugs which appear to defy logic, but this seems to be a better fit for IRC or the mailing list.

**Comment by alkopop79** [comment]
Apologies, I will move it to the support channels! @dessant Indeed frustrating! Thanks you for your reply, I will try IRC!

**Comment by alkopop79** [comment]
Just opened a topic in the support channel. Please remove/delete or close this issue!
