### ISSUE TITLE
Type Error on 3d Rendering example

### ISSUE THREAD

**Issue by BaelfireNightshade** [kivy/kivy#5502]
### Versions

* Python: 3.6.3:2c5fed8
* OS: Windows 10 Pro (Build: 16299.64)
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I'm trying to run the example 3d Rendering script
I've made sure that my Kivy, python 3, and the example scripts, are up to date, but it still gives the error
```
File "C:\Users\████\Desktop\Kivy\3dRendering\objloader.py", line 64, in finish_object
     data = [v[0], v[1], v[2], n[0], n[1], n[2], t[0], t[1]]
 TypeError: 'map' object is not subscriptable
```
I've already seen #1977, but as mentioned, my python, kivy, and example scripts are up to date (which includes the fixes mentioned in that issue resolution).

### Code and Logs

Console Log:
```
C:\Users\████\Desktop\Kivy\3dRendering>main.py
[INFO   ] [Logger      ] Record log in C:\Users\████\.kivy\logs\kivy_17-11-27_19.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.4.0 - Build 21.20.16.4541'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <b'4.40 - Build 21.20.16.4541'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Shader      ] Read <C:\Users\████\Desktop\Kivy\3dRendering\simple.glsl>
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:6: '' :  #version directive missing">
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:6: '' :  #version directive missing">
 Traceback (most recent call last):
   File "C:\Users\████\Desktop\Kivy\3dRendering\main.py", line 76, in <module>
     RendererApp().run()
   File "C:\Users\████\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "C:\Users\████\Desktop\Kivy\3dRendering\main.py", line 72, in build
     return Renderer()
   File "C:\Users\████\Desktop\Kivy\3dRendering\main.py", line 30, in __init__
     self.scene = ObjFile(resource_find("monkey.obj"))
   File "C:\Users\████\Desktop\Kivy\3dRendering\objloader.py", line 129, in __init__
     self.finish_object()
   File "C:\Users\████\Desktop\Kivy\3dRendering\objloader.py", line 64, in finish_object
     data = [v[0], v[1], v[2], n[0], n[1], n[2], t[0], t[1]]
 TypeError: 'map' object is not subscriptable

```

**Comment by MaddoxRauch** [comment]
`self.texcoords.append(map(float, values[1:3]))` on line 112 in the objloader.py file needs to have the `map()` function wrapped in a `list()` function. `map()` returns an iterator. Like so `self.texcoords.append(list(map(float, values[1:3])))`
