### ISSUE TITLE
MemoryError installation at 99%.

### ISSUE THREAD

**Issue by zzj0402** [kivy/kivy#5510]
### Versions

* Python: Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
* OS: Windows 10 Home , Version 1703, OS Build 15063.726
* Kivy: 1.10.0
* Kivy installation method: https://kivy.org/docs/installation/installation-windows.html#Installation 2. python -m pip install kivy.deps.gstreamer

### Description

I tried to install Kivy following the instructions provided on kivy.org. But I encountered the same error 3 times at 99%.

### Code and Logs

```python
Collecting kivy.deps.gstreamer
  Downloading kivy.deps.gstreamer-0.1.12-cp27-cp27m-win32.whl (121.0MB)
    99% |############################### | 121.0MB 153kB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Python27\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "C:\Python27\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Python27\lib\site-packages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "C:\Python27\lib\site-packages\pip\download.py", line 571, in written_chunks
    for chunk in chunks:
  File "C:\Python27\lib\site-packages\pip\utils\ui.py", line 139, in iter
    for x in it:
  File "C:\Python27\lib\site-packages\pip\download.py", line 560, in resp_read
    decode_content=False):
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 314, in read
    data = self._fp.read(amt)
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 63, in read
    self._close()
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError
```

**Comment by KeyWeeUsr** [comment]
Try with `--no-cache-dir`. IIRC, Gstreamer is too big for the PIP cache, therefore it results in this error, however the installation works just fine if not put to the cache. If it works for you, feel free to open a pull request with the change in the installation docs :)

**Comment by zzj0402** [comment]
Yep it worked. Thank you KeyWeeUsr
