### ISSUE TITLE
Touchring can cause deadlock on RPi with touchscreen

### ISSUE THREAD

**Issue by kubked** [kivy/kivy#5512]
### Versions

* Python: 2.7.9
* OS: Kivy Pie 1.0
* Kivy: 1.10.0
* Kivy installation method: already installed

### Description

I was developing GUI app for Raspberry Pi with Waveshare 10.1inch HDMI touchscreen. I've made few (3 to 5) background threads calling Clock.schedule_once about once per second each.
App was hanging unexpectedly on one of three Raspberry Pi I used. It was the only rpi which had touchring enabled. Touchring deactivation solved a problem.

I've checked whole code to make sure all threads call schedule_once and run kivy related code only in main thread.

### Code and Logs

App hangs so there wasn't anything usefull in kivy logs. I've created callstack snapshots:

```
#28 Frame 0x6d6ee850, for file /usr/local/lib/python2.7/dist-packages/kivy/clock.py, line 581, in tick (self=<ClockBase(_duration_count=27, _events_duration=<float at remote 0x1677e68>, _rfps_counter=27, _rfps=79, _start_tick=<float at remote 0x1421408>, _duration_ts0=<float at remote 0x1b6e890>, _sleep_obj=None, _sleep_time=<float at remote 0x1b35150>, _frames_displayed=295138, _fps_counter=27, _fps=<float at remote 0x1bb0bd0>, _frames=295139, _last_fps_tick=<float at remote 0x1b6e890>, _dt=<float at remote 0x1bd0a38>) at remote 0x767c2308>, ts=<float at remote 0x1b598a8>, current=<float at remote 0x1a68238>, t_tot=<float at remote 0x1b6e960>)
    self._process_events()
#31 Frame 0x6c8f8bb0, for file /usr/local/lib/python2.7/dist-packages/kivy/base.py, line 339, in idle (self=<EventLoopBase(status='started', quit=False, me_list=[], window=<WindowEglRpi(_context=<Context(sandbox=None) at remote 0x767dadd8>, egl_info=(<kivy.lib.vidcore_lite.egl.Display at remote 0x74b45bc0>, <kivy.lib.vidcore_lite.egl.Surface at remote 0x74b45ba0>, <kivy.lib.vidcore_lite.egl.Context at remote 0x74b45bd0>), single_vkeyboard=True, _keyboards={'system': <Keyboard(widget=None, callback=None, window=<...>, target=None) at remote 0x6f042848>}, _vkeyboard_cls=None, _top=0, win=<kivy.lib.vidcore_lite.egl.NativeWindow at remote 0x6f0b54e8>, _is_desktop=True, _cursor=<kivy.graphics.vertex_instructions.Rectangle at remote 0x6d50b3b0>, use_syskeyboard=True, allow_vkeyboard=True, _system_keyboard=<...>, trigger_keyboard_height=<kivy._clock.ClockEvent at remote 0x6f049710>, initialized=True, docked_vkeyboard=True, _left=0, dpi=<float at remote 0x71302c48>, trigger_create_window=<kivy._clock.ClockEvent at remote...(truncated)
    Clock.tick()
#34 Frame 0x6c905a40, for file /usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py, line 85, in _mainloop (self=<WindowEglRpi(_context=<Context(sandbox=None) at remote 0x767dadd8>, egl_info=(<kivy.lib.vidcore_lite.egl.Display at remote 0x74b45bc0>, <kivy.lib.vidcore_lite.egl.Surface at remote 0x74b45ba0>, <kivy.lib.vidcore_lite.egl.Context at remote 0x74b45bd0>), single_vkeyboard=True, _keyboards={'system': <Keyboard(widget=None, callback=None, window=<...>, target=None) at remote 0x6f042848>}, _vkeyboard_cls=None, _top=0, win=<kivy.lib.vidcore_lite.egl.NativeWindow at remote 0x6f0b54e8>, _is_desktop=True, _cursor=<kivy.graphics.vertex_instructions.Rectangle at remote 0x6d50b3b0>, use_syskeyboard=True, allow_vkeyboard=True, _system_keyboard=<...>, trigger_keyboard_height=<kivy._clock.ClockEvent at remote 0x6f049710>, initialized=True, docked_vkeyboard=True, _left=0, dpi=<float at remote 0x71302c48>, trigger_create_window=<kivy._clock.ClockEvent at remote 0x6f0496b8>) at remote 0x6f0422d0>)
    EventLoop.idle()
#37 Frame 0x6c8f8d20, for file /usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py, line 90, in mainloop (self=<WindowEglRpi(_context=<Context(sandbox=None) at remote 0x767dadd8>, egl_info=(<kivy.lib.vidcore_lite.egl.Display at remote 0x74b45bc0>, <kivy.lib.vidcore_lite.egl.Surface at remote 0x74b45ba0>, <kivy.lib.vidcore_lite.egl.Context at remote 0x74b45bd0>), single_vkeyboard=True, _keyboards={'system': <Keyboard(widget=None, callback=None, window=<...>, target=None) at remote 0x6f042848>}, _vkeyboard_cls=None, _top=0, win=<kivy.lib.vidcore_lite.egl.NativeWindow at remote 0x6f0b54e8>, _is_desktop=True, _cursor=<kivy.graphics.vertex_instructions.Rectangle at remote 0x6d50b3b0>, use_syskeyboard=True, allow_vkeyboard=True, _system_keyboard=<...>, trigger_keyboard_height=<kivy._clock.ClockEvent at remote 0x6f049710>, initialized=True, docked_vkeyboard=True, _left=0, dpi=<float at remote 0x71302c48>, trigger_create_window=<kivy._clock.ClockEvent at remote 0x6f0496b8>) at remote 0x6f0422d0>)
    self._mainloop()
#40 Frame 0x6f07d4e0, for file /usr/local/lib/python2.7/dist-packages/kivy/base.py, line 504, in runTouchApp (widget=None, slave=False, MotionEventFactory=<classobj at remote 0x6c930ca8>, kivy_postproc_modules={'doubletap': <InputPostprocDoubleTap(double_tap_distance=<float at remote 0x19aa440>, double_tap_time=<float at remote 0x19aa430>, touches={}) at remote 0x6c93c410>, 'retaintouch': <InputPostprocRetainTouch(distance=<float at remote 0x19aa450>, _available=[], _links={}, timeout=<float at remote 0x19aa460>) at remote 0x6c93c2b0>, 'ignorelist': <InputPostprocIgnoreList(ignore_list=[]) at remote 0x6c93c350>, 'calibration': <InputPostprocCalibration(frame=0, devices={}) at remote 0x6c93c2f0>, 'dejitter': <InputPostprocDejitter(ignore_devices=[u'mouse', u'mactouch', u''], last_touches={}, jitterdist=<float at remote 0x19aa400>) at remote 0x6c93c370>, 'tripletap': <InputPostprocTripleTap(touches={}, triple_tap_distance=<float at remote 0x19aa420>, triple_tap_time=<float at remote 0x19aa410>) at remote 0x6c93c430...(truncated)
    EventLoop.window.mainloop()
#44 Frame 0x709a2030, for file /usr/local/lib/python2.7/dist-packages/kivy/app.py, line 828, in run (self=<MainApp(_app_window=<WindowEglRpi(_context=<Context(sandbox=None) at remote 0x767dadd8>, egl_info=(<kivy.lib.vidcore_lite.egl.Display at remote 0x74b45bc0>, <kivy.lib.vidcore_lite.egl.Surface at remote 0x74b45ba0>, <kivy.lib.vidcore_lite.egl.Context at remote 0x74b45bd0>), single_vkeyboard=True, _keyboards={'system': <Keyboard(widget=None, callback=None, window=<...>, target=None) at remote 0x6f042848>}, _vkeyboard_cls=None, _top=0, win=<kivy.lib.vidcore_lite.egl.NativeWindow at remote 0x6f0b54e8>, _is_desktop=True, _cursor=<kivy.graphics.vertex_instructions.Rectangle at remote 0x6d50b3b0>, use_syskeyboard=True, allow_vkeyboard=True, _system_keyboard=<...>, trigger_keyboard_height=<kivy._clock.ClockEvent at remote 0x6f049710>, initialized=True, docked_vkeyboard=True, _left=0, dpi=<float at remote 0x71302c48>, trigger_create_window=<kivy._clock.ClockEvent at remote 0x6f0496b8>) at remote 0x6f0422d0>, built=Fa...(truncated)
    runTouchApp()
#47 Frame 0x76c652f0, for file /XXX/main.py, line 40, in <module> ()
    MainApp().run()
```

C-code stack from 28 frame:
```
#0  0x76effa40 in do_futex_wait (isem=isem@entry=0x1427180) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
#1  0x76effaf4 in __new_sem_wait (sem=sem@entry=0x1427180) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:69
#2  0x00152004 in PyThread_acquire_lock (waitflag=1, lock=0x1427180) at ../Python/thread_pthread.h:324
#3  lock_PyThread_acquire_lock.lto_priv.2554 (self=0x76ce7370, args=<optimized out>) at ../Modules/threadmodule.c:52
#4  0x76658b10 in __Pyx_PyObject_Call (kw=0x0, arg=<optimized out>, func=<optimized out>) at /tmp/pip-gDUvyK-build/kivy/_clock.c:13824
#5  __Pyx_PyObject_CallNoArg (func=<optimized out>) at /tmp/pip-gDUvyK-build/kivy/_clock.c:13895
#6  __pyx_pf_4kivy_6_clock_10ClockEvent_2__call__ (__pyx_v_largs=(), __pyx_v_self=0x6f0876b8) at /tmp/pip-gDUvyK-build/kivy/_clock.c:1741
#7  __pyx_pw_4kivy_6_clock_10ClockEvent_3__call__ (__pyx_v_self=<kivy._clock.ClockEvent at remote 0x6f0876b8>, __pyx_args=(), __pyx_kwds=<optimized out>) at /tmp/pip-gDUvyK-build/kivy/_clock.c:1696
#8  0x7516510c in __Pyx_PyObject_Call (kw=0x0, arg=<optimized out>, func=<kivy._clock.ClockEvent at remote 0x6f0876b8>) at /tmp/pip-gDUvyK-build/kivy/graphics/context.c:11031
#9  __Pyx_PyObject_CallNoArg (func=<kivy._clock.ClockEvent at remote 0x6f0876b8>) at /tmp/pip-gDUvyK-build/kivy/graphics/context.c:11102
#10 __pyx_f_4kivy_8graphics_7context_7Context_dealloc_vertexbatch (__pyx_v_self=<optimized out>, __pyx_v_batch=<optimized out>) at /tmp/pip-gDUvyK-build/kivy/graphics/context.c:4855
#11 0x752b8f50 in __pyx_pf_4kivy_8graphics_3vbo_11VertexBatch_2__dealloc__ (__pyx_v_self=0x66ebd348) at /tmp/pip-gDUvyK-build/kivy/graphics/vbo.c:5113
#12 __pyx_pw_4kivy_8graphics_3vbo_11VertexBatch_3__dealloc__ (__pyx_v_self=<kivy.graphics.vbo.VertexBatch at remote 0x66ebd348>) at /tmp/pip-gDUvyK-build/kivy/graphics/vbo.c:5090
#13 __pyx_tp_dealloc_4kivy_8graphics_3vbo_VertexBatch (o=<kivy.graphics.vbo.VertexBatch at remote 0x66ebd348>) at /tmp/pip-gDUvyK-build/kivy/graphics/vbo.c:6406
#14 0x7532d2f8 in __pyx_tp_dealloc_4kivy_8graphics_12instructions_VertexInstruction (o=<kivy.graphics.vertex_instructions.Rectangle at remote 0x66ecf110>)
    at /tmp/pip-gDUvyK-build/kivy/graphics/instructions.c:15121
#15 0x0006fd38 in dict_dealloc.lto_priv.330 (mp=0x66ef3458) at ../Objects/dictobject.c:1010
#16 0x000d15d4 in subtype_dealloc.lto_priv.1435 (self=<EnhancedDictionary at remote 0x66ef3458>) at ../Objects/typeobject.c:1030
#17 0x0006fd38 in dict_dealloc.lto_priv.330 (mp=0x6c807660) at ../Objects/dictobject.c:1010
#18 0x000d1440 in subtype_dealloc.lto_priv.1435 (
    self=<MTDMotionEvent(osy=<float at remote 0x1bb0bf0>, osx=<float at remote 0x1b84078>, osz=<float at remote 0x1885398>, uid=111, push_attrs=('x', 'y', 'z', 'dx', 'dy', 'dz', 'ox', 'oy', 'oz', 'px', 'py', 'pz', 'pos'), double_tap_time=0, pos=('begin', <MTDMotionEvent(osy=<float at remote 0x18b1440>, osx=<float at remote 0x1bd7b68>, osz=<float at remote 0x1885398>, uid=113, push_attrs=(...), double_tap_time=0, pos=(<float at remote 0x19aa4d0>, <float at remote 0x16cc3a0>), is_touch=True, shape=None, grab_exclusive_class=None, grab_current=None, id=110, push_attrs_stack=[], dsz=<float at remote 0x1b6e790>, dsx=<float at remote 0x1b6e990>, dsy=<float at remote 0x1adf030>, pz=<float at remote 0x1885398>, px=<float at remote 0x1885398>, py=<float at remote 0x1885398>, is_triple_tap=False, triple_tap_time=0, is_double_tap=False, profile=['pos', 'pressure'], grab_list=[], grab_state=False, time_end=<float at remote 0x1612380>, psz=<float at remote 0x1885398>, pressure=<float at remote 0x19d3c40>, psx=<float at remote 0x1b...(truncated)) at ../Objects/typeobject.c:1015
#19 0x0006fb78 in tupledealloc.lto_priv.393 (op=0x6c7c4950) at ../Objects/tupleobject.c:222
#20 0x0012f68c in partial_dealloc (pto=0x66e56090) at ../Modules/_functoolsmodule.c:159
#21 0x0006fd38 in dict_dealloc.lto_priv.330 (mp=0x66ef9030) at ../Objects/dictobject.c:1010
#22 0x000d1440 in subtype_dealloc.lto_priv.1435 (self=<WeakMethod(_func=<functools.partial at remote 0x66e56090>, _obj=None, _class=None) at remote 0x6c901dd0>) at ../Objects/typeobject.c:1015
#23 0x7663f130 in __pyx_tp_dealloc_4kivy_6_clock_ClockEvent (o=<kivy._clock.ClockEvent at remote 0x66ee11e8>) at /tmp/pip-gDUvyK-build/kivy/_clock.c:12416
#24 0x7664a42c in __pyx_f_4kivy_6_clock_11CyClockBase__process_events (__pyx_v_self=0x767c2308, __pyx_skip_dispatch=__pyx_skip_dispatch@entry=1) at /tmp/pip-gDUvyK-build/kivy/_clock.c:7313
#25 0x7664b118 in __pyx_pf_4kivy_6_clock_11CyClockBase_18_process_events (__pyx_v_self=<optimized out>) at /tmp/pip-gDUvyK-build/kivy/_clock.c:7410
#26 __pyx_pw_4kivy_6_clock_11CyClockBase_19_process_events (__pyx_v_self=<optimized out>, unused=<optimized out>) at /tmp/pip-gDUvyK-build/kivy/_clock.c:7394
#27 0x00083db0 in call_function (oparg=<optimized out>, pp_stack=0x7eb115d0) at ../Python/ceval.c:4017
#28 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x6d6ee850, for file /usr/local/lib/python2.7/dist-packages/kivy/clock.py, line 581, in tick (self=<ClockBase(_duration_count=27, _events_duration=<float at remote 0x1677e68>, _rfps_counter=27, _rfps=79, _start_tick=<float at remote 0x1421408>, _duration_ts0=<float at remote 0x1b6e890>, _sleep_obj=None, _sleep_time=<float at remote 0x1b35150>, _frames_displayed=295138, _fps_counter=27, _fps=<float at remote 0x1bb0bd0>, _frames=295139, _last_fps_tick=<float at remote 0x1b6e890>, _dt=<float at remote 0x1bd0a38>) at remote 0x767c2308>, ts=<float at remote 0x1b598a8>, current=<float at remote 0x1a68238>, t_tot=<float at remote 0x1b6e960>), throwflag=throwflag@entry=0) at ../Python/ceval.c:2679
```

Cythonized interesting frames:
```
#6  _clock.c:1741 *         self.clock._lock_acquire()             # <<<<<<<<<<<<<<
#24 _clock.c:7313     /* "kivy/_clock.pyx":400
 *             else:
 *                 self._lock_acquire()
 *             event = self._next_event             # <<<<<<<<<<<<<<
 *
 *         self._next_event = self._cap_event = None
 */

```

Please notice, that self.clock._lock is already acquired (line before by same thread). When next_event is assigned to event the last reference to event is lost and ClockEvent is called to dealloc. It causes VertexBatch to dealloc and it calls self.trigger_gl_dealloc (kivy/graphics/context.pyx:92), which is defined as:
```
self.trigger_gl_dealloc = Clock.create_trigger(self.gl_dealloc, 0)
```
Clock.create_trigger creates new ClockEvent. It needs to acquire clock._lock (frame 6) which was already acquired by this thread which creates deadlock.

**Comment by Julian-O** [comment]
Closing because #8434 makes it obsolete.
