### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by CodeMouse92** [kivy/kivy#5529]
### Versions

* Python: Python 3.6.3
* OS: Ubuntu 17.10
* Kivy: 1.10.0 (`1.10.0-0~stable0+201708191146~pkg175~ubuntu17.10.1`)
* Kivy installation method: Stable PPA

NOTE: Cannot install via `pip`, separate issue.

### Description

I've got a Kivy project that worked fine on 16.04 and 17.04, but now that I'm on 17.10, I get the following error:

```
[INFO   ] [Logger      ] Record log in /home/jason/.kivy/logs/kivy_17-12-11_5.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
 Traceback (most recent call last):
   File "./omission.py", line 6, in <module>
     from omission import run
   File "/home/jason/Code/Repositories/omission/omission/run.py", line 5, in <module>
     from omission.interface.window import OmissionApp
   File "/home/jason/Code/Repositories/omission/omission/interface/window.py", line 13, in <module>
     from kivy.app import App
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 30, in <module>
     from kivy.event import EventDispatcher
   File "/usr/lib/python3/dist-packages/kivy/event.py", line 8, in <module>
     import kivy._event
 ImportError: /usr/lib/python3/dist-packages/kivy/_event.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

### Code and Logs

```python
"""
User Interface [Omission]
"""

# This is needed to force use of SDL2 for audio, needed for Windows and
# for Snapcraft.
import os
os.environ['KIVY_AUDIO'] = 'sdl2'

#pylint: disable=C0413

import kivy
from kivy.app import App
from kivy.config import Config
from kivy.core.window import Window
from kivy.uix.floatlayout import FloatLayout

from omission.data.data_loader import DataLoader
from omission.interface.credits import Credits
from omission.interface.game import Gameplay
from omission.interface.highscore import Highscore
from omission.interface.menu import Menu
from omission.interface.popup import PopupLabel
from omission.interface.rules import Rules

# We need this imported, just to ensure it is seen by the .kv file
# pylint: disable=W0401,W0614
from omission.interface.decorative_widgets import *

kivy.require('1.10.0')

class OmissionWindow(FloatLayout):
    """
    Parent class for the app. Most of the callback functions needed by the
    application will need to go here, so they can be accessed by any
    Kivy widget via `root.whatever()`
    """

    def __init__(self, **kwargs):
        """
        Initialize a new OmissionWindow.
        """
        super().__init__(**kwargs)

        self.show_menu()
        #self.show_highscore("", 0)

# More code.....
```

**Comment by bionoid** [comment]
Does `import fpectl` work on the older distros, but not on 17.10? It may be  a discrepancy with `--with-fpectl` cpython build flag, which afaic is required to export the `PyFPE_jbuf` symbol. Not sure about the details though.

**Comment by tito** [comment]
Duplicated of #5453
