### ISSUE TITLE
Kivy not working on ubuntu with python3.6 (anaconda)

### ISSUE THREAD

**Issue by bauripalash** [kivy/kivy#5549]
### Versions

* Python: 3.6.2
* OS: Ubuntu 17.04 (32bit)
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

I'm new to kivy and trying to run following code on my system but its giving me below mentioned error

### Code and Logs

```python
import kivy
kivy.require('1.10.0')
from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()

```
After Running the abovr code , i got that >

```
palash@ash:~/Desktop$ py ska.py
[INFO   ] [Logger      ] Record log in /home/palash/.kivy/logs/kivy_17-12-25_16.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 |Anaconda custom (32-bit)| (default, Jul 20 2017, 13:51:33) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
```
I've install pygame , build-essential,git, ffmpeg, libsdl2-dev, libsdl2-image-dev, libsdl2-mixer-dev, libsdl2-ttf-dev, libportmidi-dev, libswscale-dev, libavformat-dev, libavcodec-dev ,zlib1g-dev

**Comment by pkemarco** [comment]
Restart installation, and see the website's orientations

2017-12-25 6:42 GMT+01:00 welcome[bot] <notifications@github.com>:

**Comment by bauripalash** [comment]
after reinstalling i'm getting this error >

```bash
[INFO   ] [Logger      ] Record log in /home/palash/.kivy/logs/kivy_17-12-26_6.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 |Anaconda custom (32-bit)| (default, Jul 20 2017, 13:51:33) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - ImportError: /home/palash/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/i386-linux-gnu/libmodplug.so.1)
  File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/utils.py", line 496, in __get__
     retval = self.func(inst)
   File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/metrics.py", line 174, in dpi
     EventLoop.ensure_window()
   File "/home/palash/anaconda3/lib/python3.6/site-packages/kivy/base.py", line 127, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by pkemarco** [comment]
Install dependencies :

sudo apt-get install -y \
    python-pip \
    build-essential \
    mercurial \
    git \
    python \
    python-dev \
    ffmpeg \
    libsdl-image1.2-dev \
    libsdl-mixer1.2-dev \
    libsdl-ttf2.0-dev \
    libsmpeg-dev \
    libsdl1.2-dev \
    libportmidi-dev \
    libswscale-dev \
    libavformat-dev \
    libavcodec-dev \
    zlib1g-dev


2017-12-26 9:22 GMT+01:00 Palash Bauri <notifications@github.com>:

**Comment by pkemarco** [comment]
sudo apt-get install -y \
    libgstreamer1.0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good


2017-12-26 10:05 GMT+01:00 Erickson PASSY <passyerickson@gmail.com>:

**Comment by bauripalash** [comment]
I installed all the dependencides ehich are above mentioned but still getting this error

```bash
[INFO   ] [Logger      ] Record log in /home/palash/.kivy/logs/kivy_17-12-26_12.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 |Anaconda custom (32-bit)| (default, Jul 20 2017, 13:51:33) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
```

**Comment by kuzeyron** [comment]
@bauripalash Have a look at this if it can solve your case: [kivy not working with ..](https://github.com/kivy/kivy/issues/4656)

**Comment by bauripalash** [comment]
@kuzeyron  I tried to install from github repository and but still getting this error >

```bash
[INFO   ] [Logger      ] Record log in /home/palash/.kivy/logs/kivy_17-12-26_17.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-4c6f7be, 20171226
[INFO   ] [Python      ] v3.6.2 |Anaconda custom (32-bit)| (default, Jul 20 2017, 13:51:33) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/palash/Desktop/kivy/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/palash/Desktop/kivy/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - ImportError: /home/palash/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/i386-linux-gnu/libmodplug.so.1)
  File "/home/palash/Desktop/kivy/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/palash/Desktop/kivy/kivy/core/window/window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/palash/Desktop/kivy/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by kuzeyron** [comment]
@bauripalash  It looks to me that SDL2 is failing for you. Another link you could walk through: [Can't install libsdl2-dev:i386 on Ubuntu 17.04 64 ..](https://askubuntu.com/questions/967951/cant-install-libsdl2-devi386-on-ubuntu-17-04-64-bit-alongside-libsdl2-devamd6)

Just because you are using 32-Bits system I believe it can be more difficult to make it run. But the link can solve it for you (as I'm hoping for).

**Comment by bauripalash** [comment]
i tried this and got this>
```bash
$ sudo apt install libsdl2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsdl2-dev is already the newest version (2.0.5+dfsg1-2ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
```

i will not try to use kivy on my current machine for now, until I buy new computer

**Comment by XD-Coffin** [comment]
Just change the graphics settings to intel graphics.

**Comment by steve3p0** [comment]
> Just change the graphics settings to intel graphics.

Where do I change this?  I want to avoid setting this at the system os level.
