### ISSUE TITLE
CTRL-C in a textinput crashes the app

### ISSUE THREAD

**Issue by HellnoRO** [kivy/kivy#5569]
### Versions

* Python: 3.6.3
* OS: Windows 10
* Kivy: 1.10.0
* Kivy installation method: using pip, followed the steps shown in the guide

### Description

Trying to use CTRL-C to copy text from a textinput, and the program crashes.

### Code and Logs

```python
import kivy
from kivy.uix.textinput import TextInput
from kivy.app import App

class program(App):
    def build(self):
        return TextInput()

prog = program()
prog.run()


Traceback (most recent call last):
   File "E:/pycharm/MethasiaChatSurelyUnstable/vladegay.py", line 12, in <module>
     prog.run()
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
     self._mainloop()
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 602, in _mainloop
     self.modifiers):
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
   File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
   File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\window\__init__.py", line 159, in _on_window_key_down
     return self.dispatch('on_key_down', keycode, text, modifiers)
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
   File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
   File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\textinput.py", line 2404, in keyboard_on_key_down
     self.copy()
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\textinput.py", line 1712, in copy
     return Clipboard.copy(self.selection_text)
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\clipboard\__init__.py", line 73, in copy
     self._copy(data)
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\clipboard\__init__.py", line 87, in _copy
     self.put(data, self._clip_mime_type)
   File "C:\Users\hellNo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\clipboard\clipboard_winctypes.py", line 55, in put
     msvcrt.wcscpy_s(c_wchar_p(hCd), len(text), c_wchar_p(text))
 ValueError: embedded null character

```

**Comment by KeyWeeUsr** [comment]
Most likely related to our ctypes clipboard error on Py 3.6 Appveyor tests.

**Comment by jrball3** [comment]
I am running into this issue as well - Any timeframe on a fix?

**Comment by pkemarco** [comment]
Up
