### ISSUE TITLE
Can not play wav sound on MacOS 10.11.6, Python 3.6, Kivy 1.10.0

### ISSUE THREAD

**Issue by yhcharles** [kivy/kivy#5582]
### Versions

* Python: v3.6.2 |Anaconda custom (64-bit)| 
* OS: MacOS 10.11.6
* Kivy: v1.10.0
* Kivy installation method: pip

### Description

1. can not play audio, shows `Unable to create a playbin`
2. I searched and followed [issue 2381](https://github.com/kivy/kivy/issues/2381), tried `brew install gst-plugins-bad`
3. no exceptions now, but still can not hear any sound played

### Code and Logs

code:
```python
from kivy.core.audio import SoundLoader
s = SoundLoader.load('test.wav')
s.play()
```

logs:
```
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 |Anaconda custom (64-bit)| (default, Sep 21 2017, 18:29:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.14.74'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 6100'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [AudioGstplayer] Using Gstreamer 1.12.4.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer, audio_avplayer ignored)

(process:93177): GLib-GObject-WARNING **: gsignal.c:2523: signal 'sync-message' is invalid for instance '0x7fc8fa9c2940' of type '(null)'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'video-sink'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'async-handling'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'uri'

(process:93177): GLib-GObject-WARNING **: gsignal.c:2523: signal 'sync-message' is invalid for instance '0x7fc8fa9c2d50' of type '(null)'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'video-sink'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'async-handling'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'uri'

(process:93177): GLib-GObject-WARNING **: gsignal.c:2523: signal 'sync-message' is invalid for instance '0x7fc8fa081140' of type '(null)'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'video-sink'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'async-handling'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'uri'
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'volume'

(process:93177): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:93177): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:93177): GLib-GObject-WARNING **: g_object_set_valist: object class '(null)' has no property named 'volume'
[INFO   ] [Base        ] Leaving application in progress...
```

**Comment by upgle** [comment]
I'm facing the same issue

**Comment by dwaynewei** [comment]
@upgle  hey bro, sorry I don't know how to solve this issue. and I was wondering if you could tell that how did u installed the kivy 1.10.0 on macOS 10.11.6?  my macOS version is also 10.11.6 but I cannot install kivy 1.10.0 completely, it give back this error, 

[
Noogler@Calypso:~% kivy3
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Applications/Kivy3.app/Contents/Resources/python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /Applications/Kivy3.app/Contents/Resources/python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

[1]    1595 trace trap  kivy3
]

have you met this error before?  cause I googled it for several days and couldn't get it solved.  
In another way I installed kivy1.9 on my macOS 10.11.6 and it goes well except for one broblem that when I run "kivy", it is using python2, however I want to use python3 just like you. 
much appreciate!!

**Comment by HeaTTheatR** [comment]
I confirm - on MacOS 10.14, Python 3 and Kivy 1.10.1 audio playback does not work.

```python
from kivy.core.audio import SoundLoader

sound = SoundLoader.load('Why.mp3')
if sound:
    print("Sound found at %s" % sound.source)
    print("Sound is %.3f seconds" % sound.length)
    sound.play()
```

Result:

```python
 Traceback (most recent call last):
   File "/Users/macbookair/Projects/KivyMD/demos/kitchen_sink/main.py", line 16, in <module>
     sound = SoundLoader.load('Why.mp3')
   File "/Users/macbookair/Opt/Kivy3/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivy/core/audio/__init__.py", line 86, in load
     return classobj(source=filename)
   File "/Users/macbookair/Opt/Kivy3/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivy/core/audio/audio_gstplayer.py", line 45, in __init__
     super(SoundGstplayer, self).__init__(**kwargs)
   File "kivy/_event.pyx", line 262, in kivy._event.EventDispatcher.__init__
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/Users/macbookair/Opt/Kivy3/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivy/core/audio/__init__.py", line 174, in on_source
     self.load()
   File "/Users/macbookair/Opt/Kivy3/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivy/core/audio/audio_gstplayer.py", line 62, in load
     self.player.load()
   File "kivy/lib/gstplayer/_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load
 kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin
```

Tried brew install gst-plugins-bad - result is the same

**Comment by matham** [comment]
@HeaTTheatR Your issue is different. Please open a new issue specific to your issue, or better, ask on the support channels.

**Comment by goodboyyyy** [comment]
same problem 
` Traceback (most recent call last):
   File "mediaMain.py", line 199, in <module>
     DropApp().run()
   File "/anaconda3/lib/python3.6/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/anaconda3/lib/python3.6/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/anaconda3/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/anaconda3/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/anaconda3/lib/python3.6/site-packages/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/anaconda3/lib/python3.6/site-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/anaconda3/lib/python3.6/site-packages/kivy/uix/video.py", line 183, in _do_video_load
     self._video = CoreVideo(filename=filename, **self.options)
   File "/anaconda3/lib/python3.6/site-packages/kivy/core/video/video_gstplayer.py", line 56, in __init__
     super(VideoGstplayer, self).__init__(**kwargs)
   File "/anaconda3/lib/python3.6/site-packages/kivy/core/video/__init__.py", line 84, in __init__
     self.filename = kwargs.get('filename')
   File "/anaconda3/lib/python3.6/site-packages/kivy/core/video/__init__.py", line 116, in <lambda>
     lambda self, x: self._set_filename(x),
   File "/anaconda3/lib/python3.6/site-packages/kivy/core/video/__init__.py", line 113, in _set_filename
     self.load()
   File "/anaconda3/lib/python3.6/site-packages/kivy/core/video/video_gstplayer.py", line 68, in load
     self.player.load()
   File "kivy/lib/gstplayer/_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load
 kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin
`

**Comment by matham** [comment]
This error `unable to create playbin error` is fixed by setting `GST_REGISTRY` to `~/registry.bin`. https://github.com/kivy/kivy/pull/6270
