### ISSUE TITLE
Error running app with rst and python3 NameError: name 'StandardError' is not defined

### ISSUE THREAD

**Issue by apolinux** [kivy/kivy#5594]
### Versions

* Python: 3.5
* OS: Android
* Kivy:  1.10.0
* Kivy installation method:  pip

### Description
I have created an app with kivy and is deployed and runs OK in android. After I added rst module, troubles came. I got an error that docutils not found. After that I included in .spec and this error I got:

2-01 11:26:08.368 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/docutils/__init__.py", line 112, in <module>
02-01 11:26:08.369 20514 20630 I python  :      class ApplicationError(StandardError):
02-01 11:26:08.370 20514 20630 I python  :  NameError: name 'StandardError' is not defined

### Code and Logs
a piece of code in kv including rst:
```python
TabbedPanelItem:
                text:_('Help')
                BoxLayout:
                    orientation:'vertical'
                    RstDocument:
                        text:_('_Help_')
                        on_touch_down:self.collide_point(*args[1].pos)
                        #and root.on_click()
                    Button:
                        size_hint_y:0.1
                        text:_('OK')
                        on_touch_down:self.collide_point(*args[1].pos) and root.on_click()
```

This is the full log:
```python
02-01 11:26:08.266 20514 20630 I python  :  Traceback (most recent call last):
02-01 11:26:08.266 20514 20630 I python  :    File "main.py", line 4, in <module>
02-01 11:26:08.267 20514 20630 I python  :      ShisenshoApp().run()
02-01 11:26:08.268 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/app.py", line 828, in run
02-01 11:26:08.273 20514 20630 I python  :      runTouchApp()
02-01 11:26:08.274 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/base.py", line 504, in runTouchApp
02-01 11:26:08.277 20514 20630 I python  :      EventLoop.window.mainloop()
02-01 11:26:08.277 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
02-01 11:26:08.282 20514 20630 I python  :      self._mainloop()
02-01 11:26:08.283 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
02-01 11:26:08.285 20514 20630 I python  :      EventLoop.idle()
02-01 11:26:08.286 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/base.py", line 342, in idle
02-01 11:26:08.288 20514 20630 I python  :      self.dispatch_input()
02-01 11:26:08.288 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/base.py", line 327, in dispatch_input
02-01 11:26:08.290 20514 20630 I python  :      post_dispatch_input(*pop(0))
02-01 11:26:08.291 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/base.py", line 233, in post_dispatch_input
02-01 11:26:08.292 20514 20630 I python  :      listener.dispatch('on_motion', etype, me)
02-01 11:26:08.292 20514 20630 I python  :    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7807)
02-01 11:26:08.293 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/core/window/__init__.py", line 1188, in on_motion
02-01 11:26:08.298 20514 20630 I python  :      self.dispatch('on_touch_down', me)
02-01 11:26:08.299 20514 20630 I python  :    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7807)
02-01 11:26:08.302 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/core/window/__init__.py", line 1204, in on_touch_down
02-01 11:26:08.306 20514 20630 I python  :      if w.dispatch('on_touch_down', touch):
02-01 11:26:08.306 20514 20630 I python  :    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7807)
02-01 11:26:08.307 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/widget.py", line 457, in on_touch_down
02-01 11:26:08.311 20514 20630 I python  :      if child.dispatch('on_touch_down', touch):
02-01 11:26:08.311 20514 20630 I python  :    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7807)
02-01 11:26:08.312 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/widget.py", line 457, in on_touch_down
02-01 11:26:08.315 20514 20630 I python  :      if child.dispatch('on_touch_down', touch):
02-01 11:26:08.315 20514 20630 I python  :    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7807)
02-01 11:26:08.316 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/widget.py", line 457, in on_touch_down
02-01 11:26:08.319 20514 20630 I python  :      if child.dispatch('on_touch_down', touch):
02-01 11:26:08.319 20514 20630 I python  :    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7807)
02-01 11:26:08.320 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
02-01 11:26:08.322 20514 20630 I python  :      self.dispatch('on_press')
02-01 11:26:08.323 20514 20630 I python  :    File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7762)
02-01 11:26:08.324 20514 20630 I python  :    File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:13521)
02-01 11:26:08.325 20514 20630 I python  :    File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy/_event.c:12356)
02-01 11:26:08.326 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 64, in custom_callback
02-01 11:26:08.329 20514 20630 I python  :      exec(__kvlang__.co_value, idmap)
02-01 11:26:08.329 20514 20630 I python  :    File "/data/data/org.percasoft.shisensho/files/app/shisensho/shisensho.kv", line 318, in <module>
02-01 11:26:08.332 20514 20630 I python  :      on_press : Gameboard.about()
02-01 11:26:08.333 20514 20630 I python  :    File "./shisensho/gameboard.py", line 437, in about
02-01 11:26:08.336 20514 20630 I python  :      view = ModalAbout(auto_dismiss=False)
02-01 11:26:08.336 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/modalview.py", line 152, in __init__
02-01 11:26:08.339 20514 20630 I python  :      super(ModalView, self).__init__(**kwargs)
02-01 11:26:08.339 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/anchorlayout.py", line 68, in __init__
02-01 11:26:08.341 20514 20630 I python  :      super(AnchorLayout, self).__init__(**kwargs)
02-01 11:26:08.342 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/layout.py", line 76, in __init__
02-01 11:26:08.345 20514 20630 I python  :      super(Layout, self).__init__(**kwargs)
02-01 11:26:08.345 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/widget.py", line 345, in __init__
02-01 11:26:08.347 20514 20630 I python  :      Builder.apply(self, ignored_consts=self._kwargs_applied_init)
02-01 11:26:08.348 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 451, in apply
02-01 11:26:08.350 20514 20630 I python  :      self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
02-01 11:26:08.350 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 567, in _apply_rule
02-01 11:26:08.352 20514 20630 I python  :      self._apply_rule(child, crule, rootrule)
02-01 11:26:08.352 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 567, in _apply_rule
02-01 11:26:08.355 20514 20630 I python  :      self._apply_rule(child, crule, rootrule)
02-01 11:26:08.355 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 567, in _apply_rule
02-01 11:26:08.358 20514 20630 I python  :      self._apply_rule(child, crule, rootrule)
02-01 11:26:08.358 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 567, in _apply_rule
02-01 11:26:08.360 20514 20630 I python  :      self._apply_rule(child, crule, rootrule)
02-01 11:26:08.361 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/lang/builder.py", line 526, in _apply_rule
02-01 11:26:08.363 20514 20630 I python  :      cls = Factory_get(cname)
02-01 11:26:08.363 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/factory.py", line 139, in __getattr__
02-01 11:26:08.366 20514 20630 I python  :      module = __import__(name=item['module'], fromlist='.')
02-01 11:26:08.366 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/kivy/uix/rst.py", line 81, in <module>
02-01 11:26:08.367 20514 20630 I python  :      from docutils.parsers import rst
02-01 11:26:08.368 20514 20630 I python  :    File "/data/user/0/org.percasoft.shisensho/files/app/crystax_python/site-packages/docutils/__init__.py", line 112, in <module>
02-01 11:26:08.369 20514 20630 I python  :      class ApplicationError(StandardError):
02-01 11:26:08.370 20514 20630 I python  :  NameError: name 'StandardError' is not defined
02-01 11:26:08.618 20514 20630 I python  : Python for android ended.

```
thanks in advance.

**Comment by tshirtman** [comment]
The error seems to originate in docutils, rather than in kivy code. 

https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/__init__.py#l89

    Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
    [GCC 7.2.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> StandardError 
    <type 'exceptions.StandardError'>
    >>> 

    Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
    [GCC 7.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> StandardError
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'StandardError' is not defined
    >>>

**Comment by apolinux** [comment]
@tshirtman  Would you suggest to try other docutils version?

**Comment by Julian-O** [comment]
[Docutils bug](https://sourceforge.net/p/docutils/bugs/370/), long since fixed. 

Closing as stale and out of scope.
