### ISSUE TITLE
examples/widgets/textalign.py: AttributeError: 'NoneType' object has no attribute 'children'

### ISSUE THREAD

**Issue by drscotthawley** [kivy/kivy#5628]
### Versions

* Python:  3.5.3 (anaconda)
* OS: macOS High Sierra (10.13.3)
* Kivy: 1.10.1.dev0
* Kivy installation method: pip install git+https://github.com/kivy/kivy.git

### Description

I simply try to run the example file:
https://github.com/kivy/kivy/blob/master/examples/widgets/textalign.py

and when I do so, I get  AttributeError: 'NoneType' object has no attribute 'children'

### Code and Logs

```python
$ python textalign.py
[INFO   ] [Logger      ] Record log in /Users/shawley/.kivy/logs/kivy_18-02-20_7.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180201
[INFO   ] [Python      ] v3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.30.14'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 6100'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "textalign.py", line 48, in <module>
     TextAlignApp().run()
   File "/Users/shawley/anaconda/envs/py35/lib/python3.5/site-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "textalign.py", line 44, in build
     self.select(0)
   File "textalign.py", line 19, in select
     for _child in self.selector.grid.children[:]:
 AttributeError: 'NoneType' object has no attribute 'children'
```

**Comment by bionoid** [comment]
Did you copy the `textalign.py` file individually, or do  `pip install kivy-examples` or something else to obtain it? Seems like [textalign.kv](https://github.com/kivy/kivy/blob/master/examples/widgets/textalign.kv) is missing or not loaded for other reasons.

**Comment by drscotthawley** [comment]
@bionoid Oh, very sorry. I did not get the textalign.kv file.  I found the textalign.py example via Google search after finding an e-mail in the Kivy discussion list where someone suggested "check out the textalign example", & I didn't think to look for a .kv file (still new, used to seeing embedded Builder scripts).
I'll close this issue.
