### ISSUE TITLE
UnicodeDecodeError when trying out Kivy's official FileChooser Usage Example

### ISSUE THREAD

**Issue by hanachan1026** [kivy/kivy#5657]
### Versions

* Python: 3.5.3
* OS: MacOS10.13.1
* Kivy: 1.10.0
* Kivy installation method: dmg file

### Description

I tried this https://pyky.github.io/kivy-doc-ja/api-kivy.uix.filechooser.html#usage-example
Executed with ```kivy main.py```

### Code and Logs

```python
main.py
#-*- coding: utf-8 -*-
from kivy.app import App
from kivy.uix.floatlayout import FloatLayout
from kivy.factory import Factory
from kivy.properties import ObjectProperty
from kivy.uix.popup import Popup

import os


class LoadDialog(FloatLayout):
    load = ObjectProperty(None)
    cancel = ObjectProperty(None)


class SaveDialog(FloatLayout):
    save = ObjectProperty(None)
    text_input = ObjectProperty(None)
    cancel = ObjectProperty(None)


class Root(FloatLayout):
    loadfile = ObjectProperty(None)
    savefile = ObjectProperty(None)
    text_input = ObjectProperty(None)

    def dismiss_popup(self):
        self._popup.dismiss()

    def show_load(self):
        content = LoadDialog(load=self.load, cancel=self.dismiss_popup)
        self._popup = Popup(title="Load file", content=content,
                            size_hint=(0.9, 0.9))
        self._popup.open()

    def show_save(self):
        content = SaveDialog(save=self.save, cancel=self.dismiss_popup)
        self._popup = Popup(title="Save file", content=content,
                            size_hint=(0.9, 0.9))
        self._popup.open()

    def load(self, path, filename):
        with open(os.path.join(path, filename[0])) as stream:
            self.text_input.text = stream.read()

        self.dismiss_popup()

    def save(self, path, filename):
        with open(os.path.join(path, filename), 'w') as stream:
            stream.write(self.text_input.text)

        self.dismiss_popup()


class Editor(App):
    pass


Factory.register('Root', cls=Root)
Factory.register('LoadDialog', cls=LoadDialog)
Factory.register('SaveDialog', cls=SaveDialog)


if __name__ == '__main__':
    Editor().run()

```

```editor.kv
editor.kv
Root:
    text_input: text_input

    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: 'Load'
                on_release: root.show_load()
            Button:
                text: 'Save'
                on_release: root.show_save()

        BoxLayout:
            TextInput:
                id: text_input
                text: ''

            RstDocument:
                text: text_input.text
                show_errors: True

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<SaveDialog>:
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            on_selection: text_input.text = self.selection and self.selection[0] or ''

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)

```

```
Traceback (most recent call last):
   File "main.py", line 65, in <module>
     Editor().run()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/app.py", line 828, in run
     runTouchApp()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 663, in mainloop
     self._mainloop()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/base.py", line 342, in idle
     self.dispatch_input()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7681)
   File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
   File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy/_event.c:12356)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/Users/hanayatakuma/tools/kivyTest/editor.kv", line 42, in <module>
     on_release: root.load(filechooser.path, filechooser.selection)
   File "main.py", line 44, in load
     self.text_input.text = stream.read()
   File "/Applications/Kivy.app/Contents/Resources/./venv/bin/../../../Frameworks/python/3.5.0/lib/python3.5/codecs.py", line 321, in decode
     (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by kuzeyron** [comment]
Are you sure that `def load(self, path, filename)` is correct?

**Comment by hanachan1026** [comment]
@kuzeyron I just checked ```print(path)``` and ```print(filename)```
and I noticed filename is full path to my selection file
so I changed my main.py
```python
def load(self, path, filename):
        # print(path)
        print(filename)
        # with open(os.path.join(path, filename[0])) as stream:
        #     self.text_input.text = stream.read()
        with open(filename[0]) as stream:
            self.text_input.text = stream.read()

        self.dismiss_popup()
```

Now it works. Thank you
