### ISSUE TITLE
Buildozer compilation gets stuck

### ISSUE THREAD

**Issue by SoukupMCAT** [kivy/kivy#5666]
### Versions

* Python: 2.7
* OS: Ubuntu 14.2 (virtual env)
* Kivy: 1.9.1

### Description

During the .apk compilation it gets stuck on unpacking kivy. It doesn't crash it just gets completely stuck. I tried to wait for an hour. Can you please help me? I already tried to reinstall buildozer, cython and kivy. It gets stuck on the task below, nothing happens then. 

### Code and Logs

```
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/kivy-pygame-python2/armeabi-v7a


```

**Comment by bionoid** [comment]
1. Upgrade to latest buildozer version, if you haven't already
2. Run `buildozer distclean`, and `rm -fr ~/.buildozer` to start from scratch
3. Uncomment/set `p4a.branch = master` option in your spec file

If that doesn't help, set `log_level = 2` and upload the *complete* build log + buildozer.spec on https://gist.github.com. Then reach out via official support channels, see: https://github.com/kivy/kivy#support

**Comment by SoukupMCAT** [comment]
Thank you very much @bionoid it worked! 
Now I got another problem:

```
[INFO]:    Building sdl for armeabi-v7a
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni
[INFO]:    -> running ndk-build V=1
Should remove twisted tests etc. here, but skipping for now                                    
Exception in thread background thread for pid 27138:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_2: 

  RAN: /home/kivy/.buildozer/android/platform/android-ndk-r9c/ndk-build V=1

  STDOUT:
/home/kivy/beerctrl/src/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni/sdl/Android.mk:8: *** Please define SDL_JAVA_PACKAGE_PATH to the path of your Java package with dots replaced with underscores, for example "com_example_SanAngeles".  Stop.


  STDERR:


[INFO]:    STDOUT:
	/home/kivy/beerctrl/src/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni/sdl/Android.mk:8: *** Please define SDL_JAVA_PACKAGE_PATH to the path of your Java package with dots replaced with underscores, for example "com_example_SanAngeles".  Stop.
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni && /home/kivy/.buildozer/android/platform/android-ndk-r9c/ndk-build V=1

[WARNING]: ERROR: /home/kivy/.buildozer/android/platform/android-ndk-r9c/ndk-build failed!
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=selfserviceapp --bootstrap=sdl2 --requirements=pygame,sqlite3,twisted,android,plyer,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/beerctrl/src/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```
anybody knows, why is this happening during `buildozer android debug` command? I have already updated buildozer, python-for-android and apt-get to latest version.

**Comment by bionoid** [comment]
Try a newer NDK - r16b works for me, r9c may be too old
