### ISSUE TITLE
Strange behavior when sharing a Animation between compound animations(Sequence, Parallel)

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy/kivy#5671]
### Versions

* Python: 3.6.3
* OS: Linux Mint 18.2
* Kivy: master
* Kivy installation method: pip

### Description

When two compound animations(Sequence, Parallel) sharing a Animation, I think the behavior is not corrent. 

#### example1: two Parallels sharing a Animation

```python
from kivy.animation import Animation
from kivy.lang import Builder
from kivy.base import runTouchApp


root = Builder.load_string(r'''
FloatLayout:
    Button:
        id: button1
        size_hint: None, None
        text: 'anim1'
''')
button1 = root.ids.button1
anim_shared = Animation(height=50)
anim1 = anim_shared & Animation(top=600)
anim2 = anim_shared & Animation(y=0)
anim1.bind(
    on_start=lambda *args: print('1: start'),
    on_progress=lambda *args: print('1: progress'),
    on_complete=lambda *args: print('1: complete'),
)
anim2.bind(
    on_start=lambda *args: print('2: start'),
    on_progress=lambda *args: print('2: progress'),
    on_complete=lambda *args: print('2: complete'),
)


def on_button1_press(button):
    anim1.start(button1)


button1.bind(on_press=on_button1_press)

runTouchApp(root)
```

output is:

```
1: start
[INFO] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/tmp/firefox/animation/test.py", line 42, in <module>
     runTouchApp(root)
   File "/tmp/firefox/kivy/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/tmp/firefox/kivy/kivy/core/window/window_sdl2.py", line 723, in mainloop
     self._mainloop()
   File "/tmp/firefox/kivy/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/tmp/firefox/kivy/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/tmp/firefox/kivy/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events (/tmp/firefox/animation/kivy/kivy/_clock.c:7839)
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events (/tmp/firefox/animation/kivy/kivy/_clock.c:7597)
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events (/tmp/firefox/animation/kivy/kivy/_clock.c:7519)
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/tmp/firefox/animation/kivy/kivy/_clock.c:3258)
   File "/tmp/firefox/kivy/kivy/animation.py", line 352, in _update
     self.stop(widget)
   File "/tmp/firefox/kivy/kivy/animation.py", line 217, in stop
     self.dispatch('on_complete', widget)
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (/tmp/firefox/animation/kivy/kivy/_event.c:7681)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (/tmp/firefox/animation/kivy/kivy/_event.c:13524)
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch (/tmp/firefox/animation/kivy/kivy/_event.c:13050)
   File "/tmp/firefox/kivy/kivy/animation.py", line 531, in on_anim_complete
     self._widgets[widget.uid]['complete'] += 1
 KeyError: 9
```

There are no '1: progress' and app crashed when 'anim_shared' completed.

#### example2:  two Sequences sharing a Animation

```python
from kivy.animation import Animation
from kivy.lang import Builder
from kivy.base import runTouchApp


root = Builder.load_string(r'''
FloatLayout:
    Button:
        id: button1
        size_hint: None, None
        text: 'anim1'
''')
button1 = root.ids.button1
anim_shared = Animation(height=50)
anim1 = anim_shared + Animation(top=600)
anim2 = anim_shared + Animation(y=0)
anim1.bind(
    on_start=lambda *args: print('1: start'),
    on_progress=lambda *args: print('1: progress'),
    on_complete=lambda *args: print('1: complete'),
)
anim2.bind(
    on_start=lambda *args: print('2: start'),
    on_progress=lambda *args: print('2: progress'),
    on_complete=lambda *args: print('2: complete'),
)


def on_button1_press(button):
    anim1.start(button1)


button1.bind(on_press=on_button1_press)

runTouchApp(root)
```

output is:

```
2: start
1: start
2: progress
1: progress
2: progress
1: progress
.
.
.
1: progress
1: progress
.
.
.
1: complete
```

I didn't call anim2.start() however '2: start' and '2: progress' are displayed.

### It should be fixed?

I already understand why examples didn't work and can fix example1 easily.
example2 is also fixable, but I 'm not sure thats worth it.

Can someone tell me:
Those should be fixed?
Sharing a Animation is wrong usage in the first place?

**Comment by bionoid** [comment]
> Sharing a Animation is wrong usage in the first place?

It doesn't seem to be *documented* use at least, nor is there a unit test that does this in [tests/tests_animations.py](https://github.com/kivy/kivy/blob/master/kivy/tests/test_animations.py)... so I guess it was not the original developer's intention. 

> Those should be fixed?

It's a nice feature, fixing it seems like a good idea to me, +1! 

Whether the maintainers will accept/merge a patch is a different question of course, I don't know about that. Generally it will be merged if it doesn't break existing functionality :)

**Comment by gottadiveintopython** [comment]
my bad. I didnt notice the test code, and seems like sharing is not correct usage.
But anyways I'll try to fix that.

thanks for your comment :)

**Comment by tshirtman** [comment]
I agree it would be very nice to fix, has been bitten by that myself in the past.

**Comment by gottadiveintopython** [comment]
Thanks

Yes, performance is the most I'm worrying about.

**Comment by gottadiveintopython** [comment]
https://gist.github.com/gottadiveintopython/17b22b1b540f29bc63beb812afff3ca3

sorry I gave up. Not because the code doesn't work, because the code getting really ugly. I think it's not worth it.
