### ISSUE TITLE
Kivy app doesn't start with no connected screen

### ISSUE THREAD

**Issue by omermazig** [kivy/kivy#5689]
### Versions

* Python: 3.6
* OS: Ubuntu 16.04.4 x64
* Kivy: 1.10

### Description
I have a kivy app and I want to set a CI and test it automatically, so I got a DigitalOcean virtual server and I want to run my tests on it. 

The problem is that I believe that there is no screen connected to this virtual machine (and maybe not even an installed x-server), and I get the following error: 

### Code and Logs

```
[INFO   ] [Logger      ] Record log in /home/ci-user/.kivy/logs/kivy_18-04-02_4.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609]
[INFO   ] [AudioGstplayer] Using Gstreamer 1.8.3.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: b'Failed to connect to the Mir Server'
  File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 140, in __init__
    super(WindowSDL, self).__init__()
  File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 899, in __init__
    self.create_window()
  File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 269, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 84, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (/tmp/pip-build-g0kywea3/Kivy/kivy/core/window/_window_sdl2.c:2290)
  File "kivy/core/window/_window_sdl2.pyx", line 57, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (/tmp/pip-build-g0kywea3/Kivy/kivy/core/window/_window_sdl2.c:1872)

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[INFO   ] [Text        ] Provider: sdl2
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip(['clipboard_dbusklipper', 'clipboard_gtk3'] ignored)
[INFO   ] [CutBuffer   ] cut buffer support enabled
[WARNING] [Factory     ] Ignored class "NotificationPopup" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.popups.NotificationPopup'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Popup, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/popups.kv.
[WARNING] [Factory     ] Ignored class "YesNoPopup" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.popups.YesNoPopup'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Popup, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/popups.kv.
[WARNING] [Factory     ] Ignored class "DbDataEntryPopup" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.popups.DbDataEntryPopup'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Popup, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/popups.kv.
[WARNING] [Factory     ] Ignored class "CameraView" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.camera_views.CameraView'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyBoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/camera_views.kv.
[WARNING] [Factory     ] Ignored class "CameraControlButtons" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.camera_views.CameraControlButtons'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyBoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/camera_views.kv.
[WARNING] [Factory     ] Ignored class "TinyLayout" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyLayout'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Layout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyBoxLayout" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyBoxLayout'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyLayout+BoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyGridLayout" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyGridLayout'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyLayout+GridLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinySpinner" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinySpinner'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Spinner, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Button, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyToggleButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyToggleButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+ToggleButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyLabel" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyLabel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Label, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinySquareIconButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinySquareIconButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyToggledSquareIconButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyToggledSquareIconButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinySquareIconButton+ToggleButtonBehavior, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "ImageHasDefectsButton" re-declaration. Current -  module: None, cls: <class 'fixi.screens.ImageHasDefectsButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyToggledSquareIconButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyTextInput" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyTextInput'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+TextInput, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "FieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.FieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyBoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TextFieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TextFieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FieldInputBox, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "IntFieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.IntFieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FieldInputBox, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "ChoiceFieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.ChoiceFieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FieldInputBox, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TurningWidget" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TurningWidget'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Widget, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "InitErrorScreen" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_apps.InitErrorScreen'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: BoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "DataEntryBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.DataEntryBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyBoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "FieldLine" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.FieldLine'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: BoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "FieldChooserButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.FieldChooserButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Button, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "MultiSelectOption" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.MultiSelectOption'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyToggleButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "SingleSelectOption" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.SingleSelectOption'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "StringInput" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.StringInput'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TextInput, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "SearchBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.SearchBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: StringInput, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "DataDisplayLine" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.DataDisplayLine'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyLabel, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/utils.py", line 496, in __get__
     retval = self.func(inst)
   File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/metrics.py", line 174, in dpi
     EventLoop.ensure_window()
   File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/base.py", line 127, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/utils.py", line 496, in __get__
     retval = self.func(inst)
   File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/metrics.py", line 174, in dpi
     EventLoop.ensure_window()
   File "/home/ci-user/.virtualenvs/fixi/lib/python3.6/site-packages/kivy/base.py", line 127, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.

```

Any idea how to avoid this? Or if the error actually relates to the reasons I pointed out?

**Comment by bionoid** [comment]
You probably need `export KIVY_GL_BACKEND=mock`

**Comment by omermazig** [comment]
I set it and it did nothing (same exceptions):

```
Purge log fired. Analysing...
Purge finished!
[INFO   ] [Logger      ] Record log in /home/ci-user/.kivy/logs/kivy_18-04-03_7.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name 'bcm'
  File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: b'Failed to connect to the Mir Server'
  File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 140, in __init__
    super(WindowSDL, self).__init__()
  File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 899, in __init__
    self.create_window()
  File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 269, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 84, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (/tmp/pip-build-g0kywea3/Kivy/kivy/core/window/_window_sdl2.c:2290)
  File "kivy/core/window/_window_sdl2.pyx", line 57, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (/tmp/pip-build-g0kywea3/Kivy/kivy/core/window/_window_sdl2.c:1872)

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip(['clipboard_dbusklipper', 'clipboard_gtk3'] ignored)
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [Text        ] Provider: sdl2
[WARNING] [Factory     ] Ignored class "NotificationPopup" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.popups.NotificationPopup'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Popup, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/popups.kv.
[WARNING] [Factory     ] Ignored class "YesNoPopup" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.popups.YesNoPopup'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Popup, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/popups.kv.
[WARNING] [Factory     ] Ignored class "DbDataEntryPopup" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.popups.DbDataEntryPopup'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Popup, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/popups.kv.
[WARNING] [Factory     ] Ignored class "TinyLayout" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyLayout'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Layout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyBoxLayout" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyBoxLayout'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyLayout+BoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyGridLayout" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyGridLayout'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyLayout+GridLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinySpinner" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinySpinner'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Spinner, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Button, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyToggleButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyToggleButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+ToggleButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyLabel" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyLabel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+Label, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinySquareIconButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinySquareIconButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyToggledSquareIconButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyToggledSquareIconButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinySquareIconButton+ToggleButtonBehavior, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TinyTextInput" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TinyTextInput'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyWidget+TextInput, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "FieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.FieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyBoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TextFieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TextFieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FieldInputBox, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "IntFieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.IntFieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FieldInputBox, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "ChoiceFieldInputBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.ChoiceFieldInputBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FieldInputBox, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "TurningWidget" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_widgets.TurningWidget'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Widget, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "InitErrorScreen" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.tiny_apps.InitErrorScreen'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: BoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/tiny_widgets.kv.
[WARNING] [Factory     ] Ignored class "DataEntryBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.DataEntryBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyBoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "FieldLine" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.FieldLine'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: BoxLayout, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "FieldChooserButton" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.FieldChooserButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Button, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "MultiSelectOption" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.MultiSelectOption'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyToggleButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "SingleSelectOption" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.SingleSelectOption'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyButton, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "StringInput" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.StringInput'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TextInput, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "SearchBox" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.SearchBox'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: StringInput, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[WARNING] [Factory     ] Ignored class "DataDisplayLine" re-declaration. Current -  module: None, cls: <class 'tiny_kivy_widgets.forms.DataDisplayLine'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: TinyLabel, filename: /home/ci-user/tiny_inspektor/sw/tiny_kivy_widgets/src/tiny_kivy_widgets/forms.kv.
[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/utils.py", line 496, in __get__
     retval = self.func(inst)
   File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/metrics.py", line 174, in dpi
     EventLoop.ensure_window()
   File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/base.py", line 127, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception ignored in: 'kivy.properties.dpi2px'
 Traceback (most recent call last):
   File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/utils.py", line 496, in __get__
     retval = self.func(inst)
   File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/metrics.py", line 174, in dpi
     EventLoop.ensure_window()
   File "/home/ci-user/.virtualenvs/tiny_annotator/lib/python3.6/site-packages/kivy/base.py", line 127, in ensure_window
     sys.exit(1)
 SystemExit: 1
[CRITICAL] [App         ] Unable to get a Window, abort.

```

Other ideas?

**Comment by bionoid** [comment]
You need xvfb as well, sorry haven't looked at this for a while, see https://github.com/kivy/kivy/blob/1.10.0/.travis.yml#L83-L94

**Comment by omermazig** [comment]
I'm not sure I understand you're answer. I did:

```
export KIVY_GL_BACKEND=mock
sudo apt-get install xvfb
xvfb-run python kivy_app_main.py
```
and it still gave the same exception. Am I missing something?

**Comment by bionoid** [comment]
Sorry I don't have a headless machine handy to test, but maybe just missing the args from previous link?

    xvfb-run --server-args="-screen 0 1280x720x24 -ac +extension GLX" python kivy_app_main.py

If not, I'm not sure what's missing. You'll probably have to refer to xvfb docs or wait for someone that was involved with travis to clarify

**Comment by omermazig** [comment]
The last one works! (with `export KIVY_GL_BACKEND=mock` in the ~/.bashrc). Thank you!
