### ISSUE TITLE
Nested recycle view

### ISSUE THREAD

**Issue by croccio** [kivy/kivy#5735]
### Versions

* Python: python3
* OS: macos
* Kivy: master version
* Kivy installation method: pip

### Description

how can I have nested scrollview??

### Code and Logs

```python

FilmShowCaseScreen.kv

<Row@BoxLayout>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos
    value: ''
    Label:
        text: root.value

<FilmShowCaseScreen>:
    name: 'FilmShowCaseScreen'
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            size: self.size
            pos: self.pos
    rv: rv
    orientation: 'vertical'

    RecycleView:
        id: rv
        scroll_type: ['bars', 'content']
        scroll_wheel_distance: dp(114)
        bar_width: dp(10)
        viewclass: 'Row'
        RecycleBoxLayout:
            default_size: None, dp(56)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
            spacing: dp(2)


FilmShowCaseLayout

<FilmRow@RecycleBoxLayout>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos
    value: ''
    Label:
        text: root.value

<FilmShowCaseLayout>:

    RecycleView:
        id: rv
        scroll_type: ['bars', 'content']
        scroll_wheel_distance: dp(114)
        bar_width: dp(10)
        viewclass: 'FilmRow'
        RecycleBoxLayout:
            default_size: None, dp(56)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'horizontal'
            spacing: dp(2)



main.py

class FilmShowCaseScreen(Screen):

    def __init__(self, **kwargs):
        Screen.__init__(self, **kwargs)
        Clock.schedule_once(self.populate)

    def populate(self, *l):
        self.rv.data = [FilmShowCaseLayout()]


class FilmShowCaseLayout(BoxLayout):

    def __init__(self, **kwargs):
        BoxLayout.__init__(self, **kwargs)
        Clock.schedule_once(self.populate)

    def populate(self, *l):
        self.recycleView.data = [{'value': ''.join(sample(ascii_lowercase, 6))}
                        for x in range(50)]


```
Traceback (most recent call last):
   File "main.kv", line 59, in <module>
     Film4AllApp().run()
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/core/window/window_sdl2.py", line 723, in mainloop
     self._mainloop()
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/uix/recycleview/__init__.py", line 225, in refresh_views
     lm.compute_sizes_from_data(data, f)
   File "/Users/antonioscardigno/Library/Python/2.7/lib/python/site-packages/kivy/uix/recyclelayout.py", line 154, in compute_sizes_from_data
     ph = item.get('pos_hint', ph)
 AttributeError: 'FilmShowCaseLayout' object has no attribute 'get'

**Comment by tshirtman** [comment]
This looks like a support question, but i'm not sure i understand, you  want each (or some) item(s) of your recycleview to also be recycleview? That's probably a bad idea, but it's probably possible.

You need to read the RecycleView documentation, though, because you are using it wrong (don't give widgets to `data`, gives it the parameter for your viewclass to create the widgets).
