### ISSUE TITLE
Kivy Does Not Open after creating .exe with cx_Freeze 

### ISSUE THREAD

**Issue by H1bertto** [kivy/kivy#5745]
### Versions

* Python: 3.6
* OS: Windows 10
* Kivy: 10.1.dev0
* cx_Freeze: 5.1.1

### Description

In PyCharm IDE, Kivy works perfectly, but when I create .exe with cx_Freeze, it throws errors:

### Code and Logs

```python
[ERROR  ] [Core        ] error while reading localconfiguration
Traceback (most recent call last):
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\config.py", line 675, in <module>
    Config.read(kivy_config_fn)
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\config.py", line 442, in read
    for k, v in self.items(section):
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 858, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 858, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 855, in <lambda>
    section, option, d[option], d)
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%y-%m-%d_%_.txt'
[ERROR  ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\logger.py", line 225, in emit
    self._configure()
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\logger.py", line 155, in _configure
    log_name = Config.get('kivy', 'log_name')
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\config.py", line 474, in get
    value = PythonConfigParser.get(self, section, option, **kwargs)
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 800, in get
    d)
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\lib\ConfigParser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%y-%m-%d_%_.txt'
[INFO   ] [Kivy        ] v1.10.1.dev0, git-5f6c66e, 20180507
[INFO   ] [Python      ] v3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ImportRerror: DLL load failed: The specified module could not be found.
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python36\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\humberto.v.souza\AppData\Local\Programs\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] [App          ] Unable to get a Window, abort.

```

**Comment by H1bertto** [comment]
My setup.py:

```python
from cx_Freeze import setup, Executable
import sys
import os

os.environ['TCL_LIBRARY'] = r'C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\tcl\tcl8.6'
os.environ['TK_LIBRARY'] = r'C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\tcl\tk8.6'

base = None
if sys.platform == "win32":
    base = "Win32GUI"
setup(
    name="Kivy",
    options={'build_exe': {'packages': ["time", "kivy", "threading", "ctypes", "teste1", "teste2"],
                           'includes': ["dispatch", "ctypes", "kivy", "OpenGL"],
                           'excludes': [""],
                           'include_files':
                               [r'C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\DLLs\tcl86t.dll',
                                r'C:\Users\humberto.v.souza\AppData\Local\Programs\Python\Python36\DLLs\tk86t.dll',
                                r'C:\Users\humberto.v.souza\PycharmProjects\Kivy\Teste.kv']}
             },
    version="1.0.5",
    author="Humberto",
    author_email="",
    description='Kivy',
    executables=[Executable(r'C:\Users\humberto.v.souza\PycharmProjects\Kivy\TesteKivy.py',
                            base=None,  # "Console", base, # None
                            icon=r"C:\Users\humberto.v.souza\Downloads\Icos\laptop.ico")],
    requires=['cx_Freeze']

)
```

**Comment by dolang** [comment]
Sorry, don't have the time right now to try to reproduce that, and I have no experience with `cx_Freeze` either. I don't even know if that's supported.

However, it seems it can't find the `SDL2.dll`. On Windows, I think Kivy looks for it in `./share/sdl2/bin`. But you can put a folder containing the DLLs on the PATH (in cmd.exe e.g. `set PATH=...`) to test if that's the problem.

If you don't package all those dependency DLLs somehow, they need to be installed with the system interpreter's pip, too.

**Comment by H1bertto** [comment]
Hmmm... I'll try this, thanks

**Comment by H1bertto** [comment]
It did not work either, I'll have to look for another way to create an .exe with Kivy.
Would you know in any way?

**Comment by kkhaue** [comment]
@H1bertto vi que é BR, pode me ajudar por favor a transformar uma GUI kivy em .exe tentei com PyInstaller e Freeze e nenhuma deu tentativa deu certo

**Comment by gaurav431** [comment]
executables=[Executable(r'C:\Users\humberto.v.souza\PycharmProjects\Kivy\TesteKivy.py',
                            base=bass  # "Console", base, # None
                            icon=r"C:\Users\humberto.v.souza\Downloads\Icos\laptop.ico")],
    requires=['cx_Freeze']




bass = bass
base = "Win32GUI"
