### ISSUE TITLE
Camera issue when defining resolution

### ISSUE THREAD

**Issue by DanielVip3** [kivy/kivy#5752]
### Versions

* Python: 3.6
* OS: Windows 10 64 bit
* Kivy: 1.10.0
* Kivy installation method: Pip

### Description
I start off saying that I'm a novice and I'm trying to make an android app with Kivy Launcher, and I'm using OpenCV 3.
In the app, I tried to set the resolution for my camera, that should be linked with a fullscreen button. 
The app runs when I set 
`cam = Camera(play=True)`
but I don't know why it doesn't take any photo.
Or, at least, it takes a white photo.

So, I tried adding resolution parameter and I can't figure out why it raises this error :
```python
[INFO   ] [Logger      ] Record log in C:\Users\danie\.kivy\logs\kivy_18-05-15_66.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Camera      ] Provider: opencv
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.13399 Compatibility Profile Context 15.201.1151.1008'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon HD 8370D'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.40'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <18>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "C:\Users\danie\Desktop\app\main.py", line 11, in <module>
     cam = Camera(play=True, index=1, resolution=(1920, 1080))
   File "C:\Users\danie\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\camera.py", line 91, in __init__
     on_index()
   File "C:\Users\danie\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\uix\camera.py", line 103, in _on_index
     resolution=self.resolution, stopped=True)
   File "C:\Users\danie\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\camera\camera_opencv.py", line 67, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "C:\Users\danie\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\camera\__init__.py", line 70, in __init__
     self.init_camera()
   File "C:\Users\danie\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\camera\camera_opencv.py", line 117, in init_camera
     self._resolution = (int(frame.shape[1]), int(frame.shape[0]))
 AttributeError: 'NoneType' object has no attribute 'shape'
```
I think that this error is related to OpenCV(at least, that's what I can read), but I don't know if there's a fix or not.
I don't know how to install OpenCV 2(because I'm using 3 now), else I would try using it.
I expected to simply set my resolution and take a photo when pressing the button.
Also, without choosing the right resolution, the photo is white. 

### Code and Logs

```python
from kivy import *
from kivy.app import *
import cv2
from kivy.uix.button import *
from kivy.uix.camera import *
from kivy.uix.image import *
from kivy.core.window import *
from kivy.uix.boxlayout import *
from kivy.config import *

cam = Camera(play=True, resolution=(1920, 1080))

Config.set("graphics", "fullscreen", "auto")

class myLayout(BoxLayout):
    def callback(self, obj):
        print('Did it')
        cam.export_to_png(filename="boh.png")
        
    def __init__(self, **kwargs):
        super(myLayout, self).__init__(**kwargs)

        self.cols = 1
        bottone = Button(text="Prova")
        bottone.bind(on_press=self.callback)
        self.add_widget(bottone)      
        
class MainApp(App):     
    def build(self, **kwargs):
        mL = myLayout()
        return mL


if __name__=="__main__":
    MainApp().run()
```

**Comment by crisdesivo** [comment]
Has this been solved? I have this issue as well

**Comment by bluefloyd00** [comment]
same here

**Comment by VishvajeetRamanuj** [comment]
I am facing similar issue.
I see no assignee no label to this issue. please assign if it can solve issue faster.
I seen this same question was asked on stackoverflow on dated 18th July 2016. but still no answer. Bellow is the link
https://stackoverflow.com/questions/38446292/kivy-error-camera-webcam-gives-error-videocaptureresolution-not-found

If anyone know other better alternative then please suggest me. I want to build application in python which uses machine learning functionality and run it on Android.

**Comment by fo1yy** [comment]
Hey guys, I had the same problem, I just ran the command "pip install cython" and it worked

**Comment by einav888** [comment]
Did someone solve this? 
How does "pip install cython"  help me? I've tried and it doesn't work.

**Comment by VishvajeetRamanuj** [comment]
Try it using outside of conda

**Comment by vishu2435** [comment]
please i am also facing it

**Comment by VictorManhani** [comment]
I resolved just installing the latest version of python (3.9), Kivy (2.0) and of opencv-python (4.4.0.46), with:

First, I follow this tutorial at youtube:
[Using KivyMD with Python 3.9, Kivy 2.0.0 and a VSCode IDE](https://www.youtube.com/watch?v=Z2PRH_ciLwQ&t=563s)

Second, I just install opencv in terminal:
pip3 install opencv-python

That's it.

**Comment by MattBcool** [comment]
I have also encountered this issue and after reinstalling Kivy 2.0 with the above steps posted by VictorManhani, the issue persisted.

Turns out I didn't have my webcam plugged in. Be sure your webcam is properly working and all should be good after installing!
Hope this helps anyone else.

**Comment by AmitNikhade** [comment]
I am facing the same problem. 


(base) lucifer@lucifer-Lenovo-ideapad-330-15IKB:~/Documents/Ki/kivy$ /home/lucifer/anaconda3/bin/python /home/lucifer/Documents/Ki/main.py
[INFO   ] [Logger      ] Record log in /home/lucifer/.kivy/logs/kivy_21-05-29_37.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]
[INFO   ] [Python      ] Interpreter at "/home/lucifer/anaconda3/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[INFO   ] [Camera      ] Provider: opencv(['camera_picamera', 'camera_gi'] ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 20.2.6'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) UHD Graphics 620 (KBL GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[ WARN:0] global /tmp/pip-req-build-99ib2vsi/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
 Traceback (most recent call last):
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
     setattr(self.__ref__(), name, value)
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
     
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
     observable_list_dispatch(self)
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
     cpdef set(self, EventDispatcher obj, value):
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
     '''Convert the initial value to a correctly validating value.
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
     not including callbacks removed during dispatching.
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
     self.last_callback = callback.prev
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/uix/camera.py", line 103, in _on_index
     self._camera = CoreCamera(index=self.index,
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 70, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 120, in init_camera
     self._resolution = (int(frame.shape[1]), int(frame.shape[0]))
 AttributeError: 'NoneType' object has no attribute 'shape'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/lucifer/Documents/Ki/main.py", line 53, in <module>
     MyApp().run()
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/home/lucifer/Documents/Ki/main.py", line 49, in build
     return MyLayout()
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/lang/builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "/home/lucifer/Documents/Ki/myapplayout.kv", line 7:
 ...
       5:    AndroidCamera:
       6:        index: 0
 >>    7:        resolution: 640, 480
       8:        allow_stretch: True
       9:        play: True
 ...
 AttributeError: 'NoneType' object has no attribute 'shape'
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
     setattr(self.__ref__(), name, value)
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
     observable_list_dispatch(self)
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
     cpdef set(self, EventDispatcher obj, value):
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
     '''Convert the initial value to a correctly validating value.
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
     not including callbacks removed during dispatching.
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
     self.last_callback = callback.prev
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/uix/camera.py", line 103, in _on_index
     self._camera = CoreCamera(index=self.index,
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 70, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/lucifer/anaconda3/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 120, in init_camera
     self._resolution = (int(frame.shape[1]), int(frame.shape[0]))

**Comment by Julian-O** [comment]
It isn't clear that these are all the same issue. Take them to the Support channels. If they agree it is a bug and not just a configuration issue, come back here with the information we need to solve it.
