### ISSUE TITLE
Animation.on_complete does not fire when Window arg is parsed into Animation.start

### ISSUE THREAD

**Issue by JakubBlaha** [kivy/kivy#5757]
### Versions

* Python: 3.6.5
* OS: Windows 10
* Kivy: 1.10.0
* Kivy installation method: wheels

### Description

The `Animation.on_complete` does not fire when `Window` is parsed into the `Animation.start` method. On other widgets I have not encountered with this issue.

### Code and Logs

```python
anim = Animation(size=(300, 300), transition='out_expo')
anim.on_complete = lambda: print('completed')
anim.start(Window)

```

**Comment by kuzeyron** [comment]
You could try using `self.animation.bind(on_complete=self.clear_color)`.
Which is found from [this issue](https://github.com/kivy/kivy/issues/5204)

**Comment by tshirtman** [comment]
I can't reproduce here.

```
from kivy.app import App
from kivy.core.window import Window
from kivy.animation import Animation
from kivy.uix.button import Button


class WApp(App):
    def build(self):
        return Button(on_press=self.start_anim)

    def start_anim(self, *args):
        anim = Animation(size=(300, 300), transition='out_expo')
        anim.on_complete = lambda: print('completed')
        anim.start(Window)


if __name__ == '__main__':
    WApp().run()
```

i get:

```
 Traceback (most recent call last):
   File "/tmp/test_an Traceback (most recent call last):
   File "/tmp/test_anim.py", line 18, in <module>
     WApp().run()
   File "/home/gabriel/dev/kivy/kivy/app.py", line 826, in run
     runTouchApp()
   File "/home/gabriel/dev/kivy/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/gabriel/dev/kivy/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/home/gabriel/dev/kivy/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/home/gabriel/dev/kivy/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/home/gabriel/dev/kivy/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/home/gabriel/dev/kivy/kivy/animation.py", line 352, in _update
     self.stop(widget)
   File "/home/gabriel/dev/kivy/kivy/animation.py", line 217, in stop
     self.dispatch('on_complete', widget)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
 TypeError: <lambda>() takes 0 positional arguments but 1 was givenim.py", line 18, in <module>
     WApp().run()
   File "/home/gabriel/dev/kivy/kivy/app.py", line 826, in run
     runTouchApp()
   File "/home/gabriel/dev/kivy/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/gabriel/dev/kivy/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/home/gabriel/dev/kivy/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/home/gabriel/dev/kivy/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/home/gabriel/dev/kivy/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/home/gabriel/dev/kivy/kivy/animation.py", line 352, in _update
     self.stop(widget)
   File "/home/gabriel/dev/kivy/kivy/animation.py", line 217, in stop
     self.dispatch('on_complete', widget)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
 TypeError: <lambda>() takes 0 positional arguments but 1 was given
```
at the end of the animation, which is proof that the lambda was called.

But yes, as @kuzeyron this is not how you should bind a function to an event, use `bind`.

Please give a more complete test case if you still have the error.

**Comment by JakubBlaha** [comment]
I still have the problem.

Maybe `Config.set('graphics', 'multisamples', 0)` is the problem. I have set it like that because I am experiencing the issue with OpenGL version detection.

If I do `anim.bind('on_complete', fn)` I get an error saying `TypeError: bind() takes exactly 0 positional arguments (2 given)`.

**Comment by tshirtman** [comment]
The syntax is `anim.bind(on_complete=fn)` or alternativelay `anim.fbind('on_complete', fn)` both versions works the same for me. I don't think the multisample level will have any effect on that (but i tested anyway, no change for me).

However, i just saw you had the issue on 1.10.0 so i checked it, and i can reproduce the issue there, so it's been fixed since, and the next release will contain the fix.

**Comment by JakubBlaha** [comment]
Is there some way I can fix that myself? I know that pre-releases can be pretty unstable.

**Comment by tshirtman** [comment]
Actually, i think it would be a lot better for you to try the latest master, we are really nearing a release and things are quite smooth now, the actual release (due "soon") might not be very different.

Alternatively, since we have a known test, one could use git bisect to find which commit fixed it and you could apply it manually, but i do think it's more trouble than it's worth.
