### ISSUE TITLE
can't run test suite: UserWarning: Unknown distribution option: 'dependency_links'

### ISSUE THREAD

**Issue by martinkg** [kivy/kivy#5800]
### Versions

* Python: python3-3.6.5-1.fc28.x86_64
* OS: Fedora Linux f28 4.16.14-300.fc28.x86_64
* Kivy: Kivy-1.10.0
* Kivy installation method: rpm package

### Description
when running the test suite with `python3 setup.py test` i get this error message:
```
Using distutils

Detected Cython version 0.28.1
  This version of Cython is untested with Kivy. While this version may
  work perfectly fine, it is possible that you may experience issues. If
  you do have issues, please downgrade to a supported version. It is
  best to use the newest supported version, 0.25.2, but the minimum
  supported version is 0.23.

  If your platform provides a Cython package, check if you can downgrade
  to a supported version. Otherwise, uninstall the platform package and
  install Cython via pip:

    pip install -I Cython==0.25.2
Using this graphics system: OpenGL
GStreamer found via pkg-config
SDL2 found via pkg-config
SDL2: found SDL header at /usr/include/SDL2/SDL.h
SDL2: found SDL_mixer header at /usr/include/SDL2/SDL_mixer.h
SDL2: found SDL_ttf header at /usr/include/SDL2/SDL_ttf.h
SDL2: found SDL_image header at /usr/include/SDL2/SDL_image.h
 /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'dependency_links'
   warnings.warn(msg)
 /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
   warnings.warn(msg)
 /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'
   warnings.warn(msg)
 usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
    or: setup.py --help [cmd1 cmd2 ...]
    or: setup.py --help-commands
    or: setup.py cmd --help
 
 error: invalid command 'test'
```
i solved this by adding this patch to setup.py:
```
--- setup.py.orig	2018-06-12 11:14:47.855845336 +0200
+++ setup.py	2018-06-12 11:14:58.414846101 +0200
@@ -4,6 +4,7 @@
 #
 from __future__ import print_function
 
+import setuptools
 import sys
 build_examples = False
 if "--build_examples" in sys.argv:
```
but then i get the following error message:

```
gcc -pthread -shared -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none build/temp.linux-x86_64-3.6/kivy/lib/gstplayer/_gstplayer.o -L/usr/lib64 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lpython3.6m -o /home/martin/rpmbuild/BUILD/Kivy-1.10.0/kivy/lib/gstplayer/_gstplayer.cpython-36m-x86_64-linux-gnu.so -lm
xclip version 0.13
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
 Traceback (most recent call last):
   File "setup.py", line 1056, in <module>
     ] if not skip_cython else [])
   File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
     dist.run_commands()
   File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
     self.run_command(cmd)
   File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
     cmd_obj.run()
   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 226, in run
     self.run_tests()
   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
     exit=False,
   File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
     self.parseArgs(argv)
   File "/usr/lib64/python3.6/unittest/main.py", line 118, in parseArgs
     self._do_discovery(argv[2:])
   File "/usr/lib64/python3.6/unittest/main.py", line 229, in _do_discovery
     self.test = loader.discover(self.start, self.pattern, self.top)
   File "/usr/lib64/python3.6/unittest/loader.py", line 341, in discover
     tests = list(self._find_tests(start_dir, pattern))
   File "/usr/lib64/python3.6/unittest/loader.py", line 398, in _find_tests
     full_path, pattern, namespace)
   File "/usr/lib64/python3.6/unittest/loader.py", line 475, in _find_test_path
     tests = self.loadTestsFromModule(package, pattern=pattern)
   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
     tests.append(self.loadTestsFromName(submodule))
   File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
     module = __import__(module_name)
   File "/home/martin/rpmbuild/BUILD/Kivy-1.10.0/doc/autobuild.py", line 35, in <module>
     import kivy.core.gl
   File "/home/martin/rpmbuild/BUILD/Kivy-1.10.0/kivy/core/gl/__init__.py", line 83, in <module>
     import kivy.core.window  # NOQA
   File "/home/martin/rpmbuild/BUILD/Kivy-1.10.0/kivy/core/window/__init__.py", line 27, in <module>
     from kivy.uix.behaviors import FocusBehavior
   File "/home/martin/rpmbuild/BUILD/Kivy-1.10.0/kivy/uix/behaviors/__init__.py", line 89, in <module>
     from kivy.uix.behaviors.compoundselection import CompoundSelectionBehavior
   File "/home/martin/rpmbuild/BUILD/Kivy-1.10.0/kivy/uix/behaviors/compoundselection.py", line 136, in <module>
     _is_desktop = Config.getboolean('kivy', 'desktop')
 AttributeError: 'NoneType' object has no attribute 'getboolean'
```

Is there any solution ?

**Comment by dolang** [comment]
Usually, I run the tests simply with:
```
make test
```
from the main directory, and not with `setup.py test`.

The following python modules should be installed if you want to run the tests: `nose`, `mock`, `coverage`, `pygments` and `docutils`.

But the error you're seeing is unrelated to that. I'm not sure if `python setup.py test` is even supported.

-----

By the way, Kivy allows compilation/packaging with both `distutils` and `setuptools`, and some functionality only works with `setuptools`. But you don't have to modify `setup.py` for that. If you want to activate `setuptools`, then do:
```
export KIVY_USE_SETUPTOOLS=1
python setup.py ...
```

**Comment by martinkg** [comment]
On Fedora 28 the following python modules are installed:

`python3-nose mock python3-coverage python3-pygments docutils`

make test fails also with:

```
+ cd Kivy-1.10.0
+ export KIVY_USE_SETUPTOOLS=1
+ KIVY_USE_SETUPTOOLS=1
+ make test
make: *** No rule to make target 'test'.  Stop.
```

**Comment by dolang** [comment]
That's strange, the `test` target is definitely in the [Makefile](https://github.com/kivy/kivy/blob/1.10.0/Makefile#L86-L88). It basically translates to:
```
rm -rf kivy/tests/build
python3 -m nose.core kivy/tests
```
in your case.

**Comment by martinkg** [comment]
ok, i had the wrong tar archive of kivy.

now i get this error message:

```
+ cd kivy-1.10.0
+ make test
rm -rf kivy/tests/build
python3 -m nose.core kivy/tests
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'nose.core' found in sys.modules after import of package 'nose', but prior to execution of 'nose.core'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[INFO   ] [Logger      ] Record log in /home/martin/.kivy/logs/kivy_18-06-12_23.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.5 (default, Mar 29 2018, 18:20:46) 
[GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]
#1 Failure: ModuleNotFoundError (No module named 'kivy._clock') ... ERROR
#2 Failure: ModuleNotFoundError (No module named 'kivy.properties') ... ERROR
#3 Failure: ModuleNotFoundError (No module named 'kivy._event') ... ERROR
#4 Failure: ModuleNotFoundError (No module named 'kivy._clock') ... ERROR
#5 test_length_playing (kivy.tests.test_audio.AudioGstreamerTestCase) ... ERROR
#6 test_length_simple (kivy.tests.test_audio.AudioGstreamerTestCase) ... ERROR
#7 test_length_stopped (kivy.tests.test_audio.AudioGstreamerTestCase) ... ERROR
#8 test_length_playing (kivy.tests.test_audio.AudioPygameTestCase) ... ERROR
#9 test_length_simple (kivy.tests.test_audio.AudioPygameTestCase) ... ERROR
#10 test_length_stopped (kivy.tests.test_audio.AudioPygameTestCase) ... ERROR
#11 test_length_playing (kivy.tests.test_audio.AudioTestCase) ... ERROR
#12 test_length_simple (kivy.tests.test_audio.AudioTestCase) ... ERROR
#13 test_length_stopped (kivy.tests.test_audio.AudioTestCase) ... ERROR
#14 test_clipboard_copy (kivy.tests.test_clipboard.ClipboardTestCase) ... [TRACE  ] [Clipboard   ] Unable to use dbusklipper
[TRACE  ] 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.klipper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/rpmbuild/BUILD/kivy-1.10.0/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/martin/rpmbuild/BUILD/kivy-1.10.0/kivy/core/clipboard/clipboard_dbusklipper.py", line 16, in <module>
    proxy = bus.get_object("org.kde.klipper", "/klipper")
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.klipper was not provided by any .service files
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
```

**Comment by dolang** [comment]
It's easy to take a wrong step here and get errors, because of how the project relies on compiled code & has supports switching out dependencies. Make sure that you...:
* Compile it beforehand (use `make` or `python3 build_ext -i`)
* Run the commands from the base directory
* Do not install it then try to run the tests. It can be made to work but it's tricky. Take the source, compile, test, in that order. Optionally install it afterwards.
* Don't try to run code (for instance, an example) from the base directory after installation. Python might get confused by the source files. Just `cd` somewhere else, then that should work.

**Comment by dolang** [comment]
So I guessed this was actually related to RPM packaging and not just an ordinary installation to figure things out. I then went and found your package on Koji. I've only had a short look at it so far, but this may help anyway:
* You're using the 4 SDL2 libraries as build dependencies, but then switch to `python3-pygame` for the `Requires:`. Pygame is deprecated as a dependency, please use the four SDL2 libraries instead.
* There's the `kivy-daily` PPA for Ubuntu over in the `kivy-sdk-packager` project which should give you a better idea of what the [dependencies](https://github.com/kivy/kivy-sdk-packager/blob/master/linux/debian/daily/control#L190-L213) really are. Some of them can be switched out for others. There's no `.spec` file in that project, I'm afraid.
* Tangentially related: If you're familiar with **Ansible**, I have [a Gist](https://gist.github.com/dolang/6b58c49836b525ad8fb94618e260ac4b) here for an automated build just with SDL2, gstreamer & tests (GitHub master branch). If you want to give that a spin, simply `wget` the raw version, then run `ansible-playbook -K kivy-dev-fedora.yml`. It might be helpful in one way or another to see a working build on Fedora 28 other than your RPM package.

I'd still like to invite you to join the [#kivy IRC support channel](https://kivy.org/#support), it would be easier to figure things out together and might save you some time.

There are also a few minor problems you might encounter which would be more convenient to talk about in a chat channel.

**Comment by dessant** [comment]
@dolang, thanks for helping out a fellow Kivy user!
@martinkg, this may indeed be best to entangle on IRC instead.
