### ISSUE TITLE
Kivy RenderContext wrong size error

### ISSUE THREAD

**Issue by FLKivyKid** [kivy/kivy#5851]
### Versions

* Python: 2.7 or 3.5
* OS: Raspbian Stretch
* Kivy: Should be 1.10.1, I think I'm getting 1.11.0.dev0
* Kivy installation method: using terminal, globally on the system

### Description

App does not even open. As soon as it ran, the issue comes up on the python 3.5.3 Shell, ending with a ValueError: Kivy.graphics.instructions.RenderContext has the wrong size, try recompiling. Expected 84, got 88... Nothing has worked so far. Would love some assistance in resolving this, so that I could get back to working on the project. Thanks.

### Code and Logs

=========== RESTART: /home/pi/Desktop/Kivy Projects/control.py ===========
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_18-07-10_19.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "/home/pi/Desktop/Kivy Projects/tankcontrol.py", line 13, in <module>
     from kivy.app import App
   File "/usr/local/lib/python3.5/dist-packages/kivy/app.py", line 327, in <module>
     from kivy.uix.widget import Widget
   File "/usr/local/lib/python3.5/dist-packages/kivy/uix/widget.py", line 244, in <module>
     from kivy.graphics import (
   File "/usr/local/lib/python3.5/dist-packages/kivy/graphics/__init__.py", line 89, in <module>
     from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \
   File "kivy/graphics/vbo.pxd", line 7, in init kivy.graphics.instructions (/tmp/pip-build-4zik8qjr/Kivy/kivy/graphics/instructions.c:16488)
     cdef class VBO:
   File "kivy/graphics/compiler.pxd", line 1, in init kivy.graphics.vbo (/tmp/pip-build-4zik8qjr/Kivy/kivy/graphics/vbo.c:6998)
     cdef class GraphicsCompiler
   File "kivy/graphics/shader.pxd", line 5, in init kivy.graphics.compiler (/tmp/pip-build-4zik8qjr/Kivy/kivy/graphics/compiler.c:4525)
     cdef class ShaderSource:
   File "kivy/graphics/instructions.pxd", line 9, in init kivy.graphics.shader
     cdef class RenderContext
 ValueError: kivy.graphics.instructions.RenderContext has the wrong size, try recompiling. Expected 84, got 88

>>> ```

**Comment by tito** [comment]
I feel you have mixed compilation somewhere.
1. ensure you don't have kivy directory in your application (/home/pi/Desktop/Kivy Projects/)
2. if you compiled yourself and tried various method, maybe you mixed up local compilation with local installation. Delete all the copy of kivy you have (/usr/local/lib/python3.5/dist-packages/kivy, the clone you have). Then just git clone and "pip install -e ." from the kivy directory if you want to use master
3. ensure you don't mix PYTHONPATH that include local kivy with global installation
