### ISSUE TITLE
Strange Key Error

### ISSUE THREAD

**Issue by openedhardware** [kivy/kivy#5865]
### Versions

* Python: 3.5.3
* OS: Raspbian Stretch
* Kivy: v1.11.0.dev0, git-2edd0c4, 20180714
* Kivy installation method: Compiled from source

I am displaying the docked keyboard on a screen, and getting this error log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/window_egl_rpi.py", line 92, in mainloop
    self._mainloop()
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/window_egl_rpi.py", line 87, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 340, in idle
    self.dispatch_input()
  File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 325, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 231, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (/tmp/pip-siuyf6wr-build/kivy/_event.c:8191)
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/__init__.py", line 1335, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (/tmp/pip-siuyf6wr-build/kivy/_event.c:8191)
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/__init__.py", line 1351, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (/tmp/pip-siuyf6wr-build/kivy/_event.c:8191)
  File "/usr/local/lib/python3.5/dist-packages/kivy/uix/vkeyboard.py", line 844, in on_touch_down
    self.process_key_on(touch)
  File "/usr/local/lib/python3.5/dist-packages/kivy/uix/vkeyboard.py", line 745, in process_key_on
    key = self.get_key_at_pos(x, y)
  File "/usr/local/lib/python3.5/dist-packages/kivy/uix/vkeyboard.py", line 715, in get_key_at_pos
    for key in layout_geometry['LINE_HINT_%d' % line_nb]:
KeyError: 'LINE_HINT_5'
```
- `email.py`
```python
import os
import threading
from kivy.clock import Clock
from kivy.lang import Builder
from kivy.core.window import Window
from screens.base import BaseScreen
from settings import PREVIEW_TIMEOUT
from utils.e_mail import is_valid_email, send_email
from utils.store_selectors import CurEvent
import utils.logger as logger

Builder.load_file(os.path.join(os.path.dirname(__file__), 'kv', 'email.kv'))


class EmailScreen(BaseScreen):
    _allow_focus = True
    """ Internal variable for the auto-focusing feature of the email input box.
    """

    _cnt = PREVIEW_TIMEOUT
    """ Timeout value
    """

    def __init__(self, **kwargs):
        super(EmailScreen, self).__init__(**kwargs)
        self.ids.txt_email.bind(focus=self.on_email_focus)
        self.ids.txt_email.bind(text=self.on_email_text)

    def on_enter(self, *args):
        self._cnt = PREVIEW_TIMEOUT
        Clock.schedule_interval(self.count_down, 1)
        self._allow_focus = True
        self.on_email_focus()
        super(EmailScreen, self).on_enter(*args)

    def on_email_focus(self, *args):
        if not self.ids.txt_email.focus and self._allow_focus:
            self.ids.txt_email.focus = True

    def on_btn_send(self):
        email = self.ids.txt_email.text
        if is_valid_email(email):
            if CurEvent().get().get('Email'):
                threading.Thread(target=send_email, args=(email, )).start()
            else:
                logger.error('Email: XML file does not contain `Email` field - {}'.format(CurEvent().get()))
            self.return_to_home()

    def on_btn_cancel(self):
        self.return_to_home()

    def on_leave(self, *args):
        self._allow_focus = False
        self._cnt = -1
        Window.release_all_keyboards()
        super(EmailScreen, self).on_leave(*args)

    def on_touch_down(self, touch):
        """
        Update timeout value when user touches screen
        :param touch:
        :return:
        """
        super(EmailScreen, self).on_touch_down(touch)
        self._cnt = PREVIEW_TIMEOUT

    def on_email_text(self, *args):
        """
        Update the timeout value when the text changes
        :param args:
        :return:
        """
        self._cnt = PREVIEW_TIMEOUT

    def count_down(self, *args):
        self._cnt -= 1
        if self._cnt == 0:
            self.return_to_home()
            return False        # Cancel this
```

- `email.kv`
```
<EmailScreen>:
    name: 'email_screen'
    BoxLayout:
        id: box
        size_hint: .5, .5
        padding: 30
        spacing: 30
        orientation: 'vertical'
        pos_hint: {'center_y': .75, 'center_x': .5}
        Label:
            text: 'Please enter your email'
            color: 0, 0, 0, 1
            font_size: self.size[1] * .7
            pos_hint: {'center_x': .5}
        KioskEmailInput:
            id: txt_email
            multiline: False
            font_size: self.size[1] * .7
        BoxLayout:
            spacing: 100
            size_hint_y: None
            height: 112
            Button:
                background_normal: 'assets/images/cancel-normal.png'
                background_down: 'assets/images/cancel-pressed.png'
                on_release: root.on_btn_cancel()

            Button:
                id: send_email_button
                background_normal: 'assets/images/send-email-normal.png'
                background_down: 'assets/images/send-email-pressed.png'
                on_release: root.on_btn_send()
```

**Comment by tito** [comment]
After testing, i cannot reproduce the issue here. Did you customize the keyboard in anyway?
Double-check you have the latest version, and don't change anything in the VKeyboard or configuration.
If you did, then tell us how to reproduce the issue :)

(Instanciated a TextInput, with in the config.ini: keyboard_mode = dock)
