### ISSUE TITLE
Kivy crashed when clicked on edges of text input field with large input text 

### ISSUE THREAD

**Issue by fakabbir** [kivy/kivy#5890]
### Versions

* Python: 3.6.5
* OS: Windows 10, 64-bit
* Kivy: v1.10.0
* Kivy installation method:

### Description

After entering large text in text input field and clicking at the right edge near the text, whole kivy UI crashes. 

Present UI: 
![image](https://user-images.githubusercontent.com/13721550/43764807-14f11550-9a4c-11e8-8a7d-3a0ec5ac67ab.png)

### Code and Logs
**- few values are used for list indexing that are getting float values i.e**

- s1c, 
- s2c, 
- col,
-  a, 
- b

debugger logs:
![image](https://user-images.githubusercontent.com/13721550/43764851-2effa8b2-9a4c-11e8-9d7d-f9a1e5e13422.png)

![image](https://user-images.githubusercontent.com/13721550/43764862-343ebc1e-9a4c-11e8-9401-e1cf8b71477d.png)

![image](https://user-images.githubusercontent.com/13721550/43764867-390b5efa-9a4c-11e8-9aa5-e79840f9bcbe.png)

![image](https://user-images.githubusercontent.com/13721550/43764880-3ce61fce-9a4c-11e8-83da-b3b27c240752.png)

```python
[INFO   ] [Logger      ] Record log in C:\Users\merla.chandrika\.kivy\logs\kivy_18-08-03_15.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[WARNING] [Factory     ] Ignored class "FileListEntry" re-declaration. Current -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x000001BF397EBC50>>, 'FileListEntry'), baseclass: None, filename: None. Ignored -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x000001BF397EBC50>>, 'FileListEntry'), baseclass: None, filename: None.
[WARNING] [Factory     ] Ignored class "FileIconEntry" re-declaration. Current -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x000001BF397EBC50>>, 'FileIconEntry'), baseclass: None, filename: None. Ignored -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x000001BF397EBC50>>, 'FileIconEntry'), baseclass: None, filename: None.
[WARNING] [Factory     ] Ignored class "AccordionItemTitle" re-declaration. Current -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x000001BF397EBC50>>, 'AccordionItemTitle'), baseclass: None, filename: None. Ignored -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x000001BF397EBC50>>, 'AccordionItemTitle'), baseclass: None, filename: None.
[WARNING] [Factory     ] Ignored class "ActionPreviousImage" re-declaration. Current -  module: None, cls: None, baseclass: Image, filename: C:\Program Files\Python36\lib\site-packages\kivy\data\style.kv. Ignored -  module: None, cls: None, baseclass: Image, filename: C:\Users\merla.chandrika\Desktop\rda-studio\configs\kvs\style.kv.
[WARNING] [Factory     ] Ignored class "ActionPreviousButton" re-declaration. Current -  module: None, cls: None, baseclass: Button, filename: C:\Program Files\Python36\lib\site-packages\kivy\data\style.kv. Ignored -  module: None, cls: None, baseclass: Button, filename: C:\Users\merla.chandrika\Desktop\rda-studio\configs\kvs\style.kv.
[WARNING] [Factory     ] Ignored class "ColorPicker_Input" re-declaration. Current -  module: None, cls: None, baseclass: TextInput, filename: C:\Program Files\Python36\lib\site-packages\kivy\data\style.kv. Ignored -  module: None, cls: None, baseclass: TextInput, filename: C:\Users\merla.chandrika\Desktop\rda-studio\configs\kvs\style.kv.
[WARNING] [Factory     ] Ignored class "ColorPicker_Label" re-declaration. Current -  module: None, cls: None, baseclass: Label, filename: C:\Program Files\Python36\lib\site-packages\kivy\data\style.kv. Ignored -  module: None, cls: None, baseclass: Label, filename: C:\Users\merla.chandrika\Desktop\rda-studio\configs\kvs\style.kv.
[WARNING] [Factory     ] Ignored class "ColorPicker_Selector" re-declaration. Current -  module: None, cls: None, baseclass: BoxLayout, filename: C:\Program Files\Python36\lib\site-packages\kivy\data\style.kv. Ignored -  module: None, cls: None, baseclass: BoxLayout, filename: C:\Users\merla.chandrika\Desktop\rda-studio\configs\kvs\style.kv.
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 22.20.16.4799'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 520'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 22.20.16.4799'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:4: '' :  #version directive missing">
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:4: '' :  #version directive missing">
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
params: {'id': 'query', 'type': 'string', 'visible': 'true', 'display_name': 'Query', 'required': 'true'}
Keyboard have been closed, Invoking again
[INFO   ] [Base        ] Leaving application in progress...
Traceback (most recent call last):
   File "studio.py", line 150, in <module>
     BuildConsole().run()  # Calling Desktop Automation Application
   File "C:\Program Files\Python36\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Program Files\Python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Program Files\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
     self._mainloop()
   File "C:\Program Files\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "C:\Program Files\Python36\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Program Files\Python36\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Program Files\Python36\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\core\window\__init__.py", line 1188, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\core\window\__init__.py", line 1204, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\textinput.py", line 1369, in on_touch_down
     self.cursor = self.get_cursor_from_xy(*touch_pos)
   File "kivy\properties.pyx", line 478, in kivy.properties.Property.__set__ (kivy\properties.c:5572)
   File "kivy\properties.pyx", line 1471, in kivy.properties.AliasProperty.set (kivy\properties.c:24194)
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\textinput.py", line 2561, in _set_cursor
     offset = self.cursor_offset()
   File "C:\Program Files\Python36\lib\site-packages\kivy\uix\textinput.py", line 606, in cursor_offset
     _lines[row][:col], self.tab_width,
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by mteud** [comment]
Had the same issue, posted fix in #4926

**Comment by pythonic64** [comment]
Should be fixed by https://github.com/kivy/kivy/pull/6666. 
@fakabbir can you re-test with latest master branch?

**Comment by fakabbir** [comment]
@pythonic64 Sure, Will update soon

**Comment by Julian-O** [comment]
Assuming fixed. Closing. Let us know if that is incorrect.
