### ISSUE TITLE
Nested Builder.load_string load : AttributeError

### ISSUE THREAD

**Issue by davied9** [kivy/kivy#5893]
### Versions

* Python: Python 3.7.0
* OS: Windows 7 Professional SP1
* Kivy:  1.10.1
* Kivy installation method: pip

### Description

I tried to add a component A to component B as a child, like this:
```
A:
    B:
```
both A and B are built with Builder.load_string
B has reference 'bt1' defined and refered in B.__init__
but I've got 
```
AttributeError: 'Base' object has no attribute 'bt1'
```

### Code and Logs
I've simplify most of my code to simplist case of this error

test.py
```
from __future__ import print_function
from base import Base
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

Builder.load_string('''
<User>:
    base: base
    Button:
        text: 'test'
    Base:
        id: base
''')

class User(BoxLayout):
    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        print('calling from test : {}'.format(self.base.bt1.text)) # this line is ok
        
        
if '__main__' == __name__:
    from kivy.app import App
    
    class test_app(App):
        def build(self):
            return User()
            
    test_app().run()
```

base.py
```
from __future__ import print_function
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

Builder.load_string('''
<Base>:
    bt1: bt1
    bt2: bt2
    orientation: 'vertical'
    Button:
        id: bt1
        text: 'base 1'
    Button:
        id: bt2
        text: 'base 2'
''')

class Base(BoxLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)
        print('calling from base : {}'.format(self.bt1.text)) # This line cause the problem
```

log
```
[INFO   ] Logger: Record log in C:\Users\Administrator\.kivy\logs\kivy_18-08-13_13.txt
[INFO   ] Kivy: v1.10.1
[INFO   ] Python: v3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.4.0 - Build 21.20.16.4860'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) HD Graphics P530'>
[INFO   ] GL: OpenGL parsed version: 4, 4
[INFO   ] GL: Shading version <b'4.40 - Build 21.20.16.4860'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "E:\Program_files\Python37\lib\runpy.py", line 193, in _run_module_as_main
[WARNING] stderr:     "__main__", mod_spec)
[WARNING] stderr:   File "E:\Program_files\Python37\lib\runpy.py", line 85, in _run_code
[WARNING] stderr:     exec(code, run_globals)
[WARNING] stderr:   File "D:\temp\test.py", line 28, in <module>
[WARNING] stderr:     test_app().run()
[WARNING] stderr:   File "E:\Program_files\Python37\lib\site-packages\kivy\app.py", line 800, in run
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "D:\temp\test.py", line 26, in build
[WARNING] stderr:     return User()
[WARNING] stderr:   File "D:\temp\test.py", line 17, in __init__
[WARNING] stderr:     super(User, self).__init__(**kwargs)
[WARNING] stderr:   File "E:\Program_files\Python37\lib\site-packages\kivy\uix\boxlayout.py", line 131, in __init__
[WARNING] stderr:     super(BoxLayout, self).__init__(**kwargs)
[WARNING] stderr:   File "E:\Program_files\Python37\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
[WARNING] stderr:     super(Layout, self).__init__(**kwargs)
[WARNING] stderr:   File "E:\Program_files\Python37\lib\site-packages\kivy\uix\widget.py", line 348, in __init__
[WARNING] stderr:     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
[WARNING] stderr:   File "E:\Program_files\Python37\lib\site-packages\kivy\lang\builder.py", line 469, in apply
[WARNING] stderr:     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
[WARNING] stderr:   File "E:\Program_files\Python37\lib\site-packages\kivy\lang\builder.py", line 582, in _apply_rule
[WARNING] stderr:     child = cls(__no_builder=True)
[WARNING] stderr:   File "D:\temp\base.py", line 21, in __init__
[WARNING] stderr:     print('calling from base : {}'.format(self.bt1.text))
[WARNING] stderr: AttributeError: 'Base' object has no attribute 'bt1'

```

**Comment by davied9** [comment]
anyone knows the 'id' things imported in which version???
I've found another problem "KeyError : minimum_height", which is related to version 1.9.1, so I'm thinking that maybe this is related, too??

**Comment by davied9** [comment]
Did you reproduce the problem in first comment in kivy 1.10.1?

**Comment by gottadiveintopython** [comment]
That's normal behaviour. If you construct a widget hierarchy with Kv language, `Builder.apply()` is delayed. `Builder.apply()` is the one who applies Kv rules including `id` things.

```python
from kivy.uix.widget import Widget
from kivy.lang import Builder


class VerboseWidget(Widget):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        print('__init__()', self.uid, kwargs)


Builder.load_string('''
<WidgetA>:
    VerboseWidget:
<WidgetB>:
    WidgetA:
''')


class WidgetA(VerboseWidget):
    pass


class WidgetB(VerboseWidget):
    pass


a = WidgetA()
print('------------------------------------')
print(f'a.uid == {a.uid}')
print(f'a.children[0].uid == {a.children[0].uid}')
print('------------------------------------')
b = WidgetB()
print('------------------------------------')
print(f'b.uid == {b.uid}')
print(f'b.children[0].uid == {b.children[0].uid}')
print(f'b.children[0].children[0].uid == {b.children[0].children[0].uid}')
```

```text
__init__() 9 {'__no_builder': True}
__init__() 2 {}
------------------------------------
a.uid == 2
a.children[0].uid == 9
------------------------------------
__init__() 13 {'__no_builder': True}
__init__() 15 {'__no_builder': True}
__init__() 11 {}
------------------------------------
b.uid == 11
b.children[0].uid == 13
b.children[0].children[0].uid == 15
```

https://github.com/kivy/kivy/blob/11c9fe6c03fa03d16eceb1656ca51ff0129815dc/kivy/uix/widget.py#L347-L348

Hope you get the idea.

**Comment by davied9** [comment]
@gottadiveintopython 

Thanks a lot, I've got the idea. So it's normal behaviour for current code.

But from the perspective of usage, I think the 'id' thing should be available here.

If not, I can only manually add component in __init__, and this will break the structure defined in Builder string, and this make the code harder to understand.

**Comment by gottadiveintopython** [comment]
> But from the perspective of usage, I think the 'id' thing should be available here.

Yep I agree with that. If you or someone create a PR for that, I'd be happy :), since it's one of the inconvenience of Kivy for me from the very beginning.

**Comment by davied9** [comment]
@gottadiveintopython After I fix my code to avoid this, I still meet some other compiling problem, I decide to move on. Maybe later when I come back to kivy, I'll try to figure this out.

Still thanks for your time.

**Comment by gottadiveintopython** [comment]
No problem :)

**Comment by gottadiveintopython** [comment]
A workaround is:

```python
class Base(BoxLayout):
    def __init__(self, **kwargs):
        super(Base, self).__init__(**kwargs)
        Clock.schedule_once(self._after_kv_applied)

    def _after_kv_applied(self, __):
        print('calling from base : {}'.format(self.bt1.text))
```
