### ISSUE TITLE
Kivy Garden graph:  ZeroDivisionError: float division by zero - In case of repetitive value to plot

### ISSUE THREAD

**Issue by Shivangisingh06** [kivy/kivy#5897]
### Versions

* Python:3.6.5
* OS: Windows 10 64-bit
* Kivy: v1.10.0
* Kivy installation method: pip as mentioned on Kivy installation guide

### Description

My application picks up runtime values from command line to plot a graph and keeps updating ymax and ymin as per the runtime values .
If similar values starts appearing kivy garden graph throws an  'ZeroDivisionError: float division by zero'.

### Code and Logs

[INFO   ] [Logger      ] Record log in C:\Users\ssingh\.kivy\logs\kivy_18-08-14_24.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 391.03'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'Quadro P1000/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
YUV 422
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\ssingh\source\repos\KivyGuiChanges\KivyGui\mvPCIeBandwidthGUI.py", line 622, in <module>
     mvPCIeBandwidthGUIApp().run()
   File "C:\Users\ssingh\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Users\ssingh\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\ssingh\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
     self._mainloop()
   File "C:\Users\ssingh\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "C:\Users\ssingh\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 339, in idle
     Clock.tick()
   File "C:\Users\ssingh\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\clock.py", line 581, in tick
     self._process_events()
   File "kivy\_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7700)
   File "kivy\_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7577)
   File "kivy\_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7498)
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
   File "C:\Users\ssingh\.kivy\garden\garden.graph\__init__.py", line 1164, in draw
     self.plot_mesh()
   File "C:\Users\ssingh\.kivy\garden\garden.graph\__init__.py", line 1167, in plot_mesh
     points = [p for p in self.iterate_points()]
   File "C:\Users\ssingh\.kivy\garden\garden.graph\__init__.py", line 1167, in <listcomp>
     points = [p for p in self.iterate_points()]
   File "C:\Users\ssingh\.kivy\garden\garden.graph\__init__.py", line 1127, in iterate_points
     y_px = self.y_px()
   File "C:\Users\ssingh\.kivy\garden\garden.graph\__init__.py", line 1049, in y_px
     ratioy = (size[3] - size[1]) / float(ymax - ymin)
 ZeroDivisionError: float division by zero
Press any key to continue . . .

**Comment by matham** [comment]
Please open issues relating to graph in the https://github.com/kivy-garden/garden.graph/ repo because it's not a Kivy builtin widget. Also, please provide a complete and minimal example to reproduce the issue there.
