### ISSUE TITLE
GridLayout crash with multiple child using size_hint_min/max

### ISSUE THREAD

**Issue by tito** [kivy/kivy#5906]
### Versions

* Python: 2.7.13
* OS: Arch linux
* Kivy: v1.10.1.dev0, git-c6d5565, 20180412
* Kivy installation method: setup.py

### Description

If you try to use `size_hint_max_y` in multiple child in a GridLayout, it breaks.

### Code and Logs

```python
from kivy.lang import Builder
from kivy.base import runTouchApp

runTouchApp(Builder.load_string("""
GridLayout:
    cols: 3
    GridLayout:
        rows: 1
        size_hint_max_y: dp(120)
    GridLayout:
        rows: 1
        size_hint_max_y: dp(120)
"""))
```

The backtrace:
```
 Traceback (most recent call last):
   File "test.py", line 13, in <module>
     """))
   File "/home/tito/code/kivy/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/tito/code/kivy/kivy/core/window/window_sdl2.py", line 723, in mainloop
     self._mainloop()
   File "/home/tito/code/kivy/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/home/tito/code/kivy/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/home/tito/code/kivy/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:8143)
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7903)
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7824)
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3542)
   File "/home/tito/code/kivy/kivy/uix/gridlayout.py", line 509, in do_layout
     self._fill_rows_cols_sizes()
   File "/home/tito/code/kivy/kivy/uix/gridlayout.py", line 366, in _fill_rows_cols_sizes
     rows_sh_max[col] = nmin(rows_sh_max[col], shh_max)
 IndexError: list index out of range
```

**Comment by matham** [comment]
This should have been fixed in https://github.com/kivy/kivy/pull/5788.
