### ISSUE TITLE
"Exception ignored" (suppressed) (should crash)

### ISSUE THREAD

**Issue by ShadowLNC** [kivy/kivy#5942]
### Versions

* Python: 3.6.6
* OS: Windows 10 x64 (1803, build 17134.285)
* Kivy: 1.10.1
* Kivy installation method: Pip

Output from `pip freeze`:
```
certifi==2018.8.13
chardet==3.0.4
docutils==0.14
idna==2.7
Kivy==1.10.1
Kivy-Garden==0.1.4
kivy.deps.glew==0.1.10
kivy.deps.sdl2==0.1.18
Pygments==2.2.0
requests==2.19.1
urllib3==1.23
```

### Description

Any exception raised upon the change of a TextInput (via the callback pattern) is suppressed.

I would expect the program to crash; the fact that the program does not crash means I was only able to notice the bug by viewing the logs.

### Code and Logs

```python
import shutil

import kivy
import kivy.app

from kivy.lang import Builder
from kivy.logger import Logger
from kivy.uix.boxlayout import BoxLayout

from kivy.config import Config
Config.set('kivy', 'log_level', 'debug')

Builder.load_string("""
<View>:
    file: file
    orientation: 'horizontal'

    TextInput:
        id: file
        hint_text: "File path"
        multiline: False
        on_text: root.callback_text()
""")


class View(BoxLayout):
    def callback_text(self):
        Logger.debug("View: Text")
        if self.file.text:
            # The if statement works around Kivy bug #3588
            # (it does indeed terminate on an exception in the setup phase).
            # shutil.copyfile(self.file.text, "testfile")  # Errors suppressed.
            raise ValueError("All Exception subclasses suppressed.")


class MyApp(kivy.app.App):
    def build(self):
        Logger.debug("App: build")
        return View()


if __name__ == '__main__':
    Logger.debug("App: run")
    MyApp().run()
```

The traceback is printed in the console/logs when it is suppressed. In the logs, each of these lines is prefixed with `[WARNING] stderr:` (but not in the console).

```
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1449, in kivy.properties.AliasProperty.trigg
er_change
   File "kivy\properties.pyx", line 1455, in kivy.properties.AliasProperty.trigg
er_change
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "D:\Professional\importrandom\overwatch-scoreboard\venv\lib\site-package
s\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 10, in <module>
   File "repro2.py", line 33, in callback_text
     raise ValueError("All Exception subclasses suppressed.")
 ValueError: All Exception subclasses suppressed.
```

It seems like [others](https://stackoverflow.com/questions/47453637/stop-kivy-from-ignoring-exceptions) may have encountered [similar issues](https://groups.google.com/forum/#!topic/kivy-users/yIx4auIYBTg).

**Comment by matham** [comment]
This is because the callback is called through cython, which eats all exceptions, I agree this should be changed, but it would require going through all cython code and make sure is passes exceptions upwards.

**Comment by tshirtman** [comment]
We could make it opt-in before that, via configuration.

**Comment by tshirtman** [comment]
Actually, this cython code is supposed to raise if 2 is returned, 
https://github.com/kivy/kivy/blob/ac292250295fa9b21234e8bd45d80b095ae83e47/kivy/_event.pyx#L1140-L1141

not sure how that result is supposed to be returned, res is never assigned to 2, i'm trying to see how it's supposed to be used there.

**Comment by matham** [comment]
@tshirtman The idea is not for us to return 2 on error. Rather, if there's an error in the function, cython will catch it and return 2. That way, cython has a way to propagate errors upwards because cython inspects the return value and if it's 2 will raise the exception to python.

You can read about it here: https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values.
