### ISSUE TITLE
the camera example does not work under ubuntu16

### ISSUE THREAD

**Issue by XCfor** [kivy/kivy#6052]
### Versions

* Python: 2.7
* OS: ubuntu 16
* Kivy: 1.10.1
* Kivy installation method: ppa

### Description
the camera example does not work under ubuntu16 but my camera is well
### Code and Logs
```python
''''
Camera Example
==============

This example demonstrates a simple use of the camera. It shows a window with
a buttoned labelled 'play' to turn the camera on and off. Note that
not finding a camera, perhaps because gstreamer is not installed, will
throw an exception during the kv language processing.

'''

# Uncomment these lines to see all the messages
# from kivy.logger import Logger
# import logging
# Logger.setLevel(logging.TRACE)

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
import time
Builder.load_string('''
<CameraClick>:
    orientation: 'vertical'
    Camera:
        id: camera
		resolution: (640, 480)
        play: False

    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()
''')
class CameraClick(BoxLayout):
    def capture(self):
        '''
        Function to capture the images and give them the names
        according to their captured time and date.
        '''
        camera = self.ids['camera']
        timestr = time.strftime("%Y%m%d_%H%M%S")
        camera.export_to_png("IMG_{}.png".format(timestr))
        print("Captured")
class TestCamera(App):

    def build(self):
        return CameraClick()
TestCamera().run()
```

log: AttributeError: 'NoneType' object has no attribute 'set_state'

thank you for replay

**Comment by tshirtman** [comment]
please provide the full log, not just the latest line.

**Comment by XCfor** [comment]
thanks a lot for your reply , the whole log is as below:
Traceback (most recent call last):
   File "main.py", line 60, in <module>
     TestCamera().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "main.py", line 57, in build
     return CameraClick()
   File "/usr/lib/python2.7/dist-packages/kivy/uix/boxlayout.py", line 131, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 348, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 469, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 630, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 6:
 ...
       4:    Camera:
       5:        id: camera
 >>    6:        resolution: (640, 480)
       7:        play: False
       8:
 ...
 Error: gst_parse_error: no element "v4l2src" (1)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 623, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1236)
   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__ (kivy/properties.c:5202)
   File "kivy/properties.pyx", line 817, in kivy.properties.ListProperty.set (kivy/properties.c:11372)
   File "kivy/properties.pyx", line 524, in kivy.properties.Property.set (kivy/properties.c:6028)
   File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch (kivy/properties.c:6709)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (kivy/_event.c:13525)
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch (kivy/_event.c:12724)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/camera.py", line 103, in _on_index
     resolution=self.resolution, stopped=True)
   File "/usr/lib/python2.7/dist-packages/kivy/core/camera/camera_gi.py", line 65, in __init__
     super(CameraGi, self).__init__(**kwargs)
   File "/usr/lib/python2.7/dist-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/usr/lib/python2.7/dist-packages/kivy/core/camera/camera_gi.py", line 89, in init_camera
     self._pipeline = Gst.parse_launch(pl.format(video_src, caps))
 
 Error in atexit._run_exitfuncs:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
     func(*targs, **kargs)
   File "/usr/lib/python2.7/dist-packages/kivy/core/camera/camera_gi.py", line 169, in camera_gi_clean
     camera.stop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/camera/camera_gi.py", line 123, in stop
     self._pipeline.set_state(Gst.State.PAUSED)
 AttributeError: 'NoneType' object has no attribute 'set_state'
 Error in sys.exitfunc:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
     func(*targs, **kargs)
   File "/usr/lib/python2.7/dist-packages/kivy/core/camera/camera_gi.py", line 169, in camera_gi_clean
     camera.stop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/camera/camera_gi.py", line 123, in stop
     self._pipeline.set_state(Gst.State.PAUSED)
 AttributeError: 'NoneType' object has no attribute 'set_state'

**Comment by tshirtman** [comment]
That's the whole traceback, not the whole log, it's better, but not necessarily enough.

**Comment by Enkumicahel** [comment]
@tshirtman can you please help with this issue. I am also facing the same error:

```
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
 /usr/lib/python2.7/dist-packages/kivy/core/camera/camera_gi.py:10: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
   from gi.repository import Gst
```

**Comment by tito** [comment]
Camera works under Ubuntu. What you may have is likely missing some gstreamer package. If you get it working with gstreamer, then it will work in Kivy.
