### ISSUE TITLE
Python 3.7 Filechooser error

### ISSUE THREAD

**Issue by ImperialStranger** [kivy/kivy#6084]
### Versions

* Python: 3.7.1
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: PIP

### Description

When I run kivy filechooser it runs succesfully but shows error 'pywintypes error'.

### Code and Logs

```python
[INFO   ] [Logger      ] Record log in C:\Users\farha\.kivy\logs\kivy_18-12-23_121.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 388.43'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GT 1030/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[ERROR  ] unable to access to <\hiberfil.sys>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\kivy\uix\filechooser.py", line 178, in is_hidden
    return GetFileAttributesEx(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[ERROR  ] unable to access to <\pagefile.sys>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\kivy\uix\filechooser.py", line 178, in is_hidden
    return GetFileAttributesEx(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[ERROR  ] unable to access to <\swapfile.sys>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\kivy\uix\filechooser.py", line 178, in is_hidden
    return GetFileAttributesEx(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[INFO   ] [GL          ] NPOT texture support is available
[ERROR  ] unable to access to <\hiberfil.sys>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\kivy\uix\filechooser.py", line 178, in is_hidden
    return GetFileAttributesEx(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[ERROR  ] unable to access to <\pagefile.sys>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\kivy\uix\filechooser.py", line 178, in is_hidden
    return GetFileAttributesEx(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
[ERROR  ] unable to access to <\swapfile.sys>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\kivy\uix\filechooser.py", line 178, in is_hidden
    return GetFileAttributesEx(fn)[0] & FILE_ATTRIBUTE_HIDDEN
pywintypes.error: (32, 'GetFileAttributesEx', 'The process cannot access the file because it is being used by another process.')
```

**Comment by johnvorsten** [comment]
This is related to issue #5873

**Comment by shashi278** [comment]
Been using Filechooser since a while but never came across such issue. Seems like kind of permission issues. Consider providing snippet to reproduce the problem.

**Comment by LegionBG** [comment]
This is trying to read every possible file to build the folders tree, therfore it's going through the whole system. These files are meant to be locked and not accessible as it can cause all sorts of issues, hence you get the error. Don't worry about it, but don't give it access anyway.

**Comment by Stephen528** [comment]
Is there any plan to resolve this? It does not present well when it prints "ERROR" on the console.

**Comment by Unknown807** [comment]
I put this as the file chooser's filter parameter and the errors don't come up anymore
`filters: ["!*.sys"]`
