### ISSUE TITLE
Svg constructor problem

### ISSUE THREAD

**Issue by AndreMPCosta** [kivy/kivy#6101]
### Versions

* Python: v3.7.0b4 
* OS: Deepin (Debian)
* Kivy: v1.11.0.dev0, git-372b819, 20190104

### Description

I was trying to load a svg file, but I encountered this problem: (Note: Kivy 1.10.1 is working, that's what I'm running on android)
### Code and Logs

```python
class GymCard(Scatter):

    def __init__(self, filename, **kwargs):
        super().__init__(**kwargs)
        with self.canvas:
            svg = Svg(filename=filename)
        self.size = svg.width, svg.height

```

Just creating a new object:
```python
self.gymcard = GymCard('./assets/card.svg')
```

Returns:
```
Traceback (most recent call last):
   File "/home/andre/playapp/main.py", line 51, in <module>
     app.run()
   File "/usr/local/lib/python3.7/dist-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/usr/local/lib/python3.7/dist-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python3.7/dist-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
     self._mainloop()
   File "/usr/local/lib/python3.7/dist-packages/kivy/core/window/window_pygame.py", line 289, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python3.7/dist-packages/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/usr/local/lib/python3.7/dist-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/home/andre/playapp/screens.py", line 32, in <lambda>
     Clock.schedule_once(lambda x: self.delayed_init())
   File "/home/andre/playapp/screens.py", line 47, in delayed_init
     self.add_gym_card()
   File "/home/andre/playapp/screens.py", line 55, in add_gym_card
     self.gymcard = GymCard('./assets/card.svg')
   File "/home/andre/playapp/widgets/custom_widgets.py", line 56, in __init__
     svg = Svg(filename=filename)
   File "kivy/graphics/svg.pyx", line 419, in kivy.graphics.svg.Svg.__init__
 AttributeError: 'kivy.graphics.svg.Svg' object has no attribute '_filename'
```

**Comment by ssolari** [comment]
@AndreMPCosta just use file name as a positional argument and it should work
```
with self.canvas:
    svg = Svg(filename)
```

not sure, but it seems the word ```filename``` is overloaded in several places in the Svg object as below and this is probably causing the issue using keywords

https://github.com/kivy/kivy/blob/8b6af301e453e3cdded6fa34c0a64e1c3e55c7aa/kivy/graphics/svg.pyx#L482-L491
