### ISSUE TITLE
[Kivy v1.10.1] no module nqmed 'kivy.__clock' 

### ISSUE THREAD

**Issue by par3kh** [kivy/kivy#6147]
i installed kivy from windows 10 and when i use it this error shows up can anyone please help me. I've tried reinstalling everything and it still doesn't work

[INFO   ] [Logger      ] Record log in C:\Users\parek\.kivy\logs\kivy_19-02-09_8.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
 Traceback (most recent call last):
   File "C:/Users/parek/Desktop/Python/App.py", line 17, in <module>
     from kivy.app import App
   File "C:\Users\parek\AppData\Roaming\Python\Python37\site-packages\kivy\app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "C:\Users\parek\AppData\Roaming\Python\Python37\site-packages\kivy\base.py", line 26, in <module>
     from kivy.clock import Clock
   File "C:\Users\parek\AppData\Roaming\Python\Python37\site-packages\kivy\clock.py", line 362, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ModuleNotFoundError: No module named 'kivy._clock'

**Comment by tito** [comment]
Look like you have installed then from source and you didn't compiled. Explain what you did in the support channel if you want help!
