### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by PtmDex** [kivy/kivy#6154]
After installing modules, I followed instructions to build an apk file.
My app uses gspread and oauth2client. Put all the requirements in the buildozer.spec file.
I run `buildozer android debug deploy run logcat` then the application crash after loading screen.
The first thing I think the problem is it can't find "libpython3.5m.so", "libpython3.6m.so", "libpython3.7m.
Here is the link for the log and the buildozer.spec file. [buildozer.spec](http://www.mediafire.com/file/129d59jdb5w4w38/buildozer.spec/file)   [log file](http://www.mediafire.com/file/of2qg23a1jhnanm/log.txt/file)

Please help me thanks T_T.

**Comment by tito** [comment]
```
02-11 14:04:05.995 16676 16676 I zygote  : The ClassLoaderContext is a special shared library.
02-11 14:04:06.022 16530 16664 I python  :  Traceback (most recent call last):
02-11 14:04:06.022 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/app/main.py", line 11, in <module>
02-11 14:04:06.023 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/platform/build/build/python-installs/avacremote/oauth2client/service_account.py", line 26, in <module>
02-11 14:04:06.024 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/platform/build/build/python-installs/avacremote/oauth2client/crypt.py", line 23, in <module>
02-11 14:04:06.025 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/platform/build/build/python-installs/avacremote/oauth2client/_pure_python_crypt.py", line 22, in <module>
02-11 14:04:06.026 16530 16664 I python  :  ImportError: No module named pyasn1.codec.der
02-11 14:04:06.026 16530 16664 I python  : Python for android ended.
```

You're missing pyasn1.
