### ISSUE TITLE
MacOS: Clipboard nspaste make app crash when copying text

### ISSUE THREAD

**Issue by Thong-Tran** [kivy/kivy#6170]
### Versions

* Python: 3.7.1
* OS: MacOS 10.13.6
* Kivy: 1.10.1
* Kivy installation method: pypi

### Description

When I try copy text in TextInput, this make app crash. But paste is OK.

### Code and Logs

```log
Traceback (most recent call last):
   File "main.py", line 56, in <module>
     app.run()
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 662, in _mainloop
     self.modifiers):
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/core/window/__init__.py", line 162, in _on_window_key_down
     return self.dispatch('on_key_down', keycode, text, modifiers)
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/uix/textinput.py", line 2434, in keyboard_on_key_down
     self.copy()
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/uix/textinput.py", line 1727, in copy
     return Clipboard.copy(self.selection_text)
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/core/clipboard/__init__.py", line 73, in copy
     self._copy(data)
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/core/clipboard/__init__.py", line 87, in _copy
     self.put(data, self._clip_mime_type)
   File "/Users/ivc/kivy/.env3/lib/python3.7/site-packages/kivy/core/clipboard/clipboard_nspaste.py", line 40, in put
     pb.writeObjects_([data])
   File "pyobjus/pyobjus.pyx", line 393, in pyobjus.ObjcMethod.__call__
   File "pyobjus/pyobjus_conversions.pxi", line 617, in pyobjus.convert_py_arg_to_cy
   File "pyobjus/pyobjus_conversions.pxi", line 441, in pyobjus.convert_py_to_nsobject
   File "pyobjus/pyobjus.pyx", line 393, in pyobjus.ObjcMethod.__call__
   File "pyobjus/pyobjus_conversions.pxi", line 617, in pyobjus.convert_py_arg_to_cy
   File "pyobjus/pyobjus_conversions.pxi", line 452, in pyobjus.convert_py_to_nsobject
   File "pyobjus/pyobjus.pyx", line 974, in pyobjus.objc_create_delegate
 pyobjus.ObjcException: You've passed b'kivyproject' as delegate, but there is no @protocol methods declared.
```

**Comment by tito** [comment]
You got a bug :)
In the meantime, you can avoid it by using `KIVY_CLIPBOARD=sdl2` as a environemnt variable.

Thanks for reporting!

**Comment by Thong-Tran** [comment]
😂 Thank, I already used this setting instead of it.
