### ISSUE TITLE
Action Bar Overflow Fails to Add Widget Because Widget Added Already Has Parent

### ISSUE THREAD

**Issue by amrosado** [kivy/kivy#6184]
### Versions

* Python: 3.7.
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: pip

### Code and Logs

```python
class FrontEnd(App):
    def build(self):
        tabbedPannel = TabbedPanel()

        analyseRawPanel = TabbedPanelItem(text='Analyze Raw')
        analyzePanel = TabbedPanelItem(text='Analyze')
        exportPanel = TabbedPanelItem(text='Export')

        fullBox = GridLayout(cols=3)

        analyseRawPanel.add_widget(fullBox)

        cycleInfoBox = GridLayout(cols=1, size_hint_max_x=300)
        signalFigureBox = GridLayout(cols=1, rows=2)
        filteredSignalBox = GridLayout(cols=1, rows=2)

        fullBox.add_widget(cycleInfoBox)
        fullBox.add_widget(signalFigureBox)
        fullBox.add_widget(filteredSignalBox)

        nav1 = NavigationToolbar2Kivy(canvas)
        nav2 = NavigationToolbar2Kivy(canvas2)
        #
        # for child in nav1.actionbar.children:
        #     for subChild in child.children:
        #         if hasattr(subChild, 'icon'):
        #             subChild.icon = subChild.icon[:len(subChild.icon)-3] + 'svg'
        #
        # for child in nav2.actionbar.children:
        #     for subChild in child.children:
        #         if isinstance(subChild, ActionButton):
        #             pass

        chooseBaseFileDirLabel = Label(text='Choose base data directory', size_hint_y=30)
        listViewDataTypeLabel = Label(text='Choose data type to import', size_hint_y=30)

        data = [
            {
                'text': 'HAFM',
                'is_selected': True
            },
            {
                'text': 'BFP2',
                'is_selected': False
            },
            {
                'text': 'BFP1',
                'is_selected': False
            }
        ]

        argsConverter = lambda row_index, rec: {'text': rec['text'], 'size_hint_y': None, 'height': 25}
        listAdapter = ListAdapter(data=data, args_converter=argsConverter , cls=ListItemButton, selection_mode='single', allow_empty_selection=False)
        listViewDataType = ListView(adapter=listAdapter, size_hint_y=50)
        fileChooserList = FileChooserListView(dirselect=True, filters=[is_dir], size_hint_y=200)

        cycleInfoBox.add_widget(listViewDataTypeLabel)
        cycleInfoBox.add_widget(listViewDataType)
        cycleInfoBox.add_widget(chooseBaseFileDirLabel)
        cycleInfoBox.add_widget(fileChooserList)

        signalFigureBox.add_widget(nav1.actionbar)
        filteredSignalBox.add_widget(nav2.actionbar)

        signalFigureBox.add_widget(canvas)
        filteredSignalBox.add_widget(canvas2)

        tabbedPannel.add_widget(analyseRawPanel)
        tabbedPannel.add_widget(analyzePanel)
        tabbedPannel.add_widget(exportPanel)

        return tabbedPannel

```

When switching to tab featuring actionbars the following error is throw:

```
  Traceback (most recent call last):
   File "C:\Users\arosado\.IntelliJIdea2018.3\config\plugins\python\helpers\pydev\pydevd.py", line 1741, in <module>
     main()
   File "C:\Users\arosado\.IntelliJIdea2018.3\config\plugins\python\helpers\pydev\pydevd.py", line 1735, in main
     globals = debugger.run(setup['file'], None, None, is_module)
   File "C:\Users\arosado\.IntelliJIdea2018.3\config\plugins\python\helpers\pydev\pydevd.py", line 1135, in run
     pydev_imports.execfile(file, globals, locals)  # execute the script
   File "C:\Users\arosado\.IntelliJIdea2018.3\config\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
     exec(compile(contents+"\n", file, 'exec'), glob, loc)
   File "C:/Users/arosado/GitHub/HAFM/FrontEnd.py", line 118, in <module>
     FrontEnd().run()
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\app.py", line 826, in run
     runTouchApp()
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\base.py", line 346, in idle
     Clock.tick_draw()
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\clock.py", line 588, in tick_draw
     self._process_events_before_frame()
   File "kivy\_clock.pyx", line 427, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 467, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 465, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\uix\boxlayout.py", line 309, in do_layout
     c.size = (w, h)
   File "kivy\properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 1341, in kivy.properties.ReferenceListProperty.set
   File "kivy\properties.pyx", line 502, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\uix\actionbar.py", line 758, in on_width
     self._layout_random()
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\uix\actionbar.py", line 707, in _layout_random
     super_add(child, group_index)
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\uix\boxlayout.py", line 314, in add_widget
     return super(BoxLayout, self).add_widget(widget, index, canvas)
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\uix\layout.py", line 97, in add_widget
     return super(Layout, self).add_widget(widget, index, canvas)
   File "C:\Users\arosado\Envs\HAFM\lib\site-packages\kivy\uix\widget.py", line 531, in add_widget
     % (widget, parent))
 kivy.uix.widget.WidgetException: Cannot add <kivy.uix.actionbar.ActionSeparator object at 0x000001CB771AD868>, it already has a parent <kivy.uix.actionbar.ActionOverflow object at 0x000001CB771AD118>

```
The following changes to box layout corrects this error:

```python
    def add_widget(self, widget, index=0, canvas=None):
        widget.fbind('pos_hint', self._trigger_layout)
        widget.parent = None
        return super(BoxLayout, self).add_widget(widget, index, canvas)
```

**Comment by amrosado** [comment]
Is there anyone looking into this at all?

**Comment by zhuchangzhan** [comment]
Having the same problem

**Comment by amrosado** [comment]
I haven't heard anything about this in a long time.  I suggest just figuring a work around that is best for your GUI.

**Comment by yves-surrel** [comment]
The `ActionOverflow` widget is not supposed to contain any `ActionSeparator`, as shown by its overloaded `add_widget` method.

But in `ActionView._layout_random()` (in the very last lines), items in hidden_items are added to `overflow_group` (which is an `ActionOverflow` widget) using the inherited `add_widget` method, not the overloaded one.

So, in `ActionView._layout_random()`, it is necessary to prevent `overflow_group` to receive any `ActionSeparator`, so it is necessary to replace:
```
over_add(child)
```
by
```
if not isinstance(child, ActionSeparator):
    over_add(child)
```
