### ISSUE TITLE
./gradlew not found

### ISSUE THREAD

**Issue by mahlangudf** [kivy/kivy#6262]
I was trying to build my app using Buildozer. This is the error I got. How can I solve this?

WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No compiled python is present to zip, skipping.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
Warning: failed to apply patch (exit code 1), assuming it is already applied: src/patches/SDLActivity.java.patch
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/daniel/Desktop/isindebeleonline/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1081, in <module>
    main()
  File "/home/daniel/Desktop/isindebeleonline/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1075, in main
    ToolchainCL()
  File "/home/daniel/Desktop/isindebeleonline/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 577, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/daniel/Desktop/isindebeleonline/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 152, in wrapper_func
    func(self, args)
  File "/home/daniel/Desktop/isindebeleonline/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 874, in apk
    gradlew = sh.Command('./gradlew')
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1202, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: ./gradlew

**Comment by robertpro** [comment]
what is the command you ran? and also you should open the issue on [Buildozer repository](https://github.com/kivy/buildozer/issues/new)
