### ISSUE TITLE
buildozer download kivy without checking kivy installed on OS(ubuntu), and downloading kivy in buildozer get error{  http.client.IncompleteRead: IncompleteRead(0 bytes read)}

### ISSUE THREAD

**Issue by GitHub9800** [kivy/kivy#6307]
### Versions

* Python:python3.6
* OS:ubuntu
* Kivy:
* Kivy installation method:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Code and Logs
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1186, in <module>
    main()
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1180, in main
    ToolchainCL()
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 663, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 152, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 205, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 536, in build_recipes
    recipe.download_if_necessary()
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 297, in download_if_necessary
    self.download()
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 343, in download
    self.download_file(self.versioned_url, filename)
  File "/mnt/e/008p4a/py2android/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 158, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python3.6/urllib/request.py", line 1819, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 483, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.6/http/client.py", line 594, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3crystax,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/mnt/e/008p4a/py2android/.buildozer/android/platform/build" --ndk-api=21
#
# Buildozer failed to execute the last command

```python
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.

```

**Comment by haihit** [comment]
is this issue fixed? i meet the same issue
