### ISSUE TITLE
Kivy 1.11.0 and PyInstaller

### ISSUE THREAD

**Issue by onslauth** [kivy/kivy#6358]
### Versions

* Python: 3.6.5
* OS: OSx
* Kivy: 1.11.0
* Kivy installation method: pip

### Description

Kivy pyinstaller hook script fails, please see traceback below:

### Logs

```
$ python3 -m kivy.tools.packaging.pyinstaller_hooks hook ./kivy-hooks
[INFO   ] [Logger      ] Record log in /Users/xxx/.kivy/logs/kivy_19-06-03_16.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.5 (default, May  7 2018, 14:48:21) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
[INFO   ] [Python      ] Interpreter at "/usr/local/opt/python/bin/python3.6"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Logger      ] Record log in /Users/xxx/.kivy/logs/kivy_19-06-03_17.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.5 (default, May  7 2018, 14:48:21) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
[INFO   ] [Python      ] Interpreter at "/usr/local/opt/python/bin/python3.6"
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "/usr/local/lib/python3.6/site-packages/kivy/tools/packaging/pyinstaller_hooks/__main__.py", line 11, in <module>
     lines = get_deps_all()['hiddenimports']
   File "/usr/local/lib/python3.6/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 275, in get_deps_all
     'binaries': _find_gst_binaries(),
   File "/usr/local/lib/python3.6/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 354, in _find_gst_binaries
     gst_plugin_path = _find_gst_plugin_path()
   File "/usr/local/lib/python3.6/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 342, in _find_gst_plugin_path
     match = re.search(r'\s+(\S+libgstcoreelements\.\S+)', stdoutdata)
   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 182, in search
     return _compile(pattern, flags).search(string)
 TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by matham** [comment]
This is caused by https://github.com/kivy/kivy/pull/6165. I'm guessing it was only tested on py2.

**Comment by matham** [comment]
Can you test https://github.com/kivy/kivy/pull/6359 to see if it fixes it? Just edit the changed kivy files in place to see if it fixes it, as I don't have access to osx to test.

**Comment by onslauth** [comment]
@matham - Thank you for the help. I will test this evening and let you know if its fixed.

**Comment by onslauth** [comment]
@matham: The fix sorted out one problem, but there is one further down.

### Logs
```
 Traceback (most recent call last):
   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "/usr/local/lib/python3.6/site-packages/kivy/tools/packaging/pyinstaller_hooks/__main__.py", line 11, in <module>
     lines = get_deps_all()['hiddenimports']
   File "/usr/local/lib/python3.6/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 275, in get_deps_all
     'binaries': _find_gst_binaries(),
   File "/usr/local/lib/python3.6/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 359, in _find_gst_binaries
     glob.glob(os.path.join(plugin_dir, 'libgst*')))
   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 94, in join
     genericpath._check_arg_types('join', a, *p)
   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/genericpath.py", line 151, in _check_arg_types
     raise TypeError("Can't mix strings and bytes in path components") from None
 TypeError: Can't mix strings and bytes in path components
```

**Comment by onslauth** [comment]
@matham 

In: _kivy/tools/packaging/pyinstaller_hooks/__init__.py_ on line 359:
```
             glob.glob(os.path.join(str(plugin_dir), 'libgst*')))
```

That solves the problem.

**Comment by matham** [comment]
I fixed it in a slightly different way, if you want to test again: https://github.com/kivy/kivy/pull/6359/files#diff-e61315f416494d54c2e1abef9727c362. Please note that I removed my original changes.

**Comment by onslauth** [comment]
@matham That fix seems to work fine without any problems.

Thank you for all the help.
