### ISSUE TITLE
TypeError on Carousel slides creation

### ISSUE THREAD

**Issue by Inspirateur** [kivy/kivy#6361]
### Versions

* Python: 3.7
* OS: Windows 10
* Kivy: 1.11.0
* Kivy installation method: pip

### Description

I'm creating slides for a Carousel at runtime and each slides give me this error (which prevents them to load):
```
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
   File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\carousel.py", line 194, in _curr_slide
     return self.slides[self.index]
 TypeError: list indices must be integers or slices, not NoneType
[INFO   ] [GL          ] Unpack subimage support is available
[INFO   ] [Base        ] Leaving application in progress...
[INFO   ] [WindowSDL   ] exiting mainloop and closing.
```
My code isn't in the stack trace, here's the kivy code the error makes me jump to:
```python
    def _curr_slide(self):
        if len(self.slides):
            return self.slides[self.index]

    current_slide = AliasProperty(_curr_slide,
                                  bind=('slides', 'index'),
                                  cache=True)
    '''The currently shown slide.

    :attr:`current_slide` is an :class:`~kivy.properties.AliasProperty`.

    .. versionchanged:: 1.5.0
        The property no longer exposes the slides container. It returns
        the widget you have added.
    '''
```

Please note that my Carousel worked fine in version 1.10.1 (the one I used just before trying this new one).

**Comment by 20Tauri** [comment]
This clones https://github.com/kivy/kivy/issues/6345

**Comment by Inspirateur** [comment]
whoops my bad, github didn't show me this one when I wanted to create mine :x 
It seems like it is the same issue indeed
