### ISSUE TITLE
'Carousel.remove_widget()' causes IndexError when the last slide is active, and the error is not delivered to a user

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy/kivy#6370]
### Versions

* Python: 3.7.1
* OS: Linux Mint 18.2
* Kivy:  v2.0.0.dev0, git-e828f22
* Kivy installation method: `git clone` then `pip -e`

### Description

When a `Carousel` meets the following conditions:

- having 2 or more slides (`len(carousel.slides) >= 2`)
- the last slide is active  (`carousel.index == len(carousel.slides) - 1`)

removing any slide causes `IndexError`. The error is shown in the strerr, but can't be catched.

### Code and Logs

```python
from kivy.app import App
from kivy.factory import Factory
from kivy.clock import Clock
import random


N_SLIDES = random.choice(range(2, 4))  # Has to be 2 or greater

class SampleApp(App):
    def build(self):
        c = Factory.Carousel()
        for i in range(N_SLIDES):
            c.add_widget(Factory.Label(text=str(i), font_size=100))
        c.index = N_SLIDES - 1  # switch to the last slide
        return c
    
    def on_start(self):
        c = self.root
        Clock.schedule_once(
            lambda __: c.remove_widget(random.choice(c.slides)),  # remove any slide
            c.anim_move_duration + 1)


if __name__ == '__main__':
    SampleApp().run()
```

The following errors are printed, but the app still is running and I can switch to other slide.

```
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
     ps.observers.dispatch(obj, ps.value, None, None, 0)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
     result = self._dispatch(
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
     return f(obj, value)
   File "kivy/properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
     cpdef trigger_change(self, EventDispatcher obj, value):
   File "kivy/properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
     dvalue = ps.getter(obj)
   File "/tmp/firefox/kivy/kivy/uix/carousel.py", line 194, in _curr_slide
     return self.slides[self.index or 0]
 IndexError: list index out of range
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
     ps.observers.dispatch(obj, ps.value, None, None, 0)
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
     result = self._dispatch(
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
     return f(obj, value)
   File "kivy/properties.pyx", line 1503, in kivy.properties.AliasProperty.trigger_change
     cpdef trigger_change(self, EventDispatcher obj, value):
   File "kivy/properties.pyx", line 1505, in kivy.properties.AliasProperty.trigger_change
     dvalue = ps.getter(obj)
   File "/tmp/firefox/kivy/kivy/uix/carousel.py", line 194, in _curr_slide
     return self.slides[self.index or 0]
 IndexError: list index out of range
```

#### pytest

```python
import pytest


@pytest.fixture(
    scope='session', params=(True, False), ids=lambda v: 'loop=' + str(v))
def loop(request):
    return request.param


@pytest.fixture(
    scope='session', params=tuple(range(5)),
    ids=lambda v: 'n_slides=' + str(v))
def n_slides(request):
    return request.param


@pytest.fixture
def carousel(loop, n_slides):
    from kivy.uix.carousel import Carousel
    from kivy.uix.widget import Widget
    c = Carousel(loop=loop)
    for i in range(n_slides):
        c.add_widget(Widget())
    return c


def test_remove_a_slide_when_the_last_slide_is_active(capsys, carousel):
    import random
    if len(carousel.slides) == 0:
        pytest.skip()
    carousel.index = len(carousel.slides) - 1
    carousel.remove_widget(random.choice(carousel.slides))
    stderr_text = capsys.readouterr().err
    for line in stderr_text.split('\n'):
        assert not line.startswith('IndexError:')


if __name__ == "__main__":
    pytest.main(args=[
        __file__,
    ])
```

**Comment by Benjelino** [comment]
I wrote this code to by-pass the Index Error Exception and also made the clear_widgets() function much more faster.
   def remove_carousel():
        if carousel.previous_slide is None:
            carousel.clear_widgets()
        else:
            carousel.anim_move_duration = 0
            self.carousel.load_slide(carousel.slides[0])
            timer()

    def timer(self):
        t = Timer(0.000000001, self.remove_carousel)
        t.start()
