### ISSUE TITLE
Can't use ListView after update

### ISSUE THREAD

**Issue by NicolaM94** [kivy/kivy#6386]
As the title says, after updating Kivy from 1.10.x to 1.11.0 I can't use the class ListView anymore.
Was it removed with the new version or is it just a problem of mine?

Here's my error record:

[INFO   ] [Logger      ] Record log in C:\Users\Nicola\.kivy\logs\kivy_19-06-16_5.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\python.exe"
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 430.86'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1050 Ti/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "c:/Users/Nicola/Desktop/WeatherApp/main.py", line 7, in <module>
     WeatherApp().run()
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\app.py", line 828, in run
     self.load_kv(filename=self.kv_file)
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\app.py", line 599, in load_kv
     root = Builder.load_file(rfilename)
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 402, in load_string
     root=widget, rule_children=rule_children)
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
     rule_children=rule_children)
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 538, in apply
     rule_children=rule_children)
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 616, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Users\Nicola\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\factory.py", line 131, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <ListView>

**Comment by AndreMiras** [comment]
Yes good guess `ListView` was removed in favor of `RecycleView`, see changelog https://github.com/kivy/kivy/releases/tag/1.11.0 and PR https://github.com/kivy/kivy/pull/5968
