### ISSUE TITLE
Outlined Text Not Displaying Correctly on Raspberry Pi

### ISSUE THREAD

**Issue by DanTheMan2000** [kivy/kivy#6421]
### Versions

* Python: v3.5.3
* OS: Linux raspberrypi 4.19.57-v7
* Kivy: 1.11.1
* Kivy installation method: pip3 install kivy

### Description
See the images below. The outlined text displays correctly on Windows,  but does not display correctly on Linux. The text does not "fill in" with solid white.

Running on Windows:
![Running on Windows](https://user-images.githubusercontent.com/52839433/61320427-037b6c80-a7cf-11e9-8a1c-f3ce8212170d.png)

Running on Raspberry Pi:
![Running on Raspberry Pi](https://user-images.githubusercontent.com/52839433/61320452-0ece9800-a7cf-11e9-955e-a7aed0f305b5.jpg)

### Code and Logs

```python
from kivy import Config
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label

Config.set('kivy', 'log_level', 'trace')
Config.write()


class TestApp(App):

    def build(self):
        b = BoxLayout(orientation='vertical')
        label1 = Label(text='Regular Text', font_size='100dp', bold=True)
        label2 = Label(text='Outlined Text', outline_width=4, outline_color=(1, 0, 0, 0), font_size='100dp', bold=True)
        b.add_widget(label1)
        b.add_widget(label2)
        return b


TestApp().run()
```

```
[INFO   ] [Logger      ] Record log in /var/log/fbd/fbd_19-07-16_14.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.5/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[TRACE  ] [Lang        ] load file /usr/local/lib/python3.5/dist-packages/kivy/data/style.kv
[TRACE  ] [Parser      ] parsing 1295 lines
[TRACE  ] [Parser      ] got directive <kivy 1.0>
[TRACE  ] [Builder     ] build rule for <Label>
[TRACE  ] [Builder     ] build rule for <-Button,-ToggleButton>
[TRACE  ] [Builder     ] build rule for <BubbleContent>
[TRACE  ] [Builder     ] build rule for <BubbleButton>
[TRACE  ] [Builder     ] build rule for <Slider>
[TRACE  ] [Builder     ] build rule for <ProgressBar>
[TRACE  ] [Builder     ] build rule for <SplitterStrip>
[TRACE  ] [Builder     ] build rule for <Scatter>
[TRACE  ] [Builder     ] build rule for <RelativeLayout>
[TRACE  ] [Builder     ] build rule for <Image,AsyncImage>
[TRACE  ] [Builder     ] build rule for <EffectWidget>
[TRACE  ] [Builder     ] build rule for <TabbedPanelContent>
[TRACE  ] [Builder     ] build rule for <TabbedPanelStrip>
[TRACE  ] [Builder     ] build rule for <StripLayout>
[TRACE  ] [Builder     ] build rule for <TabbedPanelHeader>
[TRACE  ] [Builder     ] build rule for <Selector>
[TRACE  ] [Builder     ] build rule for <TextInput>
[TRACE  ] [Builder     ] build rule for <TextInputCutCopyPaste>
[TRACE  ] [Builder     ] build rule for <CodeInput>
[TRACE  ] [Builder     ] build rule for <TreeViewNode>
[TRACE  ] [Builder     ] build rule for <TreeViewLabel>
[TRACE  ] [Builder     ] build rule for <StencilView>
[TRACE  ] [Builder     ] build rule for <FileChooserListLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserListView>
[TRACE  ] [Builder     ] build template for [FileListEntry@FloatLayout+TreeViewNode]
[TRACE  ] [Builder     ] build rule for <FileChooserIconLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserIconView>
[TRACE  ] [Builder     ] build template for [FileIconEntry@Widget]
[TRACE  ] [Builder     ] build rule for <FileChooserProgress>
[TRACE  ] [Builder     ] build rule for <Switch>
[TRACE  ] [Builder     ] build rule for <ModalView>
[TRACE  ] [Builder     ] build rule for <Popup>
[TRACE  ] [Builder     ] build rule for <SpinnerOption>
[TRACE  ] [Builder     ] build rule for <Spinner>
[TRACE  ] [Builder     ] build rule for <ActionBar>
[TRACE  ] [Builder     ] build rule for <ActionView>
[TRACE  ] [Builder     ] build rule for <ActionSeparator>
[TRACE  ] [Builder     ] build rule for <ActionButton,ActionToggleButton>
[TRACE  ] [Builder     ] build rule for <ActionLabel>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionCheck>
[TRACE  ] [Builder     ] build rule for <ActionPreviousImage@Image>
[TRACE  ] [Builder     ] build rule for <ActionPreviousButton@Button>
[TRACE  ] [Builder     ] build rule for <ActionPrevious>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionOverflow>
[TRACE  ] [Builder     ] build rule for <ActionDropDown>
[TRACE  ] [Builder     ] build template for [AccordionItemTitle@Label]
[TRACE  ] [Builder     ] build rule for <AccordionItem>
[TRACE  ] [Builder     ] build rule for <SettingSpacer>
[TRACE  ] [Builder     ] build rule for <SettingItem>
[TRACE  ] [Builder     ] build rule for <SettingBoolean>
[TRACE  ] [Builder     ] build rule for <SettingString>
[TRACE  ] [Builder     ] build rule for <SettingPath>
[TRACE  ] [Builder     ] build rule for <SettingOptions>
[TRACE  ] [Builder     ] build rule for <SettingTitle>
[TRACE  ] [Builder     ] build rule for <SettingSidebarLabel>
[TRACE  ] [Builder     ] build rule for <SettingsPanel>
[TRACE  ] [Builder     ] build rule for <Settings>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSidebar>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSidebar>
[TRACE  ] [Builder     ] build rule for <ContentPanel>
[TRACE  ] [Builder     ] build rule for <InterfaceWithTabbedPanel>
[TRACE  ] [Builder     ] build rule for <ScrollView>
[TRACE  ] [Builder     ] build rule for <VideoPlayerPreview>
[TRACE  ] [Builder     ] build rule for <VideoPlayerAnnotation>
[TRACE  ] [Builder     ] build rule for <VideoPlayer>
[TRACE  ] [Builder     ] build rule for <CheckBox>
[TRACE  ] [Builder     ] build rule for <ScreenManager>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Input@TextInput>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Label@Label>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Selector@BoxLayout>
[TRACE  ] [Builder     ] build rule for <ColorWheel>
[TRACE  ] [Builder     ] build rule for <ColorPicker>
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[TRACE  ] [Image       ] Unable to use <gif> as loader!
[TRACE  ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/__init__.py", line 135, in core_register_libs
    level=0)
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/image/img_sdl2.py", line 11, in <module>
    from kivy.core.image import _img_sdl2
ImportError: /usr/local/lib/python3.5/dist-packages/kivy/core/image/_img_sdl2.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: IMG_SaveJPG_RW
[TRACE  ] [Image       ] Unable to use <gif> as loader!
[TRACE  ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/__init__.py", line 135, in core_register_libs
    level=0)
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/image/img_ffpyplayer.py", line 7, in <module>
    import ffpyplayer
ImportError: No module named 'ffpyplayer'
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Text        ] Provider: sdl2
[DEBUG  ] [App         ] Loading kv <Application/test.kv>
[DEBUG  ] [App         ] kv <Application/test.kv> not found
[TRACE  ] [Parser      ] parsing 19 lines
[TRACE  ] [Builder     ] build rule for <-CoverBehavior>
[INFO   ] [Window      ] Provider: egl_rpi
[DEBUG  ] [Window      ] Actual display size: 1920x1080
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[DEBUG  ] [GL          ] glShaderBinary is not available
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[TRACE  ] [Cache       ] Flushed category kv.texture from cache
[TRACE  ] [Cache       ] Flushed category kv.shader from cache
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImagePIL    ] Load </usr/local/lib/python3.5/dist-packages/kivy/data/glsl/default.png>
[TRACE  ] [Image       ] '/usr/local/lib/python3.5/dist-packages/kivy/data/glsl/default.png', populate to textures (1)
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[TRACE  ] [Lang        ] Found 0 rules for <kivy.uix.boxlayout.BoxLayout object at 0x75dc5bc8>
[TRACE  ] [Lang        ] Found 1 rules for <kivy.uix.label.Label object at 0x73d4ba40>
[DEBUG  ] [Resource    ] add </usr/share/fonts> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/dejavu> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/freefont> in path list
[DEBUG  ] [Resource    ] add </usr/local/share/fonts> in path list
[DEBUG  ] [Resource    ] add </usr/local/share/fonts/noto> in path list
[DEBUG  ] [Resource    ] add </usr/local/lib/python3.5/dist-packages/kivy/data/fonts> in path list
[TRACE  ] [Lang        ] Found 1 rules for <kivy.uix.label.Label object at 0x723d58b8>
[DEBUG  ] [Base        ] Create provider from mouse
[DEBUG  ] [Base        ] Create provider from probesysfs,provider=mtdev
[DEBUG  ] [ProbeSysfs  ] using probesysfs!
[DEBUG  ] [ProbeSysfs  ] found device: ILITEK ILITEK Multi-Touch at /dev/input/event0
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [MTD         ] Read event from </dev/input/event0>
[DEBUG  ] [Base        ] Create provider from probesysfs,provider=hidinput
[DEBUG  ] [ProbeSysfs  ] using probesysfs!
[DEBUG  ] [ProbeSysfs  ] found device: ILITEK ILITEK Multi-Touch at /dev/input/event0
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[DEBUG  ] [Base        ] Create provider from probesysfs,provider=hidinput
[DEBUG  ] [ProbeSysfs  ] using probesysfs!
[DEBUG  ] [ProbeSysfs  ] found device: ILITEK ILITEK Multi-Touch at /dev/input/event0
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 11051
[INFO   ] [HIDMotionEvent] using <ILITEK ILITEK Multi-Touch>
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 6187
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range ABS X position is 0 - 11051
[INFO   ] [HIDMotionEvent] using <ILITEK ILITEK Multi-Touch>
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[TRACE  ] [Lang        ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x73d20ce0>, key=pos, value=<code object <module> at 0x76325a70, file "/usr/local/lib/python3.5/dist-packages/kivy/data/style.kv", line 10>, 'int(self.center_x - self.texture_size[0] / 2.), int(self.center_y - self.texture_size[1] / 2.)'
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range ABS Y position is 0 - 6187
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range ABS X position is 0 - 11051
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[TRACE  ] [Lang        ] call_fn => value=(653, 211)
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range position X is 0 - 11051
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range ABS Y position is 0 - 6187
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[TRACE  ] [Lang        ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x73d20ce0>, key=size, value=<code object <module> at 0x76325980, file "/usr/local/lib/python3.5/dist-packages/kivy/data/style.kv", line 9>, 'self.texture_size'
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range position Y is 0 - 6187
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range position X is 0 - 11051
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[TRACE  ] [Lang        ] call_fn => value=[613, 118]
[INFO   ] [HIDMotionEvent] <ILITEK ILITEK Multi-Touch> range position Y is 0 - 6187
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[TRACE  ] [Lang        ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x73d20ce0>, key=texture, value=<code object <module> at 0x76325930, file "/usr/local/lib/python3.5/dist-packages/kivy/data/style.kv", line 8>, 'self.texture'
[TRACE  ] [Lang        ] call_fn => value=<Texture hash=1916187952 id=0 size=(613, 118) colorfmt='rgba' bufferfmt='ubyte' source=None observers=1>
[TRACE  ] [Lang        ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x75dc6500>, key=pos, value=<code object <module> at 0x76325a70, file "/usr/local/lib/python3.5/dist-packages/kivy/data/style.kv", line 10>, 'int(self.center_x - self.texture_size[0] / 2.), int(self.center_y - self.texture_size[1] / 2.)'
[TRACE  ] [Lang        ] call_fn => value=(673, 751)
[TRACE  ] [Lang        ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x75dc6500>, key=size, value=<code object <module> at 0x76325980, file "/usr/local/lib/python3.5/dist-packages/kivy/data/style.kv", line 9>, 'self.texture_size'
[TRACE  ] [Lang        ] call_fn => value=[574, 118]
[TRACE  ] [Lang        ] call_fn <kivy.graphics.vertex_instructions.Rectangle object at 0x75dc6500>, key=texture, value=<code object <module> at 0x76325930, file "/usr/local/lib/python3.5/dist-packages/kivy/data/style.kv", line 8>, 'self.texture'
[TRACE  ] [Lang        ] call_fn => value=<Texture hash=1916187792 id=0 size=(574, 118) colorfmt='rgba' bufferfmt='ubyte' source=None observers=1>
```

**Comment by DanTheMan2000** [comment]
I found a recent bug fix on the SDL_ttf repo committed about 4 weeks ago that is related to text outlines. How would I use the latest SDL_ttf code in Kivy????

[http://hg.libsdl.org/SDL_ttf/rev/bf2e6c9bfc83](url)

**Comment by matham** [comment]
I'd compile it manually and install it. Then recompile kivy using that as a dependency..
