### ISSUE TITLE
CodeInput problem: lexer object is not callable in kv file

### ISSUE THREAD

**Issue by DeybisMelendez** [kivy/kivy#6454]
### Versions

* Python: 3.7.4
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: https://riptutorial.com/es/kivy/example/6889/instalacion-y-configuracion

### Description

The example shown in the CodeInput documentation does not have an example of how to integrate it into the kv file.

[CodeInput Doc](https://kivy.org/doc/stable/api-kivy.uix.codeinput.html)

Executing it as follows causes error.

```
#main.py 
from kivy.app import App
from kivy.uix.codeinput import CodeInput
from pygments.lexers import CythonLexer
class Main(CodeInput):
	pass
class MainApp(App):
	def build(self):
		return Main()
if __name__ == '__main__':
    MainApp().run()

#main.kv 

#:import CythonLexer pygments.lexers
<Main>:
	lexer: CythonLexer()
```
### Code and Logs

```python
 Traceback (most recent call last):
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 249, in create_handler
     return eval(value, idmap), bound_list
   File "C:\Users\damv2\Desktop\codeinputerror\main.kv", line 3, in <module>
     lexer: CythonLexer()
 TypeError: '_automodule' object is not callable

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 692, in _apply_rule
     rctx['ids'])
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 254, in create_handler
     cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "C:\Users\damv2\Desktop\codeinputerror\main.kv", line 3:
 ...
       1:#:import CythonLexer pygments.lexers
       2:<Main>:
 >>    3:       lexer: CythonLexer()
 ...
 TypeError: '_automodule' object is not callable
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 249, in create_handler
     return eval(value, idmap), bound_list
   File "C:\Users\damv2\Desktop\codeinputerror\main.kv", line 3, in <module>
     lexer: CythonLexer()


 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "C:\Users\damv2\Desktop\codeinputerror\main.py", line 10, in <module>
     MainApp().run()
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\app.py", line 829, in run
     root = self.build()
   File "C:\Users\damv2\Desktop\codeinputerror\main.py", line 8, in build
     return Main()
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\uix\codeinput.py", line 101, in __init__
     super(CodeInput, self).__init__(**kwargs)
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\uix\textinput.py", line 527, in __init__
     super(TextInput, self).__init__(**kwargs)
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\uix\behaviors\focus.py", line 367, in __init__
     super(FocusBehavior, self).__init__(**kwargs)
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
     rule_children=rule_children)
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
     rule_children=rule_children)
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 538, in apply
     rule_children=rule_children)
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 707, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "C:\Users\damv2\Desktop\codeinputerror\main.kv", line 3:
 ...
       1:#:import CythonLexer pygments.lexers
       2:<Main>:
 >>    3:       lexer: CythonLexer()
 ...
 BuilderException: Parser: File "C:\Users\damv2\Desktop\codeinputerror\main.kv", line 3:
 ...
       1:#:import CythonLexer pygments.lexers
       2:<Main>:
 >>    3:       lexer: CythonLexer()
 ...
 TypeError: '_automodule' object is not callable
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 249, in create_handler
     return eval(value, idmap), bound_list
   File "C:\Users\damv2\Desktop\codeinputerror\main.kv", line 3, in <module>
     lexer: CythonLexer()

   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 692, in _apply_rule
     rctx['ids'])
   File "C:\Users\damv2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kivy\lang\builder.py", line 254, in create_handler
     cause=tb)
```

**Comment by crigaut** [comment]
Replace the first line in the kv file by:
```python
#:import CythonLexer pygments.lexers.CythonLexer
```
You imported the module `lexer` and not the Cython lexer itself.

**Comment by DeybisMelendez** [comment]
Ok, but the documentation have this: `from pygments.lexers import CythonLexer` [doc](https://kivy.org/doc/stable/api-kivy.uix.codeinput.html) I think it would be better to add an example for kv files there.
