### ISSUE TITLE
ListProperty cannot be deepcopy'd (or pickled, probably)

### ISSUE THREAD

**Issue by dcbaker** [kivy/kivy#6504]
### Versions

* Python: 3.7.4
* OS: Gentoo Linux
* Kivy: 1.11.1
* Kivy installation method: pipenv

### Description

`ListProperty` does not implement a valid `__reduce__` or `__reduce_ex__` method, making it impossible to deepcopy (or presumably pickle).

### Code and Logs

```python
import copy
from kivy.properties import ListProperty
from kivy.event import EventDispatcher

class A(EventDispatcher):
    attr = ListProperty()

a = A()
b = copy.deepcopy(a)
```

```
[INFO   ] [Logger      ] Record log in /home/dylan/.kivy/logs/kivy_19-09-05_17.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/dylan/.local/share/virtualenvs/venv/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.4 (default, Aug  1 2019, 15:47:41) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/dylan/.local/share/virtualenvs/venv/bin/python"
 Traceback (most recent call last):
   File "foo.py", line 9, in <module>
     b = copy.deepcopy(a)
   File "/home/dylan/.local/share/virtualenvs/venv/lib/python3.7/copy.py", line 169, in deepcopy
     rv = reductor(4)
   File "stringsource", line 2, in kivy._event.EventDispatcher.__reduce_cython__
 TypeError: no default __reduce__ due to non-trivial __cinit__
```

**Comment by matham** [comment]
I'm guessing this would be an easy fix, so PR with unit test is welcome. `DictProperty` presumably has a similar issue.

**Comment by gottadiveintopython** [comment]
I think this issue is not related to `ListProperty`, because the following code produce the same error.

```python
import copy
from kivy.event import EventDispatcher

class A(EventDispatcher):
    pass

a = A()
b = copy.deepcopy(a)
```

Also, I believe we can't just `copy.deepcopy()` a `EventDispatcher` even if no error is occured.

**Comment by JacekJagosz** [comment]
Unfortunately this is still an issue in the latest version.
```
File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
     y = _reconstruct(x, memo, *rv)
   File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
     state = deepcopy(state, memo)
   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
     y = copier(x, memo)
   File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
     y[deepcopy(key, memo)] = deepcopy(value, memo)
   File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
     rv = reductor(4)
   File "stringsource", line 2, in kivy.properties.ListProperty.__reduce_cython__
 TypeError: no default __reduce__ due to non-trivial __cinit__

Process finished with exit code 1
```

**Comment by philip501** [comment]
I have a similar / the same problem.

```
from copy import deepcopy
from kivy.properties import ListProperty
from kivy.uix.widget import Widget

class A(Widget):
    attr = ListProperty()

a = A()
deepcopy({'value': a.attr})
```

my workaround was to cast it to list.


Versions:

- Python: 3.10.11
- OS: Windows 11
- Kivy: 2.2.1
