### ISSUE TITLE
UrlRequest.wait block indefinitely

### ISSUE THREAD

**Issue by bit4bit** [kivy/kivy#6522]
### Versions

* Python: 3.7.0
* OS: GNU/Linux -GuixSD-
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

when request a unknown url (or url down) method *wait* not finish

### Code and Logs

~~~
def got_json(req, result):
    for key, value in result['headers'].items():
        print('{}: {}'.format(key, value))

req = UrlRequest('http://invalidurl', got_json, timeout=2)
req.wait() #block wait infinity
~~~

**Comment by johnny-stevie** [comment]
Maybe because its a synchronous request which is causing this problem?
im having a problem where my UrlRequest cant even access the url. It returns a malformed url error when the url is correct. Does UrlRequest not like some domains or some types of urls? Im confused.

**Comment by caver456** [comment]
Same issue here, kivy 1.10.1, python 3.7.0, windows 10.  The goal is to make the request synchronous, i.e. not move on to the next part of the code until either a response or a timeout is obtained.

```
        request=UrlRequest(self.cloudServer+"/api/v1/events",
            on_success=self.on_getCloudEvents_success,
            on_failure=self.on_getCloudEvents_failure,
            on_error=self.on_getCloudEvents_error,
            timeout=5,
            method="GET",
            debug=True)
        request.wait()
...

    def on_getCloudEvents_success(self,request,result):
        Logger.info("on_getCloudEvents_success called:")
        Logger.info("  result="+str(result))
        
    def on_getCloudEvents_failure(self,request,result):
        Logger.info("on_getCloudEvents_failure called:")
        Logger.info("  request was sent to "+str(request.url))
        Logger.info("    request body="+str(request.req_body))
        Logger.info("    request headers="+str(request.req_headers))
        Logger.info("  result="+str(result))

    def on_getCloudEvents_error(self,request,result):
        Logger.info("on_getCloudEvents_error called:")
        Logger.info("  request was sent to "+str(request.url))
        Logger.info("    request body="+str(request.req_body))
        Logger.info("    request headers="+str(request.req_headers))
        Logger.info("  result="+str(result))
        
```
it never gets past wait().  Killed the program manually after a half minute:

....
  < 5 seconds after the request is sent:>
```
[INFO   ] [on_getCloudEvents_error called]
[INFO   ] [  request was sent to http]//127.0.0.1:5000/api/v1/events
[INFO   ]     request body=None
[INFO   ]     request headers=None
[INFO   ]   result=timed out
```
  < endless loop here - I killed it with Ctrl-C after a while >
```
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 1866, in <module>
     theApp.run()
   File "C:\Python37-32\lib\site-packages\kivy\app.py", line 826, in run
     runTouchApp()
   File "C:\Python37-32\lib\site-packages\kivy\base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "C:\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "C:\Python37-32\lib\site-packages\kivy\base.py", line 337, in idle
     Clock.tick()
   File "C:\Python37-32\lib\site-packages\kivy\clock.py", line 581, in tick
     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "main.py", line 1251, in showStartupSyncChoices
     self.buildSyncChoicesList()
   File "main.py", line 1272, in buildSyncChoicesList
     request.wait()
   File "C:\Python37-32\lib\site-packages\kivy\network\urlrequest.py", line 563, in wait
     sleep(delay)
 KeyboardInterrupt
```

**Comment by caver456** [comment]
upgraded kivy to 1.11.1 - the problem remains.  Probably just a case of not understanding the intended usage of wait() - is there an example out there somewhere?

**Comment by caver456** [comment]
Here's a discussion on the kivy form that points out this can all be accomplished using the asynchronous callbacks as intended; that's very true, but, this is more of a case of the wait() function not working as documented, or at the very least, of the documentation not saying that it will wait for a >successful< response.  It should probably either be supported or nixed.

In an attempt to make the on_failure and on_error callbacks release the wait command, I added this to each of those callbacks, since wait() waits for resp_status to be other than None:
request.resp_status="Failure" # or "Error" or such
however this gives "AttributeError: can't set attribute".

O well.  Moving on.  Tried my own flag but I'm still not understanding something in the timing logic, since it waits for the full totalWait seconds even though the response was immediate:

...
        request=UrlRequest(self.cloudServer+"/api/v1/events",
            on_success=self.on_getCloudEvents_success,
            on_failure=self.on_getCloudEvents_failure,
            on_error=self.on_getCloudEvents_error,
            timeout=3,
            method="GET",
            debug=True)
        # make it synchronous
        self.SYNC_REQUEST_STAT=None
        totalWait=0
        while self.SYNC_REQUEST_STAT is None and totalWait<6:
            Logger.info("   stat="+str(self.SYNC_REQUEST_STAT))
            time.sleep(0.5)
            totalWait=totalWait+0.5

    def on_getCloudEvents_success(self,request,result):
        Logger.info("on_getCloudEvents_success called:")
        Logger.info("  result="+str(result))
        self.SYNC_REQUEST_STAT="Success" # to end the synchronous wait
        
    def on_getCloudEvents_failure(self,request,result):
        Logger.info("on_getCloudEvents_failure called:")
        Logger.info("  request was sent to "+str(request.url))
        Logger.info("    request body="+str(request.req_body))
        Logger.info("    request headers="+str(request.req_headers))
        Logger.info("  result="+str(result))
        self.SYNC_REQUEST_STAT="Failure" # to end the synchronous wait

    def on_getCloudEvents_error(self,request,result):
        Logger.info("on_getCloudEvents_error called:")
        Logger.info("  request was sent to "+str(request.url))
        Logger.info("    request body="+str(request.req_body))
        Logger.info("    request headers="+str(request.req_headers))
        Logger.info("  result="+str(result))
        self.SYNC_REQUEST_STAT="Error" # to end the synchronous wait


In this case, all 12 sleep iterations get printed, each one showing 'None', and after that the successful return value is show.  Basically looks like on_getCloudEvents_success is not actually processed until after the while loop is finished... thought it would be the other way around...?

Ok, will go the long way - make each handler call a separate function for the next task in order.

**Comment by caver456** [comment]
Note, I also tried making SYNC_REQUEST_STAT global, by removing the leading 'self.' in each case and adding 'global SYNC_REQUEST_STAT' at the start of each function that references it, but, still no luck.

**Comment by hymancheng** [comment]
does UrlRequest wok on mobile phone?

**Comment by caver456** [comment]
It does work on an android tablet, have not tried on a phone but would
expect it to be the same.

**Comment by MrBillium** [comment]
I came across this too and although URLRequest is primarily asnyc, there are times where a synchronous call makes more sense  - e.g. login - and the docs do say it is supported!

I came up with a very simple workaround : I subclassed , added one line of code and modified one other to make the wait continue if timeout expires
Here is example code

```
from kivy.network.urlrequest import UrlRequest
import time


# my modified version with one new attribute self.start_time and one modification to wait() while
class myUrlRequest(UrlRequest):
    # subclassed to use timeout in blocking wait()
    def __init__(self, url, **kwargs):
        super().__init__(url, **kwargs)
        **self.start_time = time.time()  # new attribute to keep track of request duration**


    def wait(self, delay=0.5):
        # modified While to 'and' timeout not expired
        while (self.resp_status is None) **and (self.start_time + self._timeout > time.time()**):
            self._dispatch_result(delay)
            time.sleep(delay)



badurl = 'http://192.168.199.199:8765'  # bad ( hopefully) link

# my version
ret = myUrlRequest(badurl, timeout=3)
ret.wait()
print (f' This will fire after timeout expires with ret.result = {ret.result}')

# original version
ret2 = UrlRequest(badurl, timeout=3)
ret2.wait()
print (' This will not print because wait is forever')`
```

**Comment by NomadDemon** [comment]
Is this 1.11 problem? urlrequest was refactored a bit on newer versions like 2.x

**Comment by Julian-O** [comment]
Tested with Kivy 2.2.1 on Windows 11. Got same problem.

```
    from kivy.network.urlrequest import UrlRequest
    
    def got_json(req, result):
        for key, value in result['headers'].items():
            print('{}: {}'.format(key, value))
    
    print("Prerequest")
    req = UrlRequest('http://invalidurl', got_json, timeout=2)
    print("After request")
    req.wait() #block wait infinity
    print("Wait concludes")
```    
This was the result of debugging:

The request is (obviously) to a bad URL.

The call to `wait()` loops until resp_status changes to be not None. (Spoiler: resp_status never changes!)

In the first loop, it calls `_dispatch_result()`.

`_dispatch_result()` pops the queue, and sets `result` to "error", `resp` to None and `data` to a description of the error. This seems reasonable, given the URL is bad.

The next block is protected by `if resp:` and doesn't execute, because `resp` is None. If `resp` is supposed to include an HTTP error code from the server, it is appropriately set to None, because there was no server to provide an HTTP error code. **In the skipped code, and only in the skipped code, `self._resp_status` is set.**

There is an `on_error()` callback that is then called, and the `_dispatch_result()` loop runs again until the queue is empty but the die is already cast.

When `_dispatch_result()` returns, the `wait()` loop continues forever, because it is waiting for `self._resp_status` to be set, and it never will be.

Either `self._resp_status` to some arbitrary non-Null value when an error occurs, so the `wait()` loop will end, or `wait()` should have a better loop conditional.
