### ISSUE TITLE
install kivy on python 3.8.0 

### ISSUE THREAD

**Issue by hussam132** [kivy/kivy#6563]
Hi i update my python version to 3.8.0 and when i try to install kivy i get the following error "also the error happened when i try to install it on pycharm" :

```
C:\Users\Hussam>pip install Kivy
Collecting Kivy
  Using cached https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hussam\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hussam\\AppData\\Local\\Temp\\pip-install-wmjvsmt5\\Kivy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hussam\\AppData\\Local\\Temp\\pip-install-wmjvsmt5\\Kivy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Hussam\AppData\Local\Temp\pip-install-wmjvsmt5\Kivy\pip-egg-info'
         cwd: C:\Users\Hussam\AppData\Local\Temp\pip-install-wmjvsmt5\Kivy\
    Complete output (199 lines):
    Using setuptools
    User distribution detected, avoid portable command.
    Using this graphics system: OpenGL
    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)


    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"


    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)


    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"


    WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)


    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"


    ERROR: Dependency for context.pyx not resolved: config.pxi
    ERROR: Dependency for compiler.pyx not resolved: config.pxi
    ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for fbo.pyx not resolved: config.pxi
    ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for instructions.pyx not resolved: config.pxi
    ERROR: Dependency for opengl.pyx not resolved: config.pxi
    ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
    ERROR: Dependency for shader.pyx not resolved: config.pxi
    ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for texture.pyx not resolved: config.pxi
    ERROR: Dependency for vbo.pyx not resolved: config.pxi
    ERROR: Dependency for vertex.pyx not resolved: config.pxi
    ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for cgl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
    ERROR: Dependency for svg.pyx not resolved: config.pxi
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Plex\Scanners.py because it changed.
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Plex\Actions.py because it changed.
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\Scanning.py because it changed.
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\Visitor.py because it changed.
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\FlowControl.py because it changed.
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Runtime\refnanny.pyx because it changed.
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\FusedNode.py because it changed.
    Compiling C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Tempita\_tempita.py because it changed.
    [1/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\FlowControl.py
    [2/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\FusedNode.py
    [3/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\Scanning.py
    [4/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Compiler\Visitor.py
    [5/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Plex\Actions.py
    [6/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Plex\Scanners.py
    [7/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Runtime\refnanny.pyx
    [8/8] Cythonizing C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\Cython\Tempita\_tempita.py
     Unable to find pgen, not compiling formal grammar.
     warning: no files found matching 'Doc\*'
     warning: no files found matching '*.pyx' under directory 'Cython\Debugger\Tests'
     warning: no files found matching '*.pxd' under directory 'Cython\Debugger\Tests'
     warning: no files found matching '*.pxd' under directory 'Cython\Utility'
     warning: no files found matching 'pyximport\README'
     Traceback (most recent call last):
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
         return self.find_available_vc_vers()[-1]
     IndexError: list index out of range


     During handling of the above exception, another exception occurred:


     Traceback (most recent call last):
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\core.py", line 148, in setup
         dist.run_commands()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
         self.run_command(cmd)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
         cmd_obj.run()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
         cmd = self.call_command('install_lib', warn_dir=0)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
         self.run_command(cmdname)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
         self.distribution.run_command(command)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
         cmd_obj.run()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
         self.build()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\command\install_lib.py", line 107, in build
         self.run_command('build_ext')
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
         self.distribution.run_command(command)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
         cmd_obj.run()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
         _build_ext.run(self)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 340, in run
         self.build_extensions()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 449, in build_extensions
         self._build_extensions_serial()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
         self.build_extension(ext)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
         _build_ext.build_extension(self, ext)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 528, in build_extension
         objects = self.compiler.compile(sources,
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 360, in compile
         self.initialize()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
         vc_env = _get_vc_env(plat_spec)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
         return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
         self.si = SystemInfo(self.ri, vc_ver)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
         self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
         raise distutils.errors.DistutilsPlatformError(err)
     distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/


     During handling of the above exception, another exception occurred:


     Traceback (most recent call last):
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
         yield saved
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
         yield
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
         _execfile(setup_script, ns)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
         exec(code, globals, locals)
       File "C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\setup.py", line 228, in <module>
         This version of Cython is untested with Kivy. While this version may
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
         return distutils.core.setup(**attrs)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
         raise SystemExit("error: " + str(msg))
     SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/


     During handling of the above exception, another exception occurred:


     Traceback (most recent call last):
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
         run_setup(setup_script, args)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
         raise
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
         self.gen.throw(type, value, traceback)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
         yield
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
         self.gen.throw(type, value, traceback)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
         saved_exc.resume()
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
         six.reraise(type, exc, self._tb)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
         raise value.with_traceback(tb)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
         yield saved
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
         yield
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
         _execfile(setup_script, ns)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
         exec(code, globals, locals)
       File "C:\Users\Hussam\AppData\Local\Temp\easy_install-ez_wj3mg\Cython-0.29.10\setup.py", line 228, in <module>
         This version of Cython is untested with Kivy. While this version may
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
         return distutils.core.setup(**attrs)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
         raise SystemExit("error: " + str(msg))
     SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/


     During handling of the above exception, another exception occurred:


     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "C:\Users\Hussam\AppData\Local\Temp\pip-install-wmjvsmt5\Kivy\setup.py", line 1073, in <module>
         setup(
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
         _install_setup_requires(attrs)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
         dist.fetch_build_eggs(dist.setup_requires)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
         resolved_dists = pkg_resources.working_set.resolve(
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
         dist = best[req.key] = env.best_match(
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
         return self.obtain(req, installer)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
         return installer(requirement)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
         return cmd.easy_install(req)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
         return self.install_item(spec, dist.location, tmpdir, deps)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
         dists = self.install_eggs(spec, download, tmpdir)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
         return self.build_and_install(setup_script, setup_base)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
         self.run_setup(setup_script, setup_base, args)
       File "c:\users\hussam\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
         raise DistutilsError("Setup script exited with %s" % (v.args[0],))
     distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
when i was use python 3.7.5  kivy works fine but new is not 
Is the problem about the version of python ?  
any solution 
thanks

**Comment by GwenaelPellenArkeup** [comment]
Hello.

SystemExit: error: Microsoft Visual C++ 14.0 is required.

You can download build tools on https://visualstudio.microsoft.com/fr/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

**Comment by akshayaurora** [comment]
@GwenaelPellenArkeup this is because the install is trying to compile in case of absence of pre-built binary in wheels.

Kivy should be releasing a 3.8 wheel shortly.

**Comment by matham** [comment]
Waiting for https://github.com/appveyor/ci/issues/3142.

Also, seems manylinux wheel build was broken when 3.8 was released and manylinux wheels have not been building since start of Oct.

**Comment by hussam132** [comment]
I think the error because kivy still not support python 3.8.0 until new

**Comment by BenkiKuu** [comment]
I have the same problem and I was thinking its macosCatalina, thank you this is super helpful any idea when the new kivy support for python3.8 will be available?

**Comment by hussam132** [comment]
hi
if you go to kivy downloads page you will see the supported versions of
python from kivy is 2.7 and 5.3 to 3.7
so kivy not support python 3.8 yet

**Comment by sruano0** [comment]
Is this fixed? I still cant't use kivy with python 3.8. It shows its only available with python 2.7, however, its about to be deprecated for 2.7 :/ please help

**Comment by gagan5ingh** [comment]
its December now kivy is not installing. what should i do now.
does anyone have any idea how long would it take? switching to older version of python is the only option?

**Comment by gagan5ingh** [comment]
try installing by downloading kivy from https://www.lfd.uci.edu/~gohlke/pythonlibs/#kivy
and dont use pycharm

**Comment by matham** [comment]
We are not likely to release a 1.11.1 version for 3.8 to pypi. However, you can install kivy master using `pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/`.

**Comment by kiarakarla** [comment]
> We are not likely to release a 1.11.1 version for 3.8 to pypi. However, you can install kivy master using `pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/`.

Thank you!

**Comment by emlanis** [comment]
> We are not likely to release a 1.11.1 version for 3.8 to pypi. However, you can install kivy master using `pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/`.

thanks a bunch. This really works for me finally. But I've to select Python 2.7 as my base interpreter using pycharm. I seriously in love with kivy and it wasn't cooperating. 

Finally came to realise that there's still no updated version of kivy that works cool with python 3.8.. Oh c'mon kivy!
