### ISSUE TITLE
USB HID-device won't reconnect for a running app.

### ISSUE THREAD

**Issue by jonryk** [kivy/kivy#6613]
If I disconnect a USB connected HID I get the same error as previously noted in [#4406](https://github.com/kivy/kivy/issues/4406)
Kivy won't properly handle system USB dis-/re-connections taking place while the app is running (for system-devices enabled in the .kivy/config.ini).

I suspect this might be why the issue has been overlooked / neglected: Everything works fine when running under X/windows-system (when the HID and their dis-/re-connections are handled though X), and even if system-devices are used directly (not running X), they work fine as long as you don't disconnect / reconnect the USB HID-device while the app is running.

However, since I want to be able to disconnect and reconnect a USB HID while runing my Kivy-app on a stripped down raspbian without X, I'm out of luck... If the device has been disconnected, the running app will not reattach the device when it is reconnected.

- Hope someone can enlighten me! :-)

**Comment by jmichon** [comment]
I think I have encountered the same error on RaspberryPI 4. The issue however concerns the touchscreen, which is not being disconnected while the app is running (maybe the driver does something weird?). This is the official RaspberryPI touchscreen. Kivy built from source from the latest master. 
```
[INFO   ] MTD: </dev/input/event1> input device disconnected
[WARNING] stderr: Exception in thread HIDInputMotionEventProvider:
[WARNING] stderr: Exception in thread HIDInputMotionEventProvider:
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
[WARNING] stderr:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
[WARNING] stderr:     self.run()
[WARNING] stderr:     self.run()
[WARNING] stderr:   File "/usr/lib/python3.7/threading.py", line 865, in run
[WARNING] stderr:   File "/usr/lib/python3.7/threading.py", line 865, in run
[WARNING] stderr:     self._target(*self._args, **self._kwargs)
[WARNING] stderr:     self._target(*self._args, **self._kwargs)
[WARNING] stderr:   File "/usr/local/lib/python3.7/dist-packages/kivy/input/providers/hidinput.py", line 738, in _thread_run
[WARNING] stderr:   File "/usr/local/lib/python3.7/dist-packages/kivy/input/providers/hidinput.py", line 738, in _thread_run
[WARNING] stderr:     data = fd.read(struct_input_event_sz)
[WARNING] stderr:     data = fd.read(struct_input_event_sz)
[WARNING] stderr: OSError: [Errno 19] No such device
[WARNING] stderr: OSError: [Errno 19] No such device
[WARNING] stderr: 
[WARNING] stderr: 
```

**Comment by clickworkorange** [comment]
Having the same issue. Apart from some GPIO signals, which are handled outside Kivy, a physical keyboard is the only input used in my application. It is optional and only used for administration, and will not be left plugged in when not in use. At the moment I'm handling it by requiring a reboot to enter admin mode, but it is annoying to have to remember to connect the keyboard _before_ rebooting; it cannot be connected once the Kivy app is running - and it must be disconnected before rebooting to exit admin mode, or the exception mentioned above will be triggered. 

I'm thinking that possibly the best way around this is to let Python handle the keyboard and pass the events to Kivy - in other words to configure Kivy without any input providers and capture the keyboard and its events in the Python application layer. Clumsy, but could work.
