### ISSUE TITLE
Issue with android.runnable.run_on_ui_thread() decorator

### ISSUE THREAD

**Issue by vesellov** [kivy/kivy#6620]
### Versions

* Python: 3.7
* OS: Ubuntu 18.04
* Kivy: Kivy-1.11.1-py3.7
* Kivy installation method: inside buildozer.spec requirements

### Description

Hi guys.

First of all I would like to give you Huge Respect for everything you are doing here! Kivy + p4a is awesome project!

Based on [Android-native-embedded-browser](https://github.com/kivy/kivy/wiki/Android-native-embedded-browser) Wiki sample I am trying to build an Android APP that will run a small browser inside WebView widget and also background twisted server as detached Android service.

It is building fine, but when i am starting the .APK on my Android I am getting such error:

```
...
11-22 14:34:00.624 23260 23330 I python  : BitDustApp.on_start
11-22 14:34:00.624 23260 23330 I python  : BitDustApp.request_app_permissions
11-22 14:34:00.705 23260 23330 I python  : BitDustApp.request_app_permissions : None
11-22 14:34:00.706 23260 23330 I python  : [WARNING] [Base        ] Unknown <android> provider
11-22 14:34:00.706 23260 23330 I python  : [INFO   ] [Base        ] Start application main loop
11-22 14:34:00.707 23260 23330 I python  : [INFO   ] [Base        ] Leaving application in progress...
11-22 14:34:00.707 23260 23330 I python  :  Traceback (most recent call last):
11-22 14:34:00.707 23260 23330 I python  :    File "/app/.buildozer/android/app/main.py", line 135, in <module>
11-22 14:34:00.708 23260 23330 I python  :    File "/app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bitdust/kivy/app.py", line 855, in run
11-22 14:34:00.708 23260 23330 I python  :    File "/app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bitdust/kivy/base.py", line 504, in runTouchApp
11-22 14:34:00.709 23260 23330 I python  :    File "/app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bitdust/kivy/core/window/window_sdl2.py", line 747, in mainloop
11-22 14:34:00.709 23260 23330 I python  :    File "/app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bitdust/kivy/core/window/window_sdl2.py", line 479, in _mainloop
11-22 14:34:00.710 23260 23330 I python  :    File "/app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bitdust/kivy/base.py", line 339, in idle
11-22 14:34:00.710 23260 23330 I python  :    File "/app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bitdust/kivy/clock.py", line 591, in tick
11-22 14:34:00.711 23260 23330 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
11-22 14:34:00.711 23260 23330 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
11-22 14:34:00.712 23260 23330 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
11-22 14:34:00.712 23260 23330 I python  :    File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
11-22 14:34:00.713 23260 23330 I python  :    File "kivy/_clock.pyx", line 88, in kivy._clock.ClockEvent.get_callback
11-22 14:34:00.713 23260 23330 I python  :    File "/app/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/bitdust/kivy/weakmethod.py", line 47, in __call__
11-22 14:34:00.714 23260 23330 I python  :  AttributeError: 'BitDustUI' object has no attribute 'f2'
11-22 14:34:00.714 23260 23330 I python  : Python for android ended.
```

### Code and Logs

My current code is present in a separate branch on GitHub:

main.py : https://github.com/vesellov/bitdust.android/blob/webview/src/main.py
buildozer.spec : https://github.com/vesellov/bitdust.android/blob/webview/buildozer.spec

Looks like something is wrong with `run_on_ui_thread` decorator? Or i am missing some libraries?

**Comment by vesellov** [comment]
I also tried with `p4a.bootstrap = webview` in `buildozer.spec` but then another issue raised while building: 
```[ERROR]:   Build failed: Conflict detected: 'kivy' inducing dependencies ('sdl2',), and 'genericndkbuild' inducing conflicting dependencies ('genericndkbuild',)```
