### ISSUE TITLE
*.kv file can't contain Chinese.

### ISSUE THREAD

**Issue by WalkerMe** [kivy/kivy#6628]
### Versions

* Python: Python 3.5.1
* OS: Win 10
* Kivy: Kivy==1.11.1
* Kivy installation method: pip

### Code and Logs

```python
 Traceback (most recent call last):
   File "G:/Workspace/PyCharm/WUKit/Src/kmain.py", line 87, in <module>
     WKApp().run()
   File "G:\Workspace\Venvs\WUKit\lib\site-packages\kivy\app.py", line 828, in run
     self.load_kv(filename=self.kv_file)
   File "G:\Workspace\Venvs\WUKit\lib\site-packages\kivy\app.py", line 599, in load_kv
     root = Builder.load_file(rfilename)
   File "G:\Workspace\Venvs\WUKit\lib\site-packages\kivy\lang\builder.py", line 290, in load_file
     data = fd.read()
 UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 575: illegal multibyte sequence
```

**Comment by DanTheMan2000** [comment]
Set the encoding type when reading the file:

```
with open('example.kv', encoding='utf-8') as f:
    Builder.load_string(f.read())
```

**Comment by baseplate-admin** [comment]
Hey i have a question here.

```python
with open('example.kv', encoding='utf-8') as f:
    Builder.load_string(f.read())
```

Why is this not the default behavior?

**Comment by p0lygun** [comment]
I don't think that will fix it... load file by default uses `utf-8`
https://github.com/kivy/kivy/blob/1598e4e0a057875321807800c9b1ff49fbfd6fdd/kivy/lang/builder.py#L291

**Comment by baseplate-admin** [comment]
> it looks like it did not back then but then the default was set in https://github.com/kivy/kivy/pull/6880

Opps, i missed this part :( 

Anyways LGTM then :)
