### ISSUE TITLE
kivycatalog demo: AttributeError: 'MarkupLabel' object has no attribute 'get_descent'

### ISSUE THREAD

**Issue by HeRo002** [kivy/kivy#6637]
OK... I got the error mentioned in the title when trying to run the KivyCatalog demo. 
I posted the problem on https://groups.google.com/forum/#!topic/kivy-users/JBAgpwieDL8 which didn't really help. 
Then I posted it on https://discordapp.com/channels/423249981340778496/423250272316293120 where 'tshirtman' solved it - quite fast! 

It turns out the following Terminal command was needed (I use Ubuntu Linux): 

sudo apt install libsdl2-ttf-2.0-0

'tshirtman' asked me to mention:

" the issue is core/text/text_pil.py missing the get_descent method "

This is the exact Terminal-command that gave the error:

henrik@Henrik-L570:/usr/share/kivy-examples/demo/kivycatalog$ python3 main.py

### Versions

* Python: v3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]

* OS: Ubuntu 18.04.3 LTS 
GNOME: 3.28.2

* Kivy: v1.11.1
* Kivy installation method: 
I think I used: https://kivy.org/doc/stable/installation/installation-linux.html#using-software-packages-ppa-etc

### Description

See above.

Here is the full error log from Terminal:

```henrik@Henrik-L570:/usr/share/kivy-examples/demo/kivycatalog$ python3 main.py
[INFO   ] [Logger      ] Record log in /home/henrik/.kivy/logs/kivy_19-12-06_0.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/lib/python3/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 19.0.8'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [VideoGstplayer] Using Gstreamer 1.14.5.0
[INFO   ] [Video       ] Provider: gstplayer
[WARNING] [Image       ] Unable to load image </usr/share/kivy-examples/widgets/cityCC0.mpg>
[ERROR  ] [Image       ] Error loading texture ../../widgets/cityCC0.mpg
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event9
[INFO   ] [MTD         ] Read event from </dev/input/event9>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event9". Please ensure you have the appropriate permissions.
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 192, in <module>
     KivyCatalogApp().run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 339, in idle
     Clock.tick()
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 591, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/usr/lib/python3/dist-packages/kivy/uix/label.py", line 409, in texture_update
     self._label.texture.bind()
   File "kivy/graphics/texture.pyx", line 764, in kivy.graphics.texture.Texture.bind
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/usr/lib/python3/dist-packages/kivy/core/text/__init__.py", line 754, in _texture_fill
     self.render(real=True)
   File "/usr/lib/python3/dist-packages/kivy/core/text/markup.py", line 143, in render
     ret = self._render_real()
   File "/usr/lib/python3/dist-packages/kivy/core/text/__init__.py", line 678, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/usr/lib/python3/dist-packages/kivy/core/text/markup.py", line 480, in render_lines
     script_pos = max(0, psp if psp else self.get_descent())
 AttributeError: 'MarkupLabel' object has no attribute 'get_descent'
```

**Comment by Jowls1** [comment]
I've just had this error on a Raspberry Pi 3b running Buster and Kivy 2.0.0rc4.  The error I got was:
`AttributeError: 'MarkupLabel' object has no attribute 'get_descent'`

The symptoms of the error were that the GUI just froze.  I tracked it down to a label being updated with `Markup: True`.  If I set the label to `Markup: False`, it ran fine.

The issue for me is that I had used an image created on a Pi 4, which had installed Kivy as per the Pi 4 instructions (manually compiling all the SDL2 packages).

**The fix was simple**:
`sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev`

After that, all my labels worked with `Markup`.  Recording it here in case someone else has this issue.

**Comment by Julian-O** [comment]
I cant tell if this means it is a configuration issue, a documentation about configuration issue or a real bug.

**Comment by ElliotGarbus** [comment]
@Julian-O 
This is not an issue on Windows.

**Comment by Julian-O** [comment]
@ElliotGarbus: Oh, I understood that. The OP had a cryptic error message. Installing `libsdl2-ttf-2.0-0` fixed it.

My confusion is about the plan going forward. Which of these just happened?

* The documentation clearly told the user what to do, and the user didn't do it. User's fault. No action required.
* The documentation told the user what to do, and the user didn't do it and it happens frequently enough that our support team identified it immediately. Preventing this is worthwhile. Add the error and solution to the FAQ to mitigate the mistake, make the installation documentation clearer to prevent it, consider adding code to detect the problem and display a more meaningful error, considered automating installation instructions to prevent this error.
* The documentation didn't mention everything needed to install. Add installing `libsdl2-ttf-2.0-0` to the documentation.
* The documentation didn't need to mention everything needed to install, because the automated install scripts should have covered all the dependencies, without the user having to know. Fix the code
* Something else?

**Comment by ElliotGarbus** [comment]
I've never done a build on Linux but reading the problem and the fix, it appears there are a set of dependencies that are (or were) not included in the build:  libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
