### ISSUE TITLE
kv language: comment being processed rather than ignored

### ISSUE THREAD

**Issue by wavecycle** [kivy/kivy#6657]
### Versions

* Python: 3.7.3
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: used pip install instructions

### Description

I was setting a custom attribute "canvas_color", which would in turn be referenced by the canvas rgba attribute and I got an error "TypeError: 'NoneType' object is not iterable". The problem seems to come from a comment that was after the canvas_color value.

How to replicate: If I run the code pasted below I get the type error as described above. If I delete the comment at the end of line 9 "#comment" and rerun, then it runs without a problem.

### Code and Logs

```
from kivy.app import App
from kivy.lang.builder import Builder

root_kv = """
LabelCanvas:
	text: "test"

<CanvasFill@Widget>:
	canvas_color: 0 ,0 ,0 ,0 #comment
	canvas.before:
		Color:
			rgba: self.canvas_color
		Rectangle:
			pos: self.pos
			size: self.size

<LabelCanvas@Label+CanvasFill>:
"""


class EmptyApp(App):
	def build(self):
		self.root = Builder.load_string(root_kv)


if __name__ == "__main__":
	EmptyApp().run()
```

**Comment by Fak3** [comment]
Can you try this: `canvas_color: (0 ,0 ,0 ,0) #comment`?

**Comment by wavecycle** [comment]
Hi, I'm not using Kivy any more. Take care

**Comment by Franccisco** [comment]
Hi

> Can you try this: `canvas_color: (0 ,0 ,0 ,0) #comment`?

I get the same error with that.

This error is because of the current parser implementation:

https://github.com/kivy/kivy/blob/e48052d878c5bdfc00ebf4a92be71134152c40f7/kivy/lang/parser.py#L523-L536

As you can see, the documentation says it works only with comments on a
single line.

**Comment by DrakeProvost** [comment]
Same issue. This might fall into the category of "it's not a bug, it's a feature!", but I feel it's a confusing feature since it doesn't match what one would expect based on Python. I think they should change this.

**Comment by ProgramCrafter** [comment]
I've ran into the same issue.

My versions are:
- Python: 3.9.0
- OS: Windows 10
- Kivy: 2.0.0
- Kivy installation method: `pip install kivy`

This code crashes:
```python
from kivy.config import Config
Config.set('kivy', 'log_level', 'debug')

from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory

kv = """
<ColouredWidget@Widget>:
  backcolor:        0.2, 0.4, 1.0, 1 # this comment breaks everything
  
  canvas.before:
    Color:
      rgba:         self.backcolor
    
    Ellipse:
      segments:     5
      pos:          self.pos
      size:         self.size

<Test@FloatLayout>:
  ColouredWidget:

"""


class TestApp(App):
    def build(self):
        return Factory.Test()


if __name__ == '__main__':
    Builder.load_string(kv)
    TestApp().run()
```
and the following code works:
```python
from kivy.config import Config
Config.set('kivy', 'log_level', 'debug')

from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory

kv = """
<ColouredWidget@Widget>:
  backcolor:        0.2, 0.4, 1.0, 1
  # no comments
  
  canvas.before:
    Color:
      rgba:         self.backcolor
    
    Ellipse:
      segments:     5
      pos:          self.pos
      size:         self.size

<Test@FloatLayout>:
  ColouredWidget:

"""


class TestApp(App):
    def build(self):
        return Factory.Test()


if __name__ == '__main__':
    Builder.load_string(kv)
    TestApp().run()
```

I think the parser should either *raise an exception* when the comment is placed at the end of the line or *handle* these comments as normal ones, not silently ignore the line.

**Comment by DrakeProvost** [comment]
To be clear, @ProgramCrafter does that code crash, or does it silently ignore the line with a comment at the end? You seem to have said both.

**Comment by ProgramCrafter** [comment]
@DrakeProvost
There is the log:
```
[INFO   ] [Logger      ] Record log in C:\Users\****\.kivy\logs\kivy_21-11-30_91.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Program Files\Python39\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Program Files\Python39\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [App         ] Loading kv <D:\Python\test.kv>
[DEBUG  ] [App         ] kv <D:\Python\test.kv> not found
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[DEBUG  ] [GL          ] available extensions: b'GL_3DFX_texture_compression_FXT1 GL_AMD_depth_clamp_separate GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_cl_event GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_robustness_isolation GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_separate_stencil GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_polygon_offset_clamp GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_compression_s3tc GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_IBM_texture_mirrored_repeat GL_INTEL_coarse_fragment_shader GL_INTEL_conservative_rasterization GL_INTEL_fragment_shader_ordering GL_INTEL_framebuffer_CMAA GL_INTEL_map_texture GL_INTEL_multi_rate_fragment_shader GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_shader_subgroup GL_KHR_shader_subgroup_arithmetic GL_KHR_shader_subgroup_ballot GL_KHR_shader_subgroup_basic GL_KHR_shader_subgroup_clustered GL_KHR_shader_subgroup_quad GL_KHR_shader_subgroup_shuffle GL_KHR_shader_subgroup_shuffle_relative GL_KHR_shader_subgroup_vote GL_KHR_texture_compression_astc_ldr GL_NV_blend_square GL_NV_conditional_render GL_NV_primitive_restart GL_NV_texgen_reflection GL_OVR_multiview GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays GL_WIN_swap_hint WGL_EXT_swap_control'
[DEBUG  ] [GL          ] glShaderBinary is not available
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 30.0.100.9837'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) AlderLake-S Mobile Graphics Controller'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 30.0.100.9837'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load <C:\Program Files\Python39\lib\site-packages\kivy\data\glsl\default.png>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "C:\Program Files\Python39\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
 TypeError: 'NoneType' object is not iterable

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "D:\Python\test-comment.py", line 34, in <module>
     TestApp().run()
   File "C:\Program Files\Python39\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\Program Files\Python39\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "D:\Python\test-comment.py", line 29, in build
     return Factory.Test()
   File "C:\Program Files\Python39\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Program Files\Python39\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Program Files\Python39\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "C:\Program Files\Python39\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\Program Files\Python39\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\Program Files\Python39\lib\site-packages\kivy\lang\builder.py", line 661, in _apply_rule
     child.apply_class_lang_rules(
   File "C:\Program Files\Python39\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "C:\Program Files\Python39\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "C:\Program Files\Python39\lib\site-packages\kivy\lang\builder.py", line 596, in _apply_rule
     self._build_canvas(widget.canvas.before, widget,
   File "C:\Program Files\Python39\lib\site-packages\kivy\lang\builder.py", line 929, in _build_canvas
     raise BuilderException(
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 7:
 ...
       5:  canvas.before:
       6:    Color:
 >>    7:      rgba:         self.backcolor
       8:
       9:    Ellipse:
 ...
 TypeError: 'NoneType' object is not iterable
   File "C:\Program Files\Python39\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\context_instructions.pyx", line 275, in kivy.graphics.context_instructions.Color.rgba.__set__
```
Firstly, *backcolor* is set to None, meaning that line is not handled properly. Then using *backcolor* in Color.rgba causes the program to crash.

**Comment by Julian-O** [comment]
Summarising: This is a feature request to permit end-of-line comments in KV, similar to Python.

I suspect there are going to be grammar ambiguity issues, but I will leave that for an expert to decide.
