### ISSUE TITLE
PyInstaller built Package can't run on OSX Catalina 10.15.3

### ISSUE THREAD

**Issue by mengqimusic** [kivy/kivy#6747]
# Versions

* Python: 3.7.6
* OS: Catalina 10.15.3
* Kivy: 1.11.1
* Kivy installation method: pip install kivy

### Description

I tested with a minimal python script, after building with PyInstaller 3.6 with :

```
pyinstaller -y --clean --windowed --add-data "kivytest.kv":. \
  --exclude-module _tkinter \
  --exclude-module Tkinter \
  --exclude-module enchant \
  --exclude-module twisted \
  kivytest.py
```

The packed app won't run, error message contains :

```
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "kivytest.py", line 2, in <module>
   File "/Volumes/SSD 1T/Dropbox/[MQ]/Files/Python/test/env37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
     exec(bytecode, module.__dict__)
   File "kivy/app.py", line 319, in <module>
   File "/Volumes/SSD 1T/Dropbox/[MQ]/Files/Python/test/env37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
     exec(bytecode, module.__dict__)
   File "kivy/base.py", line 26, in <module>
   File "/Volumes/SSD 1T/Dropbox/[MQ]/Files/Python/test/env37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
     exec(bytecode, module.__dict__)
   File "kivy/clock.py", line 363, in <module>
   File "kivy/_clock.pyx", line 9, in init kivy._clock
 ModuleNotFoundError: No module named 'kivy.weakmethod'
[12719] Failed to execute script kivytest
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

But doing the same thing on my High Sierra 10.13.6 computer is no problem (altho the app created on it won't run on the Catalina)

### Code and Logs

```python
import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout

class Base(BoxLayout):
    pass

class KivyTest(App):
    def build(self):
        return Base()

if __name__ == '__main__':
    KivyTest().run()
```
```kv
#:kivy 1.11.1

<Base>:
    Button:
        text:'a'
```

**Comment by mengqimusic** [comment]
Just found out it works on internal hard drive on the Catalina machine. Why?

Thanks.

**Comment by 1melty1** [comment]
Same question

**Comment by akshayaurora** [comment]
Need more investigation, could be a permissions issue with access to the drive.

**Comment by ElliotGarbus** [comment]
@Julian-O This can be closed.  
I routinely use pyinstaller with kivy with a spec file.   When debugging build issues with pyinstaller it is best to look at the kivy log to determine the cause of the failure.

Attached below is a spec file I use on MacOS.  
```python
# -*- mode: python -*-

block_cipher = None
app_name = 'Your App Name'
mac_icon = '../Images/your_logo_512.icns'  # use 512 x 512 for mac icon


a = Analysis(['../main.py'],
             pathex=[],
             binaries=[],
             datas=[('../*.kv', '.'),
                    ('../Images/*.png', './Images')],  # customize for your code
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['_tkinter', 'Tkinter', 'enchant', 'twisted'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name=app_name,
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=False)

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name=app_name)

app = BUNDLE(coll,
             name=app_name + '.app',
             icon=mac_icon,
             bundle_identifier=None)
```
