### ISSUE TITLE
Kivy 1.11.1 on Raspbian won't use ffmpeg player for Video

### ISSUE THREAD

**Issue by OutsourcedGuru** [kivy/kivy#6766]
### Versions

* Python: 3.7.3
* OS: Linux octopi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
* Kivy: 1.11.1
* Hardware: Pi 4B with standard Raspberry Pi NoIR v2 camera on ribbon cable
* Software: OctoPi IMG from http://github.com/guysoft/OctoPi which includes mjpg_streamer for webcam
* Kivy installation method:
  - Install OctoPi 0.17.0
  - Remove/replace Python 2.7 virtual environment with 3.7.3
  - `pip install octoprint`
  - `pip install ffmpeg-python`
  - `pip install -U Cython==0.28.2`
  - `sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev python-setuptools libgstreamer1.0-dev git-core gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-{omx,alsa} python-dev libmtdev-dev xclip xsel`
  - `pip install kivy==1.11.1`
  - `mkdir ~/tmp && cd ~/tmp`
  - `touch TestVideo.py && nano TestVideo.py`

Install nodm to launch Kivy app within a minimal x11 context from Raspbian Buster Lite
```
sudo apt-get -y install xserver-xorg libpam0g-dev help2man libx11-dev debhelper
mkdir ~/src
cd ~/src
git clone https://github.com/slashblog/nodm.git
cd nodm
git checkout d48a8f6266d3f464138e0e95b65896917c35c89f
source /etc/os-release
wget http://deb.debian.org/debian/pool/main/n/nodm/nodm_0.13-5.debian.tar.xz
tar xf nodm_0.13-*.debian.tar.xz
sudo dpkg-buildpackage -us -uc -b
cd ..
sudo dpkg -i nodm_0.13-*_armhf.deb # "y"
cd ~
sudo rm -Rf src/* && rmdir src
sudo sh -c 'echo "NODM_ENABLED=true" > /etc/default/nodm'
sudo sh -c 'echo "NODM_USER=$SUDO_USER" >> /etc/default/nodm' # Note that the variable SUDO_USER is used
sudo sh -c 'echo "NODM_FIRST_VT='\''7'\''" >> /etc/default/nodm'
sudo sh -c 'echo "NODM_XSESSION=/etc/X11/Xsession" >> /etc/default/nodm'
sudo sh -c 'echo "NODM_X_OPTIONS='\''-nolisten tcp'\''" >> /etc/default/nodm'
sudo sh -c 'echo "NODM_MIN_SESSION_TIME=60" >> /etc/default/nodm'
sudo sh -c 'echo "NODM_X_TIMEOUT=300" >> /etc/default/nodm'
touch ~/.xsession
nano ~/.xsession
# --
#!/bin/bash
export DISPLAY=:0.0
/usr/bin/xset s off
/usr/bin/xset -dpms
/usr/bin/xset s noblank
source /home/pi/oprint/bin/activate
cd /home/pi/tmp
python TestVideo.py
fi
# --
```

### Description
I was attempting to replace the memory-leaking `gstplayer` video provider with anything else. Your documentation suggests that `ffmpeg` is an option so I'm attempting to use this.

Although it appears to load `ffmpeg` over `gstreamer`, it then doesn't find an `FFVideo()` method that it's looking for and crashes.

### Code and Logs

~/tmp/TestVideo.py
```
import os
os.environ['KIVY_WINDOW'] = 'sdl2'
os.environ['KIVY_GL_BACKEND'] = 'gl'
os.environ['KIVY_VIDEO'] = 'ffmpeg'
from kivy.app import App
from kivy.core.window import Window
from kivy.uix.video import Video
Window.fullscreen = True

class KivyVideo(App):
    def build(self):
        return Video(state="play", source="http://localhost:8080/?action=stream")

KivyVideo().run()
```

Log output:
```
[INFO   ] Logger: Record log in /home/pi/ocm-db/logs/mprint-hmi_20200311_38.log
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/home/pi/oprint/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0]
[INFO   ] Python: Interpreter at "/home/pi/oprint/bin/python"
[INFO   ] ImageLoaderFFPy: Using ffpyplayer 4.3.0
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_ffpyplayer, img_gif (img_pil ignored)
[DEBUG  ] Window: Provider <egl_rpi> ignored by config
[INFO   ] Window: Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] GL: Using the "OpenGL" graphics system
[DEBUG  ] GL: glShaderBinary is not available
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'2.1 Mesa 19.2.0-rc1'>
[INFO   ] GL: OpenGL vendor <b'Broadcom'>
[INFO   ] GL: OpenGL renderer <b'V3D 4.2'>
[INFO   ] GL: OpenGL parsed version: 2, 1
[INFO   ] GL: Shading version <b'1.20'>
[INFO   ] GL: Texture max size <4096>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard allowed, single mode, docked
[DEBUG  ] Video: Provider <gstplayer> ignored by config
[INFO   ] Video: Provider: ffmpeg(['video_gstplayer'] ignored)
[DEBUG  ] App: Loading kv <./kivyvideo.kv>
[DEBUG  ] App: kv <./kivyvideo.kv> not found
[ERROR  ] Image: Error reading file http://localhost:8080/?action=stream
[INFO   ] Base: Start application main loop
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "TestVideo.py", line 14, in <module>
[INFO   ] HIDMotionEvent: <Atmel Atmel maXTouch Digitizer> range ABS Y position is 0 - 4095
[INFO   ] MTD: </dev/input/event0> range touch minor is 0 - 0
[INFO   ] HIDMotionEvent: <Atmel Atmel maXTouch Digitizer> range ABS X position is 0 - 4095
[INFO   ] MTD: </dev/input/event1> range pressure is 0 - 255
[WARNING] stderr:     KivyVideo().run()
[INFO   ] HIDMotionEvent: <Atmel Atmel maXTouch Digitizer> range position X is 0 - 4095
[INFO   ] MTD: </dev/input/event0> range pressure is 0 - 255
[INFO   ] HIDMotionEvent: <Atmel Atmel maXTouch Digitizer> range ABS Y position is 0 - 4095
[INFO   ] MTD: </dev/input/event1> axes invertion: X is 0, Y is 0
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/app.py", line 855, in run
[INFO   ] HIDMotionEvent: <Atmel Atmel maXTouch Digitizer> range position Y is 0 - 4095
[INFO   ] MTD: </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] MTD: </dev/input/event1> rotation set to 0
[INFO   ] MTD: </dev/input/event0> rotation set to 0
[WARNING] stderr:     runTouchApp()
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp
[WARNING] stderr:     EventLoop.window.mainloop()
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
[WARNING] stderr:     self._mainloop()
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
[WARNING] stderr:     EventLoop.idle()
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/base.py", line 339, in idle
[WARNING] stderr:     Clock.tick()
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/clock.py", line 591, in tick
[WARNING] stderr:     self._process_events()
[WARNING] stderr:   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/uix/video.py", line 189, in _do_video_load
[WARNING] stderr:     self._video.play()
[WARNING] stderr:   File "/home/pi/oprint/lib/python3.7/site-packages/kivy/core/video/video_ffmpeg.py", line 47, in play
[WARNING] stderr:     self._player = ffmpeg.FFVideo(self._filename)
[WARNING] stderr: AttributeError: module 'ffmpeg' has no attribute 'FFVideo'
```

**Comment by matham** [comment]
I don't think the ffmpeg backend is supported anymore. We probably should deprecate it as I don't think anyone is using it anymore. If you look at the actual project it says that it has been deprecated: https://github.com/tito/ffmpeg-android.

**Comment by OutsourcedGuru** [comment]
Fair enough. I think I would remove it from the suggestions and docs.

**Comment by matham** [comment]
PRs welcome!
