### ISSUE TITLE
Unable to import modules in KV file  packaged with Pyinstaller

### ISSUE THREAD

**Issue by onsunsl** [kivy/kivy#6805]
**Software Versions**
* Python: 3.6.3
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method:  pip (including kivy.deps,angle, kivy.deps.glew, kivy.deps.gstreamer)
* Pyinstaller: 3.5

**Describe the bug**
There is no probalem running with the source code, but an internal exception occars when using the `:import xxx.bbb` module when loading `.kv ` file after packagede with `Pyinstaller`.

**Code and Logs and screenshots**

* KV file
```QML
// REPLACE ME: Paste your code and logs here, a template can be found at https://git.io/vM1id.
<UiManager>:
    #:import TopStateBar ui.kv.status_bar.top_bar
    #:import ToolBar ui.kv.tool_bar.tool_bar
    #:import CustomScreenManager ui.kv.base.screen_manager
    FloatLayout:
        BoxLayout:
            orientation:'vertical'
            canvas.before:
                Color:
                    rgba:0.13, 0.17, 0.4, 1
                Rectangle:
                    pos:self.pos
                    size:self.size
            padding:10,5,10,10

            BoxLayout:
                id:box_bar
                size_hint:1,None
                pos_hint:{'top':1}
                orientation:'vertical'
                height: 0
                padding:0,30,0,0
```

* log

```log
2020-04-01 11:33:22,757 MainThread ERROR : 
Traceback (most recent call last):
  File "site-packages\kivy\lang\parser.py", line 471, in execute_directives
ModuleNotFoundError: No module named 'ui.kv.status_bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\kivy\lang\parser.py", line 473, in execute_directives
ModuleNotFoundError: No module named 'ui.kv.status_bar'
2020-04-01 11:33:22,758 MainThread WARNING : stderr: Traceback (most recent call last):
2020-04-01 11:33:22,758 MainThread WARNING : stderr:   File "site-packages\kivy\lang\parser.py", line 471, in execute_directives
2020-04-01 11:33:22,759 MainThread WARNING : stderr: ModuleNotFoundError: No module named 'ui.kv.status_bar'
2020-04-01 11:33:22,759 MainThread WARNING : stderr: 
2020-04-01 11:33:22,759 MainThread WARNING : stderr: During handling of the above exception, another exception occurred:
2020-04-01 11:33:22,759 MainThread WARNING : stderr: 
2020-04-01 11:33:22,759 MainThread WARNING : stderr: Traceback (most recent call last):
2020-04-01 11:33:22,759 MainThread WARNING : stderr:   File "site-packages\kivy\lang\parser.py", line 473, in execute_directives
2020-04-01 11:33:22,760 MainThread WARNING : stderr: ModuleNotFoundError: No module named 'ui.kv.status_bar'
2020-04-01 11:33:22,760 MainThread WARNING : stderr: 
2020-04-01 11:33:22,760 MainThread WARNING : stderr: During handling of the above exception, another exception occurred:
2020-04-01 11:33:22,760 MainThread WARNING : stderr: 
2020-04-01 11:33:22,760 MainThread WARNING : stderr: Traceback (most recent call last):
2020-04-01 11:33:22,761 MainThread WARNING : stderr:   File "ui\kv\utils\load_kv.py", line 48, in load
2020-04-01 11:33:22,761 MainThread WARNING : stderr:   File "site-packages\kivy\lang\builder.py", line 368, in load_string
2020-04-01 11:33:22,762 MainThread WARNING : stderr:   File "site-packages\kivy\lang\parser.py", line 401, in __init__
2020-04-01 11:33:22,762 MainThread WARNING : stderr:   File "site-packages\kivy\lang\parser.py", line 507, in parse
2020-04-01 11:33:22,763 MainThread WARNING : stderr:   File "site-packages\kivy\lang\parser.py", line 484, in execute_directives
2020-04-01 11:33:22,763 MainThread WARNING : stderr: kivy.lang.parser.ParserException: Parser: File "D:\code\CPOS\dist\CPOS\ui\kv\ui_manager.kv", line 4:
2020-04-01 11:33:22,763 MainThread WARNING : stderr: ...
2020-04-01 11:33:22,763 MainThread WARNING : stderr:       2:
2020-04-01 11:33:22,764 MainThread WARNING : stderr:       3:<UiManager>:
2020-04-01 11:33:22,764 MainThread WARNING : stderr: >>    4:    #:import TopStateBar ui.kv.status_bar.top_bar
2020-04-01 11:33:22,764 MainThread WARNING : stderr:       5:    #:import ToolBar ui.kv.tool_bar.tool_bar
2020-04-01 11:33:22,764 MainThread WARNING : stderr:       6:    #:import CustomScreenManager ui.kv.base.screen_manager
2020-04-01 11:33:22,764 MainThread WARNING : stderr: ...
2020-04-01 11:33:22,764 MainThread WARNING : stderr: Unable to import package 'ui.kv.status_bar.top_bar'
2020-04-01 11:33:22,764 MainThread WARNING : stderr: 
2020-04-01 11:33:22,765 MainThread WARNING : stderr: During handling of the above exception, another exception occurred:
2020-04-01 11:33:22,765 MainThread WARNING : stderr: 
2020-04-01 11:33:22,765 MainThread WARNING : stderr: Traceback (most recent call last):
2020-04-01 11:33:22,765 MainThread WARNING : stderr:   File "pos_main.py", line 92, in <module>
2020-04-01 11:33:22,765 MainThread WARNING : stderr:   File "pos_main.py", line 79, in main
2020-04-01 11:33:22,766 MainThread WARNING : stderr:   File "site-packages\kivy\app.py", line 829, in run
2020-04-01 11:33:22,766 MainThread WARNING : stderr:   File "ui\kv\kivy_main.py", line 36, in build
2020-04-01 11:33:22,767 MainThread WARNING : stderr:   File "ui\kv\ui_manager.py", line 68, in __init__
2020-04-01 11:33:22,768 MainThread WARNING : stderr:   File "ui\kv\utils\load_kv.py", line 53, in load
2020-04-01 11:33:22,768 MainThread WARNING : stderr: ui.kv.utils.load_kv.KvLoadException: Load D:\code\CPOS\dist\CPOS\ui\kv\ui_manager.kv file error:Parser: File "D:\code\CPOS\dist\CPOS\ui\kv\ui_manager.kv", line 4:
2020-04-01 11:33:22,768 MainThread WARNING : stderr: ...
2020-04-01 11:33:22,769 MainThread WARNING : stderr:       2:
2020-04-01 11:33:22,769 MainThread WARNING : stderr:       3:<UiManager>:
2020-04-01 11:33:22,769 MainThread WARNING : stderr: >>    4:    #:import TopStateBar ui.kv.status_bar.top_bar
2020-04-01 11:33:22,769 MainThread WARNING : stderr:       5:    #:import ToolBar ui.kv.tool_bar.tool_bar
2020-04-01 11:33:22,769 MainThread WARNING : stderr:       6:    #:import CustomScreenManager ui.kv.base.screen_manager
2020-04-01 11:33:22,769 MainThread WARNING : stderr: ...
2020-04-01 11:33:22,769 MainThread WARNING : stderr: Unable to import package 'ui.kv.status_bar.top_bar'
```

**Comment by Wlodarski** [comment]
From what I understand, PyInstaller guesses which librairies to include by parsing the .py python files only, not the .kv files. Additional modules must be explicitly declared in your[ .spec file](https://pyinstaller.readthedocs.io/en/stable/spec-files.html)

So either you import the packages outside of the .kv files, in the .py side or you need declare them in the appropriate **data** and **binary** sections of your .spec file.

**Comment by rodrigovimieiro** [comment]
You have to specify it in the .spec file. Check this [example](https://github.com/kivymd/KivyMD/blob/master/demos/kitchen_sink/pyinstaller.spec) from official kivyMD. It worked for me.
