### ISSUE TITLE
UrlRequest callback results in Weakly-referenced object and WIN DEATH: null on Android

### ISSUE THREAD

**Issue by grandvalley** [kivy/kivy#6833]
**Software Versions**
* Python: 3.6.8
* OS: Ubuntu/Linux
* Kivy: Kivy==1.11.1
* Kivy installation method: pip

**Describe the bug**

I'm attempting to run a very basic example on Android of making a login (asynchronous) request with UrlRequest and then on success callback moving to another screen.

Synchronous request using python requests for example, works fine on Android.

```
class LoginScreen(Screen):

    def login(self, *args):

        manager = self.manager

        def login_success(req, result):
            manager.current = "ScreenTwo"

        values = {'username': 'test', 'password': 'test'}
        params = json.dumps(values)
        UrlRequest("%s/auth/login/" % (APP_SETTINGS.get('DOMAIN')), on_success=login_success, req_body=params, req_headers=APP_SETTINGS.get('HEADERS'))
```

**Expected behavior**

This works perfectly fine on Ubuntu but on Android it crashes and produces the logs below.

**Code and Logs and screenshots**
```python
04-23 11:07:43.470   232  6088 I BufferQueueProducer: [SurfaceView](this:0xb31dcc00,id:94,api:1,p:13892,c:232) queueBuffer: fps=28.73 dur=1009.55 max=508.64 min=7.49
04-23 11:07:43.480   232   232 I SurfaceFlinger: [Built-in Screen (type:0)] fps:28.735193,dur:1009.22,max:521.83,min:13.60
04-23 11:07:43.630  1143  1593 D NetworkController.MobileSignalController(0/2147483643): onSignalStrengthsChanged signalStrength=SignalStrength: 15 99 -15 -200 -15 -200 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 0x4 gsm|lte level=4
04-23 11:07:43.640  1143  1593 D NetworkController.MobileSignalController(0/2147483643): getMobileIconGroup(): 0
04-23 11:07:43.640  1143  1593 D NetworkController.MobileSignalController(0/2147483643): updateLTEMobileIconGroup(): 0
04-23 11:07:44.010   232   251 I BufferQueueProducer: [StatusBar](this:0xb3205400,id:7,api:1,p:1143,c:232) queueBuffer: fps=0.99 dur=1011.98 max=1011.98 min=1011.98
04-23 11:07:44.230 13892 13918 I python  : [INFO   ] [Base        ] Leaving application in progress...
04-23 11:07:44.230 13892 13918 I python  :  Traceback (most recent call last):
04-23 11:07:44.230 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/app/main.py", line 76, in <module>
04-23 11:07:44.240 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/odis/kivy/app.py", line 855, in run
04-23 11:07:44.240 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/odis/kivy/base.py", line 504, in runTouchApp
04-23 11:07:44.240 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/odis/kivy/core/window/window_sdl2.py", line 747, in mainloop
04-23 11:07:44.240 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/odis/kivy/core/window/window_sdl2.py", line 479, in _mainloop
04-23 11:07:44.250 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/odis/kivy/base.py", line 339, in idle
04-23 11:07:44.250 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/odis/kivy/clock.py", line 591, in tick
04-23 11:07:44.260 13892 13918 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
04-23 11:07:44.260 13892 13918 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
04-23 11:07:44.260 13892 13918 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
04-23 11:07:44.260 13892 13918 I python  :    File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
04-23 11:07:44.260 13892 13918 I python  :    File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
04-23 11:07:44.260 13892 13918 I python  :    File "/home/andrew/Desktop/openpickup/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/odis/kivy/weakmethod.py", line 56, in is_dead
04-23 11:07:44.260 13892 13918 I python  :  ReferenceError: weakly-referenced object no longer exists
04-23 11:07:44.260 13892 13918 I python  : Python for android ended.
04-23 11:07:44.340   713   713 V DeviceStorageMonitorService: restatDataDir : /data= 328347/360448
04-23 11:07:44.340   713   713 V DeviceStorageMonitorService: freeMemory=733720576
04-23 11:07:44.340   713   713 I DeviceStorageMonitorService: Posting Message again
04-23 11:07:44.450 13892 13918 D MALI    : osup_destructor:170: osup_destructor
04-23 11:07:44.650   713  1396 I ActivityManager: Killing 12702:com.android.chrome/u0a59 (adj 15): DHA:empty #31
04-23 11:07:44.650   713  1078 D NetworkPolicy: isUidForegroundLocked: 10098, mScreenOn: true, uidstate: 7, mProxSensorScreenOff: false
04-23 11:07:44.670   713  1497 D GraphicsStats: Buffer count: 5
04-23 11:07:44.670   713  1497 I WindowState: WIN DEATH: Window{91b7bcb u0 d0 p13892 org.test.odis/org.kivy.android.PythonActivity}
04-23 11:07:44.670   713  1466 I Sensors : AccelerometerSensor(0) setDelay : 66667000(ns)
04-23 11:07:44.670   713  1497 W WindowManager: Force-removing child win Window{86081fd u0 d0 p13892 SurfaceView} from container Window{91b7bcb u0 d0 p13892 org.test.odis/org.kivy.android.PythonActivity}
04-23 11:07:44.670   713  2072 I ActivityManager: Process org.test.odis (pid 13892)(adj 0) has died(109,522)
04-23 11:07:44.680   232  6088 I BufferQueueProducer: [org.test.odis/org.kivy.android.PythonActivity](this:0xb31dc000,id:93,api:1,p:-1,c:232) disconnect(P): api 1
04-23 11:07:44.670   713  2072 D ActivityManager: cleanUpApplicationRecord -- 13892
04-23 11:07:44.680   232  6088 I BufferQueueConsumer: [org.test.odis/org.kivy.android.PythonActivity](this:0xb31dc000,id:93,api:1,p:-1,c:232) getReleasedBuffers: returning mask 0xffffffffffffffff
04-23 11:07:44.680   232  6088 I BufferQueueProducer: [SurfaceView](this:0xb31dcc00,id:94,api:1,p:-1,c:232) disconnect(P): api 1
04-23 11:07:44.680   232  6088 I BufferQueueConsumer: [SurfaceView](this:0xb31dcc00,id:94,api:1,p:-1,c:232) getReleasedBuffers: returning mask 0xffffffffffffffff
04-23 11:07:44.680   232  6088 D GraphicBuffer: free, handle(0xb59ac0a0) (w:540 h:924 s:544 f:0x1 u:0x000b00)
04-23 11:07:44.680   232  6088 I [MALI][Gralloc]: [-]hnd(0xb59ac0a0), client(30), share_fd(54)
04-23 11:07:44.680   232  6088 D GraphicBuffer: free, handle(0xb5961180) (w:540 h:924 s:544 f:0x1 u:0x000b00)
04-23 11:07:44.680   232  6088 I [MALI][Gralloc]: [-]hnd(0xb5961180), client(30), share_fd(73)
04-23 11:07:44.680   232  6088 I SurfaceFlinger: id=94 Removed TurfaceView (4/8)
04-23 11:07:44.680   232  6088 I SurfaceFlinger: EventThread Client Pid (13892) disconnected by (232)
04-23 11:07:44.680   232  6088 I SurfaceFlinger: EventThread Client Pid (13892) disconnected by (232)
04-23 11:07:44.680   348   381 D GuiExt  : [GuiExtS] binder of dump tunnel(RB-0xb3e2cfb8) died
04-23 11:07:44.680   713  2072 D ActivityManager: removeProcessNameLocked mProcessNames.remove pid=13892 ,hash=141578126 ,name=org.test.odis
04-23 11:07:44.680   713  2072 W ActivityManager: Force removing ActivityRecord{d387424 u0 org.test.odis/org.kivy.android.PythonActivity t16}: app died, no saved state
04-23 11:07:44.680   232  1760 I SurfaceFlinger: id=94 Removed TurfaceView (-2/8)
04-23 11:07:44.680   713  1497 D InputDispatcher: Focus left window: 13892
04-23 11:07:44.680   232   232 I BufferQueueConsumer: [SurfaceView](this:0xb31dcc00,id:94,api:1,p:-1,c:-1) disconnect(C)
04-23 11:07:44.680   232   232 D GraphicBuffer: free, handle(0xb5960aa0) (w:540 h:924 s:544 f:0x1 u:0x000b00)
04-23 11:07:44.680   232   232 I [MALI][Gralloc]: [-]hnd(0xb5960aa0), client(30), share_fd(59)
04-23 11:07:44.680   232   232 I BufferQueue: [SurfaceView](this:0xb31dcc00,id:94,api:1,p:-1,c:-1) ~BufferQueueCore
04-23 11:07:44.680   232   232 I SurfaceFlinger: [Built-in Screen (type:0)] fps:17.448242,dur:1203.56,max:667.88,min:15.99
04-23 11:07:44.690   232  1760 I SurfaceFlinger: id=93 Removed QythonActiv (5/7)
04-23 11:07:44.690   232  2129 I SurfaceFlinger: id=93 Removed QythonActiv (-2/7)
04-23 11:07:44.690   232   251 I SurfaceFlinger: [SF client] DEL(0xb5cd2980) for (713:system_server)
04-23 11:07:44.690   232   251 D SurfaceFlinger:     remove: org.test.odis/org.kivy.android.PythonActivity
04-23 11:07:44.690   232   251 I SurfaceFlinger: id=93 Removed QythonActiv (-2/7)
04-23 11:07:44.690   352   352 I Zygote  : Process 13892 exited cleanly (255)
04-23 11:07:44.690  2220  2220 V SamsungIME: onTrimMemory Level = 20
04-23 11:07:44.690   713  2173 W WindowManager: Failed looking up window
04-23 11:07:44.690   713  2173 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@7b32e54 does not exist
04-23 11:07:44.690   713  2173 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:15261)
04-23 11:07:44.690   713  2173 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:15252)
04-23 11:07:44.690   713  2173 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1824)
04-23 11:07:44.690   713  2173 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
04-23 11:07:44.690   713  2173 I WindowState: WIN DEATH: null
04-23 11:07:44.700   713  2072 D InputDispatcher: Focused application set to: xxxx
04-23 11:07:44.700   713  2072 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1170000  uid : 1000  pid : 713  pkgName : ACTIVITY_RESUME_BOOSTER@11
04-23 11:07:44.700   713  2072 D ActivityManager: mDVFSHelper.acquire()
04-23 11:07:44.700   232   232 I BufferQueueConsumer: [org.test.odis/org.kivy.android.PythonActivity](this:0xb31dc000,id:93,api:1,p:-1,c:-1) disconnect(C)
04-23 11:07:44.700   232   232 D GraphicBuffer: free, handle(0xb5960d20) (w:540 h:960 s:544 f:0x1 u:0x000b00)
04-23 11:07:44.700   232   232 I [MALI][Gralloc]: [-]hnd(0xb5960d20), client(30), share_fd(71)
04-23 11:07:44.700   232   232 I BufferQueue: [org.test.odis/org.kivy.android.PythonActivity](this:0xb31dc000,id:93,api:1,p:-1,c:-1) ~BufferQueueCore

```

**Additional context**

buildozer.spec

requirements = python3,kivy,git+https://github.com/HeaTTheatR/KivyMD.git,requests,plyer,certifi,openssl

android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION,CAMERA

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 17c

version of Android: 6.0.1

**Comment by grandvalley** [comment]
Nevermind.

Garbage collector picks up UrlRequest.

Just reference it like:

`self.req = UrlRequest`

Solves the issue...

**Comment by levexis** [comment]
I just wasted an hour or two tracking this down. The docs need updating to mention the weak refs / garbage collection. A more "realistic example" would be helpful as nobody is writing their code in root scope!

**Comment by matham** [comment]
A PR is welcome.
