### ISSUE TITLE
Kivy's hookspath() stops PyInstaller

### ISSUE THREAD

**Issue by thomas-pilgaard** [kivy/kivy#6871]
**Software Versions**
Kivy: v1.11.1
PyInstaller: 3.6
Python: 3.7.3
Platform: Linux-5.5.0-0.bpo.2-amd64-x86_64-with-debian-10.3

**Describe the bug**
Using 

```
a = Analysis(...
             hookspath=hookspath(),
             ...)
```

in my PyInstaller .spec file, as described in

https://kivy.org/doc/stable/api-kivy.tools.packaging.pyinstaller_hooks.html

causes PyInstaller to stop with an AssertionError:

```
INFO: Caching module graph hooks...
 Traceback (most recent call last):
1057 WARNING: stderr: Traceback (most recent call last):
   File "/media/build/mosaic/venv/bin/pyinstaller", line 8, in <module>
1058 WARNING: stderr:   File "/media/build/mosaic/venv/bin/pyinstaller", line 8, in <module>
     sys.exit(run())
1058 WARNING: stderr:     sys.exit(run())
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
1058 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
     run_build(pyi_config, spec_file, **vars(args))
1059 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
1059 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
1066 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 734, in main
1066 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 734, in main
     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
1067 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 681, in build
1067 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 681, in build
     exec(code, spec_namespace)
1067 WARNING: stderr:     exec(code, spec_namespace)
   File "mosaic.spec", line 120, in <module>
1067 WARNING: stderr:   File "mosaic.spec", line 120, in <module>
     cipher=cipher_)
1068 WARNING: stderr:     cipher=cipher_)
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 244, in __init__
1068 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 244, in __init__
     self.__postinit__()
1068 WARNING: stderr:     self.__postinit__()
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
1069 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
     self.assemble()
1069 WARNING: stderr:     self.assemble()
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 343, in assemble
1069 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 343, in assemble
     excludes=self.excludes, user_hook_dirs=self.hookspath)
1070 WARNING: stderr:     excludes=self.excludes, user_hook_dirs=self.hookspath)
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 734, in initialize_modgraph
1070 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 734, in initialize_modgraph
     user_hook_dirs=user_hook_dirs,
1071 WARNING: stderr:     user_hook_dirs=user_hook_dirs,
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 116, in __init__
1071 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 116, in __init__
     self._reset(user_hook_dirs)
1071 WARNING: stderr:     self._reset(user_hook_dirs)
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 134, in _reset
1071 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 134, in _reset
     self._hooks = self._cache_hooks("")
1072 WARNING: stderr:     self._hooks = self._cache_hooks("")
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 215, in _cache_hooks
1072 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 215, in _cache_hooks
     return ModuleHookCache(self, hook_dirs)
1072 WARNING: stderr:     return ModuleHookCache(self, hook_dirs)
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 100, in __init__
1082 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 100, in __init__
     self._cache_hook_dirs(hook_dirs)
1083 WARNING: stderr:     self._cache_hook_dirs(hook_dirs)
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 133, in _cache_hook_dirs
1083 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 133, in _cache_hook_dirs
     hook_module_name_prefix=self._hook_module_name_prefix,
1083 WARNING: stderr:     hook_module_name_prefix=self._hook_module_name_prefix,
   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 289, in __init__
1084 WARNING: stderr:   File "/media/build/mosaic/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 289, in __init__
     assert self.hook_module_name not in HOOKS_MODULE_NAMES
1084 WARNING: stderr:     assert self.hook_module_name not in HOOKS_MODULE_NAMES
 AssertionError
1084 WARNING: stderr: AssertionError
```

According to PyInstaller issues

https://github.com/pyinstaller/pyinstaller/issues/4626
https://github.com/pyinstaller/pyinstaller/issues/1835

the functionality of overloading a hook is not intended to be supported by PyInstaller.

Furthermore, the suggestion of a `--prefer-custom` option appears neither to be at or near the implementation stage. Answers to the issues suggest editing Pyinstaller's hook files in-place as a solution. This seems unsustainable in the long term, as such modifications could possibly be wiped by future updates or cause such updates to behave buggily. On the other hand, importing all modules all the time as happens without modification, is not the right solution for every use case either.

**Expected behavior**
It would be helpful if Kivy could find a way to re-enable hookspath() to overload `hook-kivy.py` without PyInstaller interpreting it as a problem.

**To Reproduce**
As far as I can tell, attempting to overload PyInstaller's `hook-*.py` files by creating a same-named file with your own content in a path indicated to hookpath in the creation of an Analysis object in the .spec file, causes PyInstaller to stop with this AssertionError.

**Comment by matham** [comment]
Yeah, that's something I ran into and fixed it on my side by running `python -c "import os, PyInstaller; os.remove(os.path.join(os.path.dirname(PyInstaller.__file__), 'hooks', 'hook-kivy.py'))"` to remove the hook that is distributed with pyinstaller.

As [you can see](https://github.com/pyinstaller/pyinstaller/pull/1678), we were strongly opposed to including kivy hooks into pyinstaller, until we were re-assured that we can overwrite the hooks.

I suppose the best advice is to not show how to overwrite the hooks in our docs.

**Comment by thomas-pilgaard** [comment]
Thank you for the suggestion on how to fix the issue on my end. Removing the hook provided by PyInstaller does seem to offer the path of least resistance in the short term.

I find the link to the discussion of whether to add the hook to PyInstaller very enlightening. It looks to me like an example of how clear communication between multiple stakeholders can be very challenging and easily lead to unintended results.

Being new to Kivy, I realise that I don't see the full picture. Having said that, it seems to me that a helpful direction moving forward could be to request having the hook removed from PyInstaller and continue offering a similar hook or even a selection of example hooks with Kivy. This would provide increased transparency to users of Kivy about how module importing works in PyInstaller, while enabling overloading the hook without issues relating to how PyInstaller interprets conflicts with its included hooks. User-control of the hook seems absolutely necessary to control what is added to your package. I see suggesting such a change to PyInstaller as a reasonable action. The initial inclusion was made years ago and friction, between PyInstaller's now clearer policy on handling of included hooks and the need for flexibility in a framework such as Kivy, have become abundantly clear since then.

Regarding learning Kivy as a newcomer and diagnosing a problem such as this, I feel like it took significantly more effort than it should have to realize what my problem with controlling module imports to PyInstaller was. There are multiple contributing factors I think, such as building on/for a Linux distribution, which is not well-documented for Kivy, and having a problem caused by the interaction of two separate-except-for-that-one-detail systems. I think a note in the documentation, whether in a build example or in the hook documentation, about this issue, with a recommendation of how to work constructively with the limitation, could go a long way towards helping users managing the issue in the future.

**Comment by Legorooj** [comment]
@matham I'm a developer of PyInsatller, and have good news for you and the other kivy devs: PyInstaller now supports having the kivy hooks and entire compatibility layer in kivy itself as of next release (4.0 - ETA may-june).
