### ISSUE TITLE
AsyncImage loading image on pc but not on Android

### ISSUE THREAD

**Issue by darkbite** [kivy/kivy#6907]
**Software Versions**
* Python: python3
* OS: Android
* Kivy: 1.11
* Kivy installation method: from buildozer

**Describe the bug**
while trying to use AsyncImage method got  urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>, the same code without modifications if run on pc work just great.

**Expected behavior**
load images .

**main.py**
```python
class ImgDetalle(AsyncImage):
    urlImg = StringProperty()
    pass
```

**main.kv**
```python
<ImgDetalle>:
    source: self.urlImg
    size_hint_y: None
    size: dp(300), dp(300)
```

**ABD log from the app**
```python
05-30 18:20:36.817  9799  9987 I python  : [ERROR  ] [Loader      ] Failed to load image <https://images2.listindiario.com/n/content/620/619827/p/680x460/202005302158471.jpeg>
05-30 18:20:36.817  9799  9987 I python  : Traceback (most recent call last):
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/urllib/request.py", line 1319, in do_open
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/http/client.py", line 1230, in request
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/http/client.py", line 1276, in _send_request
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/http/client.py", line 1225, in endheaders
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/http/client.py", line 1004, in _send_output
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/http/client.py", line 944, in send
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/http/client.py", line 1399, in connect
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/ssl.py", line 500, in wrap_socket
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/ssl.py", line 1040, in _create
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/ssl.py", line 1309, in do_handshake
05-30 18:20:36.817  9799  9987 I python  : ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
05-30 18:20:36.817  9799  9987 I python  :
05-30 18:20:36.817  9799  9987 I python  : During handling of the above exception, another exception occurred:
05-30 18:20:36.817  9799  9987 I python  :
05-30 18:20:36.817  9799  9987 I python  : Traceback (most recent call last):
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/main/kivy/loader.py", line 342, in _load_urllib
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/urllib/request.py", line 525, in open
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/urllib/request.py", line 542, in _open
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/urllib/request.py", line 502, in _call_chain
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/urllib/request.py", line 1362, in https_open
05-30 18:20:36.817  9799  9987 I python  :   File "/mnt/c/users/papi_/desktop/scrappingnews/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/urllib/request.py", line 1322, in do_open
05-30 18:20:36.817  9799  9987 I python  : urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```

**Comment by darkbite** [comment]
solved it by specifying the python version and installing kivy from a local dir. like this:

requirements = python3==3.8.3, kivy, kivymd, requests, beautifulsoup4, certifi, openssl
requirements.source.kivy = /mnt/c/users/papi_/desktop/kivy-master

Hope to help those struggling just like i was :)
