### ISSUE TITLE
2.0.0rc3 and KivyMD

### ISSUE THREAD

**Issue by Ham-Merhead** [kivy/kivy#6957]
**Software Versions**
* Python:  3.8.2
* OS:  Windows 10
* Kivy: 2.0.0rc3
* Kivy installation method:  pip

**Describe the bug**
Using KivyMD 1.104.1

2.0.0rc2  the example below gives:
`[WARNING] [ColorParser ] Invalid color format for '#'`

2.0.0rc3 the example below gives:
 ```
Traceback (most recent call last):
   File "C:\Users\Bobf\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 701, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 527, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 2023, in kivy.properties.ColorProperty.convert
 ValueError: MDTabsLabel.color must have 3 or 4 components (got [])
```

**Expected behavior**

**To Reproduce**
Use KivyMD 1.104.1

**Code and Logs and screenshots**
```python
from kivymd.app import MDApp
from kivymd.uix.tab import MDTabs,MDTabsBase
from kivymd.uix.boxlayout import MDBoxLayout

class Tab(MDBoxLayout, MDTabsBase):
    def __init__(self, **kwargs):
        super(Tab, self).__init__(**kwargs)
        pass
    
class MyApp(MDApp):

    def build(self):
        t = MDTabs()
        b = Tab(text='foo')
        return t

if __name__ == '__main__':
    MyApp().run()
```

**Additional context**

**Comment by Ham-Merhead** [comment]
Also filed here https://github.com/HeaTTheatR/KivyMD/issues/359

**Comment by matham** [comment]
We don't support KivyMD as it is a independent project and the bug seems to be in that code.
