### ISSUE TITLE
Cant install kivy on ubuntu 20.04 python3.8.2

### ISSUE THREAD

**Issue by tanjilk** [kivy/kivy#7063]
**Software Versions**
* Python: Python 3.8.2
* OS: Ubuntu 20.04
* Kivy installation method: pip3 install kivy
Im trying to install kivy with pip but im having this error

```
(kivy_venv) ➜  ~ pip --version
pip 18.1 from /home/tanjil/kivy_venv/lib/python3.8/site-packages/pip (python 3.8)
(kivy_venv) ➜  ~ pip3 install kivy
Collecting kivy
  Using cached https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
      Failed building wheel for cython
    ERROR: Failed to build one or more wheels
     Traceback (most recent call last):
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
         subprocess.check_call(cmd)
       File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
         raise CalledProcessError(retcode, cmd)
     subprocess.CalledProcessError: Command '['/home/tanjil/kivy_venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpfb5bnooa', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    
     The above exception was the direct cause of the following exception:
    
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-install-lvyc3wtz/kivy/setup.py", line 1073, in <module>
         setup(
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
         _install_setup_requires(attrs)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
         dist.fetch_build_eggs(dist.setup_requires)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
         resolved_dists = pkg_resources.working_set.resolve(
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve
         dist = best[req.key] = env.best_match(
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match
         return self.obtain(req, installer)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain
         return installer(requirement)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
         return fetch_build_egg(self, req)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
         raise DistutilsError(str(e)) from e
     distutils.errors.DistutilsError: Command '['/home/tanjil/kivy_venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpfb5bnooa', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    Using setuptools
    Using this graphics system: OpenGL
    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)
    
    b"Package gstreamer-1.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `gstreamer-1.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'gstreamer-1.0' found\n"
    
    WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)
    
    b"Package sdl2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `sdl2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'sdl2' found\nPackage SDL2_ttf was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_ttf.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_ttf' found\nPackage SDL2_image was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_image.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_image' found\nPackage SDL2_mixer was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_mixer.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_mixer' found\n"
    
    WARNING: A problem occurred while running pkg-config --libs --cflags pangoft2 (code 1)
    
    b"Package pangoft2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `pangoft2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'pangoft2' found\n"
    
    ERROR: Dependency for context.pyx not resolved: config.pxi
    ERROR: Dependency for compiler.pyx not resolved: config.pxi
    ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for fbo.pyx not resolved: config.pxi
    ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for instructions.pyx not resolved: config.pxi
    ERROR: Dependency for opengl.pyx not resolved: config.pxi
    ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
    ERROR: Dependency for shader.pyx not resolved: config.pxi
    ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for texture.pyx not resolved: config.pxi
    ERROR: Dependency for vbo.pyx not resolved: config.pxi
    ERROR: Dependency for vertex.pyx not resolved: config.pxi
    ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for cgl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
    ERROR: Dependency for svg.pyx not resolved: config.pxi
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lvyc3wtz/kivy/

```
Also i tried with `python3.8 -m pip install kivy`  but i still can't install kivy.

**Comment by tanjilk** [comment]
I had run the `pip install --upgrade pip setuptools wheel`but i still cant install kivy
```
(kivy_venv) ➜  ~ python3.8 -m pip install kivy
Collecting kivy
  Using cached https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
      Failed building wheel for cython
    ERROR: Failed to build one or more wheels
     Traceback (most recent call last):
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
         subprocess.check_call(cmd)
       File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
         raise CalledProcessError(retcode, cmd)
     subprocess.CalledProcessError: Command '['/home/tanjil/kivy_venv/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4kfpdc9b', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    
     The above exception was the direct cause of the following exception:
    
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-install-fl74v4m3/kivy/setup.py", line 1073, in <module>
         setup(
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
         _install_setup_requires(attrs)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
         dist.fetch_build_eggs(dist.setup_requires)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
         resolved_dists = pkg_resources.working_set.resolve(
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve
         dist = best[req.key] = env.best_match(
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match
         return self.obtain(req, installer)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain
         return installer(requirement)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
         return fetch_build_egg(self, req)
       File "/home/tanjil/kivy_venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
         raise DistutilsError(str(e)) from e
     distutils.errors.DistutilsError: Command '['/home/tanjil/kivy_venv/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4kfpdc9b', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    Using setuptools
    Using this graphics system: OpenGL
    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)
    
    b"Package gstreamer-1.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `gstreamer-1.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'gstreamer-1.0' found\n"
    
    WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)
    
    b"Package sdl2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `sdl2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'sdl2' found\nPackage SDL2_ttf was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_ttf.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_ttf' found\nPackage SDL2_image was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_image.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_image' found\nPackage SDL2_mixer was not found in the pkg-config search path.\nPerhaps you should add the directory containing `SDL2_mixer.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'SDL2_mixer' found\n"
    
    WARNING: A problem occurred while running pkg-config --libs --cflags pangoft2 (code 1)
    
    b"Package pangoft2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `pangoft2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'pangoft2' found\n"
    
    ERROR: Dependency for context.pyx not resolved: config.pxi
    ERROR: Dependency for compiler.pyx not resolved: config.pxi
    ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for fbo.pyx not resolved: config.pxi
    ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for instructions.pyx not resolved: config.pxi
    ERROR: Dependency for opengl.pyx not resolved: config.pxi
    ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
    ERROR: Dependency for shader.pyx not resolved: config.pxi
    ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for texture.pyx not resolved: config.pxi
    ERROR: Dependency for vbo.pyx not resolved: config.pxi
    ERROR: Dependency for vertex.pyx not resolved: config.pxi
    ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for cgl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
    ERROR: Dependency for svg.pyx not resolved: config.pxi
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-fl74v4m3/kivy/
```

**Comment by tanjilk** [comment]
How can i install it?

**Comment by tanjilk** [comment]
As here  
```
  kivy/include/gl_redirect.h:72:13: fatal error: GL/gl.h: No such file or directory
     72 | #   include <GL/gl.h>
        |             ^~~~~~~~~
 ```
Is necessary to have **opengl dev headers** and to install the kivy make sure that you have the necessary packages.   
I ran with `sudo apt-get install build-essential libgl1-mesa-dev` to get the opengl dev headers and after that install the kivy with   
`➜  ~ pip install https://github.com/kivy/kivy/archive/master.zip`
