### ISSUE TITLE
Font not found error: cour.ttf

### ISSUE THREAD

**Issue by hioymaci** [kivy/kivy#7089]
**Software Versions**
* Python: 3.6.7
* OS: Ubuntu 18.04.5 LTS x64
* Kivy: 1.11.1
* Kivy installation method: conda

**Describe the bug**
I run the application in Windows 10 and there is no problem. But I run in Ubuntu 18 python gives this error:

>  Traceback (most recent call last):
>    File "main.py", line 591, in <module>
>      main()
>    File "main.py", line 587, in main
>      app.run()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/app.py", line 855, in run
>      runTouchApp()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/base.py", line 504, in runTouchApp
>      EventLoop.window.mainloop()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
>      self._mainloop()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
>      EventLoop.idle()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/base.py", line 348, in idle
>      Clock.tick_draw()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/clock.py", line 598, in tick_draw
>      self._process_events_before_frame()
>    File "kivy/_clock.pyx", line 427, in kivy._clock.CyClockBase._process_events_before_frame
>    File "kivy/_clock.pyx", line 467, in kivy._clock.CyClockBase._process_events_before_frame
>    File "kivy/_clock.pyx", line 465, in kivy._clock.CyClockBase._process_events_before_frame
>    File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/uix/label.py", line 413, in texture_update
>      self._label.refresh()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 759, in refresh
>      self.resolve_font_name()
>    File "/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 356, in resolve_font_name
>      raise IOError('Label: File %r not found' % fontname)
>  OSError: Label: File 'cour.ttf' not found
> 

**Expected behavior**
There should no error.

**To Reproduce**
I do not use specifically cour.tff font. I do not know which code use it.

**Additional context**
I fixed the problem via downloading cour.tff on the internet then I added it to this folder: 

> /home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/data/fonts

This is code in _/home/halil/.conda/envs/chargegen_test/lib/python3.6/site-packages/kivy/core/text/__init__.py_

```
if filename is None:
    # XXX for compatibility, check directly in the data dir
    filename = pep8_fn = os.path.join(kivy_data_dir, fontname)
    if not os.path.exists(pep8_fn) or not os.path.isfile(pep8_fn):
        raise IOError('Label: File %r not found' % fontname)
```

**Comment by hioymaci** [comment]
I found that I added that font in kv file. My search algorithm not found it, sorry. 
```
            Label:
                font_name: 'cour'
```
