### ISSUE TITLE
KIVY_GLES_LIMITS doesn't work

### ISSUE THREAD

**Issue by kalluwa** [kivy/kivy#7105]
**Software Versions**
* Python:
(kivy_venv) D:\githubs\kivy\kivy_venv\share\kivy-examples\3Drendering>python --version
Python 3.7.0

* OS:
win10
* Kivy:
1.11.1
* Kivy installation method:
python -m pip install kivy==1.11.1
**Describe the bug**
 "OverflowError: value too large to convert to unsigned short"  even with 
```
import os
os.environ['KIVY_GLES_LIMITS'] = "0"
```

**Expected behavior**
showing the window 

**To Reproduce**
https://kivy.org/doc/stable/examples/gen__3Drendering__main__py.html
replace monkey.obj with a large indices(>65535) model

**Code and Logs and screenshots**
```python
(kivy_venv) D:\githubs\kivy\kivy_venv\share\kivy-examples\3Drendering>python main.py
[INFO   ] [Logger      ] Record log in C:\Users\kk\.kivy\logs\kivy_20-09-25_16.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "D:\githubs\kivy\kivy_venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\githubs\kivy\kivy_venv\Scripts\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.13587 Compatibility Profile Context 19.40.48 26.20.14048.2'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon(TM) Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Shader      ] Read <D:\githubs\kivy\kivy_venv\share\kivy-examples\3Drendering\simple.glsl>
1511424
188928
 Traceback (most recent call last):
   File "main.py", line 80, in <module>
     RendererApp().run()
   File "D:\githubs\kivy\kivy_venv\lib\site-packages\kivy\app.py", line 829, in run
     root = self.build()
   File "main.py", line 76, in build
     return Renderer()
   File "main.py", line 37, in __init__
     self.setup_scene()
   File "main.py", line 69, in setup_scene
     mode='triangles',
   File "kivy\graphics\vertex_instructions.pyx", line 401, in kivy.graphics.vertex_instructions.Mesh.__init__
   File "kivy\graphics\vertex_instructions.pyx", line 491, in kivy.graphics.vertex_instructions.Mesh.indices.__set__
   File "kivy\graphics\memory.pxi", line 72, in kivy.graphics.vertex_instructions._ensure_ushort_view
 OverflowError: value too large to convert to unsigned short
```

**Additional context**
https://github.com/kivy/kivy/pull/2430/files
https://github.com/kivy/kivy/pull/2809/files
https://kivy.org/doc/stable/guide/environment.html
https://kivy.org/doc/stable/examples/gen__3Drendering__main__py.html
https://github.com/kivy/kivy/pull/2430

**Comment by Neizvestnyj** [comment]
Same error
