### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf' on apk

### ISSUE THREAD

**Issue by MS-Jahan** [kivy/kivy#7121]
**Software Versions**
* Python: 3.8.5 (default, Sep  5 2020, 10:50:12)
* OS: Manjaro Linux
* Kivy: v1.11.1
* Kivy installation method: through pip

**Describe the bug**
I've created an app which uses pyrebase module for firebase. I've created the apk with buildozer. But when I want to post something (post data to firebase, works on PC), app just closes automatically.

I've run _adb logcat_ and found,
`ModuleNotFoundError: No module named 'google.protobuf'`

**adb logcat**

```
10-02 12:36:39.615 11970 11998 I python  : [INFO   ] [Base        ] Leaving application in progress...
10-02 12:36:39.617 11970 11998 I python  :  Traceback (most recent call last):
10-02 12:36:39.618 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/app/main.py", line 924, in <module>
10-02 12:36:39.620 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivy/app.py", line 950, in run
10-02 12:36:39.622 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivy/base.py", line 560, in runTouchApp
10-02 12:36:39.624 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivy/base.py", line 334, in mainloop
10-02 12:36:39.627 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivy/base.py", line 378, in idle
10-02 12:36:39.629 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivy/base.py", line 329, in dispatch_input
10-02 12:36:39.631 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivy/base.py", line 295, in post_dispatch_input
10-02 12:36:39.633 11970 11998 I python  :    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
10-02 12:36:39.633   921  3007 W Bundle  : Key android.icon expected Parcelable but value was a java.lang.Integer.  The default value <null> was returned.
10-02 12:36:39.634   921  3007 W Bundle  : Attempt to cast generated internal exception:
10-02 12:36:39.634   921  3007 W Bundle  : java.lang.ClassCastException: java.lang.Integer cannot be cast to android.os.Parcelable
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.os.Bundle.getParcelable(Bundle.java:946)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.app.Notification.fixDuplicateExtra(Notification.java:2790)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.app.Notification.fixDuplicateExtras(Notification.java:2780)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.app.Notification.readFromParcelImpl(Notification.java:2178)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.app.Notification.<init>(Notification.java:2106)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.service.notification.StatusBarNotification.<init>(StatusBarNotification.java:104)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.service.notification.StatusBarNotification$1.createFromParcel(StatusBarNotification.java:194)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.service.notification.StatusBarNotification$1.createFromParcel(StatusBarNotification.java:191)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.service.notification.IStatusBarNotificationHolder$Stub$Proxy.get(IStatusBarNotificationHolder.java:93)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.service.notification.NotificationListenerService$NotificationListenerWrapper.onNotificationPosted(NotificationListenerService.java:1226)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:72)
10-02 12:36:39.634   921  3007 W Bundle  : 	at android.os.Binder.execTransact(Binder.java:756)
10-02 12:36:39.635 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivymd/uix/behaviors/ripplebehavior.py", line 294, in on_touch_up
10-02 12:36:39.642 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivymd/uix/button.py", line 947, in on_touch_up
10-02 12:36:39.644 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/kivy/uix/behaviors/button.py", line 179, in on_touch_up
10-02 12:36:39.646 11970 11998 I python  :    File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
10-02 12:36:39.648 11970 11998 I python  :    File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
10-02 12:36:39.650 11970 11998 I python  :    File "kivy/_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
10-02 12:36:39.652 11970 11998 I python  :    File "<string>", line 989, in <lambda>
10-02 12:36:39.654 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/app/main.py", line 613, in post
10-02 12:36:39.656 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/pyrebase/__init__.py", line 1, in <module>
10-02 12:36:39.658 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/pyrebase/pyrebase.py", line 18, in <module>
10-02 12:36:39.660 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/gcloud/storage/__init__.py", line 43, in <module>
10-02 12:36:39.662 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/gcloud/storage/blob.py", line 31, in <module>
10-02 12:36:39.664 11970 11998 I python  :    File "/home/sjs/nasa/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/greenx/gcloud/_helpers.py", line 28, in <module>
10-02 12:36:39.667 11970 11998 I python  :  ModuleNotFoundError: No module named 'google.protobuf'
10-02 12:36:39.667 11970 11998 I python  : Python for android ended.
10-02 12:36:39.929 12241 12272 I LogSaver: LogSaver new instance with filename: carrier_services
10-02 12:36:39.966 12241 12272 I BugleBackup: Registering preference change listener for "bugle".
10-02 12:36:40.040   652   790 D AlarmManager: waitForAlarm result:4currentTime=1601620600040, elapsedRealtime=789823888
10-02 12:36:40.040   652   790 D AlarmManager: triggerAlarmsLocked firstBatch = firstWakeup : Batch{19524b9 num=1 start=789828029 end=789828029} mNextWakeup = 789823888
10-02 12:36:40.040   652   790 V AlarmManager: Alarm to uid=1000 listener=android.app.AlarmManager$ListenerWrapper@dc730fe
10-02 12:36:40.040   652   652 D JobScheduler.Time: evaluateConstraint job for: com.whatsapp sourceUid:10127 app is not started!!
10-02 12:36:40.041   652   790 D AlarmManager: sending alarm.type = 2, action = null, cn = null, operation = null
10-02 12:36:40.041   652   790 D AlarmManagerService: set alarm to kernel: 789828.029000000, type=2 
10-02 12:36:40.045   652   652 V AlarmManager: set(null) : type=2 triggerAtTime=790755584 win=698771 tElapsed=790755584 maxElapsed=791454355 interval=0 flags=0x0
10-02 12:36:40.047   652   652 D AlarmManagerService: set alarm to kernel: 789828.029000000, type=2 
10-02 12:36:40.048   652   652 I AlarmManager: alarmComplete() from android.app.AlarmManager$ListenerWrapper@dc730fe
10-02 12:36:40.067   292   292 D PowerHAL: ###Enter screen_rotation scene bgn###
```

**To Reproduce**
```
def post(self, *args):
        global localID, userdata
    
        #from screens import fbconfig
        import pyrebase
        ts = str(time.time()).replace('.', '-')
        firebaseConfig = fbconfig.posts_firebaseConfig
        firebase = pyrebase.initialize_app(firebaseConfig)
        storage = firebase.storage()
        db = firebase.database()
        
        
        data = {
            'fullname': userdata['fullname'],
            'pic': userdata['pic']
        }
        db.child(localID).update(data)
        
        
        data = {
            'text': self.ids.post_txt.text
        }
        db.child(localID).child(ts).update(data)
                
        
        files_url_dict = {}
        
        for i, file in enumerate(self.files):
            fname = file.split('.')
            db_file_location = "posts/" + localID + "/" + ts + "/" + str(i) + '.' + fname[len(fname) - 1]
            storage.child(db_file_location).put(file)
            furl = storage.child(db_file_location).get_url(None)
            files_url_dict[i] = furl
        


        db.child(localID).child(ts).child('files').set(files_url_dict)


        posts = db.child("posts").get()
        length = len(posts.val())
        print(posts, length)

        data = {str(length): localID + ", " + ts}
        db.child('posts').update(data)
        Snackbar(text="Posted Successfully!").open()
        self.files = []
        toast("Post will be judged by moderators.")

```

**Buildozer.spec file**
```
[app]

# (str) Title of your application
title = GreenX

# (str) Package name
package.name = greenx

# (str) Package domain (needed for android/ios packaging)
package.domain = org.bd

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,txt,ttf

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = venv, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy==5ed7a1335bd66c4365b666eccce049f27ebfc51b,requests,chardet,idna,urllib3,openssl,https://github.com/kivymd/KivyMD/archive/master.zip,wget,numpy, oauth2client, matplotlib, kivy_garden.mapview, pyparsing, cycler, dateutil,pyrebase,sdl2_ttf==2.0.15,futures,certifi,httplib2,pyasn1,gcloud,pycrypto,pyasn1_modules,rsa,google,python3,kivy,gspread,oauth2client,httplib2,pyopenssl,google-auth-oauthlib,pyasn1,pyasn1-modules,rsa,requests,google-auth-httplib2,openssl,google-api-python-client,google-auth,credentials,oauth2,google,cachetools,urllib3,chardet,idna,requests_oauthlib,oauthlib,protobuf,google-cloud,six

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements = matplotlib,mapview

# (str) Presplash of the application
presplash.filename = %(source.dir)s/logo.png

# (str) Icon of the application
icon.filename = %(source.dir)s/logo.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = Notifier:notifier.py

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
android.accept_sdk_license = True

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = develop

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

**Comment by MS-Jahan** [comment]
Fixed after adding some other requirements.

```
requirements = hostpython3==3.7.5, python3==3.7.5,kivy==5ed7a1335bd66c4365b666eccce049f27ebfc51b,requests,chardet,idna,urllib3,openssl,https://github.com/kivymd/KivyMD/archive/master.zip,numpy, oauth2client, matplotlib, kivy_garden.mapview, pyparsing, cycler, dateutil,pyrebase4,sdl2_ttf==2.0.15,futures,certifi,httplib2,pyasn1,gcloud,pycrypto,pyasn1_modules,rsa,google,gspread,oauth2client,httplib2,pyopenssl,google-auth-oauthlib,pyasn1,pyasn1-modules,rsa,requests,google-auth-httplib2,openssl,google-api-python-client,google-auth,credentials,oauth2,google,cachetools,urllib3,chardet,idna,requests_oauthlib,oauthlib,protobuf,google-cloud,six,googleapis-common-protos,python-jwt,requests_toolbelt,jwcrypto,cryptography
```

**Comment by sandhyareddy2001** [comment]
What exactly did you do??
