### ISSUE TITLE
Urlrequest fails with TypeError

### ISSUE THREAD

**Issue by garantor** [kivy/kivy#7125]
**Software Versions**
* Python: Python 3.7.5
* OS: MacOs
* Kivy: Kivy==1.11.1
* Kivy installation method: pip 

**Describe the bug**
```
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [AKivymd     ] v1.1
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_nspaste'] ignored)
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Loader      ] using a thread pool of 2 workers

__init__() got an unexpected keyword argument 'context'
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 50, in <module>
     SentItApp().run()
   File "/Users/afolabi/stellarweb/lib/python3.7/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/Users/afolabi/stellarweb/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/Users/afolabi/stellarweb/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/Users/afolabi/stellarweb/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/Users/afolabi/stellarweb/lib/python3.7/site-packages/kivy/base.py", line 339, in idle
     Clock.tick()
   File "/Users/afolabi/stellarweb/lib/python3.7/site-packages/kivy/clock.py", line 591, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/Users/afolabi/stellarweb/lib/python3.7/site-packages/kivy/network/urlrequest.py", line 527, in _dispatch_result
     func(self, data)
   File "/Users/afolabi/sendit/src/mainFile/billPayment.py", line 283, in bill_failed
     text2= f"Phone Number {requests_res['content']['transactions']['unique_element']}" , 
 TypeError: 'TypeError' object is not subscriptable
```

**Additional context**
This seems to work fine on android but running the code on mac throws this error, all good when on linux. 
saw this issue #6946

**Comment by RobertFlatt** [comment]
Several fixes to this code this year, perhaps a more recent kivy version is required?
See this thread for references to explore:
https://groups.google.com/forum/?oldui=1#!topic/kivy-users/ERAK1XQh8TE

**Comment by garantor** [comment]
thanks @RobertFlatt

**Comment by Zen-CODE** [comment]
Lets close this ticket, assuming the link helps solve the problem. If not, please create a new ticket with a runable code example that demonstrates the problem. 

Thanks

**Comment by garantor** [comment]
@Zen-CODE  this error persist, i noticed it is from adding 'ca_file' to urlrequest

```[INFO   ] [AKivymd     ] v1.1
[INFO   ] [GL          ] NPOT texture support is available
xclip version 0.13
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] Unpack subimage support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
[INFO   ] [MTD         ] Read event from </dev/input/event4>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
[INFO   ] [Loader      ] using a thread pool of 2 workers
__init__() got an unexpected keyword argument 'context'
<UrlRequest(Thread-6, started daemon 139954953766656)>
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 66, in <module>
     SentItApp().run()
   File "/home/afolabi/stellarweb/lib/python3.7/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/home/afolabi/stellarweb/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/afolabi/stellarweb/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/home/afolabi/stellarweb/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/home/afolabi/stellarweb/lib/python3.7/site-packages/kivy/base.py", line 339, in idle
     Clock.tick()
   File "/home/afolabi/stellarweb/lib/python3.7/site-packages/kivy/clock.py", line 591, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/home/afolabi/stellarweb/lib/python3.7/site-packages/kivy/network/urlrequest.py", line 527, in _dispatch_result
     func(self, data)
   File "/home/afolabi/sendit/src/kvfile/cabletv.py", line 666, in error_bill_pay
     text2= f"Phone Number {error_response['content']['transactions']['phone']}" , 
 TypeError: 'TypeError' object is not subscriptable
```
by removing the ca_file everything works fine when running app on linux yet to test it out on android

**Comment by Zen-CODE** [comment]
New ticket with error log and source code attached please. This looks like an error in "File "/home/afolabi/sendit/src/kvfile/cabletv.py"....

**Comment by Zen-CODE** [comment]
@garantor Please also make sure the code is minimal example demonstrating the problem, and not just a massive application with a bug in it :-) Thanks

**Comment by garantor** [comment]
```

import kivy, certifi, json

from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.network.urlrequest import UrlRequest


class MyApp(App):

    def build(self):
        return  Button(text='Hello world', on_release=self.test_url)

    def test_url(self, *args):
        data =json.dumps({
                'email':'afolabisunday31@yahoo.com',
                'password':'12345',
                'serviceId':'dstv',
                'billerCode':'1212121212',
                'variation_code':'dstv1',
                'amount':'2000',
                'phone': '081324567898765'


            })



        headers = {'Content-type': 'application/json',
                    'Accept': 'text/plain'}
        url =base+'/api/v1/paysubscriptions'
        print(url)
        UrlRequest(url=url, req_body=data, on_failure=self.error_response, on_error=self.error_response, on_success=self.response_output, req_headers=headers, ca_file=certifi.where())
                


    def response_output(self, req, response_obj):
        print('success')
        print(req)
        print(response_obj)

    def error_response(self, req, response_obj):
        print(req)
        print(response_obj)

if __name__ == '__main__':
    MyApp().run()```

@Zen-CODE  here is a minimum code that produce same error

**Comment by garantor** [comment]
@Zen-CODE  here is a minimum code that produce same error

**Comment by matham** [comment]
What is the full error log? It's impossible to run without a test server so please provide the full error log.

**Comment by garantor** [comment]
When i connect to the same url hosted on heroku (basically using https) everything works fine but while debugging on local host, there is always a context error with ca_file.

**Comment by Zen-CODE** [comment]
@garantor We really do need the full error log. This discussion is pointless otherwise...
