### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Zitrusfrucht** [kivy/kivy#7189]
**Software Versions**
* Python: 3.7
* OS: Windows 10
* Kivy: 1.11.1
* Kivy installation method: cmd in virtual environment with pip

**Describe the bug**
Dear developers, I am more or less new to Python and programming in general, so I apologize if the question is stupid.
I installed everything and it looks fine but when I import kivy (Eclipse with PyDev) I get an error message. The program still seems to work fine but I dont know if this error might affect the program somehow in the future and I dont know how to fix it.

**Code and Logs and screenshots**
```python
import kivy
```

```python
[ERROR  ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "C:\Users\User\Desktop\venv\lib\site-packages\kivy\logger.py", line 234, in emit
    self._configure()
  File "C:\Users\User\Desktop\venv\lib\site-packages\kivy\logger.py", line 194, in _configure
    Logger.info('Logger: Record log in %s' % filename)
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 1514, in _log
    self.handle(record)
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 894, in handle
    self.emit(record)
  File "C:\Users\User\Desktop\venv\lib\site-packages\kivy\logger.py", line 247, in emit
    self._write_message(message)
  File "C:\Users\User\Desktop\venv\lib\site-packages\kivy\logger.py", line 218, in _write_message
    stream.write(fs % msg)
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 40: character maps to <undefined>
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\User\Desktop\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\User\Desktop\venv\Scripts\python.exe"
```

**Comment by Cheaterman** [comment]
That it interesting to say the least! For general support you're encouraged to join our discord on https://chat.kivy.org/ instead of using GitHub issues. I'm not sure about your issue, particularly given it seems non-fatal, perhaps has to do with color handling or something?

**Comment by Zitrusfrucht** [comment]
@matham you were right! I had an "ü" in my username. So I "fixed" it by completly reinstalling windows (had to be done anyway) and choosing a different username (now my initials "PR"). And now it works perfectly fine, without any errors. Thank you.
