### ISSUE TITLE
Kivy inspector module broken in 2.0.0rc4 (and 2.0.0rc3) - working fine in 1.11.1

### ISSUE THREAD

**Issue by AndiEcker** [kivy/kivy#7214]
**Software Versions**
* Python: 3.6.9
* OS: Ubuntu 18.04
* Kivy: 2.0.0rc3 and 2.0.0rc4
* Kivy installation method: pip

**Describe the bug**
The usage of the `inspector` kivy module via command line option (`-m inspector`) or via the Kivy config file (adding it to the `modules` section) crashes the app on startup with the following traceback:

```
[INFO   ] [Window      ] auto add sdl2 input provider
[WARNING] [Modules     ] Module <inspector> missing start() function
 Traceback (most recent call last):
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 226, in update
     self.activate_module(name, win)
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 181, in activate_module
     self._configure_module(name)
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 267, in _configure_module
     if hasattr(self.mods[name]['module'], 'configure'):
 KeyError: 'module'
[INFO   ] [Window      ] Provider: x11(['window_sdl2'] ignored)
FBConfig selected:
Doublebuffer: Yes
Red Bits: 8, Green Bits: 8, Blue Bits: 8, Alpha Bits: 8, Depth Bits: 24
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 20.0.8'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[WARNING] [Modules     ] Module <inspector> missing start() function
 Traceback (most recent call last):
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 226, in update
     self.activate_module(name, win)
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 181, in activate_module
     self._configure_module(name)
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 267, in _configure_module
     if hasattr(self.mods[name]['module'], 'configure'):
 KeyError: 'module'
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - KeyError: 'module'
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/__init__.py", line 70, in core_select_lib
    cls = cls()
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 152, in __init__
    super(WindowSDL, self).__init__()
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 983, in __init__
    self.register()
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1012, in register
    Modules.register_window(self)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 209, in register_window
    self.update()
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 226, in update
    self.activate_module(name, win)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 181, in activate_module
    self._configure_module(name)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 267, in _configure_module
    if hasattr(self.mods[name]['module'], 'configure'):

x11 - KeyError: 'module'
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/__init__.py", line 70, in core_select_lib
    cls = cls()
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 983, in __init__
    self.register()
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1012, in register
    Modules.register_window(self)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 209, in register_window
    self.update()
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 226, in update
    self.activate_module(name, win)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 181, in activate_module
    self._configure_module(name)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/__init__.py", line 267, in _configure_module
    if hasattr(self.mods[name]['module'], 'configure'):

[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0
[INFO   ] [Kivy        ] v2.0.0rc4, git-d74461b, 20201015
[INFO   ] [Kivy        ] Installed at "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Aug 28 2019, 15:54:20)
[GCC 7.4.0]
[INFO   ] [Python      ] Interpreter at "/home/andi/.pyenv/versions/kivy_env/bin/python"
[INFO   ] [SoundFFPy   ] Using ffpyplayer 4.3.2
[DEBUG  ] [Audio       ] register SoundFFPy
[DEBUG  ] [Audio       ] register SoundSDL2
[DEBUG  ] [Audio       ] register MusicSDL2
[INFO   ] [Audio       ] Providers: audio_ffpyplayer, audio_sdl2
[DEBUG  ] [App         ] Loading kv </home/andi/src/transfer_local/main.kv>
 Traceback (most recent call last):
   File "/home/andi/src/transfer_local/main.py", line 95, in <module>
     TransferLocalApp(app_name='transfer_local').run_app()
   File "/home/andi/src/ae_gui_app/ae/gui_app.py", line 992, in run_app
     self._start_event_loop()
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/home/andi/src/ae_kivy_app/ae/kivy_app.py", line 812, in build
     Window.bind(on_resize=self.win_pos_size_change,
 AttributeError: 'NoneType' object has no attribute 'bind'
```

When I explicitly import the inspector module and call the create_inspector() function in the build() method of the App class then the app at least starts with no errors, but it crashes on closing the app with activated inspector with the following traceback:

```
 Traceback (most recent call last):
   File "/home/andi/src/transfer_local/main.py", line 95, in <module>
     TransferLocalApp(app_name='transfer_local').run_app()
   File "/home/andi/src/ae_gui_app/ae/gui_app.py", line 992, in run_app
     self._start_event_loop()
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/app.py", line 951, in run
     self.stop()
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/app.py", line 977, in stop
     self._app_window.remove_widget(child)
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1329, in remove_widget
     self.children.remove(widget)
   File "kivy/properties.pyx", line 756, in kivy.properties.ObservableList.remove
   File "kivy/properties.pyx", line 707, in kivy.properties.observable_list_dispatch
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/modules/inspector.py", line 383, in on_window_children
     win.add_widget(self)
   File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1307, in add_widget
     (widget, widget.parent)
 kivy.uix.widget.WidgetException: Cannot add <kivy.modules.inspector.Inspector object at 0x7fdc5143d5f8> to window, it already has a parent <kivy.core.window.window_sdl2.WindowSDL object at 0x7fdc5aab7908>
```

This is *not* happening if I use the last stable Kivy version (1.11.1).

**Expected behavior**
All inspector module activation methods should work as documented.

**To Reproduce**
see above in error description (*Describe the bug*).

**Comment by gottadiveintopython** [comment]
I don't know how to fix this, but I found a workaround:

```python
from kivy.app import App
from kivy.uix.widget import Widget


def activate_inspector():
    from kivy.config import Config
    from kivy.modules import Modules
    from kivy.core.window import Window
    Config.set('modules', 'inspector', '')
    Modules.activate_module('inspector', Window)


def deactivate_inspector():
    from kivy.modules import Modules
    from kivy.core.window import Window
    Modules.deactivate_module('inspector', Window)


class SampleApp(App):
    def on_start(self):
        activate_inspector()
    def on_stop(self):
        deactivate_inspector()
    def build(self):
        return Widget()


if __name__ == '__main__':
    SampleApp().run()
```

Use this until someone fix the issue.

**Comment by matham** [comment]
You can do it more directly with `inspector.create_inspector(Window, root)` and `inspector.stop(Window, self.root)` to start and stop the inspector without going through modules.

**Comment by tshirtman** [comment]
https://github.com/kivy/kivy/pull/7271
