### ISSUE TITLE
TextInput: app crashes when selecting using handles after deleting some text

### ISSUE THREAD

**Issue by Alspb** [kivy/kivy#7246]
**Software Versions**
* Python: 3.8.5
* OS: Linux Mint 20 (based on Ubuntu 20.04 LTS) or Android 10
* Kivy: 2.0.0rc4

**Describe the bug**
App crashes when the following actions are performed in the TextInput (described in the code below):

1. Select 'aaaa bbbb' substring (by double tap and then using selection handles), then delete it.
2. Select 'cccc' word (by double tap).
3. Pull the right selection handle right.

The traceback is placed below.

**Code**
```python
from kivy.app import App
from kivy.uix.textinput import TextInput
class Sample(App):
    def build(self):
        return TextInput(text='aaaa bbbb cccc '+'d'*200, use_handles=True)
Sample().run()
```

**Traceback**
```
Traceback (most recent call last):
   File "/usr/lib/python3.8/pdb.py", line 1704, in main
     pdb._runscript(mainpyfile)
   File "/usr/lib/python3.8/pdb.py", line 1573, in _runscript
     self.run(statement)
   File "/usr/lib/python3.8/bdb.py", line 580, in run
     exec(cmd, globals, locals)
   File "<string>", line 1, in <module>
   File "/home/al/Desktop/KivyBugs/bug6.py", line 1, in <module>
     from kivy.app import App
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/base.py", line 573, in runTouchApp
     EventLoop.mainloop()
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/base.py", line 397, in idle
     Clock.tick_draw()
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/clock.py", line 783, in tick_draw
     self._process_events_before_frame()
   File "kivy/_clock.pyx", line 658, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy/_clock.pyx", line 701, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy/_clock.pyx", line 697, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/uix/textinput.py", line 2099, in _update_graphics
     self._update_graphics_selection()
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/uix/textinput.py", line 2137, in _update_graphics_selection
     draw_selection(r.pos, r.size, line_num, (s1c, s1r),
   File "/home/al/kivy_venv/lib/python3.8/site-packages/kivy/uix/textinput.py", line 2162, in _draw_selection
     x2 = (x - self.scroll_x) + _get_text_width(lines[:s2c],
 TypeError: slice indices must be integers or None or have an __index__ method
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/al/kivy_venv/lib/python3.8/site-packages/kivy/uix/textinput.py(2162)_draw_selection()
-> x2 = (x - self.scroll_x) + _get_text_width(lines[:s2c],
```

**Comment by Julian-O** [comment]
This was "maybe fixed" by #7621.

@Alspb Can you please confirm whether it is still a problem for you?
