### ISSUE TITLE
ModuleNotFoundError: No module named 'kivy._clock'

### ISSUE THREAD

**Issue by aquastripe** [kivy/kivy#7249]
**Software Versions**
* Python: 3.8.6
* OS: Ubuntu 20.04
* Kivy: 2.0.0rc4
* Kivy installation method: `conda install kivy -c conda-forge`

**Describe the bug**

When I use `from kivy.core.window import Window`, it shows the error as title.

**Expected behavior**
No error shows.

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.

```bash
conda create -n kivy
conda activate kivy
conda install kivy -c conda-forge
```

**Code and Logs and screenshots**
```python
from kivy.core.window import Window
```

```
$ python
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy
[INFO   ] [Logger      ] Record log in /home/maniac/.kivy/logs/kivy_20-12-09_45.txt
[INFO   ] [Kivy        ] Installed at "/home/maniac/Downloads/kivy/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0]
[INFO   ] [Python      ] Interpreter at "/home/maniac/.conda/envs/kivy/bin/python"
>>> from kivy.core.window import Window
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/maniac/Downloads/kivy/kivy/core/window/__init__.py", line 17, in <module>
     from kivy.clock import Clock
   File "/home/maniac/Downloads/kivy/kivy/clock.py", line 466, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ModuleNotFoundError: No module named 'kivy._clock'
>>>  
```

![image](https://user-images.githubusercontent.com/73936909/101569300-3438f300-3a0f-11eb-8089-1f2d7eef3cff.png)

**Additional context**

```bash
$ conda list
# packages in environment at /home/maniac/.conda/envs/kivy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_0    conda-forge
docutils                  0.16             py38h924ce5b_2    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kivy                      2.0.0rc4         py38hc2ab0ce_2    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h4f3a223_6    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    8.0.1            py38h70fbd49_0    conda-forge
pip                       20.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
sdl2                      2.0.12               h58526e2_1    conda-forge
sdl2_image                2.0.5                h0e9dbb3_0    conda-forge
sdl2_mixer                2.0.4                he1b5a44_0    conda-forge
sdl2_ttf                  2.0.15               h7d98c4e_0    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
smpeg2                    2.0.0                hfc679d8_1    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.36.1             pyhd3deb0d_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

**Comment by matham** [comment]
I can see from the error message screenshot that it's running kivy from the downloads folder. If you installed kivy from conda, please don't try running it from a downloaded version of kivy. Instead run it from a different directory.

**Comment by aquastripe** [comment]
> I can see from the error message screenshot that it's running kivy from the downloads folder. If you installed kivy from conda, please don't try running it from a downloaded version of kivy. Instead run it from a different directory.

...It works!
LUL, thanks very much!

**Comment by robinssondsp** [comment]
hola tengo el mismo erro, entiendo que debo ejecutar kivy desde un directorio diferente... como lo hago ???
