### ISSUE TITLE
Exception if exiting application while inspector is open.

### ISSUE THREAD

**Issue by tshirtman** [kivy/kivy#7291]
**Software Versions**
* Python: 3.9
* OS: linux
* Kivy: master (00399f782)
* Kivy installation method: pip install --editable .

**Describe the bug**
If the kivy app is exited while the inspector is opened, the app crashes instead of exiting cleanly

This can be fixed by adding a condition in https://github.com/kivy/kivy/blob/00399f782/kivy/modules/inspector.py#L365-L366 
like `and EventLoop.status != 'started'` but that breaks the tests, which are currently run with EventLoop.status = 'stopped' (which surprised me).

**Expected behavior**
A clean exit when the application is closed with inspector opened.

**To Reproduce**
Run any app (the showcase for example) with the inspector module activated, start the inspector (ctrl-e) then exit the app using your normal operating system/window managers controls (like clicking on the cross in the corner of the window).

**crash log**
```
[INFO   ] [Inspector   ] inspector activated
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/home/gabriel/dev/kivy/examples/widgets/recycleview/messenger.py", line 196, in <module>
     MessengerApp().run()
   File "/home/gabriel/dev/kivy/kivy/app.py", line 951, in run
     self.stop()
   File "/home/gabriel/dev/kivy/kivy/app.py", line 977, in stop
     self._app_window.remove_widget(child)
   File "/home/gabriel/dev/kivy/kivy/core/window/__init__.py", line 1329, in remove_widget
     self.children.remove(widget)
   File "kivy/properties.pyx", line 756, in kivy.properties.ObservableList.remove
     observable_list_dispatch(self)
   File "kivy/properties.pyx", line 707, in kivy.properties.observable_list_dispatch
     prop.dispatch(obj)
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
     ps.observers.dispatch(obj, ps.value, None, None, 0)
   File "kivy/_event.pyx", line 1263, in kivy._event.EventObservers.dispatch
     result = self._dispatch(
   File "kivy/_event.pyx", line 1169, in kivy._event.EventObservers._dispatch
     return f(obj, value)
   File "/home/gabriel/dev/kivy/kivy/modules/inspector.py", line 370, in on_window_children
     win.add_widget(self)
   File "/home/gabriel/dev/kivy/kivy/core/window/__init__.py", line 1305, in add_widget
     raise WidgetException(
 kivy.uix.widget.WidgetException: Cannot add <kivy.modules.inspector.Inspector object at 0x7f28466a1510> to window, it already has a parent <kivy.core.window.window_sdl2.WindowSDL object at 0x7f2838ff04a0>
```

**Comment by matham** [comment]
When I used inspector, I knew that I had to unregister it during shutdown. I think that's expected from the docs. But perhaps that shouldn't be required.
