### ISSUE TITLE
Error with camera example - on RaspberryPi

### ISSUE THREAD

**Issue by MathiasL-CENTURI** [kivy/kivy#7346]
**Software Versions**
* Python: Python 3.7.3
* OS: Raspbian GNU/Linux 10 (buster)
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
When starting the main.py code from the camera example (kivy_venv/share/kivy-examples/camera), there is an error message and the code stops.

**Expected behavior**
Error message.

**To Reproduce**
1. Open the terminal ;
2. Open the virtual environment : source kivy_venv/bin/activate
3. Launch the camera example : python kivy_venv/share/kivy-examples/camera/main.py

**Code and Logs and screenshots**
This is the error message:
```python-traceback
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x1e2b5f0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
 Traceback (most recent call last):
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 104, in _on_index
     resolution=self.resolution, stopped=True)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 31, in __init__
     super(CameraPiCamera, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 37, in init_camera
     self._camera = PiCamera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 433, in __init__
     self._init_preview()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 513, in _init_preview
     self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/renderers.py", line 558, in __init__
     self.renderer.inputs[0].connect(source).enable()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/mmalobj.py", line 2212, in enable
     prefix="Failed to enable connection")
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
     raise PiCameraMMALError(status, prefix)
 picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources During handling of the above exception, another exception occurred: Traceback (most recent call last):
   File "camera/main.py", line 59, in <module>
     TestCamera().run()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "camera/main.py", line 56, in build
     return CameraClick()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 361, in __init__
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 465, in apply_class_lang_rules
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 543, in apply
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 712, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 6:
 ...
       4:    Camera:
       5:        id: camera
 >>    6:        resolution: (640, 480)
       7:        play: False
       8:    ToggleButton:
 ...
 PiCameraMMALError: Failed to enable connection: Out of resources
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 104, in _on_index
     resolution=self.resolution, stopped=True)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 31, in __init__
     super(CameraPiCamera, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 37, in init_camera
     self._camera = PiCamera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 433, in __init__
     self._init_preview()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 513, in _init_preview
     self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/renderers.py", line 558, in __init__
     self.renderer.inputs[0].connect(source).enable()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/mmalobj.py", line 2212, in enable
     prefix="Failed to enable connection")
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
     raise PiCameraMMALError(status, prefix)
```

**Quick fix**
Commenting the following line : resolution (640, 480)

**Comment by AndiEcker** [comment]
Having the same issue with zbarcam (also documented in issue #7285).

I just tried your workaround/quick-fix and commented out the two similar
lines in:
1) line 27 of kivy_garden/xcamera/xcamera.kv
2) line 11 of kivy_garden/zbarcam/zbarcam.kv

With that quick fixes in place, I don't anymore the same traceback.
Instead, I now see this error which repeats in an endless loop until you
stop/cancel the execution:

```
[ERROR  ] [OpenCV      ] Couldn't get image from Camera
Traceback (most recent call last):
  File
"/home/andi/.pyenv/versions/ae/lib/python3.6/site-packages/kivy/core/camera/camera_opencv.py",
line 149, in _update
    self._copy_to_gpu()
  File
"/home/andi/.pyenv/versions/ae/lib/python3.6/site-packages/kivy/core/camera/__init__.py",
line 127, in _copy_to_gpu
    self.dispatch('on_texture')
  File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
  File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
  File
"/home/andi/.pyenv/versions/ae/lib/python3.6/site-packages/kivy_garden/zbarcam/zbarcam.py",
line 64, in _on_texture
    texture=instance.texture, code_types=self.code_types)
  File
"/home/andi/.pyenv/versions/ae/lib/python3.6/site-packages/kivy_garden/zbarcam/zbarcam.py",
line 78, in _detect_qrcode_frame
    codes = pyzbar.decode(pil_image, symbols=code_types)
  File
"/home/andi/.pyenv/versions/ae/lib/python3.6/site-packages/pyzbar/pyzbar.py",
line 198, in decode
    scanner, symbol, ZBarConfig.CFG_ENABLE, 1
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
[ERROR  ] [OpenCV      ] Couldn't get image from Camera
......
```

Am Mi., 27. Jan. 2021 um 14:32 Uhr schrieb MathiasL-CENTURI <
notifications@github.com>:

**Comment by matham** [comment]
Can you please try master? I think https://github.com/kivy/kivy/pull/7264 may have fixed it.

**Comment by MathiasL-CENTURI** [comment]
I tried reinstalling kivy with `python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/master.zip"
` but I still have the same message.

Kivy install: 
`Kivy          2.1.0.dev0`
`Kivy-examples 2.0.0`
`Kivy-Garden   0.1.4`

Exception message :
<detail>
```python-traceback
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x19d2410 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
 Traceback (most recent call last):
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 706, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 872, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 525, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 580, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 106, in _on_index
     resolution=self.resolution, stopped=True)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 31, in __init__
     super(CameraPiCamera, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 37, in init_camera
     self._camera = PiCamera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 433, in __init__
     self._init_preview()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 513, in _init_preview
     self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/renderers.py", line 558, in __init__
     self.renderer.inputs[0].connect(source).enable()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/mmalobj.py", line 2212, in enable
     prefix="Failed to enable connection")
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
     raise PiCameraMMALError(status, prefix)
 picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main.py", line 59, in <module>
     TestCamera().run()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 924, in _run_prepare
     root = self.build()
   File "main.py", line 56, in build
     return CameraClick()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 361, in __init__
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 465, in apply_class_lang_rules
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 544, in apply
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 713, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 6:
 ...
       4:    Camera:
       5:        id: camera
 >>    6:        resolution: (640, 480)
       7:        play: False
       8:    ToggleButton:
 ...
 PiCameraMMALError: Failed to enable connection: Out of resources
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 706, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 872, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 525, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 580, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 106, in _on_index
     resolution=self.resolution, stopped=True)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 31, in __init__
     super(CameraPiCamera, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 37, in init_camera
     self._camera = PiCamera()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 433, in __init__
     self._init_preview()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/camera.py", line 513, in _init_preview
     self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/renderers.py", line 558, in __init__
     self.renderer.inputs[0].connect(source).enable()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/mmalobj.py", line 2212, in enable
     prefix="Failed to enable connection")
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
     raise PiCameraMMALError(status, prefix)
```
</detail>

**Comment by DrakeProvost** [comment]
I'm also having this issue on commit 6b8495e48328af5088a899372d93b6daabc75a02 using the kivy docs camera example. For now I think I'll roll back to 1.11.1 (commit f34c43f235f35767ed04765a90d68b23807436ba) since I've confirmed the code works there.

**Comment by matham** [comment]
>I tried reinstalling kivy with python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/master.zip" but I still have the same message.

This is surprising because if I understood that fix correctly, the resolution of camera should not be configured until you hit play. So I'm not sure why it's still doing it.
