### ISSUE TITLE
Using camera resolution property with Builder causes 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by worraps** [kivy/kivy#7399]
**Software Versions**
* Python: 3.8.5
* OS: Ubuntu 20.04 LTS
* Kivy: 2.0.0
* Kivy installation method: pip install

**Describe the bug**
Running the demo from [ KIVY Camera Demo](https://kivy.org/doc/stable/examples/gen__camera__main__py.html) results in the error. **AttributeError: 'NoneType' object has no attribute 'shape'**

See: #7285 thanks to @ElliotGarbus for verifying on Windows.

**Expected behavior**
Demo app should open using default camera (normally /dev/video0 on linux).

**To Reproduce**
Paste demo code as-is and attempt to run.

**Code and Logs and screenshots**
```python
'''
Camera Example
==============

This example demonstrates a simple use of the camera. It shows a window with
a buttoned labelled 'play' to turn the camera on and off. Note that
not finding a camera, perhaps because gstreamer is not installed, will
throw an exception during the kv language processing.

'''

# Uncomment these lines to see all the messages
# from kivy.logger import Logger
# import logging
# Logger.setLevel(logging.TRACE)

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
import time
Builder.load_string('''
<CameraClick>:
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (640, 480)
        play: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()
''')


class CameraClick(BoxLayout):
    def capture(self):
        '''
        Function to capture the images and give them the names
        according to their captured time and date.
        '''
        camera = self.ids['camera']
        timestr = time.strftime("%Y%m%d_%H%M%S")
        camera.export_to_png("IMG_{}.png".format(timestr))
        print("Captured")


class TestCamera(App):

    def build(self):
        return CameraClick()


TestCamera().run()
```

**Additional context**
Confirming similar behavior here on [SO](https://stackoverflow.com/questions/59371075/opencv-error-cant-open-camera-through-video-capture#answer-61817613)

I discovered by adding some debug prints that it appears multiple camera instances are being created... so I added a traceback dump in kivy.camera.camera_opencv.py
```python
        elif self.opencvMajorVersion in (2, 3, 4):
            # create the device
            print('Dumping stack trace in elif of CameraOpenCV.init_camera ')
            traceback.print_stack()
            self._device = cv2.VideoCapture(self._index)
```
here is a dump of the output...
```log
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_21-03-03_76.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/home/user/dev/ssb/.venv/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 450.102.04'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'Quadro P600/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Camera      ] Provider: opencv(['camera_picamera', 'camera_gi'] ignored)
Dumping stack trace in elif of CameraOpenCV.init_camera 
   File "./patchpy.py", line 57, in <module>
     TestCamera().run()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "./patchpy.py", line 54, in build
     return CameraClick()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
     child = cls(__no_builder=True)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/camera.py", line 91, in __init__
     on_index()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/camera.py", line 101, in _on_index
     self._camera = CoreCamera(index=self.index, stopped=True)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 72, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 112, in init_camera
     traceback.print_stack()
[INFO   ] [Text        ] Provider: sdl2
Debugging widgets/rules in builder.py _apply_rule
print(widget_set,widget,key,value)
Debugging widgets/rules in builder.py _apply_rule
print(widget_set,widget,key,value)
Debugging widgets/rules in builder.py _apply_rule
print(widget_set,widget,key,value)
<__main__.CameraClick object at 0x7faf15849a50> <__main__.CameraClick object at 0x7faf15849a50> orientation vertical
Debugging widgets/rules in builder.py _apply_rule
print(widget_set,widget,key,value)
<kivy.uix.button.Button object at 0x7faee80382e0> <__main__.CameraClick object at 0x7faf15849a50> text Capture
<kivy.uix.button.Button object at 0x7faee80382e0> <__main__.CameraClick object at 0x7faf15849a50> height 48dp
Debugging widgets/rules in builder.py _apply_rule
print(widget_set,widget,key,value)
<kivy.uix.togglebutton.ToggleButton object at 0x7faee92ee120> <__main__.CameraClick object at 0x7faf15849a50> text Start Camera
<kivy.uix.togglebutton.ToggleButton object at 0x7faee92ee120> <__main__.CameraClick object at 0x7faf15849a50> height 48dp
Debugging widgets/rules in builder.py _apply_rule
print(widget_set,widget,key,value)
<kivy.uix.camera.Camera object at 0x7faee9371ba0> <__main__.CameraClick object at 0x7faf15849a50> resolution (640, 480)
Dumping stack trace in elif of CameraOpenCV.init_camera 
   File "./patchpy.py", line 57, in <module>
     TestCamera().run()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "./patchpy.py", line 54, in build
     return CameraClick()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 707, in _apply_rule
     setattr(widget_set, key, value)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/camera.py", line 103, in _on_index
     self._camera = CoreCamera(index=self.index,
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 72, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 112, in init_camera
     traceback.print_stack()
[ WARN:0] global /tmp/pip-req-build-ms668fyv/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
 Traceback (most recent call last):
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 707, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/camera.py", line 103, in _on_index
     self._camera = CoreCamera(index=self.index,
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 72, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 130, in init_camera
     self._resolution = (int(frame.shape[1]), int(frame.shape[0]))
 AttributeError: 'NoneType' object has no attribute 'shape'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "./patchpy.py", line 57, in <module>
     TestCamera().run()    
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "./patchpy.py", line 54, in build
     return CameraClick()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 712, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 7:
 ...
       5:        id: camera
       6:        #index: 0
 >>    7:        resolution: (640, 480)
       8:        play: False
       9:    ToggleButton:
 ...
 AttributeError: 'NoneType' object has no attribute 'shape'
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 707, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/uix/camera.py", line 103, in _on_index
     self._camera = CoreCamera(index=self.index,
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 72, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 130, in init_camera
     self._resolution = (int(frame.shape[1]), int(frame.shape[0]))
```
**Full Disclosure:** I have no idea how to specifically interpret the code here, so this may not be quite right... but this is what I suspect.

The builder parser finds the Camera object and a camera gets created.  However, if **index** or **resolution** properties exists then the code also executes the generic setattr()
```python
                        # if there's a rule
                        if (widget_set != widget or bound or
                                key not in ignored_consts):
                            setattr(widget_set, key, value)
```
This widget_set object does not seem to reference the same Camera object that gets created earlier.  Note the debug text "Dumping stack trace... " and the following trace lines.  It gets called twice which seems to cause the exact same affect as found in the above referenced SO example.
The camera behaviour indicates this is the case too since the LED turns on for milliseconds (I suspect during the first instantiation) and then turns off until the timeout and results in the above error log.
Notice rule error:
```log
   File "/home/user/dev/ssb/.venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 712, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 7:
 ...
       5:        id: camera
       6:        #index: 0
 >>    7:        resolution: (640, 480)
       8:        play: False
       9:    ToggleButton:
```
removing resolution property (or index) causes demo to run as expected.
Hope this helps...

**Comment by matham** [comment]
I would suggest to try master because there has been some fixes to camera since 2.0.0.

**Comment by worraps** [comment]
@matham - I confirmed install from master 2.0.0dev0 works as expected

**Comment by havinzhou** [comment]
The Camera class inherits to image, and when the computer doesn't detect the Camera device, it reports the error 'NoneType' object has no 'shape', and I'm looking for a workaround
