### ISSUE TITLE
pip install kivy[base] doesn't work on Apple Silicon

### ISSUE THREAD

**Issue by anentropic** [kivy/kivy#7440]
**Software Versions**
* Python: 3.9.2
* OS: macOS Big Sur 11.2.3
* Kivy: 2.0.0
* Kivy installation method: `pip install "kivy[base]"`

**Describe the bug**
It appeared to install fine:
```
Using legacy 'setup.py install' for Kivy-Garden, since package 'wheel' is not installed.
Building wheels for collected packages: kivy
  Building wheel for kivy (PEP 517) ... done
  Created wheel for kivy: filename=Kivy-2.0.0-cp39-cp39-macosx_11_0_arm64.whl size=13473950 sha256=ea574162775418cbe9aa83e93f9090a910224de64627a5a865bc124ace30810b
  Stored in directory: /Users/anentropic/Library/Caches/pip/wheels/1c/63/58/77cfa5999369eea092050f026f7a89bf183acc4b7c28fcb4cf
Successfully built kivy
Installing collected packages: docutils, pygments, idna, chardet, certifi, urllib3, requests, Kivy-Garden, pillow, kivy, numpy
    Running setup.py install for Kivy-Garden ... done
Successfully installed Kivy-Garden-0.1.4 certifi-2020.12.5 chardet-4.0.0 docutils-0.16 idna-2.10 kivy-2.0.0 numpy-1.20.1 pillow-8.1.2 pygments-2.8.1 requests-2.25.1 urllib3-1.26.4
```
But when I run my app:

```
[INFO   ] [Logger      ] Record log in /Users/anentropic/.kivy/logs/kivy_21-03-23_7.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/Users/anentropic/Documents/Dev/Personal/myproj/.venv/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.2 (default, Mar 18 2021, 20:48:06) 
[Clang 12.0.0 (clang-1200.0.32.29)]
[INFO   ] [Python      ] Interpreter at "/Users/anentropic/Documents/Dev/Personal/myproj/.venv/bin/python"
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "/Users/anentropic/Documents/Dev/Personal/myproj/myproj/kivy_canvas.py", line 6, in <module>
     from kivy.app import App
   File "/Users/anentropic/Documents/Dev/Personal/myproj/.venv/lib/python3.9/site-packages/kivy/app.py", line 411, in <module>
     from kivy.base import runTouchApp, async_runTouchApp, stopTouchApp
   File "/Users/anentropic/Documents/Dev/Personal/myproj/.venv/lib/python3.9/site-packages/kivy/base.py", line 28, in <module>
     from kivy.clock import Clock
   File "/Users/anentropic/Documents/Dev/Personal/myproj/.venv/lib/python3.9/site-packages/kivy/clock.py", line 466, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ImportError: dlopen(/Users/anentropic/Documents/Dev/Personal/myproj/.venv/lib/python3.9/site-packages/kivy/_clock.cpython-39-darwin.so, 2): no suitable image found.  Did find:
 	/Users/anentropic/Documents/Dev/Personal/myproj/.venv/lib/python3.9/site-packages/kivy/_clock.cpython-39-darwin.so: mach-o, but wrong architecture
 	/Users/anentropic/Documents/Dev/Personal/myproj/.venv/lib/python3.9/site-packages/kivy/_clock.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Expected behavior**
I also have a non-M1 mac (Mojave) and it works fine there, so I guess this is a problem on the new hardware.

**Comment by tshirtman** [comment]
Yep, options to build binary packages in the CI are very limited at the moment, and github actions (that we use to build and release wheels) doesn't have any, when that happen, we should be able to make universal2 compatible wheels and upload them to pypi. Not sure why it even installs the existing wheels now, as i though pip would detect it's not a proper wheel for your system, but maybe you need to update setuptools or pip, as things were defined relatively recently. You can certainly install from the source package using `pip install kivy[base] --no-binary=all`, though it'll require having cython installed and other dependencies.

**Comment by anentropic** [comment]
> Not sure why it even installs the existing wheels now

I think it's maybe because there is a "source distribution" on PyPI (https://pypi.org/project/Kivy/2.0.0/#files) as well as the wheels, so pip automatically builds its own wheel locally when installing. But something in the sdist is maybe platform dependent?

**Comment by anentropic** [comment]
So maybe I just needed Cython installed first

**Comment by matham** [comment]
You shouldn't need to have anything installed because pyproject.toml will make sure the deps (including cython) are installed in the build env.

**Comment by misl6** [comment]
Kivy 2.1.0 is out and we now ship `universal2` binaries for Python 3.8-3.10.

Closing the issue cause should be fixed, anyway, if you still have some issue feel free to re-open it.
