### ISSUE TITLE
Moving the ScrollView's bar when `scroll_type=['bars','content']` causes a crash.

### ISSUE THREAD

**Issue by mrakgr** [kivy/kivy#7460]
**Software Versions**
* Python: 3.8.5
* OS: Win 10
* Kivy: 2.0.0
* Kivy installation method: conda

**Describe the bug**
Run the program and try moving the bar using the mouse. Note that if you first move the content and then try the bar, the program works properly. Things also work fine when the `scroll_type=['bars']` only.

**Code and Logs and screenshots**

```py
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button
from kivy.uix.scrollview import ScrollView
from kivy.core.window import Window
from kivy.app import runTouchApp

layout = GridLayout(cols=1, spacing=10, size_hint_y=None)
# Make sure the height is such that there is something to scroll.
layout.bind(minimum_height=layout.setter('height'))
for i in range(100):
    btn = Button(text=str(i), size_hint_y=None, height=40)
    layout.add_widget(btn)
root = ScrollView(size_hint=(1, None), size=(Window.width, Window.height),scroll_type=['bars','content'],bar_width=30)
root.add_widget(layout)

runTouchApp(root)
````

```
[INFO   ] [Logger      ] Record log in C:\Users\Marko\.kivy\logs\kivy_21-04-01_43.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Marko\anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Marko\anaconda3\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 456.71'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 970/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_leduc5/scrollview_bug.py", line 16, in <module>
     runTouchApp(root)
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\base.py", line 301, in post_dispatch_input
     wid.dispatch('on_touch_move', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\uix\scrollview.py", line 855, in on_touch_move
     if self.dispatch('on_scroll_move', touch):
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\uix\scrollview.py", line 908, in on_scroll_move
     self.effect_x.update(touch.x)
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\effects\scroll.py", line 116, in update
     self.displacement += abs(val - self.history[-1][1])
 IndexError: list index out of range
```

**Comment by matham** [comment]
I believe this is fixed in master. Please try that and report back.

**Comment by mrakgr** [comment]
I am busy, so I'll take your world for it. Getting this to your attention is good enough for me. When the next version comes out officially I'll give it a try then.
