### ISSUE TITLE
SDL2: Unable to load image

### ISSUE THREAD

**Issue by icarpis** [kivy/kivy#7503]
**Software Versions**
* Python: 3.7 x64
* OS: Windows 10
* Kivy: 2.0.0
* Kivy installation method: pip

An exception is raised while running Kivy Mapview - Exception: SDL2: Unable to load image.

I'm using Kivy Mapview to show the coordinates of some portable device.
I'm running the following method as a _multiprocessing_ Process from another main Python script, and I'm using _multiprocessing_  Queue to share the new coordinates between the processes.
```python
# Main Python File
p = Process(target=ShowMap, args=(q,))
p.start()

def ShowMap(q):
    from Map import MapViewApp
    mapViewApp = MapViewApp(q)
    mapViewApp.run()


# MapView File
import os
os.environ['no_proxy'] = '*' 
from _kivy_garden.mapview import *
from _kivy.app import App
from _kivy.uix.label import *
import threading
import time

class MapViewApp(App):
    mapView = None
    mThread = None
    q = None

    def __init__(self, q):
        super().__init__()
        self.q = q

    def build(self):
        self.mapView = MapView(zoom=15, lat=0, lon=0)
        m = MapMarker(lon=0, lat=0)
        m.source= ".\\marker.png"
        self.mapView.add_marker(m)
        threading.Thread(target=self.update_position).start()
        return self.mapView

    def update_position(self):
        while True:
            time.sleep(0.001)
            if (self.mapView):
                try:
                    (lat, lon) = self.q.get(block=False)
                except:
                    continue
                if ((type(self.mapView.children[0]) != Label) and
                    (type(self.mapView.children[1]) != Label)):
                    label_lon = Label(text="Longitude: {:.6f}".format(lon), font_size='25sp', color=[0, 0, 0, 1], pos=(70, 10), bold=True)
                    label_lat = Label(text="Latitude: {:.6f}".format(lat), font_size='25sp', color=[0, 0, 0, 1], pos=(80, -20), bold=True)
                    self.mapView.add_widget(label_lon)
                    self.mapView.add_widget(label_lat)

                self.mapView._default_marker_layer.markers[0].lon = lon
                self.mapView._default_marker_layer.markers[0].lat = lat
                self.mapView.children[0].text = "Longitude: {:.6f}".format(lon)
                self.mapView.children[1].text = "Latitude: {:.6f}".format(lat)

                self.mapView.center_on(lat, lon)

# Output

[INFO   ] [Logger      ] Record log in C:\SPB_Data\.kivy\logs\kivy_21-04-28_1.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\python.exe"
[INFO   ] [Logger      ] Purge log fired. Analysing...
[INFO   ] [Logger      ] Purge 8 log files
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.7584'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.7584'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[WARNING] [Image       ] Unable to load image <C:\Users\icarpis\source\repos\PythonApplication5\GroundStation\cache\26a7511794_19_313000_312248.png>
[INFO   ] [Base        ] Leaving application in progress...
 Process Process-1:
 Traceback (most recent call last):
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
     self.run()
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\icarpis\source\repos\PythonApplication5\GroundStation\GroundStation.py", line 624, in ShowMap
     mapViewApp.run()
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 387, in idle
     Clock.tick()
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy_garden\mapview\downloader.py", line 115, in _check_executor
     callback(*args)
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy_garden\mapview\view.py", line 122, in set_source
     self.source = cache_fn
   File "kivy\graphics\instructions.pyx", line 366, in kivy.graphics.instructions.VertexInstruction.source.__set__
   File "kivy\graphics\context_instructions.pyx", line 430, in kivy.graphics.context_instructions.BindTexture.source.__set__
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\core\image\__init__.py", line 561, in __init__
     self.filename = arg
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\core\image\__init__.py", line 756, in _set_filename
     mipmap=self._mipmap, nocache=self._nocache)
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\core\image\__init__.py", line 460, in load
     im = loader(filename, **kwargs)
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\core\image\__init__.py", line 223, in __init__
     self._data = self.load(filename)
   File "C:\Users\icarpis\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\core\image\img_sdl2.py", line 47, in load
     raise Exception('SDL2: Unable to load image')
 Exception: SDL2: Unable to load image
```

**Comment by icarpis** [comment]
@dostonru, I've updated my comment.

**Comment by tito** [comment]
This is expected, you are manipulating widget in a thread, and it will involve bad things.
CF https://github.com/kivy/kivy/wiki/Working-with-Python-threads-inside-a-Kivy-application

Deque your queue not in a thread with while loop, but use Clock.schedule_interval() instead, and forget about the while true.
