### ISSUE TITLE
Logger does deepcopy of record which fails in some environments

### ISSUE THREAD

**Issue by matham** [kivy/kivy#7528]
**Software Versions**
* Python: 3.7
* OS: Win
* Kivy: 2.1.0.dev0

**Describe the bug**
Doing `logging.exception(e)` from within a particular script fails when there's an object in the stack that can't be copied. The following the is the error I get:

```
 --- Logging error ---
 Traceback (most recent call last):
   File "G:/Python/libs/ceed/ceed/analysis/merge_data.py", line 1665, in <module>
     align = alignment[experiment] = merger.get_alignment()
   File "G:/Python/libs/ceed/ceed/analysis/merge_data.py", line 1378, in get_alignment
     return self._get_alignment(True)
   File "G:/Python/libs/ceed/ceed/analysis/merge_data.py", line 1394, in _get_alignment
     'Cannot find any experiment in the MCS parsed data')
 AlignmentException: Cannot find any experiment in the MCS parsed data
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "C:\Users\Matthew Einhorn\AppData\Local\Programs\Python\Python37\Lib\logging\__init__.py", line 1034, in emit
     msg = self.format(record)
   File "C:\Users\Matthew Einhorn\AppData\Local\Programs\Python\Python37\Lib\logging\__init__.py", line 880, in format
     return fmt.format(record)
   File "g:\python\libs\kivy\kivy\logger.py", line 291, in format
     record = copy.deepcopy(record)
   File "E:\Python\Python37\lib\copy.py", line 180, in deepcopy
     y = _reconstruct(x, memo, *rv)
   File "E:\Python\Python37\lib\copy.py", line 280, in _reconstruct
     state = deepcopy(state, memo)
   File "E:\Python\Python37\lib\copy.py", line 150, in deepcopy
     y = copier(x, memo)
   File "E:\Python\Python37\lib\copy.py", line 240, in _deepcopy_dict
     y[deepcopy(key, memo)] = deepcopy(value, memo)
   File "E:\Python\Python37\lib\copy.py", line 150, in deepcopy
     y = copier(x, memo)
   File "E:\Python\Python37\lib\copy.py", line 220, in _deepcopy_tuple
     y = [deepcopy(a, memo) for a in x]
   File "E:\Python\Python37\lib\copy.py", line 220, in <listcomp>
     y = [deepcopy(a, memo) for a in x]
   File "E:\Python\Python37\lib\copy.py", line 169, in deepcopy
     rv = reductor(4)
 TypeError: can't pickle traceback objects
 Call stack:
   File "G:/Python/libs/ceed/ceed/analysis/merge_data.py", line 1673, in <module>
     logging.exception(str(e))
 Message: 'Cannot find any experiment in the MCS parsed data'
 Arguments: ()

Process finished with exit code 0
```

It seems to be because of this line in kivy/logger.py: `record = copy.deepcopy(record)`.

**Comment by carstenfuchs** [comment]
I think this line was introduced in #7062 ?
A while ago I looked into the related code, but came to the conclusion that things are very much complicated by so much code being run on module import. Imho, #7172 and the issues it refers to summarize this well.

**Comment by Julian-O** [comment]
I have some code that solves this in the pipeline. 

#7172 describes a much larger (and IMO, more important) issue, but it does not need to be solved in order to remove the `deepcopy()` code.
