### ISSUE TITLE
On Android with ffpyplayer unable to load image image-loading.gif

### ISSUE THREAD

**Issue by abconnor** [kivy/kivy#7543]
**Software Versions**
* Python: 3.7.3
* OS: Debian Linux 10 / Android 10
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
After building with buildozer the app won't start because the loading image raises an exception
Here is what logcat says:

05-28 16:41:28.984 15070 15232 I python  : [WARNING] [Image       ] Unable to load image </data/user/0/kreisjugenddienst.de.kjdapp/files/app/_python_bundle/site-packages/kivy/data/images/image-loading.gif>
05-28 16:41:28.985 15070 15232 I python  :  Traceback (most recent call last):
05-28 16:41:28.986 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/app/main.py", line 784, in <module>
05-28 16:41:28.987 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/app.py", line 854, in run
05-28 16:41:28.989 15070 15232 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
05-28 16:41:28.990 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/app/main.py", line 720, in on_start
05-28 16:41:28.991 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/app/main.py", line 511, in veranst_karussel
05-28 16:41:28.993 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/app/main.py", line 275, in __init__
05-28 16:41:28.994 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/uix/behaviors/button.py", line 121, in __init__
05-28 16:41:28.995 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/uix/image.py", line 355, in __init__
05-28 16:41:28.996 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/uix/image.py", line 369, in _load_source
05-28 16:41:28.997 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/loader.py", line 474, in image
05-28 16:41:28.998 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/loader.py", line 184, in _get_loading_image
05-28 16:41:28.999 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/core/image/__init__.py", line 460, in load
05-28 16:41:29.000 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/core/image/__init__.py", line 223, in __init__
05-28 16:41:29.001 15070 15232 I python  :    File "/home/diakon/kivy_venv/share/TestApp/.buildozer/android/platform/build-arm64-v8a/build/python-installs/kjdapp/kivy/core/image/img_ffpyplayer.py", line 55, in load
05-28 16:41:29.003 15070 15232 I python  :    File "ffpyplayer/pic.pyx", line 982, in ffpyplayer.pic.ImageLoader.__cinit__
05-28 16:41:29.004 15070 15232 I python  :  Exception: Failed to open input file /data/user/0/kreisjugenddienst.de.kjdapp/files/app/_python_bundle/site-packages/kivy/data/images/image-loading.gif: Invalid data found when processing input
05-28 16:41:29.004 15070 15232 I python  : Python for android ended.
05-28 16:41:29.254  1399  1721 W InputDispatcher: channel '4803e6c kreisjugenddienst.de.kjdapp/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-28 16:41:29.255  1399  1721 E InputDispatcher: channel '4803e6c kreisjugenddienst.de.kjdapp/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-28 16:41:28.789  1399  8535 D BatteryService: mHealthInfo.batteryTemperature: 226
05-28 16:41:29.257  1399  8785 I ActivityManager: Process kreisjugenddienst.de.kjdapp (pid 15070) has died: fore TOP 

I use kivy.uix.videoplayer.Videoplayer and on my Linux System and there isn't a problem with that. I can't verify if the gif-file exists on my phone (not rooted), but on my computer it is in place. As default the property image_loading leads to image-loading.zip. Nevertheless the gif-file used to load. Define an other image as loading image at the declaration won't help. I included these libraries in the buildozer.spec file:
requirements = kivy,requests,urllib3,chardet,idna,ffpyplayer

Every suggestion is welcome!

**Comment by abconnor** [comment]
For those who might be interested in the solution:
The error was a version mismatch. Buildozer used version 1.11.1 of kivy, which causes conflicts with the used version of ffpyplayer. So I had to remove the folder .buildozer and all its components. Then I had to add "kivy==2.0.0" in requirements line of buildozer.spec. That's all. The next time I started the compilation, buildozer downloads the right version of kivy and the app starts.
