### ISSUE TITLE
File "kivy/core/text/_text_sdl2.pyx", line 63; TypeError: an integer is required

### ISSUE THREAD

**Issue by mahlangudf** [kivy/kivy#7552]
**Software Versions**
* Python: 3.8
* OS:
* Kivy: 1.11.1
* Kivy installation method:

**Describe the bug**
When I run "buildozer android debug deploy run"  the kivy app opens crashes on my android device .

I installed buildozer as instructed in https://buildozer.readthedocs.io/en/latest/installation.html:
"sudo apt update
sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
pip3 install --user --upgrade Cython==0.29.19 virtualenv  # the --user should be removed if you do this in a venv

# add the following line at the end of your ~/.bashrc file
export PATH=$PATH:~/.local/bin/"

**Expected behavior**

**To Reproduce**
buildozer android debug deploy run logcat

**Code and Logs and screenshots**
```python
-------- beginning of crash
--------- beginning of system
--------- beginning of main
06-13 07:40:46.219  2773  2924 I python  : Initializing Python for Android
06-13 07:40:46.219  2773  2924 I python  : Setting additional env vars from p4a_env_vars.txt
06-13 07:40:46.219  2773  2924 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
06-13 07:40:46.219  2773  2924 I python  : /data/user/0/org.test.myapp/files/app
06-13 07:40:46.219  2773  2924 I python  : Preparing to initialize python
06-13 07:40:46.219  2773  2924 I python  : _python_bundle dir exists
06-13 07:40:46.219  2773  2924 I python  : calculated paths to be...
06-13 07:40:46.219  2773  2924 I python  : /data/user/0/org.test.myapp/files/app/_python_bundle/stdlib.zip:/data/user/0/org.test.myapp/files/app/_python_bundle/modules
06-13 07:40:46.220  2773  2924 I python  : set wchar paths...
06-13 07:40:46.310  2773  2924 I python  : Initialized python
06-13 07:40:46.310  2773  2924 I python  : AND: Init threads
06-13 07:40:46.312  2773  2924 I python  : testing python print redirection
06-13 07:40:46.313  2773  2924 I python  : Android path ['.', '/data/user/0/org.test.myapp/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.test.myapp/files/app/_python_bundle/modules', '/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages']
06-13 07:40:46.313  2773  2924 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'DOWNLOAD_CACHE': '/data/cache', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/framework-oahl-backward-compatibility.jar:/system/framework/android.test.base.jar:/system/framework/featurelayer-widget.jar:/system/framework/hwEmui.jar:/system/framework/hwTelephony-common.jar:/system/framework/hwIms-common.jar:/system/framework/hwframework.jar:/system/framework/com.huawei.nfc.jar:/system/framework/org.ifaa.android.manager.jar:/system/framework/hwperf.jar:/system/framework/hwaps.jar:/system/framework/hwcustEmui.jar:/system/framework/hwcustframework.jar:/system/framework/hwcustTelephony-common.jar:/system/framework/servicehost.jar:/system/framework/hwIAwareAL.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar:/system/framework/hwServices.jar:/system/framework/hwWifi-service.jar:/system/framework/hwcustServices.jar:/system/framework/hwcustwifi-service.jar', 'OEM_ROOT': '/product/hw_oem/ANE-L21', 'ODM_PRODUCT': '/odm/hw_odm/ANE-L21', 'CUST_POLICY_DIRS': '/system/emui/base:/system/emui/oversea:/vendor/etc:/odm/etc:/product/etc:/odm/hw_odm/ANE-L21:/product/region_comm/oversea:/preas/oversea:/product/hw_oem/ANE-L21:/preload/ANE-L21/hw/meafnaf:/cust/global:/cust/hw/meafnaf:/product/special_cust/ANE-L21/hw/meafnaf', 'ANDROID_SOCKET_zygote': '18', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/user/0/org.test.myapp/files/app', 'ANDROID_APP_PATH': '/data/user/0/org.test.myapp/files/app', 'ANDROID_PRIVATE': '/data/user/0/org.test.myapp/files', 'ANDROID_UNPACK': '/data/user/0/org.test.myapp/files/app', 'PYTHONHOME': '/data/user/0/org.test.myapp/files/app', 'PYTHONPATH': '/data/user/0/org.test.myapp/files/app:/data/user/0/org.test.myapp/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
06-13 07:40:46.314  2773  2924 I python  : Android kivy bootstrap done. __name__ is __main__
06-13 07:40:46.314  2773  2924 I python  : AND: Ran string
06-13 07:40:46.314  2773  2924 I python  : Run user program, change dir and execute entrypoint
06-13 07:40:46.521  2773  2924 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 21)
06-13 07:40:46.521  2773  2924 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
06-13 07:40:46.535  2773  2924 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.myapp/files/app/.kivy/logs/kivy_21-06-13_0.txt
06-13 07:40:46.536  2773  2924 I python  : [INFO   ] [Kivy        ] v1.11.1
06-13 07:40:46.536  2773  2924 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
06-13 07:40:46.536  2773  2924 I python  : [INFO   ] [Python      ] v3.8.1 (default, Jun 13 2021, 07:29:42) 
06-13 07:40:46.536  2773  2924 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
06-13 07:40:46.537  2773  2924 I python  : [INFO   ] [Python      ] Interpreter at ""
06-13 07:40:47.704  2773  2924 I python  : [INFO   ] [Factory     ] 184 symbols loaded
06-13 07:40:48.156  2773  2924 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
06-13 07:40:48.265  2773  2924 I python  : [INFO   ] [Window      ] Provider: sdl2
06-13 07:40:48.304  2773  2924 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
06-13 07:40:48.306  2773  2924 I python  : [INFO   ] [GL          ] Backend used <sdl2>
06-13 07:40:48.307  2773  2924 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 v1.r28p0-01rel0.f5cf9dc031cadedb37ebf905af6437d5'>
06-13 07:40:48.307  2773  2924 I python  : [INFO   ] [GL          ] OpenGL vendor <b'ARM'>
06-13 07:40:48.307  2773  2924 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Mali-T830'>
06-13 07:40:48.307  2773  2924 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
06-13 07:40:48.308  2773  2924 I python  : [INFO   ] [GL          ] Texture max size <8192>
06-13 07:40:48.308  2773  2924 I python  : [INFO   ] [GL          ] Texture max units <16>
06-13 07:40:48.373  2773  2924 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
06-13 07:40:48.375  2773  2924 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
06-13 07:40:48.393  2773  2924 I python  : [INFO   ] [Text        ] Provider: sdl2
06-13 07:40:48.531  2773  2924 I python  : [WARNING] [Base        ] Unknown <android> provider
06-13 07:40:48.531  2773  2924 I python  : [INFO   ] [Base        ] Start application main loop
06-13 07:40:48.537  2773  2924 I python  : [INFO   ] [GL          ] NPOT texture support is available
06-13 07:40:48.549  2773  2924 I python  :  Traceback (most recent call last):
06-13 07:40:48.549  2773  2924 I python  :    File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
06-13 07:40:48.550  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 754, in _texture_fill
06-13 07:40:48.551  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 695, in render
06-13 07:40:48.551  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 678, in _render_real
06-13 07:40:48.552  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 656, in render_lines
06-13 07:40:48.552  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/text_sdl2.py", line 54, in _render_text
06-13 07:40:48.553  2773  2924 I python  :    File "kivy/core/text/_text_sdl2.pyx", line 63, in kivy.core.text._text_sdl2._SurfaceContainer.render
06-13 07:40:48.554  2773  2924 I python  :  TypeError: an integer is required
06-13 07:40:48.554  2773  2924 I python  :  Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
06-13 07:40:48.554  2773  2924 I python  :  Traceback (most recent call last):
06-13 07:40:48.554  2773  2924 I python  :    File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
06-13 07:40:48.555  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 754, in _texture_fill
06-13 07:40:48.555  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 695, in render
06-13 07:40:48.556  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 678, in _render_real
06-13 07:40:48.556  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/__init__.py", line 656, in render_lines
06-13 07:40:48.557  2773  2924 I python  :    File "/home/daniel/Documents/kivy_project/fieldmonitoring/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/kivy/core/text/text_sdl2.py", line 54, in _render_text
06-13 07:40:48.558  2773  2924 I python  :    File "kivy/core/text/_text_sdl2.pyx", line 63, in kivy.core.text._text_sdl2._SurfaceContainer.render
06-13 07:40:48.559  2773  2924 I python  :  TypeError: an integer is required



```

**Additional context**

**Comment by Julian-O** [comment]
A lot has changed in the past year. Can you confirm this is still a problem with a fresh build with the latest Kivy, Buildozer, P4A, SDK, NDK etc.?
