### ISSUE TITLE
Allow Original color of emoji font in Label

### ISSUE THREAD

**Issue by kengoon** [kivy/kivy#7565]
It would be awesome to if their is a way to display original emoji font in kivy Label instead of displaying light dark color of the emoji

What I mean by original color is: 😘😔🤵😔🤵🥺🙏🥺❤️
They all have color but when it is used with kivy Label or Text input, the color changes to light dark and when the color property is changed to any other color, it looses some details

**Comment by FilipeMarch** [comment]
For me even normal emojis do not work... do you know how to make normal emojis to work on a Label?

**Comment by Zerus97** [comment]
Hey @misl6 doing good? I was wondering if adding a font file thats specific for emojis would fix this problem. What do you think?

**Comment by misl6** [comment]
> Hey @misl6 doing good? I was wondering if adding a font file thats specific for emojis would fix this problem. What do you think?

Encountered this emoji issue while working on https://github.com/kivy/kivy/pull/8226, as the user can now input also emojis. Spoiler: this emoji thing it's giving me headaches these days.

Unfortunately, seems that on macOS and Linux we (the `SDL_ttf` build) have some issues rendering colored emoji.
Now I've been able to render Apple Color Emoji and noto emoji via https://github.com/PoomSmart/EmojiFonts, but not the official one.

Adding the font file will not fix the problem, and adds 20MB+ to our artifacts. Today I will try a build on Ubuntu, which may help to diagnose why Noto Color Emoji does not render with FreeType.

**Comment by misl6** [comment]
Current status:
macOS: ✅ (via #8317 )
Linux: ✅ (via #8313 )
Windows: ⚠️ Unknown, WIP.
Android: ⚠️ Unknown, likely needs some changes to the recipe
iOS: ⚠️ Unknown, likely needs some changes to the recipe

**Comment by amaendle** [comment]
I think there are just a few issues to make it work in Windows. Actually I do get the colored emoticons with that code in kivy:

```
# -*- coding: utf-8 -*-
import os
os.environ['KIVY_TEXT'] = 'sdl2'
#os.environ['KIVY_TEXT'] = 'pil'
#os.environ['KIVY_IMAGE'] = 'pil,sdl2'
from kivy.app import App
from kivy.uix.label import Label
from kivy.uix.boxlayout import BoxLayout

class MyApp(App):
    def build(self):
        layout = BoxLayout(orientation='vertical', padding=10)
        
        main_font="fonts/NotoSansSC-VariableFont_wght.ttf"
        text='[font=fonts/NotoColorEmoji]😊[/font] Hi! [font=fonts/NotoColorEmoji]🚀[/font] 你好 [font=fonts/NotoColorEmoji]🔞[/font]'

        combined_label = Label(
            text=text,
            font_name=main_font,
            font_size='19sp',
            markup=True
        )

        layout.add_widget(combined_label)

        return layout

if __name__ == '__main__':
    MyApp().run()
```

The problem is, that the size is not handled correctly and therefore the smileys are too large in this example. The png images in NotoColorEmoji have size 109, so if we request another size, the sdl2 text provider has to handle this by scaling the image accordingly (but it doesn't)

![image](https://github.com/user-attachments/assets/ec17fc18-dce8-4b2a-aff8-f69aaa7915d9)

When using the Pillow text provider, `os.environ['KIVY_TEXT'] = 'pil'`, we have similar issues. With PIL we would get the error "OSError: invalid pixel size", because the requested font size of 19 is not available in NotoColorEmoji.ttf (with NotoColorEmoji_WindowsCompatible.ttf it is the same result). However, setting `font_size='109sp'` in the code gives a result:

![image](https://github.com/user-attachments/assets/74e5970e-b718-4285-aa90-bd5fca72aa4d)

So, we have the same scaling problem as with the sdl2 text provider and missing colors.
The image is greyscale most probably , because `self._pil_draw.text((int(x), int(y)), text, font=font, fill=color)` in kivy/core/text/text_pil.py is missing the argument `embedded_color=True`.

So, there are some things to fix... but not too much.

**Comment by kengoon** [comment]
@amaendle are you using Kivy from master branch or from pypi?

**Comment by amaendle** [comment]
Some additional thoughts: to check for available fixed bitmap font sizes, we could use freetype:

```
import freetype
face = freetype.Face('fonts/NotoColorEmoji_WindowsCompatible.ttf')
available_sizes = face.available_sizes

if available_sizes:
    print("Available sizes:")
    for size in available_sizes:
        print(f"Width: {size.width}, Height: {size.height}, Size: {size.size}")
else:
    print("No fixed bitmap sizes available.")

```

> @amaendle are you using Kivy from master branch or from pypi?

I use Kivy from pypi.

**Comment by kengoon** [comment]
@amaendle try install from master branch and test again

**Comment by amaendle** [comment]
> @amaendle try install from master branch and test again

For `os.environ['KIVY_TEXT'] = 'pil'` the result is the same as before.

For `os.environ['KIVY_TEXT'] = 'sdl2'` I get an error:

```
 Traceback (most recent call last):
   File "C:\Users\[...]\NotoEmojiWinTest.py", line 49, in <module>
     MyApp().run()
   File "C:\Users\[...]\Lib\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\[...]\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\[...]\Lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\[...]\Lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\[...]\Lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\[...]\Lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\[...]\Lib\site-packages\kivy\uix\label.py", line 432, in texture_update
     self._label.texture.bind()
   File "kivy\\graphics\\texture.pyx", line 765, in kivy.graphics.texture.Texture.bind
   File "kivy\\graphics\\texture.pyx", line 785, in kivy.graphics.texture.Texture.bind
   File "kivy\\graphics\\texture.pyx", line 733, in kivy.graphics.texture.Texture.allocate
 Exception: Unable to allocate memory for texture (size is -1631716736)
```
