### ISSUE TITLE
TypeError: startswith first arg must be str or a tuple of str, not PureWindowsPath

### ISSUE THREAD

**Issue by Timtaran** [kivy/kivy#7574]
**Software Versions**
* Python: 3.8.6
* OS: W7x64
* Kivy: 2.0.0
* Kivy installation method: pip

**Describe the bug**
I have this error only when started exe app (pyinstaller)

```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "kivy_venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "kivy\__init__.py", line 272, in <module>
  File "kivy_venv\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
TypeError: startswith first arg must be str or a tuple of str, not PureWindowsPath

```

**Comment by rokm** [comment]
That's a PyInstaller 4.4 regression: pyinstaller/pyinstaller#6018

**Comment by Timtaran** [comment]
404: Not Found

**Comment by Timtaran** [comment]
``` 
pip install https://github.com/rokm/pyinstaller/archive/develop.zip
```
Now its not starting ._.

**Comment by akshayaurora** [comment]
As @rokm mentioned https://github.com/pyinstaller/pyinstaller/issues/6018 PyInstaller regression. Please track issue there.
