### ISSUE TITLE
Cant Use on M1 Ma

### ISSUE THREAD

**Issue by mindstormmaster1** [kivy/kivy#7668]
**Software Versions**
* Python: 3.9.6
* OS: MacOS
* Kivy: 2.0.0
* Kivy installation method: pip install

**Describe the bug**
When I try and run the example code in the getting started section it wont run because of an issue related to running on an M1 Mac. I really would like to know how to solve this issue! Thanks!

**Expected behavior**

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.

**Code and Logs and screenshots**
```python
/usr/local/bin/python3 "/Users/.../Downloads/Python/KivyMD APP 1/main.py"
...@...-MacBook-Air KivyMD APP 1 % /usr/local/bin/python3 "/Users/.../Downloads/Python/KivyMD APP 1/main.py"
[INFO   ] [Logger      ] Record log in /Users/ethansteckmann/.kivy/logs/kivy_21-10-23_8.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:14:58) 
[Clang 12.0.5 (clang-1205.0.22.9)]
[INFO   ] [Python      ] Interpreter at "/usr/local/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Analysing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.0.0.dev0, git-24f2f37, 2021-10-23 (installed at "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
 Traceback (most recent call last):
   File "/Users/ethansteckmann/Downloads/Python/KivyMD APP 1/main.py", line 1, in <module>
     from kivymd.app import MDApp
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivymd/__init__.py", line 70, in <module>
     import kivymd.font_definitions  # NOQA
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivymd/font_definitions.py", line 10, in <module>
     from kivy.core.text import LabelBase
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/core/text/__init__.py", line 85, in <module>
     from kivy.graphics.texture import Texture
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/graphics/__init__.py", line 89, in <module>
     from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \
 ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/graphics/instructions.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/graphics/instructions.cpython-39-darwin.so: mach-o, but wrong architecture
        /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kivy/graphics/instructions.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Additional context**

**Comment by misl6** [comment]
Kivy 2.1.0 is out and we now ship `universal2` binaries for Python 3.8-3.10.

Closing the issue cause should be fixed, anyway, if you still have some issue feel free to re-open it.
