### ISSUE TITLE
textinput crashed about kivy1.11.1

### ISSUE THREAD

**Issue by a1299646329** [kivy/kivy#7730]
Traceback (most recent call last):

  File "pos_main.py", line 170, in <module>

  File "pos_main.py", line 133, in main

  File "site-packages\kivy\app.py", line 855, in run

  File "site-packages\kivy\base.py", line 504, in runTouchApp

  File "site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop

  File "site-packages\kivy\core\window\window_sdl2.py", line 683, in _mainloop

  File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch

  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch

  File "kivy\_event.pyx", line 1138, in kivy._event.EventObservers._dispatch

  File "site-packages\kivy\core\window\__init__.py", line 163, in _on_window_key_down

  File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch

  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch

  File "kivy\_event.pyx", line 1138, in kivy._event.EventObservers._dispatch

  File "site-packages\kivy\uix\textinput.py", line 2573, in keyboard_on_key_down

  File "site-packages\kivy\uix\textinput.py", line 2425, in _key_down

  File "site-packages\kivy\uix\textinput.py", line 1147, in do_cursor_movement

IndexError: list index out of range

first I set textinput size to (0,0), then I press pageup on the keyboard.
 I get the crashed, It seems pgmove_speed  calculate error -1, 
`        pgmove_speed = int(self.height /
            (self.line_height + self.line_spacing) - 1)`

self._lines value is [''],  row value is 1
` elif action == 'cursor_pgup':`

> `            row = max(0, row - pgmove_speed)`

>  `           col = min(len(self._lines[row]), col)`

**Comment by misl6** [comment]
The issue still persists on `master`?
Can you please follow the issue template to add some more info? (https://github.com/kivy/kivy/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by misl6** [comment]
Closing for inactivity. Feel free to re-open the issue with all the details, as suggested, if the issue persists on `master`.
