### ISSUE TITLE
PiCamera causing error in Kivy 2.0.0 camera example app

### ISSUE THREAD

**Issue by leoshmu** [kivy/kivy#7738]
**Software Versions**
* Python: 3.7.3
* OS: Buster
* Kivy:2.0.0
* Kivy installation method:pip, following the tutorial online, including installing the source dependencies first, and then installing the kivy[full] option

**Describe the bug**

Camera app does not load. Window flashes for an instant and then disappears, error log suggest that a Camera module is not found

**Expected behavior**
Camera app should load

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.
run the main.py kivy-examples/camera file

**Code and Logs and screenshots**
```python
pi@raspberrypi:~ $ kivy_venv/share/kivy-examples/camera/main.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_22-01-06_1.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/pi/kivy_venv/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 19.3.2'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'V3D 4.2'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[CRITICAL] [Camera      ] Unable to find any valuable Camera provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
picamera - ModuleNotFoundError: No module named 'picamera'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 18, in <module>
    from picamera import PiCamera

gi - ModuleNotFoundError: No module named 'gi'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_gi.py", line 10, in <module>
    from gi.repository import Gst

opencv - ModuleNotFoundError: No module named 'cv2'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_opencv.py", line 48, in <module>
    import cv2

 Traceback (most recent call last):
   File "kivy_venv/share/kivy-examples/camera/main.py", line 58, in <module>
     TestCamera().run()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "kivy_venv/share/kivy-examples/camera/main.py", line 55, in build
     return CameraClick()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 361, in __init__
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 465, in apply_class_lang_rules
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 543, in apply
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
     child = cls(__no_builder=True)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 91, in __init__
     on_index()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 101, in _on_index
     self._camera = CoreCamera(index=self.index, stopped=True)
 TypeError: 'NoneType' object is not callable


```

**Additional context**
I have tried this with Kivy 2.0.0 using the stable and cuttting edge branches, also tried 1.11.1, and have loaded this on a Compute Module 4 and on a Raspberry Pi 4B

Raspistill works to give me a camera preview

I've also tried removing the resolution line as some others suggested in similar issue,         resolution: (640, 480), that did not fix it

If I uncomment the  logger lines in the camera sample app, the error code shows a little more information, but not sure if it is helpful. Thanks for your effort on kivy, I hope there is a simple fix!

```python

pi@raspberrypi:~ $ python kivy_venv/share/kivy-examples/camera/main.py
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_22-01-06_4.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/pi/kivy_venv/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[TRACE  ] [Lang        ] load file /home/pi/kivy_venv/lib/python3.7/site-packages/kivy/data/style.kv, using utf8 encoding
[TRACE  ] [Parser      ] parsing 1298 lines
[TRACE  ] [Parser      ] got directive <kivy 1.0>
[TRACE  ] [Builder     ] build rule for <Label>
[TRACE  ] [Builder     ] build rule for <-Button,-ToggleButton>
[TRACE  ] [Builder     ] build rule for <BubbleContent>
[TRACE  ] [Builder     ] build rule for <BubbleButton>
[TRACE  ] [Builder     ] build rule for <Slider>
[TRACE  ] [Builder     ] build rule for <ProgressBar>
[TRACE  ] [Builder     ] build rule for <SplitterStrip>
[TRACE  ] [Builder     ] build rule for <Scatter>
[TRACE  ] [Builder     ] build rule for <RelativeLayout>
[TRACE  ] [Builder     ] build rule for <Image,AsyncImage>
[TRACE  ] [Builder     ] build rule for <EffectWidget>
[TRACE  ] [Builder     ] build rule for <TabbedPanelContent>
[TRACE  ] [Builder     ] build rule for <TabbedPanelStrip>
[TRACE  ] [Builder     ] build rule for <StripLayout>
[TRACE  ] [Builder     ] build rule for <TabbedPanelHeader>
[TRACE  ] [Builder     ] build rule for <Selector>
[TRACE  ] [Builder     ] build rule for <TextInput>
[TRACE  ] [Builder     ] build rule for <TextInputCutCopyPaste>
[TRACE  ] [Builder     ] build rule for <CodeInput>
[TRACE  ] [Builder     ] build rule for <TreeViewNode>
[TRACE  ] [Builder     ] build rule for <TreeViewLabel>
[TRACE  ] [Builder     ] build rule for <StencilView>
[TRACE  ] [Builder     ] build rule for <FileChooserListLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserListView>
[TRACE  ] [Builder     ] build template for [FileListEntry@FloatLayout+TreeViewNode]
[TRACE  ] [Builder     ] build rule for <FileChooserIconLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserIconView>
[TRACE  ] [Builder     ] build template for [FileIconEntry@Widget]
[TRACE  ] [Builder     ] build rule for <FileChooserProgress>
[TRACE  ] [Builder     ] build rule for <Switch>
[TRACE  ] [Builder     ] build rule for <ModalView>
[TRACE  ] [Builder     ] build rule for <Popup>
[TRACE  ] [Builder     ] build rule for <SpinnerOption>
[TRACE  ] [Builder     ] build rule for <Spinner>
[TRACE  ] [Builder     ] build rule for <ActionBar>
[TRACE  ] [Builder     ] build rule for <ActionView>
[TRACE  ] [Builder     ] build rule for <ActionSeparator>
[TRACE  ] [Builder     ] build rule for <ActionButton,ActionToggleButton>
[TRACE  ] [Builder     ] build rule for <ActionLabel>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionCheck>
[TRACE  ] [Builder     ] build rule for <ActionPreviousImage@Image>
[TRACE  ] [Builder     ] build rule for <ActionPreviousButton@Button>
[TRACE  ] [Builder     ] build rule for <ActionPrevious>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionOverflow>
[TRACE  ] [Builder     ] build rule for <ActionDropDown>
[TRACE  ] [Builder     ] build template for [AccordionItemTitle@Label]
[TRACE  ] [Builder     ] build rule for <AccordionItem>
[TRACE  ] [Builder     ] build rule for <SettingSpacer>
[TRACE  ] [Builder     ] build rule for <SettingItem>
[TRACE  ] [Builder     ] build rule for <SettingBoolean>
[TRACE  ] [Builder     ] build rule for <SettingString>
[TRACE  ] [Builder     ] build rule for <SettingPath>
[TRACE  ] [Builder     ] build rule for <SettingOptions>
[TRACE  ] [Builder     ] build rule for <SettingTitle>
[TRACE  ] [Builder     ] build rule for <SettingSidebarLabel>
[TRACE  ] [Builder     ] build rule for <SettingsPanel>
[TRACE  ] [Builder     ] build rule for <Settings>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSidebar>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSidebar>
[TRACE  ] [Builder     ] build rule for <ContentPanel>
[TRACE  ] [Builder     ] build rule for <InterfaceWithTabbedPanel>
[TRACE  ] [Builder     ] build rule for <ScrollView>
[TRACE  ] [Builder     ] build rule for <VideoPlayerPreview>
[TRACE  ] [Builder     ] build rule for <VideoPlayerAnnotation>
[TRACE  ] [Builder     ] build rule for <VideoPlayer>
[TRACE  ] [Builder     ] build rule for <CheckBox>
[TRACE  ] [Builder     ] build rule for <ScreenManager>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Input@TextInput>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Label@Label>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Selector@BoxLayout>
[TRACE  ] [Builder     ] build rule for <ColorWheel>
[TRACE  ] [Builder     ] build rule for <ColorPicker>
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[TRACE  ] [Parser      ] parsing 17 lines
[TRACE  ] [Builder     ] build rule for <CameraClick>
[DEBUG  ] [App         ] Loading kv <kivy_venv/share/kivy-examples/camera/testcamera.kv>
[DEBUG  ] [App         ] kv <kivy_venv/share/kivy-examples/camera/testcamera.kv> not found
[TRACE  ] [Parser      ] parsing 19 lines
[TRACE  ] [Builder     ] build rule for <-CoverBehavior>
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 19.3.2'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'V3D 4.2'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <16>
[TRACE  ] [Cache       ] Flushed category kv.texture from cache
[TRACE  ] [Cache       ] Flushed category kv.shader from cache
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load </home/pi/kivy_venv/lib/python3.7/site-packages/kivy/data/glsl/default.png>
[TRACE  ] [Image       ] '/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/data/glsl/default.png', populate to textures (1)
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[TRACE  ] [Lang        ] Found 1 rules for <__main__.CameraClick object at 0xb43d0330>
[DEBUG  ] [Camera      ] Ignored <picamera> (import error)
[TRACE  ] 
Traceback (most recent call last):
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 18, in <module>
    from picamera import PiCamera
ModuleNotFoundError: No module named 'picamera'
[DEBUG  ] [Camera      ] Ignored <gi> (import error)
[TRACE  ] 
Traceback (most recent call last):
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_gi.py", line 10, in <module>
    from gi.repository import Gst
ModuleNotFoundError: No module named 'gi'
[DEBUG  ] [Camera      ] Ignored <opencv> (import error)
[TRACE  ] 
Traceback (most recent call last):
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_opencv.py", line 21, in <module>
    import opencv as cv
ModuleNotFoundError: No module named 'opencv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_opencv.py", line 48, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[CRITICAL] [Camera      ] Unable to find any valuable Camera provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
picamera - ModuleNotFoundError: No module named 'picamera'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_picamera.py", line 18, in <module>
    from picamera import PiCamera

gi - ModuleNotFoundError: No module named 'gi'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_gi.py", line 10, in <module>
    from gi.repository import Gst

opencv - ModuleNotFoundError: No module named 'cv2'
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 62, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/core/camera/camera_opencv.py", line 48, in <module>
    import cv2

 Traceback (most recent call last):
   File "kivy_venv/share/kivy-examples/camera/main.py", line 59, in <module>
     TestCamera().run()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "kivy_venv/share/kivy-examples/camera/main.py", line 56, in build
     return CameraClick()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 361, in __init__
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/widget.py", line 465, in apply_class_lang_rules
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 543, in apply
     rule_children=rule_children)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 659, in _apply_rule
     child = cls(__no_builder=True)
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 91, in __init__
     on_index()
   File "/home/pi/kivy_venv/lib/python3.7/site-packages/kivy/uix/camera.py", line 101, in _on_index
     self._camera = CoreCamera(index=self.index, stopped=True)
 TypeError: 'NoneType' object is not callable

```

**Comment by leoshmu** [comment]
> 

Thank you for your reply. When outside of the virtualenv, 
```
pip3 list | grep picamera
```
found picamera in the python3 dist-packages as expected. However, in the virtual environment, the lib/python3.7/site-packages folder does not contain picamera folder, and the pip3 list | grep picamera yields nothing. 

This is strange behavior, picamera is part of Buster as you stated and was already installed. 
I tried to fix this by installing picamera from within the virtual environment, but pip3 and apt-get both did not work to install picamera because picamera was detected outside of the virtualenv. 

I followed the steps of the Kivy install tutorial and made a virtual env as directed, but this seems to make picamera invisible. 

I manually copied the picamera folder from the /lib/python3/dist-packages folder directly into the kivy_venv/lib/python3.7/site-packages folder and the camera app worked great.

I think this is some sort of bug with the kivy installation process on raspberry pi, but maybe I'm making some sort of error in setting up the virtualenv
