### ISSUE TITLE
AttributeError in Kivy SVG Example

### ISSUE THREAD

**Issue by cedarbob** [kivy/kivy#7750]
**Software Versions**
* Python: 3.9
* OS: Linux
* Kivy: 2.0
* Kivy installation method: Conda package from conda-forge

**Describe the bug**
Program aborted with a traceback due to an attribute error.  

**Expected behavior**
Unknown; I haven't run this program before.

**To Reproduce**
Launch main.py from the kivy-examples/svg directory.

**Code and Logs and screenshots**
```
$python $CONDA_PREFIX/share/kivy-examples/svg/main.py
[INFO   ] [Logger      ] Record log in /home/rhr/.kivy/logs/kivy_22-01-13_9.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/rhr/Tools/miniconda3/envs/kivy_env/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17) 
[GCC 9.4.0]
[INFO   ] [Python      ] Interpreter at "/home/rhr/Tools/miniconda3/envs/kivy_env/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 460.91.03'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'Quadro P600/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/home/rhr/Tools/miniconda3/envs/kivy_env/share/kivy-examples/svg/main.py", line 50, in <module>
     SvgApp().run()
   File "/home/rhr/Tools/miniconda3/envs/kivy_env/lib/python3.9/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/rhr/Tools/miniconda3/envs/kivy_env/lib/python3.9/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/home/rhr/Tools/miniconda3/envs/kivy_env/share/kivy-examples/svg/main.py", line 43, in build
     svg = SvgWidget(filename, size_hint=(None, None))
   File "/home/rhr/Tools/miniconda3/envs/kivy_env/share/kivy-examples/svg/main.py", line 29, in __init__
     svg = Svg(filename)
   File "kivy/graphics/svg.pyx", line 429, in kivy.graphics.svg.Svg.__init__
   File "kivy/graphics/svg.pyx", line 519, in kivy.graphics.svg.Svg.source.__set__
   File "kivy/graphics/svg.pyx", line 535, in kivy.graphics.svg.Svg.set_tree
   File "kivy/graphics/svg.pyx", line 540, in kivy.graphics.svg.Svg.reload
   File "kivy/graphics/svg.pyx", line 571, in kivy.graphics.svg.Svg.parse_tree
 AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

```

**Comment by tshirtman** [comment]
this has been fixed in https://github.com/kivy/kivy/commit/68cdac45c55191e6431c0422ed4b17f1860f63b8 but we didn't have a release after 2.0 yet.
