### ISSUE TITLE
Kivy can't import package 'kivymd.stiffscroll.StiffScrollEffect'

### ISSUE THREAD

**Issue by BrightChanges** [kivy/kivy#7754]
Dear developers at Kivy,

Please, please help me.

Your database.py file in kivymd/uix/database.py path can't make the code "#:import StiffScrollEffect kivymd.stiffscroll.StiffScrollEffect" works for some reason...

Please takes a look at the trace below:

```
[INFO   ] [Logger      ] Record log in /Users/kienletrung/.kivy/logs/kivy_22-01-18_0.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/var/folders/g4/1xyrvs4j721f0tlsddrbxch00000gn/T/_MEI2YvYUa/kivy/__init__.pyc"
[INFO   ] [Python      ] v3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] [Python      ] Interpreter at "/Users/kienletrung/Desktop/CoinSnack4/dist/financiaz"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [KivyMD      ] 0.104.2.dev0 (installed at "/var/folders/g4/1xyrvs4j721f0tlsddrbxch00000gn/T/_MEI2YvYUa/kivymd/__init__.pyc")
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-14.7.18'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 6000'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[ERROR  ] 
Traceback (most recent call last):
  File "kivy/lang/parser.py", line 472, in execute_directives
ModuleNotFoundError: No module named 'kivymd.stiffscroll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kivy/lang/parser.py", line 474, in execute_directives
ModuleNotFoundError: No module named 'kivymd.stiffscroll'
 Traceback (most recent call last):
   File "kivy/lang/parser.py", line 472, in execute_directives
 ModuleNotFoundError: No module named 'kivymd.stiffscroll'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "kivy/lang/parser.py", line 474, in execute_directives
 ModuleNotFoundError: No module named 'kivymd.stiffscroll'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main.py", line 24, in <module>
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
   File "kivymd/uix/datatables.py", line 54, in <module>
   File "kivy/lang/builder.py", line 373, in load_string
   File "kivy/lang/parser.py", line 402, in __init__
   File "kivy/lang/parser.py", line 508, in parse
   File "kivy/lang/parser.py", line 483, in execute_directives
 kivy.lang.parser.ParserException: Parser: File "<inline>", line 3:
 ...
       1:
       2:#:import DEVICE_TYPE kivymd.material_resources.DEVICE_TYPE
 >>    3:#:import StiffScrollEffect kivymd.stiffscroll.StiffScrollEffect
       4:
       5:
 ...
 Unable to import package 'kivymd.stiffscroll.StiffScrollEffect'
[8390] Failed to execute script main
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]


```
This bug is very huge for me because it's preventing me from running my .exe file that uses Kivy and Python. A lot of other users are also struggling and can't use the datatable feature as well. Please help me and fix this bug. Thank you very much.

**Comment by BrightChanges** [comment]
For reference, here is the info about my Software:
Python: 3.8
OS: Mac
Kivy: 2.0.0
Kivy installation method: pip3 install https://github.com/kivy/kivy/archive/master.zip and pip3 install kivy

**Comment by BrightChanges** [comment]
I also asked about this bug on StackOverflow: https://stackoverflow.com/questions/70742358/modulenotfounderror-no-module-named-kivymd-stiffscroll

**Comment by BrightChanges** [comment]
check https://stackoverflow.com/questions/70742358/modulenotfounderror-no-module-named-kivymd-stiffscroll/70747391#70747391

**Comment by Rahul-siddu** [comment]
i 'm getting this exception while running my executable file . some exception related to MDDataATable.
i have attached a file in which the exceptions are shown  ,somebody help me to get through this



[2022-07-23_dsd_logger.log](https://github.com/kivy/kivy/files/9173250/2022-07-23_dsd_logger.log)
