### ISSUE TITLE
App crashes with ZeroDivisionError when vertical scrollbar is not visible

### ISSUE THREAD

**Issue by abedhammoud** [kivy/kivy#7803]
**Software Versions**
* Python: 3.10.2
* OS: windows 11
* Kivy: 2.1.0rc1
* Kivy installation method: pip install kivy[full] --pre

**Describe the bug**
The app contains a ScrollView. The vertical scrollbar becomes visible when you resize the application window (make it smaller).
With the vertical scrollbar visible, I can move the ScrollView as expected. If, however, you maximize the app window, and hence the scrollbar disappears,  trying to scroll by content (dragging the mouse) at the right side of the window (where the scroll bar is displayed when visible) causes the application to crash with a ZeroDivisionError: float division by zero.
 
**Expected behavior**
When the window is maximized, I expected the scrollbar to be invisible (which is the case) and trying to drag the mouse in the right side of the window not to have any effect, especially not to crash the application.

**To Reproduce**

```python
from kivy.app import App
from kivy.lang import Builder

Mykv = '''
BoxLayout:
    ScrollView:
        do_scroll: (True, True)
        bar_width:20
        bar_color: [0, 0, 1, 1]
        scroll_type: ['bars', 'content']
        BoxLayout:
            size_hint: (None, None)
            size: (800, 800)
            Label:
                text: '>' * 2000
'''

class MyApp(App):

    def build(self):
        return Builder.load_string(Mykv)

if __name__ == '__main__':
    MyApp().run()



[INFO   ] [Logger      ] Record log in C:\Users\alant\.kivy\logs\kivy_22-02-14_24.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.4.4
[INFO   ] [Kivy        ] v2.1.0rc1, git-87b6070, 20220212
[INFO   ] [Kivy        ] Installed at "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:26:10) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\alant\miniconda3\envs\alant\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 27.20.100.9621'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(R) Xe Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 27.20.100.9621'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "c:\Users\alant\OneDrive\Documents\dev\GitHub\alant-git\labs\kivy\scrollbug-ignore.py", line 26, in <module>
     MyApp().run()
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\base.py", line 296, in post_dispatch_input
     wid.dispatch('on_touch_move', me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\uix\scrollview.py", line 870, in on_touch_move
     if self.dispatch('on_scroll_move', touch):
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\alant\miniconda3\envs\alant\lib\site-packages\kivy\uix\scrollview.py", line 937, in on_scroll_move
     dy = touch.dy / float(height - height * self.vbar[1])
 ZeroDivisionError: float division by zero

```

**Additional context**
I have seen this issue with kivy 2.0, but the app crashed even when the scroll bar was visible. With 2.1.0.rc1 I can make the application crash only if the scrollbar is not visible.

**Comment by kuzeyron** [comment]
I can confirm this is happening on my end as well with `2.1.0.rc1`.
After scrolling many times.

**Comment by matham** [comment]
It's because the scroll view code doesn't take into account that the scrollview may be fully visible and that you could have `scroll_type: ['bars', 'content']` 😬

**Comment by abedhammoud** [comment]
Thanks, @kuzeyron, and @matham, for your input. @kuzeyron, are you sure the changes you made stopped the app from crashing? It still crashes for me. Just make sure the window size is such that the slider is not visible, and then drag the mouse at the right side. Crashes every time.

**Comment by kuzeyron** [comment]
Whatever I try it won't crash on my end. Could be different behavior between Windows and Linux.

**Comment by matham** [comment]
It still crashes for me!

**Comment by abedhammoud** [comment]
I tried on Ubuntu 20.04.3 LTS (GNU/Linux 5.10.60-1-microsoft-standard-WSL2 x86_64) running on a windows 11 machine and I have the same issue (with python 3.10.2, and kivy 2.1.0rc1). I will be able to test on my Linux box tomorrow and will share the results.

**Comment by abedhammoud** [comment]
Tried it also on a Linux ubuntu laptop 5.13.0-28 with python 3.10.2 and kivy 2.1.0.rc1 and the same issue appears.

**Comment by abedhammoud** [comment]
Working perfectly, thank you!!
