### ISSUE TITLE
Private ( _*) Widgets' Properties Cannot be Changed Post-Instantiation

### ISSUE THREAD

**Issue by Eastern-Skill7173** [kivy/kivy#7843]
**Software Versions**
* Python: 3.8.10
* OS: KDE Neon User Edition 5.24
* Kivy: 2.1.0
* Kivy installation method: pip ( _pip install kivy[base,media]_ )

**Describe the bug**
Private widget definitions ( _**classes that begin with an underscore**_ ) do not work correctly.
**You can define them and inherit from them but when they are instantiated, changing their properties will lead to a syntax error:**

`
     id: rail_item_holder
       ^
 SyntaxError: invalid syntax`

**Expected behavior**
Changing private widget definitions post initiation should not cause a `SyntaxError`

**To Reproduce**
```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.app import App

__all__ = (
    "NavigationRail",
)


class _RailItemHolder(GridLayout):
    """
    Custom grid layout to hold widgets irrelevant to this issue.
    """


class NavigationRail(BoxLayout):
    """
    Custom box layout to do additional calculations.
    """


class MainApp(App):
    def __init__(self, **kwargs):
        super(MainApp, self).__init__(**kwargs)
        self.kv = Builder.load_string("""
#:kivy 2.1.0
<_RailItemHolder>:
    # Definitions here apparently work fine...
    cols: 1
    size_hint_x: None
    width: "90dp"
    canvas.before:
        Color:
            rgba: (.5, .5, .5, 1)
        Rectangle:
            pos: root.pos
            size: root.size
<InheritanceTest@_RailItemHolder>:
    # It seems like you can also inherit from them
<NavigationRail>:
    _RailItemHolder:
        id: rail_item_holder
        # If you comment out the `id` you won't get an error anymore
NavigationRail:
""")

    def build(self):
        return self.kv


if __name__ == '__main__':
    MainApp().run()

```
**Full Kivy Log**
```
[INFO   ] [Logger      ] Record log in /home/eastern-skill7173/.kivy/logs/kivy_22-03-11_47.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/eastern-skill7173/PycharmProjects/Experminets/venv/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/home/eastern-skill7173/PycharmProjects/Experminets/venv/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
 Traceback (most recent call last):
   File "/home/eastern-skill7173/PycharmProjects/Experminets/new.py", line 53, in <module>
     MainApp().run()
   File "/home/eastern-skill7173/PycharmProjects/Experminets/new.py", line 26, in __init__
     self.kv = Builder.load_string("""
   File "/home/eastern-skill7173/PycharmProjects/Experminets/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
   File "/home/eastern-skill7173/PycharmProjects/Experminets/venv/lib/python3.8/site-packages/kivy/lang/parser.py", line 483, in __init__
     self.parse(content)
   File "/home/eastern-skill7173/PycharmProjects/Experminets/venv/lib/python3.8/site-packages/kivy/lang/parser.py", line 597, in parse
     rule.precompile()
   File "/home/eastern-skill7173/PycharmProjects/Experminets/venv/lib/python3.8/site-packages/kivy/lang/parser.py", line 341, in precompile
     x.precompile()
   File "/home/eastern-skill7173/PycharmProjects/Experminets/venv/lib/python3.8/site-packages/kivy/lang/parser.py", line 194, in precompile
     self.co_value = compile(value, self.ctx.filename or '<string>', mode)
   File "<string>", line 18
     id: rail_item_holder
       ^
 SyntaxError: invalid syntax

```

**Comment by gottadiveintopython** [comment]
The name of widget classes must starts with uppercase letter.
