### ISSUE TITLE
Adding a TextInput Hangs and then Crashes the App

### ISSUE THREAD

**Issue by carlcodling** [kivy/kivy#7866]
Whether using Python or a kv file I'm unable to add a TextInput without the app hanging & crashing.

I'm using Kubuntu 20.04, Python 3.8 and Kivy 2.1.0

As you can see in the attached screenshot the screen doesn't even load if I attempt to load the input on the initial screen (only the window header bar is visible), if I try to add it later once the initial screen has loaded then it simply hangs until I kill the window/app

```
from kivy.app import App


class Test(App):
    pass


Test().run()
```

```
MainBox:


<MainBox@BoxLayout>:
    TextInput:
        text:"test"
```

![Screenshot_20220414_190519](https://user-images.githubusercontent.com/54156540/163451106-0a0ff1a9-0f6f-4b2d-aff8-600c5b40f92a.png)

```
[INFO   ] Logger: Record log in /home/kailash/.kivy/logs/kivy_22-04-14_62.txt
[INFO   ] Kivy: v2.1.0
[INFO   ] Kivy: Installed at "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
[INFO   ] Python: Interpreter at "/home/kailash/.virtualenvs/kivy-thelab/bin/python"
[INFO   ] Logger: Purge log fired. Processing...
[INFO   ] Logger: Purge finished!
[INFO   ] Factory: 189 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'4.6 (Compatibility Profile) Mesa 21.2.6'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Mesa Intel(R) UHD Graphics (CML GT2)'>
[INFO   ] GL: OpenGL parsed version: 4, 6
[INFO   ] GL: Shading version <b'4.60'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/home/kailash/PycharmProjects/test2/main.py", line 8, in <module>
[WARNING] stderr:     Test().run()
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/app.py", line 954, in run
[WARNING] stderr:     self._run_prepare()
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/app.py", line 923, in _run_prepare
[WARNING] stderr:     self.load_kv(filename=self.kv_file)
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/app.py", line 696, in load_kv
[WARNING] stderr:     root = Builder.load_file(rfilename)
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/lang/builder.py", line 305, in load_file
[WARNING] stderr:     return self.load_string(data, **kwargs)
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/lang/builder.py", line 405, in load_string
[WARNING] stderr:     widget.apply_class_lang_rules(
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
[WARNING] stderr:     Builder.apply(
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/lang/builder.py", line 540, in apply
[WARNING] stderr:     self._apply_rule(
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/lang/builder.py", line 658, in _apply_rule
[WARNING] stderr:     child = cls(__no_builder=True)
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/uix/textinput.py", line 611, in __init__
[WARNING] stderr:     self._ensure_clipboard()
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/uix/textinput.py", line 2003, in _ensure_clipboard
[WARNING] stderr:     from kivy.core.clipboard import Clipboard, CutBuffer
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/core/clipboard/__init__.py", line 141, in <module>
[WARNING] stderr:     Clipboard = core_select_lib('clipboard', _clipboards, True)
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
[WARNING] stderr:     mod = importlib.__import__(name='{2}.{0}.{1}'.format(
[WARNING] stderr:   File "/home/kailash/.virtualenvs/kivy-thelab/lib/python3.8/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 17, in <module>
[WARNING] stderr:     p.communicate()
[WARNING] stderr:   File "/usr/lib/python3.8/subprocess.py", line 1015, in communicate
[WARNING] stderr:     stdout = self.stdout.read()
[WARNING] stderr: KeyboardInterrupt
```

**Comment by sccreeper** [comment]
You have to load the kv file in the App class' `build` method. For example:
---

**main.py**

```python
from kivy.app import App
from kivy.lang.builder import Builder

class Test(App):
    def build(self):
        return Builder.load_file("main.kv")


Test().run()
```

**main.kv**

```kvlang
MainBox:
  
<MainBox@BoxLayout>:
      TextInput:
          text:"test"
```

**Result**

![](https://i.imgur.com/DTmkKXv.png)

**Comment by carlcodling** [comment]
Thanks for responding but this still results in the same error. The kv file is being loaded and I can use any other widget or view within it but as soon as I add a textinput it freezes the app. 

Exactly the same code works fine if I load it on Android.

**Comment by carlcodling** [comment]
So I found the issue. I had to install xclip.
