### ISSUE TITLE
[Bug] : Unable to minimize app in `OpenBox` (linux window manager)

### ISSUE THREAD

**Issue by T-Dynamos** [kivy/kivy#7921]
Minimizing my app gives : 
```
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/usr/lib/python3.10/configparser.py", line 790, in get
     value = d[option]
   File "/usr/lib/python3.10/collections/__init__.py", line 986, in __getitem__
     return self.__missing__(key)            # support subclasses that define __missing__
   File "/usr/lib/python3.10/collections/__init__.py", line 978, in __missing__
     raise KeyError(key)
 KeyError: 'pause_on_minimize'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/tdynamos/PrivaChat/main.py", line 93, in <module>
     PrivaChat().run()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/usr/lib/python3.10/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/usr/lib/python3.10/site-packages/kivy/base.py", line 341, in mainloop
     self.window.mainloop()
   File "/usr/lib/python3.10/site-packages/kivy/core/window/window_sdl2.py", line 675, in mainloop
     if Config.getboolean('kivy', 'pause_on_minimize'):
   File "/usr/lib/python3.10/configparser.py", line 829, in getboolean
     return self._get_conv(section, option, self._convert_to_boolean,
   File "/usr/lib/python3.10/configparser.py", line 809, in _get_conv
     return self._get(section, conv, option, raw=raw, vars=vars,
   File "/usr/lib/python3.10/configparser.py", line 804, in _get
     return conv(self.get(section, option, **kwargs))
   File "/usr/lib/python3.10/site-packages/kivy/config.py", line 517, in get
     value = PythonConfigParser.get(self, section, option, **kwargs)
   File "/usr/lib/python3.10/configparser.py", line 793, in get
     raise NoOptionError(option, section)
 configparser.NoOptionError: No option 'pause_on_minimize' in section: 'kivy'

```

https://user-images.githubusercontent.com/68729523/180466660-67c01400-baf5-4996-b363-a721ea99b2a8.mp4

I use Plank as dock

**Comment by T-Dynamos** [comment]
Fixed it by setting in config
