### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.effects'

### ISSUE THREAD

**Issue by Rahul-siddu** [kivy/kivy#7924]
**Software Versions**
* Python:3.8.10
* OS:ubuntu 20.04
* Kivy:v2.1.0
* Kivy installation method:

I'm able to run my kivy python script using the terminal, but unable to run the executable file of that kivy python script. I get the following exceptions while running my executable file. 
I have created  executable file using pyinstaller.

I want to run a executable file for my kivy python script.

**Exceptions thrown while running executable file**

2022-07-23:12:22:37,395 ERROR    [parser.py:564] 
Traceback (most recent call last):
  File "kivy/lang/parser.py", line 553, in execute_directives
  File "<frozen importlib._bootstrap>", line 1093, in __import__
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivymd.effects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kivy/lang/parser.py", line 556, in execute_directives
  File "<frozen importlib._bootstrap>", line 1093, in __import__
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivymd.effects'
2022-07-23:12:22:37,395 WARNING  [logger.py:338] stderr: Traceback (most recent call last):
2022-07-23:12:22:37,395 WARNING  [logger.py:338] stderr:   File "kivy/lang/parser.py", line 553, in execute_directives
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 1093, in __import__
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-07-23:12:22:37,396 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr: ModuleNotFoundError: No module named 'kivymd.effects'
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr: 
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr: During handling of the above exception, another exception occurred:
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr: 
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr: Traceback (most recent call last):
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "kivy/lang/parser.py", line 556, in execute_directives
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 1093, in __import__
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-07-23:12:22:37,397 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-07-23:12:22:37,398 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2022-07-23:12:22:37,398 WARNING  [logger.py:338] stderr: ModuleNotFoundError: No module named 'kivymd.effects'
2022-07-23:12:22:37,398 WARNING  [logger.py:338] stderr: 
2022-07-23:12:22:37,398 WARNING  [logger.py:338] stderr: During handling of the above exception, another exception occurred:
2022-07-23:12:22:37,398 WARNING  [logger.py:338] stderr: 
2022-07-23:12:22:37,398 WARNING  [logger.py:338] stderr: Traceback (most recent call last):
2022-07-23:12:22:37,398 WARNING  [logger.py:338] stderr:   File "kube.py", line 63, in <module>
2022-07-23:12:22:37,399 WARNING  [logger.py:338] stderr:     from kivymd.uix.datatables import MDDataTable
2022-07-23:12:22:37,399 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-07-23:12:22:37,400 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-07-23:12:22:37,400 WARNING  [logger.py:338] stderr:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2022-07-23:12:22:37,400 WARNING  [logger.py:338] stderr:   File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2022-07-23:12:22:37,400 WARNING  [logger.py:338] stderr:   File "kivymd/uix/datatables.py", line 86, in <module>
2022-07-23:12:22:37,400 WARNING  [logger.py:338] stderr:   File "kivy/lang/builder.py", line 372, in load_string
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr:   File "kivy/lang/parser.py", line 483, in __init__
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr:   File "kivy/lang/parser.py", line 590, in parse
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr:   File "kivy/lang/parser.py", line 565, in execute_directives
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr: kivy.lang.parser.ParserException: Parser: File "<inline>", line 3:
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr: ...
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr:       1:
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr:       2:#:import DEVICE_TYPE kivymd.material_resources.DEVICE_TYPE
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr: >>    3:#:import StiffScrollEffect kivymd.effects.stiffscroll.StiffScrollEffect
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr:       4:
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr:       5:
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr: ...
2022-07-23:12:22:37,401 WARNING  [logger.py:338] stderr: Unable to import package 'kivymd.effects.stiffscroll.StiffScrollEffect'

**Comment by misl6** [comment]
Hi @Rahul-siddu !

I guess that you're trying to use `kivymd`, which is not installed on your side.
