### ISSUE TITLE
TypeError: Cannot convert kivy.properties.BoundedNumericPropertyStorage to kivy.properties.NumericPropertyStorage

### ISSUE THREAD

**Issue by Uraniumhazee** [kivy/kivy#8012]
**Software Versions**
* Python: 3.9.13
* OS: Windows
* Kivy: Kivy         2.1.0
* Kivymd: Kivymd       0.104.1
* Kivy installation method:
conda install -c conda-forge kivymd and
conda install -c conda-forge kivy
installed on the same ENV

**Describe the bug**
TypeError: Cannot convert kivy.properties.BoundedNumericPropertyStorage to kivy.properties.NumericPropertyStorage

main py file:
```
from kivy.lang import Builder
from kivymd.app import MDApp

class MainApp(MDApp):

    def build(self):
        self.theme_cls.theme_style = 'Dark'
        self.theme_cls.primary_palette = 'Pink'
        return Builder.load_file('Ask.kv')

MainApp().run()
```

KV file: (Ask.kv)

```
Screen:
    MDCard:
        size_hint: None, None
        size: 300, 400
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        elevation: 10
        padding: 25
        spacing: 25
        orientation: 'vertical'

        MDLabel:
            id: welcome_label
            text: 'WELCOME'
            font_size: 40
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 15

        MDTextFieldRect:
            multiline: False
            text: 'İsim Giriniz'
            on_text_validate:  app.input()
            font_size: 32
        MDRoundFlatButton:
            text: 'logın'
            font_size: 12
            pos_hint: {'center_x': 0.5}
        MDRoundFlatButton:
            text: 'logın'
            font_size: 12
            pos_hint: {'center_x': 0.5}
```

**Code and Logs and screenshots**
```(kivyEnv) C:\Users\Messi\Desktop\Python>C:/Users/Messi/anaconda3/envs/kivyEnv/python.exe "c:/Users/Messi/Desktop/Python/Projects/Kivy Lessons/Ask/main.py"
[←[1;32mINFO←[0m   ] [Logger      ] Record log in C:\Users\Messi\.kivy\logs\kivy_22-09-18_9.txt
[←[1;32mINFO←[0m   ] [Kivy        ] v2.1.0
[←[1;32mINFO←[0m   ] [Kivy        ] Installed at "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\__init__.py"
[←[1;32mINFO←[0m   ] [Python      ] v3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
[←[1;32mINFO←[0m   ] [Python      ] Interpreter at "C:\Users\Messi\anaconda3\envs\kivyEnv\python.exe"
[←[1;32mINFO←[0m   ] [Logger      ] Purge log fired. Processing...
[←[1;32mINFO←[0m   ] [Logger      ] Purge finished!
[←[1;32mINFO←[0m   ] [Factory     ] 189 symbols loaded
[←[1;32mINFO←[0m   ] [KivyMD      ] v0.104.1
[←[1;32mINFO←[0m   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[←[1;32mINFO←[0m   ] [Window      ] Provider: sdl2
[←[1;32mINFO←[0m   ] [GL          ] Using the "OpenGL" graphics system
[←[1;32mINFO←[0m   ] [GL          ] GLEW initialization succeeded
[←[1;32mINFO←[0m   ] [GL          ] Backend used <glew>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 473.81'>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 960/PCIe/SSE2'>
[←[1;32mINFO←[0m   ] [GL          ] OpenGL parsed version: 4, 6
[←[1;32mINFO←[0m   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[←[1;32mINFO←[0m   ] [GL          ] Texture max size <16384>
[←[1;32mINFO←[0m   ] [GL          ] Texture max units <32>
[←[1;32mINFO←[0m   ] [Window      ] auto add sdl2 input provider
[←[1;32mINFO←[0m   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[←[1;32mINFO←[0m   ] [Text        ] Provider: sdl2
[←[1;32mINFO←[0m   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 555, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 1264, in kivy.properties.BoundedNumericProperty.check
 TypeError: Cannot convert kivy.properties.NumericPropertyStorage to kivy.properties.BoundedNumericPropertyStorage

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "c:\Users\Messi\Desktop\Python\Projects\Kivy Lessons\Ask\main.py", line 11, in <module>
     MainApp().run()
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\app.py", line 954, in run
     self._run_prepare()
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\app.py", line 924, in _run_prepare
     root = self.build()
   File "c:\Users\Messi\Desktop\Python\Projects\Kivy Lessons\Ask\main.py", line 9, in build
     return Builder.load_file('Ask.kv')
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 305, in load_file
     return self.load_string(data, **kwargs)
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 407, in load_string
     self._apply_rule(
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 540, in apply
     self._apply_rule(
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 709, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 60:
 ...
      58:    lbl_txt: lbl_txt
      59:    height: dp(36) if not root._height else root._height
 >>   60:    width: lbl_txt.texture_size[0] + root.increment_width
      61:    padding: (dp(8), 0)
      62:    theme_text_color: 'Primary' if not root.text_color else 'Custom'
 ...
 TypeError: Cannot convert kivy.properties.NumericPropertyStorage to kivy.properties.BoundedNumericPropertyStorage
   File "C:\Users\Messi\anaconda3\envs\kivyEnv\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 555, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 1264, in kivy.properties.BoundedNumericProperty.check
```

When i run code i got this error. How can i fix it.
If i install kivy and kivymd as 
pip install kivy and pip install kivymd 
There is no problem.

But i have anaconda and if i install with 
conda install -c conda-forge kivymd and
conda install -c conda-forge kivy
Above erorr occurs!

Thanks

**Comment by RobertFlatt** [comment]
Did you compare the KivyMD versions provided respectively by pip and conda?

This is a support question, please close the issue and if necessary move it to Discord or Google Groups.
