### ISSUE TITLE
ImportError: cannot import name 'sep' from 'posixpath' (/usr/lib/python3.10/posixpath.py)

### ISSUE THREAD

**Issue by rothloup** [kivy/kivy#8037]
**Software Versions**
* Python:  3.10.6
* OS:  Ubuntu 22.04
* Kivy:  2.1.0
* Kivy installation method:  pip install into venv via PyCharm from pypi

**Describe the bug**
Debugging a simple Kivy app under PyCharm generates "AttributeError: module 'posixpath' has no attribute 'sep'"

**Expected behavior**
No AttributeError should be generated, app should run same under runtime and debug conditions.

**To Reproduce**
Run this code under DEBUG using PyCharm
```
from kivy.core.window import Window
import os
from os.path import sep
```

**Code and Logs and screenshots**
```
<project_root>/venv/bin/python /snap/pycharm-community/291/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 45611 --file <project_root>/test.py
Connected to pydev debugger (build 221.6008.17)
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "<project_root>/venv/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
[INFO   ] [Python      ] Interpreter at "<project_root>/venv/bin/python"
[INFO   ] [Factory     ] 189 symbols loaded
[DEBUG  ] [Cache       ] register <kv.resourcefind> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 510.85.02'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1660/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load <<project_root>/venv/lib/python3.10/site-packages/kivy/data/glsl/default.png>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/snap/pycharm-community/291/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
     pydev_imports.execfile(file, globals, locals)  # execute the script
   File "/snap/pycharm-community/291/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
     exec(compile(contents+"\n", file, 'exec'), glob, loc)
   File "<project_root>/test.py", line 3, in <module>
     from os.path import sep
 ImportError: cannot import name 'sep' from 'posixpath' (/usr/lib/python3.10/posixpath.py)
python-BaseException

Process finished with exit code 1
```
**Additional context**
Code runs fine under runtime mode.  Bug only appears under Debug conditions.
Other projects report similar issue - see, for example, https://github.com/stub42/pytz/issues/72 and https://pythontechworld.com/issue/pallets/jinja/1697

Suggested Fix:
Edit "filechooser.py", and any other places in kivy source that import "sep" from "os.posixpath" to instead import from "os.sep".  https://docs.python.org/3/library/os.html#os.sep

**Comment by Vadimatorik** [comment]
I am also getting this error:
```
Kivy                   2.1.0
Kivy-examples          2.1.0
Kivy-Garden            0.1.5
kivymd                 1.1.1
```
Python 3.10.6

**Comment by gwhittey-pcode** [comment]
I had same issue I just installed python3.9 and then used that to create virtualenv
