### ISSUE TITLE
Timeout error in asyncio_basic example 

### ISSUE THREAD

**Issue by yves-surrel** [kivy/kivy#8066]
**Software Versions**
* Python: 3.8.15
* OS: MacOS 11.7
* Kivy: 2.0.0
* ipykernel: 5.3.4
* Kivy installation method: `conda install -c conda-forge kivy`

**Describe the bug**
Got `asyncio.exceptions.TimeoutError`

**Expected behavior**
Example running ok

**Code and Logs and screenshots**
Naively tried:
```
python asyncio_basic.py
```

```
[INFO   ] [Logger      ] Record log in /Users/yves/.kivy/logs/kivy_22-12-03_37.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/Users/yves/opt/miniconda3/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.15 (default, Nov 10 2022, 13:17:42) 
[Clang 14.0.6 ]
[INFO   ] [Python      ] Interpreter at "/Users/yves/opt/miniconda3/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 ATI-4.6.21'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon Pro 555 OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
Sitting on the beach
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "asyncio_basic.py", line 58, in <module>
     loop.run_until_complete(root_func())
   File "/Users/yves/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
     return future.result()
   File "asyncio_basic.py", line 28, in run_app_happily
     await async_runTouchApp(root, async_lib='asyncio')  # run Kivy
   File "/Users/yves/opt/miniconda3/lib/python3.8/site-packages/kivy/base.py", line 605, in async_runTouchApp
     await EventLoop.async_mainloop()
   File "/Users/yves/opt/miniconda3/lib/python3.8/site-packages/kivy/base.py", line 362, in async_mainloop
     await self.async_idle()
   File "/Users/yves/opt/miniconda3/lib/python3.8/site-packages/kivy/base.py", line 426, in async_idle
     await Clock.async_tick()
   File "/Users/yves/opt/miniconda3/lib/python3.8/site-packages/kivy/clock.py", line 739, in async_tick
     current = await self.async_idle()
   File "/Users/yves/opt/miniconda3/lib/python3.8/site-packages/kivy/clock.py", line 1057, in async_idle
     await self._async_wait_for(
   File "/Users/yves/opt/miniconda3/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
     raise exceptions.TimeoutError()
 asyncio.exceptions.TimeoutError
```

**Additional context**
Same using `ipython` instead of `python`

**Comment by RobertFlatt** [comment]
Try the current Kivy which is 2.1.0, this example worked for me on Windows and Ubuntu.

**Comment by yves-surrel** [comment]
Same with kivy 2.1.0

Here is my full configuration

```
anyio                     3.5.0            py38hecd8cb5_0  
aom                       3.4.0                hb486fe8_1    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.2           py38hecd8cb5_1001  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py38hca72f7f_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     22.1.0           py38hecd8cb5_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1           py38hecd8cb5_0  
blas                      2.116                  openblas    conda-forge
blas-devel                3.9.0           16_osx64_openblas    conda-forge
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.0               h8346a28_1  
brotli                    1.0.9                hca72f7f_7  
brotli-bin                1.0.9                hca72f7f_7  
brotlipy                  0.7.0           py38h9ed2024_1003  
brunsli                   0.1                  h23ab428_0  
buildozer                 1.4.0                    pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.18.1               hca72f7f_0  
ca-certificates           2022.9.24            h033912b_0    conda-forge
cairo                     1.16.0               h691a603_2  
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38hc55c11b_0  
cfitsio                   3.470                hbd21bf8_7  
chaco                     5.0.0.1                       1    dbanas
charls                    2.2.0                h23ab428_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
colorama                  0.4.6                    pypi_0    pypi
conda                     22.11.0          py38h50d1736_0    conda-forge
conda-package-handling    1.9.0            py38hca72f7f_1  
cryptography              38.0.1           py38hf6deb26_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.29.32          py38he9d5cce_0  
cytoolz                   0.12.0           py38hca72f7f_0  
dask-core                 2022.7.0         py38hecd8cb5_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
distlib                   0.3.6                    pypi_0    pypi
docutils                  0.18.1           py38hecd8cb5_3  
eigen                     3.3.7                haf03e11_1  
enable                    5.2.1.1          py38h68654b4_1    dbanas
entrypoints               0.4              py38hecd8cb5_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.9                he9d5cce_0  
ffmpeg                    4.4.2           lgpl_h418d387_2    conda-forge
fftw                      3.3.9                h9ed2024_1  
filelock                  3.8.0                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                hd3eb1b0_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.13.1               hb62acd4_1  
fonts-anaconda            1                    h8fa9717_0  
fonts-conda-ecosystem     1                    hd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               hd8bbffd_0  
fribidi                   1.0.10               haf1e3a3_0  
fsspec                    2022.10.0        py38hecd8cb5_0  
gdk-pixbuf                2.42.8               h90ff1d3_1  
gettext                   0.21.0               h7535e17_0  
giflib                    5.2.1                haf1e3a3_0  
glib                      2.72.1               h2292cb8_0    conda-forge
glib-tools                2.72.1               h2292cb8_0    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.7.8                h207c4f0_0    conda-forge
gpyfft                    0.7.3                    pypi_0    pypi
graphite2                 1.3.14               he9d5cce_1  
graphviz                  2.50.0               h196fa6a_0  
gst-plugins-base          1.20.3               h37e1711_1    conda-forge
gstreamer                 1.20.3               h1d18e73_1    conda-forge
gts                       0.7.6                h6759243_3  
harfbuzz                  4.4.1                h00bb2c2_0    conda-forge
hdf5                      1.12.1          nompi_ha60fbc9_104    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
idna                      3.4              py38hecd8cb5_0  
imagecodecs               2021.8.26        py38h0f85e6e_1  
imageio                   2.19.3           py38hecd8cb5_0  
importlib-metadata        5.1.0                    pypi_0    pypi
importlib_resources       5.2.0              pyhd3eb1b0_1  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   8.6.0            py38hecd8cb5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipytree                   0.2.2              pyhd8ed1ab_0    conda-forge
ipywidgets                7.6.5              pyhd3eb1b0_1  
jasper                    2.0.33               h013e400_0    conda-forge
jedi                      0.18.1           py38hecd8cb5_1  
jinja2                    3.1.2            py38hecd8cb5_0  
jpeg                      9e                   hca72f7f_0  
jsonschema                4.16.0           py38hecd8cb5_0  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_core              4.11.2           py38hecd8cb5_0  
jupyter_server            1.18.1           py38hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jxrlib                    1.1                  haf1e3a3_2  
kivy                      2.1.0            py38h8cfb1c7_1    conda-forge
kivy-garden               0.1.5                    pypi_0    pypi
kivymd                    1.1.1                    pypi_0    pypi
kiwisolver                1.4.2            py38he9d5cce_0  
krb5                      1.19.3               hb49756b_0    conda-forge
lame                      3.100             hb7f2c08_1003    conda-forge
lcms2                     2.12                 hf1fd2bf_0  
lerc                      3.0                  he9d5cce_0  
libaec                    1.0.4                hb1e8313_1  
libblas                   3.9.0           16_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                hca72f7f_7  
libbrotlidec              1.0.9                hca72f7f_7  
libbrotlienc              1.0.9                hca72f7f_7  
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libclang                  14.0.6          default_h55ffa42_0    conda-forge
libclang13                14.0.6          default_hb5731bd_0    conda-forge
libcurl                   7.85.0               h6dfd666_0  
libcxx                    14.0.6               h9765a3e_0  
libdeflate                1.8                  h9ed2024_5  
libedit                   3.1.20210910         hca72f7f_0  
libev                     4.33                 h9ed2024_1  
libffi                    3.4.2                h0d85af4_5    conda-forge
libgd                     2.3.3                he7e2580_1  
libgfortran               5.0.0           11_3_0_hecd8cb5_28  
libgfortran5              11.3.0              h9dfd629_28  
libglib                   2.72.1               hfbcb929_0    conda-forge
libiconv                  1.16                 hca72f7f_2  
libidn2                   2.3.3                hac89ed1_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
liblapacke                3.9.0           16_osx64_openblas    conda-forge
libllvm12                 12.0.0               h9b2ccf5_3  
libllvm14                 14.0.6               h5b596cc_1    conda-forge
libnghttp2                1.46.0               ha29bfda_0  
libogg                    1.3.4                h35c211d_1    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libopencv                 4.6.0            py38he6c0e75_1    conda-forge
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.37               ha441bb4_0  
libpq                     14.5                 h4aa9af9_2    conda-forge
libprotobuf               3.20.2               hbc0c0cd_0    conda-forge
librsvg                   2.54.4               h52d90eb_0  
libsodium                 1.0.18               h1de35cc_0  
libsqlite                 3.40.0               ha978bb4_0    conda-forge
libssh2                   1.10.0               h0a4fc7d_0  
libtasn1                  4.19.0               hb7f2c08_0    conda-forge
libtiff                   4.4.0                h2cd0358_2  
libtool                   2.4.6             he9d5cce_1008  
libunistring              0.9.10               h0d85af4_0    conda-forge
libvorbis                 1.3.7                h046ec9c_0    conda-forge
libvpx                    1.11.0               he49afe7_3    conda-forge
libwebp                   1.2.4                h56c3ce4_0  
libwebp-base              1.2.4                hca72f7f_0  
libxml2                   2.9.14               hea49891_4    conda-forge
libxslt                   1.1.35               h5b33f42_0  
libzlib                   1.2.13               hfd90126_4    conda-forge
libzopfli                 1.0.3                hb1e8313_0  
llvm-openmp               14.0.6               h0dcd299_0  
locket                    1.0.0            py38hecd8cb5_0  
lxml                      4.9.1            py38h65b224f_0  
lz4-c                     1.9.3                h23ab428_1  
mako                      1.2.3            py38hecd8cb5_0  
markupsafe                2.1.1            py38hca72f7f_0  
matplotlib                3.5.3            py38hecd8cb5_0  
matplotlib-base           3.5.3            py38hfb0c5b7_0  
matplotlib-inline         0.1.6            py38hecd8cb5_0  
mistune                   0.8.4           py38h1de35cc_1001  
munkres                   1.1.4                      py_0  
mysql-common              8.0.31               h7ebae80_0    conda-forge
mysql-libs                8.0.31               hc37e033_0    conda-forge
nbclassic                 0.4.8            py38hecd8cb5_0  
nbclient                  0.5.13           py38hecd8cb5_0  
nbconvert                 6.5.4            py38hecd8cb5_0  
nbformat                  5.5.0            py38hecd8cb5_0  
ncurses                   6.3                  hca72f7f_3  
nest-asyncio              1.5.5            py38hecd8cb5_0  
nettle                    3.8.1                h96f3785_1    conda-forge
networkx                  2.8.4            py38hecd8cb5_0  
notebook                  6.5.2            py38hecd8cb5_0  
notebook-shim             0.2.2            py38hecd8cb5_0  
nspr                      4.33                 he9d5cce_0  
nss                       3.78                 ha8197d3_0    conda-forge
numpy                     1.23.4           py38h57a7bef_0  
numpy-base                1.23.4           py38hc93c6d9_0  
openblas                  0.3.21          openmp_hbefa662_3    conda-forge
opencv                    4.6.0            py38h50d1736_1    conda-forge
openh264                  2.2.0                h2292cb8_1    conda-forge
openjpeg                  2.4.0                h66ea3da_0  
openssl                   1.1.1s               hfd90126_1    conda-forge
p11-kit                   0.24.1               h65f8906_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
pango                     1.50.7               h80fe9ab_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_1  
pcre                      8.45                 h23ab428_0  
pep517                    0.6.0                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.2.0            py38hde71d04_1  
pip                       22.2.2           py38hecd8cb5_0  
pixman                    0.40.0               h9ed2024_1  
pkgutil-resolve-name      1.3.10           py38hecd8cb5_0  
platformdirs              2.5.4                    pypi_0    pypi
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                     py38_0  
prometheus_client         0.14.1           py38hecd8cb5_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-opencv                 4.6.0            py38h60dac5d_1    conda-forge
pycosat                   0.6.4            py38hca72f7f_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyface                    7.3.0            py38hecd8cb5_1  
pygments                  2.11.2             pyhd3eb1b0_0  
pyopencl                  2022.3                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9            py38hecd8cb5_0  
pyqt                      5.15.7           py38he9d5cce_0  
pyqt5-sip                 12.11.0          py38he9d5cce_0  
pyrsistent                0.18.0           py38hca72f7f_0  
pyserial                  3.5              py38hecd8cb5_0  
pysocks                   1.7.1                    py38_1  
python                    3.8.15          hc915b28_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py38hecd8cb5_0  
python-graphviz           0.20.1           py38hecd8cb5_0  
python.app                3                py38hca72f7f_0  
python_abi                3.8                      2_cp38    conda-forge
pytoml                    0.1.21                   pypi_0    pypi
pytools                   2022.1.13                pypi_0    pypi
pywavelets                1.3.0            py38hca72f7f_0  
pyyaml                    6.0              py38hca72f7f_1  
pyzmq                     23.2.0           py38he9d5cce_0  
qt-main                   5.15.6               he04cef1_0    conda-forge
qt-webengine              5.15.9               h90a370e_4  
qtwebkit                  5.212                ha2e9019_6    conda-forge
readline                  8.2                  hca72f7f_0  
regex                     2022.7.9         py38hca72f7f_0  
requests                  2.28.1           py38hecd8cb5_0  
ruamel.yaml               0.16.12          py38hed1de0f_3    conda-forge
ruamel.yaml.clib          0.2.7            py38hef030d1_0    conda-forge
ruamel_yaml               0.15.100         py38h9ed2024_0  
scikit-image              0.19.2           py38hae1ba45_0  
scipy                     1.9.3            py38h1d874dc_0  
sdl2                      2.0.22               hb486fe8_2    conda-forge
sdl2_image                2.0.5                h7fada4f_0    conda-forge
sdl2_mixer                2.0.4                h6de7cb9_0    conda-forge
sdl2_ttf                  2.0.15               hc42bb53_0    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                65.5.0           py38hecd8cb5_0  
sh                        1.14.3                   pypi_0    pypi
sip                       6.6.2            py38he9d5cce_0  
six                       1.16.0             pyhd3eb1b0_1  
smpeg2                    2.0.0                hfc679d8_1    conda-forge
snappy                    1.1.9                he9d5cce_0  
sniffio                   1.2.0            py38hecd8cb5_1  
soupsieve                 2.3.2.post1      py38hecd8cb5_0  
spyder-kernels            2.2.0            py38hecd8cb5_0  
sqlite                    3.40.0               h880c91c_0  
stack_data                0.2.0              pyhd3eb1b0_0  
svt-av1                   1.1.0                hb486fe8_1    conda-forge
terminado                 0.13.1           py38hecd8cb5_0  
tifffile                  2021.7.2           pyhd3eb1b0_2  
tinycss2                  1.2.1            py38hecd8cb5_0  
tk                        8.6.12               h5d9f67b_0  
toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.12.0           py38hecd8cb5_0  
tornado                   6.2              py38hca72f7f_0  
tqdm                      4.64.1           py38hecd8cb5_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
traits                    6.2.0            py38h9ed2024_0  
traitsui                  7.2.1              pyhd3eb1b0_0  
typing-extensions         4.4.0                    pypi_0    pypi
typing_extensions         4.3.0            py38hecd8cb5_0  
urllib3                   1.26.12          py38hecd8cb5_0  
virtualenv                20.17.0                  pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py38_1  
websocket-client          0.58.0           py38hecd8cb5_4  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py38hecd8cb5_0  
wurlitzer                 3.0.2            py38hecd8cb5_0  
xz                        5.2.6                hca72f7f_0  
yaml                      0.2.5                haf1e3a3_0  
zeromq                    4.3.4                h23ab428_0  
zfp                       0.5.5                he9d5cce_6  
zipp                      3.8.0            py38hecd8cb5_0  
zlib                      1.2.13               hfd90126_4    conda-forge
zstd                      1.5.2                hcb37349_0  
```

**Comment by yves-surrel** [comment]
The problem seems to come from the `fut` argument of the `async_wait_for` call in `kivy.clock.ClockBaseFreeInterruptOnly.async_idle`:
```
                if do_free:
                    event.clear()
                    self._process_free_events(current)
                else:
                    slept = True
                    await self._async_wait_for(
                            event.wait(), sleeptime - undershoot)
                    #       ^^^^^^^^^^^  <-- 'fut' parameter         
```
During the process of asyncio.wait_for, `fut.done()` returns `False`, raising the `TimeoutError` exception:
```
async def wait_for(fut, timeout, *, loop=None):
    """Wait for the single Future or coroutine to complete, with timeout.

    Coroutine will be wrapped in Task.

    Returns result of the Future or coroutine.  When a timeout occurs,
    it cancels the task and raises TimeoutError.  To avoid the task
    cancellation, wrap it in shield().

    If the wait is cancelled, the task is also cancelled.

    This function is a coroutine.
    """
....
    try:
        # wait until the future completes or the timeout
        try:
            await waiter
        except exceptions.CancelledError:
            if fut.done():
                return fut.result()
            else:
                fut.remove_done_callback(cb)
                # We must ensure that the task is not running
                # after wait_for() returns.
                # See https://bugs.python.org/issue32751
                await _cancel_and_wait(fut, loop=loop)
                raise

        if fut.done():   # <-------------------------------------------- False
            return fut.result()
        else:
            fut.remove_done_callback(cb)
            # We must ensure that the task is not running
            # after wait_for() returns.
            # See https://bugs.python.org/issue32751
            await _cancel_and_wait(fut, loop=loop)
            raise exceptions.TimeoutError() # <--------------------------Exception raised
    finally:
        timeout_handle.cancel()

```

**Comment by yves-surrel** [comment]
As I really need this, I made a quick'n dirty change in `async_wait_for` call in `kivy.clock.ClockBaseFreeInterruptOnly.async_idle`:
```
                if do_free:
                    event.clear()
                    self._process_free_events(current)
                else:
                    slept = True
                    event.set()  #    <------------ Added (force internal value to True)
                    await self._async_wait_for(
                            event.wait(), sleeptime - undershoot)
```
It works as expected, now. I am not expert enough to imagine all the side effects....

**Comment by ElliotGarbus** [comment]
I suspect you have some installation error.  I have run this demo correctly on Windows11 using kivy 2.2.1, python 311.4; and MacOS using Kivy 2.2.1 and python 3.9.13

As an aside, I strongly recommend Trio for async programming.

**Comment by yves-surrel** [comment]
Macbook Pro, MacOS 12.6.5

Fresh install: `mamba create -n test_kivy "python=3.9" kivy`, and the bug shows up. It does not on a Mac Mini M1...

**Comment by ElliotGarbus** [comment]
I suggest following the install instructions here: https://kivy.org/doc/stable/gettingstarted/installation.html
FWIW I do a pip install on MacOS.  Note that kivy has a selector that manages the dependencies: 

From the docs:
python -m pip install "kivy[base]" kivy_examples
This also installs the minimum dependencies of Kivy. To additionally install Kivy with audio/video support, install either kivy[base,media] or kivy[full]. See Kivy’s dependencies for the list of selectors.

**Comment by yves-surrel** [comment]
Same with pip install. Should be sthg tweaked elsewhere (some previous installation of some library using brew or anything, although I removed all that I installed with brew). I will stay with my fix, that seems to work OK.
