### ISSUE TITLE
An import error in a KV file raises AttributeError in Kivy instead of ParserException

### ISSUE THREAD

**Issue by Poikilos** [kivy/kivy#8091]
**Software Versions**
* Python: 3.10.6
* OS: Linux Mint 21
* Kivy: 2.1.0
* Kivy installation method: pip wheel

**Describe the bug**
An import error in a KV file raises AttributeError, which produces a long Kivy traceback.

**Expected behavior**
A ParserException would be more clear.

**To Reproduce**
The point of this is to raise an exception, so the code intentionally doesn't run, but does reproduce the issue.
It should reproduce the error in the latest master because the code there is the same as in my version:
https://github.com/kivy/kivy/blob/5744bc564dd99c6326438e628acd5f3e3e146ff8/kivy/lang/parser.py#L559

**Code and Logs and screenshots**
The only logs you need to know are the last line(s) shown in the screenshots.

Before fixing:
```
/home/owner/.virtualenvs/kivy/bin/python "toggle_nav_drawer.py" (in directory: /home/owner/metaprojects/examples/kivymd)
[INFO   ] [Logger      ] Record log in /home/owner/.kivy/logs/kivy_23-01-01_83.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
[INFO   ] [Python      ] Interpreter at "/home/owner/.virtualenvs/kivy/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 22.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) HD Graphics 4000 (IVB GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2022-12-08 (installed at "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "/home/owner/metaprojects/examples/kivymd/toggle_nav_drawer.py", line 60, in <module>
     Builder.load_file("toggle_nav_drawer.kv")
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/builder.py", line 305, in load_file
     return self.load_string(data, **kwargs)
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/parser.py", line 483, in __init__
     self.parse(content)
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/parser.py", line 590, in parse
     self.execute_directives()
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/parser.py", line 559, in execute_directives
     mod = getattr(mod, part)
 AttributeError: module 'kivymd.uix.navigationdrawer' has no attribute 'NavigationLayout'. Did you mean: 'MDNavigationLayout'?
Compilation failed.

```

After fixing:
```
/home/owner/.virtualenvs/kivy/bin/python "toggle_nav_drawer.py" (in directory: /home/owner/metaprojects/examples/kivymd)
[INFO   ] [Logger      ] Record log in /home/owner/.kivy/logs/kivy_23-01-01_82.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
[INFO   ] [Python      ] Interpreter at "/home/owner/.virtualenvs/kivy/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 22.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) HD Graphics 4000 (IVB GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2022-12-08 (installed at "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "/home/owner/metaprojects/examples/kivymd/toggle_nav_drawer.py", line 60, in <module>
     Builder.load_file("toggle_nav_drawer.kv")
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/builder.py", line 305, in load_file
     return self.load_string(data, **kwargs)
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/parser.py", line 490, in __init__
     self.parse(content)
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/parser.py", line 604, in parse
     self.execute_directives()
   File "/home/owner/.virtualenvs/kivy/lib/python3.10/site-packages/kivy/lang/parser.py", line 567, in execute_directives
     raise ParserException(
 kivy.lang.parser.ParserException: Parser: File "/home/owner/metaprojects/examples/kivymd/toggle_nav_drawer.kv", line 3:
 ...
       1:#:kivy 1.11.0
       2:#:import MDNavigationDrawer kivymd.uix.navigationdrawer.MDNavigationDrawer
 >>    3:#:import NavigationLayout kivymd.uix.navigationdrawer.NavigationLayout
       4:#:import NavigationDrawerDivider kivymd.uix.navigationdrawer.NavigationDrawerDivider
       5:#:import NavigationDrawerToolbar kivymd.uix.navigationdrawer.NavigationDrawerToolbar
 ...
 Module kivymd.uix.navigationdrawer does not contain NavigationLayout
 File "/home/owner/metaprojects/examples/kivymd/toggle_nav_drawer.kv", line 3
Compilation failed.

```

**Additional context**
The fix demonstrated above in "after" will be in a PR.

**Comment by Julian-O** [comment]
@Poikilos Do you plan to make a PR for this?

**Comment by Poikilos** [comment]
@Julian-O I assumed someone with more knowledge of the code could do it better. I could probably, with some time.

**Comment by Julian-O** [comment]
@Poikilos I see. I thought you had a PR on your own branch ready to go.

I am looking at the 10 months that have elapsed without any interest from anyone with "more knowledge of the code", and extrapolating that it may be a long time before anyone else gets to this.

**Comment by Poikilos** [comment]
> @Poikilos I see. I thought you had a PR on your own branch ready to go.
> 
> I am looking at the 10 months that have elapsed without any interest from anyone with "more knowledge of the code", and extrapolating that it may be a long time before anyone else gets to this.

Ok I'll double check. Now that I reread my post, I recall I may have made a change on a local install and could potentially do a diff and put it in git.
