### ISSUE TITLE
toolchain build kivy fails on X86_64

### ISSUE THREAD

**Issue by surak** [kivy/kivy#8095]
**Software Versions**
* Python:3.9.10
* OS:13.1
* Kivy:2.1.0
* Kivy installation method:toolchain build kivy  

**Describe the bug**
Undefined symbols for architecture x86_64:

```
[DEBUG   ] clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -lsqlite3 -lffi   -Wl,-stack_size,1000000  -framework CoreFoundation -o Programs/_testembed Programs/_testembed.o libpython3.9.a -ldl   -framework CoreFoundation    
[DEBUG   ] ld: warning: ignoring file libpython3.9.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
[DEBUG   ] ld: warning: ignoring file libpython3.9.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
[DEBUG   ] Undefined symbols for architecture x86_64:
[DEBUG   ]   "_Py_BytesMain", referenced from:
[DEBUG   ]       _main in python.o
[DEBUG   ] ld: symbol(s) not found for architecture x86_64
[DEBUG   ] Undefined symbols for architecture x86_64:
[DEBUG   ]   "_PyArg_ParseTuple", referenced from:
[DEBUG   ]       __audit_hook in _testembed.o
[DEBUG   ]   "_PyConfig_Clear", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_init_python_env in _testembed.o
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_init_dev_mode in _testembed.o
[DEBUG   ]       _test_init_isolated_flag in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_PyConfig_InitIsolatedConfig", referenced from:
[DEBUG   ]       _test_preinit_dont_parse_argv in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]   "_PyConfig_InitPythonConfig", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]       _test_init_python_env in _testembed.o
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_init_dev_mode in _testembed.o
[DEBUG   ]       _test_init_isolated_flag in _testembed.o
[DEBUG   ]       _test_preinit_parse_argv in _testembed.o
[DEBUG   ]       _test_init_read_set in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_PyConfig_Read", referenced from:
[DEBUG   ]       _test_init_read_set in _testembed.o
[DEBUG   ]       _test_init_warnoptions in _testembed.o
[DEBUG   ]       _test_get_argc_argv in _testembed.o
[DEBUG   ]   "_PyConfig_SetArgv", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_preinit_parse_argv in _testembed.o
[DEBUG   ]       _test_preinit_dont_parse_argv in _testembed.o
[DEBUG   ]       _test_init_run_main in _testembed.o
[DEBUG   ]       _test_init_main in _testembed.o
[DEBUG   ]       _test_init_sys_add in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_PyConfig_SetBytesString", referenced from:
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_init_read_set in _testembed.o
[DEBUG   ]   "_PyConfig_SetString", referenced from:
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_init_python_env in _testembed.o
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_init_dev_mode in _testembed.o
[DEBUG   ]       _test_init_isolated_flag in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       _test_preinit_isolated2 in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_PyConfig_SetWideStringList", referenced from:
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]   "_PyErr_Clear", referenced from:
[DEBUG   ]       _test_audit in _testembed.o
[DEBUG   ]   "_PyErr_Format", referenced from:
[DEBUG   ]       __audit_hook_run in _testembed.o
[DEBUG   ]   "_PyErr_Occurred", referenced from:
[DEBUG   ]       _test_audit in _testembed.o
[DEBUG   ]   "_PyErr_Print", referenced from:
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]       _test_audit in _testembed.o
[DEBUG   ]   "_PyErr_SetString", referenced from:
[DEBUG   ]       __audit_hook in _testembed.o
[DEBUG   ]   "_PyEval_ReleaseThread", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]   "_PyEval_RestoreThread", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ]   "_PyEval_SaveThread", referenced from:
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ]   "_PyExc_RuntimeError", referenced from:
[DEBUG   ]       __audit_hook in _testembed.o
[DEBUG   ]       __audit_hook_run in _testembed.o
[DEBUG   ]   "_PyFile_OpenCode", referenced from:
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]   "_PyFile_SetOpenCodeHook", referenced from:
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]   "_PyGILState_Check", referenced from:
[DEBUG   ]       _bpo20891_thread in _testembed.o
[DEBUG   ]   "_PyGILState_Ensure", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _bpo20891_thread in _testembed.o
[DEBUG   ]   "_PyGILState_Release", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _bpo20891_thread in _testembed.o
[DEBUG   ]   "_PyImport_AppendInittab", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]   "_PyImport_ImportModule", referenced from:
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]       __open_code_hook in _testembed.o
[DEBUG   ]   "_PyInterpreterState_GetID", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]   "_PyLong_AsVoidPtr", referenced from:
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]   "_PyLong_FromVoidPtr", referenced from:
[DEBUG   ]       __open_code_hook in _testembed.o
[DEBUG   ]   "_PyMem_RawFree", referenced from:
[DEBUG   ]       _test_pre_initialization_api in _testembed.o
[DEBUG   ]       _test_init_setpath in _testembed.o
[DEBUG   ]       _test_init_setpath_config in _testembed.o
[DEBUG   ] clang      _test_init_setpythonhome in _testembed.o
[DEBUG   ] : error: linker command failed with exit code 1 (use -v to see invocation)
[DEBUG   ]   "_PyModule_Create2", referenced from:
[DEBUG   ]       _PyInit_embedded_ext in _testembed.o
[DEBUG   ]   "_PyObject_CallMethod", referenced from:
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]       __open_code_hook in _testembed.o
[DEBUG   ]   "_PyPreConfig_InitIsolatedConfig", referenced from:
[DEBUG   ]       _test_preinit_dont_parse_argv in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]   "_PyPreConfig_InitPythonConfig", referenced from:
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_init_setpath_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_PyRun_SimpleStringFlags", referenced from:
[DEBUG   ]       _test_forced_io_encoding in _testembed.o
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _test_pre_initialization_api in _testembed.o
[DEBUG   ]       _test_pre_initialization_sys_options in _testembed.o
[DEBUG   ]       _test_init_initialize_config in _testembed.o
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_PyStatus_Exception", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_init_python_env in _testembed.o
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_init_dev_mode in _testembed.o
[DEBUG   ]       _test_init_isolated_flag in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_PySys_AddAuditHook", referenced from:
[DEBUG   ]       _test_audit in _testembed.o
[DEBUG   ]       _test_audit_subinterpreter in _testembed.o
[DEBUG   ]       _test_audit_run_command in _testembed.o
[DEBUG   ]       _test_audit_run_file in _testembed.o
[DEBUG   ]       _test_audit_run_interactivehook in _testembed.o
[DEBUG   ]       _test_audit_run_startup in _testembed.o
[DEBUG   ]       _test_audit_run_stdin in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_PySys_AddWarnOption", referenced from:
[DEBUG   ]       _test_pre_initialization_sys_options in _testembed.o
[DEBUG   ]       _test_init_sys_add in _testembed.o
[DEBUG   ]       _test_init_warnoptions in _testembed.o
[DEBUG   ]   "_PySys_AddXOption", referenced from:
[DEBUG   ]       _test_pre_initialization_sys_options in _testembed.o
[DEBUG   ]       _test_init_sys_add in _testembed.o
[DEBUG   ]   "_PySys_Audit", referenced from:
[DEBUG   ]       _test_audit in _testembed.o
[DEBUG   ]   "_PySys_ResetWarnOptions", referenced from:
[DEBUG   ]       _test_pre_initialization_sys_options in _testembed.o
[DEBUG   ]   "_PyThreadState_Get", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]   "_PyThreadState_Swap", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]   "_PyThread_acquire_lock", referenced from:
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ]   "_PyThread_allocate_lock", referenced from:
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ]   "_PyThread_exit_thread", referenced from:
[DEBUG   ] make:       _bpo20891_thread in _testembed.o
[DEBUG   ] *** [python.exe] Error 1
[DEBUG   ]   "_PyThread_free_lock", referenced from:
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ] make: *** Waiting for unfinished jobs....
[DEBUG   ]   "_PyThread_release_lock", referenced from:
[DEBUG   ]       _bpo20891_thread in _testembed.o
[DEBUG   ]   "_PyThread_start_new_thread", referenced from:
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ]   "_PyTuple_Type", referenced from:
[DEBUG   ]       __audit_hook in _testembed.o
[DEBUG   ]   "_PyUnicode_AsUTF8", referenced from:
[DEBUG   ]       __audit_hook_run in _testembed.o
[DEBUG   ]   "_PyUnicode_CompareWithASCIIString", referenced from:
[DEBUG   ]       __open_code_hook in _testembed.o
[DEBUG   ]   "_PyUnicode_FromFormat", referenced from:
[DEBUG   ]       __audit_hook_run in _testembed.o
[DEBUG   ]   "_PyWideStringList_Append", referenced from:
[DEBUG   ]       _test_init_read_set in _testembed.o
[DEBUG   ]       _test_init_sys_add in _testembed.o
[DEBUG   ]       _test_init_warnoptions in _testembed.o
[DEBUG   ]   "_PyWideStringList_Insert", referenced from:
[DEBUG   ]       _test_init_read_set in _testembed.o
[DEBUG   ]       _test_init_warnoptions in _testembed.o
[DEBUG   ]   "_Py_BytesWarningFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_DebugFlag", referenced from:
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_DecodeLocale", referenced from:
[DEBUG   ]       _test_pre_initialization_api in _testembed.o
[DEBUG   ]       _test_init_setpath in _testembed.o
[DEBUG   ]       _test_init_setpath_config in _testembed.o
[DEBUG   ]       _test_init_setpythonhome in _testembed.o
[DEBUG   ]   "_Py_DontWriteBytecodeFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_EndInterpreter", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]   "_Py_ExitStatusException", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_init_python_env in _testembed.o
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_init_dev_mode in _testembed.o
[DEBUG   ]       _test_init_isolated_flag in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_Finalize", referenced from:
[DEBUG   ]       _test_forced_io_encoding in _testembed.o
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _test_pre_initialization_api in _testembed.o
[DEBUG   ]       _test_pre_initialization_sys_options in _testembed.o
[DEBUG   ]       _test_initialize_twice in _testembed.o
[DEBUG   ]       _test_initialize_pymain in _testembed.o
[DEBUG   ]       _test_init_initialize_config in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_FrozenFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_GetArgcArgv", referenced from:
[DEBUG   ]       _test_get_argc_argv in _testembed.o
[DEBUG   ]   "_Py_IgnoreEnvironmentFlag", referenced from:
[DEBUG   ]       _test_init_compat_env in _testembed.o
[DEBUG   ]       _test_init_env_dev_mode in _testembed.o
[DEBUG   ]       _test_init_env_dev_mode_alloc in _testembed.o
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]       _test_audit in _testembed.o
[DEBUG   ]       _test_audit_subinterpreter in _testembed.o
[DEBUG   ]       _test_audit_run_command in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_Initialize", referenced from:
[DEBUG   ]       _test_forced_io_encoding in _testembed.o
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _test_pre_initialization_api in _testembed.o
[DEBUG   ]       _test_pre_initialization_sys_options in _testembed.o
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ]       _test_initialize_twice in _testembed.o
[DEBUG   ]       _test_initialize_pymain in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_InitializeFromConfig", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_init_python_env in _testembed.o
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_init_dev_mode in _testembed.o
[DEBUG   ]       _test_init_isolated_flag in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_InspectFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_InteractiveFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_IsolatedFlag", referenced from:
[DEBUG   ]       _test_init_isolated_flag in _testembed.o
[DEBUG   ]       _test_preinit_isolated2 in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_Main", referenced from:
[DEBUG   ]       _test_initialize_pymain in _testembed.o
[DEBUG   ]       _test_audit_run_command in _testembed.o
[DEBUG   ]       _test_audit_run_file in _testembed.o
[DEBUG   ]   "_Py_NewInterpreter", referenced from:
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _test_audit_subinterpreter in _testembed.o
[DEBUG   ]   "_Py_NoSiteFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_NoUserSiteDirectory", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_OptimizeFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_PreInitialize", referenced from:
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_init_dont_configure_locale in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       _test_preinit_isolated2 in _testembed.o
[DEBUG   ]       _test_init_setpath_config in _testembed.o
[DEBUG   ]       _check_init_compat_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_PreInitializeFromArgs", referenced from:
[DEBUG   ]       _test_preinit_dont_parse_argv in _testembed.o
[DEBUG   ]   "_Py_QuietFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_RunMain", referenced from:
[DEBUG   ]       _test_repeated_init_and_inittab in _testembed.o
[DEBUG   ]       _test_init_run_main in _testembed.o
[DEBUG   ]       _test_init_main in _testembed.o
[DEBUG   ]       _test_run_main in _testembed.o
[DEBUG   ]       _test_audit_run_interactivehook in _testembed.o
[DEBUG   ]       _test_audit_run_startup in _testembed.o
[DEBUG   ]       _test_audit_run_stdin in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_SetPath", referenced from:
[DEBUG   ]       _test_init_setpath in _testembed.o
[DEBUG   ]       _test_init_setpath_config in _testembed.o
[DEBUG   ]   "_Py_SetProgramName", referenced from:
[DEBUG   ]       _test_forced_io_encoding in _testembed.o
[DEBUG   ]       _test_repeated_init_and_subinterpreters in _testembed.o
[DEBUG   ]       _test_pre_initialization_api in _testembed.o
[DEBUG   ]       _test_pre_initialization_sys_options in _testembed.o
[DEBUG   ]       _test_bpo20891 in _testembed.o
[DEBUG   ]       _test_initialize_twice in _testembed.o
[DEBUG   ]       _test_initialize_pymain in _testembed.o
[DEBUG   ]       ...
[DEBUG   ]   "_Py_SetPythonHome", referenced from:
[DEBUG   ]       _test_init_setpythonhome in _testembed.o
[DEBUG   ]   "_Py_SetStandardStreamEncoding", referenced from:
[DEBUG   ]       _test_forced_io_encoding in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]   "_Py_UTF8Mode", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]   "_Py_UnbufferedStdioFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "_Py_VerboseFlag", referenced from:
[DEBUG   ]       _test_init_global_config in _testembed.o
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]       _check_init_python_config in _testembed.o
[DEBUG   ]   "__PyConfig_InitCompatConfig", referenced from:
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       _test_preinit_isolated2 in _testembed.o
[DEBUG   ]       _check_init_compat_config in _testembed.o
[DEBUG   ]   "__PyPreConfig_InitCompatConfig", referenced from:
[DEBUG   ]       _test_init_from_config in _testembed.o
[DEBUG   ]       _test_preinit_isolated1 in _testembed.o
[DEBUG   ]       _test_preinit_isolated2 in _testembed.o
[DEBUG   ]       _check_init_compat_config in _testembed.o
[DEBUG   ]   "__PyRuntime", referenced from:
[DEBUG   ]       _check_preinit_isolated_config in _testembed.o
[DEBUG   ]   "__Py_Dealloc", referenced from:
[DEBUG   ]       _test_open_code_hook in _testembed.o
[DEBUG   ]       __audit_hook_run in _testembed.o
[DEBUG   ]   "__Py_InitializeMain", referenced from:
[DEBUG   ]       _test_init_main in _testembed.o
[DEBUG   ] ld: symbol(s) not found for architecture x86_64
[DEBUG   ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[DEBUG   ] make: *** [Programs/_testembed] Error 1
Exception in thread background thread for pid 75040:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -C /Users/surak/Devel/kivy_venv/build/hostpython3/x86_64/Python-3.9.9/native-build -j12

  STDOUT:
clang -Qunused-arguments -fcolor-diagnostics -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.12 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.12  -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I/Users/surak/Devel/kivy_venv/build/hostpython3/x86_64/Python-3.9.9/Include/internal -IObjects -IInclude -IPython -I. -I/Users/surak/Devel/kivy_venv/build/hostpython3/x86_64/Py... (160749 more, please see e.stdout)

  STDERR:

Traceback (most recent call last):
  File "/Users/surak/Devel/kivy_venv/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1555, in main
    ToolchainCL()
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1299, in __init__
    getattr(self, args.command)()
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1368, in build
    build_recipes(args.recipe, ctx)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1142, in build_recipes
    recipe.execute()
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 704, in execute
    self.build_all()
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 74, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 803, in build_all
    self.build(arch)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 74, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 790, in build
    self.build_arch(arch)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/recipes/hostpython3/__init__.py", line 74, in build_arch
    shprint(sh.make, "-C", build_subdir, self.ctx.concurrent_make,
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 56, in shprint
    for line in cmd:
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/sh.py", line 915, in next
    self.wait()
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/surak/Devel/kivy_venv/lib/python3.9/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -C /Users/surak/Devel/kivy_venv/build/hostpython3/x86_64/Python-3.9.9/native-build -j12

  STDOUT:
clang -Qunused-arguments -fcolor-diagnostics -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.12 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.12  -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I/Users/surak/Devel/kivy_venv/build/hostpython3/x86_64/Python-3.9.9/Include/internal -IObjects -IInclude -IPython -I. -I/Users/surak/Devel/kivy_venv/build/hostpython3/x86_64/Py... (160749 more, please see e.stdout)

  STDERR:
```

**Expected behavior**
To finish successfully

**To Reproduce**
```toolchain build kyvi```

Looks very similar to this one: https://issuehint.com/issue/kivy/kivy-ios/666, but on intel platforms.

**Comment by misl6** [comment]
Hi @surak !

That looks like related to `kivy/kivy-ios` instead, and looks like a support issue, can you please reach us on Discord instead?
