### ISSUE TITLE
invalid frustrum

### ISSUE THREAD

**Issue by LazzaAU** [kivy/kivy#8100]
**Software Versions** kivy v2.2.0.dev0 and kivyMD 1.2.0dev0 (both due to the recent shader fix )
* Python: 3.10
* OS: Android
* Kivy:
* Kivy installation method: pip

**Describe the bug**
Due to using dev versions maybe this is expected *shrug*, however for the purpose of documenting a potential issue i get the below invalid frustrum error ever since applying the fix for boxshadow ( https://github.com/kivy/kivy/pull/8056 ) . Not saying that's the issue, but that's when i started noticing it in my logs. So far i cant say i see any visual side effects to the error other than the error in logcat but im not a whiz kid so maybe i just havent noticed the issue yet 

just thought it was worth mentioning in case some one has a brain wave to the issue :)

**Expected behavior**
No error in the log

**To Reproduce**
Maybe someone who has applied https://github.com/kivymd/KivyMD#how-to-fix-a-shader-bug-on-an-android-device can confirm ?

**Code and Logs and screenshots**
```python
01-07 20:42:21.269 23348 23724 I python  :  Exception: FBO Initialization failed: Incomplete attachment (36054)
01-07 20:42:21.269 23348 23724 I python  :  Exception ignored in: 'kivy.graphics.fbo.Fbo.raise_exception'
01-07 20:42:21.269 23348 23724 I python  :  Traceback (most recent call last):
01-07 20:42:21.269 23348 23724 I python  :    File "/home/larry/Documents/GitHubProjectFiles/Worker/.buildozer/android/platform/build-arm64-v8a/build/python-installs/worker/arm64-v8a/kivy/uix/screenmanager.py", line 477, in make_screen_fbo
01-07 20:42:21.270 23348 23724 I python  :  Exception: FBO Initialization failed: Incomplete attachment (36054)
01-07 20:42:21.270 23348 23724 I python  :  Traceback (most recent call last):
01-07 20:42:21.270 23348 23724 I python  :    File "kivy/graphics/transformation.pyx", line 301, in kivy.graphics.transformation.Matrix.view_clip
01-07 20:42:21.270 23348 23724 I python  :  ValueError: invalid frustrum
01-07 20:42:21.270 23348 23724 I python  :  Exception ignored in: 'kivy.graphics.fbo.Fbo.create_fbo'
01-07 20:42:21.270 23348 23724 I python  :  Traceback (most recent call last):
01-07 20:42:21.270 23348 23724 I python  :    File "kivy/graphics/transformation.pyx", line 301, in kivy.graphics.transformation.Matrix.view_clip
01-07 20:42:21.271 23348 23724 I python  :  ValueError: invalid frustrum
01-07 20:42:21.271 23348 23724 I python  :  Exception: FBO Initialization failed: Incomplete attachment (36054)
01-07 20:42:21.272 23348 23724 I python  :  Exception ignored in: 'kivy.graphics.fbo.Fbo.raise_exception'
01-07 20:42:21.272 23348 23724 I python  :  Traceback (most recent call last):
01-07 20:42:21.272 23348 23724 I python  :    File "/home/larry/Documents/GitHubProjectFiles/Worker/.buildozer/android/platform/build-arm64-v8a/build/python-installs/worker/arm64-v8a/kivy/uix/screenmanager.py", line 477, in make_screen_fbo
01-07 20:42:21.272 23348 23724 I python  :  Exception: FBO Initialization failed: Incomplete attachment (36054)
01-07 20:42:21.272 23348 23724 I python  :  Traceback (most recent call last):
01-07 20:42:21.272 23348 23724 I python  :    File "kivy/graphics/transformation.pyx", line 301, in kivy.graphics.transformation.Matrix.view_clip
01-07 20:42:21.272 23348 23724 I python  :  ValueError: invalid frustrum
01-07 20:42:21.272 23348 23724 I python  :  Exception ignored in: 'kivy.graphics.fbo.Fbo.create_fbo'
01-07 20:42:21.273 23348 23724 I python  :  Traceback (most recent call last):
01-07 20:42:21.273 23348 23724 I python  :    File "kivy/graphics/transformation.pyx", line 301, in kivy.graphics.transformation.Matrix.view_clip
01-07 20:42:21.273 23348 23724 I python  :  ValueError: invalid frustrum
/
```

**Additional context**

**Comment by misl6** [comment]
The issue you linked is quite old and looks completely unrelated. Maybe you linked the wrong one?

**Comment by LazzaAU** [comment]
yes i did sorry, was meant to be link to the PR related to boxshadow . Have edited that reference.

**Comment by misl6** [comment]
Looks the same as https://github.com/kivy/kivy/issues/6176 and is unrelated to #8056 .

Closing as duplicated, thank you for the report anyway!
