### ISSUE TITLE
Showcase example Python 3.8.10 exceptions

### ISSUE THREAD

**Issue by SlimeNPC** [kivy/kivy#8122]
**Software Versions**
* Python: 3.8.10
* OS: Windows 10
* Kivy: Code zip from Github (example)
* Kivy installation method: pip install kivy

**Describe the bug**
Exceptions seen using showcase example.

**Expected behavior**
N/A

**To Reproduce**
kivy-master\examples\demo\showcase>python main.py
click arrow > top right or select item from drop down
observe crash

**Code and Logs and screenshots**
```python
 Traceback (most recent call last):
   File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 240, in create_handler
     return eval(value, idmap), bound_list
   File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\data\style.kv", line 35, in <module>
     rgba: self.parent.background_color if self.parent else (1, 1, 1, 1)
 AttributeError: 'BubbleContent' object has no attribute 'background_color'
```

**Additional context**
N/A

**Comment by Shudh** [comment]
Yes facing the same issue

**Comment by GabiBonza** [comment]
Same here...
