### ISSUE TITLE
boxshadow error

### ISSUE THREAD

**Issue by Ahd999** [kivy/kivy#8246]
**Software Versions**
* Python:3.10
* OS:win11
* Kivy: Kivy-2.2.0rc1
* Kivy installation method: precompiled,prerelease wheels

**Describe the bug**
File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 925, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\boxshadow.pyx", line 443, in kivy.graphics.boxshadow.BoxShadow.spread_radius.__set__
   File "kivy\graphics\boxshadow.pyx", line 311, in kivy.graphics.boxshadow.BoxShadow._check_iter
 TypeError: 'spread_radius' accepts only list/tuple, got <class 'float'>
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "D:\agreement-maker\appdirectory\base app\main.py", line 241, in <module>
     AgreementMaker().run()
   File "D:\py310\lib\site-packages\kivy\app.py", line 955, in run
     self._run_prepare()
   File "D:\py310\lib\site-packages\kivy\app.py", line 925, in _run_prepare
     root = self.build()
   File "D:\agreement-maker\appdirectory\base app\main.py", line 233, in build
     return Builder.load_file("main.kv")
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 305, in load_file
     return self.load_string(data, **kwargs)
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 407, in load_string
     self._apply_rule(
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "D:\py310\lib\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 540, in apply
     self._apply_rule(
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 658, in _apply_rule
     child = cls(__no_builder=True)
   File "D:\py310\lib\site-packages\kivymd\uix\toolbar\toolbar.py", line 1348, in __init__
     self.action_button = MDFabBottomAppBarButton()
   File "D:\py310\lib\site-packages\kivymd\uix\button\button.py", line 1535, in __init__
     super().__init__(*args, **kwargs)
   File "D:\py310\lib\site-packages\kivymd\uix\button\button.py", line 955, in __init__
     super().__init__(*args, **kwargs)
   File "D:\py310\lib\site-packages\kivymd\uix\behaviors\declarative_behavior.py", line 311, in __init__
     super().__init__(**kwargs)
   File "D:\py310\lib\site-packages\kivymd\uix\tooltip\tooltip.py", line 195, in __init__
     super().__init__(**kwargs)
   File "D:\py310\lib\site-packages\kivymd\theming.py", line 1670, in __init__
     super().__init__(**kwargs)
   File "D:\py310\lib\site-packages\kivy\uix\behaviors\button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "D:\py310\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "D:\py310\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "D:\py310\lib\site-packages\kivymd\uix\button\button.py", line 1172, in __init__
     super().__init__(**kwargs)
   File "D:\py310\lib\site-packages\kivy\uix\widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "D:\py310\lib\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 540, in apply
     self._apply_rule(
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 595, in _apply_rule
     self._build_canvas(widget.canvas.before, widget,
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 928, in _build_canvas
     raise BuilderException(
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 11:
 ...
       9:            size: self.size
      10:            offset: root.shadow_offset
 >>   11:            spread_radius: -(root.shadow_softness)
      12:            blur_radius: root.elevation * 10
      13:            border_radius:
 ...
 TypeError: 'spread_radius' accepts only list/tuple, got <class 'float'>
   File "D:\py310\lib\site-packages\kivy\lang\builder.py", line 925, in _build_canvas
     setattr(instr, key, value)
   File "kivy\graphics\boxshadow.pyx", line 443, in kivy.graphics.boxshadow.BoxShadow.spread_radius.__set__
   File "kivy\graphics\boxshadow.pyx", line 311, in kivy.graphics.boxshadow.BoxShadow._check_iter

**Comment by Ahd999** [comment]
I'm sorry, this issue has been observed with kivymd, currently I'm closing this issue, if there is something Related to kivy in this context I'll reopen it
