### ISSUE TITLE
VideoPlayer duration property is alwys set to zero for `webm` videos

### ISSUE THREAD

**Issue by Noor-Kalibbala** [kivy/kivy#8248]
**Software Versions**
* Python: 3.9
* OS: linux mint
* Kivy: 2.2.orc1
* Kivy installation method:

The duration property of the videoplayer is alwys set to zero when the input video is webm format, thus causing ZeroDivisonErro when calcuting seek to set time.
``seek = self.position / self.duration
  d = self.duration * seek
  minutes = int(d / 60)
  seconds = int(d - minutes * 60)
  self.ids.button_box.ids.time.text = "%d:%02d" % (minutes, seconds)``

**Comment by misl6** [comment]
Hi @Noor-Kalibbala !
Can you please confirm the provider used to reproduce the video?
(Feel free to post the full log)

**Comment by Noor-Kalibbala** [comment]
@misl6 please kindly find the log below
``
[INFO   ] [Logger      ] Record log in /home/noor/.kivy/logs/kivy_23-05-19_0.txt
[INFO   ] [Kivy        ] v2.2.0rc1, git-22fd80d, 20230504
[INFO   ] [Kivy        ] Installed at "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.16 (main, Dec  7 2022, 01:12:08) 
[GCC 11.3.0]
[INFO   ] [Python      ] Interpreter at "/home/noor/PycharmProjects/pythonProject/venv3.9/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.5.0
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 22.2.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) HD Graphics 4600 (HSW GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoFFPy   ] Using ffpyplayer 4.5.0
[INFO   ] [Video       ] Provider: ffpyplayer(['video_ffmpeg'] ignored)
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-04-11 (installed at "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event5
[INFO   ] [MTD         ] Read event from </dev/input/event5>
[INFO   ] [Base        ] Start application main loop
[DEBUG  ] Importing BlpImagePlugin
[DEBUG  ] Importing BmpImagePlugin
[DEBUG  ] Importing BufrStubImagePlugin
[DEBUG  ] Importing CurImagePlugin
[DEBUG  ] Importing DcxImagePlugin
[DEBUG  ] Importing DdsImagePlugin
[DEBUG  ] Importing EpsImagePlugin
[DEBUG  ] Importing FitsImagePlugin
[DEBUG  ] Importing FitsStubImagePlugin
[DEBUG  ] Importing FliImagePlugin
[DEBUG  ] Importing FpxImagePlugin
[DEBUG  ] [Image       ] failed to import FpxImagePlugin: No module named 'olefile'
[DEBUG  ] Importing FtexImagePlugin
[DEBUG  ] Importing GbrImagePlugin
[DEBUG  ] Importing GifImagePlugin
[DEBUG  ] Importing GribStubImagePlugin
[DEBUG  ] Importing Hdf5StubImagePlugin
[DEBUG  ] Importing IcnsImagePlugin
[DEBUG  ] Importing IcoImagePlugin
[DEBUG  ] Importing ImImagePlugin
[DEBUG  ] Importing ImtImagePlugin
[DEBUG  ] Importing IptcImagePlugin
[DEBUG  ] Importing JpegImagePlugin
[DEBUG  ] Importing Jpeg2KImagePlugin
[DEBUG  ] Importing McIdasImagePlugin
[DEBUG  ] Importing MicImagePlugin
[DEBUG  ] [Image       ] failed to import MicImagePlugin: No module named 'olefile'
[DEBUG  ] Importing MpegImagePlugin
[DEBUG  ] Importing MpoImagePlugin
[DEBUG  ] Importing MspImagePlugin
[DEBUG  ] Importing PalmImagePlugin
[DEBUG  ] Importing PcdImagePlugin
[DEBUG  ] Importing PcxImagePlugin
[DEBUG  ] Importing PdfImagePlugin
[DEBUG  ] Importing PixarImagePlugin
[DEBUG  ] Importing PngImagePlugin
[DEBUG  ] Importing PpmImagePlugin
[DEBUG  ] Importing PsdImagePlugin
[DEBUG  ] Importing SgiImagePlugin
[DEBUG  ] Importing SpiderImagePlugin
[DEBUG  ] Importing SunImagePlugin
[DEBUG  ] Importing TgaImagePlugin
[DEBUG  ] Importing TiffImagePlugin
[DEBUG  ] Importing WebPImagePlugin
[DEBUG  ] Importing WmfImagePlugin
[DEBUG  ] Importing XbmImagePlugin
[DEBUG  ] Importing XpmImagePlugin
[DEBUG  ] Importing XVThumbImagePlugin
[ERROR  ] [Image       ] Error loading </home/noor/videos/Jay-Z & Kanye West - Nias In Paris (Explicit).webm>
[WARNING] Deprecated property "<BooleanProperty name=play>" of object "<kivy.uix.video.Video object at 0x7f92a101ed60>" was accessed, it will be removed in a future version
[WARNING] [MTD         ] Unable to open device "/dev/input/event5". Please ensure you have the appropriate permissions.
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/home/noor/PycharmProjects/pythonProject/mak_polls/CustomVideoPlayer/custom_video_player.py", line 340, in <module>
     TestVideoPlayer().run()
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/app.py", line 956, in run
     runTouchApp()
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/core/video/video_ffpyplayer.py", line 227, in _redraw
     self.dispatch('on_load')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/uix/video.py", line 266, in _on_load
     self._on_video_frame(largs)
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/uix/video.py", line 255, in _on_video_frame
     self.position = video.position
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "kivy/_event.pyx", line 748, in kivy._event.EventDispatcher.__proxy_setter
   File "kivy/properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1189, in kivy._event.EventObservers._dispatch
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/lang/builder.py", line 67, in call_fn
     setattr(element, key, e_value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 1667, in kivy.properties.AliasProperty.set
   File "kivy/properties.pyx", line 1672, in kivy.properties.AliasProperty._dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1189, in kivy._event.EventObservers._dispatch
   File "/home/noor/PycharmProjects/pythonProject/venv3.9/lib/python3.9/site-packages/kivy/lang/builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/home/noor/PycharmProjects/pythonProject/mak_polls/CustomVideoPlayer/custom_video_player.kv", line 29, in <module>
     on_value: root.parent.set_time()
   File "/home/noor/PycharmProjects/pythonProject/mak_polls/CustomVideoPlayer/custom_video_player.py", line 228, in set_time
     seek = self.position / self.duration
 ZeroDivisionError: float division by zero

Process finished with exit code 1
``

**Comment by RobertFlatt** [comment]
A little googling suggests one can't rely on the duration field in webm not to be empty (or zero).

https://superuser.com/questions/1585091/fixing-the-length-duration-of-a-webm-file-takes-too-much-time-by-ffmpeg
And for js users:
https://www.npmjs.com/package/fix-webm-duration

**Comment by Julian-O** [comment]
@RobertFlatt: Is it fair to say it is not Kivy's fault, and we can close the issue?

**Comment by Noor-Kalibbala** [comment]
@RobertFlatt Alright , let me close it

**Comment by baseplate-admin** [comment]
> @RobertFlatt: Is it fair to say it is not Kivy's fault, and we can close the issue?

Yes but it's an issue in [`ffplayer`](https://github.com/matham/ffpyplayer)

**Comment by Julian-O** [comment]
@baseplate-admin: Good to know. Has anyone raised an issue with them?

**Comment by RobertFlatt** [comment]
As I understand it Webm videos can have the duration property set to zero, or not present (see link above).

There is a workaround in ffmpeg, but it takes notable time to determine the duration (see link above). There is a related issue with webm videos incorrectly encoded as H264.

ffpyplayer do not implement this workaround for the first issue, and this is the assumed ffpyplayer issue. Is this correct?

As a workaround and to test the assumption, look at configuring ffmpeg from ffpyplayer. Personally I could not guide anybody through this.
