### ISSUE TITLE
_migrate_deprecated_padding_xy causing app to not load even when no padding is ever used within the app

### ISSUE THREAD

**Issue by JacekJagosz** [kivy/kivy#8280]
**Software Versions**
* Python: 3.10 and 3.9
* OS: Solus 4.3 and Raspberry Pi OS Bullseye
* Kivy: 2.2.0
* Kivy installation method: pip wheel for both devices

**Describe the bug**
My app that was created using Kivy 2.1.0 will crash at startup when trying to run with Kivy 2.2.0.
I am getting an error attached below, with function `_migrate_deprecated_padding_xy`, even though none of the lables in my code use padding.
The problematic line is https://github.com/DexerBR/kivy/blob/master/kivy/core/text/__init__.py#L331 introduced in pull #8162. If the replace `self.options['padding'] = list(self.options['padding'])` with `self.options['padding'] = [0, 0, 0, 0]` and the app launches and works just fine.
Could it be that if no padding is specified the default value of [0, 0, 0, 0] is not set early enough and this is why `self.options['padding']` is `NoneType`?

**Expected behavior**
If no padding is specified for a label, it should deafult to [0, 0, 0, 0] instead of crashing.

**To Reproduce**
I have no idea which part of the code causes this issue, as none of labels use padding.

**Code and Logs and screenshots**
```python
[INFO   ] [Kivy        ] v2.2.0
[INFO   ] [Kivy        ] Installed at "/home/jacek/.local/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.11 (main, Apr 27 2023, 08:33:53) [GCC 12.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[DEBUG  ] [Cache       ] register <kv.resourcefind> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[TRACE  ] [Lang        ] load file /home/jacek/.local/lib/python3.10/site-packages/kivy/data/style.kv, using utf8 encoding
[TRACE  ] [Parser      ] parsing 1341 lines
[TRACE  ] [Parser      ] got directive <kivy 1.0>
[TRACE  ] [Parser      ] got directive <import kivy kivy>
[TRACE  ] [Builder     ] build rule for <Label>
[TRACE  ] [Builder     ] build rule for <-Button,-ToggleButton>
[TRACE  ] [Builder     ] build rule for <BubbleContent>
[TRACE  ] [Builder     ] build rule for <BubbleButton>
[TRACE  ] [Builder     ] build rule for <Slider>
[TRACE  ] [Builder     ] build rule for <ProgressBar>
[TRACE  ] [Builder     ] build rule for <SplitterStrip>
[TRACE  ] [Builder     ] build rule for <Scatter>
[TRACE  ] [Builder     ] build rule for <RelativeLayout>
[TRACE  ] [Builder     ] build rule for <Image,AsyncImage>
[TRACE  ] [Builder     ] build rule for <EffectWidget>
[TRACE  ] [Builder     ] build rule for <TabbedPanelContent>
[TRACE  ] [Builder     ] build rule for <TabbedPanelStrip>
[TRACE  ] [Builder     ] build rule for <StripLayout>
[TRACE  ] [Builder     ] build rule for <TabbedPanelHeader>
[TRACE  ] [Builder     ] build rule for <Selector>
[TRACE  ] [Builder     ] build rule for <TextInput>
[TRACE  ] [Builder     ] build rule for <TextInputCutCopyPaste>
[TRACE  ] [Builder     ] build rule for <CodeInput>
[TRACE  ] [Builder     ] build rule for <TreeViewNode>
[TRACE  ] [Builder     ] build rule for <TreeViewLabel>
[TRACE  ] [Builder     ] build rule for <StencilView>
[TRACE  ] [Builder     ] build rule for <FileChooserListLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserListView>
[TRACE  ] [Builder     ] build template for [FileListEntry@FloatLayout+TreeViewNode]
[TRACE  ] [Builder     ] build rule for <FileChooserIconLayout>
[TRACE  ] [Builder     ] build rule for <FileChooserIconView>
[TRACE  ] [Builder     ] build template for [FileIconEntry@Widget]
[TRACE  ] [Builder     ] build rule for <FileChooserProgress>
[TRACE  ] [Builder     ] build rule for <Switch>
[TRACE  ] [Builder     ] build rule for <ModalView>
[TRACE  ] [Builder     ] build rule for <Popup>
[TRACE  ] [Builder     ] build rule for <SpinnerOption>
[TRACE  ] [Builder     ] build rule for <Spinner>
[TRACE  ] [Builder     ] build rule for <ActionBar>
[TRACE  ] [Builder     ] build rule for <ActionView>
[TRACE  ] [Builder     ] build rule for <ActionSeparator>
[TRACE  ] [Builder     ] build rule for <ActionButton,ActionToggleButton>
[TRACE  ] [Builder     ] build rule for <ActionLabel>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionCheck>
[TRACE  ] [Builder     ] build rule for <ActionPreviousImage@Image>
[TRACE  ] [Builder     ] build rule for <ActionPreviousButton@Button>
[TRACE  ] [Builder     ] build rule for <ActionPrevious>
[TRACE  ] [Builder     ] build rule for <ActionGroup>
[TRACE  ] [Builder     ] build rule for <ActionOverflow>
[TRACE  ] [Builder     ] build rule for <ActionDropDown>
[TRACE  ] [Builder     ] build template for [AccordionItemTitle@Label]
[TRACE  ] [Builder     ] build rule for <AccordionItem>
[TRACE  ] [Builder     ] build rule for <SettingSpacer>
[TRACE  ] [Builder     ] build rule for <SettingItem>
[TRACE  ] [Builder     ] build rule for <SettingBoolean>
[TRACE  ] [Builder     ] build rule for <SettingString>
[TRACE  ] [Builder     ] build rule for <SettingPath>
[TRACE  ] [Builder     ] build rule for <SettingColor>
[TRACE  ] [Builder     ] build rule for <SettingOptions>
[TRACE  ] [Builder     ] build rule for <SettingTitle>
[TRACE  ] [Builder     ] build rule for <SettingSidebarLabel>
[TRACE  ] [Builder     ] build rule for <SettingsPanel>
[TRACE  ] [Builder     ] build rule for <Settings>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSidebar>
[TRACE  ] [Builder     ] build rule for <InterfaceWithSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSpinner>
[TRACE  ] [Builder     ] build rule for <MenuSidebar>
[TRACE  ] [Builder     ] build rule for <ContentPanel>
[TRACE  ] [Builder     ] build rule for <InterfaceWithTabbedPanel>
[TRACE  ] [Builder     ] build rule for <ScrollView>
[TRACE  ] [Builder     ] build rule for <VideoPlayerPreview>
[TRACE  ] [Builder     ] build rule for <VideoPlayerAnnotation>
[TRACE  ] [Builder     ] build rule for <VideoPlayer>
[TRACE  ] [Builder     ] build rule for <CheckBox>
[TRACE  ] [Builder     ] build rule for <ScreenManager>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Input@TextInput>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Label@Label>
[TRACE  ] [Builder     ] build rule for <ColorPicker_Selector@BoxLayout>
[TRACE  ] [Builder     ] build rule for <ColorWheel>
[TRACE  ] [Builder     ] build rule for <ColorPicker>
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-01-30 (installed at "/home/jacek/.local/lib/python3.10/site-packages/kivymd/__init__.py")
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
[TRACE  ] [Image       ] Unable to use <pil> as loader!
[TRACE  ] 
Traceback (most recent call last):
  File "/home/jacek/.local/lib/python3.10/site-packages/kivy/core/__init__.py", line 131, in core_register_libs
    importlib.__import__(name='{2}.{0}.{1}'.format(category, lib, base),
  File "<frozen importlib._bootstrap>", line 1129, in __import__
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jacek/.local/lib/python3.10/site-packages/kivy/core/image/img_ffpyplayer.py", line 7, in <module>
    import ffpyplayer
ModuleNotFoundError: No module named 'ffpyplayer'
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] [Cache       ] register <kv.graphics.texture> with limit=None, timeout=None
[INFO   ] [Text        ] Provider: sdl2
[TRACE  ] [Parser      ] parsing 19 lines
[TRACE  ] [Builder     ] build rule for <-CoverBehavior>
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 23.0.3'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) UHD Graphics (JSL)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[TRACE  ] [Cache       ] Flushed category kv.texture from cache
[TRACE  ] [Cache       ] Flushed category kv.shader from cache
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImageSDL2   ] Load </home/jacek/.local/lib/python3.10/site-packages/kivy/data/glsl/default.png>
[TRACE  ] [Image       ] '/home/jacek/.local/lib/python3.10/site-packages/kivy/data/glsl/default.png', populate to textures (1)
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Version read: Loading parameters for move_8_pro
[TRACE  ] [Audio       ] Unable to use <sdl2> as loader!
[TRACE  ] 
Traceback (most recent call last):
  File "/home/jacek/.local/lib/python3.10/site-packages/kivy/core/__init__.py", line 131, in core_register_libs
    importlib.__import__(name='{2}.{0}.{1}'.format(category, lib, base),
  File "<frozen importlib._bootstrap>", line 1129, in __import__
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jacek/.local/lib/python3.10/site-packages/kivy/core/audio/audio_ffpyplayer.py", line 49, in <module>
    import ffpyplayer
ModuleNotFoundError: No module named 'ffpyplayer'
[DEBUG  ] [Audio       ] register SoundSDL2
[DEBUG  ] [Audio       ] register MusicSDL2
[INFO   ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
[WARNING] [Main        ] Cannot check user login, no possibility to hide cursor.
[INFO   ] [Main        ] my-project-data directory already exists
[INFO   ] [Main        ] user-programs directory already exists
[INFO   ] [Main        ] Loading .kv files
[DEBUG  ] [Main        ] Loading <main_screen.kv>
[INFO   ] [Main        ] Loaded all .kv files
[DEBUG  ] [App         ] Loading kv </home/jacek/aPraca/my-project-devel/mdproject.kv>
[DEBUG  ] [App         ] kv </home/jacek/aPraca/my-project-devel/mdproject.kv> not found
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0
[INFO   ] [Init        ] Entering screen
[DEBUG  ] [Resource    ] add </usr/share/fonts> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/conf.d> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/hack> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/thai> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/symbola> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/clear-sans> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/dejavu> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/noto-sans-ttf> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/truetype/droid> in path list
[DEBUG  ] [Resource    ] add </home/jacek/.local/lib/python3.10/site-packages/kivy/data/fonts> in path list
[DEBUG  ] [ImageSDL2   ] Load </home/jacek/aPraca/my-project-devel/assets/images/pwd_hidden.png>
[INFO   ] [GL          ] NPOT texture support is available
[DEBUG  ] [ImageSDL2   ] Load </home/jacek/aPraca/my-project-devel/assets/images/gradient.png>
 Traceback (most recent call last):
   File "/home/jacek/aPraca/my-project-devel/main.py", line 256, in <module>
     main()
   File "/home/jacek/aPraca/my-project-devel/main.py", line 252, in main
     MDProject().run()
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
   File "/home/jacek/aPraca/my-project-devel/main.py", line 246, in build
     self.sm = Builder.load_string(KV)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 407, in load_string
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/lang/builder.py", line 658, in _apply_rule
     child = cls(__no_builder=True)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivymd/uix/label/label.py", line 507, in __init__
     super().__init__(*args, **kwargs)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivymd/uix/label/label.py", line 332, in __init__
     super().__init__(**kwargs)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivymd/uix/behaviors/declarative_behavior.py", line 311, in __init__
     super().__init__(**kwargs)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivymd/theming.py", line 1668, in __init__
     super().__init__(**kwargs)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/uix/label.py", line 334, in __init__
     self._create_label()
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/uix/label.py", line 358, in _create_label
     self._label = CoreLabel(**dkw)
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/core/text/__init__.py", line 327, in __init__
     self._migrate_deprecated_padding_xy()
   File "/home/jacek/.local/lib/python3.10/site-packages/kivy/core/text/__init__.py", line 331, in _migrate_deprecated_padding_xy
     self.options['padding'] = list(self.options['padding'])
 TypeError: 'NoneType' object is not iterable

```

**Additional context**

**Comment by JacekJagosz** [comment]
@DexerBR The whole app is really long, and the logs don't suggest at all in what file the issue lies. Is there any way to make the logs even more verbose, so it could point to which file is the problem?
Then I could create a small piece of code replicating this issue.

**Comment by DexerBR** [comment]
> @DexerBR The whole app is really long, and the logs don't suggest at all in what file the issue lies. Is there any way to make the logs even more verbose, so it could point to which file is the problem? Then I could create a small piece of code replicating this issue.

You can try running in debug mode: `python main.py -d`

**Comment by JacekJagosz** [comment]
Unfortunately that gives me exactly the same error log, still no idea where it is happening.

**Comment by DexerBR** [comment]
> Unfortunately that gives me exactly the same error log, still no idea where it is happening.

Another idea would be to try changing `MDLabel` to `Label` and see if the problem persists. If it persists then I would recommend that you double check to ensure there is no code changing the `padding` property. If the first option works, then the problem would be with the `MDLabel` (**KivyMD**), not the **Kivy** side.

**Comment by JacekJagosz** [comment]
I got some more info on the issue. As I previously said, `_migrate_deprecated_padding_xy` would fail when `self.options['padding']` was none, the problematic line being: https://github.com/kivy/kivy/blob/master/kivy/core/text/__init__.py#L331
I would still suggest editing that part of the code from
```python3
self.options['padding'] = list(self.options['padding'])
```
to:
```
if self.options['padding'] is not None:
    self.options['padding'] = list(self.options['padding'])
else:
    self.options['padding'] = [0, 0, 0, 0]
```
as a failsafe, but it is up to you.

The problem was with some leftover .kv files from a tutorial that we haven't needed for a long time, but also we are getting the same issue when opening MDTimePicker like:
```python3
time_dialog = MDTimePicker(primary_color="black", accent_color="blue", text_toolbar_color="white")
time_dialog.bind()
time_dialog.open()
```
But when I try to create a minimal app with this bug I can't yet, but I will try further to create a minimal reproducible code.

**Comment by LeisAlAyoubi** [comment]
I got the same error in my Android App when I added padding to MDFloatLayout. 
I fixed the issue by removing the padding-keyword in my kv-file.
