### ISSUE TITLE
ValueError: Cosmetic error in output, no space between "ObjectProperty" and "or use errorhandler"

### ISSUE THREAD

**Issue by DavidPesticcio** [kivy/kivy#8346]
* Python: `3.10.12`
* OS: `Linux 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Kivy: `Kivy==2.2.1` (with `kivymd==1.1.1`)
* Kivy installation method: `virtualenv venv`, `source ./venv/bin/activate`, `python3.10 -m pip install kivymd`

**Describe the bug**
Incorrect output format for ValueError:
`ValueError: MDSlider.max has an invalid format (got <ObjectProperty name=>). Consider using ObjectPropertyor use errorhandler to convert to a number`

**Expected behavior**
Correct output format for ValueError:
`ValueError: MDSlider.max has an invalid format (got <ObjectProperty name=>). Consider using ObjectProperty
or use errorhandler to convert to a number`

**To Reproduce**
```bash
cd /tmp
```
```bash
virtualenv venv
```
```bash
source ./venv/bin/activate
```
```bash
pip install --upgrade pip
```
```bash
python3.10 -m pip install kivymd
```
```bash
cat <<EOF > ValueErrorFormat.py
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivymd.app import MDApp
from kivymd.uix.widget import MDWidget

KV = """
MyWidget:
    MDSlider:
        max: root.ValueErrorFormat
"""


class MyWidget(MDWidget):
    def __init__(self, **kwargs):
        super(MyWidget, self).__init__(**kwargs)
        self.ValueErrorFormat = NumericProperty(0.0)


class ValueErrorFormatApp(MDApp):
    def build(self):
        self.title = 'ValueError'

        return Builder.load_string(KV)


if __name__ == '__main__':
    app = ValueErrorFormatApp()
    app.run()

EOF
```
```bash
python3.10 ValueErrorFormat.py
```

**Code and Logs and screenshots**
See above.
(Template canNOT be found at https://git.io/vM1id. :-( )

```
$ cd /tmp

$ virtualenv venv
created virtual environment CPython3.10.12.final.0-64 in 504ms
  creator CPython3Posix(dest=/tmp/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/REDACTED/.local/share/virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

$ source ./venv/bin/activate

$ pip install --upgrade pip
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (23.1.2)
Collecting pip
  Using cached pip-23.2.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-23.2.1

$ python3.10 -m pip install kivymd
Collecting kivymd
  Using cached kivymd-1.1.1-py3-none-any.whl
Collecting kivy>=2.0.0 (from kivymd)
  Obtaining dependency information for kivy>=2.0.0 from https://files.pythonhosted.org/packages/b0/4d/9c65432d3fdea1edc81f51c01db6f804a6dac9d5f9fa3ff1f0a5c18e127f/Kivy-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading Kivy-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting pillow (from kivymd)
  Obtaining dependency information for pillow from https://files.pythonhosted.org/packages/3d/36/e78f09d510354977e10102dd811e928666021d9c451e05df962d56477772/Pillow-10.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata
  Downloading Pillow-10.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting Kivy-Garden>=0.1.4 (from kivy>=2.0.0->kivymd)
  Using cached Kivy_Garden-0.1.5-py3-none-any.whl (4.6 kB)
Collecting docutils (from kivy>=2.0.0->kivymd)
  Obtaining dependency information for docutils from https://files.pythonhosted.org/packages/26/87/f238c0670b94533ac0353a4e2a1a771a0cc73277b88bff23d3ae35a256c1/docutils-0.20.1-py3-none-any.whl.metadata
  Downloading docutils-0.20.1-py3-none-any.whl.metadata (2.8 kB)
Collecting pygments (from kivy>=2.0.0->kivymd)
  Obtaining dependency information for pygments from https://files.pythonhosted.org/packages/43/88/29adf0b44ba6ac85045e63734ae0997d3c58d8b1a91c914d240828d0d73d/Pygments-2.16.1-py3-none-any.whl.metadata
  Downloading Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)
Collecting requests (from Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd)
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/a4/65/057bf29660aae6ade0816457f8db4e749e5c0bfa2366eb5f67db9912fa4c/charset_normalizer-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading charset_normalizer-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Collecting idna<4,>=2.5 (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl.metadata
  Downloading urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests->Kivy-Garden>=0.1.4->kivy>=2.0.0->kivymd)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Using cached Kivy-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.9 MB)
Using cached Pillow-10.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Using cached Pygments-2.16.1-py3-none-any.whl (1.2 MB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (201 kB)
Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Installing collected packages: urllib3, pygments, pillow, idna, docutils, charset-normalizer, certifi, requests, Kivy-Garden, kivy, kivymd
Successfully installed Kivy-Garden-0.1.5 certifi-2023.7.22 charset-normalizer-3.2.0 docutils-0.20.1 idna-3.4 kivy-2.2.1 kivymd-1.1.1 pillow-10.0.0 pygments-2.16.1 requests-2.31.0 urllib3-2.0.4

$ cat <<EOF > ValueErrorFormat.py
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivymd.app import MDApp
from kivymd.uix.widget import MDWidget

KV = """
MyWidget:
    MDSlider:
        max: root.ValueErrorFormat
"""


class MyWidget(MDWidget):
    def __init__(self, **kwargs):
        super(MyWidget, self).__init__(**kwargs)
        self.ValueErrorFormat = NumericProperty(0.0)


class ValueErrorFormatApp(MDApp):
    def build(self):
        self.title = 'ValueError'

        return Builder.load_string(KV)


if __name__ == '__main__':
    app = ValueErrorFormatApp()
    app.run()

EOF

$ python3.10 ValueErrorFormat.py
[INFO   ] [Logger      ] Record log in /home/REDACTED/.kivy/logs/kivy_23-08-11_7.txt
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "/tmp/venv/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
[INFO   ] [Python      ] Interpreter at "/tmp/venv/bin/python3.10"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-05-28 (installed at "/tmp/venv/lib/python3.10/site-packages/kivymd/__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) HD Graphics 4600 (HSW GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/tmp/venv/lib/python3.10/site-packages/kivy/lang/builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 549, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 750, in kivy.properties.NumericProperty.convert
 ValueError: MDSlider.max has an invalid format (got <NumericProperty name=>). Consider using ObjectPropertyor use errorhandler to convert to a number
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/tmp/ValueErrorFormat.py", line 28, in <module>
     app.run()
   File "/tmp/venv/lib/python3.10/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/tmp/venv/lib/python3.10/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
   File "/tmp/ValueErrorFormat.py", line 23, in build
     return Builder.load_string(KV)
   File "/tmp/venv/lib/python3.10/site-packages/kivy/lang/builder.py", line 407, in load_string
     self._apply_rule(
   File "/tmp/venv/lib/python3.10/site-packages/kivy/lang/builder.py", line 709, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 4:
 ...
       2:MyWidget:
       3:    MDSlider:
 >>    4:        max: root.ValueErrorFormat
 ...
 ValueError: MDSlider.max has an invalid format (got <NumericProperty name=>). Consider using ObjectPropertyor use errorhandler to convert to a number
   File "/tmp/venv/lib/python3.10/site-packages/kivy/lang/builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 549, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 750, in kivy.properties.NumericProperty.convert
 
$
```

**Additional context**
Issue location: [https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L751](https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L751)

```
virtualenv --version
virtualenv 20.13.0+ds from /usr/lib/python3/dist-packages/virtualenv/__init__.py
```

**Comment by pythonic64** [comment]
Move `ValueErrorFormat` to class level:
```python
class MyWidget(MDWidget):
    ValueErrorFormat = NumericProperty(0.0)
    def __init__(self, **kwargs):
        super(MyWidget, self).__init__(**kwargs)
```

**Comment by DavidPesticcio** [comment]
> Move `ValueErrorFormat` to class level:
> 
> ```python
> class MyWidget(MDWidget):
>     ValueErrorFormat = NumericProperty(0.0)
>     def __init__(self, **kwargs):
>         super(MyWidget, self).__init__(**kwargs)
> ```

Whilst I appreciate your help, the issue of where to place `ValueErrorFormat = NumericProperty(0.0)` is not the issue, and this is also NOT a support request, although I guess it's also not a bug either. :smiley: 

The issue is the formatting of the ValueError output - which is confusing due to the absence of a space between the word `ObjectProperty` and `or use errorhandler...` of the resulting output.

The cause of the formatting issue can be clearly seen here: [https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L751](https://github.com/kivy/kivy/blob/master/kivy/properties.pyx#L751)

**Comment by pythonic64** [comment]
@DavidPesticcio I see that I misread your report. Can you make a pull request adding space in string at line 751?

**Comment by DavidPesticcio** [comment]
@pythonic64 https://github.com/kivy/kivy/pull/8349
