### ISSUE TITLE
ValueError: invalid frustrum on 2.2.1 but not on 2.2.0dev0 when resizing window to 0 height.

### ISSUE THREAD

**Issue by Code4SAFrankie** [kivy/kivy#8369]
**Software Versions**
* Python: Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
* OS: Windows 10
* Kivy: v2.2.1
* Kivy installation method: pip

**Describe the bug**
When scaling the window down to no height for the below program I get `ValueError: invalid frustrum`

**Expected behavior**
No error on zero window height

**To Reproduce**
**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.label import Label

Builder.load_string('''
<ScaleLabel@Label>:
    _scale: 1. if self.texture_size[0] < self.width else float(self.width) / self.texture_size[0] + 0.0000000001
    canvas.before:
        Color:
            rgba: 0, 1, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size
        PushMatrix
        Scale:
            origin: self.center
            x: self._scale or 1.
            y: self._scale or 1.
    canvas.after:
        PopMatrix
''')

class ScaleLabel(Label):
    pass

class TestApp(App):
    def build(self):
        return ScaleLabel(text="Hello world!", color=(0, 0, 1, 1), font_size=50)

if __name__ == "__main__":
   TestApp().run()
```

**Additional context**
```
[INFO   ] [Logger      ] Record log in C:\Users\User\.kivy\logs\kivy_23-09-11_15.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\WPy64-31140\python-3.11.4.amd64\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 537.13'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1080/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "d:\EBackup\Work\Python\kivy\fontscale\main.py", line 57, in <module>
     TestApp().run()
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\core\window\__init__.py", line 648, in _upd_kbd_height
     self._keyboard_changed = not self._keyboard_changed
     ^^^^^^^^^^^^^^^^^^^^^^
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1639, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1646, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1672, in kivy.properties.AliasProperty._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\core\window\__init__.py", line 1086, in <lambda>
     keyboard_height=lambda *dt: self.update_viewport())
                                 ^^^^^^^^^^^^^^^^^^^^^^
   File "C:\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\kivy\core\window\__init__.py", line 1779, in update_viewport
     projection_mat.view_clip(0.0, w, 0.0, h, -1.0, 1.0, 0)
   File "kivy\graphics\transformation.pyx", line 275, in kivy.graphics.transformation.Matrix.view_clip
   File "kivy\graphics\transformation.pyx", line 301, in kivy.graphics.transformation.Matrix.view_clip
 ValueError: invalid frustrum
```

Strangely enough this error does not occur on and it also scales the label text there:
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Kivy v2.2.0.dev0

**Comment by misl6** [comment]
Hi @Code4SAFrankie , which commit of `2.2.0.dev0` are you using?

**Comment by Code4SAFrankie** [comment]
Where would I see that?

**Comment by Julian-O** [comment]
@Code4SAFrankie: If you cloned the git repository, you could change into that directory and type `git log`. We need the top entry.

**Comment by Code4SAFrankie** [comment]
> @Code4SAFrankie: If you cloned the git repository, you could change into that directory and type `git log`. We need the top entry.

I don't git. I would have used `python -m pip install "kivy[base] @ https://github.com/kivy/kivy/archive/master.zip"`

**Comment by Code4SAFrankie** [comment]
Tried it again now (23 Nov 2023 at 11:30 PM GMT+2) after doing a fresh install with:

`C:\WPy64-31150\python-3.11.5.amd64>.\python.exe -m pip install "kivy[base]" kivy_examples`

and

`.\python.exe -m pip install kivymd`

and get this error:

```
[INFO   ] [Logger      ] Record log in C:\Users\User\.kivy\logs\kivy_23-11-23_1.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\WPy64-31150\python-3.11.5.amd64\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 546.17'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1080/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "d:\EBackup\Work\Python\kivy\fontscale2\main.py", line 32, in <module>
     TestApp().run()
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\core\window\__init__.py", line 648, in _upd_kbd_height
     self._keyboard_changed = not self._keyboard_changed
     ^^^^^^^^^^^^^^^^^^^^^^
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "kivy\properties.pyx", line 1639, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1646, in kivy.properties.AliasProperty.trigger_change
   File "kivy\properties.pyx", line 1672, in kivy.properties.AliasProperty._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\core\window\__init__.py", line 1086, in <lambda>
     keyboard_height=lambda *dt: self.update_viewport())
                                 ^^^^^^^^^^^^^^^^^^^^^^
   File "C:\WPy64-31150\python-3.11.5.amd64\Lib\site-packages\kivy\core\window\__init__.py", line 1779, in update_viewport
     projection_mat.view_clip(0.0, w, 0.0, h, -1.0, 1.0, 0)
   File "kivy\graphics\transformation.pyx", line 275, in kivy.graphics.transformation.Matrix.view_clip
   File "kivy\graphics\transformation.pyx", line 301, in kivy.graphics.transformation.Matrix.view_clip
 ValueError: invalid frustrum
```
