### ISSUE TITLE
ffpyplayer type error

### ISSUE THREAD

**Issue by cagsurgunu** [kivy/kivy#8390]
**Software Versions**
* Python: 3.10
* OS: Windows
* Kivy:2.1.1
* Kivy installation method: pip

Hello, i write a program with ffpyplayer for iptv. Sometimes iptv channels can have mistake url. if all urls are correct, channel switching(change filename) works perfect. but if there is a mistake url, my kivy app crash.
i get  Error :  TypeError: expected bytes, NoneType found. 
Can i except this error?

**Comment by misl6** [comment]
Can you please post the full log?

**Comment by cagsurgunu** [comment]
> Can you please post the full l


> Can you please post the full log?

Exception has occurred: AttributeError
'NoneType' object has no attribute 'startswith'
  File "D:\iptv\iptv_android\test1.py", line 140, in <module>
    AndroidIP_TV().run()
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by misl6** [comment]
Hi @cagsurgunu ,

Unfortunately, the provided log is not enough to triage the issue, can you please provide more? (the full output)

**Comment by cagsurgunu** [comment]
> nately, the provided log is not enou

misl6 thank you very much. i change my code for this problem. So i can't get all error. But i change again old code. if i change to old i will get and send logs to you.

**Comment by cagsurgunu** [comment]
details logs are below:
Traceback (most recent call last):
   File "C:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "C:\Python\Python39\lib\runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "c:\Users\omer.yildirim\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
     cli.main()
   File "c:\Users\omer.yildirim\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
     run()
   File "c:\Users\omer.yildirim\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
     runpy.run_path(target, run_name="__main__")
   File "c:\Users\omer.yildirim\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
     return _run_module_code(code, init_globals, run_name,
   File "c:\Users\omer.yildirim\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
     _run_code(code, mod_globals, init_globals,
   File "c:\Users\omer.yildirim\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
     exec(code, run_globals)
   File "D:\projeler\iptv\iptv_android\test1.py", line 134, in <module>
     AndroidIP_TV().run()
   File "C:\Python\Python39\lib\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "C:\Python\Python39\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Python\Python39\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Python\Python39\lib\site-packages\kivy\base.py", line 391, in idle
     Clock.tick_draw()
   File "C:\Python\Python39\lib\site-packages\kivy\clock.py", line 783, in tick_draw
     self._process_events_before_frame()
   File "kivy\_clock.pyx", line 662, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 708, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 704, in kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Python\Python39\lib\site-packages\kivy\uix\video.py", line 227, in _do_video_load
     self._video.play()
   File "C:\Python\Python39\lib\site-packages\kivy\core\video\video_ffpyplayer.py", line 397, in play
     'paused': not self._is_stream,
   File "C:\Python\Python39\lib\site-packages\kivy\core\video\video_ffpyplayer.py", line 124, in _is_stream
     return self.filename.startswith('rtsp://')
