### ISSUE TITLE
kivy/core/image/img_imageio.pyx:333:8: Operation only allowed in c++

### ISSUE THREAD

**Issue by alexg93333** [kivy/kivy#8635]
After deleting the buildozer folder (it became too large after some time and experiments) and trying to recompile my project cleanly, suddenly I get this exception:

running command:  buildozer -v android debug 

.spec
requirements = python3,kivy==master,numpy,opencv
android.api = 34
android.minapi = 24
android.archs  = arm64-v8a, armeabi-v7a

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1256, in <module>
    main()
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 685, in __init__
    getattr(self, command)(args)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 104, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 163, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 504, in build_recipes
    recipe.build_arch(arch)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1031, in build_arch
    self.build_cython_components(arch)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1056, in build_cython_components
    self.cythonize_build(env=env)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/kivy/__init__.py", line 38, in cythonize_build
    super().cythonize_build(env, build_dir=build_dir)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1104, in cythonize_build
    self.cythonize_file(env, build_dir, join(root, filename))
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/kivy/__init__.py", line 59, in cythonize_file
    super().cythonize_file(env, build_dir, filename)
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 1093, in cythonize_file
    shprint(python_command, "-c"
  File "/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/dockerpaddle/.local/lib/python3.10/site-packages/sh.py", line 915, in next
    self.wait()
  File "/home/dockerpaddle/.local/lib/python3.10/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/dockerpaddle/.local/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/dockerpaddle/.pyenv/shims/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./kivy/core/image/img_imageio.pyx

  STDOUT:
/home/dockerpaddle/.local/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/kivy/armeabi-v7a__ndk_target_24/kivy/kivy/core/image/img_imageio.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...

cdef class _ImageIOInterface:
    cdef KivyImageIOProvider* _provider

    def __cinit__(self):
        self._provider = new KivyImageIOProvider()
                            ^
------------------------------------------------------------

kivy/core/image/img_imageio.pyx:330:29: Operation only allowed in c++

Error compiling Cython file:
------------------------------------------------------------
...

    def __cinit__(self):
        self._provider = new KivyImageIOProvider()

    def __dealloc__(self):
        del self._provider
       ^
------------------------------------------------------------

kivy/core/image/img_imageio.pyx:333:8: Operation only allowed in c++

  STDERR:

# Command failed: ['/usr/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=imagefinder', '--bootstrap=sdl2', '--requirements=python3,kivy==2.3.0,numpy,opencv', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/home/dockerpaddle/Desktop/imagefinder/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=24', '--ignore-setup-py', '--debug']

**Comment by alexg93333** [comment]
After changing the requirement to  just "kivy" it successfully compiles now

**Comment by misl6** [comment]
If someone stumbles upon this:

Please note that we started breaking things for development of Kivy `3.0.0`, so building `kivy==master` may not work and it's highly discouraged.

When the next version of Kivy will be available for testing and migrating your apps, we will send out a notification on our [Discord chat](https://chat.kivy.org), [website](https://www.kivy.org) and [x.com](https://x.com/kivyframework)
