### ISSUE TITLE
Pyinstaller 6.5.0 not working with Kivy 2.3.0

### ISSUE THREAD

**Issue by ikus060** [kivy/kivy#8653]
**Software Versions**
* Python: 3.10
* OS: Linux
* Kivy: 2.3.0
* Kivy installation method: pip install kivy

**Describe the bug**

When trying to create a package using Pyinstaller, the hooks is failling with this error.  This problem was also repported in this discussion: https://github.com/orgs/kivy/discussions/1

**Expected behavior**

I'm expecting recent version of Pyinstaller to be working with Kivy.

**To Reproduce**

min.py:
```
# Importing required libraries
import kivy
from kivy.app import App
from kivy.uix.label import Label

# Defining the App class
class MinimalApp(App):
    def build(self):
        # Creating a Label widget
        label = Label(text="Hello, Minimal Kivy App!")
        return label

# Running the application
if __name__ == "__main__":
    MinimalApp().run()
```

Run pyinstaller command:
```
pyinstaller min.py
```

Here the full log of this problem:
```
$ pyinstaller min.py
89 INFO: PyInstaller: 6.5.0, contrib hooks: 2024.3
89 INFO: Python: 3.10.12
90 INFO: Platform: Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35
90 INFO: wrote /home/ikus060/workspace/PDSL/minarca.git/min.spec
98 INFO: Extending PYTHONPATH with paths
['/home/ikus060/workspace/PDSL/minarca.git']
141 INFO: Kivy: v2.3.0
141 INFO: Logger: Record log in /home/ikus060/.kivy/logs/kivy_24-03-21_10.txt
[INFO   ] [Logger      ] Record log in /home/ikus060/.kivy/logs/kivy_24-03-21_10.txt
[INFO   ] [Kivy        ] v2.3.0
141 INFO: Kivy: Installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Kivy        ] Installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/__init__.py"
141 INFO: Python: v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
[INFO   ] [Python      ] v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
141 INFO: Python: Interpreter at "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/python"
[INFO   ] [Python      ] Interpreter at "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/python"
141 INFO: Logger: Purge log fired. Processing...
[INFO   ] [Logger      ] Purge log fired. Processing...
141 INFO: Logger: Purge finished!
[INFO   ] [Logger      ] Purge finished!
142 INFO: KivyMD: 2.0.1.dev0, git-2f26dcc, 2024-03-14 (installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivymd/__init__.py")
[INFO   ] [KivyMD      ] 2.0.1.dev0, git-2f26dcc, 2024-03-14 (installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivymd/__init__.py")
143 INFO: Factory: 195 symbols loaded
[INFO   ] [Factory     ] 195 symbols loaded
165 INFO: Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
168 INFO: Text: Provider: sdl2
[INFO   ] [Text        ] Provider: sdl2
208 INFO: Window: Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
387 INFO: GL: Using the "OpenGL" graphics system
[INFO   ] [GL          ] Using the "OpenGL" graphics system
388 INFO: GL: Backend used <sdl2>
[INFO   ] [GL          ] Backend used <sdl2>
388 INFO: GL: OpenGL version <b'4.6 (Compatibility Profile) Mesa 24.0.0-1pop0~1706872735~22.04~0fa430c'>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 24.0.0-1pop0~1706872735~22.04~0fa430c'>
388 INFO: GL: OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
388 INFO: GL: OpenGL renderer <b'Mesa Intel(R) Graphics (ADL GT2)'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) Graphics (ADL GT2)'>
388 INFO: GL: OpenGL parsed version: 4, 6
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
388 INFO: GL: Shading version <b'4.60'>
[INFO   ] [GL          ] Shading version <b'4.60'>
388 INFO: GL: Texture max size <16384>
[INFO   ] [GL          ] Texture max size <16384>
389 INFO: GL: Texture max units <32>
[INFO   ] [GL          ] Texture max units <32>
413 INFO: Window: auto add sdl2 input provider
[INFO   ] [Window      ] auto add sdl2 input provider
414 INFO: Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
415 DEBUG: discover_hook_directories: Hook directories: ['/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/flet/__pyinstaller', '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivymd/tools/packaging/pyinstaller', '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks', '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks']
[DEBUG  ] [discover_hook_directories] Hook directories: ['/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/flet/__pyinstaller', '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivymd/tools/packaging/pyinstaller', '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks', '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks']
615 INFO: checking Analysis
615 INFO: Building Analysis because Analysis-00.toc is non existent
615 INFO: Initializing module dependency graph...
615 INFO: Caching module graph hooks...
621 INFO: Analyzing base_library.zip ...
913 INFO: Loading module hook 'hook-heapq.py' from '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/hooks'...
944 INFO: Loading module hook 'hook-encodings.py' from '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/hooks'...
1180 INFO: Loading module hook 'hook-pickle.py' from '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/hooks'...
1937 INFO: Caching module dependency graph...
1974 INFO: Running Analysis Analysis-00.toc
1974 INFO: Looking for Python shared library...
1987 INFO: Using Python shared library: /lib/x86_64-linux-gnu/libpython3.10.so.1.0
1987 INFO: Analyzing /home/ikus060/workspace/PDSL/minarca.git/min.py
1992 INFO: Loading module hook 'hook-kivy.py' from '/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/hooks'...
1997 INFO: Kivy: v2.3.0
1997 INFO: Logger: Record log in /home/ikus060/.kivy/logs/kivy_24-03-21_11.txt
[INFO   ] [Logger      ] Record log in /home/ikus060/.kivy/logs/kivy_24-03-21_11.txt
[INFO   ] [Kivy        ] v2.3.0
1997 INFO: Kivy: Installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Kivy        ] Installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/__init__.py"
1997 INFO: Python: v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
[INFO   ] [Python      ] v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
1997 INFO: Python: Interpreter at "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/python"
[INFO   ] [Python      ] Interpreter at "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/python"
1997 INFO: Logger: Purge log fired. Processing...
[INFO   ] [Logger      ] Purge log fired. Processing...
1998 INFO: Logger: Purge finished!
[INFO   ] [Logger      ] Purge finished!
1998 INFO: Factory: 195 symbols loaded
[INFO   ] [Factory     ] 195 symbols loaded
1999 DEBUG: Collecting submodules for kivy.graphics
[DEBUG  ] Collecting submodules for kivy.graphics
[INFO   ] [Logger      ] Record log in /home/ikus060/.kivy/logs/kivy_24-03-21_12.txt
[INFO   ] [Kivy        ] v2.3.0
[INFO   ] [Kivy        ] Installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
[INFO   ] [Python      ] Interpreter at "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
58 INFO: Kivy: v2.3.0
58 INFO: Logger: Record log in /home/ikus060/.kivy/logs/kivy_24-03-21_13.txt
[INFO   ] [Logger      ] Record log in /home/ikus060/.kivy/logs/kivy_24-03-21_13.txt
[INFO   ] [Kivy        ] v2.3.0
58 INFO: Kivy: Installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Kivy        ] Installed at "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/__init__.py"
58 INFO: Python: v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
[INFO   ] [Python      ] v3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
58 INFO: Python: Interpreter at "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/python"
[INFO   ] [Python      ] Interpreter at "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/python"
58 INFO: Logger: Purge log fired. Processing...
[INFO   ] [Logger      ] Purge log fired. Processing...
59 INFO: Logger: Purge finished!
[INFO   ] [Logger      ] Purge finished!
78 INFO: Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
80 DEBUG: collect_submodules - scanning (sub)package kivy.graphics in location(s): ['/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/graphics']
[DEBUG  ] [collect_submodules - scanning (sub)package kivy.graphics in location(s)] ['/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/graphics']
80 DEBUG: collect_submodules - scanning (sub)package kivy.graphics.cgl_backend
[DEBUG  ] collect_submodules - scanning (sub)package kivy.graphics.cgl_backend
81 DEBUG: collect_submodules - scanning (sub)package kivy.graphics.cgl_backend in location(s): ['/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/graphics/cgl_backend']
[DEBUG  ] [collect_submodules - scanning (sub)package kivy.graphics.cgl_backend in location(s)] ['/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/graphics/cgl_backend']
2205 DEBUG: collect_submodules - found submodules: ['kivy.graphics', 'kivy.graphics.boxshadow', 'kivy.graphics.buffer', 'kivy.graphics.cgl', 'kivy.graphics.cgl_backend', 'kivy.graphics.cgl_backend.cgl_debug', 'kivy.graphics.cgl_backend.cgl_gl', 'kivy.graphics.cgl_backend.cgl_glew', 'kivy.graphics.cgl_backend.cgl_mock', 'kivy.graphics.cgl_backend.cgl_sdl2', 'kivy.graphics.compiler', 'kivy.graphics.context', 'kivy.graphics.context_instructions', 'kivy.graphics.fbo', 'kivy.graphics.gl_instructions', 'kivy.graphics.instructions', 'kivy.graphics.opengl', 'kivy.graphics.opengl_utils', 'kivy.graphics.scissor_instructions', 'kivy.graphics.shader', 'kivy.graphics.stencil_instructions', 'kivy.graphics.svg', 'kivy.graphics.tesselator', 'kivy.graphics.texture', 'kivy.graphics.transformation', 'kivy.graphics.vbo', 'kivy.graphics.vertex', 'kivy.graphics.vertex_instructions']
[DEBUG  ] [collect_submodules - found submodules] ['kivy.graphics', 'kivy.graphics.boxshadow', 'kivy.graphics.buffer', 'kivy.graphics.cgl', 'kivy.graphics.cgl_backend', 'kivy.graphics.cgl_backend.cgl_debug', 'kivy.graphics.cgl_backend.cgl_gl', 'kivy.graphics.cgl_backend.cgl_glew', 'kivy.graphics.cgl_backend.cgl_mock', 'kivy.graphics.cgl_backend.cgl_sdl2', 'kivy.graphics.compiler', 'kivy.graphics.context', 'kivy.graphics.context_instructions', 'kivy.graphics.fbo', 'kivy.graphics.gl_instructions', 'kivy.graphics.instructions', 'kivy.graphics.opengl', 'kivy.graphics.opengl_utils', 'kivy.graphics.scissor_instructions', 'kivy.graphics.shader', 'kivy.graphics.stencil_instructions', 'kivy.graphics.svg', 'kivy.graphics.tesselator', 'kivy.graphics.texture', 'kivy.graphics.transformation', 'kivy.graphics.vbo', 'kivy.graphics.vertex', 'kivy.graphics.vertex_instructions']
2219 WARNING: stderr: Traceback (most recent call last):
 Traceback (most recent call last):
2219 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/pyinstaller", line 8, in <module>
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/bin/pyinstaller", line 8, in <module>
2219 WARNING: stderr:     sys.exit(_console_script_run())
     sys.exit(_console_script_run())
2219 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 228, in _console_script_run
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 228, in _console_script_run
2219 WARNING: stderr:     run()
     run()
2219 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 212, in run
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 212, in run
2219 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
     run_build(pyi_config, spec_file, **vars(args))
2219 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 69, in run_build
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 69, in run_build
2220 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
2220 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1139, in main
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1139, in main
2220 WARNING: stderr:     build(specfile, distpath, workpath, clean_build)
     build(specfile, distpath, workpath, clean_build)
2220 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1079, in build
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1079, in build
2220 WARNING: stderr:     exec(code, spec_namespace)
     exec(code, spec_namespace)
2220 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/min.spec", line 4, in <module>
   File "/home/ikus060/workspace/PDSL/minarca.git/min.spec", line 4, in <module>
2220 WARNING: stderr:     a = Analysis(
     a = Analysis(
2220 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 513, in __init__
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 513, in __init__
2221 WARNING: stderr:     self.__postinit__()
     self.__postinit__()
2221 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
2221 WARNING: stderr:     self.assemble()
     self.assemble()
2221 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 651, in assemble
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 651, in assemble
2221 WARNING: stderr:     priority_scripts.append(self.graph.add_script(script))
     priority_scripts.append(self.graph.add_script(script))
2221 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 268, in add_script
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 268, in add_script
2221 WARNING: stderr:     self._top_script_node = super().add_script(pathname)
     self._top_script_node = super().add_script(pathname)
2221 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1160, in add_script
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1160, in add_script
2221 WARNING: stderr:     self._process_imports(n)
     self._process_imports(n)
2221 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2591, in _process_imports
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2591, in _process_imports
2222 WARNING: stderr:     target_modules = self._safe_import_hook(*import_info, **kwargs)
     target_modules = self._safe_import_hook(*import_info, **kwargs)
2222 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 437, in _safe_import_hook
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 437, in _safe_import_hook
2222 WARNING: stderr:     ret_modules = super()._safe_import_hook(
     ret_modules = super()._safe_import_hook(
2222 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2048, in _safe_import_hook
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2048, in _safe_import_hook
2223 WARNING: stderr:     target_modules = self.import_hook(
     target_modules = self.import_hook(
2223 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1232, in import_hook
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1232, in import_hook
2223 WARNING: stderr:     target_package, target_module_partname = self._find_head_package(
     target_package, target_module_partname = self._find_head_package(
2223 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1411, in _find_head_package
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1411, in _find_head_package
2223 WARNING: stderr:     target_package = self._safe_import_module(
     target_package = self._safe_import_module(
2223 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 501, in _safe_import_module
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 501, in _safe_import_module
2223 WARNING: stderr:     return super()._safe_import_module(module_basename, module_name, parent_package)
     return super()._safe_import_module(module_basename, module_name, parent_package)
2223 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1792, in _safe_import_module
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1792, in _safe_import_module
2224 WARNING: stderr:     self._process_imports(n)
     self._process_imports(n)
2224 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2591, in _process_imports
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2591, in _process_imports
2224 WARNING: stderr:     target_modules = self._safe_import_hook(*import_info, **kwargs)
     target_modules = self._safe_import_hook(*import_info, **kwargs)
2224 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 368, in _safe_import_hook
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 368, in _safe_import_hook
2224 WARNING: stderr:     excluded_imports = self._find_all_excluded_imports(source_module.identifier)
     excluded_imports = self._find_all_excluded_imports(source_module.identifier)
2224 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 356, in _find_all_excluded_imports
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 356, in _find_all_excluded_imports
2224 WARNING: stderr:     excluded_imports.update(module_hook.excludedimports)
     excluded_imports.update(module_hook.excludedimports)
2224 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 316, in __getattr__
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 316, in __getattr__
2224 WARNING: stderr:     self._load_hook_module()
     self._load_hook_module()
2224 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 383, in _load_hook_module
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 383, in _load_hook_module
2225 WARNING: stderr:     self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
     self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
2225 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/compat.py", line 583, in importlib_load_source
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/compat.py", line 583, in importlib_load_source
2225 WARNING: stderr:     mod_loader.exec_module(mod)
     mod_loader.exec_module(mod)
2225 WARNING: stderr:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2225 WARNING: stderr:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2225 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/hooks/hook-kivy.py", line 21, in <module>
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/PyInstaller/hooks/hook-kivy.py", line 21, in <module>
2225 WARNING: stderr:     hiddenimports = get_deps_all()['hiddenimports']
     hiddenimports = get_deps_all()['hiddenimports']
2225 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 272, in get_deps_all
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 272, in get_deps_all
2225 WARNING: stderr:     'binaries': _find_gst_binaries(),
     'binaries': _find_gst_binaries(),
2225 WARNING: stderr:   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 370, in _find_gst_binaries
   File "/home/ikus060/workspace/PDSL/minarca.git/.venv/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 370, in _find_gst_binaries
2225 WARNING: stderr:     plugin_deps = bindepend.selectImports(plugin_filepath)
     plugin_deps = bindepend.selectImports(plugin_filepath)
2225 WARNING: stderr: AttributeError: module 'PyInstaller.depend.bindepend' has no attribute 'selectImports'
 AttributeError: module 'PyInstaller.depend.bindepend' has no attribute 'selectImports'
```

**Additional context**

**Comment by AnuragShre** [comment]
when will the fix release ?

**Comment by maltfield** [comment]
Is there any workaround for now?

**Comment by qlrd** [comment]
> Is there any workaround for now?
> 
> Update: as a workaround, I was able to fix my builds by patching my local copy of `site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py` with the changes listed here:
> 
>     * [ikus060@21c7110](https://github.com/ikus060/kivy/commit/21c7110ee79f355d6a42da0a274d2426b1e18665)
> 
> 
> ```
> maltfield@host pyinstaller_hooks % diff __init__.py.old __init__.py
> 81c81,87
> < from PyInstaller.depend import bindepend
> ---
> > #from PyInstaller.depend import bindepend
> > try:
> >     # Pyinstaller >= 6
> >     from PyInstaller.depend.bindepend import get_imports
> > except ImportError:
> >     # Pyinstaller < 6
> >     from PyInstaller.depend.bindepend import selectImports as get_imports
> 370c376,377
> <         plugin_deps = bindepend.selectImports(plugin_filepath)
> ---
> >         #plugin_deps = bindepend.selectImports(plugin_filepath)
> >         plugin_deps = get_imports(plugin_filepath)
> maltfield@host pyinstaller_hooks % 
> ```

@maltfield, I made [scripts for bash and powershell](https://github.com/qlrd/krux-installer/tree/kivy/.ci), inspired in your snippet, to simplify the process until the fix isn't published.

**Comment by Lauszus** [comment]
This was fixed in #8654 and should be closed.
