### ISSUE TITLE
ZeroDivisionError in mouse.py input provider

### ISSUE THREAD

**Issue by massimilianodelliubaldini** [kivy/kivy#8770]
**Software Versions**
* Python: 3.10.0
* OS: Windows 10 22H2
* Kivy: 2.3.0
* Kivy installation method: via pip

**Describe the bug**
The `create_hover` function in mouse.py sets values `nx` and `ny` to divide themselves by `win._density`, which may be zero. When this happens, a stack trace is thrown and the app crashes.

**Expected behavior**
Similar fixes to be applied as described by https://github.com/kivy/kivy/issues/7006#issuecomment-900231781 to prevent the error from being thrown. I'm unaware of downstream impacts of not performing the division at all, just here to report the issue. 

**To Reproduce**
Unable to reproduce as it seems to be intermittent. Reporting on behalf of another user with attached screenshot.

**Code and Logs and screenshots**
![image](https://github.com/kivy/kivy/assets/8584296/5905d53e-c70a-49d7-96a5-f4707f2b0d1e)
![image](https://github.com/kivy/kivy/assets/8584296/57589539-602f-40c7-a8b4-61e49f62fa55)

**Additional context**
Let me know if you need any other details. Thank you!

**Comment by mp-007** [comment]
@massimilianodelliubaldini 

Not 100% sure, but I think sometime GetDpiForWindow can return 0 when there is not valid active window (ex: active window is None)

source:
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow

So, in this case _update_density_and_dpi in window_sld2 will set a _density at 0.
```
    def _update_density_and_dpi(self):
        if platform == 'win':
            from ctypes import windll
            self._density = 1.
            try:
                hwnd = windll.user32.GetActiveWindow()
                self.dpi = float(windll.user32.GetDpiForWindow(hwnd))
                self._density = self.dpi / 96
            except AttributeError:
                pass
        else:
            self._density = self._win._get_gl_size()[0] / self._size[0]
            if self._is_desktop:
                self.dpi = self._density * 96.
```

to fix this, maybe this condition can be made

```
    def _update_density_and_dpi(self):
        if platform == 'win':
            from ctypes import windll
            self._density = 1.
            try:
                hwnd = windll.user32.GetActiveWindow()
                dpi = float(windll.user32.GetDpiForWindow(hwnd))
                if dpi:
                    self.dpi = dpi
                    self._density = self.dpi / 96
            except AttributeError:
                pass
        else:
            self._density = self._win._get_gl_size()[0] / self._size[0]
            if self._is_desktop:
                self.dpi = self._density * 96.
```

I'm experimenting this solution in my app, so if I don't see this error anymore. I will do a PR

**Comment by massimilianodelliubaldini** [comment]
You may want to consider having a default value for `self.dpi`. Before, it would at least be 0, but now it won't be set at all if that `if dpi:` condition fails. `self._density = 1.` is set earlier, so that is at least a decent fallback value (and won't cause ZeroDivisionErrors later on).

**Comment by mp-007** [comment]
like ?
```
self.dpi = self.density*96
```

**Comment by massimilianodelliubaldini** [comment]
My personal style is to always pair an `if` with an `else`. So if it were up to me, it would probably look like this:

```py
if dpi:
    self.dpi = dpi
    self._density = self.dpi / 96
else:
    self.dpi = 96.
    self._density = 1.
```

But that's up to the standards of the kivy project maintainers, the Python style guide, etc. I just intend to close the loophole in your proposal, that's all.

**Comment by kitsiosvas** [comment]
Hello @massimilianodelliubaldini is this issue being handled? I could work on this if not

**Comment by massimilianodelliubaldini** [comment]
I'm not working on it, but @mp-007 might be?

**Comment by mp-007** [comment]
@kitsiosvas If you have an other approach for solving this, go for it.  For now we have this potential solution but if you think you have something better, please let us know.
```
    def _update_density_and_dpi(self):
        if platform == 'win':
            from ctypes import windll
            self._density = 1.
            try:
                hwnd = windll.user32.GetActiveWindow()
                dpi = float(windll.user32.GetDpiForWindow(hwnd))
                if dpi:
                    self.dpi = dpi
                    self._density = self.dpi / 96
                else:
                    self.dpi = 96.
                    self._density = 1.
            except AttributeError:
                pass
        else:
            self._density = self._win._get_gl_size()[0] / self._size[0]
            if self._is_desktop:
                self.dpi = self._density * 96.

```

**Comment by massimilianodelliubaldini** [comment]
Just realizing the try/catch+pass might skip the if statement altogether, preventing us from setting our default...

So this is probably preferable anyway:

```py
    def _update_density_and_dpi(self):
        if platform == 'win':
            from ctypes import windll
            self.dpi = 96.
            self._density = 1.
            try:
                hwnd = windll.user32.GetActiveWindow()
                dpi = float(windll.user32.GetDpiForWindow(hwnd))
                if dpi:
                    self.dpi = dpi
                    self._density = self.dpi / 96
            except AttributeError:
                pass
        else:
            self._density = self._win._get_gl_size()[0] / self._size[0]
            if self._is_desktop:
                self.dpi = self._density * 96.
```

**Comment by SvenStaehs** [comment]
issue happened to me today:
> [INFO   ] [Kivy        ] v2.3.0
> [...]
> [INFO   ] 2025-04-03 08:04:19.251 [WindowSDL   ] Window is now on display 1
[INFO   ] 2025-04-03 09:33:56.926 [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "devhub\devhub.py", line 204, in <module>
   File "devhub\devhub.py", line 90, in run
   File "kivy\app.py", line 956, in run
   File "kivy\base.py", line 574, in runTouchApp
   File "kivy\base.py", line 341, in mainloop
   File "kivy\core\window\window_sdl2.py", line 714, in mainloop
   File "kivy\core\window\window_sdl2.py", line 814, in _collide_and_dispatch_cursor_enter
   File "kivy\core\window\window_sdl2.py", line 544, in _fix_mouse_pos
   File "kivy\\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\\properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy\\properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy\\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "kivy\input\providers\mouse.py", line 399, in begin_or_update_hover_event
   File "kivy\input\providers\mouse.py", line 312, in create_hover
 ZeroDivisionError: float division by zero
[PYI-24064:ERROR] Failed to execute script 'devhub' due to unhandled exception!
[PYI-33172:WARNING] Failed to remove temporary directory: D:\temp\_MEI331722

PR was never reviewed or even assigned or labeled, maybe writing here pings someone to take a second look? 😬

**Comment by SvenStaehs** [comment]
Oh and I am able to reproduce the issue, thought I'd share it.

Our app has a lengthy startup, so there's some time between window creating (happens when kivy is imported) and populating the window (drawing the content).
1. start application and wait for window to appear
2. move window to second screen (Win+Shift+ArrowKey)
3. immediately remove focus from window by clicking the Desktop before the window has time to load
4. window will load and display content, but not render properly (icons too small, missing text entirely, etc.)
5. move mouse into application window to produce the exception

Here's some logs, truncated too hide internals:
>[INFO   ] [Kivy        ] v2.3.0
[INFO   ] [Kivy        ] Installed at "D:\temp\_MEI251362\kivy\__init__.pyc"
[INFO   ] [Python      ] v3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\adstsv0\bin\devhub.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 31.0.101.4575'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 31.0.101.4575'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] 2025-04-03 11:28:45.491 [BashProcess ] (138014981643) 'C:\Program Files\Git\bin\bash.exe' -c 'command -v git'
[INFO   ] 2025-04-03 11:28:45.608 [BashProcess ] (138014981643) [0:00:00.115884] /mingw64/bin/git
[...] starting some lengthy stuff
[INFO   ] 2025-04-03 11:28:45.997 [Loader      ] using a thread pool of 2 workers
[INFO   ] 2025-04-03 11:28:46.003 [GL          ] NPOT texture support is available
[...] still going
[INFO   ] 2025-04-03 11:28:50.387 [Base        ] Start application main loop
[INFO   ] 2025-04-03 11:28:51.888 [WindowSDL   ] Window is now on display 2
[...] this is the point at which I'm moving the mouse over
[INFO   ] 2025-04-03 11:28:54.507 [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "devhub\devhub.py", line 204, in <module>
   File "devhub\devhub.py", line 90, in run
   File "kivy\app.py", line 956, in run
   File "kivy\base.py", line 574, in runTouchApp
   File "kivy\base.py", line 341, in mainloop
   File "kivy\core\window\window_sdl2.py", line 605, in mainloop
   File "kivy\\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "kivy\input\providers\mouse.py", line 403, in begin_hover_event
   File "kivy\input\providers\mouse.py", line 312, in create_hover
 ZeroDivisionError: float division by zero
[PYI-41044:ERROR] Failed to execute script 'devhub' due to unhandled exception!


Does you fix also address the issue of incorrect rendering on the second screen?

**Comment by SvenStaehs** [comment]
actually, it's even easier than that, not only during startup... (sorry for the multiple posts in quick succession)

Whenever I move the app to another window and immediately change the focus to a different window (same screen or not) before the kivy app has had time to update its dpi, I get this exception.  
It's possible that a process may only inspect its own windows, so getting the active window and asking for its DPI is considered an "invalid handle" and returns zero as per spec. But correctly handling DPI for multiple screens, when a kivy app might have multiple windows on different screens with different dpi, may be a more in-depth problem... So just assuming a default value might be appropriate, though it would leave the rendering potentially incorrect. Maybe asking for the DPI of the root window would help? This would handle many cases correctly. At least if my assumption about invalid handles is correct.

**Comment by mp-007** [comment]
Hi @SvenStaehs thanks for you analysis.

If you find a better solution, please let's us know. 

For the merging pr #8865, I think kivy developper are waiting kivy 3.0.0 to fix this (it will be SDL3). But I not sure because I didn't have any answer from them.

**Comment by SvenStaehs** [comment]
Your fix is simple, low-impact, and fixes the crash. That's perfect for a patch release in my book.  
The additional concerns I mentioned are minor in comparison, and would not be simple or low-impact to fix 😆

**Comment by massimilianodelliubaldini** [comment]
Given the merge of #9029, looks like we're good to close this one out?
