### ISSUE TITLE
No module named 'kivy._event'

### ISSUE THREAD

**Issue by tirolerstefan** [kivy/kivy#8842]
Hi, I installed the python3-kivy package from the daily builds ppa (deb http://ppa.launchpad.net/kivy-team/kivy-daily/ubuntu mantic main - 3.0.0-dev~daily0+202403031102-5291-pkg338~ubuntu23.10.1) and get the following error (Ubuntu 24.04 Noble, python 3.12).
I also get the issue with 2.3.0 from the stable ppa (deb http://ppa.launchpad.net/kivy-team/kivy/ubuntu mantic main - 2.3.0-0~stable0+202401051425~pkg338~ubuntu23.10.1).

Here is the output when importing the animation part:

```
$ python3
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from kivy import animation
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/lib/python3/dist-packages/kivy/animation.py", line 88, in <module>
     from kivy.event import EventDispatcher
   File "/usr/lib/python3/dist-packages/kivy/event.py", line 8, in <module>
     import kivy._event
 ModuleNotFoundError: No module named 'kivy._event'
 ```
 
How can this be solved?
Thanks!

**Comment by kuzeyron** [comment]
Try running pip instead. Or is it important to use ppa?
