### ISSUE TITLE
Kivy unable to read file alias image

### ISSUE THREAD

**Issue by perceptualJonathan** [kivy/kivy#8843]
**Software Versions**
* Python: 3.12
* OS: MacOS 12.7.4
* Kivy: 2.3
* Kivy installation method: pip

**Describe the bug**
If an image file has an alias associated with it, attempting to read the alias location is met with an error.

**Expected behavior**
When loading an image, either by the direct location or by alias, the image loads properly and is rendered.

**To Reproduce**
from kivy.uix.image import Image
im = Image(source='/path/to/alias')

**Code and Logs and screenshots**
```python
[ERROR  ] [Image       ] Error loading </path/to/alias>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/kivy/uix/image.py", line 362, in set_texture_from_resource
    self._coreimage = image = CoreImage(
                              ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/kivy/core/image/__init__.py", line 562, in __init__
    self.filename = arg
    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/kivy/core/image/__init__.py", line 755, in _set_filename
    image = ImageLoader.load(
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/kivy/core/image/__init__.py", line 461, in load
    im = loader(filename, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/kivy/core/image/__init__.py", line 223, in __init__
    self._data = self.load(filename)
                 ^^^^^^^^^^^^^^^^^^^
  File "kivy/core/image/img_imageio.pyx", line 333, in kivy.core.image.img_imageio.ImageLoaderImageIO.load
  File "kivy/core/image/img_imageio.pyx", line 157, in kivy.core.image.img_imageio.load_image_data
ValueError: No image to load at b'/path/to/alias'
```

**Comment by kuzeyron** [comment]
Is this still a problem?

**Comment by perceptualJonathan** [comment]
@kuzeyron Yes, when attempting to load an aliased image, the above issue persists.

**Comment by kuzeyron** [comment]
> @kuzeyron Yes, when attempting to load an aliased image, the above issue persists.

Can you share the code you are using with CoreImage?

**Comment by perceptualJonathan** [comment]
```
from kivy.core.image import Image as CoreImage
im = CoreImage('/path/to/alias')
```

Output: `ValueError: No image to load at b'/path/to/alias'`

If I call
```
from kivy.core.image import Image as CoreImage
im = CoreImage('/path/to/original')
```

That works without error.

**Comment by Cheaterman** [comment]
What's an alias ?
